AliceO2Group/AliceO2

- CCDB/CMakeLists.txt
- CCDB/README.md
- CCDB/include/CCDB/BasicCCDBManager.h
- CCDB/include/CCDB/CcdbApi.h
- CCDB/src/BasicCCDBManager.cxx
- CCDB/src/CCDBLinkDef.h
- CCDB/src/CcdbApi.cxx
- Common/SimConfig/include/SimConfig/SimConfig.h
- Common/SimConfig/src/SimConfig.cxx
- macro/o2sim.C
Introduce BasicCCDBManager as convenience access to CCDB
* minimalistic singleton accessor to CCDB (having transport MC in mind)
- for the moment read-only
* make o2-sim configurable to use a specific timestamp (for anchoring) and
to set a specific CCDB URL
This then provides a significant step foward. Henceforth, detectors
can query the CCDB easily to setup the transport simulation according
to the conditions at the achoring time.
> Introduce BasicCCDBManager as convenience access to CCDB

- DataFormats/Detectors/EMCAL/include/DataFormatsEMCAL/Cell.h
- DataFormats/Detectors/EMCAL/include/DataFormatsEMCAL/Constants.h
- DataFormats/Detectors/EMCAL/include/DataFormatsEMCAL/Digit.h
- DataFormats/Detectors/EMCAL/src/Cell.cxx
- DataFormats/Detectors/EMCAL/src/DataFormatsEMCALLinkDef.h
- DataFormats/Detectors/EMCAL/src/Digit.cxx
Adding getters and setters for cell type to
digits so that the interface between the
two objects is compatible. This is of
relevance for components forseen to work
with both object types.
In addition: Use o2::emcal::ChannelType_t for
channel type information.
> [EMCAL-609] Port setters/getters for cell type to Digits

- CCDB/CMakeLists.txt
This was disabled in the past and got activated by accident
in a recent commit.
(There is still a non-understood problem on Mac).
> Disable CCDB unit test on Mac

- Detectors/ITSMFT/ITS/macros/test/CheckClusters.C
- Detectors/ITSMFT/ITS/macros/test/run_buildTopoDict_its.C
CheckClusters.C now uses MC2ROFRecord to relate hits with clusters
run_buildTopoDict_its.C was using old MCCompLabel convention
> Speedup of CheckClusters.C and fix in run_buildTopoDict_its.C

- Utilities/O2Device/include/O2Device/Compatibility.h
You want to stop running when there is a new state pending.
Thanks Taku Gunji for reporting the issue with this.
> Correct the return value in o2::compatibility::FairMQ13::IsRunning()

- DataFormats/Detectors/EMCAL/CMakeLists.txt
- DataFormats/Detectors/EMCAL/include/DataFormatsEMCAL/Cell.h
- DataFormats/Detectors/EMCAL/src/Cell.cxx
- DataFormats/Detectors/EMCAL/test/testCell.cxx
Remove multiplication by 16 which worsened
the precision in energy. Now the precision
is set to 15.3 MeV, reflecting a range
from 0 - 250 GeV coded in 13 bits.
In addition: Unit test for cell class
(EMCAL-572) - A. Knospe.
> [EMCAL-551, EMCAL-572] Fix precision in energy bits

- Detectors/TPC/workflow/src/ClusterDecoderRawSpec.cxx
- Detectors/TPC/workflow/src/ClustererSpec.cxx
- Detectors/TPC/workflow/src/PublisherSpec.cxx
Filename can now contain %d format specifier which will be replaced by formatted
sector number.
Improving log messages
> Extending TPC workflow publisher to read sector data from multiple files

- Detectors/ITSMFT/common/simulation/src/Digitizer.cxx
Hi @iouribelikov 
This PR mostly fixes the problem w/o any fudge factors (thanks for the hint). The top/bottom plot is dz vs Z/R for Lr0 before/after the fix: 
(the asymmetry in z/r is because I was using 19 events with random vertex, also, z/r in this case does not really give the tg(lambda)). 
The remaining diagonal bands after the correction are due to the single pixel clusters.
The reason of the bias was in different boundaries of the sensor (+11:-19 \mum) and response object (+25:-20 \mum) depth dimensions. Note there is still an internal inconsistency: Miko's object has non-0 response over the whole depth while the transport by the construction of 30\um sensors produces hit start/stop positions in these +11:-19 range. Now I "align" the coordinate of the sensor surface with the …
> Fix: account for diff.spans of response and sensor depths

- cmake/O2DefineOptions.cmake
- cmake/rootcling_wrapper.sh.in
The root cling wrapper dumps all output to a log file, but the errors should
also appear in the build log, especially important to have the complete log for
running the CI.
Also making ENABLE_CASSERT a cmake option, default OFF
> Make sure to print out the errors from root cling

- Common/MathUtils/include/MathUtils/MathBase.h
- Detectors/TPC/calibration/SpacePoints/include/SpacePoints/SpacePointsCalibParam.h
- Detectors/TPC/calibration/SpacePoints/include/SpacePoints/TrackResiduals.h
- Detectors/TPC/calibration/SpacePoints/src/SpacePointCalibLinkDef.h
- Detectors/TPC/calibration/SpacePoints/src/TrackResiduals.cxx
- Bugfix: insertion sort in roFunc was not working properly
- additional debugging options -> single vector can be dumped to TTree
- fix method to retrieve pad row id from x-position
- fix findVoxelBin method
- remove unnecessary parameters from TPC space point calibration parameters class
- Double precision in LTMUnbinnedSig for AliRoot compatibility
- Make LTMUnbinned method better readable
- Use STL function nth_element instead of selectKthMin
- Make voxel flags the same as in AliRoot version
> Add variable y/x and z/x binning options and more

- Common/SimConfig/include/SimConfig/SimConfig.h
- Common/SimConfig/src/SimConfig.cxx
- Generators/CMakeLists.txt
- Generators/include/Generators/GeneratorHepMC.h
- Generators/src/GeneratorFactory.cxx
- Generators/src/GeneratorHepMC.cxx
- Generators/src/GeneratorsLinkDef.h
- dependencies/FindHepMC.cmake
- dependencies/O2SimulationDependencies.cmake
This PR implements an interface to HepMC files to be used within the o2 simulation.
Usage via the `o2-sim` executable is possible 
```o2-sim -g hepmc --HepMCFile thefilename.hepmc```
It is not mandatory to update `alidist` to have this code compiled.
On the other hand, https://github.com/alisw/alidist/pull/1813 solves a ROOT warning (possibly harmless).
> GeneratorHepMC: a HepMC interface to simulation

- DataFormats/simulation/CMakeLists.txt
- DataFormats/simulation/include/SimulationDataFormat/MCTruthContainer.h
- DataFormats/simulation/src/CustomStreamers.cxx
- DataFormats/simulation/src/SimulationDataLinkDef.h
- DataFormats/simulation/test/testMCTruthContainer.cxx
The MCLabelContainer has two vectors of messageable type which do not need to be root serialized.
For the moment, flattening always requires a copy, but the data can be directly copied
to the message resource. The prototype can be extended later to use multiple parts as allowed by the
DataHeader.
Restore can be done using spectator memory resources for the two regions of the input buffer, but this kind of memory resource needs to be implemented. For the moment we have a copy also here.
The DPL I/O API will be extended to use the custom methods for flatten/restore. In the end its not much different then the BOOST serialization concept, but we have the option to optimize this by using polymorphic memory resources and allocators.
TODO before merging:
This concept can be extended to a generic …
> Optimizations to the streaming of MCTruthContainer

- Common/MathUtils/include/MathUtils/Utils.h
- GPU/CMakeLists.txt
- GPU/Common/GPUDefConstantsAndSettings.h
- GPU/GPUTracking/Base/GPUParam.cxx
- GPU/GPUTracking/Base/GPUReconstruction.cxx
- GPU/GPUTracking/Base/GPUReconstruction.h
- GPU/GPUTracking/Base/GPUReconstructionConvert.cxx
- GPU/GPUTracking/Base/GPUReconstructionConvert.h
- GPU/GPUTracking/Base/hip/GPUReconstructionHIP.hip.cxx
- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/Global/GPUChainTracking.h
- GPU/GPUTracking/Merger/GPUTPCGMBorderTrack.h
- GPU/GPUTracking/Merger/GPUTPCGMMerger.cxx
- GPU/GPUTracking/Merger/GPUTPCGMMerger.h
- GPU/GPUTracking/Standalone/display/GPUDisplayKeys.cxx
- GPU/GPUTracking/Standalone/qa/GPUQA.cxx
- GPU/GPUTracking/Standalone/qa/GPUQA.h
- GPU/GPUTracking/Standalone/qconfigoptions.h
- GPU/GPUTracking/Standalone/standalone.cxx
@shahor02 : That cleans up the outliers, but we also loose some CE crossing tracks in general.
I'll have to check how much one can recover. But actually the track parameters before the merging are not exactly good.
Of course we could refit beforehand, but that would take quite some time. Might be a strategy for asynchronous though, where we might have GPU resources left anyway.
New plot below:
> More cuts on track merging, should clean up bogus CE-crossing tracks

- Detectors/ITSMFT/ITS/macros/test/CheckTracks.C
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/Cluster.h
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/Constants.h
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/IndexTableUtils.h
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/MathUtils.h
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/PrimaryVertexContext.h
- Detectors/ITSMFT/ITS/tracking/src/Cluster.cxx
- Detectors/ITSMFT/ITS/tracking/src/PrimaryVertexContext.cxx
- macro/run_trac_ca_its.C
I prepared this PR with @sgorbuno who kindly offered help in speeding up some of the routines in the tracking. This time the initialisation was optimised as well as the performance macro (CheckTracks.C) and our own steering macro.
In the new version of the steering macro there is also an example of the 2(n) iterations tracking. I still have to port the full param set of the second iteration from AliRoot, it will come in a second PR.
> [ITS] Speed-up CA initialisation + 2 iteration tracking example

- Framework/Foundation/CMakeLists.txt
- Framework/Foundation/include/Framework/FunctionalHelpers.h
- Framework/Foundation/test/test_FunctionalHelpers.cxx
This allows retrieving the N-th element of a parameter pack stored
inside a `framework::pack<Args...>`.
> DPL Analysis: add pack_element helper

- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/V3Layer.h
- Detectors/ITSMFT/ITS/simulation/src/V3Layer.cxx
The OB Space Frame Connectors on SIdes A and C were implemented in geometry following the latest blueprints. A new method was introduced in V3Layer to create them, while the method creating the Space Frame itself was revised to avoid fake overlaps and extrusions with the air container. Finally the code was cleaned a bit by deleting commented instructions that were not used anymore.
> Implement OB Space Frame connectors in geometry

- CCDB/test/testCcdbApi.cxx
With the removal of store and retrieve from CcdbApi it is not needed anymore and actually was broken since I cleaned up the ccdb-test.
> Remove outdated test

- Framework/Core/test/benchmark_ASoA.cxx
Missing `;` leads to a compilation syntax error for me. No idea why it passes the CI. Anyhow, this is a typo and should be fixed. @ktf
> Fix Typo in Framework Test

- Detectors/TPC/reconstruction/include/TPCReconstruction/HardwareClusterDecoder.h
- Detectors/TPC/reconstruction/src/HardwareClusterDecoder.cxx
This caused the problem in the wrong MC labels associated to clusters,
resulting in quite many fake track flags.
> fix wrong passing by value instead of reference

- Common/SimConfig/include/SimConfig/SimConfig.h
- Common/SimConfig/src/SimConfig.cxx
- macro/build_geometry.C
@strogolo : with this PR you can set the field during the simulation, particularly, for 0 field use
``o2-sim --field 0``, for reduced 2 kGauss: `` --field 2`` etc. Defualt is ``-5`` corresponding to -30kA in the L3.
> add option to set the field in o2-sim

- GPU/Common/GPUCommonLogger.h
This hopefully fixes the problem with the GPU CI.
> GPU: Fix AMD HIP when there is an old GCC on the system, apparently chooses wrong ABI

- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/RawPixelReader.h
- macro/run_digi2raw_its.C
- macro/run_digi2raw_mft.C
Relevant for digit->raw conversion only
> Fix to prevent overflow in rdh.memorySize assignment

- CCDB/include/CCDB/CcdbApi.h
- CCDB/src/CcdbApi.cxx
This will simplify reusing the same method for DPL Lifetime::Condition.
> CCDB: make extractFromTFile helper a static method

- Generators/src/GeneratorFromFile.cxx
The TParticle in the AliRoot Kinematics.root tree should be considered as trackable if
it has no bit 4 set (AliStack::kDoneBit) and GetStatusCode()<=1
@strogolo : with this fix muons from AliGenCosmicsParam will be transported.
> Fix Trackable def. of AliRoot TParticles

- cmake/O2AddTestWrapper.cmake
- tests/tests-wrapper.sh.in
The original patch did not compute the hard ctest timeout correctly,
since the ctest was not aware of the override of the number of
attempts
> Fix 3 attempts for all ctests override

- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/ChipMappingMFT.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/RawPixelReader.h
- Detectors/ITSMFT/common/reconstruction/src/ChipMappingMFT.cxx
A 13th type of RU is introduced, in order to take into account two different RUs with quite similar configuration.
Finally there was a bug in the MFT mapping and not a problem of the common RawPixelReader which produced strange results at decoding.
There is a test done in the common RawPixelReader which is particular to the ITS mapping, while it is very verbose for the case of the MFT: I have introduced a condition according to the name of the mapping used.
@shahor02 I have a question, in this common template there are few places where the mapping is explicitly written ChipMappingITS. Apparently it does not harm when the template is instantiated with the MFT mapping.
> MFT: introduce the 13th type of RU and fix a bug in the mapping

- Framework/Core/include/Framework/Kernels.h
Code checker complains otherwise.
> DPL: drop support for arrow < 0.14

- Detectors/ITSMFT/ITS/macros/test/CheckCOG.C
Fill the distribution of differences between the COG position of full and compact clusters with the correct values (x and z were identical).
> Fix bug in CheckCOG.C

- Framework/AnalysisTutorial/CMakeLists.txt
- Framework/AnalysisTutorial/src/histograms.cxx
- Framework/Core/include/Framework/AnalysisTask.h
- Framework/Core/include/Framework/HistogramRegistry.h
- Framework/Core/include/Framework/OutputSpec.h
- Framework/Core/src/OutputSpec.cxx
* Rename to OutputManager since we will use it also for histograms.
* Add hook to finalize objects.
* Provide initial implementation for histograms.
> DPL Analysis: rework OutputAppender API

- Detectors/ITSMFT/ITS/simulation/src/V3Layer.cxx
The visibility of the air volumes containing the OB Space Frame was changed to False in order to easier visualize the staves and the layers.
> Change visibility for OB Space Frame containers

- Detectors/EMCAL/workflow/CMakeLists.txt
- Detectors/EMCAL/workflow/include/EMCALWorkflow/CellConverterSpec.h
- Detectors/EMCAL/workflow/include/EMCALWorkflow/DigitsPrinterSpec.h
- Detectors/EMCAL/workflow/include/EMCALWorkflow/RecoWorkflow.h
- Detectors/EMCAL/workflow/src/CellConverterSpec.cxx
- Detectors/EMCAL/workflow/src/DigitsPrinterSpec.cxx
- Detectors/EMCAL/workflow/src/RecoWorkflow.cxx
- Detectors/EMCAL/workflow/src/emc-reco-workflow.cxx
- Add digits converter spec converting digits to
cells
- Convert digits printer spec (example payload task)
to DPL task
- Add writer spec for cells
- Integrate cell converter and cell writer spec in the
EMCAL reconstruction workflow
-  Make digits printer spec optional (for debugging)
> [EMCAL-548,EMCAL-612] Integration of digits converter in EMCAL workflow

- Detectors/TRD/base/include/TRDBase/Digit.h
- Detectors/TRD/base/include/TRDBase/MCLabel.h
- Detectors/TRD/simulation/include/TRDSimulation/Digitizer.h
- Detectors/TRD/simulation/src/Digitizer.cxx
Labels are implemented for the TRD. This PR proposes using one label per hit, each label contains the usual MC label info + if the hit generated a digit or not and how many digits. In parallel, each digit now contains a short that corresponds to the label index to track down multiple digits originated from the same hit.
To keep the label index during the processing of hits an augmented arrayadc is used temporarily. Here, the last array value contains the label index (as an extra time bin, not used for an adc value, but for the label index). The ArrayADC sent in the digit container remains the same, and the label index is new member in the digit class too.
https://alice.its.cern.ch/jira/browse/O2-847.
> TRD MC Labels O2-847

- DataFormats/Detectors/Common/CMakeLists.txt
Need to add direct dependency to `O2::GPUCommon` so that other targets using
`O2::DetectorsCommonDataFormats` can use correct dependencies
> O2-843 Sorting out dependencies for DataFormats/Detectors/Common

- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
- Detectors/ITSMFT/ITS/simulation/src/V3Layer.cxx
In view of the implementation of the MB/OB Support Wheels, some changes were needed to host them and avoid fake overlaps or extrusions with the air containers. Namely:
- the OB Wrapper Volume was extended in Z
- the MB Wrapper Volume was extended in Z and its shape changed from a simple Tube to a properly crafted Pcon to avoid fake overlaps with the MFT elements
- the top vertices of the Space Frame were reduced to their actual length (they were erroneously too long)
- the air volume containing the end part of the Space Frame was differently shaped to avoid fake overlaps with the support wheels
The actual wheels are not included in this PR: they will be part of a separate PR.
> Updates to wrapper volumes and containers for hosting the OB Support Wheels

- Common/SimConfig/include/SimConfig/ConfigurableParam.h
- Common/SimConfig/src/ConfigurableParam.cxx
- Generators/CMakeLists.txt
- Generators/include/Generators/QEDGenParam.h
- Generators/share/external/QEDLoader.C
- Generators/share/external/QEDepem.C
- Generators/share/external/README.md
- Generators/src/GeneratorsLinkDef.h
- Generators/src/QEDGenParam.cxx
- cmake/O2RootMacroExclusionList.cmake
- dependencies/O2SimulationDependencies.cmake
QED generator can be invoked as o2-sim -g extgen --extGenFile $O2_ROOT/share/Generators/external/QEDLoader.C with additional options provided via QEDGenParam key/value wrapper class. 
On execution qedgenparam.ini file will be written with used options + estimated x-section of the process, to be used for QED weighting wrt. the hadronic process during digitization
@sawenzel the 1st commit adds to the ConfigurableParam.writeINI and writeJSON an option to write only a particular top object key (by default all objects are dumped, as before).
> Param/INI file and loader for QED e+e- generator

- Detectors/TPC/simulation/CMakeLists.txt
- Detectors/TPC/simulation/include/TPCSimulation/CommonMode.h
- Detectors/TPC/simulation/include/TPCSimulation/DigitContainer.h
- Detectors/TPC/simulation/include/TPCSimulation/DigitGlobalPad.h
- Detectors/TPC/simulation/include/TPCSimulation/DigitTime.h
- Detectors/TPC/simulation/include/TPCSimulation/Digitizer.h
- Detectors/TPC/simulation/include/TPCSimulation/SAMPAProcessing.h
- Detectors/TPC/simulation/src/CommonMode.cxx
- Detectors/TPC/simulation/src/DigitContainer.cxx
- Detectors/TPC/simulation/src/Digitizer.cxx
- Detectors/TPC/simulation/src/TPCSimulationLinkDef.h
- Detectors/TPC/simulation/test/testTPCDigitContainer.cxx
- Steer/DigitizerWorkflow/src/TPCDigitRootWriterSpec.cxx
- Steer/DigitizerWorkflow/src/TPCDigitizerSpec.cxx
- introduces a simple class containing the relevant information
- adds another output branch for the information of each sector to the tpcdigits.root
- information is only written when the common mode value is > 0
- following a request by @wiechula
> Write out the common mode information

- DataFormats/Headers/include/Headers/RAWDataHeader.h
- DataFormats/Headers/test/test_RAWDataHeader.cxx
The references for RDH v4 and v5 are now in the wp6-doc repo
https://gitlab.cern.ch/AliceO2Group/wp6-doc/blob/master/rdh/RDHV4.md
https://gitlab.cern.ch/AliceO2Group/wp6-doc/blob/master/rdh/RDHV5.md
The previous changes to the RAWDataHeader v3 definition have committed
the update to v4 already, simply renaming the struct. Version 3 and 4
are almost identical, v3 is only missing a few fields which are filled
by the CRU, we keep v3 as a simple alias to v4.
Adding the v5 definition, which contains only one trigger information
set, the length of a few filds has been adjusted, for details see
https://indico.cern.ch/event/818188/#26-cru
https://indico.cern.ch/event/791295/#1-wp6-rdh-v5
Version 5 is not yet implemented in hardware, keeping v4 as default for now.
> Updating the definition of RAWDataHeader

- DataFormats/Detectors/ITSMFT/common/include/DataFormatsITSMFT/Cluster.h
- DataFormats/Detectors/ITSMFT/common/src/Cluster.cxx
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/LookUp.h
Method to fill provided vector std::vector<std::pair<short,short>> with increments <d_column,d_row> to traverse all fired pixels of the topology starting from the provided column and row. Used for the study of an additional stream of full hitmaps in ITS compressed data (for  lossless compression)
> method to extract topology as a walk from reference col/row

- run/O2SimDeviceRunner.cxx
`warning: ‘bool FairMQChannel::ValidateChannel()’ is deprecated: Use Validate()`
> Fixing warning for deprecated FairMQ interface method

- doc/doxyfile.in
An empty documentation is built when using doxygen v1.8.16.
The reason seems to be that when FILE_PATTERNS is left blank the default patterns are not used anymore and no file is matched.
If the desired file patterns are explicitely specified, everything seems to work fine again.
Also, doxygen prints some warning about some obsolete variables that are therefore removed
> Fix to generate doc with v1.8.16

- Framework/Core/CMakeLists.txt
- Framework/Core/README.md
- Framework/Core/include/Framework/AnalysisTask.h
- Framework/Core/include/Framework/CallbackService.h
- Framework/Core/include/Framework/ChannelInfo.h
- Framework/Core/include/Framework/ChannelSpec.h
- Framework/Core/include/Framework/ControlService.h
- Framework/Core/include/Framework/DataProcessingDevice.h
- Framework/Core/include/Framework/DeviceSpec.h
- Framework/Core/include/Framework/DeviceState.h
- Framework/Core/include/Framework/EndOfStreamContext.h
- Framework/Core/include/Framework/SourceInfoHeader.h
- Framework/Core/include/Framework/TextControlService.h
- Framework/Core/src/AODReaderHelpers.cxx
- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/src/DataProcessingHelpers.cxx
- Framework/Core/src/DataProcessingHelpers.h
- Framework/Core/src/FrameworkGUIDeviceInspector.cxx
- Framework/Core/src/SourceInfoHeader.cxx
- Framework/Core/src/TextControlService.cxx
- Framework/Core/src/runDataProcessing.cxx
- Framework/Core/test/test_DataAllocator.cxx
- Framework/Core/test/test_StaggeringWorkflow.cxx
- Framework/Utils/test/test_RootTreeWriterWorkflow.cxx
This allows DataProcessorDevices to signal in the data stream when they are done sending messages and triggers a newly introduced `EndOfStreamCallback` which can then be used to finalise the data processing (and eventually quit). 
Things still to do:
Possibilities opened by this:
- Introduce a new histogram writing device which collects all the dangling histograms and writes them to file.
- Simplify all the "batch-like" workflows which now do not need to handle quitting themselves.
- Have the timers signal EndOfStream when they are done.
> DPL: introduce EndOfStream callback

- Framework/Core/include/Framework/DataSpecUtils.h
- Framework/Core/include/Framework/ExternalFairMQDeviceProxy.h
- Framework/Core/include/Framework/RawDeviceService.h
- Framework/Core/include/Framework/SimpleRawDeviceService.h
- Framework/Core/src/DataSamplingReadoutAdapter.cxx
- Framework/Core/src/DataSpecUtils.cxx
- Framework/Core/src/ExternalFairMQDeviceProxy.cxx
- Framework/Core/src/ReadoutAdapter.cxx
- Framework/Core/src/runDataProcessing.cxx
- Framework/Core/test/unittest_DataSpecUtils.cxx
The bradcast message has been used to forward the incoming messages from
an out-of-bound device on all relevant output channels. There was a bug,
as this can only work for the first channel, messages are unique pointers
which will be empty after first send.
Messages are now sent only on the concrete channel according to the OutputSpec
of the adapter function.
The relevant information is retreived via the RawDeviceContext and for this
purpose, the DeviceSpec has been added to RawDeviceContext.
The index of FairMQ channels has been removed as we use only one channel per
channel name.
> Getting rid of broadcast method for external FairMQ DPL proxies

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/DataSpecUtils.h
- Framework/Core/include/Framework/InputRoute.h
- Framework/Core/src/DataRelayer.cxx
- Framework/Core/src/DataSpecUtils.cxx
- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/Core/test/benchmark_DataRelayer.cxx
- Framework/Core/test/benchmark_InputRecord.cxx
- Framework/Core/test/test_DataRelayer.cxx
- Framework/Core/test/test_DeviceSpec.cxx
- Framework/Core/test/test_InputRecord.cxx
- Framework/Core/test/test_SimpleWildcard.cxx
- Framework/Core/test/test_WorkflowHelpers.cxx
- Framework/Utils/test/test_RootTreeWriter.cxx
There are cases in which using a wildcard matcher in a consumer
would result in duplicated input routes, while the wanted behavior
is to have a single input route processing one matching message after
the other. This makes sure that there is no duplication in such case.
For example consider producer PRODUCER producing A/1 and A/2, and
CONSUMER matching on A/*, this will now invoke the processing callback
when either A/1 or A/2 is received.
> DPL: fix route duplication due to wildcards

- CCDB/CMakeLists.txt
@sawenzel @mconcas :
The problem is the same as we fixed in ROOT here: alisw/alidist#1733
We have the same problem with Control/Monitoring/Readout. This PR just removed the (unnecessary) dependency from O2::Device and thus from O2::Monitoring.
I think it will be quite inconvenient to patch all our dependencies like I did with ROOT. There was already a related discussion in an issue of the CMake git, so I added our case there: https://gitlab.kitware.com/cmake/cmake/issues/19123
With some luck, they fix that in a future version.
> Remove unneeded dependency (fixes GPU CI)

- GPU/TPCSpaceChargeBase/AliTPCSpaceCharge3DCalc.cxx
- GPU/TPCSpaceChargeBase/AliTPCSpaceCharge3DCalc.h
**Changes in AliTPCSpaceCharge3DCalc:**
1) Update calculation of local r and rphi distortions by deltaEz (significant for RUN 3 scenarios). 
2) Only stream data members which are relevant for simulation with constant distortions to reduce file size.
> Modifications to reduce file size of space-charge objects used as input for TPC simulation with constant distortions

- Framework/Core/include/Framework/ConcreteDataMatcher.h
- Framework/Core/include/Framework/OutputSpec.h
- Framework/Core/src/OutputSpec.cxx
If the subspec was not specified we can not simply create `ConcreteDataMatchers`
with subspec 0.
This is relevant when searching for a matching output for a DataHeader in the list of output routes. Using e.g. `OutputSpec{"TST", "Data"}` without any supspec, every DataHeader with this origin and description should match ignoring the subspec, however only with subspec 0 is matched.
The following unit tests are failing, need to look in more detail.
45 - test_Framework_test_WorkflowHelpers (Failed)
63 - test_Framework_test_DanglingOutputs (Failed)
69 - test_Framework_test_SimpleDataProcessingDevice01 (Failed)
@ktf do you think?
> Defining another OutputSpec constructors and adding some notes

- CMakeLists.txt
- Framework/Core/CMakeLists.txt
- Framework/Utils/CMakeLists.txt
Used to turn off GUI when running tests non-interactively (e.g. in CI).
> Add DPL_TESTS_BATCH_MODE cmake option

- Framework/Core/src/DataRelayer.cxx
The DataHeader info is added to the error message in case the data can
not be relayed.
> Enhancing error message

- DataFormats/Detectors/MUON/MID/CMakeLists.txt
- DataFormats/Detectors/MUON/MID/include/DataFormatsMID/ROFRecord.h
- DataFormats/Detectors/MUON/MID/src/DataFormatsMIDLinkDef.h
- Steer/DigitizerWorkflow/src/MIDDigitWriterSpec.h
- Steer/DigitizerWorkflow/src/MIDDigitizerSpec.cxx
This is the first of a series of PR, whose aim is to allow MID to handle timeframes.
Currently, the MID processors expect objects with the same timestamp within a timeframe as input. This makes it difficult to correctly treat a full timeframe.
The objects with the same timestamp will be therefore referenced with the aim of a ROFRecord.
The following commits are atomic, so please do not squash them.
> Add Readout frame records for MID

- Framework/Core/include/Framework/ExternalFairMQDeviceProxy.h
- Framework/Core/src/DataSamplingReadoutAdapter.cxx
- Framework/Core/src/ExternalFairMQDeviceProxy.cxx
- Framework/Core/src/ReadoutAdapter.cxx
- Framework/TestWorkflows/src/flpQualification.cxx
Several changes to the ExternalFairMQDeviceProxy
- using OutputSpec as filter list in dplModelAdaptor
- matching the output channel to the actual data header
- Implementing merging of split payload data and association to correct output channel
> Merging of split payload data, matching to output channel

- Detectors/ITSMFT/ITS/tracking/cuda/src/VertexerTraitsGPU.cu
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/ClusterLines.h
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/Configuration.h
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/Vertexer.h
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/VertexerTraits.h
- Detectors/ITSMFT/ITS/tracking/src/ClusterLines.cxx
- Detectors/ITSMFT/ITS/tracking/src/Vertexer.cxx
- Detectors/ITSMFT/ITS/tracking/src/VertexerTraits.cxx
- macro/run_primary_vertexer_ITS.C
@iouribelikov  @shahor02 
Here there is the equivalent on CPU of the algorithm used for vertex finding on GPU
Notably:
- Found a major bug in histogram filling for GPU: fixed (nice to have a comparison on CPU already)
- It's based on `boost::histogram`s, which are nice but not perfect. Best performances will be likely achieved as if we are going to bump our O2 boost version to 1.71.x. At the moment no `std::max_element(boost::histogram::indexed(myHistogram))` is available due to input iterator vs forward iterator implementation on boost side. (see https://github.com/boostorg/histogram/issues/198) so I had to implement my "find max" logic.
A part form that it is consistent with the GPU implementation. Cross-tests, tuning/improvements and benchmarks of this algorithm are yet to come. 
Then …
> ITS vertexer: Add CPU serial transcription of GPU vertexfinder

- Detectors/EMCAL/simulation/src/Digitizer.cxx
Segfault related to removing digits from the temp
digit container when merging digits from different
time samples. Instead the iterator of the digit
need to be stored in a separate containers, and
the digits added have to be removed in a second loop.
> [EMCAL-624] Fix segfault in EMCAL digitizer

- DataFormats/Headers/include/Headers/DataHeader.h
- DataFormats/Headers/include/Headers/Stack.h
- DataFormats/Headers/src/DataHeader.cxx
- DataFormats/Headers/test/testDataHeader.cxx
This adds (based on user feedback, thx @ironMann ):
- a Stack ctor to construct a new Stack from a Stack  already constructed and existing in a buffer
- New DataHeader ctor with args for the split payload fields
- Slight sanitizing of default values of DataHeader fields
- tests & improvements
> Stack improvements

- Framework/Core/include/Framework/DataSpecUtils.h
- Framework/Core/include/Framework/ExternalFairMQDeviceProxy.h
- Framework/Core/src/DataSpecUtils.cxx
- Framework/Core/src/ExternalFairMQDeviceProxy.cxx
- Framework/Utils/CMakeLists.txt
- Framework/Utils/Readme.md
- Framework/Utils/src/raw-proxy.cxx
Executable:
`o2-dpl-raw-proxy`
A proxy workflow to connect to a channel from DataDistribution. The incoming
data is supposed to follow the O2 data model with header-payload pair messages.
The header message must contain `DataHeader` and the internal DPL `DataProcessingHeader`.
Only data which match the configured outputs will be forwarded.
Since payload can be split into several messages, the proxy will create a new
message to merge all parts belonging to one payload entity.
>  Adding DPL raw proxy utility

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/ChannelSpec.h
- Framework/Core/include/Framework/ComputingResource.h
- Framework/Core/include/Framework/DeviceSpec.h
- Framework/Core/src/ChannelSpecHelpers.cxx
- Framework/Core/src/ChannelSpecHelpers.h
- Framework/Core/src/ComputingResourceHelpers.cxx
- Framework/Core/src/ComputingResourceHelpers.h
- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/Core/src/DeviceSpecHelpers.h
- Framework/Core/src/ResourceManager.h
- Framework/Core/src/SimpleResourceManager.cxx
- Framework/Core/src/SimpleResourceManager.h
- Framework/Core/src/runDataProcessing.cxx
- Framework/Core/test/test_ChannelSpecHelpers.cxx
- Framework/Core/test/test_DeviceSpec.cxx
- Framework/Core/test/test_DeviceSpecHelpers.cxx
- Framework/Core/test/test_FrameworkDataFlowToDDS.cxx
- Framework/Core/test/test_Graphviz.cxx
- Framework/Core/test/test_TimeParallelPipelining.cxx
Rework the way DPL assign resources to devices. This is a first
step in moving away from the hardcoded 127.0.0.1 ip address and
allows DPL workflows to run distributed without a third party
configuring the channels. 
A further optimization will also allow DPL to configure ipc / shared memory when two devices happen to be assigned to the same machine.
> DPL: improve resource management

- DataFormats/Headers/include/Headers/DataHeader.h
the descriptors are not required to be null terminated. By convention they usually are, but when using binary content please use the supported methods, e.g. the as<string> helper.
I think historically we tried to enforce that convention, but in the end there were too many use cases against. @matthiasrichter do you remember what that was? @davidrohr thanks for pointing it out.
> Coment update: Header descriptors are NOT always null terminated

- Steer/include/Steer/InteractionSampler.h
- Steer/src/InteractionSampler.cxx
Some detectors need to inspect BC's before the one being triggered, to exclude negative times we start orbit/bc sampling from orbit 1 instead of unrealistic 0 (in the real running the orbit will be reset
to 0 at the beginning of the each fill).
Produce fatal if orbit exceeds maxOrbit (corresponds to >100 hours) and wraps to 0.
@sawenzel this is needed to avoid lengthy checks/protections in ZDC trigger simulation (perhaps for other detectors also)
> Exclude orbit=0 generation and its ovefrlow by InteractionSampler

- Detectors/ITSMFT/ITS/tracking/cuda/include/ITStrackingCUDA/VertexerTraitsGPU.h
- Detectors/ITSMFT/ITS/tracking/cuda/src/Context.cu
- Detectors/ITSMFT/ITS/tracking/cuda/src/VertexerTraitsGPU.cu
- Detectors/ITSMFT/ITS/tracking/cuda/src/dummy.cxx
- Detectors/ITSMFT/ITS/tracking/hip/CMakeLists.txt
- Detectors/ITSMFT/ITS/tracking/hip/include/ITStrackingHIP/ArrayHIP.h
- Detectors/ITSMFT/ITS/tracking/hip/include/ITStrackingHIP/ClusterLinesHIP.h
- Detectors/ITSMFT/ITS/tracking/hip/include/ITStrackingHIP/ContextHIP.h
- Detectors/ITSMFT/ITS/tracking/hip/include/ITStrackingHIP/DeviceStoreVertexerHIP.h
- Detectors/ITSMFT/ITS/tracking/hip/include/ITStrackingHIP/StreamHIP.h
- Detectors/ITSMFT/ITS/tracking/hip/include/ITStrackingHIP/UniquePointerHIP.h
- Detectors/ITSMFT/ITS/tracking/hip/include/ITStrackingHIP/UtilsHIP.h
- Detectors/ITSMFT/ITS/tracking/hip/include/ITStrackingHIP/VectorHIP.h
- Detectors/ITSMFT/ITS/tracking/hip/include/ITStrackingHIP/VertexerTraitsHIP.h
- Detectors/ITSMFT/ITS/tracking/hip/src/ClusterLinesHIP.hip.cxx
- Detectors/ITSMFT/ITS/tracking/hip/src/ContextHIP.hip.cxx
- Detectors/ITSMFT/ITS/tracking/hip/src/DeviceStoreVertexerHIP.hip.cxx
- Detectors/ITSMFT/ITS/tracking/hip/src/StreamHIP.hip.cxx
- Detectors/ITSMFT/ITS/tracking/hip/src/UtilsHIP.hip.cxx
- Detectors/ITSMFT/ITS/tracking/hip/src/VertexerTraitsHIP.hip.cxx
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/IndexTableUtils.h
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/Tracklet.h
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/VertexerTraits.h
- GPU/GPUTracking/Base/hip/CMakeLists.txt
- GPU/GPUTracking/Base/hip/GPUReconstructionHIP.h
- GPU/GPUTracking/Base/hip/GPUReconstructionHIP.hip.cxx
- macro/run_primary_vertexer_ITS.C
Hi @shahor02, @iouribelikov, @davidrohr 
This PR would implement the corresponding HIP-based GPU vertexer.
Good news is that it is consistent with the CUDA one and runs on a `Vega 10 XT [Radeon PRO WX 9100]`.
I am putting WIP because of some things I would like to improve before merging, for instance the automatic calibration of parameters to use based on the detected GPU (we have something already in place for CUDA, wondering if something similar could be done with HIP+AMD).
On this and other things I will probably bug you again, David.
To the reviewer: the code is not written _ex-novo_, is derived from already implemented upstream CUDA version by mean of using `hipify-perl` that translates this for you. Then indeed the resulting files have been extensively adapted, but not in its core …
> GPU: Add HIP vertexer

- DataFormats/Headers/include/Headers/DataHeader.h
- DataFormats/Headers/include/Headers/Stack.h
- DataFormats/Headers/src/DataHeader.cxx
- Stack::calculateSize() is now constexpr
- Stack construction without a copy in some cases by allowing copy elision in the Stack ctor
> Header optimization: more constexpr!

- Framework/Core/include/Framework/ServiceRegistry.h
Use a custom lookup table rather than a std::hash.
> DPL: improve performance of ServiceRegistry lookup

- Detectors/MUON/MID/Raw/CMakeLists.txt
- Detectors/MUON/MID/Raw/include/MIDRaw/Decoder.h
- Detectors/MUON/MID/Raw/include/MIDRaw/Encoder.h
- Detectors/MUON/MID/Raw/include/MIDRaw/RawUnit.h
- Detectors/MUON/MID/Raw/src/Decoder.cxx
- Detectors/MUON/MID/Raw/src/Encoder.cxx
- Detectors/MUON/MID/Raw/src/RawInfo.h
- Detectors/MUON/MID/Raw/test/CMakeLists.txt
- Detectors/MUON/MID/Raw/test/bench_Raw.cxx
- Detectors/MUON/MID/Raw/test/testRaw.cxx
- Detectors/MUON/MID/Workflow/CMakeLists.txt
- Detectors/MUON/MID/Workflow/include/MIDWorkflow/DigitsToRawWorkflow.h
- Detectors/MUON/MID/Workflow/include/MIDWorkflow/RawWriterSpec.h
- Detectors/MUON/MID/Workflow/src/DigitsToRawWorkflow.cxx
- Detectors/MUON/MID/Workflow/src/RawWriterSpec.cxx
- Detectors/MUON/MID/Workflow/src/mid-digits-to-raw.cxx
This PR consists of two separate commits: one that introduces the raw data encoder and decoder, and the other that implements the digits-to-raw workflow.
Please do not squeeze them.
> Raw data writer for MID

- Framework/Utils/CMakeLists.txt
- Framework/Utils/Readme.md
- Framework/Utils/include/DPLUtils/RawParser.h
- Framework/Utils/src/raw-parser.cxx
- Framework/Utils/test/test_RawParser.cxx
This prototype implements a parser for O2 raw data which is organized in pages of a
fixed size, each page starts with the `RAWDataHeader`. The page size may actually be
smaller than the maximum size, depending on the header fields.
The parser class works on a contiguous sequence of raw pages in a raw buffer.
Multiple versions of `RAWDataHeader` are supported transparently and selected depending
on the version field of the header.
Hosting it under DPLUtils for the moment though this will be moved to somewhere else.
> Generic raw parser and example workflow

- Framework/AnalysisTutorial/src/histograms.cxx
- Framework/Core/include/Framework/AnalysisTask.h
- Framework/Core/src/CommonDataProcessors.cxx
Allows to export objects, that can not be statically initialized (like THn)
> DPL: Extend OutpuObj so that an object can be set later

- Framework/Core/src/AODReaderHelpers.cxx
- Framework/Core/src/WorkflowHelpers.cxx
- Use "--event=100000 --esd-file=AliESDs.root"
- Needs Converter patch: https://github.com/AliceO2Group/Run2ESDConverter/pull/16
> Commandline option to limit number of events given by the Converter

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/DataRelayer.h
- Framework/Core/include/Framework/ExpirationHandler.h
- Framework/Core/include/Framework/InputRoute.h
- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/src/DataRelayer.cxx
- Framework/Core/src/DataRelayerHelpers.cxx
- Framework/Core/src/DataRelayerHelpers.h
- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/Core/test/benchmark_DataRelayer.cxx
- Framework/Core/test/test_DataRelayer.cxx
Before this processDanglingInputs does NxM complex pass on the
inputs and the expirators, checking if there is anything to be
expired and eventually expiring it.
This changes things so that we do Nxm complex pass, where m is
the actual inputs that can expire, i.e. we do not do the pass
for all the inputs which do not have an expiration policy attach.
Since not having an expiration policy is the norm, this should
minimize the impact of processDanglingInputs for normal usage.
> DPL: optimize processDanglingInputs

- Detectors/TPC/simulation/CMakeLists.txt
- Detectors/TPC/simulation/include/TPCSimulation/SpaceCharge.h
- Detectors/TPC/simulation/macro/createResidualDistortionObject.C
- Detectors/TPC/simulation/src/SpaceCharge.cxx
- GPU/TPCSpaceChargeBase/AliTPCSpaceCharge3DCalc.cxx
- GPU/TPCSpaceChargeBase/AliTPCSpaceCharge3DCalc.h
Residual distortions (fluctuation scenario - average scenario) can be calculated, stored as TMatrices and provided to the SpaceCharge object. Like this, they can directly be applied during TPC digitization.
> Temporary solution to apply residual space-charge distortions in TPC simulation.

- Framework/Core/include/Framework/Expressions.h
The extra constructor would have allowed to build `Node`s from way too many other types.
> DPL: avoid clashes between expressions and fmt

- DataFormats/MemoryResources/test/testMemoryResources.cxx
- Utilities/O2Device/test/test_O2Device.cxx
A part of investigation of recent test failures in O2Device and MemoryResources, now each test unit has a unique session id and uses their own transport factories and allocators.
> Make FMQ transport tests use unique id for sessions

- run/o2sim_parallel.cxx
* Instead of copying config JSON, modifies it adding pid to URLs, and saves a copy.
This allows multiple 'o2sim's on one node without clashing
* Should fix the CI tests...
@sawenzel since you've merged #2526 a bit too early, here is the part that I missed.
> Allow for simultaneous o2sim runs

- Detectors/TRD/simulation/src/Digitizer.cxx
Small improvements in the TRD digitizer:
- Removal of unnecessary conditional for testing negative random numbers, give that gRandom->Rndm() is always between 0 and 1.
- Removal of unnecessary assignments when updating the pad signal.
> TRD: small improvements

- Detectors/EMCAL/reconstruction/src/AltroDecoder.cxx
EMCAL channel data are stored as 10-bit words
within a 32 bit word, meaning each raw data
word has 3 ADC words. In case the payload size
doesn't match exactly the amount of raw data
words (division by three), overflow words
are part of the raw data words and must be
ignored. The number of samples must therefore
be taken from the payload size in the channel
header and not from counting the amount
of 10-bit words within the 32-bit raw data
words.
> [EMCAL-534] Fix handling of overflow words

- Framework/Core/include/Framework/Expressions.h
- Framework/Core/src/ExpressionHelpers.h
- Framework/Core/src/Expressions.cxx
- Framework/Core/test/test_Expressions.cxx
* make operation specs produced by parsing an expression tree more generic
* remove explicit Arrow dependence
* rearrange includes
> DPL: Expressions:

- Framework/Core/include/Framework/ProcessingContext.h
Should speedup compilation and reduce risk of the magic in
ServiceRegistry to be exposed to ROOT.
> DPL: remove explicit ServiceRegistry include

- Framework/AnalysisTutorial/src/histograms.cxx
- Framework/Core/include/Framework/AnalysisTask.h
- Framework/Core/include/Framework/OutputObjHeader.h
- Framework/Core/src/CommonDataProcessors.cxx
- Framework/Foundation/include/Framework/StructToTuple.h
* Added a specialized header for OutputObj metadata (can be extended)
* Added a policy enum that determines the destination of OutputObj
* Added header parsing in common root file sink to use the policy
* Updated analysis tutorial example to use different policies
> DPL: OutputObj: support for writing in multiple files

- Framework/Core/include/Framework/ASoA.h
- Framework/Core/src/ASoA.cxx
- Framework/Core/src/ArrowDebugHelpers.h
- Framework/Core/test/test_ASoA.cxx
- Framework/Foundation/include/Framework/FunctionalHelpers.h
This allows to take two `soa::Table` with different columns and stack their common columns into a new `soa::Table`. This effectively mimics the ability to have polymorphic collections and access data through the common base class.
> Framework: add ability to concatenate tables

- DataFormats/Detectors/EMCAL/CMakeLists.txt
- DataFormats/Detectors/EMCAL/include/DataFormatsEMCAL/TriggerRecord.h
- DataFormats/Detectors/EMCAL/src/DataFormatsEMCALLinkDef.h
- DataFormats/Detectors/EMCAL/src/TriggerRecord.cxx
- Steer/DigitizerWorkflow/src/EMCALDigitWriterSpec.cxx
- Steer/DigitizerWorkflow/src/EMCALDigitWriterSpec.h
- Steer/DigitizerWorkflow/src/EMCALDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/EMCALDigitizerSpec.h
- Adding class o2::emcal::TriggerRecord (adapted
from o2::itsmft::ROFRecord in order to separate
digits from various triggers in the output container
- Include Channels for the trigger record in the
digitizer spec and the digits writer spec
> [EMCAL-626] Separating digits from different Triggers

- Detectors/ZDC/simulation/src/Detector.cxx
Otherwise the hits are created but the container is reset before they are stored.
> Fix: dont clear ZDC hits when ShmManager is operational

- Generators/include/Generators/GeneratorFromFile.h
- Generators/src/GeneratorFromFile.cxx
After the check for the discrepancy between the M_PDG and M=sqrt(E^2-P^2) (off-shell particles) we check if the calculated mass TParticles::GetCalcMass() is consistent with the PDG mass. If it is, we assume that the kinematics is simply wrong and assign correct E as sqrt(P^2 + M_PDG^2).
@sawenzel this was to fix primarily the RELDIS Kinematics for ZDC tests, where the neutrons appear to be off-shell. But I've checked also on Hijing and most of the particles I've seen being off-shell were stable ones (except some lambdas):
````
[WARN] Particle -211 has off-shell mass: M_PDG= 0.13957 (assigned= 0.13957) calculated= 0.140711 -> diff= 0.00114135 | fixing
[WARN] Particle -211 has off-shell mass: M_PDG= 0.13957 (assigned= 0.13957) calculated= 0.139352 -> diff= 0.000218301 | fixing
[WARN] …
```
> isOnMassShell will try to fix particles with wrong kinematics

- Framework/Core/include/Framework/AnalysisDataModel.h
For cell table:
- Add cell type, definition according to
DataFormatsEMCAL/Constants/ChannelType_t
For trigger table:
- Add fields for FastOR Abs. ID, L0 Amplitude,
L1 time sum, trigger times, trigger bits
> [EMCAL-625] Fix EMCAL cell table, add table for calo trigger

- Detectors/EMCAL/simulation/CMakeLists.txt
- Detectors/EMCAL/simulation/include/EMCALSimulation/DMAOutputStream.h
- Detectors/EMCAL/simulation/src/DMAOutputStream.cxx
- Detectors/EMCAL/simulation/src/EMCALSimulationLinkDef.h
Class writing header and payload to a binary
file in DMA page format. The output stream
splits the payload into multiple pages
in case the payload is larger than the
8 kB offset. Header fields memorySize,
pageCounter and stop bit are handled by
the DMA output stream similarly as done
in the readout hardware.
> [EMCAL-610, EMCAL-628] Add DMA output stream

- DataFormats/common/include/CommonDataFormat/BunchFilling.h
- DataFormats/common/src/BunchFilling.cxx
- Steer/DigitizerWorkflow/src/SimReaderSpec.cxx
- Steer/include/Steer/InteractionSampler.h
- Steer/src/InteractionSampler.cxx
- macro/CMakeLists.txt
- macro/CreateBCPattern.C
@ekryshen : this will allow to run digitization with custom interacting BC patterns, e.g.
````
root -b -q $O2_ROOT/share/macro/CreateBCPattern.C+ 
o2-sim-digitizer-workflow --interactionRate 1000000 --bcPatternFile bcPattern.root
````
> Possibility to impose custom BC patter in digitization + macro to create it

- Common/SimConfig/src/SimConfig.cxx
- Detectors/Base/include/DetectorsBase/Detector.h
- run/O2HitMerger.h
- run/o2sim_parallel.cxx
This commit makes the hit merging
- asynchronous
- be performed after each event instead of at the end of simulation
This should solve a problem where the IO became
an important serial bottleneck for PbPb simulations.
Note:
We can potentially achieve still better performance by parallelizing
over the different branches in the output tree.
> o2-sim: improved hit merging

- Framework/Utils/CMakeLists.txt
- Framework/Utils/include/DPLUtils/RawParser.h
- Framework/Utils/src/RawParser.cxx
- Framework/Utils/src/raw-parser.cxx
- Framework/Utils/test/benchmark_RawParser.cxx
- Framework/Utils/test/test_RawParser.cxx
- Adding benchmark
- Using iterative approach to forward to concrete instance
slightly faster than std::visit
- Introducing get_if method for iterator to retrieve a concrete RDH
- Adding stream output operator
- Printing RDH properties in the raw parser example process
> Improvements for the RawParser utility

- run/O2HitMerger.h
- run/O2SimDevice.h
Sometimes we seem to encounter "interrupted system calls"
in the request-reply pattern between particle server and worker.
This commit is trying to achieve a more robust handling of those cases.
Instead of simply exiting (and hanging) we try to read from the socket
again in the hope to recover...
We also change the default behaviour of segmentation violation signals
for the hit merger. Instead of producing a coredump we simply exit immediately
in order not to hang and produce zombie processes (which sometimes happens on MacOS).
> o2-sim: More robust communication (retry failed receive)

- Framework/Core/src/DataRelayer.cxx
Slots created by handlers were not correctly stored and then accessed. The vector storing them was initialized with a given size and all the slots were being push back at the end, instead of putting them at the order corresponding to handlers themselves.
@ktf
> Fix dangling inputs expiration handling

- Framework/AnalysisTutorial/src/filters.cxx
- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/AnalysisTask.h
- Framework/Core/include/Framework/Expressions.h
- Framework/Core/src/Expressions.cxx
- Framework/Core/test/test_ASoA.cxx
- dependencies/Findarrow.cmake
> DPL Analysis: add support for filtered tables

- Detectors/TOF/reconstruction/src/Clusterer.cxx
Rough hardcoded 25 ns bc duration changed to o2::constants::lhc::LHCBunchSpacingNS. Previous value resulted in a drop of the TOF matching efficiency after several orbits because TOF clusters get out of sync with ITS-TPC tracks for relatively large orbit counts. This fix recovers expected TOF matching efficiency for long periods. See attached.
> BC duration changed from 25 ns to LHCBunchSpacingNS constant

- Framework/AnalysisTutorial/src/dynamicColumns.cxx
- Framework/AnalysisTutorial/src/filters.cxx
- Framework/AnalysisTutorial/src/newCollections.cxx
- Framework/Core/include/Framework/AnalysisDataModel.h
- Framework/Core/include/Framework/AnalysisTask.h
- Framework/Core/src/AODReaderHelpers.cxx
- Framework/Core/src/WorkflowHelpers.cxx
- Framework/Core/test/test_WorkflowHelpers.cxx
- Framework/TestWorkflows/src/o2SimpleTracksAnalysis.cxx
- Framework/Utils/CMakeLists.txt
- Framework/Utils/src/esd-2-arrow-converter.cxx
The idea is that we can use the workflow merging capabilities of
DPL to inject the converter via:
o2-dpl-esd-2-arrow-converter --esd-file AliESD.root | my-analysis-workflow
> DPL: Support for Run2ESDConverter a separate workflow

- Common/MathUtils/include/MathUtils/Chebyshev3DCalc.h
Hi @shahor02 ,
As far as I understand, those test are not needed because the same tests are already done either in the for loop (id0-- is evaluated before id0 is decremented) or at the beginning of the function chebyshevEvaluation1D(...). If this is correct, I propose to remove them.
By removing those tests, I speedup the MCH tracking by about 15% (for the dimuon PbPb events that I use for testing), because most of the time (~80%) is in fact spent in the evaluation of the magnetic field when propagating the tracks. Actually a large part of the improvement with the new algorithm comes from the fact that it reduces the number of track propagation (by reducing the number of combinations considered in the process and by avoiding to go back and forth).
> remove double checks to speedup field evaluation

- Framework/Core/include/Framework/TypeTraits.h
- Framework/Foundation/include/Framework/Traits.h
No need to intertwine it with ROOT or BOOST.
> DPL: move is_specialization to Foundation

- Common/MathUtils/include/MathUtils/RandomRing.h
- Detectors/TRD/base/src/TRDBaseLinkDef.h
- Detectors/TRD/simulation/include/TRDSimulation/Digitizer.h
- Detectors/TRD/simulation/src/Digitizer.cxx
Speed up TRD digitizer by using circular pre-computed random numbers.
This is also a step towards multi-threading since we are no longer using the gRandom singleton.
See previous discussion here https://alice.its.cern.ch/jira/browse/O2-734.
> Optimization on TRD digitizer

- Detectors/TPC/simulation/include/TPCSimulation/DigitContainer.h
- allows to run the TPC digitization with a sampling frequency different than 5 MHz
> Flexible container size for the TPC depending on the sampling frequency

- Detectors/ITSMFT/ITS/simulation/src/V3Services.cxx
The cylinder supporting the Inner Barrel staves (CYSS) was erroneously implemented only in the lower part as a half cylinder. Now also the upper part has been inserted in the code.
> Implement the IB CYSS support cylinder also on the upper part

- Framework/Utils/src/RawParser.cxx
- Framework/Utils/src/raw-parser.cxx
Printing exception message instead of re-throwing it
> Bugfix: argument list of a formated log message

- Detectors/EMCAL/base/src/Mapper.cxx
Trivial fix: File path was missing one character (files
instead of file), therefore mapping files were not found
and reading crashed with an I/O error.
> [EMCAL-600] Fix path to mapping files

- Detectors/TPC/qc/CMakeLists.txt
- Detectors/TPC/qc/include/TPCQC/Tracks.h
- Detectors/TPC/qc/macro/runTracks.C
- Detectors/TPC/qc/src/TPCQCLinkDef.h
- Detectors/TPC/qc/src/Tracks.cxx
- Detectors/TPC/qc/test/test_Tracks.cxx
o This is the O2 part of the TPC QC task relating to the tracks
o Several 1D and 2D histograms are implemented
o A root macro is provided to run the task and save the output
o A corresponding workflow will be added to QualityControl
> First version of TPC QC Tracks task

- Framework/Core/src/ExpressionHelpers.h
- Framework/Core/src/Expressions.cxx
* isSchemaCompatible() to check whether fields required by filter
operations are present in a given Arrow schema
* createExpressionTree() to create a Gandiva expression tree that
can be later merged with another tree or used to create appliable
filter
> DPL Analysis: additional functions for filter

- Framework/Core/include/Framework/ExternalFairMQDeviceProxy.h
- Framework/Core/src/ExternalFairMQDeviceProxy.cxx
- Framework/Utils/include/DPLUtils/RawParser.h
- Framework/Utils/src/raw-parser.cxx
Immediate dispatch is hardcoded for the moment, which is probably anyhow
a suitable default. Need to make this configurable. Preferably through
the workflow configuration mechanism.
Polishing the raw parser printout and introducing argument `--log-level`.
> [O2-893] Introducing dispatch policy to ExternalFairMQDeviceProxy

- Detectors/TRD/simulation/src/Digitizer.cxx
- Removes crash reverted in #2649. 
- ADC spectrum looks better than before, more work is required but is not necessarily related to the CCDB integration.
- Small drift velocities are related to the values fetched from the CCDB, not to the CCDB integration.
> TRD: Add calibration values to the digitizer from the CCDB

- Detectors/EMCAL/reconstruction/include/EMCALReconstruction/RawReaderMemory.h
Comparison in hasNext was done by mistake against the
number of pages in payload and not against the raw
buffer size, therefore the has nextNext always returned
false as the page offset (used as current position) is
larger than the average number of pages.
> [EMCAL-534] Fix determination of next page in RawReaderMemory

- Common/MathUtils/include/MathUtils/Cartesian3D.h
- Common/MathUtils/test/testCartesian3D.cxx
- DataFormats/Detectors/ITSMFT/common/CMakeLists.txt
- DataFormats/Detectors/ITSMFT/common/include/DataFormatsITSMFT/Cluster.h
- DataFormats/Detectors/ITSMFT/common/test/test_Cluster.cxx
- DataFormats/Detectors/TPC/CMakeLists.txt
- DataFormats/Detectors/TPC/include/DataFormatsTPC/TrackTPC.h
- DataFormats/Detectors/TPC/src/DataFormatsTPCLinkDef.h
- DataFormats/Detectors/TPC/src/TrackTPC.cxx
- DataFormats/common/src/CommonDataFormatLinkDef.h
- Detectors/GlobalTracking/include/GlobalTracking/MatchTPCITS.h
- Detectors/GlobalTracking/src/MatchTPCITS.cxx
- Detectors/GlobalTrackingWorkflow/src/TPCITSMatchingSpec.cxx
- Detectors/TPC/calibration/SpacePoints/include/SpacePoints/TrackInterpolation.h
- Detectors/TPC/calibration/SpacePoints/src/TrackInterpolation.cxx
- Detectors/TPC/reconstruction/src/GPUCATracking.cxx
- Detectors/TPC/reconstruction/test/testGPUCATracking.cxx
- Detectors/TPC/workflow/include/TPCWorkflow/TrackReaderSpec.h
- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- Detectors/TPC/workflow/src/RecoWorkflow.cxx
- Detectors/TPC/workflow/src/TrackReaderSpec.cxx
- GPU/GPUTracking/Interface/GPUO2InterfaceConfiguration.h
- macro/runCATrackingClusterNative.C
@wiechula @davidrohr @matthiasrichter I've eliminated the ``vector<uint32_t>`` from the TrackTPC to make it POD and modified the dependent code.
This allows to use spans instead of vectors for the DPL inputs (hence to avoid copying the input data). 
Together with other vector->span changes this alone saves ``~0.7 GB`` of memory in TPCITS matching component for 50 pbpb events.
@martenole I've also modified your interpolation code to account for modified TrackTPC.
> Split TrackTPC and its clusters and use span<POD> to receive DPL inputs

- Detectors/MUON/MID/Simulation/include/MIDSimulation/DigitsMerger.h
- Detectors/MUON/MID/Simulation/src/DigitsMerger.cxx
- Detectors/MUON/MID/Simulation/test/testSimulation.cxx
- Steer/DigitizerWorkflow/src/MIDDigitizerSpec.cxx
This PR consists of 2 commits:
- the first one solves a bug due to which two parts of the same event were attributed to different ROFRecords
- the second part correctly treat the in-bunch pilup. These events have the same orbit and bc counter, but occur at few (fraction of) ns difference. The resulting digits are correctly identified as "separate" vertex from the MC. However, when running the clustering, they need to be merged since the MID is not capable to separate them.
The commit allows to correctly handle the in-bunch pileup (and the MC labels insure that we are still able to distingish the digits coming from different vertexes)
> Correctly treat in-bunch pileup in MID simulations

- Framework/Core/include/Framework/InputRecord.h
- Framework/Utils/include/DPLUtils/RootTreeWriter.h
- Framework/Utils/test/test_RootTreeWriter.cxx
This is a first sketch for the functionality requested by @shahor02 
A couple of things need to be polished and the unit test has to be completed.
It also depends on the correct implementation of `InputRecord::get, WIP in PR #2617 
EDIT:
> Supporting also vector<pod> in the RootTreeWriter

- Framework/Core/include/Framework/Task.h
- Utilities/Mergers/include/Mergers/Merger.h
- Utilities/Mergers/src/Merger.cxx
This is an attempt to fix https://alice.its.cern.ch/jira/browse/O2-735 (thx for @sawenzel for finding out that the task is created in each process of the workflow, not only the one that runs a particular task.)
This fix tries to cure that by running the constructor of the task object only during the InitCallback.
@sawenzel : FYI: I couldn't make our previous approach work with perfect forwarding, but I found a much simpler and cleaner solution.
So far checked only that it compiles for me, we should do a performance test, and let's see what the CI says.
> Create DPL AlgorithmSpec Task only in the InitCallback

- Framework/Core/include/Framework/TimesliceIndex.h
- Framework/Core/include/Framework/TimesliceIndex.inc
- Framework/Core/src/DataRelayer.cxx
- Framework/Core/src/LifetimeHelpers.cxx
@ktf This should bring the original behaviour of data driven dangling inputs while not destroying the timers logic.
I haven't tried it yet locally, I am waiting until the latest stack compiles...
> Fix data driven dangling inputs

- Framework/Core/test/FrameworkCoreTestLinkDef.h
- Framework/Utils/include/DPLUtils/RootTreeWriter.h
- Framework/Utils/test/test_RootTreeWriter.cxx
Wrong pointer instance was used for vectors when writing to branch after PR #2645.
This resulted into unwanted formatting of the data in the root file, though the ROOT IO appeared to be quite flexible and the readback was successful.
Adding also check for failed branch creation and enhancing the unit test.
> Bugfix RootTreeWriter

- DataFormats/Detectors/TRD/CMakeLists.txt
- DataFormats/Detectors/TRD/include/DataFormatsTRD/TriggerRecord.h
- DataFormats/Detectors/TRD/src/DataFormatsTRDLinkDef.h
- DataFormats/Detectors/TRD/src/TriggerRecord.cxx
- Steer/DigitizerWorkflow/CMakeLists.txt
- Steer/DigitizerWorkflow/src/TRDDigitWriterSpec.h
- Steer/DigitizerWorkflow/src/TRDDigitizerSpec.cxx
Adding a trigger (readout record) to the digitization process.
@tdietel @bazinski : This is a basic version of what we talked about last week.
You can take it as a basis for your own customized trigger information.
> TRD: Add basic trigger (frame) information

- DataFormats/MemoryResources/include/MemoryResources/MemoryResources.h
- DataFormats/MemoryResources/test/testMemoryResources.cxx
The spectator memory resource does not do any real allocation but provides
the poiunter to an underlying buffer which it owns as unique pointer. No
redirection to default memory resource as only the acces to the underlying
memory is supported.
> Adding SpectatorMemoryResource to be used with pmr allocators

- Framework/Utils/include/DPLUtils/RootTreeWriter.h
- Framework/Utils/test/test_RootTreeWriter.cxx
Vectors of messageable types with ROOT dictionary can be sent with serialization
method NONE or ROOT. Handle also the ROOT serialized messages.
> RootTreeWriter: Handling vectors of types which can be both ROOT and non-serialized

- Framework/Utils/include/DPLUtils/RawParser.h
- Framework/Utils/src/raw-parser.cxx
- Framework/Utils/test/test_RawParser.cxx
Adding methods to access the raw buffer at position and payload offset.
Renaming length() -> size()
The raw buffer points to the beginning of the RDH which can be different
versions and thus we can not return a concrete type. See get_if for this.
> Adding some helper methods to RawParser iterator

- Detectors/ZDC/simulation/data/simcuts.dat
- Detectors/ZDC/simulation/src/Detector.cxx
Changes introduced in the commit:
- materials for which the cut are applied have been fixed (remnants from AliRoot were left)
- in ProcessHit the hits are now correctly summed per PMT: the number of produced phototelectrons is obtained by adding the current no. of generated phe to the correct hit (the one generated in the same detector/sector)
> Updates for ZDC hit processing 

- Framework/Utils/src/raw-parser.cxx
Instead of gsl::span, std::span was used. This lead to a wrong pointer of
the raw buffer used by the parser class.
Need to investigate:
> Fixing a typo which made raw-parser crashing std namespace instead of gls for span

- Framework/Core/include/Framework/ExternalFairMQDeviceProxy.h
- Framework/Core/src/ExternalFairMQDeviceProxy.cxx
Make the DPL model adaptor more strict about unmatched input data, will throw
by default unless dropping of messages is enabled. Also improving the exception
message. Printing warning about dropped messages if enabled.
> Enforcing exception on unmatched input data in ExternalFairMQDeviceProxy

- DataFormats/Detectors/TPC/include/DataFormatsTPC/TrackTPC.h
- DataFormats/Detectors/TPC/src/DataFormatsTPCLinkDef.h
- Detectors/GlobalTracking/include/GlobalTracking/MatchTPCITS.h
- Detectors/GlobalTracking/src/MatchTPCITS.cxx
- Detectors/GlobalTrackingWorkflow/src/TPCITSMatchingSpec.cxx
- Detectors/TPC/calibration/SpacePoints/include/SpacePoints/TrackInterpolation.h
- Detectors/TPC/reconstruction/test/testGPUCATracking.cxx
- Detectors/TPC/workflow/include/TPCWorkflow/TrackReaderSpec.h
- Detectors/TPC/workflow/src/RecoWorkflow.cxx
- macro/runCATrackingClusterNative.C
Since the RootTreeWriter is now able to accept vector<basic_types>, we don't need anymore to wrap
the uint32_t to struct with dictionary to store cluster indices.
> Remove workaround for storing TPC cluster indices

- Framework/AnalysisTutorial/src/filters.cxx
- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/AnalysisDataModel.h
- Framework/Core/include/Framework/AnalysisTask.h
- Framework/Core/include/Framework/Expressions.h
- Framework/Core/src/Expressions.cxx
- Framework/Core/test/test_AnalysisTask.cxx
Warning: includes #2639, #2663 and #2664  
@ktf I've made the combined code compile and added support for Filtered<>::iterator as an argument for process(). The only thing that is missing for the filters to work is merging expressions, and creating/propagating the selection vectors.
> DPL Analysis: Bind filters to tables

- Framework/Utils/CMakeLists.txt
- Framework/Utils/test/DPLBroadcasterMerger.cxx
- Framework/Utils/test/DPLOutputTest.cxx
- Framework/Utils/test/test_RootTreeReader.cxx
The new CMake infrastructure assumes all tests are boost tests
by default, silently breaking any DPL based test which does not
declare itself as NO_BOOST_TEST.
> DPL Utils: properly handle some tests

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/BoostOptionsRetriever.h
- Framework/Core/include/Framework/ConfigParamRegistry.h
- Framework/Core/include/Framework/FairOptionsRetriever.h
- Framework/Core/include/Framework/ParamRetriever.h
- Framework/Core/include/Framework/SimpleOptionsRetriever.h
- Framework/Core/include/Framework/Variant.h
- Framework/Core/src/BoostOptionsRetriever.cxx
- Framework/Core/src/ConfigParamsHelper.cxx
- Framework/Core/src/FairOptionsRetriever.cxx
- Framework/Core/src/SimpleOptionsRetriever.cxx
- Framework/Core/test/test_BoostOptionsRetriever.cxx
- Framework/Core/test/test_ConfigParamRegistry.cxx
- Framework/Core/test/test_FairMQOptionsRetriever.cxx
- Framework/Core/test/test_ProcessorOptions.cxx
This is needed to set realistic timestamps for enumerated timeframe data sources.
> Support int64 as argument to DPL executables

- run/O2SimDeviceRunner.cxx
- run/o2sim_parallel.cxx
This commit improves termination of worker processes
upon finishing the simulation. So far, the worker processes
could live longer than the driver application which is not wanted.
> o2-sim: More robust child process termination

- Detectors/MUON/MID/Workflow/src/ClusterizerMCSpec.cxx
- Detectors/MUON/MID/Workflow/src/ClusterizerSpec.cxx
- Detectors/MUON/MID/Workflow/src/DigitReaderSpec.cxx
- Detectors/MUON/MID/Workflow/src/TrackerMCSpec.cxx
- Detectors/MUON/MID/Workflow/src/TrackerSpec.cxx
This PR fixes some issues in the MID specs. Passing a const char* to construct a divice adopted through adoptTask recently resulted in an error, since it seems that the pointer was copied as is by the framework and the corresponding object could have already been destroyed when the pointer was used.
The PR also removes the readyToQuit command. The quit is indeed handled in a better way through the endOfStream command.
> Do not pass char* to construct a device adopted through adoptTask

- Detectors/TRD/base/src/Calibrations.cxx
LocalT0 seems to be zero in all the places I looked including of course the one we are currently using.
This means that LocalT0 is essentially not used ? @tdietel 
Calculation of T0 is now (ChamberValue+LocalT0) instead of what we had (ChamberValue*LocalT0) which of course always gave zero.
> fix calculation of T0 in calibrations

- Detectors/MUON/MID/Base/include/MIDBase/DetectorParameters.h
- Detectors/MUON/MID/Raw/CMakeLists.txt
- Detectors/MUON/MID/Raw/include/MIDRaw/CRUUserLogicDecoder.h
- Detectors/MUON/MID/Raw/include/MIDRaw/CRUUserLogicEncoder.h
- Detectors/MUON/MID/Raw/include/MIDRaw/CrateMapper.h
- Detectors/MUON/MID/Raw/include/MIDRaw/CrateParameters.h
- Detectors/MUON/MID/Raw/include/MIDRaw/Decoder.h
- Detectors/MUON/MID/Raw/include/MIDRaw/Encoder.h
- Detectors/MUON/MID/Raw/include/MIDRaw/LocalBoardRO.h
- Detectors/MUON/MID/Raw/include/MIDRaw/RawBuffer.h
- Detectors/MUON/MID/Raw/include/MIDRaw/RawFileReader.h
- Detectors/MUON/MID/Raw/src/CRUUserLogicDecoder.cxx
- Detectors/MUON/MID/Raw/src/CRUUserLogicEncoder.cxx
- Detectors/MUON/MID/Raw/src/CrateMapper.cxx
- Detectors/MUON/MID/Raw/src/Decoder.cxx
- Detectors/MUON/MID/Raw/src/Encoder.cxx
- Detectors/MUON/MID/Raw/src/LocalBoardRO.cxx
- Detectors/MUON/MID/Raw/src/RawBuffer.cxx
- Detectors/MUON/MID/Raw/src/RawFileReader.cxx
- Detectors/MUON/MID/Raw/src/RawInfo.h
- Detectors/MUON/MID/Raw/test/CMakeLists.txt
- Detectors/MUON/MID/Raw/test/bench_Raw.cxx
- Detectors/MUON/MID/Raw/test/testCrateMapper.cxx
- Detectors/MUON/MID/Raw/test/testRaw.cxx
- Detectors/MUON/MID/Workflow/src/RawReaderSpec.cxx
- Detectors/MUON/MID/Workflow/src/RawWriterSpec.cxx
The old MID encoder/decoder assumed that the CRU user logic could merge the info coming from different GBTs.
This is actually not possible, so a new data format was implemented.
Thenew code makes use of the recent HBFUtils to correctly treat the RDHs.
The PR consists of several atomic commits: please do not squash.
> Modify MID raw data decoder/encoder to cope with the new user logic

- Framework/Core/test/test_CCDBFetcher.cxx
- Framework/Core/test/test_CallbackService.cxx
- Framework/Core/test/test_CustomGUIGL.cxx
- Framework/Core/test/test_CustomGUISokol.cxx
- Framework/Core/test/test_DanglingInputs.cxx
- Framework/Core/test/test_DanglingOutputs.cxx
- Framework/Core/test/test_Forwarding.cxx
- Framework/Core/test/test_FrameworkDataFlowToDDS.cxx
- Framework/Core/test/test_GenericSource.cxx
- Framework/Core/test/test_Parallel.cxx
- Framework/Core/test/test_ParallelPipeline.cxx
- Framework/Core/test/test_ParallelProducer.cxx
- Framework/Core/test/test_SimpleDataProcessingDevice01.cxx
- Framework/Core/test/test_SingleDataSource.cxx
- Framework/Core/test/test_Task.cxx
- Framework/Core/test/test_TimePipeline.cxx
- Framework/TestWorkflows/src/dataSamplingParallel.cxx
- Framework/TestWorkflows/src/dataSamplingPodAndRoot.cxx
- Framework/TestWorkflows/src/dataSamplingTimePipeline.cxx
- Framework/TestWorkflows/src/o2DataQueryWorkflow.cxx
- Framework/TestWorkflows/src/o2DiamondWorkflow.cxx
- Framework/TestWorkflows/src/o2DummyWorkflow.cxx
- Framework/TestWorkflows/src/o2ParallelWorkflow.cxx
- Framework/TestWorkflows/src/o2SyncReconstructionDummy.cxx
- Framework/TestWorkflows/test/test_MakeDPLObjects.cxx
Reference variable have to be used to refer to resources created by
DataAllocator::make. Otherwise the variable is simply copied and the data
does not correctly end up in the output.
EDIT:
The examples and tests have been consistently changed even though for the returned
reference to gsl::span (make<messageable>(Output{}, size)) it is also working without
reference because gsl::span provides copy constructor and transfers the underlying
buffer to the copy.
TODO: while doing this search and replace, many of the unit test and test workflows
have been found in a need-urgently-maintenace state. Some are not compile at all,
some do not check for data integrity, some are inconststent.
An (incomplete) list:
- o2-testworkflows-datasampling-time-pipeline does not run
- data integrity check should …
> Fixing DPL test workflows to use reference variable

- Detectors/ITSMFT/ITS/QC/TestDataReaderWorkflow/src/TestDataReader.cxx
- Detectors/ITSMFT/common/base/include/ITSMFTBase/Digit.h
- Detectors/ITSMFT/common/base/src/Digit.cxx
- Detectors/ITSMFT/common/simulation/src/Digitizer.cxx
mROFRame per digit is not used since we used external reference on digits belonging to a given ROFrame
> Eliminate unused itsmft::Digit::mROFrame data member

- Framework/Core/src/FrameworkGUIDevicesGraph.cxx
This will show a red stop sign and a yellow triangle for
errors and warnings.
> DPL GUI: use icons to signal errors / warnings

- DataFormats/MemoryResources/include/MemoryResources/MemoryResources.h
- run/O2SimDeviceRunner.cxx
The violations were introduced by #2722 and #2675 
I am wondering thy the error was not catched by the CI for these PRs or why they were merged despite.
> Fix codechecker violations

- Detectors/TRD/simulation/CMakeLists.txt
- GPU/Common/GPUCommonMath.h
- GPU/GPUTracking/Base/GPUReconstruction.cxx
- GPU/GPUTracking/Base/GPUReconstructionCPU.cxx
- GPU/GPUTracking/CMakeLists.txt
- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/Interface/GPUO2Interface.cxx
- GPU/GPUTracking/Merger/GPUTPCGMMergerGPU.cxx
- GPU/GPUTracking/Standalone/display/GPUDisplay.cxx
- GPU/GPUTracking/Standalone/qa/GPUQA.cxx
- GPU/GPUTracking/Standalone/standalone.cxx
- GPU/GPUTracking/TRDTracking/GPUTRDTracker.cxx
- GPU/GPUTracking/TRDTracking/GPUTRDTrackerGPU.cxx
- dependencies/FindOpenMPMacOS.cmake
- dependencies/O2Dependencies.cmake
@sawenzel : let's give this a try. I think this is how it should be done with modern CMake. OpenMP_FOUND was old style. If this works on MacOS, we can do away with the custom FindOpenMP.
> Fix OpenMP CMake

- GPU/Common/GPUCommonDefAPI.h
- GPU/Common/GPUDef.h
Macros for GPU thread block dimensions should be exposed outside of Tracking code.
> Move GRID dimension macros to CommonDefAPI

- Detectors/TPC/reconstruction/src/GPUCATracking.cxx
- GPU/Common/GPUCommonDef.h
- GPU/GPUTracking/Base/GPUGeneralKernels.h
- GPU/GPUTracking/Base/GPUSettings.cxx
- GPU/GPUTracking/Base/GPUSettings.h
- GPU/GPUTracking/Interface/GPUO2Interface.cxx
- GPU/GPUTracking/Merger/GPUTPCGMMerger.cxx
- GPU/GPUTracking/Merger/GPUTPCGMPropagator.h
- GPU/GPUTracking/Merger/GPUTPCGMTrackParam.cxx
- GPU/GPUTracking/Merger/GPUTPCGMTrackParam.h
- GPU/GPUTracking/SliceTracker/GPUTPCNeighboursCleaner.h
- GPU/GPUTracking/SliceTracker/GPUTPCNeighboursFinder.h
- GPU/GPUTracking/SliceTracker/GPUTPCStartHitsFinder.h
- GPU/GPUTracking/SliceTracker/GPUTPCStartHitsSorter.h
- GPU/GPUTracking/SliceTracker/GPUTPCTrackLinearisation.h
- GPU/GPUTracking/SliceTracker/GPUTPCTrackParam.h
- GPU/GPUTracking/SliceTracker/GPUTPCTrackletConstructor.h
- GPU/GPUTracking/SliceTracker/GPUTPCTrackletSelector.h
- Tracking with bz=0 failed before in continuous mode due to a floating point exception when estimating the shift of a track in z with infinite radius leading to an undefined shift.
- This also adds a nominal Pt value (currently defaulting to 200 MeV) which is applied when bz = 0 (< 0.01 kG). The value cannot be set externally yet because command line passing for the options of the TPC workflow is still missing.
- I verified whether this nominal value remains stable during the tracking, and it more or less the case (within 1 per mille).
> Improvements for bz=0 tracking

- Framework/Utils/test/test_RootTreeReader.cxx
This handles the fact that getCount() is in [0,9] while kTreeSize
is 10 resulting in the fact that the source would not always quit
before the sink.
> Actually quit test when no more data to read

- Detectors/MUON/MID/Raw/CMakeLists.txt
- Detectors/MUON/MID/Raw/exe/CMakeLists.txt
- Detectors/MUON/MID/Raw/exe/CRUBareDataChecker.cxx
- Detectors/MUON/MID/Raw/exe/CRUBareDataChecker.h
- Detectors/MUON/MID/Raw/exe/README.md
- Detectors/MUON/MID/Raw/exe/mid-raw-checker.cxx
- Detectors/MUON/MID/Raw/exe/mid-rawdump.cxx
- Detectors/MUON/MID/Raw/include/MIDRaw/CRUBareDecoder.h
- Detectors/MUON/MID/Raw/include/MIDRaw/ELinkDecoder.h
- Detectors/MUON/MID/Raw/src/CRUBareDecoder.cxx
- Detectors/MUON/MID/Raw/src/ELinkDecoder.cxx
This PR consists of two commits: one implementing the decoder and the other implementing 2 utilities to check the raw data (using the decoder).
A README.md is provided to explain how to run the checks.
The commits are atomic: please do not squash.
> MID decoder for raw data obtained without the CRU user logic

- DataFormats/simulation/include/SimulationDataFormat/MCTrack.h
- Detectors/ZDC/simulation/CMakeLists.txt
- Detectors/ZDC/simulation/include/ZDCSimulation/Detector.h
- Detectors/ZDC/simulation/include/ZDCSimulation/SpatialPhotonResponse.h
- Detectors/ZDC/simulation/include/ZDCSimulation/ZDCSimParam.h
- Detectors/ZDC/simulation/src/Detector.cxx
- Detectors/ZDC/simulation/src/SpatialPhotonResponse.cxx
- Detectors/ZDC/simulation/src/ZDCSimulationLinkDef.h
This PR provides
1. An easier accounting and summing up of hits. It is now done just per primary track.
This seems to be sufficient and avoids complicated user logic to detect when to start a new hit.
(We can go back to such a scheme if required)
2. Possibility to extract the actual spatial response image (in terms of number of photons triggered per optical fibre). This is useful for the machine learning fast simulation studies.
Extraction has to be switched on via a parameter option.
> ZDC: new hit accounting and possibility to extract spatial calorimeter response

- GPU/GPUTracking/TRDTracking/GPUTRDInterfaces.h
- GPU/GPUTracking/TRDTracking/GPUTRDTracker.cxx
- GPU/GPUTracking/TRDTracking/GPUTRDTracker.h
- GPU/GPUTracking/TRDTracking/GPUTRDTrackerDebug.h
- GPU/GPUTracking/TRDTracking/macros/checkDbgOutput.C
Hi @davidrohr 
when I implemented some optimizations for the TRD tracking I did not see a noticeable speedup. With callgrind I saw that most time for the tracking is spent in the propagate function. Currently I propagate the track to each tracklet in the chambers where the track ends up for a comparison. This is needed because of the misalignment of the chambers (the TRD space points are at different radii). If I skip these propagation steps and only propagate once to the middle of the TRD chamber I get a speedup factor of ~18 on a single core!
So I think the greatest potential for a performance optimization is here. I could use `GPUTPCGMPropagator::GetPropagatedYZ` instead of the full propagation, but then the chi2 prediction is not correct. 
Or should I try to implement my own propagate …
> TRD tracker performance optimization

- doc/doxyfile.in
- Exclude processing md* files and directories
- Changed INPUT back to @CMAKE_SOURCE_DIR@
> New attempt to eliminate unwanted empty README pages in Doxygen doc:

- macro/CMakeLists.txt
- macro/analyzeOriginHits.C
This macro determines the origin of each track leaving at least one hit in
a detector and plots the initial energy of the corresponding track.
> Hit - origin count macro

- Detectors/TPC/workflow/src/PublisherSpec.cxx
@matthiasrichter w/o this the flows requiring TPC input do not exit on completion due to the dangling inputs sink device not knowing that it should not expect data anymore (e.g. o2-tpcits-match-workflow)
> Signal endOfStream when ready to quit

- Detectors/TRD/base/include/TRDBase/Digit.h
- Detectors/TRD/macros/CheckDigits.C
- Detectors/TRD/macros/CheckHits.C
- Detectors/TRD/simulation/include/TRDSimulation/Digitizer.h
- Detectors/TRD/simulation/src/Detector.cxx
- Detectors/TRD/simulation/src/Digitizer.cxx
This PR adds the following:
- Correct type for digitized signals: `float` instead of `int`. Only ADC values need to be integer type, signals al continues variables. Now we have:
```
typedef std::uint16_t ADC_t;                                      // the ADC value type
typedef float Signal_t;                                           // the signal value type
typedef std::array<ADC_t, kTB> ArrayADC_t;                        // the array ADC - the main member of the Digit class
typedef std::array<Signal_t, kTB + 1> ArraySignal_t;              // the signal array + 1 element for mc label indexing - for the digitization process only
typedef std::vector<Digit> DigitContainer_t;                      // the digit container type to send the digits to the DPL
typedef std::unordered_map<int, …
```
> TRD: Fixed ADC spectrum

- Framework/Utils/test/test_RootTreeReader.cxx
- Framework/Utils/test/test_RootTreeWriterWorkflow.cxx
The EOS condition allows to drop the logic for triggering the workflow
termination.
Also make sure not to publish any more data after the EOS condition has
been sent. The publisher of the RootTreeReader test was constantly pumping
data into the workflow. This can conflict with the device termination and
produces the error which sometimes makes the test fail
Failed sending on socket foo.push, reason: Interrupted system call
This is the actual cause for the problem tried to be fixed in d4743769.
> Using the end-of-stream condition in the RootTreeReader/Writer tests

- Detectors/ZDC/simulation/src/Detector.cxx
Hi @coppedis 
Could you please check the last lines of the patch (L308/309): the getDetIDandSecID assigns
detector=ZEM and sector=ch1 or ch2 but then in the old code at these lines the sector was overridden to 0 (non-existent for ZEM, leads to crash in digitization), since volID is 157 while mZEMVolID is 157.
With this patch instead of checking the volID I am checking the assigned detector, so no wrong channel is assigned.
> Fix: wrong ZEM could be assigned

- Common/MathUtils/CMakeLists.txt
- Common/MathUtils/include/MathUtils/Bracket.h
- Common/MathUtils/include/MathUtils/Primitive2D.h
- Common/MathUtils/include/MathUtils/Utils.h
- Common/MathUtils/src/MathUtilsLinkDef.h
- Common/MathUtils/src/Primitive2D.cxx
- DataFormats/Detectors/ITSMFT/common/include/DataFormatsITSMFT/Cluster.h
- DataFormats/Detectors/ITSMFT/common/include/DataFormatsITSMFT/CompCluster.h
- DataFormats/Reconstruction/include/ReconstructionDataFormats/Track.h
- DataFormats/Reconstruction/src/Track.cxx
- DataFormats/common/include/CommonDataFormat/InteractionRecord.h
- Detectors/GlobalTracking/CMakeLists.txt
- Detectors/GlobalTracking/include/GlobalTracking/MatchTOF.h
- Detectors/GlobalTracking/include/GlobalTracking/MatchTPCITS.h
- Detectors/GlobalTracking/include/GlobalTracking/MatchTPCITSParams.h
- Detectors/GlobalTracking/src/GlobalTrackingLinkDef.h
- Detectors/GlobalTracking/src/MatchTPCITS.cxx
- Detectors/GlobalTracking/src/MatchTPCITSParams.cxx
- Detectors/GlobalTrackingWorkflow/include/GlobalTrackingWorkflow/TPCITSMatchingSpec.h
- Detectors/GlobalTrackingWorkflow/src/MatchTPCITSWorkflow.cxx
- Detectors/GlobalTrackingWorkflow/src/TPCITSMatchingSpec.cxx
- Detectors/GlobalTrackingWorkflow/src/tpcits-match-workflow.cxx
- Detectors/ITSMFT/ITS/reconstruction/CMakeLists.txt
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/RecoGeomHelper.h
- Detectors/ITSMFT/ITS/reconstruction/src/ITSReconstructionLinkDef.h
- Detectors/ITSMFT/ITS/reconstruction/src/RecoGeomHelper.cxx
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/ChipMappingITS.h
- macro/run_match_TPCITS.C
AfterBurner is not yet fully functional (by default off, can be activated via ``o2-tpcits-match-workflow --configKeyValues "tpcitsMatch.runAfterBurner=true"``) but still want to merge to avoid divergences.
> TPC/ITS matching fixes + AfterBurner

- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
- Utilities/Mergers/include/Mergers/MergerBuilder.h
- Utilities/Mergers/src/Merger.cxx
- Utilities/Mergers/src/MergerBuilder.cxx
In simple cases, default policy implementations from CompletionPolicyhelpers
are used.
> Cleaning up usage of DPL CompletionPolicy

- Detectors/TRD/base/include/TRDBase/Digit.h
- Detectors/TRD/simulation/include/TRDSimulation/Digitizer.h
- Detectors/TRD/simulation/src/Digitizer.cxx
In preparation for adding pileup to the TRD digitizer.
- Use of a signal array structure instead of extra time bin for keeping MC label index.
- Cleaning of Digit class, making it POD. Signal handler methods moved to the Digitizer, since they are not used elsewhere for now.
> TRD: Use of a signal array structure instead of extra time bin for keeping MC label index

- Common/SimConfig/include/SimConfig/SimConfig.h
- Common/SimConfig/src/SimConfig.cxx
- Generators/CMakeLists.txt
- Generators/include/Generators/Generator.h
- Generators/include/Generators/GeneratorHepMC.h
- Generators/include/Generators/GeneratorTGenerator.h
- Generators/include/Generators/Trigger.h
- Generators/include/Generators/TriggerParticle.h
- Generators/include/Generators/TriggerParticleParam.h
- Generators/share/external/multiphi_trigger.C
- Generators/src/Generator.cxx
- Generators/src/GeneratorFactory.cxx
- Generators/src/GeneratorHepMC.cxx
- Generators/src/GeneratorTGenerator.cxx
- Generators/src/GeneratorsLinkDef.h
- Generators/src/Trigger.cxx
- Generators/src/TriggerParticle.cxx
- Generators/src/TriggerParticleParam.cxx
This PR provides a way to attach triggers to event generators.
The event generators supported are those that implement the `o2::eventgen::Generator` protocol, namely that inherit from the abstract base class and provide a realisation of the pure virtual functions.
Triggers are defined as classes that implement the `o2::eventgen::Trigger` protocol and can be added to an event generator. The specification of the trigger can be fully costumised by defining the logic in the `o2::eventgen::Trigger::fired(TClonesArray *particles)` function, which receives all particles generated by a given event generator. The user can analyse the event and decide whether to trigger the reconstruction on that event (`return true`) or not (`return false`). If the trigger does not fire, the event generator will …
> Provide a way to trigger on generated event

- Framework/Core/test/test_ProcessorOptions.cxx
Follow-up to 7aa2497c, DPL unit test test_ProcessorOptions still failing
occasionally. Skipping now also sending of further messages after sending
the end of stream control command.
The error occurs when sending on a FairMQ channel is interrupted when the
devices are shut down. The problem is that the producer is continuously sending.
Failed sending on socket xyz, reason: Interrupted system call
This can probably be fixed on a FairMQ level.
> [O2-1049] test_ProcessorOptions flawed termination logic fails

- Steer/include/Steer/InteractionSampler.h
For very large per-BC interaction rate (>100, i.e. IR > 1e9 with default bunch filling)
the interacting BC sampling was stuck due to the numerical limitations of truncated
Poisson generation algo.
> Fix in InteractionSampler for mu>100

- macro/CMakeLists.txt
- macro/analyzeDigitLabels.C
- macro/analyzeHits.C
- prodtests/check_embedding_pileup.sh
A Root macro permitting to analyse the digit labels
automatically for signs of embedding / pileup.
The goal is to use this to check if the labels
satisfy our expectations.
The macro can be much reduced once
we have proper naming schemes in place.
> Macro to analyse and check labels for digits

- Detectors/MUON/MCH/Contour/README.md
- Detectors/MUON/MCH/Mapping/Factory/README.md
- Detectors/MUON/MCH/Mapping/Impl3/README.md
- Detectors/MUON/MCH/Mapping/README.md
- Detectors/MUON/MCH/Mapping/SegContour/README.md
- Detectors/MUON/MCH/Mapping/test/src/README.md
- Detectors/MUON/MCH/README.md
- Detectors/MUON/MCH/Raw/Decoder/README.md
- Detectors/MUON/MCH/Raw/ElecMap/README.md
- Detectors/MUON/MCH/Raw/README.md
- Detectors/MUON/MCH/Raw/Tools/README.md
- Detectors/MUON/MID/README.md
- Detectors/MUON/README.md
Documentation only.
- avoid to pollute top level Doxygen menu
- group all muon tracker doc under MCH and all muon identifier doc under MID
> [DOC] Trying to get organisation of pages correct in doxygen

- macro/CMakeLists.txt
- macro/duplicateHits.C
This macro replicates each entry in the simulation
output n-times and makes it easy to artificially
scale up input to digitizer etc.
The macro can also be used to construct event sequences
that must exhibit pileup.
> Macro allowing to duplicate simulated hits

- DataFormats/Detectors/ITSMFT/common/include/DataFormatsITSMFT/ROFRecord.h
- DataFormats/Detectors/ITSMFT/common/src/ITSMFTDataFormatsLinkDef.h
- Detectors/ITSMFT/ITS/workflow/CMakeLists.txt
- Detectors/ITSMFT/ITS/workflow/include/ITSWorkflow/TrackWriterSpec.h
- Detectors/ITSMFT/ITS/workflow/include/ITSWorkflow/VertexReaderSpec.h
- Detectors/ITSMFT/ITS/workflow/src/CookedTrackerSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/TrackReaderSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/TrackWriterSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/TrackerSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/VertexReaderSpec.cxx
- macro/run_trac_ca_its.C
- macro/run_trac_its.C
Hi @pzhristov, this PR will store together with ITS tracks the vector of seeding vertices (of the type ``o2::dataformats::Vertex<o2::dataformats::TimeStamp<int>>``) from the vertexer @mconcas + vector ROFRecords for navigation over them (for every ITS ROF it points on the entry of the 1st vertex of this ROF and number of vertices found). They will be read-out by the ITS TrackReader device together with tracks. One can also read vertices + their ROFRecords only by the standalone VertexReader.
Sample code to access them from the DPL: 
````
auto vertices = pc.inputs().get<gsl::span<Vertex>>("vertices");
auto verticesROF = pc.inputs().get<gsl::span<o2::itsmft::ROFRecord>>("verticesROF");
for (const auto& rf : verticesROF) {
printf("%d Vertices for ROF ", rf.getNEntries());      
rf.print(); …
```
> Output for ITS vertices + standalone reader

- Framework/Core/include/Framework/DataAllocator.h
- Framework/Core/src/DataAllocator.cxx
Using const reference as return for string to matching channel name, i.e.
internal string variable from matching output route. The rout configuration
is stable during computation. This avoids one level of allocation.
> DPL: small optimization to DataAllocator

- GPU/GPUTracking/CMakeLists.txt
Refactoring of TPC Cluster Finder left several headers uninstalled.
@shahor02 : I couldn't test locally, since I am currently rebuilding my aliBuild O2 setup. These headers were missing. Modulo typos, it should fix your issue.
> Install missing GPU TPC Cluster Finder header files

- Generators/src/GeneratorsLinkDef.h
This fixes build issue on centos with o2-dataflow defaults where HepMC is disabled. The same pragma appears later at L32, appropriately guarded, so I guess this was intended to be removed.
fixes Jira: [O2-1051](https://alice.its.cern.ch/jira/browse/O2-1051)
> build: Fix build with o2-dataflow defaults without HepMC (O2-1051)

- DataFormats/Detectors/EMCAL/CMakeLists.txt
- DataFormats/Detectors/EMCAL/include/DataFormatsEMCAL/MCLabel.h
- DataFormats/Detectors/EMCAL/src/DataFormatsEMCALLinkDef.h
- Detectors/EMCAL/simulation/CMakeLists.txt
- Detectors/EMCAL/simulation/include/EMCALSimulation/Digitizer.h
- Detectors/EMCAL/simulation/include/EMCALSimulation/LabeledDigit.h
- Detectors/EMCAL/simulation/include/EMCALSimulation/SimParam.h
- Detectors/EMCAL/simulation/src/Digitizer.cxx
- Detectors/EMCAL/simulation/src/DigitizerTask.cxx
- Detectors/EMCAL/simulation/src/EMCALSimulationLinkDef.h
- Detectors/EMCAL/simulation/src/SimParam.cxx
- Steer/DigitizerWorkflow/src/EMCALDigitWriterSpec.cxx
- Steer/DigitizerWorkflow/src/EMCALDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/EMCALDigitizerSpec.h
The modifications are
1.) accounting for the 4 different phases when dividing the energy into time bins
2.) introducing the 700 ns delay (the value can be modified)
3.) simulating noise digits at the beginning of each 1500 ns period
4.) accumulating digits during the 1500 ns period
5.) summing digits and passing them to the DigitizerSpec at the end of each 1500 ns period
> [EMCAL-501] modified timing in Digitizer

- Detectors/TPC/reconstruction/include/TPCReconstruction/TPCFastTransformHelperO2.h
- Detectors/TPC/reconstruction/src/TPCFastTransformHelperO2.cxx
- Detectors/TPC/reconstruction/test/testTPCFastTransform.cxx
- GPU/TPCFastTransformation/TPCFastTransformGeo.cxx
- Add roc number to the interface to the SpaceCharge Correction. It is needed to avoid the ambiguity of the TPC side identification at nominal Z~=0.
- Temporary switch off an automatic calibration of the spline grid. It needs to be updated.
> update of the TPCFastTransform interface

- GPU/GPUTracking/Base/hip/CMakeLists.txt
There should be a better way....
But for now, let's just also remove -ggdb not only -g.
> GPU: Fix removal of -g/-ggdb debug option for AMD HIP

- Detectors/EMCAL/simulation/include/EMCALSimulation/Detector.h
- Detectors/EMCAL/simulation/src/Detector.cxx
Volume ID for the SCMX (scintillator) volume different
when constructing the geometry and in the VMC specifically
for geant4. In order to circumvent this the sensitive volumes
are added with registerSensitiveVolumeAndGetVolID, and for
the SCMX volume the resulting index is used for the volume
cache.
> [O2-1037] Fix handling of SCMX volume cache for Geant4

- DataFormats/Detectors/FIT/FV0/include/DataFormatsFV0/BCData.h
- DataFormats/Detectors/FIT/FV0/src/BCData.cxx
- Detectors/FIT/FV0/macro/readFV0Digits.C
- Detectors/FIT/FV0/simulation/include/FV0Simulation/DigitizationParameters.h
- Detectors/FIT/FV0/simulation/include/FV0Simulation/Digitizer.h
- Detectors/FIT/FV0/simulation/src/Digitizer.cxx
Cleanup, optimization and one significant bug fix:
- Bug: `SimulateLightYield()` always returned number of photons set as input, instead of reducing their number by a factor of ~40. The present fix results in the similar reduction factor in CPU time of digitization.
- Cleanup: removed unused `channels` and `triggers` members of `BCData`
- Minor optimizations (% replaced with `if`, followed by counter reset)
> FV0 digitization - optimization and bug fix

- Framework/Core/include/Framework/DispatchControl.h
- Framework/Core/include/Framework/DispatchPolicy.h
- Framework/Core/include/Framework/MessageContext.h
- Framework/Core/include/Framework/Output.h
- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/src/DataProcessor.cxx
- Framework/Core/test/test_StaggeringWorkflow.cxx
Main extensions:
- sending messages in one multimessage at the end of computation
- implementing trigger matcher in `DispatchPolicy`
While messages which become ready for sending during computation are scheduled,
a trigger matcher decides when to send all scheduled messages. All messages
are sent as multimessage. This makes sure that data sets belonging together
will be received together on the receiver side and simplifies implementation
of `CompletionPolicy`.
> DPL: Extending dispatching policy

- Framework/Core/include/Framework/DataSampling.h
- Framework/Core/src/CompletionPolicyHelpers.cxx
- Framework/TestWorkflows/src/o2DiamondWorkflow.cxx
- Framework/Utils/src/esd-2-arrow-converter.cxx
Cleaning also up includes of CompletionPolicy.h and using the default
completion policy utilities.
> DPL: Regexp matching in CompletionPolicyHelpers::defineByName

- Detectors/ITSMFT/MFT/base/include/MFTBase/Geometry.h
- Detectors/ITSMFT/MFT/base/src/Geometry.cxx
- Detectors/ITSMFT/MFT/base/src/HeatExchanger.cxx
- Detectors/ITSMFT/MFT/simulation/src/Detector.cxx
Addition of a new parameter sGrooves to create or not the grooves of the MFT heat exchangers, default is sGrooves =0 to save time and memory in simulations.
> Control of the grooves creation on heat exchangers

- Framework/Core/include/Framework/DataRef.h
- Framework/Core/include/Framework/InputRecord.h
- Framework/Core/src/InputRecord.cxx
- Framework/Core/test/test_InputRecord.cxx
The iterator API did not reflect the features introduced with the completion policies. Slots might be invalid.
- filtering out invalid input slots from the iteration
- `nullptr` as default values of DataRef members
- fixing const'ness of `InputRecord::isValid` method
> DPL: Improving InputRecord iterator

- Detectors/ITSMFT/ITS/workflow/src/TrackerSpec.cxx
For some reasons getting a span as ``pc.inputs().get<gsl::span<const itsmft::CompClusterExt>>(...)`` leads to 
/Type mismatch: attempt to extract a non-messagable object from message with unserialized data/  exception.
With ``pc.inputs().get<gsl::span<itsmft::CompClusterExt>>(...)`` everything works fine.
> Fix: avoid using <const T> in pc.inputs().get<gsl::span<T>>

- DataFormats/Detectors/TPC/include/DataFormatsTPC/ZeroSuppression.h
- GPU/GPUTracking/Base/GPUReconstructionConvert.cxx
- GPU/GPUTracking/Standalone/tools/testCL.sh
- GPU/GPUTracking/TPCClusterFinder/ClusterAccumulator.cxx
- GPU/GPUTracking/TPCClusterFinder/DecodeZS.cxx
Store the total number of ADC samples in the header, for fast computation of cluster memory layout after decoding.
> Minor change to TPC ZS Format

- Framework/Core/CMakeLists.txt
- Framework/Core/test/test_AnalysisDataModel.cxx
This is to debug issues with ASoA which seem to appear only
when using the AnalysisDataModel classes.
> DPL Analysis: introduce an AnalysisDataModel specific test

- Framework/Core/include/Framework/Output.h
- Explicitely deleting copy constructor and assignment operator because
that would require to copy the stack instance
- Adding move assignment operator
- Correcting move constructor
> DPL: Cleaning up class o2::framework::Output

- Detectors/ITSMFT/common/simulation/src/Digitizer.cxx
G4 sometimes creates particles which are few seconds late wrt collision. Digitization of hits from such
unphisical particles requires generation of few 100K RO frames...
This protection will exclude processing of hits with time_in_event > 20\mus. A warning will be printed
for the first 10 excluded hits
> Protect ITS digitization from G4 hits with huge times

- Steer/DigitizerWorkflow/src/SimReaderSpec.cxx
- Steer/DigitizerWorkflow/src/TPCDigitizerSpec.cxx
endOfStream control event is issued by the SimReader device as data source
of the workflow. The event is propagated through the DPL workflow devices.
DPL decides how to change the state of the device and can terminate devices.
> Using endOfStream in the digitizer workflow

- Detectors/TPC/workflow/include/TPCWorkflow/ClustererSpec.h
- Detectors/TPC/workflow/src/ClustererSpec.cxx
- Detectors/TPC/workflow/src/PublisherSpec.cxx
- Detectors/TPC/workflow/src/RecoWorkflow.cxx
- Detectors/TPC/workflow/src/tpc-reco-workflow.cxx
1. Simplifying the completion policy in TPC workflow
The custom completion policy was implemented in a complecated way to make
sure that data and mc of the same sector are available before starting the
computation. After moving to grouped output messages for one computation/each
triggered dispatch in commit f6d950b, we can rely on the fact that these
two inputs are arriving together.
The custom dispatch policy of the TPC reco workflow has been extended to trigger
dispatch on published digits/clusters/etc and publishing the optional mc data
before.
2.  Removing obsolete DIGTRIGGERS channel in the tpc-reco-workflow
The TPCDigitizer publishes also the DIGTRIGGERS channel but the information
is not used in the connected cluster finder. Before introducing a central
gatherer for dangling …
> Updating TPC reco workflow

- Detectors/ITSMFT/ITS/simulation/src/V3Services.cxx
- Detectors/Passive/src/Pipe.cxx
While converting from TGeo to Geant4, two badly shaped Polycones were found (see JIRA tickets https://alice.its.cern.ch/jira/browse/O2-546 and https://alice.its.cern.ch/jira/browse/O2-1045). In both cases a section, where both inner and outer radii change, was wrongly coded resulting in a surface of zero thickness.
The bugs were fixed by properly defining the change of first the outer radius and then the inner radius so as to have a surface of realistic thickness.
> Bug fix in two badly shaped Polycones

- DataFormats/Detectors/TPC/include/DataFormatsTPC/ZeroSuppression.h
- GPU/GPUTracking/Base/GPUReconstructionConvert.cxx
- GPU/GPUTracking/TPCClusterFinder/DecodeZS.cxx
- GPU/GPUTracking/TPCClusterFinder/DecodeZS.h
- GPU/GPUTracking/TPCClusterFinder/GPUTPCClusterFinderKernels.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCClusterFinderKernels.h
- GPU/GPUTracking/TPCClusterFinder/GPUTPCSharedMemoryData.h
First parallelization level over threads. Still to come in independent follow-up PRs:
- parallelize over ADC sequences.
- Prefetch 8kb page into shared memory.
- Decode into target buffer directly instead of using the streamBuffer cache
> GPU: Add first thread-parallelization for ZS decoding over pad rows

- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/SliceTracker/GPUTPCSliceData.h
Fix long-standing problem if incorrectly found adjacent clusters on GPU. Number of clusters after clusterizer was updated from upper bound to real number, but the GPU tracker was initialized before and not updated, leading to a shift in adjacent cluster IDs.
> GPU: Fix missing synchronization of number of clusters after clusterizer

- GPU/Common/GPUDef.h
- GPU/GPUTracking/TPCClusterFinder/DecodeZS.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCSharedMemoryData.h
This is the final threading implementation for now.
In the future, one could also parallelize over multiple 8kb pages.
Shared memory is 48kb, which would allow to cache 5 pages per multiprocessor in parallel to have more GPU threads running concurrently.
But this would make the code even more complicated. Before, some benchmarks are needed to judge whether this is necessary.
> Full multi-threaded GPU ZS decoding, parallelized over ADC sequences

- Generators/CMakeLists.txt
- Generators/include/Generators/GeneratorPythia8.h
- Generators/include/Generators/GeneratorPythia8Param.h
- Generators/share/egconfig/pythia8_hf.cfg
- Generators/share/egconfig/pythia8_hi.cfg
- Generators/share/egconfig/pythia8_inel.cfg
- Generators/src/GeneratorFactory.cxx
- Generators/src/GeneratorPythia8.cxx
- Generators/src/GeneratorPythia8Param.cxx
- Generators/src/GeneratorsLinkDef.h
- macro/run_sim_pythia8hi.C
This PR replaces the Pythia8 event generator interface with a new interface that complies with the `o2::eventgen::Generator` protocol.
This enables the use of event generator triggers as provided in PR #2772 on the native Pythia8 interface.
The previous Pythia8 interface implemented in `Generators/src/Pythia8Generator.cxx` is replaced by `Generators/src/GeneratorPythia8.cxx` throughout the O2. The original file `Generators/src/Pythia8Generator.cxx` is still kept in place for the time being and will be removed at a later stage.
Changes in `Generators/src/GeneratorFactory` are done accordingly. Notice that the already-existing Pythia8 configurations selectable with -g option in o2-sim (pythia8, pythia8hf, pythia8hi) are still available. On the other hand, the configuration has been moved …
> Pythia8 generator compliant with o2::eventgen::Generator protocol

- Generators/share/egconfig/pythia8_hi.cfg
There was a mistype in the pythia8 configuration file.
> Fix to pythia8 heavy-ion configuration

- GPU/Common/CMakeLists.txt
- GPU/Common/GPUCommonAlgorithm.h
- GPU/Common/GPUCommonAlgorithmThrust.h
- GPU/GPUTracking/Base/hip/CMakeLists.txt
- GPU/GPUTracking/Base/hip/ctest/testGPUsortHIP.hip.cxx
Include sorting for AMD GPUs in HIP implementation using [AMD's implementation of the THRUST API](https://github.com/ROCmSoftwarePlatform/rocThrust).  Includes unit tests.
> Sorting for AMD HIP

- Detectors/ITSMFT/ITS/tracking/hip/include/ITStrackingHIP/VectorHIP.h
- Detectors/ITSMFT/ITS/tracking/hip/include/ITStrackingHIP/VertexerTraitsHIP.h
- Detectors/ITSMFT/ITS/tracking/hip/src/StreamHIP.hip.cxx
- Detectors/ITSMFT/ITS/tracking/hip/src/VertexerTraitsHIP.hip.cxx
Errors to fix:
```
/home/qon/alice-builder/sw/SOURCES/O2/v1.1.0/0/Detectors/ITSMFT/ITS/tracking/hip/include/ITStrackingHIP/VectorHIP.h:18:10: error: inclusion of deprecated C++ header 'assert.h'; consider using 'cassert' instead [modernize-deprecated-headers]
/home/qon/alice-builder/sw/SOURCES/O2/v1.1.0/0/Detectors/ITSMFT/ITS/tracking/hip/include/ITStrackingHIP/VertexerTraitsHIP.h:50:11: error: prefer using 'override' or (rarely) 'final' instead of 'virtual' [modernize-use-override]
/home/qon/alice-builder/sw/SOURCES/O2/v1.1.0/0/Detectors/ITSMFT/ITS/tracking/hip/src/StreamHIP.hip.cxx:24:12: error: use '= default' to define a trivial default constructor [modernize-use-equals-default]
/home/qon/alice-builder/sw/SOURCES/O2/v1.1.0/0/Detectors/ITSMFT/ITS/tracking/hip/src/StreamHIP.hip.cxx:29:12 …
```
> ITS-GPU: Fix undetected checkode errors

- cmake/O2AddTestWrapper.cmake
That variable can be used to redirect output of the tests under the
given directory, instead of the default CMAKE_CURRENT_BINARY_DIR.
> [WIP] [O2-583] Add cmake variable DEFAULT_TEST_OUTPUT_DIRECTORY

- Detectors/ZDC/simulation/include/ZDCSimulation/SpatialPhotonResponse.h
- Detectors/ZDC/simulation/src/Detector.cxx
- Detectors/ZDC/simulation/src/SpatialPhotonResponse.cxx
* be able to calculate photon count per readout channel
* associate a detectorID to the response image
* keep hit time in response
> ZDC: Improvements on SpatialPhotonResponse

- Framework/Core/include/Framework/CompletionPolicy.h
- Framework/Core/include/Framework/CompletionPolicyHelpers.h
- Framework/Core/src/CompletionPolicyHelpers.cxx
- Framework/Core/test/test_CompletionPolicy.cxx
We aim to implement depending packages like e.g. QualityControl independently
of the actual policy implementation by using definitions from the CompletionPolicy
header file.
Adding helper method to retrieve DataHeader from CompletionPolicy input set
This PR is supposed to be merge before #2886 and AliceO2Group/QualityControl#304 will be adjusted accordingly.
> Define signature of CompletionPolicy callback in the header and adding helper method

- Detectors/Raw/CMakeLists.txt
- Detectors/Raw/README.md
- Detectors/Raw/include/DetectorsRaw/HBFUtils.h
- Detectors/Raw/include/DetectorsRaw/RawFileReader.h
- Detectors/Raw/include/DetectorsRaw/RawFileReaderWorkflow.h
- Detectors/Raw/src/HBFUtils.cxx
- Detectors/Raw/src/RawFileReader.cxx
- Detectors/Raw/src/RawFileReaderWorkflow.cxx
- Detectors/Raw/src/rawfile-reader-workflow.cxx
- Detectors/Raw/src/rawfileCheck.cxx
Allows to feed raw data from files (create from MC or real ones) into the DPL workflows w/o going via
``readout.exe -> StfBuilder -> o2-dpl-raw-proxy `` processes.
See README for details.
> Raw data files reader workflow

- Detectors/TPC/calibration/src/CalibPedestal.cxx
Shift binning by -0.5 to account for the discrete nature of ADC values.
Fit and statistics data are evaluated at the bin centre.
> Fix pedestal value calculation

- GPU/GPUTracking/Base/hip/CMakeLists.txt
@mpuccio @mconcas @MichaelLettrich : They send the flag `-fno-gpu-rdc` which one has to pass to the compiler to avoid the GPU compilation during linking.
> GPU: Compile GPU HIP code during compilation, not linking

- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFNoiseSuppression.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFNoiseSuppression.h
@davidrohr This PR removes redundant memcleans in the TPCClusterFinder. They were required because of a buffer overflow in the noise suppresion which is now fixed as well.
Also I removed additional memcleans that are already handled by the `resetMaps` kernel.
> Remove redundant memcleans in TPCClusterFinder

- Framework/Core/include/Framework/CompletionPolicy.h
- Framework/Core/include/Framework/CompletionPolicyHelpers.h
- Framework/Core/src/CompletionPolicyHelpers.cxx
- Framework/Core/test/test_CompletionPolicy.cxx
Making the default completion policies more flexible by introducing an optional
device matcher to allow fine-grained configuration with the helpers
Checking if the template type argument of getHeader is already a pointer.
> DPL: Update to completion policy helpers

- GPU/GPUTracking/Base/GPUParam.inc
This PR is #2454 rebased onto master
> Fix: min 0.01 was imposed on TPC cluster err^2 instead of err

- Framework/Core/src/DataDescriptorQueryBuilder.cxx
@ktf : This fixes the crash in the GPU CI for me.
The problem is that `assignLastStringMatch` etc. may fail, leaving currentOrigin etc. undefined.
Dereferencing it leads to memory corruption depending on the compiler, and in the GPU CI container it is causing the crash.
I am not 100% sure if my fix is correct, perhaps we should also bail out with an exception?
But since at least for now, the `test_Framework_test_DataDescriptorMatcher` runs into the condition that the `assignLastStringMatch` fails, we would have to fix the test first before we throw a fatal exception in the QueryBuilder.
> Fix memory corruption in Framework/DataDescriptorQueryBuilder

- Detectors/MUON/MCH/Raw/Encoder/CMakeLists.txt
- Detectors/MUON/MCH/Raw/Encoder/Payload/BareElinkEncoder.h
- Detectors/MUON/MCH/Raw/Encoder/Payload/BareElinkEncoderMerger.h
- Detectors/MUON/MCH/Raw/Encoder/Payload/BitSet.cxx
- Detectors/MUON/MCH/Raw/Encoder/Payload/BitSet.h
- Detectors/MUON/MCH/Raw/Encoder/Payload/CruBufferCreator.cxx
- Detectors/MUON/MCH/Raw/Encoder/Payload/CruBufferCreator.h
- Detectors/MUON/MCH/Raw/Encoder/Payload/DataBlock.cxx
- Detectors/MUON/MCH/Raw/Encoder/Payload/ElinkEncoder.cxx
- Detectors/MUON/MCH/Raw/Encoder/Payload/ElinkEncoder.h
- Detectors/MUON/MCH/Raw/Encoder/Payload/ElinkEncoderMerger.h
- Detectors/MUON/MCH/Raw/Encoder/Payload/Encoder.cxx
- Detectors/MUON/MCH/Raw/Encoder/Payload/EncoderImpl.h
- Detectors/MUON/MCH/Raw/Encoder/Payload/GBTEncoder.h
- Detectors/MUON/MCH/Raw/Encoder/Payload/UserLogicElinkEncoder.h
- Detectors/MUON/MCH/Raw/Encoder/Payload/UserLogicElinkEncoderMerger.h
- Detectors/MUON/MCH/Raw/Encoder/Payload/benchBitSet.cxx
- Detectors/MUON/MCH/Raw/Encoder/Payload/testBareElinkEncoder.cxx
- Detectors/MUON/MCH/Raw/Encoder/Payload/testBitSet.cxx
- Detectors/MUON/MCH/Raw/Encoder/Payload/testElinkEncoder.cxx
- Detectors/MUON/MCH/Raw/Encoder/Payload/testEncoder.cxx
- Detectors/MUON/MCH/Raw/Encoder/Payload/testGBTEncoder.cxx
- Detectors/MUON/MCH/Raw/Encoder/README.md
- Detectors/MUON/MCH/Raw/Encoder/include/MCHRawEncoder/DataBlock.h
- Detectors/MUON/MCH/Raw/Encoder/include/MCHRawEncoder/Encoder.h
- Detectors/MUON/MCH/Raw/README.md
This PR only deals with the encoding of the payload part, in order to minimize the PR's size. 
The handling of the headers (RDH) to reach a valid raw data format will be done in a follow-up PR.
The encoders are separated at elink level for the two raw data format we have (bare and user logic), but there's only one implementation for GBT level and up.
```
├── CMakeLists.txt
├── Payload
│   ├── BareElinkEncoder.h
│   ├── BareElinkEncoderMerger.h
│   ├── BitSet.cxx
│   ├── BitSet.h
│   ├── CruBufferCreator.cxx
│   ├── CruBufferCreator.h
│   ├── DataBlock.cxx
│   ├── ElinkEncoder.cxx
│   ├── ElinkEncoder.h
│   ├── ElinkEncoderMerger.h
│   ├── Encoder.cxx
│   ├── EncoderImpl.h
│   ├── GBTEncoder.h
│   ├── UserLogicElinkEncoder.h
│   ├── UserLogicElinkEncoderMerger.h
│   ├── benchBitSet.cxx
│   …
```
> [MRRTF-87] [O2-972] Initial support for MCH Raw Data Encoder

- GPU/Common/GPUDefConstantsAndSettings.h
- GPU/Common/GPUDefGPUParameters.h
- GPU/GPUTracking/Base/GPUReconstruction.h
- GPU/GPUTracking/Base/GPUReconstructionCPU.cxx
- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/SliceTracker/GPUTPCGeometry.h
- GPU/GPUTracking/SliceTracker/GPUTPCTracker.cxx
GPUCA_SORT_STARTHITS was not set correctly since some time, which crashed processing of Run 2 data, and could lead to memory corruption in any case. This sets it correctly, also fixes the behavior when it is not set, and adds some debugging output.
> GPU: Fix sorting of start hits

- GPU/GPUTracking/Base/GPUOutputControl.h
- GPU/GPUTracking/Base/GPUReconstruction.cxx
- GPU/GPUTracking/Base/GPUReconstruction.h
- GPU/GPUTracking/Base/GPUReconstructionCPU.h
- GPU/GPUTracking/Base/GPUReconstructionDeviceBase.cxx
- GPU/GPUTracking/Base/GPUReconstructionDeviceBase.h
- GPU/GPUTracking/Base/cuda/GPUReconstructionCUDA.cu
- GPU/GPUTracking/Base/cuda/GPUReconstructionCUDA.h
- GPU/GPUTracking/Base/hip/GPUReconstructionHIP.h
- GPU/GPUTracking/Base/hip/GPUReconstructionHIP.hip.cxx
- GPU/GPUTracking/Base/opencl-common/GPUReconstructionOCLInternals.h
- GPU/GPUTracking/Global/GPUChain.h
- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/SliceTracker/GPUTPCSliceOutput.cxx
- GPU/GPUTracking/Standalone/standalone.cxx
Can provide external output buffers (standalone benchmark does it already)
Can register the memory for GPU DMA transfers.
Can write compressed TPC clusters into it (more is comming)
> Initial support of externally provided GPU output buffers in O2

- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/AnalysisTask.h
- Framework/Core/include/Framework/Expressions.h
- Framework/Core/src/ASoA.cxx
- Framework/Core/src/Expressions.cxx
- Framework/Core/test/test_ASoA.cxx
- Framework/Core/test/test_AnalysisTask.cxx
Streamlines the manipulation of filtered/join/concat by tracking the types of predefined tables so they can be bound from external inputs.
> DPL: adapt filters to be used over joins and concats

- Detectors/Raw/src/HBFUtils.cxx
ITS is still using RDH with mentioning v3 but with the format corresponding to v4.
So, we enforce the RDHv3 to be treated as RDHv4
> Treat RDHv3 and RDH4

- GPU/Common/GPUCommonMath.h
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFPeakFinder.cxx
I opened bug reports, but so long we can live with these workarounds.
This is btw the first time clang11 master and the llvm converter are able to process the full GPU source code. Next step is to set up some hardware and actually test it.
> GPU: 2 minor workarounds for bugs in clang and llvm spirv converter

- Framework/Core/include/Framework/AODReaderHelpers.h
- Framework/Core/include/Framework/DataAllocator.h
- Framework/Core/include/Framework/TableTreeHelpers.h
- Framework/Core/src/CommonDataProcessors.cxx
- Framework/Core/src/DataAllocator.cxx
- Framework/TestWorkflows/src/o2AODDummy.cxx
If one needs DataAllocator to create arrow tables, the
TableBuilder.h header should be included before DataAllocator.h.
This way we avoid rebuilding everything when ASoA.h changes.
We should probably do the same for boost and ROOT.
> DPL: decouple DataAllocator from TableBuilder

- Framework/Core/src/CommonDataProcessors.cxx
This actually fills the FairMQ queue in any case, so we must avoid it. One more reason to do the adaptive rate.
> DPL: do not sleep when no dangling outputs available

- Framework/Core/test/test_StaggeringWorkflow.cxx
Reduce staggering time to speed up the unit test. Removing obsolete code, the
compute method is not invoked any more after issuing end of stream, the local
handling is not necessary any more.
> Cleaning and speeding up the StaggeringWorkflow unit test

- Framework/Core/include/Framework/MessageContext.h
- Framework/Core/src/DataProcessor.cxx
This is a follow-up to commit f6d950b
1. Introducing a registry of channel names in the MessageContext
The unique references of string objects from the registry allow fast access
and association of messages to actual FairMQChannels by avoiding string
allocation.
2. Optimization to unordered_map
Using pointer to channel string as key to avoid allocation of strings.
The ContextObjects hold references of the string variables from the registry.
The string references from the OutputRoute definition of the device do not
fulfill the requirement to refer to one single string object per channel,
because the device stores a vector of OutputRoutes.
> DPL: Optimization for associating output messages with actual channels

- Framework/Utils/include/DPLUtils/RootTreeReader.h
- Framework/Utils/test/test_RootTreeReader.cxx
Branch configuration now allows specification of a type as template parameter
of the helper struct BranchDefinition. The type is used to deduce the optimal
serialization method. By default (without type), all objects are paublished
ROOT serialized. Messagable types with ROOT dictionary can now by published
unserialized when the type is provided in the reader configuration.
> DPL Util: RootTreeReader extension to support unserialized output

- Detectors/TPC/reconstruction/include/TPCReconstruction/Clusterer.h
- Detectors/TPC/reconstruction/include/TPCReconstruction/HwClusterer.h
- Detectors/TPC/reconstruction/src/ClustererTask.cxx
- Detectors/TPC/reconstruction/src/HwClusterer.cxx
Does not change the actual algorithm which accesses data object via iterators,
the read-only span can be build from any array and vector, e.g. pmr::vector or
even with custom allocator.
> Using span of o2::tpc::Digit as input to TPC HwClusterer

- Detectors/EMCAL/base/CMakeLists.txt
- Detectors/EMCAL/base/include/EMCALBase/RCUTrailer.h
- Detectors/EMCAL/base/src/RCUTrailer.cxx
- Detectors/EMCAL/reconstruction/CMakeLists.txt
- Detectors/EMCAL/reconstruction/include/EMCALReconstruction/AltroDecoder.h
- Detectors/EMCAL/reconstruction/src/AltroDecoder.cxx
- Detectors/EMCAL/reconstruction/src/RawReaderFile.cxx
- Detectors/EMCAL/reconstruction/src/RawReaderMemory.cxx
As with the current FW/readoutCard version the
StopBit in the RDH header is not set, a valid
RCU trailer must be required in order to decide
whether the payload ends with the current page.
In addition move RCUTrailer to EMCALbase as
it will be needed as well in the raw data
encoding.
> [EMCAL-642] Determine end-of-data via valid RCU trailer

- Detectors/CPV/workflow/src/DigitsPrinterSpec.cxx
- Detectors/EMCAL/workflow/src/DigitsPrinterSpec.cxx
- Detectors/PHOS/workflow/src/DigitsPrinterSpec.cxx
- Framework/TestWorkflows/src/o2DataQueryWorkflow.cxx
- Steer/DigitizerWorkflow/src/CollisionTimePrinter.cxx
- Steer/DigitizerWorkflow/src/EMCALDigitWriterSpec.cxx
These files are using std::cout but not including <iostream>, which, depending on the setup, misses the symbol. I think when std::cout is used, one should explicitly include <iostream>
> Add missing includes

- Detectors/TPC/workflow/include/TPCWorkflow/PublisherSpec.h
- Detectors/TPC/workflow/src/ClustererSpec.cxx
- Detectors/TPC/workflow/src/PublisherSpec.cxx
- Detectors/TPC/workflow/src/RecoWorkflow.cxx
Providing the data type of the objects to be published in the RootTreeReader
branch configuration to allow the DPL IO to decide upon serialization method.
The unserialized data is extracted as span on the receiver side.
Requires #2982 and #2987.
> TPC workflow: sending data from publishers unserialized

- Detectors/TOF/reconstruction/src/Decoder.cxx
to suppress  [-Wformat=] warnings: format %d expects argument of type int, but argument 2 has type long..
> suppress compilation warnings

- Detectors/TPC/reconstruction/src/GPUCATracking.cxx
- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- GPU/GPUTracking/Interface/GPUO2InterfaceConfiguration.h
Hi @matthiasrichter 
To test your https://github.com/AliceO2Group/AliceO2/pull/2982 I've fixed the TPC code to use ``span<o2::tpc::Digit>`` instead of the vector in the clusterizers and tracking interface, but it still dies with 
````
Exception caught: Inconsistent serialization method for extracting span
````
I've checked in the gdb, the RootTreeReader still uses ``snapshot(mKey, std::move(ROOTSerializedByClass(*data, mClassInfo)));`` to send the digits.
So, the behaviour is exactly the same as w/o your patch (which is cherry-picked in this PR).
If you cherry-pick my commit from this PR, you can check yourself  it as:
````
o2-sim -m TPC  -n 20
o2-sim-digitizer-workflow -b
o2-tpc-reco-workflow   --infile tpcdigits.root --output-type tracks
o2-tpc-reco-workflow  --disable-mc --ca-clusterer …
```
> Use span<digits>  instead of a vector in the TPC tracking

- Framework/Core/include/Framework/DataRefUtils.h
- Framework/Core/test/test_ParallelPipeline.cxx
Workflow spec helper MergeInputs requires amend callback to adjust also
binding name in order to have unique binding identifiers
Fixing and enhancing unit test test_ParallelPipeline
- unique binding names
- fixed to check of pipeline numbers for every channel on the final consumer
the intended check was not working because the shared object can not be
used in different processes, but the ambigous binding names made the test
work anyhow
- testing also partially valid InputRecord by using completion policy 'consume'
Adding a helper method DataSpecUtils::isValid
> Bugfix: test_ParallelPipeline

- Detectors/EMCAL/simulation/include/EMCALSimulation/Detector.h
- Detectors/EMCAL/simulation/src/Detector.cxx
Removing EMCAL mother volume XEN (envelope) and putting the supermodules directly into cave. Creating EMCAL mother volumes would always run into overlaps with PHOS/CPV.
> [O2-1079, EMCAL-637] Fix overlaps between EMCAL and PHOS/CPV

- Detectors/MUON/MID/Raw/include/MIDRaw/RawBuffer.h
- Detectors/MUON/MID/Raw/src/RawBuffer.cxx
- Detectors/MUON/MID/Raw/src/RawFileReader.cxx
- Detectors/MUON/MID/Raw/test/testRaw.cxx
- Allow to navigate on RDHs
- Prevent crash on empty HBs
- Save the last HB page in case it was not fully consumed (this prevents the invalidation of the pointer to the last RDH)
Specific tests of the raw buffer are implemented as well.
The commits are atomic: please do not squash
> Improve the MID Raw buffer

- Framework/Core/include/Framework/DataProcessingDevice.h
- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/test/test_CallbackService.cxx
- Framework/Core/test/test_SimpleStringProcessing.cxx
This should reduce the amount of CPU used by data processors when they are idle
while retaining the ability to increase back the rate, should it be needed.
> DPL: introduce exponential backoff when idle (O2-626, O2-714)

- Framework/Core/include/Framework/AnalysisTask.h
- Framework/Core/src/Expressions.cxx
- Framework/Core/test/test_AnalysisTask.cxx
@ktf filters were not working after latest update due to the type not being decayed. ExpressionInfo vector was not populated when inputs were attached leading to a segfault.
> DPL Analysis: fix for crash when using filters

- Framework/Core/src/DataProcessingDevice.cxx
Looks like we still compute dangling inputs, even when we sent an "endOfStream"
event. IIRC, the idea behind this was that we might want to resume a stream
on some external input (e.g. a new file queued to be processed). However under
no circumstances this should be considered a high frequency mode, so we always
backoff when we are in StreamingState::Idle.
> DPL: backoff devices with dangling inputs (O2-714)

- CCDB/include/CCDB/CcdbApi.h
- CCDB/src/CcdbApi.cxx
The CCDB objects are now written under the standard
name "ccdb-object". Some extra treatment added, to be
backward compatible.
Fixes https://alice.its.cern.ch/jira/browse/O2-1155
> CCDB: Standardize key referring to serialized object

- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/Core/src/DeviceSpecHelpers.h
- The two methods are now static methods of class DeviceSpecHelpers
- skip name parameter in the channel config string if name is empty
> DPL:  Making inputChannel2String and outputChannel2String class methods

- Framework/Core/include/Framework/CompletionPolicy.h
- Framework/Core/include/Framework/CompletionPolicyHelpers.h
- Framework/Core/include/Framework/DataRelayer.h
- Framework/Core/include/Framework/DispatchPolicy.h
- Framework/Core/include/Framework/InputRecord.h
- Framework/Core/include/Framework/InputSpan.h
- Framework/Core/include/Framework/MessageSet.h
- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/src/DataRelayer.cxx
- Framework/Core/src/InputRecord.cxx
- Framework/Core/test/benchmark_DataRelayer.cxx
- Framework/Core/test/benchmark_InputRecord.cxx
- Framework/Core/test/test_CompletionPolicy.cxx
- Framework/Core/test/test_DataAllocator.cxx
- Framework/Core/test/test_DataRelayer.cxx
- Framework/Core/test/test_InputRecord.cxx
- Framework/Utils/test/test_RootTreeWriter.cxx
Implementing support for multiple input parts per cache entry. @ktf in the end I decided to keep the layout of the cache and indexing. My original idea was to store an `{index, number of entries}`-pair in the cache, the index referring to a position in a list of messages per input. But having separate lists for all the inputs, i.e. rows in the cache, is pretty much the same like having one list for all and using the existing indexing.
- CompletionPolicy API has been adjusted to work with `span<DataRef>` instead of `span<PartRef>`
- DataRelayer cache entries changed to `MessageSet` containing vector of `PartRef` owning the input messages
- extending `InputSpan` to hold multiple inputs per route
- extending `InputRecord` API to access multiple parts per input slots through an iterator API …
> DPL support for vectored IO

- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/Detector.h
- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/V3Services.h
- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
- Detectors/ITSMFT/ITS/simulation/src/V3Services.cxx
The ITS Outer Barrel Support Cones, which connect the MB layers with the OB layers, were implemented in the geometry following the latest blueprints. Also the Trays for the cables on Side A were implemented. The Wrapper volumes were adapted to avoid fake overlaps.
> OB Support Cones and Trays implemented in geometry

- Detectors/TRD/base/CMakeLists.txt
- Detectors/TRD/base/include/TRDBase/FeeParam.h
- Detectors/TRD/base/include/TRDBase/TRDGeometry.h
- Detectors/TRD/base/include/TRDBase/TRDGeometryBase.h
- Detectors/TRD/base/src/CalDet.cxx
- Detectors/TRD/base/src/FeeParam.cxx
- Detectors/TRD/base/src/TRDGeometry.cxx
- Detectors/TRD/base/test/testTRDGeometry.cxx
- Detectors/TRD/simulation/src/Detector.cxx
- Detectors/TRD/simulation/src/Digitizer.cxx
- Detectors/TRD/workflow/CMakeLists.txt
- Detectors/TRD/workflow/src/TRDDigitizerSpec.cxx
- GPU/GPUTracking/Standalone/tools/createGeo.C
- GPU/GPUTracking/Standalone/tools/createGeo.sh
Convert TRDGeometry to a singleton.
1. removing the TRDGeometry instance in every Tracklet.
2. fix where TRDGeometry is used in various places.
3. move Tracklet functions into TRDGeometry, moving the geometry logic out of tracklets and where it should live.
4. Add some tests for the added functions.
> Convert TRDGeometry to a singleton O2-1197

- Framework/Core/CMakeLists.txt
- Framework/Core/src/dplRun.cxx
This is a standalone driver which can be used
to run DPL configurations dumped via the --dump
option.
> DPL: introduce standalone driver

- Framework/Core/include/Framework/DeviceSpecHelpers.h
- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/Core/src/runDataProcessing.cxx
- Framework/Core/test/test_DeviceSpec.cxx
- Framework/Core/test/test_DeviceSpecHelpers.cxx
- Framework/Core/test/test_FrameworkDataFlowToDDS.cxx
- Framework/Core/test/test_Graphviz.cxx
- Framework/Core/test/test_TimeParallelPipelining.cxx
- Framework/Core/test/test_WorkflowSerialization.cxx
Make the DeviceSpecHelpers available for e.g. the DPL utilities.
> Moving DeviceSpecHelpers.h to Framework/Core/include/Framework

- Analysis/Tutorials/CMakeLists.txt
- Analysis/Tutorials/src/aodreader.cxx
- Analysis/Tutorials/src/aodwriter.cxx
- Analysis/Tutorials/src/dynamicColumns.cxx
- Framework/Core/include/Framework/DataAllocator.h
- Framework/Core/include/Framework/RootTableBuilderHelpers.h
- Framework/Core/include/Framework/TableTreeHelpers.h
- Framework/Core/src/AODReaderHelpers.cxx
- Framework/Core/src/CommonDataProcessors.cxx
- Framework/Core/src/DataAllocator.cxx
- Framework/Core/src/WorkflowHelpers.cxx
The functionality was added to read and process data from any flat TTree in a task.
An example is provided by
Analysis/Tutorials/src/aodwriter.cxx
Analysis/Tutorials/src/aodreader.cxx
With aodwriter two tables are created and saved to a root file. In aodreader these trees are read and processed.
Usage:
o2-analysistutorial-aodwriter --aod-file AO2D.root --res-file tabletotree > log
o2-analysistutorial-aodreader --aod-file tabletotree_0.root > log
where AO2D.root is an aod file.
> read and process data from any flat tree

- Framework/Core/include/Framework/ExternalFairMQDeviceProxy.h
- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/Core/src/DeviceSpecHelpers.h
- Framework/Core/src/ExternalFairMQDeviceProxy.cxx
- Framework/Core/src/runDataProcessing.cxx
- Framework/Core/test/test_DeviceSpec.cxx
- Framework/Core/test/test_DeviceSpecHelpers.cxx
- Framework/Core/test/test_FrameworkDataFlowToDDS.cxx
- Framework/Core/test/test_Graphviz.cxx
- Framework/Core/test/test_TimeParallelPipelining.cxx
- Framework/Core/test/test_WorkflowSerialization.cxx
This reverts "Moving DeviceSpecHelpers.h to Framework/Core/include/Framework"
commit 0547343
We decided that the details of the builder logic should not be exposed.
Adding a helper method to ExternalFairMQDeviceProxy to provide the required functionality to
configure external channels.
> Keep DeviceSpecHelpers.h a private tool of the DPL builder logic

- Framework/Core/src/ChannelSpecHelpers.cxx
- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/Core/src/DeviceSpecHelpers.h
- Framework/Core/src/runDataProcessing.cxx
- Framework/Core/test/test_DeviceSpecHelpers.cxx
- Framework/Core/test/test_FrameworkDataFlowToDDS.cxx
Devices sitting on the same resource will use the same shared memory
pool. Notice how we set the FairMQ `--session` to be
`dpl_<driver-process-pid>`.
> DPL: enable shared memory backend

- Framework/Core/include/Framework/AnalysisTask.h
For a derived soa::Table, index column can be filled using the iterator to an indexed table directly, without invoking globalIndex().
> DPL Analysis: ability to use iterator of an indexed table directly

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/ExternalFairMQDeviceProxy.h
- Framework/Core/src/ExternalFairMQDeviceProxy.cxx
- Framework/Core/test/test_ExternalFairMQDeviceWorkflow.cxx
Adding specifyFairMQDeviceOutputProxy helper method to create a DataProcessorSpec
for a DPL processor with an out-of-band channel to relay DPL workflow data to an
external FairMQDevice device.
The output configuration is determined by one or multiple entries of the FairMQDevice
command line option '--channel-config' in the format. The binding of each input spec
must correspond to an output channel.
Adding unit test to connect an out-of-band output channel with a DPL input proxy,
but this must be disabled for the moment because of FairMQ printing an error message
when the input poller is aborted during device shutdown.
To be done in later update
> DPL: add utility to create external output proxies

- Steer/DigitizerWorkflow/src/GRPUpdaterSpec.cxx
- Steer/DigitizerWorkflow/src/GRPUpdaterSpec.h
- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
This commit fixes a problem in the digitizer workflow.
Up until now, this was only working with files named "o2sim.root"
and "o2sim_grp.root". Now it is possible to use arbitrary names
```
o2-sim-digitizer-workflow --GRP o2simTRD_grp.root --simFile o2simTRD.root -b --onlyDet TRD
```
> Digitizer workflow: Ability to use arbitrary GRP file

- Detectors/EMCAL/workflow/include/EMCALWorkflow/CellConverterSpec.h
- Detectors/EMCAL/workflow/include/EMCALWorkflow/DigitsPrinterSpec.h
- Detectors/EMCAL/workflow/include/EMCALWorkflow/PublisherSpec.h
- Detectors/EMCAL/workflow/src/CellConverterSpec.cxx
- Detectors/EMCAL/workflow/src/DigitsPrinterSpec.cxx
- Detectors/EMCAL/workflow/src/PublisherSpec.cxx
- Detectors/EMCAL/workflow/src/RecoWorkflow.cxx
Cell and digit vectors are supposed to handle the objects
from an entire time frame. For EMCAL the time frame will
contain several triggers. In order to separate data from
different triggers a second object, vector of TriggerRecords,
is provided in addition to the vector of objects marking
ranges belonging to the same trigger. The publisher has to
read the trigger records branch from the digit/cell tree
and provide it to the various workflows.
> [EMCAL-507, EMCAL-548, EMCAL-611, EMCAL-612] Prepare publishers for time frames

- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFStreamCompaction.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFStreamCompaction.h
- GPU/GPUTracking/TPCClusterFinder/GPUTPCClusterFinder.cxx
This PR fixes a buffer overflow in the compaction step. The cluster finder should now respect `mNMaxPeaks` and `mNMaxClusters`. Respecting `mNMaxClusterPerRow` should have been fixed in #2885. 
Interestingly `mNMaxClusters` was already too low for the simulated data. Thats why i increased it.
I wonder why that never caused any problems?
@davidrohr
> TPCClusterFinder: Fix buffer overflow

- Detectors/FIT/FDD/simulation/include/FDDSimulation/DigitizationParameters.h
- Detectors/FIT/FDD/simulation/include/FDDSimulation/Digitizer.h
- Detectors/FIT/FDD/simulation/src/Digitizer.cxx
Couple of optimizations in the digitizer as used by FV0. Requested in O2-1139.
> Optimization of the Digitizer

- Analysis/Tutorials/src/filters.cxx
- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/AnalysisDataModel.h
- Framework/Core/include/Framework/AnalysisTask.h
- Framework/Foundation/include/Framework/Pack.h
* Filters are now correctly processed when grouping
* Updated filters.cxx example
* Fixed index binds for unfiltered/ungrouped case
> DPL Analysis: use std:vector for filter selection

- CCDB/test/testCcdbApi.cxx
Snapshot only current test path to prevent test timeout.
This should fix the current problem with this test observed in the CI
> Fix testCcdbApi

- Detectors/Base/CMakeLists.txt
- Detectors/Base/test/README.md
- Detectors/Base/test/testDCAFitter.cxx
- Detectors/CMakeLists.txt
- Detectors/README.md
- Detectors/Vertexing/CMakeLists.txt
- Detectors/Vertexing/README.md
- Detectors/Vertexing/include/DetectorsVertexing/DCAFitterN.h
- Detectors/Vertexing/include/DetectorsVertexing/HelixHelper.h
- Detectors/Vertexing/src/DCAFitterN.cxx
- Detectors/Vertexing/src/VertexingLinkDef.h
- Detectors/Vertexing/test/testDCAFitterN.cxx
@ginnocen this is the arbitrary N-prong fitter (if you need N>3, let me know, will change the parameter). The see the Detectors/Base/README for details: the interface is essentially the same, just to get the tracks instead of ``getTrack0()`` , ``getTrack1()`` you should use ``getTrack(0)`` or ``getTrack(1)`` ...
I did not modify you vertexing class to account for the change since this would create a conflict with https://github.com/AliceO2Group/AliceO2/pull/3055 but eventually the current ``DCAFitter`` should be changed by ``DCAFitterN<2>``. Let me know if you want me to do this change, eventually, the old class should be eliminated.
At the moment there is a small instability (present also in the old DCAFitter) sometimes affecting the convergence efficiency (per-mille level for 2 prongs, …
> Templated secondary N-prong vertex fitter

- GPU/GPUTracking/Base/GPUMemorySizeScalers.h
- GPU/GPUTracking/TPCClusterFinder/GPUTPCClusterFinder.cxx
This PR adjusts the size of cluster buckets and fixes some naming issue in the memory scaler.
> TPCClusterFinder: Adjust maxCluster size and bucket size.

- Framework/Core/include/Framework/InputRecord.h
- Framework/Core/include/Framework/InputSpan.h
- Framework/Core/src/InputRecord.cxx
- Framework/Core/test/test_InputRecord.cxx
- fix the end iterator instance of part iterator
- making const what should be const
- bounds check before getNofParts callback to check against span size
- init InputRecord from InputSpan by move (which was intended but there was
an unwanted copy)
- making InputRecord::get<T>(DataRef) a static method
This method actually only requires the pointers from the DataRef argument, no
concrete object or state is needed.
At some point this can be also seperated from InputRecord, thus separating data
and serialization method.
> A few improvements to DPL InputRecord

- DataFormats/simulation/include/SimulationDataFormat/MCCompLabel.h
- Detectors/TRD/base/include/TRDBase/MCLabel.h
- Detectors/TRD/base/src/TRDBaseLinkDef.h
- macro/analyzeDigitLabels.C
* use standard MCCompLabel for TRD
* generalize MCCompLabel constructor
* benefit from custom streamer for MCTruthContainer for TRD
fixed https://alice.its.cern.ch/jira/browse/O2-1213
> TRD: Benefit from custom streamer for labels

- Steer/DigitizerWorkflow/src/EMCALDigitWriterSpec.cxx
- Steer/DigitizerWorkflow/src/EMCALDigitWriterSpec.h
The writer implementation does not implement any special handling for
EMCAL data, so it is replaced by the RootTreeWriter workflow utility to simplify the workflow.
@mfasDa, @sawenzel please check if this gives the expected result of the digitization. I have observed, that the digit properties are slightly different when running digitization repeatedly, independently of this PR. There seems to be a random component in the digitization. So I could not do a one-to-one comparison.
Is there a way to make the digitization deterministic? A switch or so, but did not find a configurable option in that respect.
> Using the standard RootTreeWriter in the DMCAL digitization

- Framework/Utils/CMakeLists.txt
- Framework/Utils/Readme.md
- Framework/Utils/src/dpl-output-proxy.cxx
Adding the o2-dpl-output-proxy utility provides a configurable output proxy workflow
to forward workflow output to out-of-band channels, meaning channels outside DPL.
Output channel(s) are defined with the FairMQ device channel configuration option.
Input to the proxy is defined by the DPL data spec syntax. The binding label is used
to match to a configured output channel. Binding can be the same for multiple data specs
in order to forward multiple input specs to the same channel.
Example:
o2-dpl-output-proxy --dataspec "channelname:TPC/TRACKS" --channel-config name=channelname,...
Upcoming:
> DPL: add an out-of-band output proxy

- GPU/TPCSpaceChargeBase/AliTPCPoissonSolver.cxx
- GPU/TPCSpaceChargeBase/AliTPCSpaceCharge3DCalc.cxx
- GPU/TPCSpaceChargeBase/AliTPCSpaceCharge3DCalc.h
Adopting changes from un-merged PR 2165 (https://github.com/AliceO2Group/AliceO2/pull/2165).
Bug fix in AliTPCPoissonSolver in loop range variables to allow different number of bins in z and r.
Changes in AliTPCSpaceCharge3DCalc:
* Adding local correction lookup tables for debug purposes
* Fixing z sign of SetInputSpaceCharge function
* Bug fixes in fast global distortion integration method
> New functionality and bug fixes for TPCSpaceChargeBase code 

- Detectors/MUON/MID/Raw/exe/CRUBareDataChecker.cxx
- Detectors/MUON/MID/Raw/include/MIDRaw/CrateParameters.h
- Detectors/MUON/MID/Raw/include/MIDRaw/ELinkDecoder.h
- Detectors/MUON/MID/Raw/include/MIDRaw/LocalBoardRO.h
- Detectors/MUON/MID/Raw/src/CRUBareDecoder.cxx
- Detectors/MUON/MID/Raw/src/CRUUserLogicDecoder.cxx
- Detectors/MUON/MID/Raw/src/CRUUserLogicEncoder.cxx
- Detectors/MUON/MID/Raw/src/ELinkDecoder.cxx
- Detectors/MUON/MID/Raw/src/LocalBoardRO.cxx
- Detectors/MUON/MID/Raw/src/RawInfo.h
This PR aims at reorganizing few constants/names used for MID raw data.
It consists of two commits:
- the first moves the functions to test the raw board status outside of CrateParameters...since they are not parameters of the crate, although they test some of them
- the second rename the event word into trigger word, in accordance with the name used in the readout electronics for the same word
The commits are atomic: please do not squash them
> Reorganize some MID constants/names

- Framework/Core/include/Framework/TableBuilder.h
- Framework/Core/test/test_TableBuilder.cxx
- Framework/Foundation/include/Framework/StructToTuple.h
This might reduce the amount of gymnastic required to serialize a
struct which matches the schema.
> DPL Analysis: it's now possible to pass structs to fill a table.

- GPU/GPUTracking/Base/GPUReconstructionKernels.h
- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/TPCClusterFinder/Array2D.h
- GPU/GPUTracking/TPCClusterFinder/CfUtils.h
- GPU/GPUTracking/TPCClusterFinder/ChargePos.h
- GPU/GPUTracking/TPCClusterFinder/ClusterAccumulator.cxx
- GPU/GPUTracking/TPCClusterFinder/ClusterAccumulator.h
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFChargeMapFiller.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFChargeMapFiller.h
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFClusterizer.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFClusterizer.h
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFDecodeZS.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFDeconvolution.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFDeconvolution.h
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFNoiseSuppression.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFNoiseSuppression.h
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFPeakFinder.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFPeakFinder.h
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFStreamCompaction.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFStreamCompaction.h
- GPU/GPUTracking/TPCClusterFinder/GPUTPCClusterFinder.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCClusterFinder.h
- GPU/GPUTracking/TPCClusterFinder/GPUTPCClusterFinderDump.cxx
- GPU/GPUTracking/TPCClusterFinder/clusterFinderDefs.h
This PR adjusts the ZS decoder to write charges directly to the chargeMap buffer. So the cluster finder only has to store charge positions instead of entire digits in intermediate buffers.
> TPCClusterFinder: Decode ZS directly to charge map.

- Framework/Core/src/DataProcessingDevice.cxx
Devices which have data-driven inputs and a timer or ccdb input couldn't properly receive an EndOfStream signal. They also have no way of knowing that an EndOfStream arrived on certain input channels, so they could trigger it on their own.
This changes the default behaviour of EndOfStream, so input channels marked as `Pull` (not related to the push-pull channel types) don't have to be completed, unless a certain device is a only data source. I am open to discuss other solutions for that, I will also have to see if that breaks anything else.
> Do not wait for EndOfStream on fake input channels

- CODEOWNERS
This is already the situation for all other detectors
except EMCAL
> Removing AliceO2Group/core from EMCAL codeowners

- CODEOWNERS
Adding @tdietel to the CODEOWENERS of the TRD detector for requesting PR reviews.
> Update TRD CODEOWENERS

- DataFormats/common/include/CommonDataFormat/InteractionRecord.h
- DataFormats/common/src/InteractionRecord.cxx
This reverts commit b9ea5d9cefb376b644c48375a5d884db3e8c41f2.
We are observing problems with writing the InteractionRecord to ROOT tree, like in #3098.
[12401:its-cluster-writer]: Fatal in <TBranchElement::InitializeOffsets>: Could not find the real data member 'ITSClustersROF.mBCData.user' when constructing the branch 'ITSClustersROF' [Likely an internal error, please report to the developers].
The same is for the ITSDigitWriter of the digitizer workflow.
Because of this sim_challenge is not running anymore.
> Revert "Allow usage of (padding) 2bytes in the IR for user data (#3083)"

- Detectors/EMCAL/simulation/include/EMCALSimulation/Digitizer.h
- Detectors/EMCAL/simulation/include/EMCALSimulation/SimParam.h
Fixed timing bug in Digitizer::readyToFlush(), set default busy time to 35 microseconds
> [EMCAL-501] fix timing bug, set busy time

- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CookedTracker.h
- Detectors/ITSMFT/ITS/reconstruction/src/CookedTracker.cxx
- Detectors/ITSMFT/ITS/workflow/src/ClusterWriterSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/ClustererSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/CookedTrackerSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/TrackWriterSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/TrackerSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/VertexReaderSpec.cxx
- Detectors/ITSMFT/MFT/tracking/include/MFTTracking/IOUtils.h
- Detectors/ITSMFT/MFT/tracking/src/IOUtils.cxx
- Detectors/ITSMFT/MFT/workflow/src/TrackerSpec.cxx
Hi Ruben, while working on the DPL IO API I came across these possible optimizations. I have so far quickly tested the standard its-reco-workflow with the cooked tracker, and from the first glimpse some histogrammed track parameters look the same. But verification would need a better one-to-one comparison, also for the MC labels.
Please have a look, and if there are some standard tests I'm happy to run those to verify the changes.
Optimization:
Avoid snapshot copies by allocating vectors directly in output message memory.
Cleanup:
The processors should be independent of the control, removing the forced
termination after one computation. The DPL now handles an end-of-stream
signal issued by upstream processors (data publishers) and automatically
terminates the workflow (depending on …
> Optimization for ITS tracking workflows and cleaning up workflow control

- Detectors/TRD/base/src/TRDBaseLinkDef.h
Since the TRD/MCLabel is just an alias to o2::MCCompLabel, adding it to LinkDef leads to duplicate dictionary.
This is to avoid ``Warning in <TInterpreter::ReadRootmapFile>: class  o2::MCCompLabel found in libO2TRDBase.so  is already in libO2SimulationDataFormat.so
``
> Do not generate dict.for alias of MCCompLabel

- Generators/src/GeneratorFactory.cxx
- prodtests/check_embedding_pileup.sh
- Use 1 muon per event instead of 100
- Fix the momentum range
- Use muons instead of pions when testing MCH, MFT, MID
> Improve default parameters for forward generators

- Analysis/Tasks/vertexerhf.cxx
- Framework/Core/include/Framework/AnalysisDataModel.h
Splitting TPC cluster information into findable, found, crossedrows, shared. Storing differences for better compression.
This increases the data by 16 bits for now. With some optimization we can reduce these fields from 24bits to 16 bits.
> adding detailed information about TPC clusters

- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/TPCClusterFinder/Array2D.h
- GPU/GPUTracking/TPCClusterFinder/ChargePos.h
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFNoiseSuppression.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCClusterFinder.cxx
This PR fixes a rounding issue when accessing 2D arrays, when the width / height of the array was not a multiple of the tiling width / height.
@davidrohr This also fixes the difference between cpu and gpu on edge charges.
> TPCClusterFinder: Fix rounding issue when accessing 2D array.

- Detectors/TRD/workflow/include/TRDWorkflow/TRDTrapSimulatorSpec.h
- Detectors/TRD/workflow/src/TRDDigitizerSpec.cxx
- Detectors/TRD/workflow/src/TRDTrapSimulatorSpec.cxx
- Detectors/TRD/workflow/src/TRDTrapSimulatorWorkFlow.cxx
- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
- Change the logic of disabling TrapSimulator.
- Remove the manual setting of time for digits.
- trdtracklets.root is no longer created when trapsimulator is disabled in digitizer.
- option parameters stay the same.
> fix disabling TRD trapsimulator

- Detectors/TPC/workflow/include/TPCWorkflow/RecoWorkflow.h
- Detectors/TPC/workflow/src/RecoWorkflow.cxx
- Detectors/TPC/workflow/src/tpc-reco-workflow.cxx
The running processors are configured by the type of desired output, like
e.g. raw, clusters, tracks. A writer process is by default added For each
of the configured outputs. When combining the workflow with other workflows,
the writers are not always necessary and can now be removed from the workflow
using the key 'disable-writer' in the '--output-type' option.
This can also be used to prevent a routing bug which is triggered when attaching
the DPL output proxy or the QC workflow to the TPC reco workflow.
o2-tpc-reco-workflow ... | o2-dpl-output-proxy --dataspec "dpl-output-proxy:TPC/TRACKS ...
The proxy is added between tracker and writer, however the writer is trying to
send back data to the proxy via a channel which is not existing
[23170:tpc-track-writer]: [23:46:43][ERROR] requested …
> Adding posibility to disable writers in tpc-reco-workflow

- CCDB/CMakeLists.txt
- CCDB/include/CCDB/CcdbApi.h
- CCDB/include/CCDB/CcdbObjectInfo.h
- CCDB/src/CcdbApi.cxx
- Common/Utils/CMakeLists.txt
- Common/Utils/include/CommonUtils/MemFileHelper.h
- Common/Utils/src/CommonUtilsLinkDef.h
- Common/Utils/test/testMemFileHelper.cxx
Moved repetetive TMemFile creation code to CommonUtils/MemFileHelper
Added possibility to store binary blob (e.g. TMemFile binary image), this should allow to
CCDB writer devices to be agnostic of the particular object type.
> Simplify and extend CcdbApi storeAs.. methods

- GPU/GPUTracking/Base/GPUHostDataTypes.h
- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/TPCClusterFinder/MCLabelAccumulator.h
@davidrohr This PR fixes the broken mc labels produced by the cluster finder.
Two bugs are fixed here. First one is that a kernel required for the mc labels wasn't called.
The second bug was caused by the implicit `MCCompLabel(bool noise)` constructor which caused the raw `uint64` labels to be treated as noise. I didn't change the definition in `MCCompLabel` because this implicit constructor is used all over the place. But some of these usages look like they might be bugs...
> TPCClusterFinder: Fix mc label behavior.

- Framework/Core/include/Framework/InputRecord.h
Support getting the sub-parts while doing so.
> DPL: unify the InputRecord::get API

- Analysis/DataModel/include/Analysis/Jet.h
- Analysis/Tasks/CMakeLists.txt
- Analysis/Tasks/jetfinder.cxx
- Analysis/Tutorials/CMakeLists.txt
- Analysis/Tutorials/src/jetAnalysis.cxx
- dependencies/FindFastJet.cmake
- dependencies/O2Dependencies.cmake
Hi @ktf,
as discussed with Jan and Nima, I started working on the integration of fastjet. As a first step, I would add linking against fastjet in AnalysisCore (with the intention of then using it for analysis and input to the skimming layer). If you have a better proposal, where or how to add this, let me know.
I will also add fastjet as a dependency to O2 in a PR against alidist.
Cheers,
Jochen
> Add jet finding

- CCDB/src/CCDBLinkDef.h
- Detectors/CMakeLists.txt
- Detectors/Calibration/CMakeLists.txt
- Detectors/Calibration/include/DetectorsCalibration/TimeSlot.h
- Detectors/Calibration/include/DetectorsCalibration/TimeSlotCalibration.h
- Detectors/Calibration/include/DetectorsCalibration/Utils.h
- Detectors/Calibration/workflow/CCDBPopulatorSpec.h
- Detectors/Calibration/workflow/ccdb-populator-workflow.cxx
- Detectors/TOF/calibration/CMakeLists.txt
- Detectors/TOF/calibration/include/TOFCalibration/LHCClockCalibrator.h
- Detectors/TOF/calibration/src/LHCClockCalibrator.cxx
- Detectors/TOF/calibration/src/TOFCalibrationLinkDef.h
- Detectors/TOF/calibration/testWorkflow/DataGeneratorSpec.h
- Detectors/TOF/calibration/testWorkflow/LHCClockCalibratorSpec.h
- Detectors/TOF/calibration/testWorkflow/data-generator-workflow.cxx
- Detectors/TOF/calibration/testWorkflow/lhc-clockphase-workflow.cxx
1) Detectors/Calibration defines base classes templates for use time slot definition (container for the data accumulated over a certain number of TFs) and their manipulation. It also provides a generic workflow which receives binary images of the calibration data (the content is irrelevant) accompanied by the ``CcdbObjectInfo`` and puts then on the CCDB
2) Detectors/TOF/calibration implements TOF specific data accumulation slots and their processing, as well as the workflow to aggregate asynchronously TFs from different EPNs and to extract calibration data for groups of TFs.
In real life, the channelling of data from different EPNs to this aggregator device will require a special proxy device (to be written), as a place-holder at the moment data from different EPNs is emulated by the …
> Sample workflows for calibration in groups of TFs, case of LHC clock calibration in TOF

- cmake/rootcling_wrapper.sh.in
Need to catch a non-zero return value from grep in case of not finding any occurence (most of the time hidden because of empty log files).
> Fix parsing of log from dictionary generation

- Framework/Utils/CMakeLists.txt
- Framework/Utils/Readme.md
- Framework/Utils/include/DPLUtils/DPLRawParser.h
- Framework/Utils/include/DPLUtils/RawParser.h
- Framework/Utils/test/test_DPLRawParser.cxx
The parser handles transparently input in the format of raw pages.
There three levels:
- the DPL processor has one or more input route(s)
- multiple parts per input route (split payloads or multiple input
specs matching the same route spec
- variable number of raw pages in one payload
The parser provides an iterator interface to loop over raw pages,
starting at the first payload at the first route and going to the
next route when all payloads are processed.
TODO:
> Adding DPL RawParser utility

- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/TableBuilder.h
- Framework/Core/test/test_ASoA.cxx
- Framework/Core/test/test_TableBuilder.cxx
For the moment we use 1 byte per bool.
> DPL Analysis: add initial support for boolean columns

- Framework/Utils/include/DPLUtils/RawParser.h
- Framework/Utils/test/test_RawParser.cxx
So far the fixed page size has been used to calculate the size of the payload,
simply because of the lack of information at the time of implmenting the parser.
The variable size of the payload is stored in the member memorySize in both
RDH v4 and v5. Since the raw parser does only supports those two versions at
the moment, the fix can be applied as it is. there is no need to support RDH v2
which has a member blockLength.
> Fix RawParser: set proper size estimate for payload

- Detectors/TRD/workflow/src/TRDTrapSimulatorSpec.cxx
@bazinski, @tdietel please check if the code works also with these optimizations.
We can avoid copies by using `DataAllocator::make` instead of snapshot,
the vector is then allocated directly in the message memory and send once
the computation is done.
Not sure what to do with the digits though, because the original code line
sending a snapshot is commented. Still the input object should be considered
const because we are doing optimizations on the API to avoid copied data also
here. That means one has to create a new vector from the input object (this
also makes it clear that there is a copy), or in this particular case here
I suggest to do the sorting on an index and use the sorted index to access
the individual objects from a read-only object.
> Using in-message vectors for the output of the TRDTrapSimulatorSpec

- Framework/Core/scripts/o2-datasampling-benchmark.sh
- Framework/Core/src/Dispatcher.cxx
- Framework/TestWorkflows/CMakeLists.txt
- Framework/TestWorkflows/src/dataSamplingBenchmark.cxx
This introduces a script which runs Data Sampling benchmarks and prints results to files. It is supposed to work both with zeromq and shmem transport (as enabled in this PR: https://github.com/AliceO2Group/AliceO2/pull/2670 ).
There is a mechanism which prevents the benchmark from allocating too much memory, to avoid deadlocks (Dispatcher need to copy data, but there is not enough memory for that and it waits until there is, but only Dispatcher can free it by processing messages).
However, with that fixed, I can see still some crashes related to shared memory (appearing only for larger throughputs/message payload sizes):
```
[193856:Dispatcher]:  *** Break *** bus error
[193856:Dispatcher]: essor_id=Dispatcher
...
[193856:Dispatcher]: …
```
> [QC-262] Data Sampling Benchmark

- Framework/Core/include/Framework/runDataProcessing.h
@ktf I've moved also the ``"readers"`` option after the customization, since most of specs use ``vector::swap`` to set their options. Please correct if this is wrong.
> Allow options customization before adding framework options

- Detectors/TPC/reconstruction/CMakeLists.txt
- Detectors/TPC/reconstruction/macro/createTPCSpaceChargeCorrection.C
Adding macro to create TPCFastTransform correction object for space-charge distortions.
> Macro to create TPC space-charge correction object to be used in reconstruction

- DataFormats/Detectors/EMCAL/CMakeLists.txt
- DataFormats/Detectors/EMCAL/doxymodules.h
- DataFormats/Detectors/EMCAL/include/DataFormatsEMCAL/Cell.h
- DataFormats/Detectors/EMCAL/include/DataFormatsEMCAL/Cluster.h
- DataFormats/Detectors/EMCAL/include/DataFormatsEMCAL/Digit.h
- DataFormats/Detectors/EMCAL/include/DataFormatsEMCAL/EventData.h
- DataFormats/Detectors/EMCAL/include/DataFormatsEMCAL/EventHandler.h
- DataFormats/Detectors/EMCAL/include/DataFormatsEMCAL/MCLabel.h
- DataFormats/Detectors/EMCAL/include/DataFormatsEMCAL/TriggerRecord.h
- DataFormats/Detectors/EMCAL/src/DataFormatsEMCALLinkDef.h
- DataFormats/Detectors/EMCAL/src/EventHandler.cxx
Providing easy access to objects (clusters / cells /
cell indices) from the same trigger within a
timeframe. Can be initialized with cells, clusters
(both separated) and cluster + cells together,
together with the corresponding trigger records.
The event data contains either empty gsl::spans
for the branches not initialized or the gsl::spans
with the range of objects belonging to the same
event. The event handler is stl-iterable as
bidirectional iterator.
> [EMCAL-645] Implemetation of an EMCAL event handler

- Detectors/CPV/testsimulation/plot_dig_cpv.C
- Detectors/CPV/testsimulation/plot_hit_cpv.C
- macro/run_digi.C
Due to missing includes these tests were failing when testing with new versions of FairRoot and MC packages
> Fixed missing includes in macros

- GPU/GPUTracking/Base/cuda/GPUReconstructionCUDA.cu
Only consider the device selected with --gpuDevice. So setting up the
device doesn't fail even when other devices are unavailable.
> GPU: Only look at selected gpuDevice in cuda backend

- prodtests/check_embedding_pileup.sh
The generated particle PID does not really matter since we do noyt simulate absorption elements.
The use of fwpigen allows to genarate a larger number of particles per event.
This prevents the case where no hit is created because the only produced muon falls outside the acceptance.
> Use fwpigen for MCH, MID and MFT in pileup tests

- Detectors/EMCAL/reconstruction/include/EMCALReconstruction/Clusterizer.h
- Detectors/EMCAL/reconstruction/src/Clusterizer.cxx
Making the EMCAL clusterizer more flexible regarding input by using
gsl::span for the read-only input data. GSL provides an automatic conversion
from std::vector.
This makes the code more flexible with respect to DPL IO API changes.
> Using gsl::span as input to EMCAL clusterizer

- DataFormats/MemoryResources/include/MemoryResources/MemoryResources.h
- DataFormats/MemoryResources/test/testMemoryResources.cxx
We want the allocator with the underlying stateful memory resource to be
propagated to target object on move assignment, a specific type trait
indicator needs to be defined.
> Allowing the SpectatorAllocator to be propagated

- Framework/Core/include/Framework/AnalysisTask.h
- Framework/Core/include/Framework/TableBuilder.h
- Framework/Core/test/benchmark_TableBuilder.cxx
- Framework/Core/test/test_TableBuilder.cxx
Using the two new methods of TableBuilder and WritingCursor
can result in much faster table building, especially for large table,
if the number of rows of the final table is (roughly) known in
advance.
> DPL Analysis: add reserve method for table building

- Steer/DigitizerWorkflow/src/TPCDigitRootWriterSpec.cxx
This makes the code more flexible towards upcoming API changes.
> Determining the type of input object from InputRecord::get result

- Detectors/GlobalTracking/include/GlobalTracking/MatchTOF.h
- Detectors/GlobalTracking/include/GlobalTracking/MatchTPCITS.h
- Detectors/GlobalTracking/src/MatchTOF.cxx
- Detectors/GlobalTracking/src/MatchTPCITS.cxx
- Detectors/GlobalTrackingWorkflow/src/TPCITSMatchingSpec.cxx
- Detectors/GlobalTrackingWorkflow/tofworkflow/src/RecoWorkflowSpec.cxx
Determining the type of the local FIT info variable from the InputRecord return
type. The info is passed as gsl::span to the workers, we benefit from the span
constructor provided by gsl::span.
This makes the code independent of upcoming API changes.
> Using gsl::span for the optional FIT info input of GlobalTracking workers

- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/Core/test/test_FrameworkDataFlowToDDS.cxx
FairMQ uses a session id (string) to set namespaces for shared memory regions, the
default argument is 'default'. Since 2b19ec21, DPL sets a session id string created
from the pid of the driver process, making it impossible to set the argument from the
command line.
Fixes:
```
Error: option '--session' cannot be specified more than once
```
> [O2-1252] DPL: make session id configurable from command line again

- Detectors/EMCAL/base/src/Geometry.cxx
- Convert remaining ALIC instances to cave
- Remove XEN from paths which was dropped due to
overlaps with CPV/PHOS
> [EMCAL-637] Fix geometry path in loading geo matrices

- Analysis/Tutorials/src/outputs.cxx
- Framework/Core/include/Framework/AnalysisTask.h
- Framework/Core/src/CommonDataProcessors.cxx
* Force ROOT not to store histo references in a default directory to allow having multiple histos with the same name
* Fix output object routing to use hashes 
* Remove extra 'std::move'
> DPL Analysis: prevent ROOT from overwriting histos in OutputObj

- DataFormats/Detectors/ITSMFT/common/include/DataFormatsITSMFT/ClusterPattern.h
- DataFormats/Detectors/ITSMFT/common/include/DataFormatsITSMFT/ClusterTopology.h
- DataFormats/Detectors/ITSMFT/common/include/DataFormatsITSMFT/TopologyDictionary.h
- DataFormats/Detectors/ITSMFT/common/src/ClusterPattern.cxx
- DataFormats/Detectors/ITSMFT/common/src/ClusterTopology.cxx
- DataFormats/Detectors/ITSMFT/common/src/ITSMFTDataFormatsLinkDef.h
- DataFormats/Detectors/ITSMFT/common/src/TopologyDictionary.cxx
- Detectors/ITSMFT/ITS/macros/test/CheckCOG.C
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/ClustererTask.h
- Detectors/ITSMFT/ITS/reconstruction/src/ClustererTask.cxx
- Detectors/ITSMFT/ITS/workflow/include/ITSWorkflow/ClustererSpec.h
- Detectors/ITSMFT/ITS/workflow/src/ClusterWriterSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/ClustererSpec.cxx
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/Clusterer.h
- Detectors/ITSMFT/common/reconstruction/src/BuildTopologyDictionary.cxx
- Detectors/ITSMFT/common/reconstruction/src/Clusterer.cxx
- macro/run_clus_itsSA.C
This PR opens a possibility to keep full cluster topology information for topology groups.
This information is stored "in parallel" with the clusters themselves. It does not take much disk
(or RAM) space, because the grouped topologies are rare.
The changes are backward compatible. Both old data structures and interfaces are preserved.
Saving the full topology information can be activated with an optional processing flag.
A use case for this additional information in an "offline" analysis is demonstrated in ITS/macros/test/CheckCOG.C macro (lines 108-113).
> Possibility to optionally save cluster topology information for grouped topologies

- Framework/Utils/Readme.md
- Framework/Utils/include/DPLUtils/DPLRawParser.h
- Framework/Utils/include/DPLUtils/RawParser.h
- Framework/Utils/src/raw-parser.cxx
- Framework/Utils/test/test_DPLRawParser.cxx
The `o2-dpl-raw-parser` is now using the `DPLRawParser` to iterate over all raw pages of all parts on all routes.
DPLRawParser has been extended by some printout functionality.
Small bugfix in RawParser: checking memory size before calculating the payload size of the raw page
> Using the DPLRawParser in the raw-parser example

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/CompletionPolicy.h
- Framework/Core/include/Framework/InputSpan.h
- Framework/Core/src/CompletionPolicyHelpers.cxx
- Framework/Core/src/DataRelayer.cxx
- Framework/Core/test/test_CompletionPolicy.cxx
- Framework/Core/test/test_InputSpan.cxx
The change is transparent for the user code as the InputSpan provides an
iterator interface. Using InputSpan will allow to have access to the parts
within one route in order to create more complex completion checks.
> DPL: Using InputSpan as argument for CompletionPolicy callback

- CCDB/CMakeLists.txt
- CCDB/README.md
- CCDB/include/CCDB/BasicCCDBManager.h
- CCDB/include/CCDB/CcdbApi.h
- CCDB/src/CcdbApi.cxx
- CCDB/test/testBasicCCDBManager.cxx
By default loaded object will be cached in the BasicCCDBManager and owned by it,
therefore user should not delete retrieved objects.
If the query is done for the object which is already in the cache, its pointer is
returned instead of loading again the object from the CCDB server, unless the
validity range of the cached object does not match to requested timestamp.
In case user wants to enforce a fresh copy loading, the cache for particular CCDB
path can be cleaned by invoking ``mgr.clear(<path>)``.
One can also reset whole cache using ``mgr.clear()``.
Uncached mode can be imposed by invoking ``mgr.setCachingEnabled(false)``, in which
case every query will retrieve a new copy of object from the server and
the user should take care himself of deleting retrieved objects to avoid memory …
> Introduce object caching and ownership in BasicCCDBManager

- Analysis/Tasks/vertexerhf.cxx
We are working with Maja to solve an issue in the combination utility in presence of single track cut. I suggest to temporarily get back to the previous implementation while we solve the problem.
(Please squash).
> Temporary move back to traditional double loop

- Framework/Core/include/Framework/ASoAHelpers.h
- Framework/Core/test/test_ASoAHelpers.cxx
The only one possible combination wasn't generated when table size was equal to requested combination size.
Added more tests for combinations with small tables, `continue` and `break`.
> DPL Analysis: Fixed edge case for combinations from a small table

- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFMCLabelFlattener.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCClusterFinder.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCClusterFinder.h
- GPU/GPUTracking/TPCClusterFinder/MCLabelAccumulator.cxx
This PR fixes a memleak and some undefined behavior in the tpc cluster finder.
@davidrohr: This patch should fix the crash on your testset. I also didn't see anymore address sanitizer warnings.
> TPCClusterFinder: Fix memleak and undefined behavior in mc labels.

- Framework/Core/include/Framework/RootTableBuilderHelpers.h
- Framework/Core/include/Framework/TableBuilder.h
- Framework/Core/test/test_Root2ArrowTable.cxx
For the moment one needs to create explicitly the ReaderHolder,
which carries the information about the size of the the array in
the type (TTreeReader{Value,Array} do not provide that).
Next step will be to make sure convertASoA uses the new API.
> DPL Analysis: add ability to read array columns from ROOT

- Framework/Core/include/Framework/ConfigContext.h
- Framework/Core/include/Framework/runDataProcessing.h
- Framework/Core/src/WorkflowHelpers.cxx
- Framework/Core/test/benchmark_WorkflowHelpers.cxx
- Framework/Core/test/test_WorkflowHelpers.cxx
- Steer/DigitizerWorkflow/src/SimReaderSpec.cxx
- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
- Steer/DigitizerWorkflow/src/TPCDigitizerSpec.cxx
So far, during topology construction, we could not know
if the command line was invoked merely to list program options.
This is problematic since topology construction might need to
do some computation / read files / etc. which influence the workflow.
In case of --help this should not be needed.
This commit tries to address this issue by adding additional information
to the ConfigContext which is passed to the workflow construction function.
The principle is applied to the digitizer workflow, which for the first
time prints out the expected output when invoked with
`o2-sim-digitizer-workflow --help` (up until now one needed a GRP file
for this to work).
> DPL workflow creation: pass presence of --help

- Detectors/ITSMFT/ITS/tracking/cuda/include/ITStrackingCUDA/Vector.h
@mpuccio this protects the `reset` calls on `Vector`s that did not allocate GPU memory at construction time.
From this, running the `cuda-memcheck o2-its-reco-workflow --trackerCA --gpuDevice=2` or steering macro you should spot the next error.
> [its-GPU] Protect reset method in case of uninitialised Vectors

- Detectors/EMCAL/base/include/EMCALBase/RCUTrailer.h
- Detectors/EMCAL/base/src/RCUTrailer.cxx
- Detectors/EMCAL/simulation/CMakeLists.txt
- Detectors/EMCAL/simulation/include/EMCALSimulation/DMAOutputStream.h
- Detectors/EMCAL/simulation/include/EMCALSimulation/RawOutputPageHandler.h
- Detectors/EMCAL/simulation/include/EMCALSimulation/RawWriter.h
- Detectors/EMCAL/simulation/src/DMAOutputStream.cxx
- Detectors/EMCAL/simulation/src/RawOutputPageHandler.cxx
- Detectors/EMCAL/simulation/src/RawWriter.cxx
- Add encoding of the RCU trailer
- Convert to TF-based format for DDL detectors:
DMA pages are buffered untill the end-
of-timeframe is reached. At the end-of-
timeframe pages are sent consecutively
for all link. Each link gets its own
timeframe.
> [EMCAL-610] Encoding RCU trailer, TF-based raw format

- GPU/TPCFastTransformation/TPCFastTransform.h
@sgorbuno : I have added 2 additional simple transformation functions, which I need for convenience.
I was wondering why you have the division / mVDrift. Perhaps it would make sense to compute mVDriftInverse ahead of time, and store it in the object.
> GPU: Add some more simple transformation functions to TPCFastTransform

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/InputRecordWalker.h
- Framework/Core/test/test_InputRecordWalker.cxx
Each input route can have multiple parts per input route and computation.
Adding `InputRecordWalker` helper to allow simple iteration over all parts
available in the computation. Optionally a filter can be used to define
valid parts and ignore all parts not matching the filter.
The iterator is using DataRef as value type.
Usage
```
for (auto const& ref : InputRecordWalker(inputs)) {
// do something with the data described by the DataRef object, e.g.
auto data = inputs.get<TYPE>(ref)
}
```
> DPL: Adding helper to iteratate over all parts of all input routes

- DataFormats/Detectors/ITSMFT/common/include/DataFormatsITSMFT/ClusterPattern.h
- DataFormats/Detectors/ITSMFT/common/src/ClusterPattern.cxx
- Detectors/ITSMFT/ITS/macros/test/CheckCOG.C
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/ClustererTask.h
- Detectors/ITSMFT/ITS/reconstruction/src/ClustererTask.cxx
- Detectors/ITSMFT/ITS/workflow/include/ITSWorkflow/ClusterWriterSpec.h
- Detectors/ITSMFT/ITS/workflow/src/ClusterWriterSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/ClustererSpec.cxx
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/Clusterer.h
- Detectors/ITSMFT/common/reconstruction/src/Clusterer.cxx
This PR is intended to reduce the RAM (and disk) usage when working with preserved rare cluster patterns. If I am not wrong, the RAM needed for the rare patterns should already be reduced by a factor ~10 with respect to the PR #3183 (for PbPb).
The information about the rare patterns is stored in std::vector\<unsigned char\>.
For the moment, the changes are backward compatible.
Possible next steps:
1) Build the topology dictionary from compact clusters and stored patterns.
2) Drop the "full" clusters.
@shahor02 @lbariogl  Could you have a look please ?
> Optimization of storing rare cluster patterns

- Framework/Core/src/AODReaderHelpers.cxx
* Refactored common code in helper function
* Proper error in case a tree is not found
* Extract the origin and description from the table metadata
> DPL Analysis: cleanup persistent table reading

- Detectors/ITSMFT/common/simulation/src/MC2RawEncoder.cxx
- Detectors/Raw/README.md
- Detectors/Raw/include/DetectorsRaw/HBFUtils.h
- Detectors/Raw/include/DetectorsRaw/RawFileWriter.h
- Detectors/Raw/src/HBFUtils.cxx
- Detectors/Raw/src/RawFileReader.cxx
- Detectors/Raw/src/RawFileWriter.cxx
- Detectors/Raw/test/testRawReaderWriter.cxx
given that some detectors (e.g. TOF, TPC) at the moment cannot guarantee a unique
(within a given run) mapping FEEID <-> {cruID, linkID, EndPoint}, the
defined by the DataDistribution may mix data of different links (FEEDs) to single DPL input.
To avoid this, the  definition is temporarily changed to a 32 bit hash
code (Fletcher32). When the new RDHv6 (with source ID) will be put in production, both
DataDistribution and RawFileReader will be able to assign the  in a
consistent way, as a combination of FEEID and SourceID.
> Temporary change of raw utils SubSpec definition

- GPU/GPUTracking/SliceTracker/GPUTPCGrid.cxx
bugfix: inconsistency in an empty grid of TPC clusters. 
GPUTPCGrid::getBinIndex(..)  returned  -1  for an empty grid.  Now it returns 0.
> bugfix: inconsistency in an empty grid of TPC clusters

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/DebugGUI.h
- Framework/Core/src/runDataProcessing.cxx
- GPU/GPUTracking/CMakeLists.txt
This is a follow-up to the cleanup in commit 64a93f3f
Despite the message from the cmake configuration that the packages mentioned below
are recommended but not required, O2 does not build correctly if development package of
GLFW is not available on the system.
```
-- The following RECOMMENDED packages have not been found:
* GLFW
* DebugGUI
CMake Error at cmake/O2AddLibrary.cmake:75 (add_library):
Target "O2lib-Framework" links to target "AliceO2::DebugGUI" but the target
was not found.  Perhaps a find_package() call is missing for an IMPORTED
target, or an ALIAS target is missing?
```
The DebugGUI package depends on package GLFW, but the package is defined optional
by alidist. If GLFW development files are not found on the system, a dummy package
is added by alidist, but it is not a real …
> Restore optionality of DebugGUI and GLFW for O2 build

- Detectors/Raw/README.md
- Detectors/Raw/include/DetectorsRaw/HBFUtils.h
- Detectors/Raw/include/DetectorsRaw/RawFileWriter.h
- Detectors/Raw/src/HBFUtils.cxx
- Detectors/Raw/src/RawFileWriter.cxx
- Detectors/Raw/test/testRawReaderWriter.cxx
The autoformatting behaviour of RawFileWriter::addData can be changed
to preformatted page storage by adding an extra true argument in the end of addData method, e.g.
writer.addData(rdh, ir, gsl::span( (char*)payload_f, payload_f_size ), true );
In the case provided data blob is interpretted as a fully formatted CRU page payload (i.e. it lacks
the RDH which will be added by the writer) of the maximum size 8192-sizeof(RDH) = 8128 bytes.
The writer will create a new CRU page with provided payload, equipping it with the proper RDH:
copying already stored RDH of the current HBF, if the interaction record  belongs to the same HBF
or generating new RDH for new HBF otherwise (and filling all missing HBFs in-between).
In case the payload size exceeds maximum, an exception will be thrown w/o any …
> Possibility to add to the link CRU page with preformatted payload:

- Detectors/ITSMFT/MFT/tracking/src/TrackFitter.cxx
This PR updates the seed covariances for the MFT track fitting.
It also disables a `throw runtime_error` due to a bug on MFT track finding, 
which sometimes return tracks with more than one cluster from the same 
MFT layer.
> [MFT] Improve MFT fitter seed covariances

- DataFormats/Detectors/TOF/include/DataFormatsTOF/RawDataFormat.h
This PR updates the file containing the TOF raw data format.
Specifically 
* fixed an error on `LTM_EVSIZE` macro
* use of `__cplusplus` directive
* addition of `detField` description
> Update to TOF raw data format

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/NoDebugGUI.h
- Framework/Core/src/runDataProcessing.cxx
- Framework/Core/test/test_CustomGUIGL.cxx
- Framework/Core/test/test_CustomGUISokol.cxx
- Framework/Core/test/test_SimpleTracksED.cxx
- GPU/GPUTracking/Standalone/display/GPUDisplayBackendGlfw.cxx
A follow up to #3245 
- The DebugGUI header needs to be loaded from the external DebugGUI
package, the correct include path is `DebugGUI/DebugGUI.h`
- Make sure that DebugGUI dependencies are defined before internal ones
- Renaming dummy DebugGUI header into NoDebugGUI.h to make it really
different from the header in the DebugGUI package
- Making dummy functions from NoDebugGUI.h 'static inline'
While the main DPL driver was including the correct header, some other
code was still including the wrong file. And having code including the dummy
DebugGUI.h header in the compilation was causing unwanted side effects.
While the DebugGUI was opening correctly for the workflow unit tests,
it did not open for all workflows linking to the GPU library which was
including the wrong dummy header. The …
> Bugfix: Including the correct header file for DebugGUI

- Framework/Core/include/Framework/DataProcessingHeader.h
- Framework/Core/src/DataProcessingHeader.cxx
this change removes the need for linking against O2::Framework for
users only interested in this header, such as DataDistribution.
Reduced number of library dependencies with this change:
ldd `which StfBuilder` | wc -l
157 -> 41
Alternatively, this header def can be moved to O2::Header library.
What do you think? @ktf @mkrzewic
> dpl header: make the class header only

- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/ASoAHelpers.h
- Framework/Core/test/test_ASoA.cxx
- Framework/Core/test/test_ASoAHelpers.cxx
Added full, strictly upper and upper policies that return tuples of items from the same category.
Based on Anton's PR #3214 as it makes range checks easier.
@ktf  Please have a look - I marked some "FIXME"s in code.
The main design question is whether arrow arrays need to be used for grouping - as in AnalysisTask.h `invokeProces()`. Will categorized combinations be later added here? (e.g. for mixed events `process(Combination& c1, Tracks& tracks1, Combination& c2, Tracks& tracks2)`?
> DPL Analysis: Added combinations on categorized data

- run/CMakeLists.txt
Otherwise on e.g. Ubuntu the o2-sim-primary-server-device-runner is
_not_ linked with all the subsystem libraries. One of the consequences
being that their dictionaries are not loaded and thus their ConfigParam
for instance are not usable.
> Use LINK_WHAT_YOU_USE where needed (on Linux only)

- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/AnalysisDataModel.h
- Framework/Core/include/Framework/AnalysisTask.h
- Framework/Core/test/test_AnalysisTask.cxx
A substantial rework of invokeProcess() that allows user to request more than two arguments in process, see, for example, test_AnalysisTask.cxx:
```
struct BTask {
void process(o2::aod::Collision const&, o2::soa::Join<o2::aod::Tracks, o2::aod::TracksExtra, o2::aod::TracksCov> const&, o2::aod::UnassignedTracks const&, o2::soa::Join<o2::aod::Calos, o2::aod::CaloTriggers> const&)
{
}
};
```
If the first argument of the process() is an iterator, all compatible tables in the rest of the arguments will be grouped according to the index of the table of the first argument.
> DPL Analysis: rework invokeProcess to accept more than two arguments

- Framework/Core/include/Framework/DataAllocator.h
- Framework/Core/src/DataAllocator.cxx
- Framework/Core/test/test_DataAllocator.cxx
`DataAllocator::isAllowed` can be used to check for conditional outputs.
> DPL: adding DataAllocator method to check validity of a certain output

- Steer/DigitizerWorkflow/src/TPCDigitRootWriterSpec.cxx
- Steer/DigitizerWorkflow/src/TPCDigitRootWriterSpec.h
- Steer/DigitizerWorkflow/src/TPCDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/TPCDigitizerSpec.h
A couple of cleanups for the TPC digitizer workflow implementation
- Using InputRecordWalker to process data on iterator basis rather than the route
binding, this allows to transparently access multiple parts per route.
- The output route is selected by subspec of the incoming data block rather than a
fixed identifier.
- Removing custom end of stream handling
- Adding an alternative function using a workflow helper to create parallel pipelines
of TPC Digitizers
- Reworking TPCDigitRootWriterSpec of TPC digitization workflow, the custom code for
checking for completeness is deprecated by the DPL end-of-stream feature
> More flexible data handling in the TPCDigitizerSpec,reworking TPCDigitRootWriterSpec

- DataFormats/Detectors/FIT/FDD/include/DataFormatsFDD/Digit.h
- DataFormats/Detectors/FIT/FT0/src/Digit.cxx
- DataFormats/Detectors/FIT/FT0/src/RecPoints.cxx
- DataFormats/Detectors/FIT/FV0/src/BCData.cxx
- DataFormats/Detectors/ITSMFT/common/include/DataFormatsITSMFT/ROFRecord.h
- DataFormats/Detectors/ZDC/src/BCData.cxx
- Detectors/ITSMFT/ITS/macros/test/run_digi2rawVarPage_its.C
- Detectors/TOF/base/include/TOFBase/Digit.h
This fix will override https://github.com/AliceO2Group/AliceO2/pull/3262 as it covers more similar cases of dereferencing potentially random address while creating empty span.
> Avoid creating empty span with non-default span c-tor

- Framework/Core/src/WorkflowHelpers.cxx
This is only a temporary solution to avoid failure of certain workflows. Needs to be solved properly.
> temporarily only allow dangling outputs to be saved

- Detectors/TPC/workflow/include/TPCWorkflow/RecoWorkflow.h
- Detectors/TPC/workflow/src/ClusterDecoderRawSpec.cxx
- Detectors/TPC/workflow/src/ClustererSpec.cxx
Sort DataRef objects for the different sectors by sector number. This will
become necessary if multiple sectors are sent over the same route in a
single timeslice.
Also defining helper methods in the header file as 'static inline' to avoid
conflicts if the header file is inlcuded in both an executable and a library.
> Arranging data with respect to sector number instead of subspec

- Detectors/FIT/workflow/CMakeLists.txt
Applying the trick of Laurent to enforce proper linking of config param.
> Use LINK_WHAT_YOU_USE for FIT reco. workflow

- Framework/Core/src/WorkflowHelpers.cxx
The vector of inputSpec given to aod-writer as input contains only unique elements. This should solve the problem encountered with certain workflows.
> aod-writer with unique list of inputSpec

- Generators/share/external/hijing.C
This PR fixes a issue in the `hijing.C` example macro.
It also updates the configuration settings to `hij->SetPtHardMin(2.9)` is in the latest AliRoot productions.
> Update hijing settings and fix macro

- DataFormats/Detectors/ITSMFT/MFT/include/DataFormatsMFT/TrackMFT.h
- DataFormats/Detectors/ITSMFT/MFT/src/TrackMFT.cxx
- Detectors/ITSMFT/MFT/tracking/include/MFTTracking/FitterTrackMFT.h
- Detectors/ITSMFT/MFT/tracking/include/MFTTracking/TrackCA.h
- Detectors/ITSMFT/MFT/tracking/src/FitterTrackMFT.cxx
- Detectors/ITSMFT/MFT/tracking/src/TrackFitter.cxx
- Detectors/ITSMFT/MFT/tracking/src/TrackParamMFT.cxx
- Detectors/ITSMFT/MFT/workflow/include/MFTWorkflow/TrackFitterSpec.h
- Detectors/ITSMFT/MFT/workflow/src/TrackFitterSpec.cxx
* Added propagation of MCLabels to fitted MFT Tracks and print function
* FitterWorkflow now uses gsl::span
* TrackMFT dropped TMatrix in favor of SMatrix
> [MFT] Propagation of MCLabels, use of SMatrix on TrackMFT

- Detectors/Base/src/GeometryManager.cxx
Due to the assigning to string_view rather than to string in my previous commit
@noferini Thanks for spotting!
> Hotfix: loading default geometry fails

- Analysis/DataModel/include/Analysis/Jet.h
- Analysis/DataModel/include/Analysis/SecondaryVertex.h
- Analysis/DataModel/include/Analysis/TrackSelectionTables.h
- Analysis/Tasks/correlationsCollection.cxx
- Analysis/Tasks/eventSelection.cxx
- Analysis/Tutorials/src/aodreader.cxx
- Analysis/Tutorials/src/aodwriter.cxx
- Analysis/Tutorials/src/associatedExample.cxx
- Analysis/Tutorials/src/dynamicColumns.cxx
- Analysis/Tutorials/src/filters.cxx
- Analysis/Tutorials/src/newCollections.cxx
- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/AnalysisDataModel.h
- Framework/Core/test/benchmark_ASoA.cxx
- Framework/Core/test/benchmark_ASoAHelpers.cxx
- Framework/Core/test/benchmark_TableBuilder.cxx
- Framework/Core/test/benchmark_TableToTree.cxx
- Framework/Core/test/benchmark_TreeToTable.cxx
- Framework/Core/test/test_ASoA.cxx
- Framework/Core/test/test_ASoAHelpers.cxx
- Framework/Core/test/test_AnalysisTask.cxx
- Framework/Core/test/test_GroupSlicer.cxx
- Framework/Core/test/test_Root2ArrowTable.cxx
- Framework/Core/test/test_TableBuilder.cxx
- Framework/TestWorkflows/src/o2SimpleTracksAnalysis.cxx
This changes the API of the column so that by default the branch
is called "f"#_Name_. Where _Name_ is the first argument of the macro.
The old API is still available using DECLARE_SOA_COLUMN_FULL.
> DPL Analysis: calculate branch name

- cmake/O2RootMacroExclusionList.cmake
- macro/CMakeLists.txt
@pzhristov since the `json.h was fixed (thanks @max !) I am enabling it back.
> Re-enable check of run_trac_ca_its.C as json.h is fixed

- DataFormats/Detectors/EMCAL/include/DataFormatsEMCAL/Cell.h
- DataFormats/Detectors/EMCAL/include/DataFormatsEMCAL/Constants.h
- DataFormats/Detectors/EMCAL/include/DataFormatsEMCAL/Digit.h
- DataFormats/Detectors/EMCAL/include/DataFormatsEMCAL/MCLabel.h
- DataFormats/Detectors/EMCAL/src/Digit.cxx
- Detectors/EMCAL/simulation/include/EMCALSimulation/Digitizer.h
- Detectors/EMCAL/simulation/include/EMCALSimulation/LabeledDigit.h
- Detectors/EMCAL/simulation/src/Digitizer.cxx
- Detectors/EMCAL/simulation/src/LabeledDigit.cxx
[WIP EMCAL-501] store energy in Digits in ADC counts
- Change "Energy" -> "Amplitude" in Digit and related classes
- Store amplitude in ADC counts (either Low or High Gain) in Digits
- Add constants::EMCAL_HGLGFACTOR = 16
- Change constants::EMCAL_HGLGTRANSITION to Int_t
- Digitizer.h: set mBusyTime = 35000 and mDelay = 7 for consistency with default values in SimParam.h
> [EMCAL-501] store energy in Digits in ADC counts

- Detectors/TRD/simulation/src/Digitizer.cxx
> TRD: Use diffused electron coordinate instead of nominal value

- Detectors/MUON/MCH/Mapping/Interface/include/MCHMappingInterface/Segmentation.inl
- Detectors/MUON/MCH/Mapping/test/CMakeLists.txt
- Detectors/MUON/MCH/Mapping/test/src/Segmentation.cxx
In the cases where only one cathode has a pad under the position used in
findPadPairByPosition the returned padIndex was relative to the cathode
and not to the detection element as it should have been.
> [MCH] Fix a bug in findPadPairByPosition

- Algorithm/CMakeLists.txt
- Algorithm/include/Algorithm/FlattenRestore.h
- Algorithm/test/test_FlattenRestore.cxx
- DataFormats/Detectors/TPC/CMakeLists.txt
- DataFormats/Detectors/TPC/include/DataFormatsTPC/CompressedClusters.h
- DataFormats/Detectors/TPC/include/DataFormatsTPC/CompressedClustersHelpers.h
- DataFormats/Detectors/TPC/src/CompressedClusters.cxx
- DataFormats/Detectors/TPC/src/DataFormatsTPCLinkDef.h
- DataFormats/Detectors/TPC/test/testCompressedClusters.cxx
We have observed a problem with serialization of the CompClusters container. It's not fully debugged in ROOT, unpacking the streamed object is sometimes failing.
Implemented a custom streamer to flatten the object before streaming. The buffer is stored instead of the arrays behind the pointers. All pointers are now transient. This reduces the complexity of the container. After deserialization, the pointers are set to the content in the flat buffer.
The flatten/restore functionality can also be used to transport the container unserialized.
Adding also some generic tools for flatten and restore.
> Custom streamer for the TPC CompClusters container

- Detectors/TPC/workflow/CMakeLists.txt
- Detectors/TPC/workflow/include/TPCWorkflow/CATrackerSpec.h
- Detectors/TPC/workflow/include/TPCWorkflow/EntropyEncoderSpec.h
- Detectors/TPC/workflow/include/TPCWorkflow/RecoWorkflow.h
- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- Detectors/TPC/workflow/src/EntropyEncoderSpec.cxx
- Detectors/TPC/workflow/src/RecoWorkflow.cxx
- Framework/Utils/include/DPLUtils/RootTreeWriter.h
New output types added
- compressed-clusters
- encoded-clusters
Changes
- integrating the handling of compressed clusters object produced by
the CA track, data is sent out with spec TPC/COMPCLUSTERS/0
- adding a skeleton for the TPC cluster encoder
Adding also support for objects marked as ROOT serialized in the DPL ROOTTreeWriter
> Rework of the TPC reco workflow to support compressed clusters

- Detectors/FIT/FDD/workflow/include/FDDWorkflow/RecPointReaderSpec.h
- Detectors/FIT/FDD/workflow/src/RecPointReaderSpec.cxx
- Detectors/FIT/workflow/include/FITWorkflow/FT0RecPointReaderSpec.h
- Detectors/FIT/workflow/src/FT0RecPointReaderSpec.cxx
- Detectors/GlobalTrackingWorkflow/include/GlobalTrackingWorkflow/TrackTPCITSReaderSpec.h
- Detectors/GlobalTrackingWorkflow/src/TrackTPCITSReaderSpec.cxx
- Detectors/ITSMFT/ITS/workflow/include/ITSWorkflow/TrackReaderSpec.h
- Detectors/ITSMFT/ITS/workflow/include/ITSWorkflow/VertexReaderSpec.h
- Detectors/ITSMFT/ITS/workflow/src/TrackReaderSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/VertexReaderSpec.cxx
- Detectors/ITSMFT/common/workflow/include/ITSMFTWorkflow/ClusterReaderSpec.h
- Detectors/ITSMFT/common/workflow/src/ClusterReaderSpec.cxx
- Detectors/TOF/workflow/include/TOFWorkflow/ClusterReaderSpec.h
- Detectors/TOF/workflow/src/ClusterReaderSpec.cxx
- Detectors/TPC/workflow/include/TPCWorkflow/TrackReaderSpec.h
- Detectors/TPC/workflow/src/TrackReaderSpec.cxx
To allow feeding multiple TFs into the DPL workflows, the readers for reco objects (clusters, tracks etc.) will treat each tree entry as a separate TF. Behaviour for trees with single entry is unchanged.
Suppressed ``mState`` and ``mFinished`` data members of readers: the stat of the device will be determined by availability of further data to send and ReadToQuit call.
> Rec.objects readers treat each tree entry as a new TF 

- Analysis/Tasks/vertexerhf.cxx
With the help of @ekryshen, I included in the vertexerhf task a simple trigger selection based on the converted trigger bit. We plan to replace this preliminary selection with the event selection task that will soon be released. This implementation was validated with respect to the Run2 framework.
> Add simple trigger selection based on trigger bit in the vertexerhf task

- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- GPU/GPUTracking/Base/GPUMemorySizeScalers.h
- GPU/GPUTracking/Base/GPUReconstruction.cxx
- GPU/GPUTracking/Interface/GPUO2Interface.cxx
- GPU/GPUTracking/SliceTracker/GPUTPCStartHitsFinder.cxx
- GPU/GPUTracking/SliceTracker/GPUTPCTracker.cxx
- GPU/GPUTracking/SliceTracker/GPUTPCTrackletConstructor.cxx
- GPU/GPUTracking/SliceTracker/GPUTPCTrackletSelector.cxx
@shahor02 :
- This fixes the memory corruption, which was however only a secondary symptom of the insufficient buffer size.
- If the buffer size is exceeded, the workflow will now die with a fatal.
- Buffer size estimation improved, and adding a factor 2 safety margin for now on the CPU (only increases the virtual memory size, no memory should be allocated if not needed. This should allow the workflow to work also with "abnormal" input data.
> Some fixes for TPC workflow

- GPU/GPUTracking/Base/GPUSettings.cxx
- GPU/GPUTracking/Merger/GPUTPCGlobalMergerComponent.cxx
- GPU/GPUTracking/SliceTracker/GPUTPCTrackerComponent.cxx
- GPU/GPUTracking/SliceTracker/GPUTPCTrackerComponent.h
Sync over fixes needed for AliRoot AliGPU
> GPU: HLT components should propagate the error when GPU initialization fails

- Framework/Core/src/WorkflowHelpers.cxx
- Framework/Core/test/test_WorkflowHelpers.cxx
This prevents sorting issues when merging workflows.
> DPL: make sure outputs associated to enumerations are stable

- doc/DetectorSimulation.md
- run/SimExamples/AliRoot_Hijing/README.md
- run/SimExamples/AliRoot_Hijing/aliroot_hijing.macro
- run/SimExamples/AliRoot_Hijing/run.sh
This is a simple simulation example showing how to run event simulation using the Hijing event generator interface from AliRoot.
The configuration of AliGenHijing is performed by the function `hijing(double energy = 5020., double bMin = 0., double bMax = 20.)` defined in the macro `aliroot_hijing.macro`.
The macro file is specified via the argument of `--extGenFile` whereas the specific function call to retrieven the configuration is specified via the argument of `--extGenFunc`.
To run this example you need to load an AliRoot package compatible with the O2.
for more details, https://alice.its.cern.ch/jira/browse/AOGM-246
> Example to run AliRoot Hijing simulation

- Generators/include/Generators/Generator.h
- Generators/src/Generator.cxx
- Generators/src/GeneratorHepMC.cxx
- Generators/src/GeneratorPythia8.cxx
- Generators/src/GeneratorTGenerator.cxx
- Generators/src/PrimaryGenerator.cxx
- doc/DetectorSimulation.md
- run/SimExamples/Adaptive_Pythia8/README.md
- run/SimExamples/Adaptive_Pythia8/adaptive_pythia8.macro
- run/SimExamples/Adaptive_Pythia8/pythia8_inel.cfg
- run/SimExamples/Adaptive_Pythia8/run.sh
This PR provides a new functionality for event generators in case of embedding into a background event. Event generators are notified of the embedding via the `notifyEmbedding` function.
The `MCEventHeader` of the background event is passed via the function.
Event generators can override the `notifyEmbedding` function and adapt the event generation according to the information that comes in the background `MCEventHeader`.
This is a basic ingredient to be able to embed events that are dependent on the background characteristics. A classical example if it it to embed a signal whose multiplicity depends on the multiplicity of the background event. 
Futher developments will provide dedicated support for specialised event signatures in the `MCEventHeader`. This PR is the backbone if it. 
An …
> Notify generators of embedding into background

- Detectors/Raw/include/DetectorsRaw/RDHUtils.h
- Detectors/Raw/src/RDHUtils.cxx
- Detectors/TPC/base/include/TPCBase/Digit.h
- Detectors/TPC/reconstruction/include/TPCReconstruction/GPUCATracking.h
- Detectors/TPC/reconstruction/src/GPUCATracking.cxx
- Detectors/TPC/simulation/run/convertDigitsToRawZS.cxx
- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- GPU/GPUTracking/Base/GPUDataTypes.h
- GPU/GPUTracking/Base/GPURawData.h
- GPU/GPUTracking/Base/GPUReconstructionConvert.cxx
- GPU/GPUTracking/Base/GPUReconstructionConvert.h
- GPU/GPUTracking/Base/GPUReconstructionKernels.h
- GPU/GPUTracking/CMakeLists.txt
- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/Interface/GPUO2Interface.cxx
- GPU/GPUTracking/Standalone/CMakeLists.txt
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFDecodeZS.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFDecodeZS.h
- macro/runCATrackingClusterNative.C
- Utilize `RDHUtils` where possible instead of accessing the RDH directly. (Currently, OpenCL doesn't support bitfields, so I had to place some `#ifdef`s in `GPURawData.h`. We could also move all these `#ifdef`s to `RAWDataHeader.h` and `RDHUtils.h`, but that would be quite messy. I filed a bug report to Clang C++ for OpenCL asking to support bitfields. I'd wait what comes out there first.)
- The TPC reco workflow does not longer cash the raw data for all subspecifications internally after this was fixed in the raw reader workflow.
- Raw data encoder should now support multiple TFs (still testing this feature while the CI runs...).
- Use correct time frame length from `HBFUtils.h`
- Cleaned up computation of tpc timebins in decoding after longer discussion via mail.
Still missing are:
- …
> Work on TPC ZS encoding and decoding

- Detectors/TPC/workflow/src/CATrackerSpec.cxx
Let CATrackerSpec throw an exception in case of initialization error or
tracker runtime error.
> TPC reco workflow: runtime exception instead of (FATAL)ERROR message

- Framework/Utils/src/raw-parser.cxx
printout stream was accumulating the output due to the improper reset after flushing
> Fix: properly reset printout stream after flushing

- Detectors/TPC/reconstruction/src/GPUCATracking.cxx
minor fix, this was not propagated back to the workflow.
> GPU: Propagate clustersNative found by ca-clusterer back to tpc workflow

- Detectors/Raw/include/DetectorsRaw/HBFUtils.h
- Detectors/Raw/src/RawFileReaderWorkflow.cxx
- Detectors/Raw/src/RawFileReaderWorkflow.h
- Detectors/Raw/src/rawfile-reader-workflow.cxx
rawfile-reader-workflow was doing n+1 passes over data when --loops n was asked, now does
exactly n and and not asking anything == asking 1
Eliminate wrong setter of HBFUtils (as CongigurableParam it cannoot have ones)
> Fix: RawFileReader was making 1 extra loop

- GPU/GPUTracking/Base/hip/GPUReconstructionHIP.hip.cxx
@mconcas : that should fix your problem
This is just a warning to myself in order not to run into a compiler problem because I keep forgetting about it.
Obviously not needed in ITS GPU initialization...
> GPU: Break with with failure about broken compiler only for standalone tests

- Detectors/Raw/include/DetectorsRaw/RDHUtils.h
- Detectors/TPC/base/CMakeLists.txt
- Detectors/TPC/base/include/TPCBase/RDHUtils.h
- Detectors/TPC/base/test/testRDHUtils.cxx
- Detectors/TPC/simulation/run/convertDigitsToRawZS.cxx
- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- GPU/GPUTracking/Base/GPURawData.h
- GPU/GPUTracking/Base/GPUReconstructionConvert.cxx
- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/Standalone/qconfigoptions.h
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFDecodeZS.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFDecodeZS.h
- GPU/GPUTracking/TPCClusterFinder/GPUTPCClusterFinder.cxx
This requires #3372 and #3369, so I just included the commits here, should be clean after rebasing.
Changes are:
- Fix a problem in TPC ZS decoding when the first HBF does not contain any payload.
- Fix decoding when storing 12 bit values instead of 10
- Use the TPC cru --> feeid mapper instead of in place computation.
Hopefully this store is closed now...
> More work on Zero-Suppression

- Detectors/TPC/simulation/run/convertDigitsToRawZS.cxx
@shahor02 (@wiechula ): I am looking into the memory issue you reported, but I believe there is no memory leak. It just needs that much memory because it reads all the digits in memory.
This PR tries to help this in 2 ways:
- Do not set the branch address for MC labels, since they are not needed anyway.
- Add an option to go sector by sector instead of parallelizing over the sectors.
However, I have tried the 200 PbPb events you have on CernBox with this patch, and on my system with 64GB of memory it still runs out of memory.
I traced where the memory is allocated, and actually the very first call to `treeSim->GetEntry(ievent);` already exhaust my memory. I am no expert to ROOT, but I was assuming if I set only 1 single branch address for the sector I want to read, ROOT would only read …
> TPC: Add sector-by-sector option for TPC ZS encoder and do not read MC labels

- doc/DetectorSimulation.md
- run/SimExamples/HepMC_STARlight/README.md
- run/SimExamples/HepMC_STARlight/run-starlight.sh
- run/SimExamples/HepMC_STARlight/run.sh
This is a simple simulation example showing how to run event simulation using the `STARlight` event generator.
The `STARlight` event generation process is launched in a clean environment by the script `run-starlight.sh`.
The `run-starlight.sh` script performs initialisation operations of the enviroment to run `STARlight`.
It copies in the currect directory the relevant files need for the operation from the `STARlight` installation directory.
The relevant files are
* `slight.in` to configure the event generator
* `starlight2hepmc.awk` and `pdgMass.awk to convert the output in `HepMC2` format.
At the end of the `STARlight` process, the `HepMC2` output file is `startlight.hepmc` and can be used for the `o2` simulation in the second part of this example.
To run this example you need to have …
> Example to run STARlight via HepMC file

- Detectors/ITSMFT/MFT/base/include/MFTBase/MFTBaseParam.h
To avoid several overlapping volumes, the disk support are not created by default. MFT experts are working to solve that.
> Skip the creation of the DiskSupport by default

- Analysis/Tutorials/src/aodreader.cxx
- Analysis/Tutorials/src/aodwriter.cxx
- Framework/Core/ANALYSIS.md
- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/DataInputDirector.h
- Framework/Core/include/Framework/DataOutputDirector.h
- Framework/Core/include/Framework/TableTreeHelpers.h
- Framework/Core/src/AODReaderHelpers.cxx
- Framework/Core/src/CommonDataProcessors.cxx
- Framework/Core/src/DataInputDirector.cxx
- Framework/Core/src/DataOutputDirector.cxx
- Framework/Core/src/WorkflowHelpers.cxx
- Framework/Core/test/test_DataInputDirector.cxx
- Framework/Core/test/test_DataOutputDirector.cxx
Added functionality which allows the internal-dpl-aod-reader to read tables from different sets of files.
The required information is encoded in a JSON file, which is provided to the internal-dpl-aod-reader via the json-file command line option. More information can be found in the Framework/Core/ANALYSIS.md file.
> enable customization of internal-dpl-aod-reader with json file

- DataFormats/Detectors/ITSMFT/common/include/DataFormatsITSMFT/ClusterTopology.h
- Detectors/ITSMFT/ITS/README.md
- Detectors/ITSMFT/ITS/reconstruction/src/ClustererTask.cxx
- Detectors/ITSMFT/ITS/simulation/src/digi2raw.cxx
- Detectors/ITSMFT/ITS/workflow/include/ITSWorkflow/ClustererSpec.h
- Detectors/ITSMFT/ITS/workflow/src/ClustererSpec.cxx
- Detectors/ITSMFT/MFT/reconstruction/src/ClustererTask.cxx
- Detectors/ITSMFT/MFT/workflow/include/MFTWorkflow/ClustererSpec.h
- Detectors/ITSMFT/MFT/workflow/src/ClustererSpec.cxx
- Detectors/ITSMFT/common/reconstruction/CMakeLists.txt
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/Clusterer.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/DigitPixelReader.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/GBTLink.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/PixelReader.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/RawPixelDecoder.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/RawPixelReader.h
- Detectors/ITSMFT/common/reconstruction/src/Clusterer.cxx
- Detectors/ITSMFT/common/reconstruction/src/DigitPixelReader.cxx
- Detectors/ITSMFT/common/reconstruction/src/GBTLink.cxx
- Detectors/ITSMFT/common/reconstruction/src/RawPixelDecoder.cxx
- Detectors/ITSMFT/common/workflow/include/ITSMFTWorkflow/STFDecoderSpec.h
- Detectors/ITSMFT/common/workflow/src/STFDecoderSpec.cxx
-- Multi-threading for ITS/MFT data decoding/clusterization
*  All PixelReader derived classes got possibility of per HBF-reading
*  Raw data decoding (via DigitPixelReader) supports multithreding on particular RU level
*  Clusterizer support multithreding by splitting HBF clusterization to n nearly equal parts
in n-hits and running 1 thread per part.
(at the moment gave up using output.make in favor of snapshot to avoid propagation of the PMR
vectors to clusterizer buffers and exposing them in the headers to non-framework code.
-- Pass configKeyValues to ITS digi2raw (e.g. to manipulate HBFUtil settings)
> Multi-threading for ITS/MFT data decoding/clusterization + minor fixes

- DataFormats/Detectors/TPC/include/DataFormatsTPC/ClusterNativeHelper.h
- DataFormats/Detectors/TPC/src/ClusterNativeHelper.cxx
- Detectors/TPC/workflow/src/CATrackerSpec.cxx
This makes the code more flexible with respect to the input, e.g support vectors with different
allocators.
- using const input arrays and use spans to be more flexible for the read-only input data
- adding method descriptions
Another side note:
With PR #2155 (65e17cb) restoring the access index always involves
a copy of the data. This is contradictory to the idea of the index simply
providing pointers to data and we should rethink the concept. Very likely
the partitioning of the data pad-row wise does not make sense any more
and the monolithic data set should be produced already by the decoder.
> Cleaning-up TPC ClusterNativeHelper

- Detectors/MUON/MID/Simulation/src/Geometry.cxx
Solution to 'cut' RPC overlaps (thanks to [Andreas Morsch's suggestion](https://alice.its.cern.ch/jira/browse/O2-601?focusedCommentId=246436&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-246436))
> Increase the thickness of cutting RPC layers in MID geometry

- prodtests/sim_challenge.sh
Execute stages in the sim-recoworkflow in
a task-wrapper. The wrapper supervises the log files
and can detect critical problems and eventually kill
the processes. This prevents DPL workflows to hang indefinitely
when one process reported a problem but others are not notified
to shutdown.
A workaround until
https://alice.its.cern.ch/jira/browse/O2-1078
is available.
The task-wrapper might actually be interesting for other purposes:
- monitor memory etc
- send email on failure
> Use a taskwrapper in sim_challenge

- Detectors/ITSMFT/ITS/tracking/hip/include/ITStrackingHIP/VectorHIP.h
- Detectors/ITSMFT/ITS/tracking/hip/include/ITStrackingHIP/VertexerTraitsHIP.h
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/ClusterLines.h
@mpuccio @mconcas : Could you have a look at this?
These fixes are needed for the upcoming ROCm because it does no longer support chainging __host__ / __device__ qualifiers while overloading function (same behavior as cuda-clang).
Hope this doesn't break anything else.
> GPU: Some fixes that will be required for upcomint ROCm release

- Detectors/GlobalTrackingWorkflow/CMakeLists.txt
- Detectors/GlobalTrackingWorkflow/tofworkflow/CMakeLists.txt
- Detectors/GlobalTrackingWorkflow/tofworkflow/include/TOFWorkflow/TOFMatchedReaderSpec.h
- Detectors/GlobalTrackingWorkflow/tofworkflow/src/TOFMatchedReaderSpec.cxx
- Detectors/GlobalTrackingWorkflow/tpcinterpolationworkflow/CMakeLists.txt
- Detectors/GlobalTrackingWorkflow/tpcinterpolationworkflow/include/TPCInterpolationWorkflow/TPCInterpolationSpec.h
- Detectors/GlobalTrackingWorkflow/tpcinterpolationworkflow/include/TPCInterpolationWorkflow/TPCResidualWriterSpec.h
- Detectors/GlobalTrackingWorkflow/tpcinterpolationworkflow/include/TPCInterpolationWorkflow/TrackInterpolationReaderSpec.h
- Detectors/GlobalTrackingWorkflow/tpcinterpolationworkflow/include/TPCInterpolationWorkflow/TrackInterpolationWorkflow.h
- Detectors/GlobalTrackingWorkflow/tpcinterpolationworkflow/src/TPCInterpolationSpec.cxx
- Detectors/GlobalTrackingWorkflow/tpcinterpolationworkflow/src/TPCResidualWriterSpec.cxx
- Detectors/GlobalTrackingWorkflow/tpcinterpolationworkflow/src/TrackInterpolationReaderSpec.cxx
- Detectors/GlobalTrackingWorkflow/tpcinterpolationworkflow/src/TrackInterpolationWorkflow.cxx
- Detectors/GlobalTrackingWorkflow/tpcinterpolationworkflow/src/tpc-interpolation-workflow.cxx
- Detectors/TPC/calibration/SpacePoints/include/SpacePoints/SpacePointsCalibParam.h
- Detectors/TPC/calibration/SpacePoints/include/SpacePoints/TrackInterpolation.h
- Detectors/TPC/calibration/SpacePoints/include/SpacePoints/TrackResiduals.h
- Detectors/TPC/calibration/SpacePoints/src/SpacePointCalibLinkDef.h
- Detectors/TPC/calibration/SpacePoints/src/TrackInterpolation.cxx
- Detectors/TPC/calibration/SpacePoints/src/TrackResiduals.cxx
MatchInfoTof has the index of the matched track stored directly as a member now.
> TPC track interpolation as DPL workflow, add TOF reader for matching information

- Framework/Core/include/Framework/AnalysisTask.h
Grouping table needs to bind all the indices from associated tables before being given to the GroupSlicer object.
> DPL Analysis: fix for index binding when grouping

- Framework/Core/src/Kernels.cxx
Initial support for handling grouping derived tables that do not have entries referring to some of the rows of the grouping table, for example if we have groups of tracks not from all collisions.
> DPL Analysis: Grouping kernel now adds empty ranges

- Steer/DigitizerWorkflow/src/SimReaderSpec.cxx
- Steer/DigitizerWorkflow/src/SimReaderSpec.h
- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
- Removing custom code for propagating end-of-stream, this is now handled
by DPL.
- Removing the TPC sector to subchannel mapping, this was deprecated by
introducing dedicated routes for TPC sectors
> Cleanup of TPC digitizer workflow

- Detectors/MUON/MCH/Workflow/src/digits-sink-workflow.cxx
length doesn't work for me with my system ms_gsl. The ms_gsl we have in alidist has length() but it is quite old, so I assume it is removed.
So should we use size()?
> Fix length --> size (length not supported by new ms_gsl)

- Detectors/EMCAL/base/include/EMCALBase/Geometry.h
- Detectors/EMCAL/base/src/Geometry.cxx
Time consumption of getting cell indices can be improved
using a lookup table. This implementation uses a std::vector
as type of the lookup table. With this approach a speedup
of factor 2 is achieved.
> [EMCAL-605] Speedup GetCellIndex using a lookup table

- DataFormats/Detectors/TPC/include/DataFormatsTPC/ClusterNativeHelper.h
- Detectors/TPC/workflow/include/TPCWorkflow/CATrackerSpec.h
- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- Detectors/TPC/workflow/src/RecoWorkflow.cxx
https://alice.its.cern.ch/jira/browse/O2-1338
Test sequence to produce the ca clusters and store in `tpc-native-clusters.root`
```
o2-tpc-reco-workflow --infile tpcdigits.root --output-type tracks,clusters --tracker-options "cont refX=83 bz=-5.0068597793 qa" --ca-clusterer
```
Run tracking from the stored clusters
```
o2-tpc-reco-workflow --input-type clusters --infile tpc-native-clusters.root --output-type tracks --tracker-options "cont refX=83 bz=-5.0068597793 qa"
```
The resulting tracks and qa blocks are from first glimpse identical.
> [O2-1338] Implement writing of TPC clusters found by ca-clusterer

- DataFormats/Detectors/ITSMFT/MFT/include/DataFormatsMFT/TrackMFT.h
- DataFormats/Detectors/ITSMFT/MFT/src/TrackMFT.cxx
- Detectors/ITSMFT/MFT/tracking/include/MFTTracking/FitterTrackMFT.h
- Detectors/ITSMFT/MFT/tracking/include/MFTTracking/TrackExtrap.h
- Detectors/ITSMFT/MFT/tracking/include/MFTTracking/TrackFitter.h
- Detectors/ITSMFT/MFT/tracking/src/TrackExtrap.cxx
- Detectors/ITSMFT/MFT/tracking/src/TrackFitter.cxx
- Detectors/ITSMFT/MFT/workflow/src/TrackFitterSpec.cxx
- MFT Fitter: seed charge and momentum from quadratic fit
- Optimizing seed for MFT Track fitter
- Supression of verbose fitting output (to be added to a configurable
parameter)
- TrackMFT storing pt and chi2 from quadratic fit
- Adding choices for seeds
- Droping failed tracks instead of throwing errors (FIX https://alice.its.cern.ch/jira/browse/O2-1343 )
- Explictly disabling propagation of covariance matrix on MFT Track fitting.
> [MFT] Several improvements on MFT track fitting

- Analysis/Tutorials/CMakeLists.txt
- CMakeLists.txt
- Framework/TestWorkflows/CMakeLists.txt
- cmake/O2AddWorkflow.cmake
Such an helper can be used to generate executables which are
known to be DPL workflows. Besides adding automatically the dependency
on O2::Framework, this helper will also make sure that the workflow
is executed once with the `--dump` flag so that a JSON representation
is generated and put in `${CMAKE_INSTALL_DATADIR}/dpl` for the sake
of consumption by various deployment mechanisms, e.g. the AliHyperloop
infrastructure. Notice it's also valid to start one of those workflows
with:
o2-dpl-run < $O2_ROOT/share/dpl/some-workflow.json
> Introduce o2_add_dpl_workflow

- DataFormats/Headers/CMakeLists.txt
- DataFormats/Headers/include/Headers/DAQID.h
- DataFormats/Headers/include/Headers/RAWDataHeader.h
- DataFormats/Headers/include/Headers/RDHAny.h
- DataFormats/Headers/src/DAQID.cxx
- DataFormats/Headers/src/RDHAny.cxx
- DataFormats/Headers/test/testDAQID.cxx
- Detectors/ITSMFT/ITS/simulation/src/digi2raw.cxx
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/GBTLink.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/RawPixelReader.h
- Detectors/ITSMFT/common/reconstruction/src/GBTLink.cxx
- Detectors/ITSMFT/common/reconstruction/src/RawPixelDecoder.cxx
- Detectors/ITSMFT/common/simulation/include/ITSMFTSimulation/MC2RawEncoder.h
- Detectors/ITSMFT/common/simulation/src/MC2RawEncoder.cxx
- Detectors/Raw/README.md
- Detectors/Raw/include/DetectorsRaw/HBFUtils.h
- Detectors/Raw/include/DetectorsRaw/RDHUtils.h
- Detectors/Raw/include/DetectorsRaw/RawFileReader.h
- Detectors/Raw/include/DetectorsRaw/RawFileWriter.h
- Detectors/Raw/src/HBFUtils.cxx
- Detectors/Raw/src/RDHUtils.cxx
- Detectors/Raw/src/RawFileReader.cxx
- Detectors/Raw/src/RawFileWriter.cxx
- Detectors/Raw/test/testRawReaderWriter.cxx
- Detectors/TPC/simulation/run/convertDigitsToRawZS.cxx
*   DAQ<->O2 origin mapping + test (RDHv6 contains DQA source ID)
*   Support for arbitrary RDH via RDHAny placeholder
*   RDHUtils::RDHAny can be used operate on the fields of arbitrary RDH version (4,5,6 at the 
moment), provided the statis getter and setters of RDHUtils are used
*   In case of RDH v6 the DAQ source ID is set to the RDH.
*   RawFileWriter can be attributed an O2 origin which in case of RDHv6 is propagated as DAQID to 
the RDH. 
*   User can request to create data with any RDH version by setting awFileWriter::useRDHVersion(xx)
*   RawFileReader will detect/parse the RDH version automatically.
*    Modifications are propagated to ITS/MFT RawPixelDecoder and MC2RawEncoder
*  TPC and ITS mc->raw encoders can use any RDH version.
By dafault, the RDH version linked to …
> RawFileReader/Writer can work with any RDH version, incl. v6

- GPU/Common/FlatObject.h
- GPU/TPCFastTransformation/CMakeLists.txt
- GPU/TPCFastTransformation/Spline1D.cxx
- GPU/TPCFastTransformation/Spline1D.h
- GPU/TPCFastTransformation/Spline2D.cxx
- GPU/TPCFastTransformation/Spline2D.h
- GPU/TPCFastTransformation/SplineHelper1D.h
- GPU/TPCFastTransformation/TPCFastTransform.cxx
- GPU/TPCFastTransformation/TPCFastTransform.h
- GPU/TPCFastTransformation/TPCFastTransformationLinkDef_AliRoot.h
#include "TFile.h"  is replaced by a template argument in FlatObject.h.
The reason is that ROOT classes can not be included from GPUTracker headers, 
because ROOT types are redefined in the GPUTracker.  
TFile.h can only be included from a source file.
> make FlatObject streamer work from GPUTracker library

- Detectors/Raw/include/DetectorsRaw/RDHUtils.h
@shahor02 : I think this is a minimum-invasive way to get rid of the errors for now.
I prefer to really disable the functions instead of just silencing the warnings as in #3452 .
The problem was with the interaction record mostly.
We could also add GPU...() macros there everywhere, but I then we would need #ifdef's again for the iostream stuff in the InteractionRecord.h, so I would like to keep it as simple as possible.
Hopefully this is just sufficient.
> Attempt to get rid of CUDA warnings / errors

- dependencies/CMakeLists.txt
- dependencies/FindO2GPU.cmake
@shahor02 : This fixes the -Werror, which was lost before in the CUDA compilation. In addition, it enables -Werror for the device functions (triggering an error on the problem discussed in #3408).
This means, the warnings in RDHUtils.h must be fixed before this can be merged.
> Make sure compile options (particularly -Werror) are not lost for CUDA

- Detectors/TPC/workflow/include/TPCWorkflow/CATrackerSpec.h
- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- Detectors/TPC/workflow/src/tpc-reco-workflow.cxx
Keep the messages in the DPL internal input queue instead of buffering in the
CA tracker. 
- Using DPL CompletionPolicy to Wait for complete input.
- Also removing all custom code for buffering of input data.
- Removing custom end-of-stream handling, both digitizer and reco workflow are adapted to use only DPL eos, namely there are no data sets with negative sector number in the TPC sector header anymore.
> [O2-1363] Remove buffering of input data from the TPC CA tracker spec

- Framework/Core/include/Framework/InputRecord.h
- Framework/Core/test/test_DataAllocator.cxx
There was compilation problem when using the InputRecord API with vectors of
PODs. Adding also a test case to the unit test.
> DPL Inputrecord: fixing compilation error when trying to use get<std::vector<pod>>

- GPU/GPUTracking/Global/GPUChainTracking.cxx
@davidrohr This should fix the clusters on GPU when skipping ZS.
> TPCClusterFinder: Fix a race condition when using digits as input.

- Detectors/GlobalTracking/include/GlobalTracking/MatchTOF.h
- Detectors/GlobalTracking/src/MatchTOF.cxx
- Detectors/GlobalTrackingWorkflow/tofworkflow/src/RecoWorkflowSpec.cxx
- macro/CMakeLists.txt
- macro/compareTOFClusters.C
Acccordingly to suggestion from PR #3443(Force TOF cluster to be messageable) also tof reco workflow was changed to use span instead of vector from inputs
> change from vector to span in tof reco workflow

- Framework/Utils/include/DPLUtils/MakeRootTreeWriterSpec.h
The content of the variant with the termination conditions was uninitialized,
leading to an invalid instance when extracting a concrete type from the variant.
> Bugfix: Defining a default termination condition in MakeRootTreeWriterSpec

- Detectors/ITSMFT/ITS/workflow/include/ITSWorkflow/ClustererSpec.h
- Detectors/ITSMFT/ITS/workflow/src/ClustererSpec.cxx
- Detectors/ITSMFT/MFT/workflow/src/ClustererSpec.cxx
- Detectors/ITSMFT/common/reconstruction/CMakeLists.txt
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/Clusterer.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/ClustererParam.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/PixelData.h
- Detectors/ITSMFT/common/reconstruction/src/Clusterer.cxx
- Detectors/ITSMFT/common/reconstruction/src/ClustererParam.cxx
- Detectors/ITSMFT/common/reconstruction/src/ITSMFTReconstructionLinkDef.h
- Detectors/ITSMFT/common/workflow/src/STFDecoderSpec.cxx
- Detectors/ITSMFT/common/workflow/src/stf-decoder-workflow.cxx
With ``o2::itsmft::ClustererParam.maxRowColDiffToMask>0`` a special version of maskFiredInSample 
is called which allows to mask neighbours in the vicinity +-maxRowColDiffToMask (both in col.and row) of the overflown fired pixel.
Needed to eliminate corona from lately fired pixels.
> Optionally mask neighbours of overflown pixel

- Detectors/TRD/base/include/TRDBase/Digit.h
MonteCarlo label was taken out but version number not bumped.
> TRD Digits version number bumped

- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
- Steer/DigitizerWorkflow/src/TPCDigitRootWriterSpec.cxx
The span is directly using the raw input data without copy, for writing an
std vector of digits the data needs to be copied to such an object. For the triggered data,
this avoids an extra copy.
In addition, minor change to define only one lane if help printout is produced.
> TPC digitizer workflow: Extracting unserialized TPC digit data by gsl::span

- Detectors/GlobalTrackingWorkflow/tofworkflow/src/tof-reco-workflow.cxx
- Detectors/TOF/base/include/TOFBase/Geo.h
- Detectors/TOF/base/include/TOFBase/WindowFiller.h
- Detectors/TOF/base/src/Geo.cxx
- Detectors/TOF/reconstruction/src/Encoder.cxx
- Detectors/TOF/simulation/src/Digitizer.cxx
- Detectors/TOF/workflow/src/CompressedDecodingTask.cxx
- Detectors/TOF/workflow/src/TOFRawWriterSpec.cxx
Hi @noferini 
Since you were caching the HBFUtils::getNOrbitsPerTF in  ``Geo::ORBIT_IN_TF``, the eventual changes in the former were not propagating to the code which needed this parameter.
This PR changes the caching to direct use of HBFUtils. Also, it allows to pass the ``configKeyValues`` option to TOF workflow, needed e.g. to set non-standard values in HBFUtils. No I am at least able to generate raw data with e.g. 128 HB per TF.
Still, I see some problems in  the raw data generation, please see comments I am adding to this PR.
> Fixes usage of HBFUtils::nOrbitsPerTF in TOF (e.g. raw data generation with non-standard) 

- Detectors/TRD/simulation/include/TRDSimulation/Digitizer.h
- Detectors/TRD/simulation/src/Digitizer.cxx
Two minor improvements were spotted while developing the pileup implementation for the TRD digitizer: 
- Make several variables class members rather than local variables. They are initialized at the construction of the digitizer.
- Swapped a for-if loop for a if-for loop to minimize the number of if-else comparisons.
I prefer to make this small PR now and do not mix this with the pileup implementation.
In 10 pp events:
(Now) `TRD: Digitization took 0.949013s`
(Before) `TRD: Digitization took 1.11397s`
In 1 hi event:
(Now) `TRD: Digitization took 124.626s`
(Before) `TRD: Digitization took 136.157s`
> TRD Digitizer: moving temporary variables to class members

- Analysis/Tutorials/src/eventMixing.cxx
- Analysis/Tutorials/src/tracksCombinations.cxx
- Framework/Core/ANALYSIS.md
- Framework/Core/include/Framework/ASoAHelpers.h
- Framework/Core/test/benchmark_ASoAHelpers.cxx
- Framework/Core/test/test_ASoAHelpers.cxx
- under- and overflows can be ignored
- limited number of combinations per category
- simplified combinations .end()
> DPL Analysis: Fixes for block combinations / mixed events

- Detectors/ITSMFT/ITS/simulation/src/digi2raw.cxx
- Detectors/Raw/README.md
- Detectors/Raw/include/DetectorsRaw/RDHUtils.h
- Detectors/Raw/include/DetectorsRaw/RawFileReader.h
- Detectors/Raw/include/DetectorsRaw/RawFileWriter.h
- Detectors/Raw/src/RawFileReader.cxx
- Detectors/Raw/src/RawFileReaderWorkflow.cxx
- Detectors/Raw/src/RawFileReaderWorkflow.h
- Detectors/Raw/src/RawFileWriter.cxx
- Detectors/Raw/src/rawfile-reader-workflow.cxx
- Detectors/Raw/src/rawfileCheck.cxx
* Checking for non-fatal errors can be suppressed in the raw-file-reader-workflow
* Adding for empty HBF may be optionally avoided in the writer except for 1st HBFs of TF
> Options to suppress error check in RawReader and empty HBFs in RawWriter

- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/GBTLink.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/RawPixelDecoder.h
- Detectors/ITSMFT/common/reconstruction/src/GBTLink.cxx
- Detectors/ITSMFT/common/reconstruction/src/RawPixelDecoder.cxx
- Detectors/ITSMFT/common/workflow/include/ITSMFTWorkflow/STFDecoderSpec.h
- Detectors/ITSMFT/common/workflow/src/STFDecoderSpec.cxx
With option --old-format provided the STFDecoderSpec will interpret data as
in old format: single trigger per HBF, no GBT trigger word
> Support decoding old ITS/MFT format

- Detectors/TPC/workflow/src/tpc-reco-workflow.cxx
As it triggers throwing exception after suppressing bufferization
@matthiasrichter The commented line triggers processing data of different sectors as they arrive instead of waiting for the complete TF, which triggers the exception mentioned in private emails.
> Fix: disable TPC CAtracker completion policy customization

- Detectors/EMCAL/simulation/src/Digitizer.cxx
[EMCAL-502] generate positive noise digits only
Change Digitizer class to generate only noise Digits with positive energies.
> [EMCAL-502] generate positive noise digits only

- Detectors/TPC/reconstruction/test/testGPUCATracking.cxx
- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- GPU/GPUTracking/Base/GPUDataTypes.h
- GPU/GPUTracking/CMakeLists.txt
- GPU/GPUTracking/GPUTrackingLinkDef_O2.h
- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/Global/GPUChainTracking.h
- GPU/GPUTracking/Global/GPUChainTrackingIO.cxx
- GPU/GPUTracking/Interface/GPUO2Interface.cxx
- GPU/GPUTracking/Interface/GPUO2Interface.h
- GPU/GPUTracking/Merger/GPUTPCGMTrackParam.cxx
- GPU/GPUTracking/dEdx/GPUdEdx.h
- GPU/GPUTracking/dEdx/TPCdEdxCalibrationSplines.cxx
- GPU/GPUTracking/dEdx/TPCdEdxCalibrationSplines.h
The splines which will be used to correct the dE/dx for detector effects like different pad sizes and track topologies (local dip angle: z angle - dz/dx and diffusion from electron drift) are created by the Random Forest ML algorithm. The training data is created by the O2 simulation with artificial tracks (no Landau distribution, constant dE/dx, fixed GEM amplification of 2000). For each region and for qMax/qTot an individual spline is created which leads to a total of 20 splines. 
It is planned to make further topological corrections also with the splines: relative pad and time position of a track, local inclination angle: y angle = dy/dx (improves dE/dx at low momenta) and threshold effects.
> Adding TPCdEdxCalibrationSplines class to correct the dEdx for geometrical and track topological effects

- Generators/src/Generator.cxx
This PR fixes a bug in the logic of the event-generator trigger.
The particle vector was not cleared after a failed trigger.
> Fix a bug in the event-generator trigger logic not clearing particles

- Common/Utils/include/CommonUtils/ConfigurableParam.h
- Common/Utils/include/CommonUtils/ConfigurableParamHelper.h
- Common/Utils/src/ConfigurableParamHelper.cxx
- make sure provenance information is available before
printing parameter
- use std::string const& instead of std::string
- print main parameter key in printouts
> ConfParam: minor improvements

- Generators/include/Generators/Generator.h
- Generators/include/Generators/GeneratorPythia8.h
- Generators/src/Generator.cxx
- Generators/src/GeneratorPythia8.cxx
- doc/DetectorSimulation.md
- run/SimExamples/README.md
- run/SimExamples/Signal_ImpactB/README.md
- run/SimExamples/Signal_ImpactB/run.sh
- run/SimExamples/Signal_ImpactB/signal_impactb.macro
This PR implements the `updateHeader` virtual method of the `o2::eventgen::Generator` class.
The method is called in the generation loop and can be overridden by a concrete `Generator`.
This allows generators to update the `MCEventHeader` with extra information.
In this case, `Pythia8` updates the impact parameter information in the `MCEventHeader` in case it is sunning the heavy-ion model.
The extra information can be used by event generators of signal events in an embedding scenario, to allow them to tune the generation on the background event to be embedded into.
This PR also brings an example of the use of the impact parameter in embedding simulation.
The simulation example show the following things
a) how to run a simple background event simulation with some parameter customization …
> Add Pythia8 HI impact parameter to event header + example

- Detectors/MUON/MCH/Mapping/README.md
- Detectors/MUON/MCH/Mapping/cli/CMakeLists.txt
- Detectors/MUON/MCH/Mapping/cli/cli.cxx
in order to ease spot checks (e.g. for decoder debugging during commissioning)
> [MCH] Add small CLI for mapping

- Detectors/GlobalTrackingWorkflow/tofworkflow/src/TOFMatchedWriterSpec.cxx
- Detectors/GlobalTrackingWorkflow/tofworkflow/src/tof-reco-workflow.cxx
- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- Detectors/TPC/workflow/src/RecoWorkflow.cxx
* TPC::TRACKMCLBL make outputSpec names consistent
Depending on the device the Tracks MC labels were called either TRACKMCLBL or TRACSKMCLBL
* TOF workflow: allow disabling root I/O for w-flows merging
In the ``raw`` mode the input from the root files (e.g. TPCITS tracks) should be disabled in favor of direct DPL input from TPC/ITS matcher. Explicitly add option to disable root input and output to be able to merge different workflows.
Fix in tree filling.
--------------------------
Instructions to run (just for the record) combined w-flow:
In ``raw`` data mode:
````
o2-raw-file-reader-workflow --loop 1 --conf raw/rawAll.cfg | o2-itsmft-stf-decoder-workflow |  o2-its-reco-workflow --disable-mc --clusters-from-upstream --disable-root-output  | o2-tpc-reco-workflow --ca-clusterer …
```
> Fixes for combining reco workflows

- Detectors/ITSMFT/ITS/README.md
- Detectors/ITSMFT/ITS/reconstruction/CMakeLists.txt
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/FastMultEst.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/FastMultEstConfig.h
- Detectors/ITSMFT/ITS/reconstruction/src/FastMultEst.cxx
- Detectors/ITSMFT/ITS/reconstruction/src/FastMultEstConfig.cxx
- Detectors/ITSMFT/ITS/workflow/src/CookedTrackerSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/TrackerSpec.cxx
* Fast mult.estimator and its config for ITS selective reconstruction:
implements fast estimator of signal clusters multiplicity either via free noise + signal fit
or via signal fit with noise level imposed. Multiplicity is provided as Ncl. per layer modulo acceptance
correction from the FastMultEstConfig. The latter provides the settings for the estimator as well as 
the low/high cuts on the estimate mult. and (if these cuts are passed) eventual cuts on the vertices multiplicity used to seed the ITS tracks.
* FastMultEst and cuts from FastMultEstConfig are deployed in ITS tracking workflows to avoid tracking ROF with too high or too low number of signal clusters (or vertices with too many contributors. The following command will track only ROFs with N signal clusters between 50 and 4000 …
> Multiplicity estimator and ev. selection for ITS sync. processing

- DataFormats/Headers/include/Headers/Stack.h
- DataFormats/Headers/test/testDataHeader.cxx
at runtime we don't always know the type of the header but it should be enough to construct a stack anyway from whatever get<> gives back.
> Fix stack construction from BaseHeader references

- Generators/src/GeneratorPythia8.cxx
This PR prepares a few pieces of the O2 for the upgrade of Pythia8 to version 8.302.
Given that a few details have changed in the API, corresponding pre-processor directives have been put in place to allow the code to be built safely with both the current Pythia8 version and the upcoming one.
Also, the patch to set the vertices at (0,0,0) as discussed in #3446 is not needed anymore in the upcoming Pythia8.302 version.
> Get ready for Pythia8 upgrade to 8.302

- run/SimExamples/README.md
- run/SimExamples/Trigger_ImpactB_Pythia8/README.md
- run/SimExamples/Trigger_ImpactB_Pythia8/run.sh
- run/SimExamples/Trigger_ImpactB_Pythia8/trigger_impactb_pythia8.macro
This is a simple simulation example showing how to run event simulation using the Pythia8 event generator in heavy-ion mode and use an external custom trigger.
The external trigger makes use of the `DeepTrigger` functionality to allow the user to access the internals of the event generator to define the trigger.
In this example, information about the impact parameter of the currently-generated Pythia8 heavy-ion event is used.
The trigger selection defines impact parameters to be accepted according to a min-max range that can be adjusted from the command line.
The definition and configuration of the external `DeepTrigger` is performed by the function `trigger_impactb_pythia8(double bMin = 0., double bMax = 20.)` defined in the macro `trigger_impactb_pythia8.macro`.
The macro file is …
> An example to run Pythia8 heavy-ion with impact-parameter trigger

- Detectors/EMCAL/workflow/src/CellConverterSpec.cxx
- Detectors/EMCAL/workflow/src/ClusterizerSpec.cxx
- Detectors/EMCAL/workflow/src/DigitsPrinterSpec.cxx
- Detectors/EMCAL/workflow/src/PublisherSpec.cxx
@mfasDa this fixes the hunging of the workflow: the publisher should declare end of stream once data is over. Still, I am not sure why the processing devices can get data with ``emcheader->mHasPayload==0``? Could you recheck the publisher, perhaps it does 1 empty cycle in the end?
> EMCal wokflow: fix in completion policy

- Detectors/MUON/MCH/Workflow/CMakeLists.txt
- Detectors/MUON/MCH/Workflow/src/cru-page-reader-workflow.cxx
- Detectors/MUON/MCH/Workflow/src/hbf-reader-workflow.cxx
The workflow allows to read the contents of a binary file filled with a sequence of HBFrames.
Such file can be created for example by saving the output of readout.exe to file.
This reader does not perform any consistency check on the RDH sequence in the file,
it only checks the header version and size and uses the `offsetToNext` RDH
field to determine the size of the frame.
As such, it is more tolerant than the official `o2-raw-file-reader-workflow` and can be useful in the readout debugging/commissioning phase, for example to read files where empty HBFrames have been skipped.
> [MCH] added simple HBFrame reader workflow

- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/ASoAHelpers.h
- Framework/Core/include/Framework/AnalysisTask.h
- Framework/Core/include/Framework/ArrowTypes.h
- Framework/Core/include/Framework/Kernels.h
- Framework/Core/src/Kernels.cxx
- Framework/Core/test/test_ASoA.cxx
- Framework/Core/test/test_GroupSlicer.cxx
- Framework/Core/test/test_Kernels.cxx
* Added support for empty underlying tables in soa::Table
* Improved type handling for table slicing kernel
* Temporary removed slicing test in test_ASoA
Now it is possible to not have exact correspondence between grouping
table entries and groups in a grouped table.
> DPL Analysis: grouping extension for empty sets

- DataFormats/Reconstruction/include/ReconstructionDataFormats/BaseCluster.h
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/Tracker.h
- Detectors/ITSMFT/ITS/tracking/src/IOUtils.cxx
- Detectors/ITSMFT/ITS/tracking/src/Tracker.cxx
- Detectors/ITSMFT/ITS/workflow/src/TrackerSpec.cxx
The cluster indices were registered wrt ROF start only in MCLabels mode while in raw mode they were kept wrt TF start.
Indices must be stored in out->in order
> Fix in ITS CAtracker cluster indexing 

- Detectors/GlobalTrackingWorkflow/tpcinterpolationworkflow/include/TPCInterpolationWorkflow/TrackInterpolationWorkflow.h
- Detectors/GlobalTrackingWorkflow/tpcinterpolationworkflow/src/TrackInterpolationWorkflow.cxx
- Detectors/GlobalTrackingWorkflow/tpcinterpolationworkflow/src/tpc-interpolation-workflow.cxx
Needed for clean merging of workflows.
Also, removed ``disable-mc`` option since the MC is anyway not supported in this flow
> Optionally disable root I/O in TPC calib interpolation workflow

- Detectors/FIT/workflow/include/FITWorkflow/RecoWorkflow.h
- Detectors/FIT/workflow/src/RecoWorkflow.cxx
- Detectors/FIT/workflow/src/fit-reco-workflow.cxx
- Detectors/GlobalTrackingWorkflow/src/tpcits-match-workflow.cxx
Hi @AllaMaevskaya 
As far as I can see, there is no yet decoded device to convert the T0 raw stream to digits which can be used for the reconstruction. 
Could you prepare one, please? The aim is to have ``o2-ft0-decoderaw`` device to be able to run:
````
o2-ft0-digi2raw  -o raw/FT0
o2-raw-file-reader-workflow --conf raw/FT0/FT0raw.cfg | o2-ft0-decoderaw | o2-fit-reco-workflow --disable-mc --disable-root-input
````
i.e. ``o2-fit-reco-workflow`` getting the input not from the digits file using reader but from the DPL
> options to disable root I/O in fit workflow

- Detectors/EMCAL/workflow/include/EMCALWorkflow/ClusterizerSpec.h
- Detectors/EMCAL/workflow/src/CellConverterSpec.cxx
- Detectors/EMCAL/workflow/src/ClusterizerSpec.cxx
- Detectors/EMCAL/workflow/src/DigitsPrinterSpec.cxx
- Detectors/EMCAL/workflow/src/PublisherSpec.cxx
* eliminate dummy data sendning cycle in the end of publisher processing and
the protection against processing these empty data in all processor devices.
* do not create MC outputSpec in the publisher if MC was disabled.
* add timer for the Clusterizer
@mfasDa there was indeed an empty cycle in the of the publisher lifetime (apparently in the original TPC code it served to inform the downstream devices about the end of data, not needed anymore sine endOfStream() is available).
Benchmarking the data you provided I see (fixed to 2.4 GHz) 0.062s per your Run2 "TF". If it indeed contains 300 EMC triggers, than we are completely safe. 
But this looks too good and is certainly not compatible with 0.02s per single pp triggers. Perhaps you should rerun pp again. 
In my test I see ~ 320 clusters …
> Fixes in EMCal workflow

- Detectors/MUON/MID/Raw/include/MIDRaw/ColumnDataToLocalBoard.h
- Detectors/MUON/MID/Raw/src/ColumnDataToLocalBoard.cxx
- Detectors/MUON/MID/Raw/src/Encoder.cxx
- Detectors/MUON/MID/Raw/test/testRaw.cxx
This PR fixes two issues:
- the answer of the local boards to the HB trigger was incorrectly encoded, resulting in errors in the decoding of data
- the case where only the anode or cathode was fired was not correctly treated
The PR also includes some additional tests to spot these two cases.
The commits are meant to be atomic: please do not squash them.
> Fix bugs in the encoding of MID raw data

- Analysis/Tutorials/src/associatedExample.cxx
- Framework/Core/include/Framework/AnalysisTask.h
* Allows to use Joins for grouping, for example
`process(soa::Join<aod::Collisions, aod::CollisionsExtra>::iterator, aod::Tracks)`
* Updated tutorial example that demonstrates it
> DPL Analysis: Fix for grouping with a joined iterator

- DataFormats/Headers/include/Headers/DataHeader.h
- DataFormats/Headers/test/testDataHeader.cxx
- Framework/Utils/test/test_RootTreeReader.cxx
- Utilities/O2Device/test/test_O2Device.cxx
Since all data parts are equipped with this there is enough reason to move this into the DataHeader, as was envisioned and agreed. Please do comment on the exact layout of this, for now it is long uint. 8 bytes should be enough for everybody.
> Add TF id member to DataHeader

- Detectors/GlobalTracking/include/GlobalTracking/MatchTPCITS.h
- Detectors/GlobalTracking/src/MatchTPCITS.cxx
For the record: matching of low-mult. preselected ITS data to TPC is slower than the naive ITS multiplicity scaling because 100% of TPC tracks are prepared for matching (and only ~1% is used).
Given that matching in sync. reco is done having in mind further matching in TRD and TOF, one could apply a low pT cut-off of 0.4 GeV (at least)  w/o any loss of efficiency. Only this speeds up the matching by factor of 2.
````
o2-tpcits-match-workflow --configKeyValues "tpcitsMatch.minTPCPt=0.4" ...
````
> More detailed timing for TPC/ITS matching

- Framework/Core/CMakeLists.txt
- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/test/test_RegionInfoCallbackService.cxx
Apparently our service registry gets confused if it gets a non-const
object.
> DPL: make sure the RegionInfoCallback is actually invoked

- Framework/Core/src/InputRecord.cxx
FairMQ shared memory transport gives a nullptr for a zero-length message,
while zmq transport returns a valid pointer. Validity check did require
both valid header and payload message pointers. That makes zero length
shared memory messages to be masked out.
In principle it's enough to check for the header message pointer because
the DataRelayer logic makes sure that the message pair has arrived. To
check for the payload message pointer we would need to check the payload
size and her it would mean to get DataHeader and check. Some overhead
we probably do not want.
> DPL: Base validity check for InputRecord route on header message only

- Detectors/Vertexing/include/DetectorsVertexing/DCAFitterN.h
Hi @shahor02 ,
while working on the hypertriton 3 body decay @galocco spotted this typo. I corrected it as it seems to me appropriate, please check it is fine.
We are checking what is the effect.
Cheers,
Max
> Fix copy/paste typo in starting point definition

- Framework/Core/include/Framework/DataRefUtils.h
- Framework/Core/include/Framework/TypeTraits.h
- Framework/Core/test/test_DataRefUtils.cxx
Collections in ROOT can be non-owning or owning and the proper cleanup depends on
this flag. Be it a bug or a feature in ROOT, but the owning flag of the extracted
object only depends on the state at serialization of the original object. However,
all objects created during deserialization are new and must be owned by the collection
to avoid memory leak. So we call SetOwner if available for the type.
> DPL IO: Make extracted ROOT collections owning to avoid memory leak

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/RootConfigParamHelpers.h
- Framework/Core/src/RootConfigParamHelpers.cxx
- Framework/Core/test/FrameworkCoreTestLinkDef.h
- Framework/Core/test/TestClasses.h
- Framework/Core/test/test_RootConfigParamHelpers.cxx
This allows defining a set of ConfigParamSpecs from a ROOT serializable
class.
An extra helper allows going from a ptree to an instance of such a class,
closing the circle.
Further improvements will allow getting the instance directly from the
ConfigParamRegistry, e.g.:
ctx.options.get<Klass>("someClass");
Notice how the mechanism can already support multiple instances of the same
class.
> DPL: add support for ROOT serialised classes as ConfigParamSpecs

- Detectors/ITSMFT/ITS/macros/test/CheckTopologies.C
- Detectors/ITSMFT/ITS/reconstruction/src/ClustererTask.cxx
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/Clusterer.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/PixelData.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/RawPixelReader.h
- Detectors/ITSMFT/common/reconstruction/src/Clusterer.cxx
Since the loop over the ROFs in updated clusterization is managed by the clusterizer rather than
the reader (even in autoRead mode), the reader should try to cache its data at decodeNextTrigger call.
Eliminate the internal tree in the cluster: we anyway do not store per ROF.
> Fix: data caching for ITS SA clustering with old reader

- Detectors/Raw/README.md
- Detectors/Raw/include/DetectorsRaw/RawFileReader.h
- Detectors/Raw/include/DetectorsRaw/RawFileWriter.h
- Detectors/Raw/src/RawFileReader.cxx
- Detectors/Raw/src/RawFileWriter.cxx
- Detectors/Raw/src/rawfile-reader-workflow.cxx
- Detectors/Raw/src/rawfileCheck.cxx
- Detectors/TPC/simulation/run/convertDigitsToRawZS.cxx
* Detector may chose if HBF end is signaled by RDH.stop on new page
Some detectors signal the end of the HBF by adding an empty CRU page containing
just a header with RDH.stop=1 while others may simply set the RDH.stop in the last
page of the HBF (it may appear to be also the 1st and the page of the HBF and may or
may not  contain the payload). This behaviour is steered by call
writer.setAddSeparateHBFStopPage(bool v). By default end of the HBF is signaled on separate page.
* By default don't treat as error RDH.stop on 1st HBF page (need to be requested specially)
* TPC ZS data converter does not add empty page to signal HBF end.
The RDH.stop=1 will be set at the last CRU page of the HBF, w/o adding separate page for that.
This behaviour can be inverted using option -p [ --stop-page ]
> Detector may chose if HBF end is signaled by RDH.stop on new page

- Framework/Utils/include/DPLUtils/MakeRootTreeWriterSpec.h
- Framework/Utils/include/DPLUtils/RootTreeWriter.h
- Framework/Utils/test/test_RootTreeWriter.cxx
- Framework/Utils/test/test_RootTreeWriterWorkflow.cxx
Updated compile time build of the branch definitions from argument pack. It is now possible to call additional methods for initialization without a virtual interface. This is used to set optional handler callbacks.
New features
- Custom optional preprocessor can be added to DataProcessorSpec generator
- Custom optional handler callback for branch definitions
- Reducing the number of compiled branches, internal compile optimization
> Updating DPL RootTreeWriter

- Framework/Core/CMakeLists.txt
Want to enable the unit test, but we first need to fix this in FairMQ or in the DPL driver.
There is a problem in the termination of the FairMQDevice by signals because
the pending input polling is aborted and this throws an error
```
[ERROR] Failed receiving on socket input-proxy.input-proxy[0].pull, reason: Interrupted system call, nbytes = -1
```
This make the unit test fail for the moment.
> DPL: Enable unit test test_ExternalFairMQDeviceWorkflow

- DataFormats/Headers/include/Headers/DataHeader.h
- DataFormats/Headers/src/DataHeader.cxx
This is a follow up of the recent change of the `DataHeader`, #3475 
Checking if the header version and size matches the implementation.
There is no support for multiple versions of a particular header at
the moment. The minimum is to require the size and version to match
the current implementation.
TODO
> Sanity check for O2 headers on the header stack

- Framework/Core/ANALYSIS.md
- Framework/Core/include/Framework/ASoAHelpers.h
- Framework/Core/test/benchmark_ASoAHelpers.cxx
- Framework/Core/test/test_ASoAHelpers.cxx
- loosened constraints on sliding window
- fixed all combinations for the case of different tables of different size
- all combinations on different tables are upper by default, not full
> DPL Analysis: Final fixes for block combinations, edge cases for basic combinations

- Analysis/DataModel/src/dumpDataModel.cxx
- Framework/Core/include/Framework/AnalysisDataModel.h
Rename Label to Lbl since label in O2 is used in different scope. 
Add the MC information to dumpDataModel
> Label renamed to Lbl, MC information in dumpDataModel

- Framework/Core/include/Framework/runDataProcessing.h
- Framework/Core/src/runDataProcessing.cxx
We are reviewing the way we create, populate, catch and rethrow exceptions in QC as they were implemented at a time when DPL did not exist and we had our own `main()`. 
The exceptions we use in QC and the other FLP repositories are based on `boost::exception`. I don't think that we should debate here and now whether it is good or not.
The fatal exceptions are left bubbling up, finally reaching the DPL main. The way  they are printed at the moment do not take advantage of the details we add to them.  
For example this is the current output of a configuration mistake that is not recoverable : 
```
[ERROR] error while setting up workflow: AliceO2::Common::Exception
[INFO] Process 19328 is exiting.
```
vs the one after this PR : 
```
[ERROR] error while setting up workflow: …
```
> handle boost exceptions to print all details

- Detectors/TPC/workflow/src/CATrackerSpec.cxx
This implements the callback to register the memory for the GPU.
Requires #3499 and #3521 to be merged.
@ktf : I assume I have to change something in `Detectors/Raw/src/RawFileReaderWorkflow.cxx` to make it send the data via a shared memory region. Can you give me a hint? As it is now, the workflow still runs but the callback is not called.
> GPU: Implement callback to register shared memory regions for GPU DMA

- Detectors/TPC/workflow/src/RecoWorkflow.cxx
- removing remnants of custom end-of-stream handling
The checkReady callback is not necessary anymore to steer termination of the
workflow, eos is handled inside DPL
- MC label branches are optionally disabled at runtime using a new feature of
the RootTreeWriter. The definition of branches can now be done completely
at compile time, separate code branches for the different can be avoided
> Simplifying creation of writers in the TPC reco workflow

- Analysis/DataModel/src/dumpDataModel.cxx
- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/AnalysisTask.h
- Framework/Core/include/Framework/RootTableBuilderHelpers.h
- Framework/Core/include/Framework/TableBuilder.h
- Framework/Core/src/verifyAODFile.cxx
* Replace `soa::Column::label()` with `soa::Column::columnLabel()` so that one can have `label()` as a getter for a column. 
* Replace `aod::TableMetadata::label()` with `tableLabel` for consistency
> DPL: distinctly named *label() methods for soa::Column and Table

- Detectors/Raw/README.md
- Detectors/Raw/src/RawFileReader.cxx
- Detectors/Raw/src/rawfile-reader-workflow.cxx
- Detectors/Raw/src/rawfileCheck.cxx
To avoid clash with global framework options the configuration file with raw data should be
provided via --input-conf options.
Fix in the error-checking optional requests processing
> Fix RawReader options, --input-conf instead of --conf

- Detectors/TPC/simulation/run/convertDigitsToRawZS.cxx
- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- GPU/GPUTracking/Base/GPUReconstruction.h
- GPU/GPUTracking/Base/GPUReconstructionConvert.cxx
- GPU/GPUTracking/Base/GPUReconstructionConvert.h
- GPU/GPUTracking/Global/GPUChainTracking.cxx
@shahor02 : Add option --no-padding to TPC raw writer. Currently, the tpc-reco-workflow fails for me reading raw data:
```
o2-raw-file-reader-workflow --conf tpcrawzs.raw/tpcraw.cfg | o2-tpc-reco-workflow --ca-clusterer --input-type=zsraw --disable-m
Invalid workflow: No matching output found for <matcher query: (and origin:TPC (and startTime:$0  description:RAWDATA ))>. Candidates:
-TPC/CLUSREFS/0
-TPC/TRACKS/0
```
> Support padded or unpadded TPC ZS pages

- Detectors/TPC/workflow/CMakeLists.txt
- Detectors/TPC/workflow/include/TPCWorkflow/TPCSectorCompletionPolicy.h
- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- Detectors/TPC/workflow/src/TPCSectorCompletionPolicy.cxx
- Detectors/TPC/workflow/src/tpc-reco-workflow.cxx
Background: the DPL completion policy defines when a data set is complete for
computation. The default policy is true if there is data on all input routes.
The TPC data is split into parts per sector, and currently the workflow defines
one route per sector. Also the CA tracker spec defines one input route per sector.
In order to support multiple parts(sectors) on the same input route, e.g. by a
generalized matcher with a wildcard om the subSpec, a custom policy needs to be
added to tell DPL when the data set is complete
Fixing the logic of the completion policy
- correcting the check for mixed cluster and digit input which is not allowed,
but the tracker spec needs to be adjusted to support either the one or the other,
the this temporary check can be removed
- for digit or cluster input …
> Correcting the TPC CA tracker completion policy and reactivating it

- DataFormats/Detectors/TPC/include/DataFormatsTPC/Helpers.h
- DataFormats/Detectors/TPC/include/DataFormatsTPC/ZeroSuppression.h
- DataFormats/Detectors/TPC/src/DataFormatsTPCLinkDef.h
- Detectors/TPC/base/CMakeLists.txt
- Detectors/TPC/base/include/TPCBase/ZeroSuppress.h
- Detectors/TPC/base/src/ZeroSuppress.cxx
- Detectors/TPC/workflow/CMakeLists.txt
- Detectors/TPC/workflow/include/TPCWorkflow/CATrackerSpec.h
- Detectors/TPC/workflow/include/TPCWorkflow/RecoWorkflow.h
- Detectors/TPC/workflow/include/TPCWorkflow/ZSSpec.h
- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- Detectors/TPC/workflow/src/RecoWorkflow.cxx
- Detectors/TPC/workflow/src/ZSSpec.cxx
- Detectors/TPC/workflow/src/tpc-reco-workflow.cxx
- GPU/GPUTracking/Base/GPUReconstructionConvert.cxx
new options for the o2-tpc-reco-workflow for the usage with the ca-clusterer, to use zero suppression with digits from simulation:
-tpc-zs  : convert input tpc digits to zero suppressed raw pages and feed them into the ca-tracker
-zs-threshold : set zero suppression threshold, default 2.0
--zs-10bit  : use 10 bit ADC values for the zero suppression, default (false) use 12 bit ADC 
sample usage:
o2-tpc-reco-workflow --infile tpcdigits.root --ca-clusterer --tpc-zs --disable-mc 
option --disable-mc is still mandatory, tpc-tracker segfaults when forwarding MC from digits is enabled
> TPC workflow for zs from digits including MC

- Framework/Core/include/Framework/AnalysisTask.h
Removing <charconv> code path until it can be used without version checks.
> Do not use <charconv> for now

- DataFormats/Detectors/TPC/include/DataFormatsTPC/TPCSectorHeader.h
- Detectors/GlobalTrackingWorkflow/src/TPCITSMatchingSpec.cxx
- Detectors/GlobalTrackingWorkflow/tpcinterpolationworkflow/src/TPCInterpolationSpec.cxx
- Detectors/TPC/workflow/include/TPCWorkflow/TPCSectorCompletionPolicy.h
- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- Detectors/TPC/workflow/src/ClusterDecoderRawSpec.cxx
- Detectors/TPC/workflow/src/ClustererSpec.cxx
- Detectors/TPC/workflow/src/RecoWorkflow.cxx
- Detectors/TPC/workflow/src/ZSSpec.cxx
- Steer/DigitizerWorkflow/src/TPCDigitRootWriterSpec.cxx
- Steer/DigitizerWorkflow/src/TPCDigitizerSpec.cxx
TPCSectorHeader has been used to transport information for single TPC sectors.
For future extensions it will be needed to mark multiple sectors, the new
version uses one bit for each sector which will be set if data is present for
the sector.
We will need this to be more flexible with the exchange of TPC data, like e.g. #3552.
> Updating version of TPCSectorHeader

- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/Core/test/test_FrameworkDataFlowToDDS.cxx
- Framework/TestWorkflows/src/o2DiamondWorkflow.cxx
* If present, it's forwarded to each device and handled by FairMQ.
* If not present, it's added to the options of each device, forcing
the "info" log level.
Notice that setting it higher than "INFO" can only be done if an external
Control is used, since the DPL driver sends control messages as INFO level.
> DPL: add global --severity option

- Steer/CMakeLists.txt
- Steer/src/O2MCApplication.cxx
For the record, I found this one when trying to compile only Mch-related targets using : 
```
cmake --build . --target $(ninja -t targets | grep -i "^O2" | grep -i mch | cut -d ':' -f 1 | tr "\n" " ")
```
and still getting TPC libs built...
> [Steer] Remove unwanted/unneeded depencency on TPCSimulation

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/BoostOptionsRetriever.h
- Framework/Core/include/Framework/ConfigParamRegistry.h
- Framework/Core/include/Framework/ConfigParamStore.h
- Framework/Core/include/Framework/DeviceConfigInfo.h
- Framework/Core/include/Framework/DeviceInfo.h
- Framework/Core/include/Framework/FairOptionsRetriever.h
- Framework/Core/include/Framework/ParamRetriever.h
- Framework/Core/include/Framework/SimpleOptionsRetriever.h
- Framework/Core/include/Framework/runDataProcessing.h
- Framework/Core/src/BoostOptionsRetriever.cxx
- Framework/Core/src/ConfigParamStore.cxx
- Framework/Core/src/ConfigurationOptionsRetriever.cxx
- Framework/Core/src/ConfigurationOptionsRetriever.h
- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/src/DeviceConfigInfo.cxx
- Framework/Core/src/FairOptionsRetriever.cxx
- Framework/Core/src/FrameworkGUIDeviceInspector.cxx
- Framework/Core/src/PropertyTreeHelpers.cxx
- Framework/Core/src/PropertyTreeHelpers.h
- Framework/Core/src/SimpleOptionsRetriever.cxx
- Framework/Core/src/runDataProcessing.cxx
- Framework/Core/test/benchmark_WorkflowHelpers.cxx
- Framework/Core/test/test_ConfigParamStore.cxx
- Framework/Core/test/test_ConfigurationOptionsRetriever.cxx
- Framework/Core/test/test_DeviceConfigInfo.cxx
- Framework/Core/test/test_FairMQOptionsRetriever.cxx
- Framework/Core/test/test_RootConfigParamHelpers.cxx
- Framework/Core/test/test_WorkflowHelpers.cxx
- Framework/Core/test/unittest_SimpleOptionsRetriever.cxx
This also include framework support for multiple, nested,
ParamRetriever. To be integrated by the driver / GUI.
> DPL: add provenance information for ConfigParamSpec

- DataFormats/Detectors/TPC/include/DataFormatsTPC/ClusterNativeHelper.h
The short version is skipping the MCLabel parameters for use cases
without labels.
> Adding a short version of ClusterNativeHelper fillIndex

- DataFormats/Detectors/TPC/include/DataFormatsTPC/ClusterNativeHelper.h
- Detectors/GlobalTrackingWorkflow/include/GlobalTrackingWorkflow/TPCITSMatchingSpec.h
- Detectors/GlobalTrackingWorkflow/src/TPCITSMatchingSpec.cxx
- Detectors/GlobalTrackingWorkflow/src/tpcits-match-workflow.cxx
- Detectors/GlobalTrackingWorkflow/tpcinterpolationworkflow/include/TPCInterpolationWorkflow/TPCInterpolationSpec.h
- Detectors/GlobalTrackingWorkflow/tpcinterpolationworkflow/src/TPCInterpolationSpec.cxx
- Detectors/GlobalTrackingWorkflow/tpcinterpolationworkflow/src/tpc-interpolation-workflow.cxx
- Detectors/TPC/workflow/include/TPCWorkflow/TPCSectorCompletionPolicy.h
The matcher process requires the TPC sector completion to trigger and data on
all defined routes.
@davidrohr , @shahor02 this is an example for a custom completion policy. We could implement it in a dedicated class for the global matching workflows.
>  Defining completion policy for the GlobalTrackingWorkflow processor specs and some cleanup

- DataFormats/Detectors/TPC/include/DataFormatsTPC/ClusterNativeHelper.h
- DataFormats/Detectors/TPC/src/ClusterNativeHelper.cxx
- Detectors/GlobalTrackingWorkflow/src/TPCITSMatchingSpec.cxx
- Detectors/GlobalTrackingWorkflow/tpcinterpolationworkflow/src/TPCInterpolationSpec.cxx
- Detectors/TPC/reconstruction/include/TPCReconstruction/HardwareClusterDecoder.h
- Detectors/TPC/reconstruction/src/HardwareClusterDecoder.cxx
- Detectors/TPC/workflow/include/TPCWorkflow/TPCSectorCompletionPolicy.h
- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- Detectors/TPC/workflow/src/ClusterDecoderRawSpec.cxx
- Detectors/TPC/workflow/src/PublisherSpec.cxx
- Detectors/TPC/workflow/src/RecoWorkflow.cxx
This PR is sketching the work for moving to an updated transport format as it is produced by the CAclusterer. The format consists of a header with the index of cluster counts for the full TPC and one monolithic buffer for all cluster objects. The cluster offsets per {sector,row} coordinates corresponds to the accumulated cluster counts. The preliminary version seems to work when MC labels are disabled.
The main changes are:
- the ClusterDecoderRaw directly writes the updated format
- ClusterNativeHelper can read the updated format
> Updated format for transport of TPCNativeCluster

- DataFormats/Detectors/TPC/include/DataFormatsTPC/ClusterNative.h
- DataFormats/Detectors/TPC/include/DataFormatsTPC/ClusterNativeHelper.h
- Detectors/TPC/workflow/include/TPCWorkflow/CATrackerSpec.h
- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- GPU/GPUTracking/Base/GPUOutputControl.h
- GPU/GPUTracking/Base/GPUReconstruction.cxx
- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/Global/GPUChainTracking.h
- GPU/GPUTracking/Global/GPUTrackingInputProvider.cxx
- GPU/GPUTracking/Interface/GPUO2Interface.cxx
- GPU/GPUTracking/Interface/GPUO2Interface.h
- GPU/GPUTracking/Interface/GPUO2InterfaceConfiguration.h
This should basically be only the last commit, but it depends on #3546 and #3547.
This adds writing of the TPC clusters during GPU reconstruction to a preallocated flat buffer and shipping that without serialization and without any copy.
I figured we'll run into the same ROOT TBuffer problems as with the compressed clusters, so we should not store the data to a root file in this way but, until we have a workaround to split the entries, keep storing the clusters per tpc sector.
Thus, this adds a new data type `CLSNATIVEFLAT` for messagint the ClusterNative in a flat format.
The `o2-tpc-reco-workflow` sends in this format when the `disable-writer` option is set, and the `o2-tpcits-match-workflow` receives in this format when the `--disable-root-input` is set. Otherwise, both keep using the …
> Flat trivially-messageable output path for tpc clusters from gputracker to tpc-its-matcher

- Framework/Core/src/ChannelSpecHelpers.cxx
- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/Core/src/DeviceSpecHelpers.h
- Framework/Core/src/runDataProcessing.cxx
This enables shared memory when on the same host and makes sure that the `--shm-segment-size` option is the same and the largest specified value for every device. If no device requires a special size, the default of 2GB is used.
> DPL: enable shmem (O2-1434)

- Framework/Core/include/Framework/ASoA.h
Add check to protect against invalid read from mapping array (`mSelectedRows[mMaxSelection]`) when the iterator reaches `end` as it also does in every range-based for loop. 
@aalkin Probably I am missing something but I don't quite understand the logic of using `mSelectionRow` directly in case the selection is empty? Why don't we invalidate the view in this case (which also happens in `moveToEnd()` in the current code)?
> Fix invalid read for FilteredIndexPolicy

- Framework/Core/include/Framework/ASoA.h
- Framework/Core/test/test_ASoA.cxx
This drops the std::tuple usage which seems to be extremely
heavyweight on GCC 7.3 in terms of template recursion due
checks for PODabibility. This should:
* Speed up compilation
* Increase the number of columns one can have in a table,
without having to increase the template recursion.
> DPL Analysis: improve compile time performance of ASoA

- GPU/Common/GPUCommonMath.h
OpenMP atomics with capture are poorly supported in compilers and it seems in particular CAS is not always compiled correctly. Instead, we just use the GCC/clang builtins which map directly to the x86 atomic CPU instructions.
> Replace #pragma omp atomic with GCC/clang builtins

- GPU/GPUTracking/DataCompression/AliHLTTPCClusterStatComponent.cxx
- GPU/GPUTracking/DataCompression/GPUTPCCompressionTrackModel.cxx
- GPU/GPUTracking/Merger/GPUTPCGMMerger.cxx
- GPU/GPUTracking/Merger/GPUTPCGMPropagator.cxx
- GPU/GPUTracking/Merger/GPUTPCGMPropagator.h
- GPU/GPUTracking/Merger/GPUTPCGMTrackParam.cxx
- GPU/GPUTracking/SliceTracker/GPUTPCTrackParam.cxx
- GPU/GPUTracking/Standalone/display/GPUDisplay.cxx
- GPU/GPUTracking/Standalone/qa/GPUQA.cxx
- GPU/GPUTracking/TRDTracking/GPUTRDInterfaces.h
- GPU/GPUTracking/oldFiles/GPUTPCGMOfflineFitter.cxx
Hi @davidrohr 
this is the material correction map in the propagator. It works now. 
For the TPC fit the resolutions stays the same, the pulls look a bit different (I would say, better).
> Use of material map in the track propagator

- Detectors/FIT/FT0/simulation/include/FT0Simulation/Detector.h
- Detectors/FIT/FT0/simulation/src/Detector.cxx
- increased min step size in thick radiator and front quartz MCP window;
- added radiator (0TOP) and front quartz MCP window (0MOP) as sensitive volumes;
- when photons just appeared we check QE and stop transport of photon if not;
- stop writing Cherenkov photons in Kine tree.  
CPU time was dropped down
- for pp from 0.43 to 0.25 s / event;
- for Pb-Pb  from 29 to 17s / event.
> speed up FT0 simulation

- Framework/Core/include/Framework/TypeTraits.h
- Framework/Core/test/test_TypeTraits.cxx
- Framework/Utils/include/DPLUtils/MakeRootTreeWriterSpec.h
- Framework/Utils/include/DPLUtils/RootTreeWriter.h
- Framework/Utils/test/test_RootTreeWriter.cxx
- More flexible API for passing handlers to RootTreeWriter
- Supporting DataRef const& as optional callback parameter in the branch
callbacks.
- Introducing a custom close handler.
- Adding support for auxiliary inputs, i.e. inputs which are not connected to
a branch definition. Auxiliary inputs can be accessed in the preprocessor callback
> Update of DPL RootTreeWriter

- Detectors/GlobalTrackingWorkflow/include/GlobalTrackingWorkflow/TrackWriterTPCITSSpec.h
- Detectors/GlobalTrackingWorkflow/src/TrackWriterTPCITSSpec.cxx
- Detectors/GlobalTrackingWorkflow/tpcinterpolationworkflow/include/TPCInterpolationWorkflow/TPCResidualWriterSpec.h
- Detectors/GlobalTrackingWorkflow/tpcinterpolationworkflow/src/TPCResidualWriterSpec.cxx
Replacing duplicated boiler plate code by DPL RootTreeWriter.
> Simplifying writer specs in the GlobalTracking workflows

- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFPeakFinder.h
- GPU/GPUTracking/TPCClusterFinder/clusterFinderDefs.h
This fixes a problem introduced in #3691 
@fweig : Could you have a look, I didn't dig deeper, but the change to uint seems to segfault on large events. This revert only that change, but leaves your cleanup in, which seems to be ok.
> GPU: Revert size back to size_t in clusterizer

- Framework/Utils/include/DPLUtils/RootTreeWriter.h
The argument pack was not correctly forwarded when only one branch definition was
in use.
> Bug fix RootTreeWriter: Argument parsing of the constructor

- Generators/src/PrimaryGenerator.cxx
This commit fixes a issue that could happen in case of user-defined event generators that attempt to directly add tracks via the 
```
virtual void AddTrack(Int_t pdgid, Double_t px, Double_t py, Double_t pz,
Double_t vx, Double_t vy, Double_t vz,
Int_t parent = -1, Bool_t wanttracking = true,
Double_t e = -9e9, Double_t tof = 0.,
Double_t weight = 0., TMCProcess proc = kPPrimary);
```
method and do not specify a valid energy, that is they use the default.
For the cases where a negative energy is passed, a protection must be taken in the method to convert the negative value to a reasonable value. If the particle PDG id is known, than the mass is retrieved and the energy computed. Otherwise zero mass is assumed.
> Compute particle energy is negative value passed to AddTrack

- Framework/Core/src/ChannelSpecHelpers.cxx
- Framework/Core/src/DataProcessingDevice.cxx
In the case of shmem backend, a nullptr in the payload is actually a valid message, so we need to forward it, if requested. Analogous to 99c816d27f6960af9ccb6428bba27ffbae032e51.
> DPL: consider nullptr in payload a valid message when forwarding O2-1489

- Detectors/ITSMFT/common/reconstruction/src/ChipMappingITS.cxx
solves the problem of different ITS reconstruction (clusterization) results seen in https://github.com/AliceO2Group/AliceO2/pull/3693#issuecomment-637876988
> ITS fix: make sure chips decoded in inc. SW ID order

- Framework/Core/src/DataProcessingDevice.cxx
Messages with empty (nullptr) payload are nevertheless valid when running on
shmem transport and soon also for FairMQ.
> DPL: do not skip messages with nullptr payload

- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/ChipMappingITS.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/ChipMappingMFT.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/GBTLink.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/RUDecodeData.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/RUInfo.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/RawPixelDecoder.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/RawPixelReader.h
- Detectors/ITSMFT/common/reconstruction/src/ChipMappingITS.cxx
- Detectors/ITSMFT/common/reconstruction/src/ChipMappingMFT.cxx
- Detectors/ITSMFT/common/reconstruction/src/GBTLink.cxx
- Detectors/ITSMFT/common/reconstruction/src/RUInfo.cxx
- Detectors/ITSMFT/common/reconstruction/src/RawPixelDecoder.cxx
- Detectors/ITSMFT/common/simulation/src/MC2RawEncoder.cxx
Before the Alpide cableHW ID was mapped to cableSW ID which was corresponding both to the
1) position of the cable in the ActiveLanes mask shipped in the GBTHeader
2) the order in which cached cables data was decoded.
To make decoding more flexible and guarantee that the cables are decoded in such order
that leads to decoded chips ordered in their SW ID, an extra mapping cableHW -> cableHWPos
is introduced for (1), while the cableSW is redefined to be used for (2) only.
@bovulpes you may need to change the ChipMappingMFT, I will add some details in https://alice.its.cern.ch/jira/browse/O2-1475
> Separate cable HW_ID position and ordering mappings

- Detectors/Raw/src/RawFileWriter.cxx
- Detectors/TPC/simulation/run/convertDigitsToRawZS.cxx
@davidrohr: with this PR the ``o2-tpc-digits-to-rawzs --configKeyValues "HBFUtils.orbitFirst=1"`` will discard all data of (dummy) HBFs preceding the desired 1st TF start.
This works for all converters, since the modification is on the RawWriter level. 
But for the TPC I had to remove the biasing of the digits time by the ``HBFUtils::getFirstIR()`` since in this way it would always add ``HBFUtils.orbitFirst`` empty orbits in front of the 1st digitized one.
If you want to be able to shift the TF to the future, the shift should be provided by an additional option, independent from the ``HBFUtils::getFirstIR()``.
> RawWriter will discard data with IR<HBFUtils.getFirstIR()

- Steer/DigitizerWorkflow/src/TPCDigitRootWriterSpec.cxx
The implementation of digitization of triggered TPC data makes the corresponding
writer special, because the entries are split based on a trigger info object.
This is handled using specific branch callbacks for writing portions of digits and
labels.
> Using the RootTreeWriter as writer for TPC digits in the digitization workflow

- Framework/Core/include/Framework/ExternalFairMQDeviceProxy.h
- Framework/Core/src/ExternalFairMQDeviceProxy.cxx
This is a long pending task. Removing merging of split parts which had been
introduced in the first version of the raw proxy when multiple message per
route have not been supported by DPL.
Messages are now simply forwarded on the DPL route, independent of this it
needs to be checked what is/whether something is necessary to forward shm
messages without copy.
> DPL raw input proxy: Skipping merging of split parts in the external proxy

- DataFormats/Detectors/TPC/include/DataFormatsTPC/CompressedClusters.h
- DataFormats/Detectors/TPC/src/CompressedClusters.cxx
- Detectors/TPC/reconstruction/src/GPUCATracking.cxx
- Detectors/TPC/workflow/include/TPCWorkflow/CATrackerSpec.h
- Detectors/TPC/workflow/include/TPCWorkflow/RecoWorkflow.h
- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- Detectors/TPC/workflow/src/RecoWorkflow.cxx
- GPU/GPUTracking/Base/GPUDataTypes.cxx
- GPU/GPUTracking/Base/GPUDataTypes.h
- GPU/GPUTracking/Base/GPUReconstruction.h
- GPU/GPUTracking/Base/GPUReconstructionCPU.cxx
- GPU/GPUTracking/Base/GPUReconstructionCPU.h
- GPU/GPUTracking/DataCompression/GPUTPCClusterStatistics.cxx
- GPU/GPUTracking/DataCompression/GPUTPCCompressionKernels.cxx
- GPU/GPUTracking/DataCompression/TPCClusterDecompressor.cxx
- GPU/GPUTracking/DataCompression/TPCClusterDecompressor.h
- GPU/GPUTracking/Global/GPUChain.h
- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/Global/GPUChainTracking.h
- GPU/GPUTracking/Global/GPUTrackingInputProvider.cxx
- GPU/GPUTracking/Interface/GPUO2InterfaceConfiguration.h
- GPU/GPUTracking/Merger/GPUTPCGMMerger.cxx
- GPU/GPUTracking/Standalone/standalone.cxx
@shahor02 : This adds the reading of tpc compressed clusters in the tpc workflow.
It is not properly rebased, basically it is the last 2 commits and depends on #3685.
As soon as #3685 is merged, I'll rebase this.
Also, I found a bug in the track model compression, which currently doesn't decompress correctly.
I'll try to fix that in the meantime and push on top of this.
But for just testing the passing of the ctf to the tpc-workflow, cherry picking the last two commits here should do.
I used the command line
```
o2-ctf-reader-workflow  --ctf-input o2_ctf_0000000000.root  | o2-its-reco-workflow --trackerCA --clusters-from-upstream --disable-mc | o2-tpc-reco-workflow --input-type compressed-clusters-ctf --output-type tracks,clusters --disable-mc
```
I added a new input-type …
> Add reading of tpc compressed clusters in TPC workflow

- Detectors/Raw/src/RawFileReaderWorkflow.cxx
This makes sure the --pipeline option can be used to multiply
downstream devices.
> raw-file-reader: keep time-pipelining into account when serving data O2-1483

- DataFormats/simulation/include/SimulationDataFormat/Stack.h
- DataFormats/simulation/include/SimulationDataFormat/TrackReference.h
- DataFormats/simulation/src/Stack.cxx
- missing initialisation of mTrackNumber in one of the constructors
- corrected "alive" and "stopped" conditions
- particles producing a TrackReference are kept on the stack
(avoids also "Invalid trackref ... needs to be removed" messages.)
> bug fixes related to TrackReferences

- Detectors/Raw/test/testHBFUtils.cxx
- Steer/DigitizerWorkflow/src/SimReaderSpec.cxx
- Steer/include/Steer/InteractionSampler.h
- Steer/src/InteractionSampler.cxx
o2-sim-digitizer-workflow --firstOrbit <orb> --firstBC <bc>
will enforce sampling starting from given orbit/bc (if bc exceeds LHCMaxBunches,
the firstOrbit will be incremented by bc/LHCMaxBunches and bc%LHCMaxBunches will
be used as a 1st bc.
Default behaviour is unchanged: firstOrbit = 1, firstBC = 0.
@davidrohr with ``o2-sim-digitizer-workflow --firstOrbit 0`` you can avoid a gap between default ``HBFUtil.getFirstIR()`` and 1st sampled orbit, in case the ZDC is not in the game. Even with ZDC in the  ``o2-sim-digitizer-workflow --firstOrbit 0 --firstBC 4`` should be absolutely safe, it will just skip 1st 4 BCs.
> Options to set 1st orbit/bc for sampling in digitization

- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- GPU/GPUTracking/Base/GPUProcessor.h
- GPU/GPUTracking/CMakeLists.txt
Weird fun fact:
Using `basePtr = (T*)GPUCA_BUFFER_ALIGNMENT;` instead of `reinterpret_cast<size_t&>(basePtr) = GPUCA_BUFFER_ALIGNMENT;` doesn't work (if you use -O2 or -O3, -O0 works)!
I first thought it is a miscompilation and took me a while to understand that the compiler behaviour is totally legit. I'll buy a beer for everyone who can explain it to me properly :)
> Fix memory corruption in TPC tracker when DPL provides unaligned input buffer

- CODEOWNERS
- DataFormats/Detectors/Upgrades/CMakeLists.txt
- Detectors/CMakeLists.txt
- Detectors/Upgrades/CMakeLists.txt
- cmake/O2DefineOptions.cmake
@ktf @davidrohr @mconcas @mpuccio @marcovanleeuwen
As discussed some time ago, introduction of `Upgrades` directory to contain evolving detectors for future upgrades (s.a. ITS3, FoCal, post-LS4, ...). Please comment if this looks fine to you or if you'd prefer to handle this differently
> Add structure for upgrades

- Detectors/GlobalTracking/include/GlobalTracking/MatchTOF.h
- Detectors/GlobalTracking/src/MatchTOF.cxx
- Detectors/GlobalTrackingWorkflow/tofworkflow/src/RecoWorkflowSpec.cxx
The mInitDone flag (legacy of macro-steered mode), set during 1st TF processeing, was preventing setting the input of following TFs. Therefore, after the 1st TF the matching was running over potentially invalid old input from 1st TF.
Introduced separate flag for DPL data attachment, in the DPL mode process directly with overloaded run method w/o wrong check for init.
> Fix: check for initDone was blocking next TF input

- Detectors/ITSMFT/ITS/workflow/include/ITSWorkflow/ClusterWriterSpec.h
- Detectors/ITSMFT/ITS/workflow/include/ITSWorkflow/TrackWriterSpec.h
- Detectors/ITSMFT/ITS/workflow/src/ClusterWriterSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/TrackWriterSpec.cxx
- Detectors/ITSMFT/MFT/workflow/include/MFTWorkflow/ClusterWriterSpec.h
- Detectors/ITSMFT/MFT/workflow/include/MFTWorkflow/TrackWriterSpec.h
- Detectors/ITSMFT/MFT/workflow/src/ClusterWriterSpec.cxx
- Detectors/ITSMFT/MFT/workflow/src/TrackWriterSpec.cxx
- Steer/DigitizerWorkflow/src/ITSMFTDigitWriterSpec.cxx
Duplicate boiler plate code is replaced with standard RootTreeWriter.
> Using DPL RootTreeWriter for ITS and MFT workflows

- Analysis/DataModel/include/Analysis/EventSelection.h
- Analysis/Tasks/centralityQa.cxx
- Analysis/Tasks/centralityTable.cxx
- Analysis/Tasks/eventSelection.cxx
- Analysis/Tasks/eventSelectionQa.cxx
- Analysis/Tasks/multiplicityQa.cxx
- Analysis/Tasks/multiplicityTable.cxx
Changes:
* Added new aliases corresponding to muon and UPC classes
* Added AD timing decisions in the event selection table
* Added AD timing QA in the event selection QA
* Isolated configurable cut parameters in EvSelParameters structure
* Introduced alias names similar to Run2 (kINT7 etc)
* replaced alias[0] to alias[kINT7] for minimum bias selection
* Suppressed debug messages
> Added new aliases, AD timing decisions

- Utilities/rANS/CMakeLists.txt
- Utilities/rANS/include/rANS/Coder.h
- Utilities/rANS/include/rANS/Decoder.h
- Utilities/rANS/include/rANS/DecoderSymbol.h
- Utilities/rANS/include/rANS/Encoder.h
- Utilities/rANS/include/rANS/EncoderSymbol.h
- Utilities/rANS/include/rANS/ReverseSymbolLookupTable.h
- Utilities/rANS/include/rANS/SymbolStatistics.h
- Utilities/rANS/include/rANS/SymbolTable.h
- Utilities/rANS/include/rANS/helper.h
- Utilities/rANS/src/SymbolStatistics.cxx
- Utilities/rANS/test/test_ransEncodeDecode.cxx
Improvements in robustness of the codebase and advanced diagnostics 
* add logging on info, warning, error, debug, and tracing level.
* timers for inclusive time of key components (building of statistics, dictionaries, encoding/decoding)
* diagnostics if build in cmake debug mode (i.e. assertions enabled): 
* source message and symbol statistics (entropy, number of symbols, size of source alphabet)
* dictionary sizes
* encoder/decoder compression
* assertions in debug mode to ease debugging of underflows/ overflows
* improved unit-testing
* hardening of public API (checks for empty messages, unallocated buffers etc) (O2-1488)
* small bugfixes
> (O2-1203) [rANS] Codebase Hardening + Diagnostics

- Detectors/FIT/FT0/simulation/src/digi2raw.cxx
- Detectors/GlobalTrackingWorkflow/tofworkflow/src/tof-reco-workflow.cxx
- Detectors/ITSMFT/common/simulation/include/ITSMFTSimulation/MC2RawEncoder.h
- Detectors/ITSMFT/common/simulation/src/MC2RawEncoder.cxx
- Detectors/MUON/MCH/Raw/Encoder/Digit/digit2raw.cxx
- Detectors/MUON/MID/Raw/include/MIDRaw/Encoder.h
- Detectors/MUON/MID/Raw/src/Encoder.cxx
- Detectors/MUON/MID/Workflow/src/RawWriterSpec.cxx
- Detectors/Raw/include/DetectorsRaw/RawFileWriter.h
- Detectors/TOF/reconstruction/include/TOFReconstruction/Encoder.h
- Detectors/TOF/reconstruction/src/Encoder.cxx
- Detectors/TOF/simulation/CMakeLists.txt
- Detectors/TOF/simulation/src/digi2raw.cxx
- Detectors/TOF/workflow/include/TOFWorkflow/TOFRawWriterSpec.h
- Detectors/TOF/workflow/src/TOFRawWriterSpec.cxx
- Detectors/TPC/simulation/run/convertDigitsToRawZS.cxx
- Detectors/TPC/workflow/src/ZSSpec.cxx
All detectors data must start with SOX (X = continuous or triggered) trigger bits set in the RDH.
This PR ensures that this info from the GRP (updated during digitization) is transferred from the converter to the RawFileWriter, which takes care of setting the trigger bits.
Also, a other modifications are introduced to uniformize (more or less) the conventions the different converters.
add o2-tof-digi2raw executable aliased to the tof workflow with output-type=raw and supporting the same options as other converters. Also, the config file is brought to same conventions as for other detectors. The output names a modified to cruxxxtof.raw
Also, change default output filename to <det>.raw. The config file writing is delegated to RawFileWriter, will be stored in the same format as for other …
> Make sure digi->raw converters set SOX trigger bits in the very 1st RDH

- Detectors/ITSMFT/MFT/simulation/CMakeLists.txt
- Detectors/ITSMFT/MFT/simulation/src/digi2raw.cxx
- Detectors/ITSMFT/MFT/workflow/CMakeLists.txt
- Detectors/ITSMFT/MFT/workflow/include/MFTWorkflow/DigitWorkflow.h
- Detectors/ITSMFT/MFT/workflow/include/MFTWorkflow/DigitWriterSpec.h
- Detectors/ITSMFT/MFT/workflow/src/DigitWorkflow.cxx
- Detectors/ITSMFT/MFT/workflow/src/DigitWriterSpec.cxx
- Detectors/ITSMFT/MFT/workflow/src/mft-digit-workflow.cxx
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/ChipMappingMFT.h
- Detectors/ITSMFT/common/reconstruction/src/ChipMappingMFT.cxx
- Detectors/ITSMFT/common/workflow/src/STFDecoderSpec.cxx
I add also a device to read the piped decoded digits and write them into a file in ROOT format. This is the full chain to check the encoding / decoding:
o2-sim -j 4 -m MFT -e TGeant3 -n 10 -g boxgen --configKeyValues 'BoxGun.pdg=13; BoxGun.eta[0]=-3.8; BoxGun.eta[1]=-2.1; BoxGun.prange[0]=5.0; BoxGun.prange[1]=10.; BoxGun.number=10'
o2-sim-digitizer-workflow -b 
o2-mft-digi2raw -b
o2-raw-file-reader-workflow -b --nocheck-missing-stop --max-tf 100 --input-conf MFTraw.cfg | o2-itsmft-stf-decoder-workflow -b --mft --digits --dict-file ITSdictionary.bin | o2-mft-digit-workflow -b
and at the end compare the digits from the two files:
mftdigits.root
and
mftdigitsdecode.root
> MFT: introduce the decoder for the new data format.

- GPU/GPUTracking/TRDTracking/GPUTRDDef.h
- GPU/GPUTracking/TRDTracking/GPUTRDInterfaces.h
- GPU/GPUTracking/TRDTracking/GPUTRDTrack.cxx
- GPU/GPUTracking/TRDTracking/GPUTRDTracker.cxx
- GPU/GPUTracking/TRDTracking/GPUTRDTracker.h
- GPU/GPUTracking/TRDTracking/macros/checkDbgOutput.C
- If the tracklets are out of the search road **either** in Y **or** Z they are ignored
- Some additions to the debugging macro
> Tracklet error parameterization is loaded based on B-field, not per compiler flag anymore

- DataFormats/common/include/CommonDataFormat/InteractionRecord.h
- DataFormats/common/src/InteractionRecord.cxx
- DataFormats/simulation/src/DigitizationContext.cxx
- Detectors/FIT/FDD/simulation/src/Digitizer.cxx
- Detectors/ITSMFT/common/simulation/src/Digitizer.cxx
- Detectors/TRD/workflow/src/TRDDigitizerSpec.cxx
- Detectors/ZDC/simulation/src/Digitizer.cxx
- Steer/DigitizerWorkflow/src/CPVDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/EMCALDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/FDDDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/HMPIDDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/ITSMFTDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/MCHDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/PHOSDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/TOFDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/TPCDigitizerSpec.cxx
- Steer/src/InteractionSampler.cxx
- Steer/test/testInteractionSampler.cxx
To avoid round-off  errors the InteractionTimeRecord produced by the InteractionSampler in the digitization will store the time in ns wrt the BC/orbit it indicates (i.e. it is the time of the interaction within the bunch) rather than the time from BC=0/orbit=0 stored before. The latter can be obtained as ``InteractionTimeRecord::getTimeNS()``.
The detectors digitization code was updated correspondingly, so the change is transparent for them.
> InteractionTimeRecord will store time in BC instead of abs. time

- Detectors/GlobalTrackingWorkflow/src/TPCITSMatchingSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/ClusterWriterSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/ClustererSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/CookedTrackerSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/DigitReaderSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/TrackerSpec.cxx
- Detectors/ITSMFT/MFT/workflow/src/ClusterReaderSpec.cxx
- Detectors/ITSMFT/MFT/workflow/src/ClusterWriterSpec.cxx
- Detectors/ITSMFT/MFT/workflow/src/ClustererSpec.cxx
- Detectors/ITSMFT/MFT/workflow/src/DigitReaderSpec.cxx
- Detectors/ITSMFT/MFT/workflow/src/TrackerSpec.cxx
- Detectors/ITSMFT/common/workflow/src/ClusterReaderSpec.cxx
- Detectors/ITSMFT/common/workflow/src/EntropyDecoderSpec.cxx
- Detectors/ITSMFT/common/workflow/src/EntropyEncoderSpec.cxx
- Detectors/ITSMFT/common/workflow/src/STFDecoderSpec.cxx
@bovulpes some DataDescription names were not changed all devices using then in the https://github.com/AliceO2Group/AliceO2/pull/3688.
I've fixed both the ITS and MFT part but I am not familiar with MFT workflows to test, please check.
> Fix inconsistencies in ITS/MFT message DataDescription names

- DataFormats/simulation/include/SimulationDataFormat/Stack.h
- DataFormats/simulation/src/Stack.cxx
- For Geant3 the current particle has to be updated when a new particle is taken from the stack
- For Geant4 the current particle has to be updated when a new particle is put on the stack (in SetCurrentParticle which is always called after PushTrack)
> bug correction for current particle during stepping 

- Detectors/TRD/workflow/include/TRDWorkflow/TRDTrapSimulatorSpec.h
- Detectors/TRD/workflow/src/TRDTrapSimulatorSpec.cxx
- Detectors/TRD/workflow/test/run_trivial_trapsimulator.sh
- Fix the trigger records on receiving them in the trap simulator.
- boolean option --trd-fixtrigrecord  added to enable the fix if needed.
- if you request fix and it appears to not be needed, you are warned and nothing is done.
- fix double deletion error
- fix crash of trackletwriter
- removed object creation in message, and reverted to snapshotting at the end. Clearer to read as well.
> Fix trigger records in TRD trap simulator

- Detectors/TPC/base/include/TPCBase/ParameterElectronics.h
- Detectors/TPC/base/test/testTPCParameters.cxx
@davidrohr,  @wiechula I've changed the timebin definition to account for the real BC spacing.
This should solve the problem of de-synchronization between the ITS and TPC for TF>1.
I did a fast test with boxgen, comparing 1 "long TF" reconstruction with digits and the same data converted to 4 TFs of  64 HBFs, matching in TF>1 ( x>5700 on the attached plot showing the matched track times in \mus, red from digits, blue from raw) improved (before ~half of matches were lost) but is still not good, apparently I have problems also in the matching code.
In any case, the time now should be correct and the eventual change in time -> timebin mapping in digtization to avoid round-off errors should not affect the readability of digits So, David, I think you can generate a sample w/o much risk of its …
> Define default TPC time bin BCs

- Generators/src/GeneratorFromFile.cxx
A particle is primary, if its UniqueID() == 0, and trackable, if TestBit(BIT(14)) == 1.
In a future update we can also put the untrackable primaries (parents) on the stacks. For this
one needs to calculate the daughter and mother IDs from the information in the Kinematics.tree
> Fix of test for trackable primaries

- Detectors/GlobalTracking/include/GlobalTracking/MatchTPCITS.h
- Detectors/GlobalTracking/src/MatchTPCITS.cxx
Since the ITS data may contain gaps even in continuous mode and the TPC time-bin
is mapped to ideal ITS ROFrame, we need an extra mapping ideal frames to closest
real frame.
At the moment set the 1st orbit of TF from 1 IR of the supplied ITS data, which assumes all ITS ROFs are complete and w/o gaps, otherwise it will fail. Robust solution is to set the 1st IR of TF externally.
> Fixes for ITSTPC matching at TF>0 or ITS data with gaps

- Detectors/EMCAL/simulation/src/Detector.cxx
- Detectors/EMCAL/simulation/src/SpaceFrame.cxx
patch for previous commit  c7614eee17594a8ebd7558ef3effd561b158b8ad
- some volumes had been erroneously shifted up in y
- support structure (calFrameMO) added to barrel
> wrong y-shift in EMCAL corrected & support structure added to barrel

- Detectors/ITSMFT/ITS/tracking/include/ITStracking/Definitions.h
- Detectors/MUON/MID/Base/include/MIDBase/ChamberEfficiency.h
- Detectors/MUON/MID/Raw/include/MIDRaw/LocalBoardRO.h
- Detectors/TPC/reconstruction/include/TPCReconstruction/HalfSAMPAData.h
- Framework/Core/include/Framework/ServiceRegistry.h
- Framework/Core/src/DataSamplingConditionFactory.cxx
It seems that GCC 10 removed some implicit includes, see e.g. https://gcc.gnu.org/gcc-10/porting_to.html.
> add missing includes needed for gcc 10

- Detectors/ITSMFT/MFT/tracking/include/MFTTracking/IOUtils.h
- Detectors/ITSMFT/MFT/tracking/include/MFTTracking/Tracker.h
- Detectors/ITSMFT/MFT/tracking/src/IOUtils.cxx
- Detectors/ITSMFT/MFT/tracking/src/Tracker.cxx
- Detectors/ITSMFT/MFT/workflow/include/MFTWorkflow/RecoWorkflow.h
- Detectors/ITSMFT/MFT/workflow/include/MFTWorkflow/TrackerSpec.h
- Detectors/ITSMFT/MFT/workflow/src/ClustererSpec.cxx
- Detectors/ITSMFT/MFT/workflow/src/RecoWorkflow.cxx
- Detectors/ITSMFT/MFT/workflow/src/TrackWriterSpec.cxx
- Detectors/ITSMFT/MFT/workflow/src/TrackerSpec.cxx
- Detectors/ITSMFT/MFT/workflow/src/mft-digit-workflow.cxx
- Detectors/ITSMFT/MFT/workflow/src/mft-reco-workflow.cxx
MFT was still using the full clusters for the track finding, with this PR the compressed clusters are used instead. The default for the MFT clusterer is now to produce only the compressed clusters. The dictionary for the cluster patterns is the one produced separately from an ITS simulation.
> MFT: do the standalone tracking using the compressed clusters

- Detectors/FIT/FDD/workflow/CMakeLists.txt
- Detectors/FIT/FDD/workflow/include/FDDWorkflow/RecPointWriterSpec.h
- Detectors/FIT/FDD/workflow/src/RecPointWriterSpec.cxx
- Detectors/FIT/workflow/CMakeLists.txt
- Detectors/FIT/workflow/include/FITWorkflow/FT0RecPointWriterSpec.h
- Detectors/FIT/workflow/src/FT0RecPointWriterSpec.cxx
- Detectors/GlobalTrackingWorkflow/tofworkflow/include/TOFWorkflow/TOFCalibWriterSpec.h
- Detectors/GlobalTrackingWorkflow/tofworkflow/include/TOFWorkflow/TOFMatchedWriterSpec.h
- Detectors/GlobalTrackingWorkflow/tofworkflow/src/TOFCalibWriterSpec.cxx
- Detectors/GlobalTrackingWorkflow/tofworkflow/src/TOFMatchedWriterSpec.cxx
- Detectors/TOF/workflow/CMakeLists.txt
- Detectors/TOF/workflow/include/TOFWorkflow/TOFClusterWriterSpec.h
- Detectors/TOF/workflow/src/TOFClusterWriterSpec.cxx
- Detectors/TOF/workflow/src/TOFDigitWriterSpec.cxx
Using DPL utility RootTreeWriter and the MakeRootTreeWriterSpec generator and removing duplicated boiler-plate code in the TOF and FIT workflows
Have been checking the following workflow tests:
```
o2-its-reco-workflow --disable-root-output | o2-tpc-reco-workflow --tpc-digit-reader '--infile tpcdigits.root' --ca-clusterer --input-type digits --output-type clusters,tracks | o2-tpcits-match-workflow --disable-root-input | o2-tof-reco-workflow --disable-root-input --disable-root-output | o2-tpc-scdcalib-interpolation-workflow --disable-root-input
```
```
o2-fit-reco-workflow
```
```
o2-fdd-reco-workflow
```
here there is a crash independent of this PR
```
===========================================================
#6  std::__cxx11::basic_string<char, std::char_traits<char>, …
```
> Further cleanup of workflow writers for TOF and FIT

- Analysis/Tasks/correlationsCollection.cxx
- Analysis/Tasks/correlationsMixed.cxx
- Analysis/Tutorials/src/associatedExample.cxx
- Analysis/Tutorials/src/filters.cxx
- Framework/Core/include/Framework/AODReaderHelpers.h
- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/AnalysisDataModel.h
- Framework/Core/include/Framework/AnalysisTask.h
- Framework/Core/include/Framework/BasicOps.h
- Framework/Core/include/Framework/DataAllocator.h
- Framework/Core/include/Framework/Expressions.h
- Framework/Core/src/AODReaderHelpers.cxx
- Framework/Core/src/DataAllocator.cxx
- Framework/Core/src/ExpressionHelpers.h
- Framework/Core/src/Expressions.cxx
- Framework/Core/src/WorkflowHelpers.cxx
- Framework/Core/test/benchmark_ASoA.cxx
- Framework/Core/test/benchmark_ASoAHelpers.cxx
- Framework/Core/test/test_ASoA.cxx
- Framework/Core/test/test_AnalysisDataModel.cxx
- Framework/Core/test/test_Expressions.cxx
- Framework/Core/test/test_Kernels.cxx
@ktf @jgrosseo thank you for patience.
This introduces an "expression column" defined by the same sort of expression used in filters. Such columns are added to a pre-existing soa::Table with a `DECLARE_SOA_EXTENDED_TABLE` macro, specifying the base table and the list of columns, declared with `DECLARE_SOA_EXPRESSION_COLUMN`. Extended tables have special origin 'DYN' to distinguish them from normal AOD tables and allow framework to spawn a device that would run the expressions to create new columns in memory and send the table further. 
I've added an example column "Pt2" (pt-squared) and extended the `Tracks` table with it, renaming the original table to `StoredTracks`. The change should be completely transparent for user tasks, requesting `Tracks` (see example in filters.cxx) and this …
> DPL Analysis: Expression-based column for soa::Table

- GPU/GPUTracking/Base/GPUReconstruction.cxx
- GPU/GPUTracking/Base/GPUReconstruction.h
- GPU/GPUTracking/Base/GPUReconstructionCPU.cxx
- GPU/GPUTracking/Base/GPUSettings.cxx
- GPU/GPUTracking/Base/GPUSettings.h
- GPU/GPUTracking/Global/GPUChain.h
- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/Global/GPUChainTracking.h
- GPU/GPUTracking/Standalone/qconfigoptions.h
- GPU/GPUTracking/Standalone/standalone.cxx
- GPU/GPUTracking/Standalone/utils/bitfield.h
This is just some framework code to support overlapping input / output of consecutive time frames, actual implementation of the pipeline will follow.
+ some cleanup off fstream headers.
> GPU: Add double-pipeline mode to hide latencies of input / output

- Detectors/MUON/MCH/Raw/Decoder/src/UserLogicElinkDecoder.h
- Detectors/MUON/MCH/Workflow/src/DataDecoderSpec.cxx
The PR introduces the following fixes:
* corrects the handling of incomplete data words, stopping the processing as soon as the end of the data packet being decoded is reached. An error message is printed if no packet end if detected.
* corrects the decoding of SAMPA HeartBeat packets, which were previously treated as errors.
* improves the use of the RDHAny structure in the HBFrame decoder
> MCH: UserLogic decoder bugfixes

- Detectors/MUON/MCH/Simulation/src/Station345Geometry.cxx
- Detectors/MUON/MCH/Simulation/test/testGeometry.cxx
The dipole volume is rotated 180 degrees when placed in its mother volume, a fact which was not correctly taken into account when placing the MCH Station 3 within it. As a result that station (and only this one) ended up wrongly flipped left-right in the final geometry. 
This PR fixes that (and add a corresponding unit test)
> [MCH] Add extra rotation to Station3 when put into the dipole

- DataFormats/simulation/src/Stack.cxx
- Steer/include/Steer/O2MCApplication.h
Avoid overwriting of the status code of primary particles from the event generator.
In the previous version of the code the status code is used to store the trackID of primary particles. This is not needed since Geant4 passes the trackID in SetCurrentTrack(...) and for Geant3 the trackID is equal to the size of the stack at the moment when the particle is read back from the stack.
Currently the status code is not stored in MCTrack. However, we should keep this option open for the future.
> Do not ovewrite status code of primaries.

- Detectors/MUON/MCH/Base/include/MCHBase/Digit.h
- Detectors/MUON/MCH/Base/src/Digit.cxx
- Detectors/MUON/MCH/Workflow/src/DataDecoderSpec.cxx
- Detectors/MUON/MCH/Workflow/src/file-to-digits-workflow.cxx
The information on the number of samples in the detected signal is needed in order to perform digits merging in continuous data taking mode, and might be exploited to distinguish real signals from noise hits.
> MCH: added number-of-samples parameter to the Digit structure

- Framework/Core/src/runDataProcessing.cxx
Short option `-c` is already used by option `--completion-policy`
> Removing duplicated short option, probably a simple c&p typo

- Common/SimConfig/include/SimConfig/SimConfig.h
- Common/SimConfig/src/SimConfig.cxx
- Detectors/gconfig/CMakeLists.txt
- Detectors/gconfig/commonConfig.C
- Detectors/gconfig/g3Config.C
- Detectors/gconfig/g4Config.C
- Detectors/gconfig/src/G3Config.cxx
- Detectors/gconfig/src/G4Config.cxx
- Generators/CMakeLists.txt
- Generators/include/Generators/DecayerPythia8.h
- Generators/include/Generators/DecayerPythia8Param.h
- Generators/share/pythia8/decays/base.cfg
- Generators/share/pythia8/decays/bjpsidimuon.cfg
- Generators/src/DecayerPythia8.cxx
- Generators/src/DecayerPythia8Param.cxx
- Generators/src/GeneratorsLinkDef.h
- macro/o2sim.C
This PR implements a dedicated `o2` external decayer for G3 and G4.
The current implementation makes use of Pythia8 to deal with particle decays and is defined in the `DecayerPythia8` class.
The settings of the decayer can be modified by passing via configurable parameters the filename containing the settings
```
--configKeyValues 'DecayerPythia8.config=path_to_config_file'
```
The default points to 
```
${O2_ROOT}/share/Generators/pythia8/decays/base.cfg
```
Multiple files can be used, to allow the user to add custom settings on top of the defaults ones
```
--configKeyValues 'DecayerPythia8.config=path_to_default_file path_to_user_file'
```
An example of user custom setting is given in
```
${O2_ROOT}/share/Generators/pythia8/decays/bjpsidimuon.cfg
```
> Rdev external decayer

- Detectors/TRD/workflow/src/TRDTrapSimulatorSpec.cxx
The unserialized input object is access by span to avoid copy in the input
data access. Currently, the objects still need to be copied because they
are changed during processing. The code can be adapted to e.g. use a sorted
index instead of sorting the digit array. For the trigger record its probably
negligible because its small. Anyhow the functionality to fix the input trigger
record is something temporary and the whole copy can be avoided once this is
fixed upstream.
> Extracting TRD digits and trigger record by span

- Common/MathUtils/include/MathUtils/Utils.h
- DataFormats/Reconstruction/CMakeLists.txt
- DataFormats/Reconstruction/include/ReconstructionDataFormats/DCA.h
- DataFormats/Reconstruction/include/ReconstructionDataFormats/Track.h
- DataFormats/Reconstruction/include/ReconstructionDataFormats/Vertex.h
- DataFormats/Reconstruction/src/DCA.cxx
- DataFormats/Reconstruction/src/ReconstructionDataFormatsLinkDef.h
- DataFormats/Reconstruction/src/Track.cxx
- Detectors/Base/include/DetectorsBase/Propagator.h
- Detectors/Base/src/Propagator.cxx
- Detectors/GlobalTracking/include/GlobalTracking/MatchTPCITS.h
- Detectors/GlobalTracking/src/MatchTOF.cxx
- Detectors/GlobalTracking/src/MatchTPCITS.cxx
- Detectors/TPC/calibration/SpacePoints/include/SpacePoints/TrackInterpolation.h
- Detectors/TPC/calibration/SpacePoints/src/TrackInterpolation.cxx
@ginnocen in the end I've added these methods in 2 versions:
in the TrackPar / TrackParCov classes:
````
bool TrackPar::propagateParamToDCA(const Point3D<float>& vtx, float b, std::array<float, 2>* dca=nullptr, float maxD=999);
bool TrackParCov::propagateToDCA(const o2::dataformats::VertexBase& vtx, float b, o2::dataformats::DCA* dca=nullptr, float maxD=999)
````
you can use them (almost) exactly like in the AliExternalTrackParam::PropagateToDCA, the method for TrackPar allows to avoid track cov.matrix propagation propagation (i.e. if you just need to know the dca of the track w/o errors rather than to propagate it to vertex, use 
````
o2::dataformats::VertexBase vtx; // ...
o2::track::TrackParCov tr;
//....
o2::track::TrackPar tp(track);
array<float,2> dca; …
```
> set of methods for calculation of DCA to vertex 

- Detectors/GlobalTrackingWorkflow/src/TPCITSMatchingSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/ClusterWriterSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/ClustererSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/CookedTrackerSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/DigitReaderSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/TrackerSpec.cxx
- Detectors/ITSMFT/MFT/workflow/src/ClusterReaderSpec.cxx
- Detectors/ITSMFT/MFT/workflow/src/ClusterWriterSpec.cxx
- Detectors/ITSMFT/MFT/workflow/src/ClustererSpec.cxx
- Detectors/ITSMFT/MFT/workflow/src/DigitReaderSpec.cxx
- Detectors/ITSMFT/MFT/workflow/src/DigitWriterSpec.cxx
- Detectors/ITSMFT/MFT/workflow/src/TrackWriterSpec.cxx
- Detectors/ITSMFT/MFT/workflow/src/TrackerSpec.cxx
- Detectors/ITSMFT/common/workflow/CMakeLists.txt
- Detectors/ITSMFT/common/workflow/include/ITSMFTWorkflow/DigitWriterSpec.h
- Detectors/ITSMFT/common/workflow/src/ClusterReaderSpec.cxx
- Detectors/ITSMFT/common/workflow/src/DigitWriterSpec.cxx
- Detectors/ITSMFT/common/workflow/src/EntropyDecoderSpec.cxx
- Detectors/ITSMFT/common/workflow/src/STFDecoderSpec.cxx
- Detectors/ITSMFT/common/workflow/src/digit-writer-workflow.cxx
- Steer/DigitizerWorkflow/CMakeLists.txt
- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
DigitsWriter is extracted to separated workflow to allow writing root digits avoiding whole ITS of MFT reconstruction chain. 
The raw data can be converted to digits by
````
o2-raw-file-reader-workflow --input-conf ITSraw.cfg  | o2-itsmft-stf-decoder-workflow --digits --no-clusters | o2-itsmft-digit-writer-workflow --disable-mc --shm-segment-size 4000000000
````
The same can be used for the MFT as 
````
o2-raw-file-reader-workflow --input-conf MFTraw.cfg  | o2-itsmft-stf-decoder-workflow --digits --no-clusters --mft | o2-itsmft-digit-writer-workflow --disable-mc --mft --shm-segment-size 4000000000
````
Also fixed some non-uniformities between the DataDescriptions in ITS and MFT worflow, now all is in capital.
@bovulpes I saw that you've added separate writer for the MFT digits, in …
> Move ITS/MFT digitwriter to ITSMFT/common/workflow and make it workflow

- Detectors/TPC/workflow/src/tpc-reco-workflow.cxx
- Steer/DigitizerWorkflow/CMakeLists.txt
- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
Workflows can be combined on the command line by using pipe. Removing
the early implementation of combining the two workflows.
Example usage:
```
o2-sim-digitizer-workflow --onlyDet TPC | o2-tpc-reco-workflow --input-type digitizer --tpc-lanes 4
```
> Decoupling TPC digitizer workflow from reco workflow

- DataFormats/Detectors/Common/include/DetectorsCommonDataFormats/EncodedBlocks.h
- Utilities/rANS/include/rANS/Coder.h
- Utilities/rANS/include/rANS/Decoder.h
- Utilities/rANS/include/rANS/Encoder.h
- Utilities/rANS/include/rANS/SymbolTable.h
- Utilities/rANS/test/test_ransEncodeDecode.cxx
Refactors the rANS Coder class used by encoder decoder:
* Coder is now stateful i.e. it keeps the rANS state internally to simplify code and declutter interface
* Coder methods refactored to be compliant with std::iterator_traits.
* Coder/Encoder writes output to encode buffer from the beginning of the buffer (instead of the end) to simplify handling of the encode buffer. The return value is an iterator to the first element past the encoded message (stl complient).  
* The decoder starts from the end of the stream (i.e. iterator to first element past the message) and decodes the message.
* adapt common detector entropy coding interfaces in EncodedBlocks.
> (O2-1203) [rANS] Coder Refactoring

- Generators/src/DecayerPythia8.cxx
- Return isFinal() as the particle status code (instead of statusHepMC()), to be consistent with
the decayer implementation in AliRoot.
- Revert back the changes in commit  b3e825ecc3 (not needed anymore).
This should fix the problem with the explosion of the log file in Geant4 O2 production tests.
> A  fix for importing decay products:

- run/SimExamples/AliRoot_Hijing/run.sh
Updating this example to run with `o2-sim` executable, now that we understood how to make it work like that.
> Update AliRoot_Hijing example to run with o2-sim

- DataFormats/Headers/include/Headers/RAWDataHeader.h
- Detectors/FIT/FT0/reconstruction/CMakeLists.txt
- Detectors/FIT/FT0/reconstruction/include/FT0Reconstruction/ReadRaw.h
- Detectors/FIT/FT0/reconstruction/src/ReadRaw.cxx
- Detectors/MUON/MID/Raw/src/CRUBareDecoder.cxx
- Detectors/MUON/MID/Raw/src/RawBuffer.cxx
- Detectors/MUON/MID/Raw/src/RawFileReader.cxx
- Detectors/TOF/compression/include/TOFCompression/Compressor.h
- Detectors/TOF/compression/include/TOFCompression/CompressorTask.h
- Detectors/TOF/compression/src/Compressor.cxx
- Detectors/TOF/compression/src/CompressorTask.cxx
- Detectors/TOF/reconstruction/include/TOFReconstruction/DecoderBase.h
- Detectors/TOF/reconstruction/src/Decoder.cxx
- Detectors/TOF/reconstruction/src/DecoderBase.cxx
- Detectors/TOF/workflow/include/TOFWorkflow/CompressedInspectorTask.h
- Detectors/TOF/workflow/src/CompressedDecodingTask.cxx
- Detectors/TOF/workflow/src/CompressedInspectorTask.cxx
- Detectors/TPC/calibration/run/calib-pedestal.cxx
- Detectors/TPC/reconstruction/include/TPCReconstruction/RawReaderCRU.h
- Detectors/TPC/reconstruction/src/RawReaderCRU.cxx
- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- Detectors/TPC/workflow/src/LinkZSToDigitsSpec.cxx
- Detectors/TPC/workflow/src/ZSSpec.cxx
* TOF: fixes: use RDHUtils to access RDH fields, dont use RAWDataHeader as template typename
* FT0: fixes: use RDHUtils to access RDH fields
* TPC: fixes: use RDHUtils to access RDH fields
* MID: fixes: use RDHUtils to access RDH fields
* Link RAWDataHeader to RAWDataHeaderV6
I've fixed compilation conflicts + hardcoded particular RDH version + obvious cases of direct access to RDH fields for detectors above.
@wiechula, @noferini, @preghenella, @AllaMaevskaya, @dstocco, could you please check if these fixes are ok?
Will merge this on Fri. if there are no blockers.
@JohannesLb I see that in 0422b5cdb35adbbc714795f70b73851068deb29a you have reverted usiage of some RDHUtils getters to direct access to RDH fields. Was there any reason for that? In this PR I've reverted to RDHUtils usage.
> Move to RAWDataHeaderV6 as default header

- Framework/Core/include/Framework/InputRecord.h
- Framework/Core/test/test_DataAllocator.cxx
I'm opening a new PR in order to discuss this topic even though it depends on the commit in #2617 
When querying vectors, a spectator vactor is returned which is directly using
the raw memory without copy using polymorphic allocator and spectator memory
resource. A unique instance of the spectator memory resource is kept in the
InputRecord and valid for the lifetime of teh record.
This changes the return type to `vector<T const, o2::pmr::SpectatorAllocator<T const>>`
and thus breaks compilation in code where the vector with standard allocator is used.
This is not problematic in cases where the returned instance is only used in the
function itself and not passed onto workers (unless in a templatized function call).
Ways out of this problem:
change access to the read-only input data objects …
> DPL I/O API: Supporting spectator vector as return for InputRecord::get<std::vector<T>>

- Detectors/EMCAL/base/src/Geometry.cxx
- index in module in phi direction was used by mistake as
module index -> Discrete col / row numbers
- Previous module missing in calculation of the absolute
row ID
- Col index in DCAL odd supermodules must be shifted by 16
> [EMCAL-656] Fix calculation of glob. position from cell abs ID

- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- Detectors/TPC/workflow/src/tpc-reco-workflow.cxx
- GPU/Common/GPUCommonAlgorithm.h
- GPU/GPUTracking/Base/GPUDataTypes.h
- GPU/GPUTracking/Base/GPUReconstruction.cxx
- GPU/GPUTracking/Base/GPUReconstruction.h
- GPU/GPUTracking/Base/GPUReconstructionCPU.cxx
- GPU/GPUTracking/Base/GPUReconstructionCPU.h
- GPU/GPUTracking/Base/GPUSettings.cxx
- GPU/GPUTracking/Base/GPUSettings.h
- GPU/GPUTracking/Base/cuda/GPUReconstructionCUDA.cu
- GPU/GPUTracking/Base/cuda/GPUReconstructionCUDAInternals.h
- GPU/GPUTracking/DataCompression/GPUTPCClusterStatistics.cxx
- GPU/GPUTracking/Global/GPUChain.h
- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/Global/GPUChainTracking.h
- GPU/GPUTracking/Interface/GPUO2Interface.cxx
- GPU/GPUTracking/Interface/GPUO2Interface.h
- GPU/GPUTracking/Interface/GPUO2InterfaceConfiguration.h
- GPU/GPUTracking/Merger/GPUTPCGMMerger.cxx
- GPU/GPUTracking/Standalone/qconfigoptions.h
- GPU/GPUTracking/Standalone/standalone.cxx
- GPU/GPUTracking/Standalone/utils/timer.cxx
This PR finally implements the pipeline fed by 2 threads in a ping-pong way.
Required several additional features and improvements.
Average processing time on the RTX 2080 Ti improves from 1250 GPUs to 1175 GPUs.
> Multi-threaded ping-pong pipeline for the GPU tracking + required features + some fixes

- DataFormats/Detectors/EMCAL/include/DataFormatsEMCAL/Digit.h
Due to the change from Energy to Amplitude the new
digit class is no longer compatible with the old
layout. Therefore the ClassDef needs to be increased.
> [EMCAL-502] Increment ClassDef version of the Digit

- Common/SimConfig/CMakeLists.txt
- Common/SimConfig/include/SimConfig/SimUserDecay.h
- Common/SimConfig/src/SimConfigLinkDef.h
- Common/SimConfig/src/SimUserDecay.cxx
- Generators/include/Generators/DecayerPythia8.h
- Generators/include/Generators/DecayerPythia8Param.h
- Generators/src/DecayerPythia8.cxx
- Steer/include/Steer/O2MCApplicationBase.h
- Steer/src/O2MCApplication.cxx
- run/SimExamples/ForceDecay_Lambda_Neutron_Dalitz/README.md
- run/SimExamples/ForceDecay_Lambda_Neutron_Dalitz/decay_lambda_neutron_dalitz.cfg
- run/SimExamples/ForceDecay_Lambda_Neutron_Dalitz/run.sh
- run/SimExamples/README.md
This PR allows the user to switch on Geant user decay for any given particle.
It is technically done via configurable parameters at command line.
As an example
```
--configKeyValues 'SimUserDecay.pdg=3122 111;
```
will turn on user decay for Lambda0 (3122) and pi0 (111) which will be in turn be decayed by the external decayer. 
The feature will be useful for users that need productions with force decays and/or decay chains.
An example of use is given in
```
run/SimExamples/ForceDecay_Lambda_Neutron_Dalitz/
```
The PR also adds the `DecayerPythia8.verbose` parameter to have a verbose logging.
*****
This is the README.md of the sim example.
This is a simple simulation example showing how to force a specific particle decay chain.
To simplify the example, we will use a Box generator to inject …
> Allow to set GEANT UserDecay via configurable params

- Detectors/TPC/simulation/run/convertDigitsToRawZS.cxx
- Detectors/TPC/workflow/src/ZSSpec.cxx
- GPU/GPUTracking/Base/GPURawData.h
- GPU/GPUTracking/Base/GPUReconstructionConvert.cxx
- GPU/GPUTracking/Base/GPUReconstructionConvert.h
- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/Global/GPUChainTrackingIO.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFDecodeZS.cxx
@shahor02 @wiechula @ironMann : This moves the GPU and TPC ZS code to RDH version 6. It is not backward-compatible, so all Raw files created with the o2-tpc-digits-to-rawzs tool will not be readable anymore. Should give a readable error though. This cannot be avoided without making the RDHAny gpu-compatible and doing the arbitration on the GPU during ZS decoding. I hope we are still in a situation where we can do such a change.
> GPU: Switch GPU code to RawDataHeaderV6

- GPU/GPUTracking/Base/GPUReconstruction.h
- GPU/GPUTracking/Base/hip/GPUReconstructionHIP.h
- GPU/GPUTracking/Base/hip/GPUReconstructionHIP.hip.cxx
- GPU/GPUTracking/Global/GPUChainTracking.cxx
It seems with hip memory registered with hipHostRegister is not in the unified address space, so we have to do some magic with the host pointers to enable zero-copy dma access from GPU kernels.
> GPU: Obtain valid device-version of host pointer for HIP

- GPU/TPCFastTransformation/TPCFastTransformManager.cxx
@sgorbuno : Disabling this temporarily since it crashes. Just disabled it again once fixed.
> GPU: Disable TPC fast inverse transform for AliRoot

- Detectors/Raw/include/DetectorsRaw/RawFileWriter.h
@davidrohr I had a bug introduced in the writer, w/o this fix the TPC RDHs will not have stops set.
> Fix in RawFileWriter wrong default

- DataFormats/Detectors/Common/include/DetectorsCommonDataFormats/NameConf.h
- DataFormats/Detectors/Common/src/NameConf.cxx
- Detectors/Base/src/Ray.cxx
- Detectors/GlobalTracking/include/GlobalTracking/MatchTPCITSParams.h
- Detectors/GlobalTracking/src/MatchTPCITS.cxx
- Detectors/GlobalTrackingWorkflow/src/TPCITSMatchingSpec.cxx
* Fix in ray-tracing for material lookup
* Retrieve material LUT filename from NameConf
* Can set material query method from MatchTPCITSParams
Default method in MatchTPCITSParams is set to USEMatCorrLUT, it will be automatically overridden to USEMatCorrTGeo if the material LUT file is not available in the current directory.
This is a hack until the material LUT will be provided by the framework as CCDB object.
> Fix in ray tracing and use material LUT in TPC-ITS matching

- DataFormats/common/include/CommonDataFormat/InteractionRecord.h
Since the hadronic and QED event records need to be merged in a sorted way, the InteractionTimeRecord must implement its own comparison operators, accounting for the timeInBunch rather than inheriting them from the InteractionRecord
> InteractionTimeRecord must override comparison operators

- Framework/Logger/include/Framework/Logger.h
This needs before merging:
- FairRootGroup/FairLogger#26
- alisw/alidist#2307
- FairRootGroup/FairLogger#25
It complements the FairLogger PR and makes sure that in all cases LOG(debug, ...) is optimized away at compile time for verbosity = debug or lower.
ping @sawenzel @ktf
> Suppress LOG messages with debug severity or less at compile time for release builds

- Detectors/GlobalTracking/include/GlobalTracking/MatchTPCITS.h
- Detectors/GlobalTracking/include/GlobalTracking/MatchTPCITSParams.h
- Detectors/GlobalTracking/src/MatchTPCITS.cxx
* Eliminate vector expansion hotspot
* Option of 1/pT cutoff for ITS and TPC tracks
> Speed-up of TPC-ITS matching

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/AlgorithmSpec.h
- Framework/Core/include/Framework/ChannelConfigurationPolicyHelpers.h
- Framework/Core/include/Framework/ChannelSpec.h
- Framework/Core/include/Framework/DataProcessingDevice.h
- Framework/Core/include/Framework/DeviceState.h
- Framework/Core/src/ChannelConfigurationPolicyHelpers.cxx
- Framework/Core/src/ChannelSpecHelpers.cxx
- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/src/DriverInfo.h
- Framework/Core/src/FrameworkGUIDebugger.cxx
- Framework/Core/src/WorkflowHelpers.cxx
- Framework/Core/src/runDataProcessing.cxx
- dependencies/O2Dependencies.cmake
This is a major refactoring of the DPL driver and DataProcessingDevice, integrating libuv as a backend to do event driven I/O rather than the old busy loop. In particular this provides:
* DataProcessingDevice does not need to busy loop anymore. When ZeroMQ activity is detected on the socket by the libuv poller, we enter the standard event processing of DPL, processing all pending messages. This should ensure that we busy loop as fast as possible when data needs to be processed and we block on the epoll / kqueue call when nothing is happening. @Barthelemy @davidrohr @knopers8 this should remove completely our issue with "what delay to use to ensure best performance without consuming too much resources".
* The driver itself is fully event driven by libuv, again making it more responsive and …
> DPL:  event based processing

- Detectors/Base/include/DetectorsBase/Ray.h
- Detectors/Base/src/MatLayerCylSet.cxx
* If queried points are separated by less than threshold (1\mum), 0 material budget will be returned, with the length set.
* Material LUT will return full distance, even if outside of the acceptance
Change in the definition of the MatBudget.length: it will always correspond to full straight distance between start and end points. 
In opposite, the meanX2X0 and meanXRho are calculated only for the segments which are parametrized by the LUT (i.e. detectors acceptance).
> Material LUT treats as 0 lenght distances < 1micron, always return full length

- Analysis/DataModel/include/Analysis/SecondaryVertexHF.h
- Analysis/Tasks/CMakeLists.txt
- Analysis/Tasks/hftrackindexskimscreator.cxx
- First step for the final structure: the vertexinghf.cxx task will be split in partial steps to facilitate the code development
- The task hftrackindexskimscreator.cxx will include the creation of the track index derived tables.
- Added options to include/exclude 3 prong and a selection on the single track min pT to perform CPU timing/performance tests
- the vertexerhf.cxx code will be kept for the moment cause it provides useful comparison with Run2 code. It will be removed once the full chain and the corresponding validation tools will be in place.
> Add 3 prong case in the skim + code reorganization

- Detectors/Passive/src/Cave.cxx
- Detectors/Passive/src/FrameStructure.cxx
- Detectors/Passive/src/Pipe.cxx
- Detectors/ZDC/simulation/src/Detector.cxx
corrected
- overlaps between HMP cradle and Frame
- small overlap inside frame
- overlap between RB24 pipe and ZDC (beam pipe)
- overlap between PIPE and COMP
For this a more realistic geometry of the pipe inside COMP has been implemented:
transition round to oval and oval beam.pipe inside the compensator magnet.  
Implementation needs to be reconsidered in case there is a performance penalty.
> overlap corrections in passive components

- Detectors/TRD/simulation/include/TRDSimulation/Digitizer.h
- Detectors/TRD/simulation/src/Digitizer.cxx
Two things take place here:
- The implementation of signals pileup, and
- a basic trigger for the TRD, with dead time.
We may want to discuss where to keep the trigger. 
To do:
- Take the trigger information to the trigger records object, or
- omit the trigger records and use the digit time information instead, and
- map labels to digits by using and index in the MC label container (for another PR?)
> TRD: trigger and pileup implementation 

- Detectors/ITSMFT/ITS/macros/test/CheckTracks.C
In PYTHIA events, primary particles come from quarks not from a mother with id -1
> Fix primary particle definition in CheckTracks.C

- DataFormats/Detectors/FIT/FT0/include/DataFormatsFT0/HitType.h
ClassDefNV was missing, even with it the dictionary complains of template ambiguities when loading
Hits tree interactively
> FT0::HitType: provide all template types to generate dict.

- Framework/Core/include/Framework/AnalysisDataModel.h
- Framework/Core/src/AODReaderHelpers.cxx
- Framework/Core/test/test_AnalysisDataModel.cxx
@aalkin The current version compiles, but the extended table is not recognised in the exection, for example in:
o2-analysistutorial-mc-histograms -b --aod-file AO2D.root
and I get exception
[26594:internal-dpl-aod-spawner]: [12:39:28][ERROR] Exception caught: TRACLPARCOV: Not an extended table
> Extended table for the modified cov. matrix

- DataFormats/Headers/include/Headers/DataHeader.h
- Detectors/CTF/workflow/include/CTFWorkflow/CTFReaderSpec.h
- Detectors/CTF/workflow/src/CTFReaderSpec.cxx
- Detectors/Raw/src/RawFileReaderWorkflow.cxx
* Add ever-incrementing TF counter to DataHeader
The DataHeader::firstTForbit will not be unique when the same TFs are replayed in loop, this counter will resolve the ambiguity.
* Set the tfCounter in RawDataReader and CTFReader 
@ironMann this would need to be set also in the STFbuilder
> TF counter in the DataHeader

- Framework/Core/src/FrameworkGUIDebugger.cxx
Render it unformatted in case that's the case.
> DPL GUI: avoid misbehavior when % is passed in string

- GPU/GPUTracking/CMakeLists.txt
- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/Global/GPUChainTracking.h
- GPU/GPUTracking/TPCClusterFinder/CfFragment.h
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFChainContext.h
This PR avoids scanning the tpc raw pages multiple times for precomputing pointers for decoded adc values.
It is slightly faster than before and in particular reduces the stress on the CPU cache and the host memory.
Also, this is needed for some further optimizations that are planed.
> GPU: Compute TPC page and digits offsets for all fragments in one loop over raw pages header

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/CommonServices.h
- Framework/Core/include/Framework/DataProcessingDevice.h
- Framework/Core/include/Framework/DataProcessorSpec.h
- Framework/Core/include/Framework/DeviceSpec.h
- Framework/Core/include/Framework/ServiceRegistry.h
- Framework/Core/include/Framework/ServiceSpec.h
- Framework/Core/include/Framework/runDataProcessing.h
- Framework/Core/src/CommonServices.cxx
- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/Core/src/runDataProcessing.cxx
- Framework/TestWorkflows/src/o2DummyWorkflow.cxx
This finally implements Services as originally conceived:
* Each dataprocessor has a list of required services specification.
The specification will allow creating the service and (optionally)
configuring it, attaching them to the provided Context.
* Required services are instanciated before running, without having to
hardcode the list.
Eventually this will be extended to support transitions in a multithreaded
environment (e.g. some services might have to be created on a per thread
basis).
By default the old list of hardcoded services is provided. Users can override
that via the usual customise mecanism.
> DPL: proper Services API

- Analysis/DataModel/include/Analysis/RecoDecay.h
- Analysis/DataModel/include/Analysis/SecondaryVertex.h
- Analysis/DataModel/include/Analysis/SecondaryVertexHF.h
- Analysis/Tasks/CMakeLists.txt
- Analysis/Tasks/hfcandidatecreator2prong.cxx
- Analysis/Tasks/hftrackindexskimscreator.cxx
- Analysis/Tasks/taskdzero.cxx
- Analysis/Tasks/vertexerhf.cxx
Dear @jgrosseo this PR is ready to be merged. Please squash it before merging. A complete description of the modifications is provided below. 
- split the workflow in track finder, candidate building and task
- loop reorganized per charge, following the Run2 schema
- dca selection on single track included (being compared to Run2) 
- add validation plots inside the different tasks (to be replaced by corresponding QA). Validation plots production can be activated using a flag.
- Add a RecoDecay.h header to store the definition of decay variables
- Add more selection and kinematic variables for D0 decays
> Split workflow in multiple tasks and add validation plots

- Detectors/ITSMFT/ITS/workflow/src/ClustererSpec.cxx
- Detectors/ITSMFT/MFT/workflow/src/ClustererSpec.cxx
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/Clusterer.h
- Detectors/ITSMFT/common/reconstruction/src/Clusterer.cxx
- Detectors/ITSMFT/common/reconstruction/src/RawPixelDecoder.cxx
- Detectors/ITSMFT/common/workflow/src/STFDecoderSpec.cxx
Following patch from Gvozden switched to more conventional OMP parallel for cycle.
The OMP dynamic chunk size and number of chips per thread is tuned for AMD ROME single workflow MT processing with
export GOMP_CPU_AFFINITY=0-63
numactl -N 0 --membind 0 ./benchmark.sh
> Improve ITS clusterizer multi-threading

- Detectors/TPC/qc/src/PID.cxx
- Detectors/TPC/qc/src/Tracks.cxx
o Phi range has been changed from -pi to +pi now to 0 to 2pi
o This is changed here in the TPC O2 QC tasks
o In addition, the hard coded cut on TPC clusters in the tracks task
is switched off for the tests during TPC pre-commissioning
> TPC QC tasks on Tracks and PID: fix phi range

- Framework/Core/include/Framework/AODReaderHelpers.h
- Framework/Core/src/AODReaderHelpers.cxx
- Framework/Core/src/WorkflowHelpers.cxx
a run time watchdog is introduced which stops execution when runtime exceeds a given limit.
. use command line optino --time-limit to specify run time limit in seconds
. stops only at time frame boundaries, thus before data for next time frame is to be read
> run time watchdog

- Detectors/FIT/FT0/simulation/src/Digitizer.cxx
bug fixes in Digitizer:
- event number; 
-  remove very slow particles (with TOF>250ns);
-  correct treatment of events with the same BC/orbit
> fix event number in Digitizer

- Detectors/MUON/MCH/Workflow/README.md
- Detectors/MUON/MID/Workflow/README.md
- Detectors/Raw/README.md
- Detectors/Raw/include/DetectorsRaw/RawFileReader.h
- Detectors/Raw/src/RawFileReaderWorkflow.cxx
- Detectors/Raw/src/RawFileReaderWorkflow.h
- Detectors/Raw/src/rawfile-reader-workflow.cxx
* raw-file-reader can send TF data to non-DPL FMQ channel
Provide e.g. --session default --raw-channel-config "name=raw-reader,type=push,method=bind,address=ipc://@rr-to-dpl,transport=shmem,rateLogging=1"
* Eliminate obsolete options of raw-file-reader
No need for options message-per-tf (must be always sent as a multipart of HBFs) and output-per-link (must be always sent per output_channel)
> raw-file-reader can send TF data to non-DPL FMQ channel

- Framework/Core/include/Framework/ExternalFairMQDeviceProxy.h
- Framework/Core/src/ExternalFairMQDeviceProxy.cxx
- Framework/Core/test/test_ExternalFairMQDeviceWorkflow.cxx
@davidrohr @ironMann for me with this PR the round-robin over the pipelines works also when data are injected via ``o2-dpl-raw-proxy``. Tested with rawreader, could you check if for you it works with DD?
> Account for timeslice in FMQ ChannelRetriever of ExternalFairMQDeviceProxy

- Analysis/Tasks/correlationsCollection.cxx
- Analysis/Tasks/jetfinder.cxx
- Analysis/Tutorials/src/filters.cxx
- Analysis/Tutorials/src/histograms.cxx
- Framework/Core/include/Framework/AnalysisDataModel.h
- Framework/Core/include/Framework/BasicOps.h
- Framework/Core/include/Framework/Expressions.h
- Framework/Core/src/ExpressionHelpers.h
- Framework/Core/src/Expressions.cxx
- Framework/Core/test/test_AnalysisDataModel.cxx
- Framework/Core/test/test_Expressions.cxx
WARNING: will not work without https://github.com/alisw/alidist/pull/2343
* New functions for expressions
* p, pT, eta and phi as expression columns (currently phi is not normalized to [0:2pi), use dynamic nphi to get that)
*  Adapted filters.cxx example
* Adapted histograms.cxx example
> DPL Analysis: implementation of expression columns with new functions

- Detectors/TRD/base/src/TRDGeometry.cxx
- Detectors/TRD/simulation/src/Detector.cxx
Fix bug due to changes in #3758.
The following change:
```
std::string vpStr{"ALIC_1/B077_1/BSEGMO"};
std::string vpStr{"ALIC_1/barrel_1/B077_1/BSEGMO"};
```
affected one string that is used to compute detector geometry.
> TRD: Fix bug due to changes in #3758

- Framework/Core/src/DataProcessingDevice.cxx
The issue seems to be that UV_READABLE events are triggereded on a socket which
should be used for writing. Such a socket should not really be subscribing to
such events, but it happens because the rfind is not taking into account the
_tX. This prevents from subscribing in the first place.
> DPL: fix 100% CPU utilization when timepipeline idle (O2-1541)

- Detectors/TRD/simulation/src/Detector.cxx
Related to #3890, and just for the code quality: we want a single character rather than an array with at the most one character.
> TRD: Minor fix Detector.cxx

- Detectors/TOF/base/include/TOFBase/Geo.h
- Detectors/TOF/base/include/TOFBase/WindowFiller.h
- Detectors/TOF/reconstruction/src/Decoder.cxx
- Detectors/TOF/simulation/src/Digitizer.cxx
- Steer/DigitizerWorkflow/src/TOFDigitizerSpec.cxx
Required to simulate cosmic rays (low rates --> large number of timeframes)
> fix for float truncation affecting timing in large timeframe numbers

- Generators/CMakeLists.txt
- Generators/include/Generators/GeneratorHepMC.h
- Generators/src/GeneratorHepMC.cxx
- dependencies/FindHepMC3.cmake
- dependencies/O2SimulationDependencies.cmake
This is a complex PR because it depends on an `alidist` update.
That PR on `alidist` will be opened soon.
This PR aligns the `o2` code to the upgraded `HepMC3`.
The latest `HepMC3` tag (3.2.2) is supposed to solve a few issues.
Most importantly, the name of the library is now `libHepMC3.so`.
This solves library-name clashes with HepMC2 (lib name was the same before) and possibly allows users to load packages with dependencies on both HepMC versions at the same time (see AliRoot).
Also, a `DEBUG` macro that was clashing with `FairRoot` was renamed.
Unfortunately the `HepMC3` authors have also modified the name of the directory with the files to be included and the namespace name. Hence this update.
Changes are also in the cmake machinery, that requires adjustments in the `o2` as well.
This …
> Changes related to HepMC3 upgrade to 3.2.2

- Analysis/Tutorials/CMakeLists.txt
- Analysis/Tutorials/src/partitions.cxx
- Framework/Core/include/Framework/AnalysisTask.h
Input tables can be partitioned for use inside `process()`, added partitions.cxx example.
Pinging also @aalkin for review.
> DPL Analysis: Added partitions

- Analysis/Tutorials/src/filters.cxx
- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/AnalysisTask.h
- Framework/Core/include/Framework/Expressions.h
- Framework/Core/src/AODReaderHelpers.cxx
- Framework/Core/src/ExpressionHelpers.h
* Slight rework of the spawner code to make it available not only in AODReaderHelpers
* Spawns<> template to mark the task as an origin of a particular extended table. The table is available in the originating task as well, through this template, and can be subscribed by subsequent tasks.
* Primitive example/test in filters.cxx
> DPL Analysis: Spawns<> template for user-defined extended tables

- Detectors/TRD/base/include/TRDBase/Tracklet.h
- Detectors/TRD/base/src/Tracklet.cxx
- Detectors/TRD/simulation/src/TrapSimulator.cxx
1. put all tracklet plots in 1 file, no more hundreds of files.
2. correctly plot graphs for COLZ option and actually working.
3. output corresponding text for each plot to cross reference the plots with the tracklet parameters 
4. something wrong with the calcuation of offsets as the tracklet line is often off the axises, fixed later.
> Fix trd trackletplots

- DataFormats/Detectors/ITSMFT/common/include/DataFormatsITSMFT/ClusterPattern.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/Clusterer.h
- Detectors/ITSMFT/common/reconstruction/src/Clusterer.cxx
- Framework/Core/src/runDataProcessing.cxx
- scripts/py-analysis-benchmark.py
When at least one of bounding box dimensions of a cluster does not fit one byte, such a cluster is split into pieces that have smaller bounding boxes. The initial huge cluster is then streamed piece by piece.
> Stream huge ITS clusters in pieces

- Detectors/EMCAL/base/include/EMCALBase/Geometry.h
- Detectors/EMCAL/base/src/Geometry.cxx
Add function getting the abs. cell ID and the cell
indices from the global row and col in the EMCAL/
DCAL space.
> [EMCAL-658] Get glob cell ID from col/row in EMCAL

- Framework/Core/include/Framework/CommonServices.h
- Framework/Core/include/Framework/ServiceSpec.h
- Framework/Core/src/CommonMessageBackends.cxx
- Framework/Core/src/CommonServices.cxx
- Framework/Core/src/runDataProcessing.cxx
There is now three new hooks:
* Before forking.
* After forking on the parent path.
* After forking on the child path.
This will allow having services which exploit Copy-On-Write when
we get rid of the execvp.
We also use these hooks to set the number of available threads for
libuv.
> DPL: introduce forking hooks

- Framework/Core/src/DataProcessingDevice.cxx
Doing so avoid issues with including Tracy.hpp in the .h (to debug
yet to come mutexes).
> DPL: move TracyClient include at the top

- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- GPU/GPUTracking/DataCompression/GPUTPCCompressionKernels.cxx
@shahor02 : should fix the issue. The problem appeared when there was an empty page in the middle of a buffer. This happens when you have the empty HBFs in the same superpage.
> TPC: Fix reading of TPC raw pages with interim empty pages

- Framework/Core/src/DeviceSpecHelpers.cxx
Otherwise breaks workflow merging
> DPL: remove spurious printouts during topology creation

- Utilities/rANS/include/rANS/SymbolStatistics.h
- Utilities/rANS/src/SymbolStatistics.cxx
Building SymbolStatistics for signed data implies iterator spanning from mMin<0 to mMax>0, change mIterator
mMin and mMax to int64_t from int and size_t respectively
> SymbolStatistics::mIterator allowed to take negative values

- Detectors/TOF/base/include/TOFBase/Digit.h
- Detectors/TOF/base/include/TOFBase/Strip.h
- Detectors/TOF/base/include/TOFBase/WindowFiller.h
- Detectors/TOF/base/src/Digit.cxx
- Detectors/TOF/base/src/Strip.cxx
- Detectors/TOF/base/src/WindowFiller.cxx
- Detectors/TOF/reconstruction/include/TOFReconstruction/Clusterer.h
- Detectors/TOF/reconstruction/include/TOFReconstruction/Decoder.h
- Detectors/TOF/reconstruction/src/Clusterer.cxx
- Detectors/TOF/reconstruction/src/Decoder.cxx
- Detectors/TOF/reconstruction/src/Encoder.cxx
- Detectors/TOF/workflow/include/TOFWorkflow/CompressedDecodingTask.h
- Detectors/TOF/workflow/src/CompressedDecodingTask.cxx
- Detectors/TOF/workflow/src/TOFClusterizerSpec.cxx
* Ensure TOF matching uses TF 1st orbit for time reference
* Do not send ROMode for GRPUpdated from CompressedDecodingTask
* Fix TOF digit fields to allow multiple TF processing
Since the TOF digit stores as BC the absolute bunch count from orbit 0, with int32 it will overflow after ~100 s. Change it uint64_t.
Also fix the orbit/bc to uint32_t / uint16_t resp.
> Fixes in TOF for arbitrary TF processing

- Analysis/Tutorials/src/filters.cxx
- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/AnalysisTask.h
- Framework/Core/include/Framework/Expressions.h
Allows user-defined extended tables to be declared over Joins, e.g. Join<Tracks, TracksCov>. Note that because of how macros work the joined type needs to be aliased by 'using' (see filters.cxx example).
> DPL Analysis: permit extending Joined tables

- DataFormats/Detectors/ITSMFT/MFT/include/DataFormatsMFT/TrackMFT.h
- DataFormats/Detectors/ITSMFT/MFT/src/TrackMFT.cxx
- Detectors/ITSMFT/MFT/tracking/include/MFTTracking/FitterTrackMFT.h
- Detectors/ITSMFT/MFT/tracking/include/MFTTracking/MFTTrackingParam.h
- Detectors/ITSMFT/MFT/tracking/src/TrackExtrap.cxx
- Detectors/ITSMFT/MFT/tracking/src/TrackFitter.cxx
- Detectors/ITSMFT/MFT/workflow/src/TrackFitterSpec.cxx
* Enables MFT track fitting smoother and stores parameters closest to the absorber: MFT-MCH track matching
* Optimized track propagation
* Minor change on track seed configuration
* Storing track finding method for each track
> [MFT] Storing parameters for MCH matching & minor adjustments

- Analysis/DataModel/include/Analysis/RecoDecay.h
- Analysis/DataModel/include/Analysis/trackUtilities.h
- Analysis/Tasks/hfcandidatecreator2prong.cxx
- Analysis/Tasks/hftrackindexskimscreator.cxx
* Add function getTrackParCov to construct a TrackParCov object from track parameters.
* Simplify manipulation with 4-momenta of daughter prongs of a decay candidate using the ROOT classes.
> Simplify reconstruction of decay candidates.

- Detectors/EMCAL/base/CMakeLists.txt
- Detectors/EMCAL/base/include/EMCALBase/Geometry.h
- Detectors/EMCAL/base/include/EMCALBase/GeometryBase.h
- Detectors/EMCAL/base/src/Geometry.cxx
- Detectors/EMCAL/base/test/testGeometryRowColIndexing.C
- Fix calculation of SM ID (GetEta and GetPhi returning
number of modules, not towers)
- Fix column shift of the DCAL odd supermodules
- Add exception for invalid row-col position, either with
row/col outside the valid area or within the PHOS hole
- Throw InvalidCellIDException for cell index outside range
> [EMCAL-658] Fix calculation of pos. in sm from global pos

- doc/DetectorSimulation.md
- run/SimExamples/AliRoot_AMPT/README.md
- run/SimExamples/AliRoot_AMPT/aliroot_ampt.macro
- run/SimExamples/AliRoot_AMPT/run.sh
- run/SimExamples/README.md
This is a complex simulation example showing how to run event simulation using the AMPT event generator interface from AliRoot.
A wrapper class AliRoot_AMPT is defined to keep the AliGenAmpt instance and configure it.
It also provides methods to set a random event plane before event generation and to update the event header.
The overall setup is steered by the function `ampt(double energy = 5020., double bMin = 0., double bMax = 20.)` defined in the macro `aliroot_ampt.macro`.
The macro file is specified via the argument of `--extGenFile` whereas the specific function call to retrieven the configuration is specified via the argument of `--extGenFunc`.
To run this example you need to load an AliRoot package compatible with the O2.
for more details, …
> An example of use of AMPT from AliRoot

- Generators/include/Generators/GeneratorPythia8.h
- Generators/src/GeneratorPythia8.cxx
This PR bring some small re-arrangements to `GeneratorPythia8` class in order to be able to
* set a user hook class directly and not only from a file
* be able to import particles from a generic Pythia8 event and not only from the one of the Pythia8 instance
The PR also provides a utility function that allows the user to fill an output Pythia8 event with particles selected from the input Pythia8 event. The selection is based on the index of the ancestor and all the daughters are appended in the output event.
The function takes care of adjusting the particle indices (mothers and daughters).
An example of usage of this function will be provided soon for an HF event generator where the `c-cbar` sub-event is stripped out from the full input event and appended to the output event.
Given the …
> Small arrangements for more flexibility + selectFromAncestor util function

- Framework/Core/src/DataInputDirector.cxx
- Framework/Core/src/DataOutputDirector.cxx
so far a missing Data[Input,Output]Director in the file passed via the --json-file command line option resulted in the termination of the program.  With this modification this does no longer happen.
> Accept missing Data[Input,Output]Director in json file

- Detectors/TOF/base/src/WindowFiller.cxx
- Detectors/TOF/workflow/src/CompressedDecodingTask.cxx
- macro/compareTOFDigits.C
This is needed to fix a bug which excluded the first digits during decoding.
With the fix the error messages "Digit lost because we jump too ahead in future" (traced also in PR 3972) are no longer present.
> fix in tof decoding to recover first readout window

- Analysis/Tutorials/src/partitions.cxx
- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/AnalysisTask.h
- Framework/Core/test/test_ASoA.cxx
- Framework/Core/test/test_AnalysisTask.cxx
Hi @ktf @aalkin ,
as per Anton's suggestions I've added union and intersection of Filtered selections.
Now the partitions work properly on filtered data and it is also possible to define next filters on already Filtered tables.
> DPL Analysis: Allow for nested filtering and partitioning on filtered

- Framework/Core/include/Framework/TableTreeHelpers.h
- Framework/Core/src/TableTreeHelpers.cxx
solves bug in TableTreeHelpers when reading TBranches of type l
> TBranches of type l (ULong64_t) have to be read back as long long unsigned

- Framework/Core/src/runDataProcessing.cxx
When passing environment to a pipelined process, one can use `{timeslice0}` (0
based index) or `{timeslice1}` (1 based) which will be substituted with the
actual timeslice of the given dataprocessor.
> DPL driver: allow {timeslice0} and {timeslice1} in --environment

- Framework/Core/src/DeviceSpecHelpers.cxx
Use 90% of the soft limit for VSIZE, unless otherwise specified
or unless unlimited.
> DPL: improve logic for default shm-segment-size

- Framework/Core/CMakeLists.txt
- Framework/Core/src/ChannelSpecHelpers.cxx
This has better chances to succeed (e.g. no AFS) and will avoid polluting the
pwd.
> DPL: open ipc socket in a tmp directory (O2-1512)

- dependencies/FindLibUV.cmake
With the current implementation the dependencies are not correctly exported.
So, for packages that depend on O2, the cmake fails in finding the libUV installed via aliBuild.
This PR should be complemented later on with a modification of o2.sh and libuv.sh inside alidist.
> Fix serach path for libUV

- Analysis/Tutorials/src/filters.cxx
- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/AnalysisTask.h
Fixes to handle grouping when the grouping iterator is filtered. Added an example to filters.cxx.
> DPL Analysis: allow grouping on filtered iterator

- Analysis/Tutorials/src/filters.cxx
- Framework/Core/include/Framework/DataTypes.h
- Framework/Core/src/Expressions.cxx
Adds type upcast so that smaller integer types can be compared with larger ones directly. Fixes filtering on track type (see filters.cxx example).
> DPL Analysis: fix for integer comparison in expressions

- GPU/GPUTracking/Global/GPUChainTracking.cxx
@shahor02 : This fixes the performance problem for me when the number of omp threads is not forced to 1.
Could you check whether it works for you as well?
Another question is: What do we want as default for the number of threads?
- Before my config change this was defaulted to 1 for the TPC workflow and must be set on the command line.
- Now, it takes the default from OpenMP, which is $OMP_NUM_THREADS or just the number of cores available if unset.
- Alternatively, we also have the option GPU_proc.ompKernels. This applies multi-threading in more places and speeds up the processing on the CPU significantly. However, it looses reproducibiltiy of the output. Without this option, OMP is applied only where the concurrency cannot change the output. By default this new option is disabled. Should …
> GPU: Fix incorrect number of blocks for TPC track merging on CPU with OMP without ompKernels

- DataFormats/Detectors/Common/include/DetectorsCommonDataFormats/SimTraits.h
- Detectors/Upgrades/IT3/base/src/GeometryTGeo.cxx
- Detectors/Upgrades/IT3/simulation/src/Detector.cxx
Geometry path now is consistent with what is used with ITS.
o2sim_HitsIT3.root is now filled correctly.
@mario6829 for knowledge.
Compile O2 with 
```bash
ENABLE_UPGRADES=ON aliBuild build O2 --defaults o2
```
to test it:
```bash
o2-sim -n1 -m PIPE IT3 -g boxgen --configKeyValues 'BoxGun.pdg=211 ; BoxGun.eta[0]=0 ; BoxGun.eta[1]=0; BoxGun.number=1'
```
> Fix ITS3 simulation

- Framework/Core/include/Framework/DataProcessingDevice.h
- Framework/Core/include/Framework/ServiceRegistry.h
- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/src/ServiceRegistry.cxx
- Framework/Core/src/runDataProcessing.cxx
- Framework/Core/test/test_Services.cxx
Since the ServiceRegistry is needed to manage the lifetime of services, in
particular in a multithreaded environment, this moves the responsibility of
managing / invoking the ServiceSpec associated callback (including the one
which actually creates the service, possibly on a per thread basis) to the
service registry.
> DPL: move Service callback responsibility to ServiceRegistry

- DataFormats/Detectors/TOF/CMakeLists.txt
- DataFormats/Detectors/TOF/include/DataFormatsTOF/CTF.h
- DataFormats/Detectors/TOF/src/CTF.cxx
- DataFormats/Detectors/TOF/src/DataFormatsTOFLinkDef.h
- Detectors/CTF/workflow/CMakeLists.txt
- Detectors/CTF/workflow/src/CTFReaderSpec.cxx
- Detectors/CTF/workflow/src/CTFWriterSpec.cxx
- Detectors/GlobalTrackingWorkflow/tofworkflow/src/tof-reco-workflow.cxx
- Detectors/TOF/base/include/TOFBase/Digit.h
- Detectors/TOF/base/src/WindowFiller.cxx
- Detectors/TOF/reconstruction/CMakeLists.txt
- Detectors/TOF/reconstruction/include/TOFReconstruction/CTFCoder.h
- Detectors/TOF/reconstruction/src/CTFCoder.cxx
- Detectors/TOF/reconstruction/src/TOFReconstructionLinkDef.h
- Detectors/TOF/simulation/src/Digitizer.cxx
- Detectors/TOF/workflow/CMakeLists.txt
- Detectors/TOF/workflow/include/TOFWorkflow/DigitReaderSpec.h
- Detectors/TOF/workflow/include/TOFWorkflow/EntropyDecoderSpec.h
- Detectors/TOF/workflow/include/TOFWorkflow/EntropyEncoderSpec.h
- Detectors/TOF/workflow/src/DigitReaderSpec.cxx
- Detectors/TOF/workflow/src/EntropyDecoderSpec.cxx
- Detectors/TOF/workflow/src/EntropyEncoderSpec.cxx
- Detectors/TOF/workflow/src/TOFDigitWriterSpec.cxx
- Detectors/TOF/workflow/src/entropy-encoder-workflow.cxx
- Steer/DigitizerWorkflow/src/TOFDigitizerSpec.cxx
A first prototype of TOF CTF is provided.
digit->CTF and viceversa implemented and tested:
o2-tof-reco-workflow -b --output-type ctf|o2-ctf-writer-workflow -b --onlyDet TOF
o2-ctf-reader-workflow -b --ctf-input o2_ctf_0000000000.root |o2-tof-reco-workflow -b --input-type ctf --output-type digits
Currently TOF CTF size too large and needs optimization BUT this PR is needed to continue the work (since changes in digit structure are required to run on the grid pbpb)
> TOF CTF: first prototype

- GPU/GPUTracking/Base/GPUSettingsList.h
@shahor02 : This enables the more aggressive OMP mode I mentioned by default.
It is significantly faster on larger data, but it will also have some overhead say for triggered pp events.
And results are no longer reproducible.
> GPU: Set ompKernels=true by default in GPUReconstruction on CPU

- Utilities/rANS/include/rANS/SymbolStatistics.h
- Utilities/rANS/src/SymbolStatistics.cxx
Supersedes #4074 
@shahor02 @MichaelLettrich : Could you check this attemp. It does everything in 2-3 iterations over the data, and should actually be more exact than before, since the ideal scaling is computed under the restriction that it must not produce 0 frequency without stealing.
It is significantly faster for me in first tests, will try with full system test now. Encoding runs through, but I didn't check decoding or compression factors yet.
> Further speed up of rANS cummulative frequency rescaling

- Generators/CMakeLists.txt
Replaced install(FILES ..) with o2_data_file(..) macro;
this avoids o2sim_G3/4 ctest failures due to missing Generators directory in the
'stage' directory in build.
> Fix in Generators CMake:

- Detectors/TOF/reconstruction/include/TOFReconstruction/DecoderBase.h
This PR allows the use of the TOF compressed decoder in `CONET` mode.
This is a special mode that will be used for running QC and analyses on the TOF DCS computer nodes.
> Flag to allow use of compressed decoder in CONET mode

- Detectors/TPC/base/include/TPCBase/CalArray.h
- Detectors/TPC/qc/CMakeLists.txt
- Detectors/TPC/qc/include/TPCQC/CalPadWrapper.h
- Detectors/TPC/qc/include/TPCQC/Clusters.h
- Detectors/TPC/qc/src/TPCQCLinkDef.h
- Added a wrapper for the TPC CalDet class so that CalDet objects can be published to the CCDB. This is needed only temporarily and will be removed at a later point.
- Added a check in the /= operator of the CalArray class to prevent division by 0
> TPC CalDet wrapper

- Steer/DigitizerWorkflow/src/SimReaderSpec.cxx
So far, the same interaction records were produced for each digitization
invocation. This commit forces random start seeding as a quick fix.
> Use random seeding in digitization (interaction records)

- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- Detectors/TPC/workflow/src/tpc-reco-workflow.cxx
- GPU/GPUTracking/Standalone/qa/GPUQA.cxx
The callback registry seems to leak the shared pointer, so we pass it by reference (this can never break, since the processing function anyway keeps the shared pointer).  @ktf : This fixes the leak I mentioned in the mail before.
> Ensure proper cleanup of process attributes

- Generators/src/GeneratorFactory.cxx
configures by default Pythia8 generator to use the random seed from `gRandom->GetSeed()`.
Must protect with a `% 900000000` because Pythia8 does not accept seeds bigger than this value.
> Use the random seed from gRandom as default for Pythia8

- Framework/Core/src/runDataProcessing.cxx
@ktf : Can we use this as a workaround for now to stop flooding my logs?
> DPL: Make sure forceful exit message is printed only once

- Detectors/TPC/calibration/SpacePoints/src/TrackInterpolation.cxx
@martenole @shahor02 : I guess this needs to be done properly later based on statistics, but for now I need a quick option to fix the amount of data that is collected to keep the memory size constant in order to check for leaks., and also the output becomes outrageously large after running >1 hour with 8 GPUs.
> Add a reset interval option for the TPC track interpolation workflow

- Detectors/TPC/reconstruction/include/TPCReconstruction/KrBoxClusterFinder.h
- Detectors/TPC/reconstruction/macro/findKrBoxCluster.C
- Detectors/TPC/reconstruction/src/KrBoxClusterFinder.cxx
The old cluster finder had a small inconsistency since it did not take into account that each pad-row starts at 0.
> Revised Krypton Box Cluster Finder

- Detectors/TOF/workflow/src/CompressedDecodingTask.cxx
Needed just to comply with TOF CTF encoder inputs, to be changed to meaningfull input by TOF experts
> Add dummy PATTERNS output to TOF decoder

- Framework/Core/include/Framework/CallbackService.h
- Framework/Core/include/Framework/ControlService.h
- Framework/Core/include/Framework/TextControlService.h
- Framework/Core/src/TextControlService.cxx
A simple mutex should suffice, since in any case it's called very
rarely.
>  DPL: mark a few services as thread safe 

- Detectors/ITSMFT/common/workflow/src/digit-writer-workflow.cxx
- Detectors/ITSMFT/common/workflow/src/entropy-encoder-workflow.cxx
- Detectors/ITSMFT/common/workflow/src/stf-decoder-workflow.cxx
@shahor02 : I had some trouble that workflows were complaining that `--mft` is ambiguous.
I believe what happens is that there are processors called `mft-entropy-encoder` and `mft-ctf-dictionary` both not knowing about the `--mft` option, and the parser is trying to find out where to apply the `--mft` and then it tries to expand the option to `--mft...` and then hits this ambiguity. Perhaps it is not a good idea to have options with a name that matches the beginning of the name of a processor. Not sure if `runmft` is ideal, but it seemed the simplest way for me to work around this without adding plenty of manual options only to the processors that shall receive the `--mft` option.
> Rename --mft to --runmft to avoid ambiguity

- Detectors/TOF/workflow/src/CompressedDecodingTask.cxx
@noferini @preghenella 
This fixes the problem raw->divits conversion leading to orbit in ``ReadoutWindowData`` vector jumping to 0 (leading to negative value in https://github.com/AliceO2Group/AliceO2/blob/c168b1a41c803004095d87d75249661eb5e4eaa3/Detectors/TOF/reconstruction/src/CTFCoder.cxx#L88, which crashes differential compression).
I consider this as a temporary fix only: I don't understand why do you need to complete the ``WindowFiller::mReadoutWindowData`` vector to have expected number of windows (if raw data decoding skips some window). But even if you need to do this, empty slots with meaningful BC/Orbit identifiers must be filled during data decoding rather than before postData. As it is now, you are not guaranteed to have a complete vector for all orbits of the TF with 3 …
> Temp.fix for TOF raw->digit orbit reset to 0 (O2-1633)

- Framework/Core/src/DataProcessingDevice.cxx
Apparently triggers a state machine transition on linux.
> DPL: force ignore SIGWINCH

- Framework/Core/include/Framework/ServiceRegistry.h
- Framework/Core/src/CommonServices.cxx
- Framework/Core/test/test_Services.cxx
Fixes issue where --configuration option was ignored.
> DPL: fix ServiceRegistry::active method when service is just declared (O2-1638)

- GPU/GPUTracking/Global/GPUChainTracking.cxx
@davidrohr With this fix the cluster finder should send mc labels again.
> TPCClusterFinder: Fix mc label propagation.

- CODEOWNERS
- Utilities/rANS/include/rANS/Decoder.h
- Utilities/rANS/include/rANS/FrequencyTable.h
- Utilities/rANS/include/rANS/LiteralDecoder.h
- Utilities/rANS/include/rANS/LiteralEncoder.h
- Utilities/rANS/include/rANS/internal/SymbolStatistics.h
- Utilities/rANS/include/rANS/internal/SymbolTable.h
- Utilities/rANS/src/SymbolStatistics.cxx
- Utilities/rANS/test/test_ransEncodeDecode.cxx
Optimized, sparse storage format for SymbolTable. Reduces storage
requirements by up to factor 5x and optimizes cache performance of
encoder/ decoder.
> [rANS] Memory optimized sparse SymbolTable

- Detectors/TPC/reconstruction/src/GPUCATracking.cxx
@shahor02 @fweig : This should fix the TPC MC label creation from digits without any restrictions on zero suppression settings.
> TPC: Fix digit MC labels out of sync after zero supression

- Detectors/TPC/reconstruction/src/GPUCATracking.cxx
- Detectors/TPC/workflow/src/CATrackerSpec.cxx
@fweig : With this PR the tpc workflow can forward both the zs pages and digits + digit mc labels to the tpc clusterizer, as we discussed to create cluster mc labels also in case of zs input (Needs #4140 to work properly).
However, right now there are no TPC cluster MC labels created. I believe we just never tried to do it in this setup, but if I understand the design correctly, we could just run the MC label flattener on the digits and digits MC labels input and then create the MC labels as we do for digits.
Command to run in this mode:
```
o2-tpc-reco-workflow -b --infile tpcdigits.root --output-type clusters,tracks --ca-clusterer --tpc-zs-on-the-fly
```
Could you have a look, and if possible fix that up in a separate PR.
> TPC: Forward digits and digit MC labels to tracking in case of tpc-zs-on-the-fly, so we can create cluster MC labels

- DataFormats/Detectors/Common/include/DetectorsCommonDataFormats/EncodedBlocks.h
- Detectors/FIT/FT0/reconstruction/include/FT0Reconstruction/CTFCoder.h
- Detectors/FIT/FV0/reconstruction/include/FV0Reconstruction/CTFCoder.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/CTFCoder.h
- Detectors/TOF/reconstruction/include/TOFReconstruction/CTFCoder.h
- Detectors/TPC/reconstruction/include/TPCReconstruction/CTFCoder.h
- Utilities/rANS/include/rANS/Decoder.h
- Utilities/rANS/include/rANS/Encoder.h
- Utilities/rANS/include/rANS/internal/SymbolStatistics.h
- Utilities/rANS/include/rANS/internal/SymbolTable.h
- Utilities/rANS/include/rANS/rans.h
- Utilities/rANS/run/bin-encode-decode.cxx
the rescaling factor determines the precision of the rANS compression
algorithm SymbolTable and this it's compression efficiency and
performance.
Until now it had to be set manually. The parameter now has become
optional and the optimal precision is automatically estimated based on
the FrequencyTable that is used to compress the data.
> [rANS] automatic calculation of rescaling factor

- Framework/Core/include/Framework/HistogramRegistry.h
- Framework/Core/test/benchmark_HistogramRegistry.cxx
- Framework/Core/test/test_HistogramRegistry.cxx
Ciao @ktf,
this is a small introductory PR to allow for using different histograms in the histogram registry.
THn/THnSparse have different set of arguments in the constructors so I'd need to add HistogramConfigSpec specialization for these. TH1/2/3 can also accept different arguments (arrays of bins instead of min and max values), so that would require yet another Config specializations.
Or perhaps we should not store histogram-dependent values in a generic type?
> DPL Analysis: Extended histogram registry to use TH2 and TH3

- Framework/Core/src/BoostOptionsRetriever.cxx
- Framework/Core/src/DeviceSpecHelpers.cxx
@ktf for me this solves the problem of greedy parsing: before in the chain
```
`o2-raw-file-reader-workflow --input-conf ITSraw.cfg  | o2-itsmft-stf-decoder-workflow  --old-format --shm-segment-size 16000000000 --decoder-verbosity 2 --run | tee xx.log
````
the  ``--run`` was interpreted as ``--runmft`` option set (though I thought the ambiguity should lead to an exception), because both are defined for the workflow:
````
shahoian@alicers02:/data2/itsdata/ML$  o2-itsmft-stf-decoder-workflow  -h
...
Executor options:
...
--run                                 run workflow merged so far
...
Global workflow options:
--runmft                              source detector is MFT (default ITS)
...
````
With this PR the confusion is gone.
> Set boost parsing style explictily to exclude allow_guessing

- Framework/Core/include/Framework/Kernels.h
- Framework/Core/src/TableTreeHelpers.cxx
Fixes compilation with arrow 1.0 due to arrow/config.h not included through other arrow header and thus ARROW_VERSION nor being defined
> DPL: add missing include arrow/config.h

- Analysis/Tutorials/src/custom_index.cxx
- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/AnalysisTask.h
This allows using custom index tables as grouping tables based on their first column. Example custom_index.cxx updated with demonstration.
> DPL Analysis: grouping with index tables

- Detectors/ITSMFT/ITS/tracking/include/ITStracking/Tracker.h
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/Vertexer.h
- Detectors/ITSMFT/ITS/tracking/src/Tracker.cxx
@shahor02 @mpuccio @mconcas : This is an easy workaround for now to respect the logging level, if you are fine with it. It can be cleaned up further later on, but I didn't see an obvious solution since fair logger does not derrive from ostream, so I cannot replace the ostream variable with something fairlogger related.
An alternative would be to use boost null stream as ostream in case the debug level is below a certain threshold, but that would add a boost dependency which I wanted to avoid.
> ITS: Respect debug level for logging

- Analysis/DataModel/include/PID/BetheBloch.h
- Analysis/DataModel/include/PID/TOFReso.h
- Analysis/DataModel/include/PID/TPCReso.h
- Analysis/DataModel/include/PIDBase/ParamBase.h
- Analysis/DataModel/src/handleParamTPCBetheBloch.cxx
- Analysis/Tasks/pidTOF.cxx
- Analysis/Tasks/spectraTOF.cxx
- Analysis/Tasks/spectraTPC.cxx
Updates to TOF and TPC tasks
- TPC task
- Update TPC qa plots
- Using log binning for momentum
- Using TPC momentum instead of momentum at vertex
- Add TPC with TOF plots
-  TOF task
- Extend QA plots for TOF PID
- add event wide info
- using different tasks for different observables
- Change TOF task names
Remove verbosity in TOF PID table filler
Add TPC spectra task
Remove useless verbosity
Add param setter from the index
Add possibility to read param from file in TPC param handler
> Update in PID tasks and handlers of PID param

- Analysis/Tutorials/src/aodwriter.cxx
- Framework/Core/include/Framework/DataInputDirector.h
- Framework/Core/src/DataInputDirector.cxx
- Framework/Core/test/test_DataInputDirector.cxx
. a std::vector<std::string> is used to provide the list of input data files
. ATTENTION if this is used together with the internal-dpl-aod-reader command line option json-file:
the data files specified as item "resfiles" in the json file will be added to the list of input data files
> DataInputDirector constructor with a vector of data files and input

- Common/SimConfig/include/SimConfig/SimConfig.h
- Common/SimConfig/src/SimConfig.cxx
- Generators/CMakeLists.txt
- Generators/include/Generators/GeneratorHepMCParam.h
- Generators/share/egconfig/pythia8_userhooks_charm.C
- Generators/src/GeneratorFactory.cxx
- Generators/src/GeneratorHepMC.cxx
- Generators/src/GeneratorHepMCParam.cxx
- Generators/src/GeneratorsLinkDef.h
- dependencies/O2SimulationDependencies.cmake
- doc/DetectorSimulation.md
- prodtests/embedding_benchmark.sh
- run/CMakeLists.txt
- run/SimExamples/Adaptive_Pythia8/run.sh
- run/SimExamples/AliRoot_Hijing/run.sh
- run/SimExamples/HepMC_STARlight/run.sh
- run/SimExamples/Jet_Embedding_Pythia8/pythia8_userhooks_jets.macro
- run/SimExamples/Jet_Embedding_Pythia8/run.sh
- run/SimExamples/Signal_ImpactB/run.sh
This PR brings the following features
* clean up the temporary solution to transition to the new HepMC3 version
* HepMC is now configured via `ConfigrableParam` 
* removed the HepMC filename setup via `o2-sim` command line
* updated simulation example
* and documentation
> HepMC via configurable params, cleanup of deprecated old HepMC version

- Analysis/Tutorials/src/jetAnalysis.cxx
Access the tracks constituting a jet with the indirection through the index table. Short of the integration of the indices in the jet table, this is probably what we should advertise as access to jet constituents.
@nzardosh @aalkin Could you have a look if that makes sense to you?
> Add access to jet constituents

- Analysis/Tutorials/src/custom_index.cxx
- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/AnalysisTask.h
- Framework/Core/include/Framework/TableBuilder.h
- Framework/Core/src/TableBuilder.cxx
- Framework/Core/test/test_IndexBuilder.cxx
Index can now be built with two policies:
* Exclusive: each index row needs to have _all_ entries available
* Sparse: index is isomorphic to the base (i.e. first) table it refers to (e.g. Collisions, see custom_index.cxx)
Example updated to demonstrate how to access indexed information and how the entry validity can be checked when the sparse policy is used. 
Index building callbacks moved from TableBuilder.h to AnalysisTask.h
> DPL Analysis: introduce policies for index building

- GPU/GPUTracking/TPCClusterFinder/MCLabelAccumulator.cxx
@davidrohr This is a quick fix that should save some more memory when propagating mc labels.
> TPCClusterFinder: Reduce memory usage on MC propagation.

- Detectors/TPC/reconstruction/src/GPUCATracking.cxx
- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- GPU/GPUTracking/Base/GPUReconstruction.cxx
- GPU/GPUTracking/Interface/GPUO2InterfaceConfiguration.h
@shahor02 : With this PR, I can process my dataset with mc labels with 16 GB of memory.
I think I can perhaps still save ~1 GB by optimizing the tracking, but that will be more or less it from the reconstruction side.
On top, I think we might waste quite some memory if the MC label container is serialized and copied during deserialization but I am not yet sure about this.
> More host memory optimizations for TPC workflow

- prodtests/sim_challenge.sh
apply shared mem segement size to all workflows. Fixes https://alice.its.cern.ch/jira/browse/O2-1657.
> Fix crash in TPC reco workflow

- Detectors/ITSMFT/common/simulation/src/DigiParams.cxx
do in only once run-time parameters are set
> ITS DigiParam: suppress initialization from c-tor

- DataFormats/Detectors/Common/include/DetectorsCommonDataFormats/EncodedBlocks.h
- DataFormats/Detectors/TPC/include/DataFormatsTPC/CTF.h
- DataFormats/Detectors/TPC/src/DataFormatsTPCLinkDef.h
- Detectors/CTF/workflow/include/CTFWorkflow/CTFWriterSpec.h
- Detectors/TPC/reconstruction/include/TPCReconstruction/CTFCoder.h
- Detectors/TPC/reconstruction/src/CTFCoder.cxx
- Detectors/TPC/workflow/src/EntropyEncoderSpec.cxx
- Utilities/rANS/include/rANS/FrequencyTable.h
- Utilities/rANS/include/rANS/internal/SymbolStatistics.h
@davidrohr Indeed, I see 5% improvement in TPC CTF size with merged columns. Decoding time does not change (10.6s for my 120 pbpb events at 2.4GHz cpu clock), encoding time improves by 22%! (from 5.1 to 3.9 s). So, apparently encoding less data wins over doing this with larger dictionary.
I am enabling the columns merging by default. Merging can be disabled by passing option
``--no-ctf-columns-combining`` to tpc workflow (this is an option of ``tpc-entropy-encoder`` processor).
The used option is stored in the CTF and the dictionary. When encoding with external dictionary the flag extracted from it will define if the columns are merged or not (irrespectively of the provided option).
An attempt of decoding with inconsistent flags of stored in data and dictionary will throw an exception. …
> Option (Def=on) to merge in the TPC CTF correlated columns (+misc fixes)

- Detectors/EMCAL/simulation/include/EMCALSimulation/RawWriter.h
- Detectors/EMCAL/simulation/src/RawWriter.cxx
The mapping handler takes care of caching the mapping
and providing the correct channel mapping for a given
DDL ID. Replacing internal caching which was buggy.
> [EMCAL-610] Use mapping handler to access channel address mapping

- Detectors/FIT/FT0/reconstruction/CMakeLists.txt
- Detectors/FIT/FT0/reconstruction/include/FT0Reconstruction/InteractionTag.h
- Detectors/FIT/FT0/reconstruction/src/InteractionTag.cxx
- Detectors/GlobalTracking/CMakeLists.txt
- Detectors/GlobalTracking/include/GlobalTracking/MatchTPCITS.h
- Detectors/GlobalTracking/include/GlobalTracking/MatchTPCITSParams.h
- Detectors/GlobalTracking/src/MatchTPCITS.cxx
- Detectors/GlobalTrackingWorkflow/include/GlobalTrackingWorkflow/MatchTPCITSWorkflow.h
- Detectors/GlobalTrackingWorkflow/include/GlobalTrackingWorkflow/TPCITSMatchingSpec.h
- Detectors/GlobalTrackingWorkflow/src/MatchTPCITSWorkflow.cxx
- Detectors/GlobalTrackingWorkflow/src/TPCITSMatchingSpec.cxx
- Detectors/GlobalTrackingWorkflow/src/tpcits-match-workflow.cxx
- Detectors/Vertexing/CMakeLists.txt
- Detectors/Vertexing/include/DetectorsVertexing/PVertexer.h
- Detectors/Vertexing/include/DetectorsVertexing/PVertexerParams.h
- Detectors/Vertexing/src/PVertexer.cxx
* Extract FT0 interaction selection params to separate configurable class 
``o2::ft0::InteractionTag`` configurable param to values of FT0 trigger selection as interaction tag (A+C amplitude threshold, time bias correction (ns) to match to other detectors.
* Providing option ``--use-ft0`` option to ``o2-tpcits-match-workflow`` will add FIT (currently FT0 only) recpoints input, which can be used either for validation or for selection of matching candidates. Option provided via MatchITSTPCParams configurable param:
``--configKeyValues "tpcitsMatch.validateMatchByFIT=Disable"`` will force to ignore FT0 data
``--configKeyValues "tpcitsMatch.validateMatchByFIT=Prefer"`` will affect comparison of matching candidates: the one with
FIT match will be preferred irrespectively to chi2 of its …
> Optional use of FT0 time for ITS/TPC match selection or validation 

- Detectors/ITSMFT/ITS/tracking/src/Tracker.cxx
Hi @shahor02,
sorry that it took so long, the bug was algorithmic. In the previous version it was implicitly assumed that the innermost point of the track was at the innermost layer, now this is not anymore the case.
This fixes the processing of the events you sent me. Let me know if there are further crashes.
Cheers,
Max
> [ITSCA] Level 1 marks the end of the road

- DataFormats/Detectors/ITSMFT/ITS/include/DataFormatsITS/TrackITS.h
- Detectors/GlobalTracking/src/GlobalTrackingLinkDef.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CookedTracker.h
- Detectors/ITSMFT/ITS/tracking/src/Tracker.cxx
- Detectors/ITSMFT/ITS/workflow/include/ITSWorkflow/RecoWorkflow.h
- Detectors/ITSMFT/ITS/workflow/include/ITSWorkflow/TrackerSpec.h
- Detectors/ITSMFT/ITS/workflow/src/RecoWorkflow.cxx
- Detectors/ITSMFT/ITS/workflow/src/TrackerSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/its-reco-workflow.cxx
- GPU/GPUTracking/Global/GPUChainITS.cxx
@mpuccio, @iouribelikov : I've added the extra passes code as it is in https://github.com/AliceO2Group/AliceO2/blob/9f587108fe0e6eaabf8c642cc3ea81443ec7ad28/macro/run_trac_ca_its.C#L187-L195 to CA TrackerSpec, activated by ``--async-phase`` option. Works fine and fast but eventually this need to be converted to something configurable.
Also fixed the cluster id's extraction from the tracker.
I've suppressed the ROFrame and mass data members of the TrackITS as they are not used and added PID and contributing layers pattern.
> Add async. reco mode to ITS workflow with ca-tracker + misc.fixes

- Detectors/GlobalTracking/include/GlobalTracking/MatchTPCITS.h
- Detectors/GlobalTracking/src/MatchTPCITS.cxx
- Detectors/GlobalTrackingWorkflow/src/TPCITSMatchingSpec.cxx
- Detectors/ITSMFT/ITS/macros/test/CheckTracks.C
- Detectors/ITSMFT/ITS/macros/test/DisplayTrack.C
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CookedTracker.h
- Detectors/ITSMFT/ITS/reconstruction/src/CookedTracker.cxx
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/Tracker.h
- Detectors/ITSMFT/ITS/tracking/src/Tracker.cxx
- Detectors/ITSMFT/ITS/workflow/include/ITSWorkflow/TrackReaderSpec.h
- Detectors/ITSMFT/ITS/workflow/src/CookedTrackerSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/TrackWriterSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/TrackerSpec.cxx
- Detectors/TPC/reconstruction/src/GPUCATracking.cxx
- Detectors/TPC/workflow/include/TPCWorkflow/TrackReaderSpec.h
- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- Detectors/TPC/workflow/src/RecoWorkflow.cxx
- Detectors/TPC/workflow/src/TrackReaderSpec.cxx
- GPU/GPUTracking/Interface/GPUO2InterfaceConfiguration.h
- macro/checkTOFMatching.C
- macro/runCATrackingClusterNative.C
- macro/run_trac_ca_its.C
- macro/run_trac_its.C
Since tracks have just one label, there is no point in using MCTruthContainer (not browsable in the tree, non-messageable and occupy more memory) for them.
> Use vector instead of MCTruthContainer for ITS,TPC tracks

- Detectors/EMCAL/base/include/EMCALBase/ClusterFactory.h
- Detectors/EMCAL/base/src/ClusterFactory.cxx
The indices aren't modified, so const is appropriate. Further, this
makes the interface more consistent for converting clusters from the
clusterizer into analysis clusters.
@mfasDa
> [EMCAL-651] Add const for cell indices in cluster

- DataFormats/Detectors/ITSMFT/MFT/include/DataFormatsMFT/TrackMFT.h
- Detectors/ITSMFT/MFT/tracking/include/MFTTracking/Cluster.h
- Detectors/ITSMFT/MFT/tracking/include/MFTTracking/ROframe.h
- Detectors/ITSMFT/MFT/tracking/include/MFTTracking/TrackCA.h
- Detectors/ITSMFT/MFT/tracking/include/MFTTracking/Tracker.h
- Detectors/ITSMFT/MFT/tracking/src/IOUtils.cxx
- Detectors/ITSMFT/MFT/tracking/src/TrackFitter.cxx
- Detectors/ITSMFT/MFT/tracking/src/Tracker.cxx
- Detectors/ITSMFT/MFT/workflow/src/TrackerSpec.cxx
Main changes:
- modify the extraction and the writing of the external indices of the clusters of a track
- bug fix in the Fast Circle Fit function
- a temporary extraction of cluster errors from the patterns dictionary (ITS fix expected)
- some cosmetics in the notations
> MFT: fill vector tree with cluster external indices

- Framework/Core/src/AODReaderHelpers.cxx
The CaloTrigger was wrongly assigned to the calo cells. Credit for
finding the fix to Markus
> [EMCAL-668] Fix calo trigger AOD metadata

- Detectors/EMCAL/simulation/src/RawWriter.cxx
The digitizer creates time samples however it stores them in
ns. The time needs to be converted to sample ID dividing by
the length of the time sample.
> [EMCAL-610] Fix handling of the time sample

- Detectors/EMCAL/base/include/EMCALBase/RCUTrailer.h
- Detectors/EMCAL/base/src/Mapper.cxx
- Detectors/EMCAL/simulation/src/RawWriter.cxx
- Fix buffer overrun in findBunches leading to segfault
- In getting online ID (SRU ID in supermodule had to be
scaled with the number of supermodules in order to get
the DDL ID)
- Convert trailer size as size in 32bit words to size in byte in
carryOverMethod in order to calculate properly the
payload size
> [EMCAL-610] Fix segfault in Raw creator
