- devices/aliceHLTwrapper/Component.cxx
- devices/aliceHLTwrapper/Component.h
- devices/aliceHLTwrapper/MessageFormat.cxx
- devices/aliceHLTwrapper/MessageFormat.h
- devices/aliceHLTwrapper/SystemInterface.cxx
- devices/aliceHLTwrapper/SystemInterface.h
- devices/aliceHLTwrapper/WrapperDevice.cxx
- devices/aliceHLTwrapper/WrapperDevice.h
- devices/aliceHLTwrapper/aliceHLTWrapper.cxx
- devices/aliceHLTwrapper/cluster-relay-to-tracker.sh
- devices/aliceHLTwrapper/runComponent.cxx
> Updated formatting and naming

- devices/aliceHLTwrapper/aliceHLTWrapper.cxx
backward compatible implementation using the interface version number
> changes according to upcoming extension of the FairMQStateMachine interface 

- devices/hough/CMakeLists.txt
- devices/hough/README.md
- devices/hough/runHough.cxx
Added a method to produce a graphics file that depicts the coordinates of the loaded clusters
Bugfix: Fixed loading of the data files into memory
> Create a pdf with the cluster coordinates + bugfixes

- devices/aliceHLTwrapper/CMakeLists.txt
- devices/aliceHLTwrapper/Component.cxx
- devices/aliceHLTwrapper/EventSampler.cxx
- devices/aliceHLTwrapper/EventSampler.h
- devices/aliceHLTwrapper/MessageFormat.cxx
- devices/aliceHLTwrapper/MessageFormat.h
- devices/aliceHLTwrapper/aliceHLTEventSampler.cxx
My git clone was in a strange state, even though I had updated all remotes. I took the aliceHLTWrapper.cxx file as a template for the new executable, and introduced the same error once again. Sorry for that.
2nd trial, the new functionality allows
- synchronization of data publishers
- latency measurement
- consitency checks for aggregated timeframe parts on the EPN
> New functionality: EventSampler for HLT event header, 2nd trial

- devices/aliceHLTwrapper/launch-flp-epn.sh
The  configuration is tailored to the HLT dev cluster, will be changed in the future
> Start script for the FLP to EPN configuration

- Base/CMakeLists.txt
- Data/CMakeLists.txt
- MathUtils/CMakeLists.txt
- field/CMakeLists.txt
- its/Detector.cxx
- its/Detector.h
- o2cdb/ConditionId.cxx
- passive/CMakeLists.txt
- passive/GeoCave.h
Small modification needed for runing with ROOT6
(remove Cint from required libraries) and add std at few places
> Run with Root 6

- Base/Detector.cxx
- CMakeLists.txt
- its/Detector.cxx
- its/UpgradeSegmentationPixel.h
- its/UpgradeV1Layer.h
- macro/run_sim.C
Small issues with the namespaces and ROOT 6. 
some bugs where not seen by ROOT 5.
> Small correction needed to run with Root6

- devices/aliceHLTwrapper/aliceHLTEventSampler.cxx
- devices/aliceHLTwrapper/aliceHLTWrapper.cxx
- devices/flp2epn-distributed/runO2Prototype/runEPNReceiver.cxx
- devices/flp2epn-distributed/runO2Prototype/runFLPSender.cxx
- devices/flp2epn-distributed/runO2Prototype/runFLPSyncSampler.cxx
Now with respect to dev branch... The fix takes into account the new namespece key_value in DDS
> Change in the DDS namespaces

- devices/aliceHLTwrapper/CMakeLists.txt
- devices/flp2epn-distributed/CMakeLists.txt
- devices/flp2epn-dynamic/CMakeLists.txt
- devices/flp2epn/CMakeLists.txt
- devices/roundtrip/CMakeLists.txt
Include dependencies for the new FairMQLogger (with backward compatibility check).
> Include dependencies for the new FairMQLogger (with backward compatibility check).

- devices/flp2epn-distributed/EPNReceiver.cxx
- devices/flp2epn-distributed/EPNReceiver.h
- devices/flp2epn-distributed/FLPSender.cxx
- devices/flp2epn-distributed/FLPSender.h
- devices/flp2epn-distributed/FLPSyncSampler.h
- devices/flp2epn-distributed/run/runEPNReceiver.cxx
- devices/flp2epn-distributed/run/runFLPSender.cxx
- devices/flp2epn-distributed/run/runFLPSyncSampler.cxx
- devices/flp2epn-distributed/runO2Prototype/runEPNReceiver.cxx
- devices/flp2epn-distributed/runO2Prototype/runFLPSender.cxx
- devices/flp2epn-distributed/runO2Prototype/runFLPSyncSampler.cxx
> Improve comments & doxygen of flp2epn-distributed

- devices/flp2epn-distributed/FLPSender.cxx
> Adapt to the changed API n FairMQ

- Base/Detector.cxx
- Base/TrackReference.cxx
- gconfig/DecayConfig.C
- gconfig/SetCuts.C
- gconfig/UserDecay.C
- itsmft/its/Detector.cxx
- itsmft/its/GeometryHandler.cxx
- tpc/Detector.cxx
Use the static TVirualMC::GetMC() method instead of the global pointer
> Remove gMC 

- Detectors/TPC/simulation/include/BoxClusterer.h
- Detectors/TPC/simulation/src/BoxClusterer.cxx
I had to add forward declaration of TClonesArray in the header file and to include TClonesArray.h in the implementation file to compile with the master of Root6.
> Patch of Jens changes

- Detectors/ITSMFT/MFT/base/README.md
First MFT commit for testing the workflow.
> Readme for MFT base (just testing)

- Detectors/ITSMFT/ITS/simulation/include/DigitizerTask.h
- Detectors/TPC/simulation/include/DigitizerTask.h
Digitization Task has the same pre-processor definition in TPC and ITS
> TPC digitization Task error

- config/rootmanager.dat
> Rename output tree

- Detectors/ITSMFT/MFT/reconstruction/CMakeLists.txt
I cannot find the file in the current tip of the dev branch. Am I missing something trivial?
> Comment out installation of missing file

- Detectors/Base/CMakeLists.txt
- Detectors/Base/include/DetectorsBase/Constants.h
- Detectors/Base/include/DetectorsBase/Track.h
- Detectors/Base/include/DetectorsBase/Utils.h
- Detectors/Base/src/BaseLinkDef.h
- Detectors/Base/src/Track.cxx
- Detectors/ITSMFT/ITS/reconstruction/CMakeLists.txt
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CATracker.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CATrackingStation.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CAaux.h
- Detectors/ITSMFT/ITS/reconstruction/src/CATracker.cxx
- Detectors/ITSMFT/ITS/reconstruction/src/CATrackingStation.cxx
- Detectors/ITSMFT/ITS/reconstruction/src/CAaux.cxx
- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/Point.h
- cmake/O2Dependencies.cmake
These commits port the ITS Cellular Automaton tracker in the Alice O2 repository. They contain also a first implementation of the track parametrisation (by @shahor02) and some general utilities and constants for the tracking.
> Porting of the ITS CA tracker to AliceO2

- Utilities/DataCompression/include/DataCompression/HuffmanCodec.h
- Utilities/DataCompression/test/DataGenerator.h
- Utilities/DataCompression/test/Fifo.h
- Utilities/DataCompression/test/test_datagenerator.cxx
- Utilities/DataCompression/test/test_fifo.cxx
- Utilities/DataCompression/test/test_huffmancodec.cxx
Some tools for unit tests
- data generator for random data following a given probability distribution
- thread safe FIFO
Also a small addition to make the underlying coding model of the HuffmanCodec available to generic algorithms.
> Dev datacompression: tools for testing with random data

- Detectors/Base/include/DetectorsBase/Track.h
- Detectors/Base/include/DetectorsBase/Utils.h
- Detectors/Base/src/BaseLinkDef.h
- Detectors/Base/src/Track.cxx
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CATracker.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CATrackingStation.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CAaux.h
- Detectors/ITSMFT/ITS/reconstruction/src/CATracker.cxx
- Detectors/ITSMFT/ITS/reconstruction/src/CAaux.cxx
Avoid C functions, use ISO C++ when possible, remove old reinterpret_cast stuff...
Thanks to @shahor02 for the base class optimisation trick.
> More C++ friendly track class

- Common/Field/CMakeLists.txt
- Common/Field/include/Field/MagFieldContFact.h
- Common/Field/include/Field/MagFieldFact.h
- Common/Field/include/Field/MagFieldParam.h
- Common/Field/include/Field/MagneticField.h
- Common/Field/src/FieldLinkDef.h
- Common/Field/src/MagFieldContFact.cxx
- Common/Field/src/MagFieldFact.cxx
- Common/Field/src/MagFieldParam.cxx
- Common/Field/src/MagneticField.cxx
- Detectors/ITSMFT/ITS/macros/test/run_sim.C
- Detectors/ITSMFT/ITS/macros/test/run_trac.C
- cmake/O2Dependencies.cmake
Hi @MohammadAlTurany , here is everything squashed to single commit. @iouribelikov , I've modified the ITS test macros to use proper field: now it is set in run_sim and propagated to all other stages via parameter/factory in FairRuntimeDb.
> Alice B-field compies with FairField mechanism

- macro/CMakeLists.txt
- macro/SetIncludePath.C
- macro/load_all_libs.C
- macro/run_clus_its.C
- macro/run_clus_its.sh
- macro/run_clusterer.C
- macro/run_digi_its.C
- macro/run_digi_its.sh
- macro/run_digi_tpc.C
- macro/run_sim.C
- macro/run_sim_its.C
- macro/run_sim_its.sh
- macro/run_sim_mft.C
- macro/run_sim_tpc.C
- macro/run_trac_its.C
- macro/run_trac_its.sh
- TPC and ITS are now tested separately, 
- The full chain of ITS is now added to the CTEST
- Tests run for G3 and G4
> Re-Arrange the test macros and add new functional tests

- .gitignore
Used by vim YouCompleteMe and other IDEs integrations
> Do not track compile_commands.json and YCM config

- DataFormats/Headers/CMakeLists.txt
- DataFormats/Headers/include/Headers/TimeStamp.h
- DataFormats/Headers/test/testTimeStamp.cxx
Also some fixes for the get() function to return the correct
duration format.
> Compiling TimeStamp implementation and unit test

- CCDB/src/ConditionsMQClient.cxx
- Detectors/ITSMFT/MFT/reconstruction/include/MFTReconstruction/devices/TaskProcessor.tpl
- Detectors/ITSMFT/MFT/reconstruction/src/devices/FileSink.cxx
- Detectors/ITSMFT/MFT/reconstruction/src/devices/Sampler.cxx
- Examples/flp2epn-distributed/src/EPNReceiver.cxx
- Examples/flp2epn-distributed/src/FLPSender.cxx
- Examples/flp2epn-distributed/src/FLPSyncSampler.cxx
- Examples/flp2epn/src/O2FLPex.cxx
- Utilities/DataFlow/src/HeartbeatSampler.cxx
- Utilities/DataFlow/src/SubframeBuilderDevice.cxx
- Utilities/O2MessageMonitor/src/O2MessageMonitor.cxx
- Utilities/Publishers/src/DataPublisherDevice.cxx
> Use FairMQDevice::GetConfig() getter everywhere

- DataFormats/Headers/include/Headers/SubframeMetadata.h
- Utilities/DataFlow/CMakeLists.txt
- Utilities/DataFlow/include/DataFlow/EPNReceiverDevice.h
- Utilities/DataFlow/include/DataFlow/FLPSenderDevice.h
- Utilities/DataFlow/include/DataFlow/HeartbeatSampler.h
- Utilities/DataFlow/include/DataFlow/SubframeBuilderDevice.h
- Utilities/DataFlow/include/DataFlow/TimeframeValidatorDevice.h
- Utilities/DataFlow/run/CreateSetup.py
- Utilities/DataFlow/run/confComplexSetup.json
- Utilities/DataFlow/run/confComplexSetup2.json
- Utilities/DataFlow/run/startBasicSetup.sh
- Utilities/DataFlow/run/startComplexSetup.sh
- Utilities/DataFlow/run/startComplexSetup2.sh
- Utilities/DataFlow/src/EPNReceiverDevice.cxx
- Utilities/DataFlow/src/FLPSenderDevice.cxx
- Utilities/DataFlow/src/HeartbeatSampler.cxx
- Utilities/DataFlow/src/SubframeBuilderDevice.cxx
- Utilities/DataFlow/src/TimeframeValidatorDevice.cxx
- Utilities/DataFlow/src/runEPNReceiver.cxx
- Utilities/DataFlow/src/runFLPSender.cxx
- Utilities/DataFlow/src/runHeartbeatSampler.cxx
- Utilities/DataFlow/src/runSubframeBuilderDevice.cxx
- Utilities/DataFlow/src/runTimeframeValidatorDevice.cxx
- Utilities/Publishers/include/Publishers/DataPublisherDevice.h
- Utilities/Publishers/src/DataPublisherDevice.cxx
Do not merge. This is just to allow people (e.g. @matthiasrichter ) to comment on the progress so far.
Things to fix:
> Initial attempt at merging the work on the TimeFrame done so far

- Detectors/Base/CMakeLists.txt
- Detectors/Base/include/DetectorsBase/BaseHits.h
- Detectors/Base/src/BaseLinkDef.h
- Detectors/Base/test/testBasicHits.cxx
- cmake/O2Dependencies.cmake
* correcting CMakeLists file (list BaseHits.h header)
* fix BaseLinkDef.h
* add unit test checking the streaming of hits objects
> Make BasicHits ROOT streamable

- Detectors/CMakeLists.txt
- Detectors/EMCAL/CMakeLists.txt
- Detectors/EMCAL/base/CMakeLists.txt
- Detectors/EMCAL/base/include/EMCALBase/Digit.h
- Detectors/EMCAL/base/include/EMCALBase/Point.h
- Detectors/EMCAL/base/src/Digit.cxx
- Detectors/EMCAL/base/src/EMCALBaseLinkDef.h
- Detectors/EMCAL/base/src/Point.cxx
- Detectors/EMCAL/simulation/CMakeLists.txt
- Detectors/EMCAL/simulation/include/EMCALSimulation/Detector.h
- Detectors/EMCAL/simulation/src/Detector.cxx
- Detectors/EMCAL/simulation/src/EMCALSimulationLinkDef.h
- cmake/O2Dependencies.cmake
- Generate repository structure according to TPC
- Define structures for EMCAL simulation pint and digit:
Structure of teh simulation point extracted from
AliEMCALHit and converted in order to be compatible
with FairMCPoint
- Add skeleton for EMCAL Detector simulation:
Only function declaration (+ empty definition) and I/O,
not yet functional
> Initial commit for EMCAL package in O2

- Detectors/EMCAL/base/include/EMCALBase/Point.h
- Detectors/EMCAL/base/src/Point.cxx
- Detectors/EMCAL/simulation/include/EMCALSimulation/Detector.h
- Detectors/EMCAL/simulation/src/Detector.cxx
- cmake/O2Dependencies.cmake
- Based on new base class for Hits in O2 AliceO2::Base::BasicXYZEHit
with data type float
- Make constructors inline
> Refactoring EMCAL simulation point

- Detectors/EMCAL/base/CMakeLists.txt
- Detectors/EMCAL/base/include/EMCALBase/Hit.h
- Detectors/EMCAL/base/src/EMCALBaseLinkDef.h
- Detectors/EMCAL/base/src/Hit.cxx
- Detectors/EMCAL/simulation/include/EMCALSimulation/Detector.h
- Detectors/EMCAL/simulation/src/Detector.cxx
Changing name of the MC hit class for EMCAL from point
to hit according to #319
> Changing name of MC hit class from Point to Hit

- Common/Field/include/Field/MagFieldContFact.h
- Common/Field/include/Field/MagFieldFact.h
- Common/Field/include/Field/MagFieldParam.h
- Common/Field/include/Field/MagneticField.h
- Common/Field/include/Field/MagneticWrapperChebyshev.h
- Common/Field/src/FieldLinkDef.h
- Common/Field/src/MagFieldContFact.cxx
- Common/Field/src/MagFieldFact.cxx
- Common/Field/src/MagFieldParam.cxx
- Common/Field/src/MagneticField.cxx
- Common/Field/src/MagneticWrapperChebyshev.cxx
- Common/MathUtils/include/MathUtils/Chebyshev3D.h
- Common/MathUtils/include/MathUtils/Chebyshev3DCalc.h
- Common/MathUtils/src/Chebyshev3D.cxx
- Common/MathUtils/src/Chebyshev3DCalc.cxx
- Common/MathUtils/src/MathUtilsLinkDef.h
- Detectors/ITSMFT/ITS/reconstruction/src/CookedTracker.cxx
- Detectors/ITSMFT/MFT/simulation/src/Detector.cxx
- macro/compare_cluster.C
- macro/run_clus_its.C
- macro/run_clus_tpc.C
- macro/run_digi.C
- macro/run_digi_its.C
- macro/run_digi_tpc.C
- macro/run_reco_mft.C
- macro/run_sim.C
- macro/run_sim_its.C
- macro/run_sim_mft.C
- macro/run_sim_tpc.C
- macro/run_trac_its.C
1) o2::Field -> o2::field and o2::MathUtils -> o2::mathUtils renaming
2) Field maps rewritten with o2: namespaces instead of AliceO2 (binary:  I consider this as temporary solution: eventually this file should go wherever all binary files will go)
> Fixes for namespace starting with lowercase change

- macro/run_sim_its_ALP3.C
Updated macro based on existing run_sim_its.C but with updated parameters fro pALPIDE3 chip.
> New macro with updated parameters for pALPIDE3 chip.

- CMakeLists.txt
- cmake/checks/cxx14-test-aggregate-initialization.cxx
- cmake/checks/cxx14-test-binary-literals.cxx
- cmake/checks/cxx14-test-generic-lambda.cxx
- cmake/checks/cxx14-test-make_unique.cxx
- cmake/checks/cxx14-test-user-defined-literals.cxx
- cmake/modules/CheckCXX14Features.cmake
This should be OK to merge since alidist master now contains default gcc6 support.
> first version of C++14 checks in cmake

- Detectors/TPC/base/include/TPCBase/CalDet.h
- Detectors/TPC/base/include/TPCBase/Sector.h
- Detectors/TPC/base/test/testTPCBase.cxx
- Detectors/TPC/simulation/include/TPCSimulation/Detector.h
- Detectors/TPC/simulation/include/TPCSimulation/DigitizerTask.h
- Detectors/TPC/simulation/src/Detector.cxx
- Detectors/TPC/simulation/src/DigitizerTask.cxx
* treat A+C sectors separately
* follow standard convention for sector counting
* use Sector::MAXSECTOR instead of hard coded number
* move of ToSector function to the Sector class
* added a unit test for Sectors
> Improved TPC sector treatment

- .gitignore
- DataFormats/Headers/include/Headers/SubframeMetadata.h
- DataFormats/TimeFrame/include/TimeFrame/TimeFrame.h
- Utilities/DataFlow/CMakeLists.txt
- Utilities/DataFlow/doc/TimeframeReaderDevice.1.in
- Utilities/DataFlow/doc/TimeframeWriterDevice.1.in
- Utilities/DataFlow/include/DataFlow/FakeTimeframeBuilder.h
- Utilities/DataFlow/include/DataFlow/FakeTimeframeGeneratorDevice.h
- Utilities/DataFlow/include/DataFlow/TimeframeParser.h
- Utilities/DataFlow/include/DataFlow/TimeframeReaderDevice.h
- Utilities/DataFlow/include/DataFlow/TimeframeWriterDevice.h
- Utilities/DataFlow/run/confFakeTimeframe.json
- Utilities/DataFlow/run/startTimeframeExample.sh
- Utilities/DataFlow/src/EPNReceiverDevice.cxx
- Utilities/DataFlow/src/FakeTimeframeBuilder.cxx
- Utilities/DataFlow/src/FakeTimeframeGeneratorDevice.cxx
- Utilities/DataFlow/src/TimeframeParser.cxx
- Utilities/DataFlow/src/TimeframeReaderDevice.cxx
- Utilities/DataFlow/src/TimeframeValidationTool.cxx
- Utilities/DataFlow/src/TimeframeValidatorDevice.cxx
- Utilities/DataFlow/src/TimeframeWriterDevice.cxx
- Utilities/DataFlow/src/runFakeTimeframeGeneratorDevice.cxx
- Utilities/DataFlow/src/runTimeframeReaderDevice.cxx
- Utilities/DataFlow/src/runTimeframeWriterDevice.cxx
- Utilities/DataFlow/test/test_TimeframeParser.cxx
- Utilities/Publishers/src/DataPublisherDevice.cxx
- cmake/O2Dependencies.cmake
- doc/o2-timeframe-file-format.1.in
Initial commit. Does not work yet, albeit it should compile.
> TimeframeReader and TimeframeWriter devices

- DataFormats/Headers/include/Headers/DataHeader.h
- DataFormats/Headers/src/DataHeader.cxx
- DataFormats/Headers/test/testDataHeader.cxx
This is mostly a cleanup of DataHeader & friends in preparation of a refactor. Lots of things simplify with C++14.
> Header modernization

- Utilities/DataFlow/CMakeLists.txt
- Utilities/DataFlow/doc/SubframeBuilderDevice.1.in
- Utilities/DataFlow/include/DataFlow/PayloadMerger.h
- Utilities/DataFlow/include/DataFlow/SubframeBuilderDevice.h
- Utilities/DataFlow/include/DataFlow/SubframeUtils.h
- Utilities/DataFlow/src/SubframeBuilderDevice.cxx
- Utilities/DataFlow/src/runSubframeBuilderDevice.cxx
- Utilities/DataFlow/test/test_PayloadMerger01.cxx
- Utilities/DataFlow/test/test_SubframeUtils01.cxx
- doc/o2.1.in
From your favourite coding duo, @matthiasrichter & @ktf
> Merge multiple HBFs into STF

- README.md
- Clarify the scope
- Fix the URLs
- Clarify the website link
- Remove duplicated information
> Clarifications and fixes for the README

- Detectors/Passive/include/DetectorsPassive/FrameStructure.h
- Detectors/Passive/src/FrameStructure.cxx
Fix the medium treatment for FRAME. Needed for order to properly see hits in the TOF.
> Provide proper media for the frame structure

- Detectors/TOF/prototyping/drawTOFgeometry.C
- Detectors/TOF/simulation/include/TOFSimulation/Detector.h
- Detectors/TOF/simulation/src/Detector.cxx
- Added new feature for TOF: Hit  (F. Noferini)
- Added macro to show TOF geometry
- All addition are formatted after clang-format
> Including new feature for TOF: Hit

- Utilities/Tools/README.md
> Fixing wrong aliBuild name

- Detectors/Base/CMakeLists.txt
- Detectors/Base/include/DetectorsBase/BaseCluster.h
- Detectors/Base/src/BaseCluster.cxx
- Detectors/Base/src/BaseLinkDef.h
- cmake/O2Dependencies.cmake
For alignment reason also the user managed bitmask and count fields are added
> Base cluster with position/error, sensor ID

- Detectors/Passive/CMakeLists.txt
- Detectors/Passive/include/DetectorsPassive/FrameStructureRun3.h
- Detectors/Passive/src/FrameStructureRun3.cxx
- Detectors/Passive/src/PassiveLinkDef.h
- cmake/O2Dependencies.cmake
- macro/build_geometry.C
Providing the frame structure imported from AliFRAMEv3
which should be the correct one for Run3.
At some moment this will likely replace the other frame structure
of FrameStructure.h
> Run3 updated frame structure

- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/V3Layer.h
- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
- Detectors/ITSMFT/ITS/simulation/src/V3Layer.cxx
- macro/run_sim_its_ALP3.C
The latest ITSU Outer Barrel description was ported from current AliRoot v2 version to O2 V3 version. This completes the porting of the sensitive volumes.
> Porting latest ITSU Outer Barrel geometry from AliRoot v2 to O2

- CMakeLists.txt
- Common/CMakeLists.txt
- Common/Configuration/CMakeLists.txt
- Common/Configuration/include/Configuration/SimConfig.h
- Common/Configuration/src/ConfigurationLinkDef.h
- Common/Configuration/src/SimConfig.cxx
- Common/Configuration/test/TestConfig.cxx
- Detectors/TOF/simulation/src/TOFSimulationLinkDef.h
- Detectors/TRD/simulation/src/Detector.cxx
- Detectors/TRD/simulation/src/TRDSimulationLinkDef.h
- Generators/src/GeneratorFromFile.cxx
- cmake/O2Dependencies.cmake
- macro/build_geometry.C
- macro/o2sim.C
- run/CMakeLists.txt
- run/o2sim.cxx
An O2 simulation executable allowing to play with different options/setups;
A basic configuration class for simulation taking arguments from the command line;
The latter is just a first step into this direction to allow some systematic studies (stepping, performance, cuts) and will be replaced by a more powerful mechanism at some stage.
> Global O2 sim executable + rudimentary simulation configuration class

- Detectors/EMCAL/simulation/include/EMCALSimulation/Detector.h
- Detectors/EMCAL/simulation/src/Detector.cxx
- As function argument use consistently const std::string_view (maybe const is not needed)
- In within functions use consistently std::string
> Replace ROOT's TString with std::string and std::string_view

- Utilities/DataCompression/include/DataCompression/DataDeflater.h
- Utilities/DataCompression/include/DataCompression/dc_primitives.h
- Utilities/DataCompression/test/DataGenerator.h
- Utilities/DataCompression/test/Fifo.h
- Utilities/DataCompression/test/test_DataDeflater.cxx
- Utilities/DataCompression/test/test_DataGenerator.cxx
- Utilities/DataCompression/test/test_HuffmanCodec.cxx
- Utilities/DataCompression/test/test_dc_primitives.cxx
using bin numbers instead of float values in 'equal to' check
> Fix #489: avoid comparison of float values

- DataFormats/Headers/include/Headers/DataHeader.h
- DataFormats/Headers/test/testDataHeader.cxx
- implementing optimized comparison operator avoiding memcmp
for Descriptor struct
- adding more static asserts for key parameters
- adding simple benchmark
> More optimization and static assert checks in DataHeader definitions

- Detectors/TOF/base/include/TOFBase/Geo.h
- Detectors/TOF/base/src/Geo.cxx
- Detectors/TOF/prototyping/checkIndex.C
- Detectors/TOF/prototyping/checkRotation.C
- Detectors/TOF/simulation/include/TOFSimulation/Detector.h
- Detectors/TOF/simulation/src/Detector.cxx
Several items implemented:
- all TOF params only in one place (Geo class)
- fixes in the names of constants
- methods in Geo class optimized for pos-indexes conversion
- default rotation parameters computed once (init method in Geo class)
> Filling TOF geo class

- Detectors/Passive/include/DetectorsPassive/Magnet.h
- Detectors/Passive/src/Magnet.cxx
- Detectors/Passive/src/PassiveLinkDef.h
- macro/build_geometry.C
- macro/o2sim.C
* based on AliRoot commit aa493c1eccfe07cc25
> Providing the L3 magnet geometry

- Detectors/Passive/CMakeLists.txt
- Detectors/Passive/include/DetectorsPassive/Absorber.h
- Detectors/Passive/src/Absorber.cxx
- Detectors/Passive/src/PassiveLinkDef.h
- macro/build_geometry.C
* based on AliABSOv3 from AliRoot commit aa493c1eccfe07cc25
> Providing the Absorber geometry

- Detectors/Passive/CMakeLists.txt
- Detectors/Passive/include/DetectorsPassive/Dipole.h
- Detectors/Passive/src/Dipole.cxx
- Detectors/Passive/src/PassiveLinkDef.h
- macro/build_geometry.C
* based on AliDIPOv3 from AliRoot commit aa493c1eccfe07cc25
> Providing the dipole (DIPO) geometry

- Detectors/Passive/CMakeLists.txt
- Detectors/Passive/include/DetectorsPassive/Shil.h
- Detectors/Passive/src/PassiveLinkDef.h
- Detectors/Passive/src/Shil.cxx
- macro/build_geometry.C
based on AliSHILv3 from AliRoot commit d9533c578beee97faaeb1d2
> Porting small angle absorber - beam shield (SHIL) to O2

- Detectors/Passive/CMakeLists.txt
- Detectors/Passive/include/DetectorsPassive/Hall.h
- Detectors/Passive/src/Hall.cxx
- Detectors/Passive/src/PassiveLinkDef.h
- macro/build_geometry.C
imported/adapted from AliRoot aa493c1eccfe07cc2555ed
> Providing geometry for experimental HALL

- Detectors/Passive/include/DetectorsPassive/Pipe.h
- Detectors/Passive/src/PassiveLinkDef.h
- Detectors/Passive/src/Pipe.cxx
- macro/build_geometry.C
providing the beam pipe based on AliPIPEupgrade
from AliRoot ad01f46ea3edabdc11
> Porting PIPE from AliRoot

- COPYING
As discussed at length in JIRA (https://alice.its.cern.ch/jira/browse/OCCF-1) here is the license file. It is referred to in the header of every source file.
> [WIP] Create LICENSE file (GPLv3)

- README.md
Was overwritten by accident by the big "Data Processing Layer" PR.
> Bring back original README.md

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/DeviceSpec.h
- Framework/Core/src/DDSConfigHelpers.cxx
- Framework/Core/src/DDSConfigHelpers.h
- Framework/Core/src/DeviceSpec.cxx
- Framework/Core/src/runDataProcessing.cxx
- Framework/Core/test/test_FrameworkDataFlowToDDS.cxx
Now the configuration leaves DDS the task to configure hostname
and ports for the clients.
This also improves documentation and refactors the code a bit to allow
for standalone unit testing.
> Improve DDS config generation by Data Processing layer

- Detectors/TPC/simulation/src/Detector.cxx
> Remove duplicate section in TPC TGeoPolycon

- EventVisualisation/Base/CMakeLists.txt
- EventVisualisation/Base/include/EventVisualisationBase/ConfigurationManager.h
- EventVisualisation/Base/include/EventVisualisationBase/DataInterpreter.h
- EventVisualisation/Base/include/EventVisualisationBase/EventManager.h
- EventVisualisation/Base/include/EventVisualisationBase/GeometryManager.h
- EventVisualisation/Base/include/EventVisualisationBase/Track.h
- EventVisualisation/Base/include/EventVisualisationBase/VisualisationConstants.h
- EventVisualisation/Base/src/ConfigurationManager.cxx
- EventVisualisation/Base/src/DataInterpreter.cxx
- EventVisualisation/Base/src/GeometryManager.cxx
- EventVisualisation/Base/src/Track.cxx
- EventVisualisation/CMakeLists.txt
- EventVisualisation/DataConverter/CMakeLists.txt
- EventVisualisation/DataConverter/include/EventVisualisationDataConverter/ConversionConstants.h
- EventVisualisation/DataConverter/include/EventVisualisationDataConverter/MinimalisticEvent.h
- EventVisualisation/DataConverter/include/EventVisualisationDataConverter/MinimalisticTrack.h
- EventVisualisation/DataConverter/src/MinimalisticEvent.cxx
- EventVisualisation/DataConverter/src/MinimalisticTrack.cxx
- EventVisualisation/Detectors/CMakeLists.txt
- EventVisualisation/Detectors/include/EventVisualisationDetectors/DataInterpreterRND.h
- EventVisualisation/Detectors/src/DataInterpreterRND.cxx
- EventVisualisation/View/CMakeLists.txt
- EventVisualisation/View/include/EventVisualisationView/Initializer.h
- EventVisualisation/View/include/EventVisualisationView/MultiView.h
- EventVisualisation/View/src/Initializer.cxx
- EventVisualisation/View/src/MultiView.cxx
- EventVisualisation/View/src/main.cxx
- EventVisualisation/o2eve_config
- cmake/O2Dependencies.cmake
This is a major update in EventVisualisation brining core classes needed for data visualisation.
> Implementation of the core classes for data visualisation.

- DataFormats/simulation/include/SimulationDataFormat/MCTruthContainer.h
- DataFormats/simulation/test/testMCTruthContainer.cxx
- cmake/O2Dependencies.cmake
> include guideline support library; use of gsl::span in MCTruthContainer

- Common/MathUtils/include/MathUtils/Cartesian3D.h
- Common/MathUtils/src/Cartesian3D.cxx
- Common/MathUtils/src/MathUtilsLinkDef.h
@sawenzel could you please merge that so that it does not come via ITS PR in preparation?
This is just a small class for 2D rotations around Z which are used everywhere in the barrel reco
> Added 2D rotation class acting on Point2D and Point3D

- Detectors/TRD/base/src/TRDCommonParam.cxx
partially addresses #566 for TRD
> TRD: fix compiler warning

- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
- Detectors/ITSMFT/MFT/base/src/GeometryTGeo.cxx
- Detectors/ITSMFT/MFT/base/src/HalfDisk.cxx
- Detectors/ITSMFT/MFT/base/src/Plane.cxx
- Detectors/ITSMFT/MFT/simulation/src/Detector.cxx
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/Cluster.h
> Fix compiler warning for ITSMFT

- Detectors/TPC/base/src/Mapper.cxx
- Detectors/TPC/base/src/PadRegionInfo.cxx
- Detectors/TPC/base/src/Painter.cxx
- Detectors/TPC/calibration/include/TPCCalibration/CalibPedestal.h
- Detectors/TPC/calibration/include/TPCCalibration/CalibRawBase.h
- Detectors/TPC/monitor/include/TPCMonitor/SimpleEventDisplay.h
- Detectors/TPC/reconstruction/src/GBTFrameContainer.cxx
- Detectors/TPC/simulation/include/TPCSimulation/BoxClusterer.h
- Detectors/TPC/simulation/include/TPCSimulation/Clusterer.h
- Detectors/TPC/simulation/include/TPCSimulation/HwClusterer.h
- Detectors/TPC/simulation/src/Baseline.cxx
> TPC: fix compiler warnings

- Framework/Core/CMakeLists.txt
As agreed with @ktf. This should fix PR test failing such as in #601.
> Disable SimpleStatefulProcessing01 test for now

- Detectors/EMCAL/simulation/include/EMCALSimulation/Detector.h
- Detectors/EMCAL/simulation/src/Detector.cxx
- Detectors/TOF/simulation/include/TOFSimulation/Detector.h
- Detectors/TOF/simulation/src/Detector.cxx
- Detectors/TRD/simulation/include/TRDSimulation/Detector.h
- Detectors/TRD/simulation/src/Detector.cxx
partial accomplishement for #610
> The conversion TClonesArray -> std::vector<Hit> for EMCAL + TOF + TRD

- Detectors/Base/include/DetectorsBase/GeometryManager.h
- Detectors/Base/include/DetectorsBase/Track.h
- Detectors/Base/src/BaseLinkDef.h
- Detectors/Base/src/GeometryManager.cxx
- Detectors/Base/src/Track.cxx
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CookedTrack.h
- Detectors/TPC/reconstruction/include/TPCReconstruction/TrackTPC.h
Use static MatBudget MeanMaterialBudget(const Point3D<T> &start, const Point3D<T> &end) to get
the budget between 2 points.
Added to o2::Base::Track method to get extrapolated global position: GetXYZGloAt,
renamed method to get track position in gloal frame from GetXYZ to GetXYZGlo
> ported method to get mat.budget between 2 points in global frame

- Detectors/TPC/base/include/TPCBase/Mapper.h
- Detectors/TPC/base/include/TPCBase/ParameterGas.h
- Detectors/TPC/base/src/ParameterGas.cxx
- Detectors/TPC/simulation/include/TPCSimulation/Detector.h
- Detectors/TPC/simulation/src/Detector.cxx
* Add missing gas parameters
* Unrelated: change a parameter name for clarity
> Dev tpc eloss

- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/V3Layer.h
- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
- Detectors/ITSMFT/ITS/simulation/src/V3Layer.cxx
- Detectors/ITSMFT/common/base/include/ITSMFTBase/SegmentationAlpide.h
The IB geometry was updated to the latest data as requested at ITSU plenary session. In particular the metal stack was added to the Si sensor, the FPC aluminum layers are more realistic, and the glue between the chip and the sensor was added.
> Update IB geometry to latest data

- DataFormats/simulation/include/SimulationDataFormat/MCTrack.h
- DataFormats/simulation/include/SimulationDataFormat/Stack.h
- DataFormats/simulation/src/MCTrack.cxx
- DataFormats/simulation/src/SimulationDataLinkDef.h
- DataFormats/simulation/src/Stack.cxx
- Detectors/EMCAL/simulation/src/Detector.cxx
- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
- Detectors/ITSMFT/MFT/simulation/src/Detector.cxx
- Detectors/ITSMFT/common/simulation/src/ITSMFTSimulationLinkDef.h
- Detectors/TOF/simulation/src/Detector.cxx
- Detectors/TPC/base/src/TPCBaseLinkDef.h
- Detectors/TPC/simulation/include/TPCSimulation/Detector.h
- Detectors/TPC/simulation/src/Detector.cxx
- Detectors/TPC/simulation/src/TPCSimulationLinkDef.h
- Detectors/TRD/simulation/include/TRDSimulation/Detector.h
- Detectors/TRD/simulation/src/Detector.cxx
- Detectors/gconfig/g3Config.C
- Detectors/gconfig/g4Config.C
a) Major refactoring of stack/mctrack (see commit message)
b) Stability fixes
> Improvements to stack/mctrack; Stability fixes

- Detectors/TPC/simulation/CMakeLists.txt
- Utilities/MCStepLogger/CMakeLists.txt
> Fix broken TPC tests

- Detectors/TPC/calibration/include/TPCCalibration/CalibRawBase.h
- Detectors/TPC/calibration/src/CalibRawBase.cxx
- Detectors/TPC/monitor/macro/RunFindAdcError.C
- Detectors/TPC/monitor/macro/RunSimpleEventDisplay.C
- Detectors/TPC/reconstruction/CMakeLists.txt
- Detectors/TPC/reconstruction/include/TPCReconstruction/RawReader.h
- Detectors/TPC/reconstruction/include/TPCReconstruction/RawReaderEventSync.h
- Detectors/TPC/reconstruction/include/TPCReconstruction/SyncPatternMonitor.h
- Detectors/TPC/reconstruction/run/readRawData.cxx
- Detectors/TPC/reconstruction/src/RawReader.cxx
- Detectors/TPC/reconstruction/src/RawReaderEventSync.cxx
- Detectors/TPC/reconstruction/src/TPCReconstructionLinkDef.h
Implemented mechanism to synchronise data of multiple RawReader instances
> fix TPC RawReader synchronization

- Detectors/gconfig/g4Config.C
> Impose right stack behaviour for Geant4; cleanup

- Algorithm/include/Algorithm/PageParser.h
- Algorithm/test/pageparser.cxx
Further bugfixes and enhancements:
- bugfix in the generation of the raw buffer, the element at the page
border had been written incorrectly.
- correctly treating eof condition
the eof condition of the iterator was so far only working if there
have not been any extra padding bytes at the end of the buffer
- unit testing with page sizes 128, 100, and 89
Note: write functionality not yet implemented for grouped elements
@class PageParser
Parser for a set of data objects in consecutive memory pages.
All memory pages have a fixed size and start with a page header.
Depending on the page size and size of the data object, some
objects can be split at the page boundary and have the page header
embedded.
The class iterator can be used to iterate over the data objects
transparently.
In addition …
> Added support for grouped elements in PageParser raw decoder

- Utilities/QC/README.md
Make it clear that it is not the actual QualityControl.
Restructure slightly in order to make it more readable.
This was discussed with Matthias and Jacek in a meeting.
> Update README of QC

- Detectors/TPC/reconstruction/include/TPCReconstruction/HwClusterer.h
- Detectors/TPC/reconstruction/src/HwClusterer.cxx
Using the newly provided copy constructor of the MCTruthContainer
> use copy operator of MCTruthContainer

- Framework/Core/include/Framework/DataAllocator.h
- Framework/TestWorkflows/CMakeLists.txt
- Framework/TestWorkflows/test/test_MakeDPLObjects.cxx
Also introduces a unit test which was triggering the error.
> Fix compilation error in DataAllocator

- Framework/Core/README.md
This revamps a bit the documentation, making it more coherent with
the current implementation and tries to be more geared towards
implementing your own workflow rather of a description of the
implementation details.
> Revamp documentation

- Framework/Core/src/DataAllocator.cxx
- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/src/DataRelayer.cxx
- Framework/Core/src/DeviceMetricsInfo.cxx
- Framework/Core/src/FrameworkGUIDebugger.cxx
- Framework/Core/src/FrameworkGUIDevicesGraph.cxx
- Framework/Core/src/WorkflowHelpers.cxx
- Framework/Core/src/runDataProcessing.cxx
All spotted by running latest clang with -Wall.
> Fix warnings and minor issues in the DPL

- Detectors/FIT/base/src/README.md
- Detectors/FIT/simulation/src/README.md
- Detectors/ITSMFT/ITS/base/src/README.md
- Detectors/ITSMFT/ITS/reconstruction/include/README.md
- Detectors/ITSMFT/common/README.md
Files with empty or trivial content are polluting the doxygen
documentation. Whenever you add a README you should make
sure you have at least one section, either via:
```
```
or via
```
Meaningful section name
=======================
```
give it a meaningful name. Such a name will appear at toplevel
under the Project navigation in the doxygen documentation at:
http://aliceo2group.github.io/AliceO2/
> Eliminate spurious README files

- Utilities/Publishers/include/Publishers/DataPublisherDevice.h
- Utilities/Publishers/src/DataPublisherDevice.cxx
- Utilities/Publishers/src/runDataPublisherDevice.cxx
Alignes to our coding conventions
> Convert Utilities namespace to utilities

- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/Detector.h
- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
- Detectors/ITSMFT/ITS/simulation/src/V3Layer.cxx
Several C++ issues (mainly regarding pointers and character strings, plus a small bug fix) in the code describing ITSU geometry were tackled. New versions of V3Layer.cxx and Detector.cxx/.h were committed. More details in the comments below.
> Fix various C++ coding issues

- cmake/O2Utils.cmake
https://alice.its.cern.ch/jira/browse/OCCF-46
https://github.com/AliceO2Group/AliceO2/issues/249
> CMake error if linkdef but no headers

- README.md
- link to http version of CERN O2 web page to avoid login
- added link to doxygen pages
> Updating main README

- Common/Field/include/Field/MagFieldFast.h
- Common/Field/include/Field/MagFieldParam.h
- Common/Field/include/Field/MagneticField.h
- Common/Field/include/Field/MagneticWrapperChebyshev.h
- Common/MathUtils/include/MathUtils/Chebyshev3D.h
- Common/MathUtils/include/MathUtils/Chebyshev3DCalc.h
- Detectors/Base/include/DetectorsBase/BaseCluster.h
- Detectors/Base/include/DetectorsBase/Detector.h
- Detectors/Base/include/DetectorsBase/GeometryManager.h
- Detectors/Base/include/DetectorsBase/Track.h
- Detectors/Base/include/DetectorsBase/TrackReference.h
- Detectors/Base/src/Track.cxx
Coding convention fixes for https://github.com/AliceO2Group/AliceO2/issues/707#issuecomment-352019262 + some other classes.
> Coding conv.fix in Detector/Base: protected->private data members, #707

- Detectors/TOF/base/include/TOFBase/Geo.h
- Detectors/TOF/base/src/Geo.cxx
- Detectors/TOF/simulation/CMakeLists.txt
- Detectors/TOF/simulation/include/TOFSimulation/Digitizer.h
- Detectors/TOF/simulation/src/Digitizer.cxx
- Detectors/TOF/simulation/src/TOFSimulationLinkDef.h
- macro/run_sim_tof.C
- Create Digitizer for TOF
- with a method to test performence of digitization
> add TOF digitizer

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/TMessageSerializer.h
- Framework/Core/src/TMessageSerializer.cxx
- Framework/Core/test/test_TMessageSerializer.cxx
This adds a few more methods and helpers plus a simple test.
> Add a lower level interface to TMessageSerializer and test

- Generators/include/Generators/Pythia6Generator.h
- Generators/include/Generators/Pythia8Generator.h
- Generators/src/GeneratorsLinkDef.h
- Generators/src/Pythia6Generator.cxx
- Generators/src/Pythia8Generator.cxx
- macro/o2sim.C
- macro/run_sim_pythia8hi.C
This is a follow-up to https://github.com/AliceO2Group/AliceO2/issues/327
> Placing Pythia generators into namespace o2::eventgen

- DataFormats/simulation/test/testMCTruthContainer.cxx
- Detectors/TOF/base/CMakeLists.txt
- Detectors/TOF/base/include/TOFBase/Digit.h
- Detectors/TOF/base/include/TOFBase/Geo.h
- Detectors/TOF/base/src/Digit.cxx
- Detectors/TOF/base/src/TOFBaseLinkDef.h
- Detectors/TOF/simulation/CMakeLists.txt
- Detectors/TOF/simulation/include/TOFSimulation/Detector.h
- Detectors/TOF/simulation/include/TOFSimulation/Digitizer.h
- Detectors/TOF/simulation/include/TOFSimulation/DigitizerTask.h
- Detectors/TOF/simulation/include/TOFSimulation/MCLabel.h
- Detectors/TOF/simulation/src/Detector.cxx
- Detectors/TOF/simulation/src/Digitizer.cxx
- Detectors/TOF/simulation/src/DigitizerTask.cxx
- Detectors/TOF/simulation/src/TOFSimulationLinkDef.h
- cmake/O2Dependencies.cmake
- macro/run_digi_tof.C
- Result of the January 2018 code sprint
- Added TOF Digit
- Updated TOF Geo Object with constants
- Updated TOF Digitizer
- Added custom MC label for TOF
> Updated TOF Digitizer

- .travis.yml
Code for clang-format copied from ROOT.
> Refactor Travis configuration and add clang-format

- DataFormats/Headers/include/Headers/DataHeader.h
- DataFormats/Headers/include/Headers/NameHeader.h
- DataFormats/Headers/src/DataHeader.cxx
- DataFormats/Headers/test/testDataHeader.cxx
- Utilities/O2MessageMonitor/include/O2MessageMonitor/O2MessageMonitor.h
- Utilities/O2MessageMonitor/src/O2MessageMonitor.cxx
...to avoid racial jokes have assignment behave as expected, introduce a polymorphic set method to set members.
> Sanitize operator=

- DataFormats/simulation/include/SimulationDataFormat/MCTruthContainer.h
- DataFormats/simulation/test/testMCTruthContainer.cxx
- Detectors/TOF/simulation/src/DigitizerTask.cxx
As per suggestion of David Rohr.
> New addElements interface for MCTruthContainer

- DataFormats/simulation/CMakeLists.txt
- Detectors/TPC/reconstruction/src/TPCReconstructionLinkDef.h
- Detectors/TPC/simulation/src/TPCSimulationLinkDef.h
* Add missing header for dictionary creation
* Move pragma declarations to correct place
* Cleanup/remove some no longer required dictionary declarations
> Fix dictionary creation problems

- Detectors/EMCAL/base/include/EMCALBase/Digit.h
- Detectors/ITSMFT/MFT/simulation/include/MFTSimulation/EventHeader.h
- Detectors/TOF/base/include/TOFBase/Digit.h
- Detectors/TPC/reconstruction/include/TPCReconstruction/Cluster.h
- Utilities/aliceHLTwrapper/include/aliceHLTwrapper/AliHLTHOMERData.h
> Drop include guards for __CINT__

- Common/SimConfig/include/SimConfig/SimConfig.h
- Common/SimConfig/src/SimConfig.cxx
- Detectors/gconfig/g4Config.C
- macro/o2sim.C
requires FairRoot dev with PR #727
> Added "isMT" option to  SimConfig:

- Detectors/MUON/CMakeLists.txt
- Detectors/MUON/MCH/Base/CMakeLists.txt
- Detectors/MUON/MCH/Base/include/MCHBase/DigitBlock.h
- Detectors/MUON/MCH/Base/include/MCHBase/Mapping.h
- Detectors/MUON/MCH/Base/include/MCHBase/PreClusterBlock.h
- Detectors/MUON/MCH/Base/src/DigitBlock.cxx
- Detectors/MUON/MCH/Base/src/MUONBaseLinkDef.h
- Detectors/MUON/MCH/Base/src/Mapping.cxx
- Detectors/MUON/MCH/Base/src/PreClusterBlock.cxx
- Detectors/MUON/MCH/CMakeLists.txt
- Detectors/MUON/MCH/PreClustering/CMakeLists.txt
- Detectors/MUON/MCH/PreClustering/src/DumpDigits.cxx
- Detectors/MUON/MCH/PreClustering/src/DumpDigits.h
- Detectors/MUON/MCH/PreClustering/src/PreClusterFinder.cxx
- Detectors/MUON/MCH/PreClustering/src/PreClusterFinder.h
- Detectors/MUON/MCH/PreClustering/src/PreClusterFinderDevice.cxx
- Detectors/MUON/MCH/PreClustering/src/PreClusterFinderDevice.h
- Detectors/MUON/MCH/PreClustering/src/runDumpDigits.cxx
- Detectors/MUON/MCH/PreClustering/src/runDumpDigits.json
- Detectors/MUON/MCH/PreClustering/src/runPreClusterFinder.cxx
- Detectors/MUON/MCH/PreClustering/src/runPreClusterFinder.json
- cmake/O2Dependencies.cmake
Hi,
The preclusterizer itself is already quite optimised, but the data structures, their serialization/deserialization, as well as the mapping are going to evolve.
Since it is the first MUON commit it also defines the directory structure, with 2 subdirectories, one for MCH and one (to come) for MID.
Cheers,
Philippe
> first version of MCH preclustering and associated structures

- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/V3Layer.h
- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
- Detectors/ITSMFT/ITS/simulation/src/V3Layer.cxx
This version of the Inner Barrel geometry:
- fixes a few wrong dimensions (FPC Al and Glue thicknesses, chip gaps)
- updates various elements to the latest blueprints (in the ColdPlate, the SpaceFrame structure and the End stave connectors)
- implements the FPC capacitors
This should complete the transaction of the IB geometry to the latest available information.
> Update Inner Barrel geometry to latest blueprints, add capacitors

- Detectors/Passive/src/Cave.cxx
- macro/o2sim.C
Fix in CAVE detector ID and GRP detectors mask building
> Fix in CAVE detector ID and GRP detectors mask building

- Detectors/MUON/CMakeLists.txt
- Detectors/MUON/MID/Base/CMakeLists.txt
- Detectors/MUON/MID/Base/include/MIDBase/Mapping.h
- Detectors/MUON/MID/Base/include/MIDBase/MpArea.h
- Detectors/MUON/MID/Base/src/Mapping.cxx
- Detectors/MUON/MID/Base/src/MpArea.cxx
- Detectors/MUON/MID/Base/test/testMapping.cxx
- Detectors/MUON/MID/CMakeLists.txt
- cmake/O2Dependencies.cmake
This is the initial porting of the mapping for MID.
It actually constitutes the first pull-request for MID.
> First version of the mapping for MID

- run/CMakeLists.txt
The same configuration as in o2sim_G4 but with MT enabled.
Requires PR #901.
> Added o2sim_G4_mt test:

- Framework/Core/include/Framework/TMessageSerializer.h
- Framework/Core/test/test_TMessageSerializer.cxx
Deserialization is now possible also for all types of classes, TObject
is kept as the default.
Consistency checks for the target class info and class info of extracted
object ensure validity of reinterpret cast. The unique_ptr cleanup will
crash otherwise.
We still lack sanity check for the buffer content, TMessage might simply
crash uncontrolled.
> Added consistency checks and support deserialization of non-TObjects

- DataFormats/Headers/include/Headers/DataHeader.h
- DataFormats/Headers/include/Headers/NameHeader.h
- DataFormats/Headers/test/testDataHeader.cxx
few improvements to the header::Stack class and added some test coverage
> Stack tests and fixes

- Utilities/DataCompression/CMakeLists.txt
- Utilities/DataCompression/include/DataCompression/CodingModelDispatcher.h
- Utilities/DataCompression/include/DataCompression/DataDeflater.h
- Utilities/DataCompression/include/DataCompression/HuffmanCodec.h
- Utilities/DataCompression/include/DataCompression/TruncatedPrecisionConverter.h
- Utilities/DataCompression/include/DataCompression/dc_primitives.h
- Utilities/DataCompression/include/DataCompression/mpl_tools.h
- Utilities/DataCompression/include/DataCompression/runtime_container.h
- Utilities/DataCompression/test/DataGenerator.h
- Utilities/DataCompression/test/Fifo.h
- Utilities/DataCompression/test/test_DataDeflater.cxx
- Utilities/DataCompression/test/test_DataGenerator.cxx
- Utilities/DataCompression/test/test_Fifo.cxx
- Utilities/DataCompression/test/test_HuffmanCodec.cxx
- Utilities/DataCompression/test/test_dc_primitives.cxx
- Utilities/DataCompression/test/test_mpl_tools.cxx
- Utilities/DataCompression/tpccluster_parameter_model.h
- applying formatting rules without functional changes
- replacing `typedef` with `using`
> Modernization of data compression code base

- Generators/CMakeLists.txt
- Generators/include/Generators/PDG.h
- Generators/src/GeneratorsLinkDef.h
- Generators/src/PDG.cxx
- macro/o2sim.C
static call AliPDG::addParticlesToPdgDataBase() is added to o2sim.C
> ported AliPDG to O2 (addition of extra particles)

- Framework/Core/src/DispatcherDPL.cxx
Fixing trivial mistake, which I thought I already corrected a long time ago...
> Fix message payload size passed by DispatcherDPL

- Detectors/TPC/reconstruction/src/HardwareClusterDecoder.cxx
Moving pointer dereference after pointer check
> Bugfix TPC HardwareClusterDecoder.cxx

- Framework/Core/CMakeLists.txt
- Framework/Core/src/ComputingResource.h
- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/Core/src/DeviceSpecHelpers.h
- Framework/Core/src/DriverInfo.h
- Framework/Core/src/ResourceManager.h
- Framework/Core/src/SimpleResourceManager.cxx
- Framework/Core/src/SimpleResourceManager.h
- Framework/Core/src/runDataProcessing.cxx
- Framework/Core/test/test_DeviceSpec.cxx
- Framework/Core/test/test_FrameworkDataFlowToDDS.cxx
- Framework/Core/test/test_Graphviz.cxx
- Framework/Core/test/test_TimeParallelPipelining.cxx
It's now possible to specify what to do when a workflow is done.
It defaults to quitting.
Fixes #987 as well.
> Implement completion policy

- Generators/src/PDG.cxx
Comment out addition of some existing particles
> Use same verbosity in addAntiParticle as in addParticle

- Framework/Core/src/DataSampling.cxx
Compatible with Configuration `v1.4.0`.
This should be merged together with alidist bump of Configuration.
> Configuration lowercase namespace

- Framework/CMakeLists.txt
- Framework/Utils/CMakeLists.txt
- Framework/Utils/include/Utils/Utils.h
- Framework/Utils/src/DPLBroadcaster.cxx
- Framework/Utils/src/DPLGatherer.cxx
- Framework/Utils/src/DPLMerger.cxx
- Framework/Utils/src/DPLRouter.cxx
- Framework/Utils/src/Utils.cxx
- Framework/Utils/test/DPLBroadcasterMerger.cxx
- Framework/Utils/test/DPLBroadcasterMerger.h
- Framework/Utils/test/DPLOutputTest.cxx
- Framework/Utils/test/DPLOutputTest.h
- Framework/Utils/test/test_DPLBroadcasterMerger.cxx
- Framework/Utils/test/test_DPLOutputTest.cxx
- cmake/O2Dependencies.cmake
Generic broadcaster, gatherer, merger and splitter are implemented to be used in users workflows.
> Implementation of generic workflow utilities in DPL

- cmake/FindRapidJSON.cmake
see https://github.com/alisw/alidist/pull/1095
> Add cmake module to find RapidJSON (and make a proper target of it)

- cmake/O2Dependencies.cmake
Broken CMake config files hardcode full paths of their dependencies. Those paths
are not relocated properly, leading to O2 build errors if reusing dependencies
built under on different hosts and/or under different prefixes.
> Work around broken paths from external CMake conf

- Steer/DigitizerWorkflow/README.md
- Steer/DigitizerWorkflow/src/SimReaderSpec.cxx
- Steer/DigitizerWorkflow/src/SimReaderSpec.h
- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
- Steer/DigitizerWorkflow/src/TPCDriftTimeDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/TPCDriftTimeDigitizerSpec.h
Several improvements for digitizer DPL mockup, demonstrating configurable workflow and having a more flexible assignment of N sectors to process to M available digitizers.
This provides an almost production ready parallel TPC digitizer. See README.md for some documentation.
> Configurable TPC digitizer workflow

- Detectors/TPC/reconstruction/CMakeLists.txt
- Detectors/TPC/reconstruction/src/TPCCATracking.cxx
- cmake/O2Dependencies.cmake
Load tracking code from AliTPCCommon instead of O2HLTTPCCATracking + necessary changes to interface and dependencies.
> Pull request following the alidist PR to switch to AliTPCCommon.

- DataFormats/Headers/include/Headers/DataHeader.h
- DataFormats/Headers/test/testDataHeader.cxx
The argument list to built up a header stack can be an argument pack
of stacks and BaseHeader-derived headers. Since staks consist of a
collection of headers, the next-header flag must be set in the last
header of the sequence. Until now, the flag was only set in the first
header (where it was already before)
> Bugfix: set the next-header flag correctly in a stack as parameter

- Utilities/O2Device/include/O2Device/O2Device.h
...as it causes a crash on missing config parameter
> Don't add empty monitoring backends in O2Device

- Framework/Core/README.md
Also cleans up a few of the questions at the end.
> Add foreseen features to the Framework README

- Detectors/HMPID/simulation/src/Detector.cxx
> HMPID: avoid new/delete and use fMC instead of TVirtualMC::GetMC()

- README.md
Shield was OK, but text link was misleading
> Fix JIRA link in README.md

- Detectors/MUON/MCH/Simulation/src/Detector.cxx
correctly providing the getHits method for MCH
which is for instance important to update the trackIDs after
track filtering
> MCH: correctly implement getHits method

- Detectors/TOF/simulation/src/Detector.cxx
These messages are causing long log files otherwise
> TOF: change from INFO to DEBUG severity for alignment printouts

- DataFormats/Headers/include/Headers/DataHeader.h
- DataFormats/MemoryResources/CMakeLists.txt
- Detectors/MUON/MCH/PreClustering/src/PreClusterFinder.cxx
- Framework/Core/src/DataSampling.cxx
- Framework/Core/src/runDataProcessing.cxx
- Framework/Utils/test/DPLBroadcasterMerger.cxx
- cmake/O2Dependencies.cmake
- cmake/modules/FindFairMQInFairRoot.cmake
I have not tested this on a Mac so far.
> Support FairRoot repo split

- Framework/Core/src/FrameworkGUIDebugger.cxx
@dberzano , @sawenzel, I thought warnings are treated as errors in the CI, has this policy been changed?
> fixing shadowed variable

- Detectors/TPC/simulation/include/TPCSimulation/ElectronTransport.h
- Detectors/TPC/simulation/src/Digitizer.cxx
- Detectors/TPC/simulation/src/ElectronTransport.cxx
o Sectors on the C-side were not processed properly
o Course -> Coarse
> Bug and typo fix for coarse electron drift

- DataFormats/MemoryResources/include/MemoryResources/MemoryResources.h
- Utilities/O2Device/test/test_O2Device.cxx
adds a few minor fixes and additional tests of the Stack
> additional Stack tests

- Framework/Core/src/WorkflowHelpers.cxx
- Framework/Core/test/test_WorkflowHelpers.cxx
> DPL: Complain about duplicate DataProcessorSpec name

- Steer/include/Steer/O2RunSim.h
After the recent FairRoot bump, I got a crash
which is fixed herewith.
> Sync O2RunSim with FairRunSim

- Detectors/TPC/workflow/src/ClustererSpec.cxx
- Framework/Core/README.md
- Framework/Core/include/Framework/InputRecord.h
- Framework/Core/test/test_DataAllocator.cxx
- Framework/Core/test/test_InputRecord.cxx
- Framework/TestWorkflows/src/dataSamplingPodAndRoot.cxx
- Framework/TestWorkflows/src/test_o2RootMessageWorkflow.cxx
- Framework/TestWorkflows/test/test_MakeDPLObjects.cxx
- Framework/Utils/include/Utils/RootTreeWriter.h
- Steer/DigitizerWorkflow/src/CollisionTimePrinter.cxx
- Steer/DigitizerWorkflow/src/TPCDigitRootWriterSpec.cxx
- Steer/DigitizerWorkflow/src/TPCDriftTimeDigitizerSpec.cxx
This reverts commit 3e1dc31 and reactivates the original proposal of 6257473
For further details see #1179, #973, and #1047.
> Next round on unifying the return type of the DPL input API

- Framework/Core/COOKBOOK.md
- Framework/Core/README.md
Split into `COOKBOOK.md` the DPL implementation details, leaving
`README.md` closer to a design document.
> DPL: Prepare documentation for TB approval

- Common/SimConfig/src/SimConfig.cxx
- Steer/include/Steer/O2MCApplication.h
- cmake/O2Dependencies.cmake
- macro/o2sim.C
- run/O2HitMerger.h
- run/O2PrimaryServerDevice.h
- run/O2SimDevice.h
- run/O2SimDeviceRunner.cxx
- run/o2sim_parallel.cxx
- run/o2simtopology.json
a) possibility to fork simulation setup and share common memory structures (like geometry, cross sections) among many simulation workers via copy-on-write mechanism
b) join a simulation setup on a different node -- volunteer computing
c) improvement to SimConfig: use all modules by default
> Several new features for parallel sim

- macro/o2sim.C
- run/CMakeLists.txt
- run/o2sim.cxx
Re-enables previously commented tests.
> Reenable G4 + G4_MT tests

- Detectors/FIT/simulation/include/FITSimulation/Detector.h
- Detectors/FIT/simulation/src/Detector.cxx
- Detectors/MUON/MCH/Simulation/include/MCHSimulation/Detector.h
- Detectors/MUON/MCH/Simulation/src/Detector.cxx
> Implemented CloneModule functions (needed for MT simulation)

- Detectors/ITSMFT/MFT/base/src/HeatExchanger.cxx
Creating grooves in the rohacell plates to fit the cooling pipes for the 3 first chambers
> MFT:grooves on the 3 first chambers

- Detectors/MUON/MCH/Simulation/include/MCHSimulation/Hit.h
- Detectors/MUON/MCH/Simulation/src/GeometryTest.cxx
- Detectors/MUON/MCH/Simulation/src/Stepper.cxx
- Hit : Fix detElemId return type
- Hit : Entrance point was not recorded
- GeometryTest : Fix getNormalVector function
> Some MCH simulation fixes of mostly stupid bugs.

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/DeviceControl.h
- Framework/Core/include/Framework/FrameworkGUIDevicesGraph.h
- Framework/Core/include/Framework/FrameworkGUIState.h
- Framework/Core/src/FrameworkGUIDebugger.cxx
- Framework/Core/src/FrameworkGUIDeviceInspector.cxx
- Framework/Core/src/FrameworkGUIDeviceInspector.h
- Framework/Core/src/FrameworkGUIDevicesGraph.cxx
- Framework/DebugGUI/CMakeLists.txt
- Framework/DebugGUI/include/DebugGUI/imconfig.h
- Framework/DebugGUI/include/DebugGUI/imgui_extras.h
- Framework/DebugGUI/src/imconfig.h
- Framework/DebugGUI/src/imgui_extras.cpp
Prettifying a few screenshots for CHEP.
> DPL: few more improvements to the GUI

- Framework/Core/src/DataProcessingDevice.cxx
This sends a few metrics regarding the state in which the data
processing layer is in. In particular the `dpl/in_handle_data` is
either:
* 0: outside FairMQDevice::HandleData virtual method.
* 1: inside FairMQDevice::HandleData virtual method.
* 2: inside the stateless or stateful callback.
* 3: inside the error callback.
> DPL: Send metrics for device status

- Framework/Core/include/Framework/DeviceMetricsInfo.h
- Framework/Core/src/DeviceMetricsInfo.cxx
- Framework/Core/src/FrameworkGUIDebugger.cxx
* Keep track of min and max values for metrics.
* Scale plots according to the min and max values.
> DPL: improve scale for metrics display.

- Common/SimConfig/src/SimConfig.cxx
- DataFormats/MemoryResources/include/MemoryResources/MemoryResources.h
- DataFormats/MemoryResources/test/testMemoryResources.cxx
- Detectors/Base/include/DetectorsBase/MaterialManager.h
- Detectors/FIT/reconstruction/include/FITReconstruction/CollisionTimeRecoTask.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CA/json.h
- Detectors/MUON/MCH/Simulation/test/testGeometry.cxx
- Detectors/PHOS/reconstruction/include/PHOSReconstruction/Cluster.h
- Detectors/PHOS/simulation/include/PHOSSimulation/Digitizer.h
- Detectors/PHOS/simulation/src/Digitizer.cxx
- Framework/Core/include/Framework/BoostOptionsRetriever.h
- Framework/Core/src/FrameworkGUIDebugger.cxx
- Framework/Core/src/FrameworkGUIDeviceInspector.cxx
- Framework/Core/test/test_Task.cxx
- Framework/TestWorkflows/src/o2ParallelWorkflow.cxx
- Framework/Utils/include/Utils/RootTreeWriter.h
- run/O2HitMerger.h
- run/o2sim_parallel.cxx
Somehow the codechecker spots errors which does not trigger alibuild fails.
This commit is fixing most of them. The next step will be to fix the alidist recipe
itself to have a working CI check.
> Fix of complaints from the o2 codechecker

- Detectors/gconfig/g4Config.C
- Detectors/gconfig/g4config.in
This is fixing JIRA O2-225 and generally adjusting the g4 settings to what
is used in AliRoot/AliDPG.
> adjust default G4 configuration to current AliDPG settings

- Detectors/TPC/simulation/CMakeLists.txt
- cmake/O2Dependencies.cmake
Adding TPCSpaceChargeBase bucket and adding it to tpc_simulation_bucket requirements. Modifying TPCSimulation build to link TPCSpaceChargeBase library from AliTPCCommon repository.
> Adding TPCSpaceChargeBase library built from AliTPCCommon rep.

- Framework/Core/src/FrameworkGUIDeviceInspector.cxx
- Framework/Core/src/FrameworkGUIDeviceInspector.h
- Framework/Core/src/FrameworkGUIDevicesGraph.cxx
- Framework/Core/test/test_GUITests.cxx
Also add unit test for the device inspector GUI.
> DPL: add GUI to send signals to processes

- DataFormats/Headers/include/Headers/DataHeader.h
- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/ArrowContext.h
- Framework/Core/include/Framework/ContextRegistry.h
- Framework/Core/include/Framework/DataAllocator.h
- Framework/Core/include/Framework/DataProcessingDevice.h
- Framework/Core/include/Framework/DataProcessor.h
- Framework/Core/include/Framework/DataSourceDevice.h
- Framework/Core/include/Framework/InputRecord.h
- Framework/Core/src/DataAllocator.cxx
- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/src/DataProcessor.cxx
- Framework/Core/src/DataSourceDevice.cxx
- Framework/Core/src/FairMQResizableBuffer.cxx
- Framework/Core/src/FairMQResizableBuffer.h
- Framework/Core/src/InputRecord.cxx
- Framework/Core/test/test_FairMQResizableBuffer.cxx
- Framework/Core/test/test_SimpleRDataFrameProcessing.cxx
This is sitting on top of #1289 and provides the support of arrow for both FairMQ and DPL.
> DPL: Introduce support for Arrow in FairMQ and DPL

- CMakeLists.txt
- cmake/O2Dependencies.cmake
All other "find" commands are there.
> Move the find arrow to O2Dependencies

- Framework/Core/CMakeLists.txt
- Framework/Core/test/test_InfoLogger.cxx
- cmake/O2Dependencies.cmake
- cmake/modules/FindCommon.cmake
- cmake/modules/FindInfoLogger.cmake
This adds infologger support to AliceO2:
find.cmake, bucket, example usage & test
> adding infologger

- Detectors/CMakeLists.txt
- Detectors/TPC/reconstruction/CMakeLists.txt
- cmake/O2Dependencies.cmake
Add header-only base library for common headers.
Add TPC fast transform library.
Needs AliTPCCommon v1.4
> Add new libraries from AliTPCCommon

- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/V3Layer.h
- Detectors/ITSMFT/ITS/simulation/src/V3Layer.cxx
The description of OB modules and staves have been updated to the latest specs. In particular:
- the position of modules and related dimensions were revised
- the glue volumes were updated and correctly placed
- the FPC is now more realistic
- the Power Bus is more realistic and the Bias Bus was added
> Updated geometry for OB Modules and Staves

- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
Allow detectors to be skipped via command line.
digitizer-workflow --skipDet TOF,ITS
will not do TOF,ITS processing regardless if is
active in the GRP or not.
Also adding automatic deletion of GRP via smart pointers.
(This should better be done in the interface of GRP itself later on).
> digitizer-workflow: Add command line option to skip detectors

- Detectors/FIT/base/include/FITBase/Digit.h
- Detectors/FIT/base/src/Digit.cxx
- Detectors/FIT/base/src/FITBaseLinkDef.h
- Detectors/FIT/macros/readHitsDigits.C
- Detectors/FIT/macros/readRecPoints.C
- Detectors/FIT/macros/run_digi_fit.C
- Detectors/FIT/macros/run_reco_fit.C
- Detectors/FIT/reconstruction/include/FITReconstruction/CollisionTimeRecoTask.h
- Detectors/FIT/reconstruction/include/FITReconstruction/RecPoints.h
- Detectors/FIT/reconstruction/src/CollisionTimeRecoTask.cxx
- Detectors/FIT/reconstruction/src/RecPoints.cxx
- Detectors/FIT/simulation/include/FITSimulation/Digitizer.h
- Detectors/FIT/simulation/include/FITSimulation/DigitizerTask.h
- Detectors/FIT/simulation/src/Detector.cxx
- Detectors/FIT/simulation/src/Digitizer.cxx
- Detectors/FIT/simulation/src/DigitizerTask.cxx
set number of MCP as detID
improve digits and digitizer
spread time with Gauss woth 50ps sigma on each MCP
style fixes
event time correction
simple trigger calculation
common struct ChannelData for digitization and reco
improve RecPoints
clang-formatting fixes
This is a version cleaning up on #1269 and fixing some issues.
> Several improvements/changes in FIT digitizer/reco:

- Framework/Core/src/DispatcherFairMQ.cxx
> Send both header and payload in DispatcherFairMQ

- Detectors/FIT/base/include/FITBase/Digit.h
- Steer/DigitizerWorkflow/CMakeLists.txt
- Steer/DigitizerWorkflow/src/FITDigitWriterSpec.cxx
- Steer/DigitizerWorkflow/src/FITDigitWriterSpec.h
- Steer/DigitizerWorkflow/src/FITDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/FITDigitizerSpec.h
- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
- cmake/O2Dependencies.cmake
Initial version of FIT digitizer in the DPL digitizer workflow.
A couple of things are incomplete or not supported yet by the actual
digitizer algorithm and have to be tackled later
a) MC truth handling
b) pileup handling
> Integrating the FIT Digitizer into the DPL workflow

- DataFormats/Headers/CMakeLists.txt
- cmake/O2Dependencies.cmake
Introducing bucket for module DataFormats/Headers with minimal dependencies
> Removing dependencies from module DataFormats/Headers

- Framework/Core/include/Framework/ParamRetriever.h
- Utilities/QC/QCProducer/include/QCProducer/Producer.h
Let's see if we can get macos CI compile again.
> Fix compile warning with Apple Compiler LLVM 10.0

- Common/SimConfig/include/SimConfig/SimConfig.h
- Common/SimConfig/src/SimConfig.cxx
- Detectors/Passive/include/DetectorsPassive/Cave.h
- Detectors/Passive/src/Cave.cxx
- macro/build_geometry.C
Prepare the geometry to host ZDC. See https://alice.its.cern.ch/jira/projects/O2/issues/O2-390
Also offer new command line option to skip certain detectors in o2sim.
> Prepare for ZDC inclusion

- Steer/DigitizerWorkflow/src/TPCDigitRootWriterSpec.cxx
> Fix inconsistency warning for TPC digit labels

- Detectors/ITSMFT/common/simulation/include/ITSMFTSimulation/Digitizer.h
- Detectors/ITSMFT/common/simulation/src/Digitizer.cxx
- Steer/DigitizerWorkflow/CMakeLists.txt
- Steer/DigitizerWorkflow/src/MFTDigitWriterSpec.cxx
- Steer/DigitizerWorkflow/src/MFTDigitWriterSpec.h
- Steer/DigitizerWorkflow/src/MFTDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/MFTDigitizerSpec.h
- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
- cmake/O2Dependencies.cmake
@sawenzel @bovulpes : this is essentially a copy paste from ITS specs.
> Add MFT to DPL digitizer-workflow

- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CookedTracker.h
- Detectors/ITSMFT/ITS/reconstruction/src/ITSReconstructionLinkDef.h
to make the latter usable in the macros
> Create dict for ITS CookedTracker

- Framework/Core/src/FrameworkGUIDevicesGraph.cxx
- Framework/Core/src/WorkflowHelpers.cxx
- Framework/Core/src/WorkflowHelpers.h
- Framework/Core/test/test_WorkflowHelpers.cxx
This should address, at least partially, https://alice.its.cern.ch/jira/browse/O2-403 .
> Improve graph layout

- Framework/Core/include/Framework/DataProcessingDevice.h
- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/src/runDataProcessing.cxx
This should allow callbacks to create non data driven Timeslices.
> DPL: expose the TimesliceIndex as a service

- Framework/Core/src/DataSampling.cxx
This obsoletes https://github.com/AliceO2Group/AliceO2/pull/1415 and needs to be merged together with https://github.com/alisw/alidist/pull/1341
> Fix configuration calls

- Framework/Core/src/DataSampling.cxx
- Framework/Core/test/test_DataSampling.cxx
> Update configuration calls to the newest API

- Framework/Core/include/Framework/DataDescriptorMatcher.h
In principle `std::visit` is fine without exception.
> DPL: support macOS < 10.14

- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/Core/src/runDataProcessing.cxx
This is required for DDS & Control integration to work properly.
> DPL: pass-through a few FairMQ options

- Detectors/Base/include/DetectorsBase/Detector.h
- Detectors/Base/src/Detector.cxx
Refactor detector functionality needed in FairMQ based simulation.
Move FairMQMessage/Channel specific stuff into source file
in order to avoid problems with ROOT macros.
> Hide FairMQ stuff in Detector headers

- Framework/Core/include/Framework/Dispatcher.h
- Framework/Core/src/FairMQResizableBuffer.h
modified:   Framework/Core/include/Framework/Dispatcher.h
modified:   Framework/Core/src/FairMQResizableBuffer.h
> Fixing errors reported by clang diagnostics

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/DeviceMetricsInfo.h
- Framework/Core/include/Framework/FrameworkGUIDebugger.h
- Framework/Core/src/DeviceMetricsInfo.cxx
- Framework/Core/src/FrameworkDummyDebugger.cxx
- Framework/Core/src/FrameworkGUIDebugger.cxx
- Framework/Core/src/runDataProcessing.cxx
- Framework/Core/test/benchmark_DeviceMetricsInfo.cxx
- Framework/Core/test/test_DeviceMetricsInfo.cxx
- Framework/DebugGUI/include/DebugGUI/imgui_extras.h
- Framework/DebugGUI/src/imgui_extras.cpp
This is what I used in the CHEP presentation, I never committed it because I wanted to test it more, but since the old sparklines work the same and the other ones have not given me troubles for over one month, I suggest we put it in and eventually improve on it when we have a bit of time, in 2050.
> DPL GUI: improved metrics plots

- Framework/Core/test/test_BoostSerializedProcessing.cxx
As requested the dependency from MID detector code is purged and replaced by dummy equivalent class.
> Removing Cluster2D from tests

- Framework/Core/CMakeLists.txt
- Framework/Core/src/O2ControlHelpers.cxx
- Framework/Core/src/O2ControlHelpers.h
- Framework/Core/src/runDataProcessing.cxx
The configuration being generated is far from being complete,
however it should be good enough to simplify integration.
> DPL: add initial integration for O2 Control system

- Detectors/TPC/base/include/TPCBase/ParameterDetector.h
- Detectors/TPC/base/src/ParameterDetector.cxx
- Detectors/TPC/simulation/include/TPCSimulation/DigitContainer.h
o at average drift speed with additional margin
> Enable hard cut off for triggered mode (#1417)

- Framework/Core/include/Framework/ConfigParamsHelper.h
- Framework/Core/src/runDataProcessing.cxx
An optional argument can be specified to the `--help,-h` option, to create
different versions of the help printout:
- `full`: the full printout with executor, workflow and processor options
- `short`: executor and workflow options, as well as a summary of the processors
- `workflow`: workflow options only
- `executor`: executor options only
- by specifying a valid name for a process which defines option, its options are printed
Default behaviour is `short`.
The definition of processors might depend on the specified workflow options. The help
message is adjusted to workflow options if specified in addition to the `--help` option.
@sawenzel please comment if this fits what you had in mind for https://alice.its.cern.ch/jira/browse/O2-359
We need to decide about the default, either `short` or …
> Implemented customization of help messages of the DPL driver app

- Framework/Utils/include/Utils/RootTreeWriter.h
Using static_cast to type was invoking copy constructor because a new object was
created. This was in particular a problem if the store object is a std::vector
because new memory is allocated, while the store pointer is connected to the branch.
Not yet debugged to full extend but this is very likely related to the fact, that
the branch creates sub-branches for the underlying type of the vector.
This might also be the reason for the problem earlier experienced with an attempt
to use the extracted object directly via SetBranchAddress.
In summary, static cast to type reference has to be used
static_cast<T>.method(...) -> static_cast<T&>.method(...) -> T::method(...)
Filling now the branches individually, so the bookkeeping for the extracted object
has been removed.
> Bugfix: recursing to parent object was invoking copy constructor of store object

- Framework/Core/test/TestClasses.h
Adjusting according to modernize-use-default-member-init policy.
> Fixing issues reported by code checker

- Detectors/EMCAL/simulation/src/Digitizer.cxx
Remove digit if the digit is not in a valid position.
> [O2-379, O2-447] Catch InvalidPositionException in the digitizer

- DataFormats/Detectors/Common/include/DetectorsCommonDataFormats/DetMatrixCache.h
- DataFormats/Detectors/TPC/include/DataFormatsTPC/ClusterHardware.h
- Detectors/TRD/base/CMakeLists.txt
- Detectors/TRD/base/include/TRDBase/TRDGeometry.h
- Detectors/TRD/base/include/TRDBase/TRDGeometryBase.h
- Detectors/TRD/base/include/TRDBase/TRDGeometryFlat.h
- Detectors/TRD/base/include/TRDBase/TRDPadPlane.h
- Detectors/TRD/base/include/TRDBase/TRDSimParam.h
- Detectors/TRD/base/src/TRDGeometry.cxx
- Detectors/TRD/base/src/TRDGeometryBase.cxx
- Detectors/TRD/base/src/TRDGeometryFlat.cxx
- Detectors/TRD/base/src/TRDPadPlane.cxx
- cmake/O2Dependencies.cmake
Just for review so far, this is the flat geometry object for TRD tracking on GPU.
The actual change is in the last commit of this branch! The remaining changes are from the other pull requests.
This needs the following PRs to be merged beforehand:
AliceO2Group/AliceO2#1501
alisw/alidist#1405
AliceO2Group/AliceO2#1497
> Flat Geometry Object for TRD Tracking on GPU

- Detectors/TPC/reconstruction/CMakeLists.txt
- Detectors/TPC/reconstruction/include/TPCReconstruction/TPCFastTransformHelperO2.h
- Detectors/TPC/reconstruction/src/TPCFastTransformHelperO2.cxx
- Detectors/TPC/reconstruction/test/testTPCFastTransform.cxx
- cmake/O2Dependencies.cmake
I rebased #1459 on upstream dev, and fixed the remaining clang-format errors.
As I could not push to @sgorbuno 's original branch, I am opening this new PR.
@matthiasrichter : Could you have a look whether you are now fine with the PR? I think Sergey had already implemented or commented on all your requested changes in #1459.
> TPCFastTransform helper for O2

- Detectors/TPC/reconstruction/src/TPCCATracking.cxx
@shahor02 : This PR implements the flagging on the O2 side. It needs AliTPCCommon v.1.4.4 (alisw/alidist#1315).
Marked as [WIP], as the delta computation is not tested yet.
> Add flagging and correct deltaFwd/deltaBwd computation for tracks crossing CE

- Detectors/TPC/reconstruction/src/TPCCATracking.cxx
Minor change: create and forward TPC transformation object to TPC CA Tracking.
@matthiasrichter : Can you check and approve?
> Pass TPC Transformation to AliGPUReconstruction

- Detectors/Base/include/DetectorsBase/Detector.h
- run/O2HitMerger.h
avoid copy of data when nothing needs to be merged
> Further optimization for hit merging

- Framework/Core/src/DeviceMetricsInfo.cxx
> Match string merics with special characters

- Framework/Core/src/DataRelayer.cxx
Minor speed improvement by avoiding a few allocations.
> DPL: speedup DataRelayer

- DataFormats/simulation/src/Stack.cxx
- Steer/DigitizerWorkflow/CMakeLists.txt
- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
- Steer/DigitizerWorkflow/src/TRDDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/TRDDigitizerSpec.h
- cmake/O2Dependencies.cmake
Preparing the integration of TRD digitization into the workflow.
The TRD now needs to write a TRDDigitizer and activate a couple if lines currently commented out.
> DPL digitizer preparation for TRD

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/AODReaderHelpers.h
- Framework/Core/src/AODReaderHelpers.cxx
- Framework/TestWorkflows/src/o2AODDummy.cxx
This introduces a few helper classes which can be extended to read
ROOT Trees which contains the new AOD structure as implemented by Peter.
The o2AODDummy example is reworked to use it, rather then the old fake
data.
> DPL: initial attempt at a generic AOD reader

- Framework/Utils/include/Utils/RootTreeReader.h
- doing GetEvent on individual branch level
- disable caching
- cleanup baskets after each snapshot
> Bugfix: Reducing RootTreeReader memory consumption

- run/O2HitMerger.h
- run/O2PrimaryServerDevice.h
- run/o2sim_parallel.cxx
With this commit, the user gets feedback about the progress of
of events distributed / finished directly in the driver application.
relates to JIRA O2-464
> o2sim: monitor number of events distributed / finished

- Detectors/TPC/reconstruction/src/HwClusterer.cxx
@matthiasrichter : Please merge, this is the fix by Sebastian.
@KlewinS
> Fix for correct treatment of heartbeat in clusterizer by Sebastian

- Framework/Core/src/AODReaderHelpers.cxx
- Framework/TestWorkflows/src/o2AODDummy.cxx
* Two branches now, one for Tracks and one for Calo
* Include Calo information
> DPL: adapt to AOD format changes

- Detectors/ITSMFT/MFT/base/include/MFTBase/Geometry.h
- Detectors/ITSMFT/MFT/base/include/MFTBase/HeatExchanger.h
- Detectors/ITSMFT/MFT/base/src/Geometry.cxx
- Detectors/ITSMFT/MFT/base/src/HeatExchanger.cxx
- Detectors/ITSMFT/MFT/base/src/Ladder.cxx
New water pipes, grooves and manifolds.
> New Heat Exchanger

- Detectors/TRD/simulation/src/Detector.cxx
This PR fixes a bug when reading a keyword to identify sensitive regions for the TRD hit creation.
> Bug fix in TRD hits

- Detectors/EMCAL/base/include/EMCALBase/Digit.h
- Detectors/EMCAL/base/src/Digit.cxx
- Detectors/EMCAL/simulation/CMakeLists.txt
- Detectors/EMCAL/simulation/include/EMCALSimulation/Digitizer.h
- Detectors/EMCAL/simulation/include/EMCALSimulation/MCLabel.h
- Detectors/EMCAL/simulation/src/Digitizer.cxx
- Detectors/EMCAL/simulation/src/EMCALSimulationLinkDef.h
Introduced EMCal MCLabel class, modified Digit and Digitizer classes to work with this class to store MC truth information, changed tower index in Digit to Short_t.
> Introduced MC truth information for EMCal

- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/src/DataSourceDevice.cxx
Anything higher will clogger out outputs.
> DPL: use 60 as minimun log rate

- Detectors/ITSMFT/ITS/simulation/src/V3Layer.cxx
The numbering of chips in a IB or OB module and the numbering of OB modules in a Half Stave (i.e. the order in which these volumes are placed in their mother volume) was changed in order to be the same as in hardware (except that chips in the second OB row go from 7 to 13 instead of 8 to 14, to avoid hops in the software; the difference in numbering is handled elsewhere in software). Moreover the orientation of the chip local reference system with respect to the stave reference system was correct to be as in the hardware.
> Update in chip/module numbering and orientation to reflect hardware

- Framework/DebugGUI/src/imgui_extras.cpp
Use a single multisegment path rather than single segments.
> DPL GUI: improve performance of lines metrics

- Detectors/TRD/base/include/TRDBase/TRDGeometryBase.h
- Detectors/TRD/base/include/TRDBase/TRDGeometryFlat.h
Change some functions that used to be static in the old AliTRDgeometry, not all changed back as variables can not be static for gpu.
> reverted some functions in TRDGeometryBase to static.

- Framework/Core/include/Framework/RootTableBuilderHelpers.h
- Framework/Core/include/Framework/TableBuilder.h
- Framework/Core/src/AODReaderHelpers.cxx
- Framework/Core/test/test_Root2ArrowTable.cxx
- Framework/TestWorkflows/src/o2AODDummy.cxx
This brings the o2AODDummy example on par with the latest / greatest developments of @pzhristov AOD format.
Notice that in order to get things working with RDataFrame extra support in ROOT needs to be merged.
> Improve AOD example

- Detectors/ITSMFT/ITS/CMakeLists.txt
- Detectors/ITSMFT/ITS/macros/test/CheckDigits.C
- Detectors/ITSMFT/ITS/macros/test/run_test.sh
- Detectors/ITSMFT/ITS/macros/test/run_workflows.sh
- Detectors/ITSMFT/ITS/tracking/src/Tracker.cxx
- Detectors/ITSMFT/ITS/workflow/CMakeLists.txt
- Detectors/ITSMFT/ITS/workflow/include/ITSWorkflow/ClusterWriterSpec.h
- Detectors/ITSMFT/ITS/workflow/include/ITSWorkflow/ClustererSpec.h
- Detectors/ITSMFT/ITS/workflow/include/ITSWorkflow/CookedTrackerSpec.h
- Detectors/ITSMFT/ITS/workflow/include/ITSWorkflow/DigitReaderSpec.h
- Detectors/ITSMFT/ITS/workflow/include/ITSWorkflow/RecoWorkflow.h
- Detectors/ITSMFT/ITS/workflow/include/ITSWorkflow/TrackWriterSpec.h
- Detectors/ITSMFT/ITS/workflow/include/ITSWorkflow/TrackerSpec.h
- Detectors/ITSMFT/ITS/workflow/src/ClusterWriterSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/ClustererSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/CookedTrackerSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/DigitReaderSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/RecoWorkflow.cxx
- Detectors/ITSMFT/ITS/workflow/src/TrackWriterSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/TrackerSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/its-reco-workflow.cxx
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/Clusterer.h
- Detectors/ITSMFT/common/reconstruction/src/Clusterer.cxx
- Detectors/ITSMFT/common/reconstruction/src/DigitPixelReader.cxx
- cmake/O2Dependencies.cmake
- macro/run_clus_its.C
- macro/run_digi_its.C
To test this PR, run the run_workflows.sh script from the Detectors/ITSMF/ITS/macros/test/ directory.
Everything should already work, hopefully.
However, since the DPL is something quite new for me, it would be very nice to get a full scale review 
of these pieces of code. 
So I am labelling this PR with "WIP".
> ITS reconstruction in DPL

- DataFormats/Headers/include/Headers/Stack.h
- DataFormats/MemoryResources/include/MemoryResources/MemoryResources.h
- DataFormats/MemoryResources/test/testMemoryResources.cxx
- Framework/Core/src/DataAllocator.cxx
- Framework/Core/src/Dispatcher.cxx
- Framework/Core/src/ExternalFairMQDeviceProxy.cxx
- Framework/Core/src/LifetimeHelpers.cxx
- Framework/Utils/include/Utils/Utils.h
- Framework/Utils/src/DPLMerger.cxx
- Utilities/O2Device/README.md
- Utilities/O2Device/include/O2Device/Utilities.h
- Utilities/O2Device/test/test_O2Device.cxx
- Utilities/O2MessageMonitor/src/O2MessageMonitor.cxx
- Utilities/aliceHLTwrapper/src/MessageFormat.cxx
this largely is cleanup, also addresses codechecker warnings related to Stack.
> Stack fixes

- CCDB/src/Condition.cxx
- CCDB/src/FileStorage.cxx
- CCDB/src/GridStorage.cxx
- CCDB/src/IdPath.cxx
- CCDB/src/IdRunRange.cxx
- CCDB/src/LocalStorage.cxx
- CCDB/src/Manager.cxx
- CCDB/src/Storage.cxx
- CCDB/src/XmlHandler.cxx
This reduces the chances of dependency on FairRoot
> Migrate CCDB to use FairLogger standalone package

- run/o2sim_parallel.cxx
Another stability improvement for running multiple o2sim
in parallel:
* randomize initial port
* generate topology file per PID in order to avoid writing to same file
from 2 processes
* perform port substitution in topology file in a single transaction
> o2sim: Stability fix

- Detectors/TPC/reconstruction/src/HardwareClusterDecoder.cxx
- Detectors/TRD/simulation/src/Digitizer.cxx
- Framework/Core/src/DataSpecUtils.cxx
fixes "unsigned long" vs "unsigned long long" mismatch
> Fix warning to repair CI failure on MacOS

- Detectors/TRD/simulation/CMakeLists.txt
- Detectors/TRD/simulation/include/TRDSimulation/Detector.h
- Detectors/TRD/simulation/include/TRDSimulation/TRsim.h
- Detectors/TRD/simulation/src/Detector.cxx
- Detectors/TRD/simulation/src/TRsim.cxx
TRD transition radiation simulation (O2-454) included in the hit creation process. The parametrized hit generation from TR photons is based on the work done in AliRoot.
> TRD transition radiation simulation (O2-454)

- Framework/Core/src/FrameworkGUIDataRelayerUsage.cxx
- Framework/Core/src/TableConsumer.cxx
This is more standalone fixes found while debugging the removal of DataSourceDevice and some other  major development I am about to open a PR for. Given they fix corner cases / performance issues also in the current state of the codebase, I am speed tracking them.
> New round of minor DPL fixes

- DataFormats/simulation/test/testMCTruthContainer.cxx
fixes compilation for me (no idea how it passed the CI before)
> add missing header

- Framework/Utils/include/Utils/RootTreeReader.h
- Using move semantics for objects read from tree to be passed on to transport
- Some cleanup and fixing a memory leak
- Implementing loop mode for DPL utility RootTreeReader
If running in loop mode, the publisher will start over at the beginning
when all tree entries have been published. The default mode is `single` (shot).
Configurable via constructor arguments of type `PublishingMode`.
> Update of DPL utility RootTreeReader

- Detectors/MUON/MID/Base/include/MIDBase/Constants.h
- Detectors/MUON/MID/Simulation/src/Geometry.cxx
- Detectors/MUON/MID/Simulation/src/Geometry.h
Second PR for the MID geometry:
- implementation of service volumes (RPC supports).
- some bug fixes (RPC size and position).
- useful functions for future features ( @dstocco ), see Constants.h
> Improve MID geometry

- Framework/Core/src/AODReaderHelpers.cxx
This allows to injestion of the DZero candidates as defined by
@ginnocen prototype.
> DPL: add DZero candidates prototype

- Framework/Utils/CMakeLists.txt
This test is still timing out. Please re-enable when the underlying problem is solved.
> Comment out failing test until problem resolved

- Detectors/TPC/base/include/TPCBase/ParameterGEM.h
- Detectors/TPC/base/src/ParameterGEM.cxx
- Detectors/TPC/base/test/testTPCParameters.cxx
- Detectors/TPC/simulation/src/GEMAmplification.cxx
- Detectors/TPC/simulation/test/testTPCGEMAmplification.cxx
o Addition of a second parameter improves the description of the previous implementation
> Improve effective GEM response

- Detectors/TRD/base/CMakeLists.txt
- Detectors/TRD/base/include/TRDBase/TRDCalDet.h
- Detectors/TRD/base/include/TRDBase/TRDCalROC.h
- Detectors/TRD/base/src/TRDBaseLinkDef.h
- Detectors/TRD/base/src/TRDCalDet.cxx
- Detectors/TRD/base/src/TRDCalROC.cxx
These are two classes are required for the TRD simulation. They serve as calibration parameter containers. Both are required for the digitizer (#1649) that will be extended immediately after this pull request.
> TRD calibration parameter containers

- Detectors/MUON/MCH/Simulation/include/MCHSimulation/Digit.h
- Detectors/MUON/MCH/Simulation/include/MCHSimulation/Digitizer.h
- Detectors/MUON/MCH/Simulation/include/MCHSimulation/Response.h
- Detectors/MUON/MCH/Simulation/src/Digit.cxx
- Detectors/MUON/MCH/Simulation/src/Digitizer.cxx
- Detectors/MUON/MCH/Simulation/src/Response.cxx
- Steer/DigitizerWorkflow/src/MCHDigitWriterSpec.h
- Steer/DigitizerWorkflow/src/MCHDigitizerSpec.cxx
Improvement and further features in MCH digitisation:
- introduction of MClabels
- better encapsulation of Response and Digitisation
- improvement of parameter handling
> take modifications from digitizerMCnew branch

- Detectors/MUON/MID/Base/include/MIDBase/Constants.h
- Detectors/MUON/MID/Simulation/CMakeLists.txt
- Detectors/MUON/MID/Simulation/src/Geometry.cxx
- Detectors/MUON/MID/Simulation/src/Geometry.h
- Detectors/MUON/MID/Simulation/test/CMakeLists.txt
- Detectors/MUON/MID/Simulation/test/testGeometry.cxx
- cmake/O2Dependencies.cmake
The PR consists of 2 commits.
In the first, the geometry transfomration in MIDBase are used when building the detector geometry
In the second, the tests of the corresponding boost tests are added
> Use the transformation defined in MIDBase when building the detector geometry

- Steer/CMakeLists.txt
- Steer/include/Steer/O2MCApplication.h
- Steer/include/Steer/O2MCApplicationBase.h
- Steer/include/Steer/O2RunSim.h
- Steer/src/SteerLinkDef.h
- macro/o2sim.C
Introduction of O2MCApplicationBase class in order
to be able to customize geometry tracking cuts and special actions
during stepping.
The device based simulation now inherits from this class.
> New O2MCBase class

- Detectors/ITSMFT/MFT/base/src/GeometryTGeo.cxx
- Detectors/ITSMFT/MFT/base/src/HeatExchanger.cxx
Fix the bugs producing errors reported by valgrind as in this jira ticket:
https://alice.its.cern.ch/jira/browse/O2-481
> MFT: fix bugs in array boundary

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/RCombinedDS.h
- Framework/Core/src/RCombinedDS.cxx
- Framework/Core/test/test_TableBuilder.cxx
This datasource can take any other RDataSource and combine them
in a "full join" one effectively mimicking a double loop using
RDataFrame.
> DPL: add RCombinedDS

- run/CMakeLists.txt
should lead to better coverage.
> Include all detectors in simulation tests

- cmake/O2Utils.cmake
- cmake/tests-wrapper.sh.in
- run/CMakeLists.txt
> Add optional NON_FATAL switch to tests (O2-499)

- Framework/Core/include/Framework/RCombinedDS.h
- Framework/Core/src/RCombinedDS.cxx
- Framework/Core/test/test_TableBuilder.cxx
This introduces two new kind of indexing:
* RCombinedDSFriendIndex: an inner join done on the row number
* RCombinedDSBlockJoinIndex: combination of the rows of two tables
belonging to the same category, where the category is specified by
the value of a given column. The kind of combination can be specified
at construction time and should provide the ability to do most common
type of double loops.
> DPL: Introduce BlockJoin and Friend

- Detectors/TPC/base/include/TPCBase/ROC.h
- Detectors/TPC/simulation/test/testTPCDigitContainer.cxx
> clang format + fix ROC number calculation

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/AnalysisHelpers.h
- Framework/Core/src/AnalysisHelpers.cxx
- Framework/TestWorkflows/src/o2D0Analysis.cxx
This reduces quite a lot the verbosity of the analysis.
> DPL: add initial set of helpers for analysis

- Framework/Core/src/runDataProcessing.cxx
just specifying the possible parameters for option `--completion-policy`
in the help message
> small update to the command line help of the DPL driver

- Generators/src/GeneratorFactory.cxx
by removing unnecessary single quote escaping
> Fix modernize-raw-string-literal

- Detectors/MUON/MID/Base/include/MIDBase/Mapping.h
- Detectors/MUON/MID/Base/src/Mapping.cxx
- Add method to easily iterate over strips
- Allow to copy the mapping
> Update MID mapping

- Detectors/TPC/base/include/TPCBase/CalArray.h
- Detectors/TPC/base/include/TPCBase/CalDet.h
- Detectors/TPC/base/include/TPCBase/Mapper.h
- Detectors/TPC/calibration/include/TPCCalibration/CalibPedestal.h
- Detectors/TPC/calibration/include/TPCCalibration/CalibRawBase.h
- Detectors/TPC/calibration/macro/comparePedestalsAndNoise.C
- Detectors/TPC/calibration/macro/drawNoiseAndPedestal.C
- Detectors/TPC/calibration/macro/runPedestal.C
- Detectors/TPC/calibration/macro/runPedestal.sh
- Detectors/TPC/calibration/src/CalibPedestal.cxx
- Detectors/TPC/calibration/src/CalibRawBase.cxx
- Detectors/TPC/monitor/include/TPCMonitor/SimpleEventDisplay.h
- Detectors/TPC/monitor/macro/RunSimpleEventDisplay.C
- Detectors/TPC/monitor/macro/startMonitor
- Detectors/TPC/monitor/src/SimpleEventDisplay.cxx
- Detectors/TPC/reconstruction/CMakeLists.txt
- Detectors/TPC/reconstruction/include/TPCReconstruction/RawReader.h
- Detectors/TPC/reconstruction/include/TPCReconstruction/RawReaderCRU.h
- Detectors/TPC/reconstruction/run/rawReaderCRU.cxx
- Detectors/TPC/reconstruction/src/RawReaderCRU.cxx
- Detectors/TPC/reconstruction/src/TPCReconstructionLinkDef.h
- cmake/O2Dependencies.cmake
* Add new raw data reader for decoding raw data taken with the CRU
* Minor beautifications
> Raw reader cru

- Detectors/ITSMFT/common/simulation/CMakeLists.txt
- Detectors/ITSMFT/common/simulation/include/ITSMFTSimulation/DPLDigitizerParam.h
- Detectors/ITSMFT/common/simulation/src/DPLDigitizerParam.cxx
- Detectors/ITSMFT/common/simulation/src/ITSMFTSimulationLinkDef.h
creating parameters with template classes need
some special treatment
move static_assert and get rid of private function
in struct
> Improvements on ITSMFT DigitizerParam

- Framework/Core/src/WorkflowHelpers.cxx
This is a leftover task from https://github.com/AliceO2Group/AliceO2/pull/1652, found it in my branches
> Minor update: Using FairMQDevice::WaitFor via the RawDeviceService

- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/ChipMappingITS.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/ChipMappingMFT.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/RawPixelReader.h
- Detectors/ITSMFT/common/reconstruction/src/ChipMappingITS.cxx
- macro/run_CRUDataSkimming_its.C
- macro/run_rawdecoding_its.C
Mapping of the ITS staves (==RU) on FEE HW ID encoding Layer, StaveID within the layer and GBT link ID (0:2) serving given RU.
> Implementation of ITS FFEId numbering scheme

- Common/Field/macro/README.md
- Common/Field/macro/createMapsFromText.C
- Common/Field/macro/extractMapsAsText.C
- Common/Field/src/MagneticWrapperChebyshev.cxx
> Utilities for MagField object regeneration

- Framework/Core/src/DataProcessingDevice.cxx
Now that it's trivial to attach a debugger, let's avoid execessive
verbosity in the printouts, especially because it seems that it's non trivial to switch them off in debug builds...
> DPL: remove a bunch of debug statements

- Detectors/TRD/doc/diagram/diagram.xml
The PR does not contain code. Just keeping track of some documentation material.
> TRD documentation

- Detectors/MUON/MCH/Mapping/test/CMakeLists.txt
- Detectors/MUON/MCH/Simulation/test/CMakeLists.txt
As discussed during WP3 (March 21st 2019).
> Tests should not be installed

- CCDB/src/CcdbApi.cxx
- CCDB/test/testCcdbApi.cxx
- Common/Utils/CMakeLists.txt
- Common/Utils/include/CommonUtils/StringUtils.h
- cmake/O2Dependencies.cmake
The commit also introduces a StringUtils.h with trimming functions.
> CCDB api : Prevent whitespaces in file name

- Framework/Core/include/Framework/ExternalFairMQDeviceProxy.h
- Framework/Core/include/Framework/runDataProcessing.h
- Framework/Core/src/ExternalFairMQDeviceProxy.cxx
- Framework/TestWorkflows/README
- Framework/TestWorkflows/src/flpQualification.cxx
This allows injesting inputs already compatible with DPL in a DPL workflow.
> DPL: add adaptor for an external DPL source

- Detectors/ITSMFT/ITS/macros/EVE/DisplayEvents.C
- macro/run_trac_its.C
With this PR, the ITS event display provides the possibility to visualise the raw data.  Internally, the navigation over reconstructed clusters and tracks is now done using the ROFRecord structures.
> Visualisation of the ITS raw data

- Detectors/ITSMFT/MFT/base/src/HalfCone.cxx
> change-new-cone

- Framework/Core/src/DataSampling.cxx
It is needed to have direct connection from a task to a processor.
> Do not add Dispatcher if it has no input (QC-150)

- DataFormats/Detectors/TPC/src/ClusterNativeHelper.cxx
> Fix: _ misisng in TPC native clusters baranch name

- Detectors/Passive/src/Pipe.cxx
A list of overlaps in the Pipe volume description was solved. See JIRA ticket https://alice.its.cern.ch/jira/browse/O2-599 for more details.
> Fixing overlaps in Pipe volumes description

- DataFormats/common/include/CommonDataFormat/InteractionRecord.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/RawPixelReader.h
- macro/run_rawdecoding_its.C
> Possibility to convert ITS raw data to digits 

- DataFormats/Detectors/Common/include/DetectorsCommonDataFormats/DetID.h
- DataFormats/Detectors/Common/src/DetID.cxx
- DataFormats/Headers/include/Headers/DataHeader.h
- Detectors/Base/include/DetectorsBase/GeometryManager.h
- Detectors/FIT/CMakeLists.txt
- Detectors/FIT/FDD/CMakeLists.txt
- Detectors/FIT/FDD/base/CMakeLists.txt
- Detectors/FIT/FDD/base/include/FDDBase/Geometry.h
- Detectors/FIT/FDD/base/src/FDDBaseLinkDef.h
- Detectors/FIT/FDD/base/src/Geometry.cxx
- Detectors/FIT/FDD/simulation/CMakeLists.txt
- Detectors/FIT/FDD/simulation/include/FDDSimulation/Detector.h
- Detectors/FIT/FDD/simulation/include/FDDSimulation/Hit.h
- Detectors/FIT/FDD/simulation/src/Detector.cxx
- Detectors/FIT/FDD/simulation/src/FDDSimulationLinkDef.h
- Generators/src/GeneratorFactory.cxx
- cmake/O2Dependencies.cmake
- macro/build_geometry.C
- run/O2HitMerger.h
FDD is the AD upgrade. This commit consist of the basic detector geometry (only scintillator modules and wave length shifters) and simulation machinery up to hits. Code was tested via o2sim_serial using box generator in eta acceptance of the FDD (part of the commit), hits are created and looks healthy.
> Detector FDD

- run/O2SimDevice.h
Use new ProcessEvent implementation in Geant4_VMC
in order to avoid expensive (re)-initialization steps
done in the ProcessRun API.
For G3 we cannot move to ProcessEvent, as this in turn
does not call all necessary hooks.
Fixes https://alice.its.cern.ch/jira/browse/O2-603
> o2sim: Use ProcessEvent() for Geant4

- Detectors/ITSMFT/ITS/macros/test/run_test.sh
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CookedTracker.h
- Detectors/ITSMFT/ITS/reconstruction/src/CookedTracker.cxx
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/IOUtils.h
- Detectors/ITSMFT/ITS/tracking/src/IOUtils.cxx
- Detectors/ITSMFT/ITS/workflow/src/CookedTrackerSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/TrackWriterSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/TrackerSpec.cxx
- macro/run_trac_its.C
This PR propagates the information about RO-frame boundaries to the output of the tracking
> RO-frame information for tracking

- Detectors/TPC/workflow/src/ClusterDecoderRawSpec.cxx
- Framework/Core/include/Framework/DataAllocator.h
- Framework/Core/include/Framework/DataChunk.h
- Framework/Core/include/Framework/MessageContext.h
- Framework/Core/src/DataAllocator.cxx
- Framework/Core/src/DataProcessor.cxx
- Framework/Core/src/Dispatcher.cxx
- Framework/Core/test/test_DataAllocator.cxx
- Framework/Core/test/test_SimpleStatefulProcessing01.cxx
- Framework/Utils/src/DPLBroadcaster.cxx
- Framework/Utils/src/DPLGatherer.cxx
- Framework/Utils/src/DPLRouter.cxx
- Framework/Utils/test/DPLBroadcasterMerger.cxx
- Framework/Utils/test/DPLOutputTest.cxx
> [DPL] Support for resizable DataChunk

- Detectors/FIT/common/simulation/src/FITSimulationLinkDef.h
- cmake/O2Dependencies.cmake
- macro/build_geometry.C
- run/O2HitMerger.h
> Connect CPV to simulation

- Framework/Core/src/DataProcessingDevice.cxx
Rather than using the "dpl/" prefix, the preferred way is to attach
a tag on the metric which will improve querying on the monitoring
infrastructure side.
> DPL: use Monitoring tags for DPL metrics [O2-618]

- Steer/include/Steer/O2MCApplicationBase.h
- Steer/src/O2MCApplication.cxx
This file is helpful for the Monte Carlo step analysis.
> o2sim: Write file containing VolToModule mapping

- Detectors/TRD/base/CMakeLists.txt
- Detectors/TRD/base/include/TRDBase/Digit.h
- Detectors/TRD/base/include/TRDBase/DigitIndex.h
- Detectors/TRD/base/src/TRDBaseLinkDef.h
Developement of the TRD Digit Type/Data Format following the discussion in [(O2-624)](https://alice.its.cern.ch/jira/browse/O2-624).
> TRD Raw/Digits Data Format (O2-624)

- Detectors/TPC/simulation/src/Detector.cxx
Changed as discussed in https://alice.its.cern.ch/jira/browse/O2-596.
Thanks to Marek Kowalski.
> TPC: Fix geometry overlaps

- Detectors/TRD/simulation/src/Digitizer.cxx
Reduce TRD Digitizer verbosity.
> Reduce TRD Digitizer verbosity

- Detectors/TRD/simulation/src/Digitizer.cxx
Removed a bug that prevented the digitization chain to continue due to a wrong test in an if-statement.
> TRD digitizer bug removed

- Generators/src/Pythia8Generator.cxx
@preghenella : thanks, this fixes the problem seen by @noferini
> Fix against large t<0 in pythia: always convert tracks to cm,s

- GPU/TPCFastTransformation/TPCFastTransform.h
Fix for the JIRA ticket https://alice.its.cern.ch/jira/browse/O2-361
> add t0 correction to the in-time-frame TPC transformation

- Detectors/ITSMFT/ITS/tracking/include/ITStracking/VertexerTraits.h
- Detectors/ITSMFT/ITS/tracking/src/VertexerTraits.cxx
@mpuccio @mconcas : Can you check if this is OK with you? Gave me warnings with GCC 8.3.
> Fix compiler warnings

- Framework/Core/src/DataProcessingDevice.cxx
This is to make sure that timers get processed only once.
> DPL: make CompletionOp::Process consume timers (O2-646)

- Detectors/ZDC/simulation/src/Detector.cxx
* some volumes where wrongly placed inside ZDCA whereas they should be in cave
(electromagnetic calorimeter + support)
* fixing sign of ZDCC coordinates
Thanks to @coppedis .
> Fix ZDC overlap problems

- Detectors/ITSMFT/ITS/tracking/include/ITStracking/Configuration.h
- Detectors/ITSMFT/ITS/tracking/src/VertexerTraits.cxx
- macro/run_primary_vertexer_ITS.C
- macro/run_trac_ca_its.C
@mconcas have a look, if it is fine with you I think that this can me merged.
> Fix ITS CA reconstruction macros

- Framework/Core/include/Framework/ConfigParamsHelper.h
- Framework/Core/include/Framework/DataSpecUtils.h
- Framework/Core/include/Framework/DeviceExecution.h
- Framework/Core/include/Framework/FrameworkGUIDebugger.h
- Framework/Core/src/CommonDataProcessors.cxx
- Framework/Core/src/ConfigParamsHelper.cxx
- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/Core/src/FrameworkGUIDebugger.cxx
- Framework/Core/src/WorkflowHelpers.cxx
- Framework/Core/src/runDataProcessing.cxx
- Framework/Core/test/test_WorkflowHelpers.cxx
This is to reduce the delta of the commit which actually takes care of
workflow merging.
> DPL: minor fixes.

- Detectors/ZDC/simulation/CMakeLists.txt
- Detectors/ZDC/simulation/include/ZDCSimulation/Digit.h
- Detectors/ZDC/simulation/include/ZDCSimulation/Digitizer.h
- Detectors/ZDC/simulation/include/ZDCSimulation/Hit.h
- Detectors/ZDC/simulation/src/Digitizer.cxx
- Steer/DigitizerWorkflow/CMakeLists.txt
- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
- Steer/DigitizerWorkflow/src/ZDCDigitWriterSpec.h
- Steer/DigitizerWorkflow/src/ZDCDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/ZDCDigitizerSpec.h
- cmake/O2Dependencies.cmake
First rough version of the ZDC digitizer workflow
> Simple skeleton for ZDC digit + digitizer + DPL workflow

- Detectors/TRD/simulation/include/TRDSimulation/Digitizer.h
- Detectors/TRD/simulation/src/Digitizer.cxx
- More and better hardcoded values (waiting for ccdb)
- Unnecesary messages removed
- Almost finalized conversion of hits to signals (missing signal vector filling)
O2-455
> Improved TRD digitizer (O2-455)

- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/RawPixelReader.h
Possibility to reset reader and with and w/o statistics reset
1. Changed RawPixelReader::clear() to clear(bool resetStat = true) to reset or spare the previous statistics
2. openInput(file) will call clear(false) before attaching new file, therefore the statistics will not be reset
3. In order to reset the statistics before processing new file, one can explicitly call clear(true), i.e.
````
reader.openFile(<file1>);
while ( (chd = reader.getNextChipData(chips) ) ) { /*...*/ }
reader.clear(true); // will close the file (even if not fully processed yet) and reset statistics
reader.openFile(<file2>);
...
````
> Possibility to reset reader and with and w/o statistics reset

- DataFormats/Headers/include/Headers/TimeStamp.h
> Applying formatting guidelines

- Detectors/GlobalTracking/src/MatchTPCITS.cxx
- Detectors/TPC/base/include/TPCBase/ParameterDetector.h
- Detectors/TPC/base/include/TPCBase/ParameterElectronics.h
- Detectors/TPC/base/include/TPCBase/ParameterGEM.h
- Detectors/TPC/base/include/TPCBase/ParameterGas.h
- Detectors/TPC/base/src/CDBInterface.cxx
- Detectors/TPC/base/src/ParameterDetector.cxx
- Detectors/TPC/base/src/ParameterElectronics.cxx
- Detectors/TPC/base/src/ParameterGEM.cxx
- Detectors/TPC/base/src/ParameterGas.cxx
- Detectors/TPC/base/src/TPCBaseLinkDef.h
- Detectors/TPC/base/test/testTPCCDBInterface.cxx
- Detectors/TPC/base/test/testTPCParameters.cxx
- Detectors/TPC/reconstruction/src/TPCCATracking.cxx
- Detectors/TPC/reconstruction/src/TPCFastTransformHelperO2.cxx
- Detectors/TPC/simulation/include/TPCSimulation/DigitContainer.h
- Detectors/TPC/simulation/include/TPCSimulation/ElectronTransport.h
- Detectors/TPC/simulation/include/TPCSimulation/SAMPAProcessing.h
- Detectors/TPC/simulation/src/Detector.cxx
- Detectors/TPC/simulation/src/DigitContainer.cxx
- Detectors/TPC/simulation/src/Digitizer.cxx
- Detectors/TPC/simulation/src/ElectronTransport.cxx
- Detectors/TPC/simulation/src/GEMAmplification.cxx
- Detectors/TPC/simulation/src/SAMPAProcessing.cxx
- Detectors/TPC/simulation/src/SpaceCharge.cxx
- Detectors/TPC/simulation/test/testTPCElectronTransport.cxx
- Detectors/TPC/simulation/test/testTPCGEMAmplification.cxx
- Detectors/TPC/simulation/test/testTPCSAMPAProcessing.cxx
- Steer/DigitizerWorkflow/src/TPCDigitizerSpec.cxx
- cmake/O2Dependencies.cmake
This PR introduced the ConfigurableParam for the TPC
Can be merged
> Use configurable params for the TPC

- Detectors/Base/include/DetectorsBase/MaterialManager.h
- Detectors/Base/src/MaterialManager.cxx
- Detectors/ZDC/simulation/data/simcuts.dat
- Detectors/ZDC/simulation/include/ZDCSimulation/Detector.h
- Detectors/ZDC/simulation/src/Detector.cxx
First step towards more systematic porting of simulation cuts in a similar way offered by AliRoot.
> o2-sim : Port simulation cuts from AliRoot

- Steer/DigitizerWorkflow/src/TPCDigitRootWriterSpec.cxx
@mkrzewic : could you try with this fix?
> Ignore dummy sector=-2 transmitted in TPC digitization [O2-717]

- DataFormats/Headers/include/Headers/DataHeader.h
- DataFormats/Headers/src/DataHeader.cxx
- DataFormats/Headers/test/testDataHeader.cxx
- Framework/Core/include/Framework/DataDescriptorMatcher.h
- Framework/Core/include/Framework/DataDescriptorMatcher.inc
- Framework/Core/include/Framework/TimesliceIndex.inc
- Framework/Core/src/DataDescriptorMatcher.cxx
- Framework/Core/src/DataDescriptorQueryBuilder.cxx
- Framework/Core/src/DataSpecUtils.cxx
- Framework/Core/src/LifetimeHelpers.cxx
- Framework/Core/test/test_DataDescriptorMatcher.cxx
- Framework/Core/test/test_Parallel.cxx
- Framework/Core/test/test_ParallelProducer.cxx
- Framework/Core/test/test_TimePipeline.cxx
- Framework/Core/test/test_TimesliceIndex.cxx
- Framework/TestWorkflows/src/dataSamplingParallel.cxx
- Framework/TestWorkflows/src/dataSamplingTimePipeline.cxx
- Framework/TestWorkflows/src/flpQualification.cxx
- Framework/TestWorkflows/src/o2DataQueryWorkflow.cxx
- Framework/TestWorkflows/src/o2ParallelWorkflow.cxx
- Utilities/Mergers/src/mergersBenchmarkTopology.cxx
- Utilities/Mergers/src/mergersTopologyExample.cxx
This does not compile without propagating the changes in the framework, counting on @ktf 
For now this is a preliminary proposal on how to accommodate the needs as we learned them recently.
Not sure about the timeframeStart and timeframeDuration as TF identifier - the exact format needs to be figured out. See also O2-685
> DataHeader update

- Framework/Core/src/Dispatcher.cxx
It needs https://github.com/AliceO2Group/AliceO2/pull/2020.
@Barthelemy
> [QC-168] [QC-111] Support all serialization methods in Dispatcher

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/AnalysisDataModel.h
- Framework/Core/include/Framework/AnalysisTask.h
- Framework/TestWorkflows/src/o2SimpleTracksAnalysis.cxx
This shows how using the new SoA "skins" on top of arrow makes simple loops almost as natural as their AliRoot counterparts. See for example:
https://github.com/AliceO2Group/AliceO2/compare/dev...ktf:improve-analysis-examples?expand=1#diff-688d99cba3802db2e57169063e610aa9R79
> Improve analysis examples

- Detectors/MUON/MCH/Simulation/test/DigitMerging.cxx
- Detectors/MUON/MCH/Simulation/test/DigitMerging.h
- Framework/Core/include/Framework/Kernels.h
- Framework/Core/include/Framework/TableBuilder.h
- Framework/DebugGUI/include/DebugGUI/imgui.h
- Framework/DebugGUI/src/GL/gl3w.h
- Framework/DebugGUI/src/GL/glcorearb.h
- Framework/DebugGUI/src/HandMadeMath.h
- Framework/DebugGUI/src/imgui.h
- Framework/DebugGUI/src/imgui_extras.cpp
- Framework/DebugGUI/src/imgui_internal.h
- Framework/DebugGUI/src/sokol_gfx.h
- Framework/DebugGUI/src/stb_rect_pack.h
- Framework/DebugGUI/src/stb_textedit.h
- Framework/DebugGUI/src/stb_truetype.h
- Framework/DebugGUI/test/imgui.h
- Framework/DebugGUI/test/imgui_demo.cpp
- Framework/Foundation/test/test_Traits.cxx
- Framework/TestWorkflows/src/o2AnalysisTaskExample.cxx
This fixes all codechecker warnings, mostly in DebugGUI but also some others, and the git-clang-format changes that were triggered.
> Fix all codechecker warnings

- CCDB/src/CcdbApi.cxx
- CCDB/test/testCcdbApi.cxx
Do not merge until we ahve a fix on the QC side as well !
> CCDB: Sanitize the path and object name (QC-165)

- Common/SimConfig/include/SimConfig/ConfigurableParam.h
- Common/SimConfig/include/SimConfig/SimConfig.h
- Common/SimConfig/src/ConfigurableParam.cxx
- Common/SimConfig/src/SimConfig.cxx
- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
- macro/o2sim.C
New command line key configFile can point to a JSON/INI file with
values for parameters. These will override values provided in the
user code, and will themselves be overriden by versions coming
in the updateFromString command line flag.
> ConfigurableParam: add support for updating from file

- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
Declaration missing in PR https://github.com/AliceO2Group/AliceO2/pull/2027
> Bugfix: adding missing option declaration in digitizer workflow

- GPU/GPUTracking/Merger/GPUTPCGMPropagator.cxx
- GPU/GPUTracking/Merger/GPUTPCGMPropagator.h
add switch for the ITS field into propagator
> add switch for the ITS field into propagator

- cmake/O2Dependencies.cmake
There was a race condition with #2058.
> DPL: adapt dependency name to new convention

- DataFormats/Detectors/FIT/T0/include/DataFormatsFITT0/RecPoints.h
- DataFormats/Detectors/FIT/T0/src/RecPoints.cxx
- DataFormats/common/include/CommonDataFormat/InteractionRecord.h
- DataFormats/common/src/InteractionRecord.cxx
- Detectors/FIT/T0/reconstruction/src/CollisionTimeRecoTask.cxx
+ related misc. fixes
@AllaMaevskaya
> always set T0 collision times, even if dummy

- Algorithm/CMakeLists.txt
- Algorithm/include/Algorithm/BitstreamReader.h
- Algorithm/include/Algorithm/Parser.h
- Algorithm/include/Algorithm/RangeTokenizer.h
- Algorithm/test/test_BitstreamReader.cxx
some minor compiler warnings fixed in addition
> Adding BitstreamReader utility

- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/RawPixelReader.h
+ some rearrangement of data members
> Extra error check: tracks jumps in CRU RDH.packetCounter

- Detectors/TPC/workflow/src/CATrackerSpec.cxx
> Fix: sign of B-field is read from GRP

- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/RawPixelReader.h
The last decoded RDH for each link can be accessed as
````
const auto& MAP = rawReader.getMapping();
for (int ir = 0; ir < MAP.getNRUs(); ir++) {
for (int il = 0; il < o2::itsmft::MaxLinksPerRU; il++) {
if (rawReader.getRUDecode(ir)->links[il]) { // was link seen in data ?
const o2::header::RAWDataHeader* rdh = rawReader.getRUDecode(ir)->links[il]->lastRDH;
rawReader.printRDH(rdh);
}
}
}
````
> Cache last RDH for each link, dump RDH on error

- Framework/Core/test/benchmark_ContextRegistry.cxx
- Framework/Core/test/benchmark_DataRelayer.cxx
- Framework/Core/test/benchmark_DeviceMetricsInfo.cxx
- Framework/Core/test/benchmark_InputRecord.cxx
- Framework/Core/test/benchmark_TableBuilder.cxx
Otherwise compilation fails with google benchmark >= 1.4
> Fix missing semicolon for google benchmarks

- Detectors/TPC/reconstruction/src/GPUCATracking.cxx
- GPU/GPUTracking/Base/opencl/GPUReconstructionOCL.cl
- GPU/GPUTracking/Standalone/makefiles/makefile
- GPU/GPUTracking/Standalone/utils/bitfield.h
- GPU/GPUTracking/TRDTracking/GPUTRDTrack.cxx
- GPU/TPCFastTransformation/IrregularSpline2D3D.h
- GPU/TPCFastTransformation/IrregularSpline2D3DCalibrator.cxx
@shahor02 : fixes one problem, but there must be more, still most tracks are fake.
> Fix TPC MC Label Computation + several other fixes

- Detectors/TRD/simulation/include/TRDSimulation/Detector.h
- Detectors/TRD/simulation/src/Detector.cxx
- Detectors/TRD/simulation/src/Digitizer.cxx
Avoid string comparisons in the digitizer by extending the TRD hit.
> TRD avoid strcmps O2-734

- Detectors/MUON/MCH/Simulation/src/Station1Geometry.cxx
- Detectors/MUON/MCH/Simulation/src/Station2Geometry.cxx
- Detectors/MUON/MCH/Simulation/src/Station345Geometry.cxx
- Detectors/MUON/MID/Simulation/src/Materials.cxx
- fix (most of) the overlaps [https://alice.its.cern.ch/jira/browse/O2-601](url)
- change the slat electronic cards
- correct the gas mixture of RPC in MID
> Fix MUON geometry

- Detectors/TRD/simulation/include/TRDSimulation/Detector.h
- Detectors/TRD/simulation/src/Detector.cxx
- Detectors/TRD/simulation/src/Digitizer.cxx
In response to https://github.com/AliceO2Group/AliceO2/pull/2098#issuecomment-504924210.
> TRD local coordinates cached directly in the hit (O2-734)

- Detectors/MUON/MID/Simulation/CMakeLists.txt
- Detectors/MUON/MID/Simulation/include/MIDSimulation/ClusterLabeler.h
- Detectors/MUON/MID/Simulation/include/MIDSimulation/MCClusterLabel.h
- Detectors/MUON/MID/Simulation/include/MIDSimulation/PreClusterLabeler.h
- Detectors/MUON/MID/Simulation/src/ClusterLabeler.cxx
- Detectors/MUON/MID/Simulation/src/MCClusterLabel.cxx
- Detectors/MUON/MID/Simulation/src/MIDSimulationLinkDef.h
- Detectors/MUON/MID/Simulation/src/PreClusterLabeler.cxx
- cmake/O2Dependencies.cmake
The tests for this MC labeler were developed together with the ones for a track labeler, which will come later on.
I will therefore perform a commpn pull-request for the tests of the two labelers when the two processing algorithm will be in O2.
> Clusters labeler for MID

- Detectors/TRD/simulation/src/Digitizer.cxx
I found this little bug while investigating the digitization code. Currently not affecting the results, but important for the future.
> TRD BUG changed getCol to getRow

- Detectors/Base/include/DetectorsBase/MaterialManager.h
- Detectors/Base/src/MaterialManager.cxx
separate code from declaration (likely the MatManager is not performance
critical) for better readability and faster compile
add static function to query the tracking media used inside
a logical volume and all of its daughter volumes
(query by region)
> MaterialManager: move code to source; function to query media by region

- GPU/GPUTracking/Base/GPUDataTypes.h
- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/Global/GPUChainTracking.h
- GPU/GPUTracking/Interface/GPUO2Interface.cxx
@MichaelLettrich : This should fix your problem
> Fix missing output ptrs, which were not set

- Detectors/TRD/base/include/TRDBase/TRDSimParam.h
- Detectors/TRD/base/src/TRDSimParam.cxx
In response to https://alice.its.cern.ch/jira/browse/O2-734?focusedCommentId=232283&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-232283.
- Changed division by multiplication
- Inlined TimeResponse and CrossTalk functions.
@sawenzel: Please check if the inline functions are ok, I had to move their definitions to the header.
> TRD SimParam code optimization (O2-734)

- Detectors/TPC/reconstruction/include/TPCReconstruction/TPCFastTransformHelperO2.h
- Detectors/TPC/reconstruction/macro/getTPCTransformationExample.C
- Detectors/TPC/reconstruction/src/TPCFastTransformHelperO2.cxx
- Detectors/TPC/reconstruction/test/testTPCFastTransform.cxx
- GPU/GPUTracking/Standalone/config_libGPUTracking.mak
- GPU/TPCFastTransformation/CMakeLists.txt
- GPU/TPCFastTransformation/IrregularSpline1D.cxx
- GPU/TPCFastTransformation/IrregularSpline1D.h
- GPU/TPCFastTransformation/IrregularSpline2D3D.cxx
- GPU/TPCFastTransformation/IrregularSpline2D3D.h
- GPU/TPCFastTransformation/TPCDistortionIRS.cxx
- GPU/TPCFastTransformation/TPCDistortionIRS.h
- GPU/TPCFastTransformation/TPCFastTransform.cxx
- GPU/TPCFastTransformation/TPCFastTransform.h
- GPU/TPCFastTransformation/TPCFastTransformGeo.cxx
- GPU/TPCFastTransformation/TPCFastTransformGeo.h
- GPU/TPCFastTransformation/TPCFastTransformManager.cxx
- GPU/TPCFastTransformation/TPCFastTransformQA.cxx
- GPU/TPCFastTransformation/TPCFastTransformationLinkDef_O2.h
- GPU/TPCFastTransformation/macro/IrregularSpline2D3DCalibratorTest.C
- GPU/TPCFastTransformation/macro/generateTPCDistortionNTuple.C
restructure TPCFastTransform;
consistency tests;
inverse transformation;
extend the area of SP distortion approximation to the sector edges
get rid of unique_ptr in the GPU code
> restructure TPCFastTransform

- Detectors/ITSMFT/ITS/tracking/include/ITStracking/Vertexer.h
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/VertexerTraits.h
Fixing Vertexer Interface in order to make it work properly as expected
> Fix params

- Detectors/TRD/base/CMakeLists.txt
- Detectors/TRD/base/include/TRDBase/LTUParam.h
- Detectors/TRD/base/src/LTUParam.cxx
- Detectors/TRD/base/src/TRDBaseLinkDef.h
LTUParam are the fixed parameters for the TrapConfig.
Starting with this one.
> Adding TrapConfig parameters

- Detectors/ITSMFT/ITS/workflow/include/ITSWorkflow/RecoWorkflow.h
- Detectors/ITSMFT/ITS/workflow/src/RecoWorkflow.cxx
- Detectors/ITSMFT/ITS/workflow/src/its-reco-workflow.cxx
- macro/run_trac_ca_its.C
@iouribelikov , @mpuccio : this is to not hack the code/recompile each time we want to switch from one tracker to another.
> ITS recoworkflow option to chose the tracker

- Framework/Core/COOKBOOK.md
Took me some time to figure out what was wrong, so better document it.
> Update documentation for running gdb from GUI

- Detectors/ITSMFT/ITS/tracking/src/Cluster.cxx
- Detectors/ITSMFT/ITS/tracking/src/TrackerTraitsCPU.cxx
Checked and fixed this morning with @iouribelikov.
@shahor02 can you please check if this is also working for you?
Thanks a lot!
> Fix ITS CA tracker bug introduced while fixing OpenCL warnings

- Detectors/ITSMFT/MFT/base/CMakeLists.txt
- Detectors/ITSMFT/MFT/base/include/MFTBase/Barrel.h
- Detectors/ITSMFT/MFT/base/src/Barrel.cxx
- Detectors/ITSMFT/MFT/base/src/MFTBaseLinkDef.h
Implementation of the Barrel services following the suggestion from older pull request and working in the compatibility with the cmake changes
> Implementation of the Barrel services for the MFT

- DataFormats/simulation/include/SimulationDataFormat/MCCompLabel.h
- Detectors/ITSMFT/ITS/tracking/cuda/src/VertexerTraitsGPU.cu
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/ROframe.h
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/VertexerTraits.h
- Detectors/ITSMFT/ITS/tracking/src/VertexerTraits.cxx
- macro/run_primary_vertexer_ITS.C
This contains:
- Improvements in using the steering macro (guarded scopes for debug, more work will come)
- Inclusion of time benchmarks in the macro
- Initial fixes in algorithm revision, thanks to @a-kieffer which will contribute with more fixes
> [ITS][vertexer] Improve steering macro + fixes

- Detectors/ITSMFT/ITS/base/src/GeometryTGeo.cxx
- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/V3Layer.h
- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
- Detectors/ITSMFT/ITS/simulation/src/V3Layer.cxx
- Detectors/ITSMFT/MFT/base/src/GeometryTGeo.cxx
- Detectors/ITSMFT/common/base/include/ITSMFTBase/SegmentationAlpide.h
- Detectors/ITSMFT/test/HitAnalysis/src/HitAnalysis.cxx
@iouribelikov @mario6829 please check, if ok I will close https://github.com/AliceO2Group/AliceO2/pull/2222
> Fix: use 50 / 100 um for IB / OB chip thicknesses

- Framework/Core/include/Framework/DataAllocator.h
Replace the different SFINAE specializations with one method using
constexpr if.
> Streamline DPL Allocator::snapshot

- Framework/Core/CMakeLists.txt
- Framework/Core/README.md
- Framework/Core/include/Framework/DataSamplingConditionFactory.h
- Framework/Core/src/DataSampling.cxx
- Framework/Core/src/DataSamplingConditionCustom.cxx
- Framework/Core/src/DataSamplingConditionFactory.cxx
- Framework/Core/src/Dispatcher.cxx
> [QC-210] Custom Data Sampling Condtions using ROOT reflection

- Framework/Core/include/Framework/DataAllocator.h
- Framework/Core/include/Framework/MessageContext.h
- Framework/Core/test/test_DataAllocator.cxx
This extends DPL `make<T>` support for ROOT-serialized types from TObject derived types
to all types implementing ROOT `ClassDef` interface and thus having a Root dictionary.
If a type has both a ROOT dictionary and is messageable, the unserialized
transmission takes precedence.
> Extend DPL make-support to all ROOT-serializable types

- Framework/Core/ANALYSIS.md
Attempt at documenting how the DPL analysis framework will work.
> DPL: Analysis Framework Design Document

- Framework/Core/include/Framework/ASoA.h
* Add asArrowTable() method to create new tables from slices.
* Add size() method to get number of entries.
> DPL Analysis: improve soa::Table

- Detectors/ITSMFT/ITS/tracking/include/ITStracking/PrimaryVertexContext.h
- Detectors/ITSMFT/ITS/tracking/src/Tracker.cxx
- Detectors/ITSMFT/ITS/tracking/src/TrackerTraitsCPU.cxx
Quick fix on the efficiency higher than 1.
Fix for efficiency lower than expected comes in a separate request...
> [ITS] Fix cluster reusage in pile-up events

- Framework/Core/src/runDataProcessing.cxx
Add message when LOG(DEBUG) & co is compiled out.
> DPL driver: notify about optimized builds

- Framework/Foundation/CMakeLists.txt
- Framework/Foundation/include/Framework/StructToTuple.h
- Framework/Foundation/test/test_StructToTuple.cxx
This should come handy, among other things, for the AnalysisTask
business.
> Framework: helper to decompose structs to tuples

- Framework/AnalysisTutorial/CMakeLists.txt
- Framework/AnalysisTutorial/src/collisionTracksIteration.cxx
- Framework/AnalysisTutorial/src/trackCollectionIteration.cxx
- Framework/AnalysisTutorial/src/trackIteration.cxx
- Framework/CMakeLists.txt
- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/AnalysisDataModel.h
- Framework/Core/include/Framework/AnalysisTask.h
- Framework/Core/src/Kernels.cxx
- Framework/Core/test/test_AnalysisTask.cxx
- Framework/Foundation/include/Framework/Traits.h
- Framework/TestWorkflows/src/o2AnalysisTaskExample.cxx
Initial code to demonstrate how we can derive AOD inputs and outputs from an AnalysisTask.
> DPL: reworking AnalysisTask to have a generic process method

- GPU/TPCFastTransformation/TPCFastTransform.h
> add ideal TPC transformation

- Detectors/ITSMFT/MFT/tracking/include/MFTTracking/Cell.h
- GPU/Common/GPULogging.h
- GPU/GPUTracking/Base/GPUReconstruction.cxx
- GPU/GPUTracking/Base/GPUReconstructionTimeframe.cxx
- GPU/GPUTracking/Base/cuda/GPUReconstructionCUDA.cu
- GPU/GPUTracking/Base/hip/GPUReconstructionHIP.hip.cxx
- GPU/GPUTracking/Base/opencl-common/GPUReconstructionOCL.cxx
- GPU/GPUTracking/DataCompression/GPUTPCClusterStatistics.cxx
- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/Standalone/CMakeLists.txt
- GPU/GPUTracking/Standalone/display/GPUDisplay.cxx
- GPU/GPUTracking/Standalone/qa/GPUQA.cxx
- GPU/TPCFastTransformation/TPCFastTransform.h
fix compile error (how did it pass the CI?) and exception from fmt::printf in TPC tracking
> Two fixes for debug output

- Detectors/GlobalTracking/src/MatchTPCITS.cxx
and raw cluster time instead of calling with adjuster cluster time and 0 vertex time
> call TPC transform with separate track time

- Detectors/ITSMFT/ITS/tracking/src/VertexerTraits.cxx
@mconcas : when you are fine with it, I'll just remove them.
> Fix compile warnings, remove leftovers from refactoring MC code

- DataFormats/Detectors/FIT/FDD/include/DataFormatsFDD/Digit.h
- DataFormats/Detectors/FIT/FDD/include/DataFormatsFDD/RecPoint.h
- Detectors/FIT/FDD/CMakeLists.txt
- Detectors/FIT/FDD/reconstruction/CMakeLists.txt
- Detectors/FIT/FDD/reconstruction/include/FDDReconstruction/Reconstructor.h
- Detectors/FIT/FDD/reconstruction/src/FDDReconstructionLinkDef.h
- Detectors/FIT/FDD/reconstruction/src/Reconstructor.cxx
- Detectors/FIT/FDD/simulation/include/FDDSimulation/DigitizationParameters.h
- Detectors/FIT/FDD/simulation/include/FDDSimulation/Digitizer.h
- Detectors/FIT/FDD/simulation/src/Digitizer.cxx
- Detectors/FIT/FDD/workflow/CMakeLists.txt
- Detectors/FIT/FDD/workflow/include/FDDWorkflow/DigitReaderSpec.h
- Detectors/FIT/FDD/workflow/include/FDDWorkflow/RecPointReaderSpec.h
- Detectors/FIT/FDD/workflow/include/FDDWorkflow/RecPointWriterSpec.h
- Detectors/FIT/FDD/workflow/include/FDDWorkflow/RecoWorkflow.h
- Detectors/FIT/FDD/workflow/include/FDDWorkflow/ReconstructorSpec.h
- Detectors/FIT/FDD/workflow/src/DigitReaderSpec.cxx
- Detectors/FIT/FDD/workflow/src/RecPointReaderSpec.cxx
- Detectors/FIT/FDD/workflow/src/RecPointWriterSpec.cxx
- Detectors/FIT/FDD/workflow/src/RecoWorkflow.cxx
- Detectors/FIT/FDD/workflow/src/ReconstructorSpec.cxx
- Detectors/FIT/FDD/workflow/src/fdd-reco-workflow.cxx
Reconstruction workflow for FDD. More detailed simulation in Digitizer. Digit updated according to (future) raw data format.
> FDD reconstruction and update of Digitizer

- CCDB/README.md
Remove outdated info 
Add missing info
> Update the CCDB README

- Framework/Core/src/WorkflowSpec.cxx
- Framework/Core/test/test_ParallelPipeline.cxx
Updating the distribution algorithm of channels to the pipelines. The subspec
ids are now accessed round robin when distributed among the pipelines. This
will ensure a better performance distribution under the assumption that a
publishing process will publish the data sequentially. The data will thus be
distributed round robin among the pipelines. This will be naturally the
case unless the publisher itsself implements scheduling.
> [DPL] Updating WorkflowSpec::parallelPipeline helper

- Framework/Core/include/Framework/InputRecord.h
- Framework/Core/test/test_InputRecord.cxx
This reverts commit 5cf42d6cc886a4918c9052b213c4e23885faa88d until problem
on macos compilation is fixed.
> Revert PR #2345 "Simplifying InputRecord API"

- Detectors/TPC/workflow/src/ClusterDecoderRawSpec.cxx
- Detectors/TPC/workflow/src/ClustererSpec.cxx
- Detectors/TPC/workflow/src/tpc-reco-workflow.cxx
Configure all processes to dispatch data immediately, clusterer and decoder
processes process the sector data is they come in. This reduces to amount of data
which are hold in parallel in the pipelines.
> Applying completion and dispatch policies to process individual TPC sectors

- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/V3Services.h
- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
- Detectors/ITSMFT/ITS/simulation/src/V3Layer.cxx
- Detectors/ITSMFT/ITS/simulation/src/V3Services.cxx
The support structures of the ITS Inner Barrel on Side A were implemented. Fake overlaps with air containers were removed by properly shaping them.
> Implementation of ITS IB End Wheels support on Side A

- dependencies/Findcub.cmake
Get search path as provided by alidist recipe CUB_ROOT
> Get Findcub.cmake to work

- Detectors/TRD/simulation/src/Digitizer.cxx
This PR solves O2-790 (https://alice.its.cern.ch/jira/browse/O2-790). The solution is easy, finding out the reason of the problem was subtle.
> Remove TRD empty digits O2-790

- GPU/GPUTracking/TRDTracking/GPUTRDTracker.cxx
- GPU/GPUTracking/TRDTracking/GPUTRDTracker.h
- GPU/GPUTracking/TRDTracking/GPUTRDTrackerDebug.h
- GPU/GPUTracking/TRDTracking/macros/checkDbgOutput.C
- fixed to 4 sigma at the moment, TODO: tune cut
- removed some functions which were not needed in performance check macro
> Introduce cut on angular pull of tracklets

- GPU/TPCFastTransformation/TPCFastTransform.h
- GPU/TPCFastTransformation/TPCFastTransformGeo.h
on the request of @davidrohr :
- remove Y-correction from in-time-frame transformation; 
- z<->time conversion methods for the time frame
> TPC transformation fix

- tests/tests-wrapper.sh.in
As was discussed in WP3 meeting today.
(I tried to change as little as possible, we can clean up all the CMake macros later if we want to keep it this way. For now, let's just test whether it works.)
> Enforce 3 attempts for all ctests

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/HistogramRegistry.h
- Framework/Core/include/Framework/StringHelpers.h
- Framework/Core/test/benchmark_HistogramRegistry.cxx
- Framework/Core/test/test_HistogramRegistry.cxx
Adds StringHelpers.h with compile time hashing function, test and benchmark
> HistogramRegistry with fast by-name lookup using compile time hash

- DataFormats/MemoryResources/include/MemoryResources/MemoryResources.h
- Framework/Core/include/Framework/DataAllocator.h
- Framework/Core/include/Framework/FairMQDeviceProxy.h
- Framework/Core/src/FairMQDeviceProxy.cxx
- Framework/Utils/include/DPLUtils/Utils.h
- Framework/Utils/src/DPLMerger.cxx
> initial support for pmr containers in DPL

- DataFormats/Detectors/EMCAL/include/DataFormatsEMCAL/Constants.h
- Detectors/EMCAL/simulation/CMakeLists.txt
- Detectors/EMCAL/simulation/include/EMCALSimulation/Digitizer.h
- Detectors/EMCAL/simulation/include/EMCALSimulation/LabeledDigit.h
- Detectors/EMCAL/simulation/include/EMCALSimulation/MCLabel.h
- Detectors/EMCAL/simulation/include/EMCALSimulation/SimParam.h
- Detectors/EMCAL/simulation/src/Digitizer.cxx
- Detectors/EMCAL/simulation/src/EMCALSimulationLinkDef.h
- Detectors/EMCAL/simulation/src/LabeledDigit.cxx
- Detectors/EMCAL/simulation/src/SimParam.cxx
introduce time response, modify MC label handling, introduce noise digits
> [EMCAL-518] implement time resolution for Digits

- Framework/Core/include/Framework/DataAllocator.h
- Framework/Core/test/test_DataAllocator.cxx
> Add tests for PMR-in-DPL

- Steer/DigitizerWorkflow/src/EMCALDigitWriterSpec.cxx
- Steer/DigitizerWorkflow/src/EMCALDigitWriterSpec.h
- Steer/DigitizerWorkflow/src/EMCALDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/EMCALDigitizerSpec.h
- Lambda functions coverted to init and run function
- Local functions to large extend class members of the task
- Documentation added
> [EMCAL-613] Converting digitizer and digits writer spec to DPL task

- Detectors/TPC/reconstruction/CMakeLists.txt
- Detectors/TPC/reconstruction/include/TPCReconstruction/HwClusterer.h
- Detectors/TPC/reconstruction/include/TPCReconstruction/HwClustererParam.h
- Detectors/TPC/reconstruction/src/HwClusterer.cxx
- Detectors/TPC/reconstruction/src/HwClustererParam.cxx
- Detectors/TPC/reconstruction/src/TPCReconstructionLinkDef.h
- Detectors/TPC/workflow/src/ClustererSpec.cxx
- Detectors/TPC/workflow/src/tpc-reco-workflow.cxx
* simplify pedestal treatment
* generalize ADC below threshold treatment
* add command line options for clusterer configuration
> code simplification, command line parameters

- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/Detector.h
- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/V3Services.h
- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
- Detectors/ITSMFT/ITS/simulation/src/V3Services.cxx
The Middle Barrel and Outer Barrel Support Wheels were added to the geometry description of the ITS following the latest blueprints available.
> MB and OB Support Wheels added to geometry

- Framework/Core/include/Framework/ControlService.h
- Framework/Core/include/Framework/DeviceInfo.h
- Framework/Core/include/Framework/DeviceState.h
- Framework/Core/include/Framework/TextControlService.h
- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/src/FrameworkGUIDevicesGraph.cxx
- Framework/Core/src/TextControlService.cxx
- Framework/Core/src/runDataProcessing.cxx
- Framework/Core/test/test_GUITests.cxx
It will then be responsibility of the driver to decide what to do.
For the moment we simply quit on idle state.
The GUI has also been updated to display the state as color code for the
boxes.
> DPL: report streaming state to the driver

- Framework/TestWorkflows/src/flpQualification.cxx
- Use correct matchers for data description according to STFB emulator output
FLP/RAWDATA/0, FLP/RAWDATA/1, FLP/DISTSUBTIMEFRAME/0
- Correcting configuration of inputs and outputs
Right now, the data descriptors are not configurable in the workflow, and neither
they are in the emulator, if anything changes in the emulator, this needs to be
adopted in the code.
The path for input type `readout` has not been tested, behavior should be as before.
Has been tested with DataDistribution emulator:
```
start_Emulator-3FLP-3EPN.sh -f 1 -e 0 -s 1 --flp-dpl-channel=dpl-stf-channel
```
```
o2-testworkflows-flp-qualification --input-type stfb --channel-config "name=readout-proxy,type=pair,method=bind,address=ipc:///tmp/stf-builder-dpl-pipe-0,transport=shmem,rateLogging=1" --2-layer-jobs 2
```
> O2-587 Adjusting flpQualification workflow

- Framework/AnalysisTutorial/CMakeLists.txt
- Framework/AnalysisTutorial/src/filters.cxx
- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/Expressions.h
Does not really work, but it does not harm and compiles fine.
> DPL Analysis: initial mock up of table filters

- Framework/Core/include/Framework/DataDescriptorMatcher.h
- Framework/Core/include/Framework/DataDescriptorMatcher.inc
- Framework/Core/src/DataRelayer.cxx
ping @ktf, rebuild locally and no more problems seen.
> Fix DataDescriptor out of bounds access in DataRelayer, add some protection for similar errors

- Detectors/MUON/MID/Workflow/CMakeLists.txt
- Detectors/MUON/MID/Workflow/include/MIDWorkflow/ClusterizerSpec.h
- Detectors/MUON/MID/Workflow/include/MIDWorkflow/RawReaderSpec.h
- Detectors/MUON/MID/Workflow/include/MIDWorkflow/TrackerSpec.h
- Detectors/MUON/MID/Workflow/src/ClusterizerSpec.cxx
- Detectors/MUON/MID/Workflow/src/RawReaderSpec.cxx
- Detectors/MUON/MID/Workflow/src/RecoWorkflow.cxx
- Detectors/MUON/MID/Workflow/src/TrackerSpec.cxx
- Detectors/MUON/MID/Workflow/src/mid-reco-workflow.cxx
This is the last of the series of PRs allowing to handle the timeframe in the reconstruction workflow.
> Create dedicated data reconstruction workflow

- Framework/Core/src/AODReaderHelpers.cxx
- Framework/Core/src/CommonDataProcessors.cxx
- Framework/Core/test/test_CallbackService.cxx
- Framework/Core/test/test_CustomGUIGL.cxx
- Framework/Core/test/test_CustomGUISokol.cxx
- Framework/Core/test/test_DanglingInputs.cxx
- Framework/Core/test/test_DanglingOutputs.cxx
- Framework/Core/test/test_FrameworkDataFlowToDDS.cxx
- Framework/Core/test/test_ParallelProducer.cxx
- Framework/Core/test/test_SimpleTimer.cxx
- Framework/Core/test/test_SingleDataSource.cxx
- Framework/TestWorkflows/src/dataSamplingParallel.cxx
- Framework/TestWorkflows/src/dataSamplingPodAndRoot.cxx
- Framework/TestWorkflows/src/dataSamplingTimePipeline.cxx
- Framework/TestWorkflows/src/o2DataQueryWorkflow.cxx
- Framework/TestWorkflows/src/o2DiamondWorkflow.cxx
- Framework/TestWorkflows/src/o2OutputWildcardWorkflow.cxx
- Framework/TestWorkflows/src/o2ParallelWorkflow.cxx
- Framework/TestWorkflows/src/o2SyncReconstructionDummy.cxx
- Framework/TestWorkflows/src/test_CompletionPolicies.cxx
> DPL: Add missing includes

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/Expressions.h
- Framework/Core/src/Expressions.cxx
- Cleaned up unnecessary templated code
- Created a parser for the expression tree that generates a set of arrow kernels (WIP)
> Expressions rework

- Framework/Core/include/Framework/ContextRegistry.h
- Framework/Core/include/Framework/ServiceRegistry.h
- Framework/Foundation/include/Framework/TypeIdHelpers.h
Now it should do the hash calculation at compile time.
> DPL: optimize ContextRegistry lookup

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/Expressions.h
- Framework/Core/src/ExpressionHelpers.h
- Framework/Core/src/Expressions.cxx
- Framework/Core/test/test_Expressions.cxx
* Reworked tree-parsing algorithm to use ArrowDatumSpec
* Added a test of tree-parsing algorithm
> Continuing work on expressions

- Framework/Core/include/Framework/ContextRegistry.h
- Framework/Core/include/Framework/ServiceRegistry.h
- Framework/Foundation/include/Framework/TypeIdHelpers.h
Reverts AliceO2Group/AliceO2#2562
> Revert "DPL: optimize ContextRegistry lookup"

- Framework/Foundation/include/Framework/FunctionalHelpers.h
- Framework/Foundation/test/test_FunctionalHelpers.cxx
> DPL Analysis: add has_type_v for pack

- Detectors/Base/include/DetectorsBase/DCAFitter.h
- Detectors/Base/src/DCAFitter.cxx
Correct treatment of non-overlapping circles;
Perform part of calculations in double.
> Fix in DCAfitter

- Detectors/ITSMFT/MFT/tracking/include/MFTTracking/TrackCA.h
- Detectors/ITSMFT/MFT/tracking/src/Tracker.cxx
Replacing dynamic containers on mft tracker by static arrays as recommended by @shahor02 in PR #1885 . Most data in those containers are redundant and will be removed in the future.
> Mft tracker container

- DataFormats/Detectors/EMCAL/include/DataFormatsEMCAL/Constants.h
- Detectors/EMCAL/reconstruction/CMakeLists.txt
- Detectors/EMCAL/reconstruction/include/EMCALReconstruction/CaloFitResults.h
- Detectors/EMCAL/reconstruction/include/EMCALReconstruction/CaloRawFitter.h
- Detectors/EMCAL/reconstruction/include/EMCALReconstruction/CaloRawFitterStandard.h
- Detectors/EMCAL/reconstruction/src/CaloFitResults.cxx
- Detectors/EMCAL/reconstruction/src/CaloRawFitter.cxx
- Detectors/EMCAL/reconstruction/src/CaloRawFitterStandard.cxx
- Detectors/EMCAL/reconstruction/src/EMCALReconstructionLinkDef.h
Development of the raw fitter for O2 using the standard method. It was imported from the original raw fitter in AliRoot.
> [EMCAL-535] Development of the standard raw fitter for O2

- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/V3Services.h
- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
- Detectors/ITSMFT/ITS/simulation/src/V3Services.cxx
The Inner Barrel cylindrical support structure (CYSS) was implemented according to latest blueprints.
> Implement IB CYSS cylinder support structure

- Detectors/TPC/base/include/TPCBase/ModelGEM.h
- Detectors/TPC/base/src/ModelGEM.cxx
> Fine-tuning of the GEM model and update of the documentation 

- Common/MathUtils/include/MathUtils/Utils.h
- GPU/Common/CMakeLists.txt
- GPU/GPUTracking/CMakeLists.txt
@mconcas : This should fix your problem
> Minor fixes for GPU Code

- Common/SimConfig/src/SimConfig.cxx
- run/O2PrimaryServerDevice.h
- run/O2SimDevice.h
In an effort to make PbPb run on slow HPC nodes....
> More verbosity in simulation; Increase communication timeout

- Detectors/TPC/base/include/TPCBase/Painter.h
- Detectors/TPC/base/src/Painter.cxx
- Detectors/TPC/qc/CMakeLists.txt
- Detectors/TPC/qc/include/TPCQC/Clusters.h
- Detectors/TPC/qc/include/TPCQC/Helpers.h
- Detectors/TPC/qc/include/TPCQC/PID.h
- Detectors/TPC/qc/include/TPCQC/TrackCuts.h
- Detectors/TPC/qc/macro/runClusters.C
- Detectors/TPC/qc/macro/runPID.C
- Detectors/TPC/qc/src/Clusters.cxx
- Detectors/TPC/qc/src/Helpers.cxx
- Detectors/TPC/qc/src/PID.cxx
- Detectors/TPC/qc/src/TrackCuts.cxx
- Detectors/TPC/qc/test/test_Clusters.cxx
- Detectors/TPC/qc/test/test_TrackCuts.cxx
- added qc/PID, qc/TrackCut, qc/Clusters classes
- added Helper functions in o2::tpc::qc::helpers
- the o2::tpc::painter::draw functions now return the canvas
> Added qc classes for PID and Clusters

- Detectors/EMCAL/reconstruction/CMakeLists.txt
- Detectors/EMCAL/reconstruction/include/EMCALReconstruction/CaloFitResults.h
- Detectors/EMCAL/reconstruction/macros/RawFitterTESTs.C
- Detectors/EMCAL/reconstruction/src/CaloRawFitter.cxx
- Detectors/EMCAL/reconstruction/src/CaloRawFitterStandard.cxx
- Detectors/TRD/simulation/src/Digitizer.cxx
Testing the standard raw fitter on run2 to run3 converted data
> [EMCAL-535] Testing the standard raw fitter

- Detectors/TRD/simulation/src/Digitizer.cxx
This reverts commit 037dec0b12cf6784230162e8ee181917984de8fe, which
has problems:
* crashing of TRD digitizer
* strange ADC values and much less digits than before
* invalid drift times being processed
> Revert "TRD: Add calibrations with ccdb access to the digitizer (#2615)"

- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/BasicOps.h
- Framework/Core/include/Framework/Expressions.h
- Framework/Core/src/ExpressionHelpers.h
- Framework/Core/src/Expressions.cxx
- Framework/Core/test/benchmark_GandivaExpressions.cxx
- Framework/Core/test/test_ASoA.cxx
- Framework/Core/test/test_Expressions.cxx
> DPL Analysis: add Gandiva compiled expressions to filter tables

- Framework/Core/src/ExternalFairMQDeviceProxy.cxx
The dispatch of output messages might be delayed or failing if downstream queue
is full or unconnected, using async sending in order to log error messages.
No messages are dropped at this stage, if the dispatch is not possible, also
upstream queues will be blocked. This is what we see in O2-962
To complete the PR
Remainder: Need to review handling for failed send operations and dropped messages.
This also applies to the DataProcessor implementation, the heart of the DPL message
dispatch. And the DataRelayer cache lines. See O2-966.
> Printing error messages on output dispatch failure in ExternalFairMQDeviceProxy

- DataFormats/Detectors/ZDC/CMakeLists.txt
- DataFormats/Detectors/ZDC/include/DataFormatsZDC/BCData.h
- DataFormats/Detectors/ZDC/include/DataFormatsZDC/OrbitRawData.h
- DataFormats/Detectors/ZDC/include/DataFormatsZDC/OrbitRecData.h
- DataFormats/Detectors/ZDC/include/DataFormatsZDC/RecEvent.h
- DataFormats/Detectors/ZDC/src/BCData.cxx
- DataFormats/Detectors/ZDC/src/DataFormatsZDCLinkDef.h
- DataFormats/Detectors/ZDC/src/OrbitRawData.cxx
- DataFormats/Detectors/ZDC/src/OrbitRecData.cxx
- DataFormats/Detectors/ZDC/src/RecEvent.cxx
- Detectors/ZDC/base/include/ZDCBase/Constants.h
- Detectors/ZDC/base/src/ModuleConfig.cxx
- Detectors/ZDC/macro/CreateModuleConfig.C
- Detectors/ZDC/macro/CreateSimCondition.C
- Detectors/ZDC/macro/readZDCDigits.C
- Detectors/ZDC/simulation/include/ZDCSimulation/Digitizer.h
- Detectors/ZDC/simulation/src/Digitizer.cxx
- Detectors/ZDC/simulation/src/SimCondition.cxx
Includes temporary protection for anomalous N electrons from the simulation
> Multiple fixes in ZDC digitization

- DataFormats/Detectors/EMCAL/include/DataFormatsEMCAL/Cluster.h
- DataFormats/Detectors/EMCAL/src/Cluster.cxx
- DataFormats/Detectors/EMCAL/src/DataFormatsEMCALLinkDef.h
- Detectors/EMCAL/reconstruction/CMakeLists.txt
- Detectors/EMCAL/reconstruction/include/EMCALReconstruction/Clusterizer.h
- Detectors/EMCAL/reconstruction/include/EMCALReconstruction/ClusterizerParameters.h
- Detectors/EMCAL/reconstruction/include/EMCALReconstruction/ClusterizerTask.h
- Detectors/EMCAL/reconstruction/include/EMCALReconstruction/DigitReader.h
- Detectors/EMCAL/reconstruction/src/Clusterizer.cxx
- Detectors/EMCAL/reconstruction/src/ClusterizerParameters.cxx
- Detectors/EMCAL/reconstruction/src/ClusterizerTask.cxx
- Detectors/EMCAL/reconstruction/src/DigitReader.cxx
- Detectors/EMCAL/reconstruction/src/EMCALReconstructionLinkDef.h
- Detectors/EMCAL/workflow/CMakeLists.txt
- Detectors/EMCAL/workflow/include/EMCALWorkflow/ClusterizerSpec.h
- Detectors/EMCAL/workflow/src/ClusterizerSpec.cxx
- Detectors/EMCAL/workflow/src/RecoWorkflow.cxx
- macro/CMakeLists.txt
- macro/run_clus_emcal.C
Work-in-progress implementation of the EMCAL clusterizer into the O2 framework.
See also the corresponding JIRA ticket.
> [EMCAL-505] Porting EMCAL clusterizer to O2 framework

- Detectors/MUON/MID/Clustering/src/Clusterizer.cxx
- Detectors/MUON/MID/Clustering/src/PreClusterizer.cxx
- Detectors/MUON/MID/Tracking/src/Tracker.cxx
This significantly reduces the computation time
> Remove logs in MID tracker and clusterizer

- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/Core/src/WorkflowHelpers.cxx
- Framework/Utils/src/esd-2-arrow-converter.cxx
Needs https://github.com/AliceO2Group/AliceO2/pull/2691 to be merged first
> Use int64 for enumeration arguments

- GPU/GPUTracking/Base/GPUReconstruction.cxx
- GPU/GPUTracking/CMakeLists.txt
- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/gpucf/GPUTPCClusterFinder.h
- GPU/GPUTracking/gpucf/GPUTPCClusterFinderDump.cxx
> GPU: Add some debug dumpts for TPC Clusterizer

- Framework/TestWorkflows/CMakeLists.txt
- Framework/TestWorkflows/src/test_CCDBFetchToTimeframe.cxx
To confirm that it the fix https://github.com/AliceO2Group/AliceO2/pull/2658 worked, i've prepared an example with a data processor which has a Timeframe and a Condition input. While I am not sure it should be executed in the CI with other tests, it would be nice to keep it somewhere.
Needs https://github.com/AliceO2Group/AliceO2/pull/2692
> An example of a DataProcessor with Timeframe and Condition as inputs

- doc/DoxygenInstructions.md
- doc/doxyfile.in
- Changed INPUT with the explicit list of directories to be processed
(this should hopefully eliminate unwanted empty README pages)
- Fixes in DoxygenInstructions.md
> Improve Doxygen documentation:

- Framework/Logger/include/Framework/Logger.h
@ktf : Could you have a look? I tested this with fmt 6.1.2 running o2-sim, digitizer and tpc reco workflow. The old code is still there for the old fmt. At some point, we can bump fmt in alidist and remove the fallback here.
> Adapt to libfmt >= 6.0

- Detectors/MUON/MCH/Simulation/src/MCHSimulationLinkDef.h
> Fix: suppress obsolete o2::mch::Digit dict.entry in MCHSimulation

- GPU/Common/FlatObject.h
- GPU/TPCFastTransformation/CMakeLists.txt
- GPU/TPCFastTransformation/Spline1D.cxx
- GPU/TPCFastTransformation/Spline1D.h
- GPU/TPCFastTransformation/Spline2D.cxx
- GPU/TPCFastTransformation/Spline2D.h
- GPU/TPCFastTransformation/SplineHelper1D.cxx
- GPU/TPCFastTransformation/SplineHelper1D.h
- GPU/TPCFastTransformation/SplineHelper2D.cxx
- GPU/TPCFastTransformation/SplineHelper2D.h
- GPU/TPCFastTransformation/TPCFastTransformationLinkDef_O2.h
- GPU/TPCFastTransformation/macro/SplineDemo.C
- GPU/TPCFastTransformation/test/testSplines.cxx
Classes for 1-D and 2-D compact cubic spines. 
These splines will replace currently used splines (IrregularSpline* and SemiregularSpline*) in the TPC fast transformation.
> compact cubic splines

- Detectors/MUON/MCH/Simulation/src/Station345Geometry.cxx
Fix of observed 'bug' when running digitization.
> Modify the geometry of rounded slats

- Detectors/MUON/MID/Raw/exe/README.md
- Detectors/MUON/README.md
- doc/DoxygenInstructions.md
- Corrected instructions in DoxygenInstructions.md
- Updated MUON/MID/Raw/exe/README.md to avoid polluting top pages menu
> Fixes in Doxygen documentation

- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/TPCClusterFinder/ClusterAccumulator.cxx
- GPU/GPUTracking/TPCClusterFinder/Clusterizer.cxx
- GPU/GPUTracking/TPCClusterFinder/Deconvolution.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCClusterFinder.h
- GPU/GPUTracking/TPCClusterFinder/GPUTPCClusterFinderDump.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCClusterFinderKernels.h
- GPU/GPUTracking/TPCClusterFinder/NoiseSuppression.cxx
- GPU/GPUTracking/TPCClusterFinder/PackedCharge.h
- GPU/GPUTracking/TPCClusterFinder/clusterFinderDefs.h
* Fix illegal write in noise suppression.
* Add missing kernel call
* Extend data dump
@davidrohr
> TPCClusterFinder: Fix more differences between cpu and gpu version

- Detectors/TRD/base/include/TRDBase/Calibrations.h
- Detectors/TRD/base/include/TRDBase/ChamberStatus.h
Fix the boolean logic in ChamberStatus class for TRD re ticket O2-1022.
> TRD ChamberStatus fix (O2-1022)

- Detectors/ITSMFT/common/base/include/ITSMFTBase/SegmentationAlpide.h
- Detectors/ITSMFT/common/simulation/src/Digitizer.cxx
@shahor02 Hi Ruben. Please, have a look.  And run the CheckClusters.C
> Little fix in the Alpide digitization

- GPU/GPUTracking/TPCClusterFinder/CfUtils.h
- GPU/GPUTracking/TPCClusterFinder/GPUTPCClusterFinderDump.cxx
This pull request fixes an illegal read in tpc cluster finder. Which in turn fixes the cpu clusters.
Also adjust sorting of dumped clusters for easier comparsion.
> TPCClusterFinder: Fix illegal read

- prodtests/CMakeLists.txt
- prodtests/sim_challenge.sh
Script performing a sequence of simulation, reco (later analysis)
tasks. Defines what should currently be working (simulation challenge).
We expect this to grow with new features, such as:
- basic detector checks
- basic checks on the analysis output
- creation of raw data
Script authored by @shahor02.
> First version of standard sim-reco workflow script

- GPU/GPUTracking/Base/GPUO2FakeClasses.h
- GPU/GPUTracking/Base/GPUReconstructionConvert.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCClusterFinder.h
Fix some complaints when compiling with clang
> Fix some complaints when compiling with clang

- GPU/GPUTracking/Base/GPUSettings.h
- GPU/GPUTracking/DataCompression/GPUTPCCompressionKernels.cxx
- GPU/GPUTracking/Standalone/qconfigoptions.h
Option for benchmarking without sorting
> GPU: Add option to disable sorting in differential compression and keep input-cluster order

- Common/Utils/CMakeLists.txt
- Common/Utils/src/CommonUtilsLinkDef.h
- Common/Utils/src/HBFUtils.cxx
- Detectors/CMakeLists.txt
- Detectors/ITSMFT/common/simulation/CMakeLists.txt
- Detectors/ITSMFT/common/simulation/include/ITSMFTSimulation/MC2RawEncoder.h
- Detectors/MUON/MID/Raw/CMakeLists.txt
- Detectors/MUON/MID/Raw/include/MIDRaw/Encoder.h
- Detectors/Raw/CMakeLists.txt
- Detectors/Raw/README.md
- Detectors/Raw/include/DetectorsRaw/HBFUtils.h
- Detectors/Raw/include/DetectorsRaw/RawFileReader.h
- Detectors/Raw/src/DetectorsRawLinkDef.h
- Detectors/Raw/src/HBFUtils.cxx
- Detectors/Raw/src/RawFileReader.cxx
- Detectors/Raw/src/rawfileCheck.cxx
- Detectors/Raw/test/testHBFUtils.cxx
> add raw-file checker, RawFileReader, move HBFUtils to Detectors/Raw

- Detectors/EMCAL/reconstruction/src/RCUTrailer.cxx
Treat errors of the time sample and the L1 phase in the
stream operator as non fatal and print errors (if appearing)
in the stream. Prevents crashing (for the moment) if a
register is not set properly.
> [EMCAL-534] Error treatment of RCUtrailer stream operator

- doc/DetectorSimulation.md
Based on an Alice-Talk post by Rafael Pezzi
> Update DetectorSimulation.md - Generator info added

- GPU/GPUTracking/Base/GPUReconstructionConvert.cxx
- GPU/GPUTracking/Base/GPUReconstructionConvert.h
- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/Global/GPUChainTracking.h
- GPU/GPUTracking/Global/GPUTrackingInputProvider.cxx
- GPU/GPUTracking/Global/GPUTrackingInputProvider.h
- GPU/GPUTracking/Standalone/standalone.cxx
- GPU/GPUTracking/TPCClusterFinder/DecodeZS.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCClusterFinder.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCClusterFinder.h
- GPU/GPUTracking/TPCClusterFinder/GPUTPCClusterFinderDump.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCClusterFinderKernels.cxx
First version of parallel decoding on GPU + required fixes
> Improvements for TPC Clusterizer / Zero Suppression

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/ASoAHelpers.h
- Framework/Core/test/test_ASoAHelpers.cxx
This is not particularly (at all) optimized, as it creates in memory a table
with all the pairs, however we will be able to optimize it later
using C++20 coreroutines.
> DPL Analysis: simple helper to create combinations

- DataFormats/Detectors/FIT/FV0/include/DataFormatsFV0/Hit.h
- Detectors/FIT/FV0/simulation/include/FV0Simulation/DigitizationParameters.h
- Detectors/FIT/FV0/simulation/include/FV0Simulation/Digitizer.h
- Detectors/FIT/FV0/simulation/src/Digitizer.cxx
- Steer/DigitizerWorkflow/src/FV0DigitizerSpec.cxx
This PR implements an [idea of @sawenzel](https://github.com/AliceO2Group/AliceO2/pull/2859#discussion_r372306215)
Speedup is about a factor of 4-5 _w.r.t._ previous version.
I have verified that for 100 pp events the same charges and times are produced.
@mslupeck please double-check that it indeed provides the same output as before.
> SIMD v2 of FT0 Digitizer

- GPU/GPUTracking/Base/cuda/GPUReconstructionCUDA.cu
- GPU/GPUTracking/CMakeLists.txt
- GPU/GPUTracking/Global/GPUChain.h
- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/Merger/GPUTPCGMMerger.cxx
- GPU/GPUTracking/Merger/GPUTPCGMMerger.h
- GPU/GPUTracking/Merger/GPUTPCGMMergerDump.cxx
- GPU/GPUTracking/Standalone/display/GPUDisplay.cxx
- GPU/GPUTracking/Standalone/display/GPUDisplayKeys.cxx
See commit messages for details
> A couple of unrelated improvements for GPU code

- Detectors/ZDC/simulation/include/ZDCSimulation/Detector.h
- Detectors/ZDC/simulation/src/Detector.cxx
A few utility devs for ZDC fast sim, mainly to allow hit creation from a generated photon-response image.
> ZDC fast sim development

- GPU/GPUTracking/Base/cuda/GPUReconstructionCUDA.cu
@fweig : This should fix your problem at default settings
> GPU: Improve GPU memory size detection heuristic for systems not running an X server

- Analysis/Tasks/CMakeLists.txt
- Analysis/Tasks/validation.cxx
> Add skeleton of the QA task 

- Detectors/FIT/FV0/base/src/Geometry.cxx
- Detectors/FIT/FV0/simulation/src/Detector.cxx
[O2-1112] Fix zero-sized shapes in FV0 geometry
> [O2-1112] Fix zero-sized shapes in FV0 geometry: FV0SCREWHOLE0Thick

- GPU/GPUTracking/Base/GPUMemorySizeScalers.h
- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/Merger/GPUTPCGMMerger.cxx
@wiechula : This should fix the problem you reported.
> Fix buffer out of bounce with too many TPC clusters, and increase nCl estimate to account for noise

- GPU/GPUTracking/Global/GPUChainTracking.cxx
@fweig : This should fix the problem you reported
> GPU: Fix copy & paste error

- Examples/Ex1/README.md
Fix links to CMakeInstructions.md in Ex1, Ex2, Ex3, Ex4 and Ex5
> Update README.md files in /Examples

- Steer/DigitizerWorkflow/src/FV0DigitizerSpec.cxx
Bug fix: TFile.h has to be included.
> Add missing include file

- Framework/Core/src/DataDescriptorMatcher.cxx
> Add missing definition for match(ConcreteDataTypeMatcher..) method

- Detectors/Passive/src/Shil.cxx
Avoid double definition of sections in Pcon.
> Avoid double definition of sections in Pcon.

- Detectors/TRD/workflow/CMakeLists.txt
- Detectors/TRD/workflow/include/TRDWorkflow/TRDDigitWriterSpec.h
- Detectors/TRD/workflow/include/TRDWorkflow/TRDDigitizerSpec.h
- Detectors/TRD/workflow/src/TRDDigitWriterSpec.cxx
This supersedes #2941.
@bazinski : This is how I meant we can fix it.
@wiechula : This works for me, do you want to try?
> Fix compilation with GCC 9

- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/AnalysisDataModel.h
- Framework/Core/test/test_ASoA.cxx
This is still work in progress, because we do not actually do any binding
in the processing, yet. It should however compile and still allow people
to use the old "by hand" mechanism.
> DPL Analysis: introduce index columns

- GPU/GPUTracking/Base/GPUReconstructionConvert.cxx
- GPU/GPUTracking/TPCConvert/GPUTPCConvertKernel.cxx
avoid colission when someone does `using namespace std;`
> GPU: Fix HIP compiler warnings

- Detectors/ITSMFT/ITS/macros/test/run_digi2rawVarPage_its.C
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/RawPixelReader.h
- Detectors/ITSMFT/common/simulation/include/ITSMFTSimulation/MC2RawEncoder.h
- Detectors/ITSMFT/common/simulation/src/MC2RawEncoder.cxx
- Detectors/Raw/CMakeLists.txt
- Detectors/Raw/README.md
- Detectors/Raw/include/DetectorsRaw/HBFUtils.h
- Detectors/Raw/include/DetectorsRaw/RawFileWriter.h
- Detectors/Raw/src/DetectorsRawLinkDef.h
- Detectors/Raw/src/HBFUtils.cxx
- Detectors/Raw/src/RawFileReader.cxx
- Detectors/Raw/src/RawFileWriter.cxx
- Detectors/Raw/test/testHBFUtils.cxx
- Detectors/Raw/test/testRawReaderWriter.cxx
See Detectors/Raw/README.md for details
> Added RawDataWriter helper class and its usage for ITS MC->raw conversion

- Analysis/Tasks/validation.cxx
- this replace PR 2956 https://github.com/AliceO2Group/AliceO2/pull/2956 @nburmaso @jgrosseo
> Fix Clang for validation task update

- Detectors/TPC/reconstruction/src/GPUCATracking.cxx
> GPUCF: Add protection for input with >= 4000 time bins, not yet supported

- Framework/Core/ANALYSIS.md
- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/ASoAHelpers.h
- Framework/Core/test/benchmark_ASoAHelpers.cxx
- Framework/Core/test/test_ASoAHelpers.cxx
Combinations of more than 2 tracks with a predicate.
> DPL Analysis: add support for generating multiple combinations

- Detectors/EMCAL/reconstruction/include/EMCALReconstruction/Clusterizer.h
- Detectors/EMCAL/reconstruction/include/EMCALReconstruction/ClusterizerTask.h
- Detectors/EMCAL/reconstruction/include/EMCALReconstruction/DigitReader.h
- Detectors/EMCAL/reconstruction/src/Clusterizer.cxx
- Detectors/EMCAL/reconstruction/src/ClusterizerTask.cxx
- Detectors/EMCAL/reconstruction/src/DigitReader.cxx
- Detectors/EMCAL/reconstruction/src/EMCALReconstructionLinkDef.h
- Detectors/EMCAL/workflow/include/EMCALWorkflow/ClusterizerSpec.h
- Detectors/EMCAL/workflow/src/ClusterizerSpec.cxx
- Detectors/EMCAL/workflow/src/RecoWorkflow.cxx
- macro/run_clus_emcal.C
The Clusterizer, ClusterizerTask, DigitReader, and ClusterizerSpec have been modified so they can read cells and digits.
> [EMCAL-505, EMCAL-643] Modifying the clusterizer to read cells and digits

- Analysis/DataModel/CMakeLists.txt
- Analysis/DataModel/include/Analysis/SecondaryVertex.h
- Analysis/DataModel/src/dummy.cxx
- Analysis/DataModel/src/dumpDataModel.cxx
- Analysis/Tasks/CMakeLists.txt
- Analysis/Tasks/vertexerhf.cxx
- Framework/Core/CMakeLists.txt
We should move here all the basic building blocks of our (ALICE)
AOD schema. I also extracted Gian Michele SecondaryVertex schema
from the task and put it here.
> DPL: introduce Analysis/DataModel

- Framework/Core/src/FrameworkGUIDeviceInspector.cxx
Use instruments on macOS and perf on linux.
> DPL: add support to attach profiler to a given device

- Framework/Core/src/ExternalFairMQDeviceProxy.cxx
The channel configuartion can/must be specified on the command line and
has to match the name which is used the for registering the processing
callback (OnData) in the FairMQ device.
This creates a more descriptive exception.
> Adding a check for name of the configured input channel of the raw-proxy

- Detectors/MUON/MID/Raw/include/MIDRaw/CRUUserLogicEncoder.h
- Detectors/MUON/MID/Raw/include/MIDRaw/Encoder.h
- Detectors/MUON/MID/Raw/src/CRUUserLogicEncoder.cxx
- Detectors/MUON/MID/Raw/src/Encoder.cxx
- Detectors/MUON/MID/Workflow/src/RawWriterSpec.cxx
This PR consists of 2 commits that implement the requirements on TF, superpages, and RDH information.
Please do not squash them.
> Improve MID encoder to pass the raw file checker

- Analysis/Tasks/vertexerhf.cxx
@jgrosseo @ktf @saganatt.
Work on going to validate the results and compare to old loop strategy.
> WIP: Use combination tools in vertexinghf

- Framework/Core/include/Framework/Dispatcher.h
- Framework/Core/src/DataSampling.cxx
- Framework/Core/src/DataSamplingPolicy.cxx
- Framework/Core/src/Dispatcher.cxx
- Framework/Core/test/test_DataSampling.cxx
> A few unrelated Data Sampling improvements

- Detectors/FIT/benchmark/README.md
- Detectors/FIT/benchmark/process.py
The fixes done during the previous PR contained bugs. This small PR fixes them.
> [FIT] Benchmarking tool - bug fix

- Detectors/TOF/reconstruction/include/TOFReconstruction/DecoderBase.h
@preghenella @noferini made virtual destructor to avoid warning.
Blocker for https://github.com/AliceO2Group/QualityControl/pull/336
> Make TOF DecoderBase destructor virtual

- Framework/Core/include/Framework/AnalysisTask.h
This prevents the skipping of the last row in the grouped table
> DPL Analysis: iteration of filter slicing logic

- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/AnalysisTask.h
- Framework/Core/test/test_ASoA.cxx
* Added useful templates is_soa_* to simplify constexpr checks
* Renamed RowViewBase into RowViewCore
* Added new Table::RowViewBase as a layer over RowViewCore that is able to track table origin statically
> DPL Analysis: First iteration of RowView rework

- Analysis/Tasks/jetfinder.cxx
- use configurables for parameters
- fix pt cut
> Update jet finder task

- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/AnalysisTask.h
- Framework/Core/test/test_AnalysisTask.cxx
@ktf now it should be possible to ask for Join::iterator in process
> DPL Analysis: support for requesting iterators on Join/Concat/Filtered

- Detectors/TOF/compression/src/Compressor.cxx
- Detectors/TOF/workflow/src/CompressedDecodingTask.cxx
This fixes two warning in 
Detectors/TOF/workflow/src/CompressedDecodingTask.cxx
It also fixes a signed printf to proper unsigned one in
Detectors/TOF/compression/src/Compressor.cxx
> Fix printout

- DataFormats/Detectors/FIT/FT0/include/DataFormatsFT0/Digit.h
- Detectors/FIT/FT0/base/include/FT0Base/Geometry.h
- Detectors/FIT/FT0/simulation/include/FT0Simulation/Detector.h
- Detectors/FIT/FT0/simulation/include/FT0Simulation/DigitizationParameters.h
- Detectors/FIT/FT0/simulation/include/FT0Simulation/Digitizer.h
- Detectors/FIT/FT0/simulation/src/Detector.cxx
- Detectors/FIT/FT0/simulation/src/Digitizer.cxx
- Steer/DigitizerWorkflow/src/FT0DigitizerSpec.cxx
now embedding and pile-up works
> fix embedding and pile-up 

- Analysis/Tutorials/src/filters.cxx
- Framework/Core/include/Framework/AnalysisTask.h
- Framework/Core/src/Expressions.cxx
* Multiple filters can be declared, and those that are applicable for a given requested table will be merged together with logical 'and'
* Some minor cleanups
> DPL Analysis: multiple declared filters are now automatically merged

- DataFormats/Detectors/EMCAL/CMakeLists.txt
- DataFormats/Detectors/EMCAL/include/DataFormatsEMCAL/AnalysisCluster.h
- DataFormats/Detectors/EMCAL/src/AnalysisCluster.cxx
- DataFormats/Detectors/EMCAL/src/DataFormatsEMCALLinkDef.h
- DataFormats/common/src/CommonDataFormatLinkDef.h
- Detectors/EMCAL/base/CMakeLists.txt
- Detectors/EMCAL/base/include/EMCALBase/ClusterFactory.h
- Detectors/EMCAL/base/src/ClusterFactory.cxx
- Detectors/EMCAL/base/src/EMCALBaseLinkDef.h
- Detectors/EMCAL/reconstruction/include/EMCALReconstruction/Clusterizer.h
- Detectors/EMCAL/reconstruction/include/EMCALReconstruction/ClusterizerTask.h
- Detectors/EMCAL/reconstruction/include/EMCALReconstruction/DigitReader.h
- Detectors/EMCAL/reconstruction/src/Clusterizer.cxx
- Detectors/EMCAL/reconstruction/src/ClusterizerTask.cxx
- Detectors/EMCAL/reconstruction/src/DigitReader.cxx
- Detectors/EMCAL/workflow/include/EMCALWorkflow/ClusterizerSpec.h
- Detectors/EMCAL/workflow/src/ClusterizerSpec.cxx
- Detectors/EMCAL/workflow/src/RecoWorkflow.cxx
> [EMCAL-508, EMCAL-651] Integrate clusterizer in the EMCAL workflow

- DataFormats/Detectors/EMCAL/include/DataFormatsEMCAL/Constants.h
- DataFormats/Detectors/EMCAL/include/DataFormatsEMCAL/Digit.h
- Detectors/EMCAL/simulation/include/EMCALSimulation/Digitizer.h
- Detectors/EMCAL/simulation/include/EMCALSimulation/LabeledDigit.h
- Detectors/EMCAL/simulation/include/EMCALSimulation/SimParam.h
- Detectors/EMCAL/simulation/src/Digitizer.cxx
- Detectors/EMCAL/simulation/src/LabeledDigit.cxx
- Detectors/EMCAL/simulation/src/SimParam.cxx
- Steer/DigitizerWorkflow/src/EMCALDigitizerSpec.cxx
[EMCAL-501,502,518] implemented noise digits, changed time response to use value of function rather than integral, fixed bugs
> [EMCAL-501] noise digits, time response, fix bugs

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/AnalysisDataModel.h
@jgrosseo @shahor02 @ktf Could you have a look whether this make sense to you? Should we add something else?
In contrast to AliRoot, there is no protection against NaN results and, in fact, returning NaN when the operations can't be carried out is the most consistent behaviour, I think.
Do we have any place to document the data model and what various columns are supposed to be? For some it might be obvious, for others the precise meaning might be less clear.
> Add dynamic columns to tracks

- Analysis/Tasks/jetfinder.cxx
@jgrosseo @nzardosh using the dynamic track columns now
> Update jet finder task to use dynamic track columns

- DataFormats/Detectors/EMCAL/include/DataFormatsEMCAL/AnalysisCluster.h
- DataFormats/Detectors/EMCAL/include/DataFormatsEMCAL/EventData.h
- DataFormats/Detectors/EMCAL/include/DataFormatsEMCAL/EventHandler.h
- DataFormats/Detectors/EMCAL/src/AnalysisCluster.cxx
- Detectors/EMCAL/base/include/EMCALBase/ClusterFactory.h
- Detectors/EMCAL/base/src/ClusterFactory.cxx
- Detectors/EMCAL/base/src/EMCALBaseLinkDef.h
- Detectors/EMCAL/reconstruction/include/EMCALReconstruction/Clusterizer.h
- Detectors/EMCAL/reconstruction/src/Clusterizer.cxx
- Detectors/EMCAL/workflow/CMakeLists.txt
- Detectors/EMCAL/workflow/include/EMCALWorkflow/AnalysisClusterSpec.h
- Detectors/EMCAL/workflow/include/EMCALWorkflow/RecoWorkflow.h
- Detectors/EMCAL/workflow/src/AnalysisClusterSpec.cxx
- Detectors/EMCAL/workflow/src/RecoWorkflow.cxx
1. The ClusterFactory has been templated so it can handle both cells and digits.
2. Fixing a problem with the Clusterzier such that now it writes cells indices instead of cells AbsID.
3. Changing the data member in the AnalysisCluster from double to float.
4. A component for testing the event builder and cluster factor in the reco-workflow.
> [EMCAL-651] Testing the cluster builder

- Analysis/Core/include/Analysis/TrackSelection.h
- Analysis/Core/src/TrackSelection.cxx
- Analysis/Tasks/trackselection.cxx
* Use template instead of concrete track row type 
* Remove unnecessary includes in order not to expose expression stuff to rootcling
Note that this still requires major rework: using ROOT objects is not recommended for anything except the final analysis results
> DPL Analysis: untangle track selection

- Framework/Core/include/Framework/AnalysisDataModel.h
- Framework/Core/src/AODReaderHelpers.cxx
- Framework/Core/src/verifyAODFile.cxx
Changes to be in sync with https://github.com/alisw/AliPhysics/pull/13769
> renaming "Events" to "Collisions" in data model

- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/TableBuilder.h
- Framework/Core/test/test_TableBuilder.cxx
First step towards full array support.
> DPL Analysis: add support for arrays to TableBuilder

- Framework/Core/src/LifetimeHelpers.cxx
The message payload size was equal to the counter value, which did not seem to be the original intention, as dh.payloadSize was set to 8. That could potentially lead to memory leaks.
This makes the payload size always set to 8 bytes and the counter value is put inside the message content.
> Correct payload sizes of Lifetime::Enumeration messages.

- GPU/TPCFastTransformation/Spline2D.h
- GPU/TPCFastTransformation/TPCFastTransformManager.cxx
make new TPCFastTransform compile for AliRoot
> make new TPCFastTransform compile for AliRoot

- Analysis/Tasks/jetfinder.cxx
@nzardosh Could you have a look if that looks sane to you? Do we miss anything urgent for the first iteration?
> Add background subtraction for jets

- GPU/GPUTracking/SliceTracker/GPUTPCNeighboursFinder.cxx
20% speed up of the GPU NeighborsFinder via manual loop unrolling.
before:
AMD: 13,692 us NVIDIA: 5,169 us
after:
AMD: 11,406 us NVIDIA: 4,129 us
> 20% speed up of the GPU NeighborsFinder

- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- Detectors/TPC/workflow/src/ClusterDecoderRawSpec.cxx
- Detectors/TPC/workflow/src/ClustererSpec.cxx
- Detectors/TPC/workflow/src/PublisherSpec.cxx
- publishing all TPC sectors in one time slice, even on the same lane
- updating ClustererSpec, ClusterDecoderRawSpec, and CATrackerSpec
- supporting multiple parts per input route by using InputRecord iterator
interface
- drop the custom EOS handling, this is now handled by the DPL driver
> Simplifying TPC reco workflow processors

- CODEOWNERS
> Update all the /DataFormats/Detectors CODEOWNERS O2-1288

- Detectors/Base/CMakeLists.txt
- Detectors/Base/include/DetectorsBase/BaseDPLDigitizer.h
- Detectors/Base/src/BaseDPLDigitizer.cxx
- Detectors/TRD/workflow/src/TRDDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/CPVDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/CPVDigitizerSpec.h
- Steer/DigitizerWorkflow/src/EMCALDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/EMCALDigitizerSpec.h
- Steer/DigitizerWorkflow/src/FDDDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/FT0DigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/FV0DigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/HMPIDDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/ITSMFTDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/MCHDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/MIDDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/PHOSDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/PHOSDigitizerSpec.h
- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
- Steer/DigitizerWorkflow/src/TOFDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/TPCDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/ZDCDigitizerSpec.cxx
Introducing a first version of base class to take away boilerplate
code for DPL digitizers. For the moment
demonstrating how this can be applied to TOF.
> Digitizers: Improved service initialization

- Detectors/TRD/base/include/TRDBase/Digit.h
- Detectors/TRD/macros/CheckDigits.C
- Detectors/TRD/simulation/include/TRDSimulation/Digitizer.h
- Detectors/TRD/simulation/src/Digitizer.cxx
- Detectors/TRD/workflow/src/TRDDigitizerSpec.cxx
> TRD: Implement embedding and improve MC labels (O2-1024 and O2-847)

- GPU/TPCFastTransformation/TPCFastTransform.h
@sgorbuno : Could you have a look? The old formula was definitely wrong, the new one works for me.
> TPC Transform: Fix Z to Time conversion in time frame

- run/SimExamples/Jet_Embedding_Pythia8/pythia8_hard.cfg
- run/SimExamples/Jet_Embedding_Pythia8/pythia8_userhooks_jets.macro
- run/SimExamples/Jet_Embedding_Pythia8/run.sh
This commides provides an example script demonstrating
how embedding simulation can be done and how to configure event generation.
> Simulation example with embedding

- Detectors/MUON/MID/Simulation/src/Detector.cxx
Fix most of the overlaps for MID.
> Place the MID geometry in "YOUT2" if present

- DataFormats/Detectors/ITSMFT/common/include/DataFormatsITSMFT/ClusterTopology.h
- DataFormats/Detectors/ITSMFT/common/include/DataFormatsITSMFT/TopologyDictionary.h
- DataFormats/Detectors/ITSMFT/common/src/ClusterTopology.cxx
- DataFormats/Detectors/ITSMFT/common/src/TopologyDictionary.cxx
- Detectors/ITSMFT/ITS/macros/EVE/DisplayEventsComp.C
- Detectors/ITSMFT/ITS/macros/test/CheckCOG.C
- Detectors/ITSMFT/ITS/macros/test/CheckClusters.C
- Detectors/ITSMFT/ITS/macros/test/CheckLookUp.C
- Detectors/ITSMFT/ITS/macros/test/CheckTopologies.C
- Detectors/ITSMFT/ITS/macros/test/dictionary_integrity_test.C
- Detectors/ITSMFT/ITS/macros/test/run_buildTopoDict_its.C
- Detectors/ITSMFT/ITS/reconstruction/src/CookedTracker.cxx
- Detectors/ITSMFT/ITS/tracking/src/IOUtils.cxx
- Detectors/ITSMFT/ITS/workflow/src/CookedTrackerSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/TrackerSpec.cxx
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/BuildTopologyDictionary.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/LookUp.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/TopologyFastSimulation.h
- Detectors/ITSMFT/common/reconstruction/src/BuildTopologyDictionary.cxx
- Detectors/ITSMFT/common/reconstruction/src/Clusterer.cxx
- Detectors/ITSMFT/common/reconstruction/src/LookUp.cxx
- Detectors/ITSMFT/common/reconstruction/src/TopologyFastSimulation.cxx
- macro/compareTopologyDistributions.C
- macro/run_clus_itsSA.C
- macro/run_trac_its.C
All the elements in the dictionary of cluster-topologies are sorted in decreasing order of frequency, both for common topologies and for groups of rare topologies.
> Sorted dictionary

- Detectors/MUON/MID/Base/src/GeometryTransformer.cxx
This solves: https://alice.its.cern.ch/jira/browse/O2-1317
> Fix path to volume

- Detectors/MUON/MID/Workflow/src/TrackerMCSpec.cxx
- Detectors/MUON/MID/Workflow/src/TrackerSpec.cxx
So that the default is picked up
> Leave the geometry filename empty

- Detectors/TPC/simulation/src/Detector.cxx
Fake overlaps removed, added guard rings.
> Removed fake overlaps. Added guard rings for IFC and OFC

- Detectors/Passive/src/FrameStructure.cxx
Overlap ov19113: B077/B045_6 overlapping B077/BTOFS01_3/BTOFS3_1 ovlp=0.410779
> geo overlap fix: TOF SM passive frame

- Detectors/MUON/MCH/Simulation/src/Geometry.cxx
- Detectors/MUON/MCH/Simulation/src/Station345Geometry.cxx
Fix the main overlaps for the MCH geometry.
> Correct positions of MCH tracking chambers

- Common/MathUtils/include/MathUtils/Utils.h
- Detectors/TPC/reconstruction/src/TPCFastTransformHelperO2.cxx
- GPU/Common/FlatObject.h
- GPU/Common/GPUCommonMath.h
- GPU/TPCFastTransformation/CMakeLists.txt
- GPU/TPCFastTransformation/Spline1D.cxx
- GPU/TPCFastTransformation/Spline1D.h
- GPU/TPCFastTransformation/Spline2D.cxx
- GPU/TPCFastTransformation/Spline2D.h
- GPU/TPCFastTransformation/SplineHelper1D.cxx
- GPU/TPCFastTransformation/SplineHelper1D.h
- GPU/TPCFastTransformation/SplineHelper2D.cxx
- GPU/TPCFastTransformation/SplineHelper2D.h
- GPU/TPCFastTransformation/TPCFastSpaceChargeCorrection.cxx
- GPU/TPCFastTransformation/TPCFastSpaceChargeCorrection.h
- GPU/TPCFastTransformation/TPCFastTransformManager.cxx
- GPU/TPCFastTransformation/TPCFastTransformationLinkDef_O2.h
- GPU/TPCFastTransformation/macro/SplineDemo.C
- GPU/TPCFastTransformation/test/testSplines.cxx
A major reorganization of the spline classes. 
- simplified user interface
-  variable N of output dimensions. It is a template parameter.
- data type float or double
- choice between a self-consistent object (default) or an object with an external parameter store. 
- ROOT I/O
2 @davidrohr:  the code also compiles with AliRoot.
> reorganisation of splines

- Detectors/ITSMFT/ITS/macros/test/CheckTopologies.C
@lbariogl this speed up processing by a large factor (in 20 min the CheckTopologies did not converge when running over 300 pbpb events, now takes <10s) and skip accounting dX,dY in COG calculation if they were not assigned from the MC.
> speed up CheckTopologies and don't account noise in COG calculation

- Framework/Core/include/Framework/DeviceInfo.h
- Framework/Core/src/FrameworkGUIDeviceInspector.cxx
- Framework/Core/src/runDataProcessing.cxx
Propedeutic for AliFatal and https://alice.its.cern.ch/jira/browse/O2-1078
> DPL: keep track of exit status of child processes (O2-1078)

- Framework/Core/include/Framework/AnalysisTask.h
Slight code simplification and a check for grouping inconsistency
> DPL Analysis: check for grouping errors

- Steer/DigitizerWorkflow/src/SimReaderSpec.cxx
- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
This is the final step to remove some workarounds from the early days of
DPL. The first implementation of the TPC digitizer workflow has been using
parallel processing of sector data by distributing the data over multiple
time slices. While the TPC reco workflow has been changed already a while
ago, this has been pending for the digitizer workflow.
Sector data belonging together are now sent within one timeslice.
This includes the following changes:
- Using lane configuration of TPC reco workflow in digitizer workflow
- Sending the context info for TPC sectors in one DPL timeslice (SimReader)
- Defining custom dispatching policy set for the SimReader to publish immediately
allows staggered processing of parallel data sets
- setting completion policy for pipeline processors to process data …
> Applying the DPL timeslice concept correctly for TPC digitizer workflow

- Detectors/ITSMFT/ITS/simulation/src/digi2raw.cxx
- Detectors/Raw/macro/rawStat.C
as on p.10 of https://indico.cern.ch/event/907685/contributions/3818967/attachments/2019436/3376161/20200411_SOX_EOX_Proposal.pdf
> Implement realistic ITS readout partitioning

- prodtests/sim_challenge.sh
- prodtests/sim_performance_test.sh
until https://alice.its.cern.ch/jira/browse/O2-1334 fixed
> take out MCH from production tests

- Detectors/TPC/workflow/src/CATrackerSpec.cxx
@sawenzel : tries to initialize the matbud only upon request, gets rid of the false error.
> Make the matbud file an optional option for the tpc workflow temporarily

- GPU/GPUTracking/Base/GPUReconstructionConvert.cxx
Irrespective of the recent changes, this was a long-standing miscompilation, found when trying to encode / decode a larger amount of data.
> GPU: Fix TPC ZS remaining 8kb buffer size estimation

- Detectors/Raw/include/DetectorsRaw/RDHUtils.h
@shahor02 : I assume this was a typo?
> Fix typo setting memory size in RDHUtils

- Detectors/TPC/base/CMakeLists.txt
- Detectors/TPC/base/include/TPCBase/RDHUtils.h
- Detectors/TPC/base/test/testRDHUtils.cxx
@davidrohr , is this fine for you?
> [TPC] Add RDH mapping for feeId

- Detectors/GlobalTrackingWorkflow/include/GlobalTrackingWorkflow/MatchTPCITSWorkflow.h
- Detectors/GlobalTrackingWorkflow/src/MatchTPCITSWorkflow.cxx
- Detectors/GlobalTrackingWorkflow/src/tpcits-match-workflow.cxx
To allow clean merging with other workflows
> Optionally disable root files i/o of TPC/ITS matching w-flow

- Detectors/ITSMFT/ITS/workflow/include/ITSWorkflow/RecoWorkflow.h
- Detectors/ITSMFT/ITS/workflow/src/RecoWorkflow.cxx
- Detectors/ITSMFT/ITS/workflow/src/its-reco-workflow.cxx
To allow clean merging with other workflows
> Optionally disable root files output of ITS w-flow

- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/TableTreeHelpers.h
- Framework/Core/src/ASoA.cxx
- Framework/Core/src/ArrowDebugHelpers.h
- Framework/Core/src/TableBuilder.cxx
- Framework/Core/src/TableConsumer.cxx
- Framework/Core/test/test_ASoA.cxx
* Add helpers to handle compatibility.
* Remove the explicit mentioning of arrow::Column from everywhere.
> DPL: preparatory work to bump to 0.16.0

- CMakeLists.txt
This follows recent change in alidist alisw/alidist#2157
CMake > 3.15 is also required for #3385.
> Require CMake version 3.17

- Detectors/MUON/MCH/Simulation/CMakeLists.txt
- Detectors/MUON/MCH/Simulation/include/MCHSimulation/GeometryTest.h
- Detectors/MUON/MCH/Simulation/src/Geometry.cxx
- Detectors/MUON/MCH/Simulation/src/GeometryTest.cxx
- Detectors/MUON/MCH/Simulation/src/MCHSimulationLinkDef.h
- Detectors/MUON/MCH/Simulation/test/CMakeLists.txt
- Detectors/MUON/MCH/Simulation/test/testDigitMerging.cxx
- Detectors/MUON/MCH/Simulation/test/testDigitization.cxx
- Detectors/MUON/MCH/Simulation/test/testGeometry.cxx
- Detectors/MUON/MCH/Simulation/test/testResponse.cxx
And add a test to catch this kind of error
> [O2-1334] [MCH] Fix digitizer crash due to volpath change

- Analysis/Tutorials/src/aodreader.cxx
- Analysis/Tutorials/src/aodwriter.cxx
- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/DataAllocator.h
- Framework/Core/include/Framework/TableTreeHelpers.h
- Framework/Core/src/AODReaderHelpers.cxx
- Framework/Core/src/CommonDataProcessors.cxx
- Framework/Core/src/DataAllocator.cxx
- Framework/Core/src/TableTreeHelpers.cxx
- Framework/Core/test/benchmark_TableToTree.cxx
- Framework/Core/test/benchmark_TreeToTable.cxx
- Framework/Core/test/test_TreeToTable.cxx
. Modified TableTreeHelpers such, that boolean table columns can be read/written.
. Moved implementation of TableTreeHelpers from TableTreeHelpers.h to TableTreeHelpers.cxx
. Adapted related classes/tests/examples
> Enabling of reading/writing of boolean columns

- Framework/Utils/include/DPLUtils/RawParser.h
- Framework/Utils/src/RawParser.cxx
- Framework/Utils/test/test_RawParser.cxx
> Adding RDH v6 support to RawParser utility

- Utilities/rANS/CMakeLists.txt
- Utilities/rANS/Readme.md
- Utilities/rANS/include/librans/Coder.h
- Utilities/rANS/include/librans/Decoder.h
- Utilities/rANS/include/librans/DecoderSymbol.h
- Utilities/rANS/include/librans/Encoder.h
- Utilities/rANS/include/librans/EncoderSymbol.h
- Utilities/rANS/include/librans/ReverseSymbolLookupTable.h
- Utilities/rANS/include/librans/SymbolStatistics.h
- Utilities/rANS/include/librans/SymbolTable.h
- Utilities/rANS/include/librans/helper.h
- Utilities/rANS/include/librans/rans.h
- Utilities/rANS/src/SymbolStatistics.cxx
- Utilities/rANS/test/test_ransEncodeDecode.cxx
This adds a simple custom implementation of the rANS entropy coder to O2 which compresses data close to entropy level at high bandwidths.
> O2-1203 rANS library for entropy coding

- Detectors/ITSMFT/MFT/workflow/include/MFTWorkflow/ClusterWriterSpec.h
- Detectors/ITSMFT/MFT/workflow/src/ClusterWriterSpec.cxx
The MFT workflow is broken, this is a temporary fix, allowing the MFT to write and use for tracking the full clusters.
> MFT temporary fix

- GPU/Common/GPUCommonDef.h
Doesn't break anything so far, but was not totally correct
> GPU: Fix protection

- DataFormats/Reconstruction/CMakeLists.txt
- DataFormats/Reconstruction/include/ReconstructionDataFormats/Track.h
- DataFormats/Reconstruction/src/Track.cxx
- Detectors/Vertexing/include/DetectorsVertexing/DCAFitterN.h
- Detectors/Vertexing/include/DetectorsVertexing/HelixHelper.h
- Detectors/Vertexing/src/DetectorsVertexingLinkDef.h
- Detectors/Vertexing/test/testDCAFitterN.cxx
@preghenella this PR should allow to fit any charges combination, as well as b = 0 case.
>  DCAFitter seeder adapted for neut/chrg and neut/neut cases 

- Analysis/Tutorials/CMakeLists.txt
- Analysis/Tutorials/src/tracksCombinations.cxx
- Framework/Core/ANALYSIS.md
- Framework/Core/include/Framework/ASoAHelpers.h
- Framework/Core/test/benchmark_ASoAHelpers.cxx
- Framework/Core/test/test_ASoAHelpers.cxx
Cleaned policies and tests, updated documentation.
> [DPL Analysis] Added faster block combinations for same tables and an analysis example.

- DataFormats/Detectors/TOF/include/DataFormatsTOF/Cluster.h
- Detectors/GlobalTrackingWorkflow/tpcinterpolationworkflow/src/TPCInterpolationSpec.cxx
And use span instead of the vector to retrieve clusters from DPL input
> Force TOF cluster to be messageable

- Analysis/Tutorials/CMakeLists.txt
- Analysis/Tutorials/src/eventMixing.cxx
Hi @ktf @jgrosseo @aalkin ,
this is first working attempt to get mixed-event tracks. `CollisionsCombinationsTask` and `CollisionsFilteringTask` should not be in the user code but they show what is possibly missing in grouping/filtering . Also (@aalkin ?) - will it possible to get a task as `MixedEventsTask` here (with multiple grouping)? 
Please let me know what you think.
> DPL Analysis: First workflow for event mixing

- Detectors/TPC/simulation/run/convertDigitsToRawZS.cxx
Data is required to be ordered in time frames. This requires to write
one file per end point (= link in case of user logic) instead of one
file per cru.
Catch problem in opening digit file and extracting digits tree
> Change to output per endpoint

- Framework/Core/include/Framework/DataSampling.h
- Framework/Core/src/DataSampling.cxx
> [QC-252] Data Sampling: utility methods for multinode setups

- DataFormats/Detectors/TOF/include/DataFormatsTOF/CompressedDataFormat.h
- DataFormats/Detectors/TOF/include/DataFormatsTOF/RawDataFormat.h
- Detectors/TOF/compression/include/TOFCompression/Compressor.h
- Detectors/TOF/compression/include/TOFCompression/CompressorTask.h
- Detectors/TOF/compression/src/Compressor.cxx
- Detectors/TOF/compression/src/CompressorTask.cxx
- Detectors/TOF/compression/src/tof-compressed-inspector.cxx
- Detectors/TOF/compression/src/tof-compressor.cxx
- Detectors/TOF/reconstruction/include/TOFReconstruction/DecoderBase.h
- Detectors/TOF/reconstruction/src/Decoder.cxx
- Detectors/TOF/reconstruction/src/DecoderBase.cxx
- Detectors/TOF/reconstruction/src/Encoder.cxx
- Detectors/TOF/workflow/include/TOFWorkflow/CompressedDecodingTask.h
- Detectors/TOF/workflow/include/TOFWorkflow/CompressedInspectorTask.h
- Detectors/TOF/workflow/src/CompressedDecodingTask.cxx
- Detectors/TOF/workflow/src/CompressedInspectorTask.cxx
This PR brings the new TOF raw data format, updated to the latest DRM firmware.
It also updates the compression algorithm, more specifically in the following points:
- Split compressor main algorithm in multiple routines
- Adapt compressor for CONET data processing
- New definition of diagnostic bits based on enum + new checks
- Use pointers for data summary 
- Use decoding macros from RawDataHeader.h
- Make compressor a template to handle multiple RDH versions
- Write TDC errors in compressed stream
> Rdev compressor devel

- Generators/src/GeneratorPythia8.cxx
This PR brings a temporary patch to the Pythia8 interface of the `o2`.
When running the Pythia8 heavy-ion machinery, particle production vertices are displaced from (0,0,0,0). Likely this is related to the internal machinery that sets the vertices in fm scales.
There is no clear cut to my mind to distinguish these vertices (fm scale) from genuine secondary vertices (mm scale) and it is possible that when decays are on these different scales are mixed.
While waiting for news and for a prescription from the Pythia8 authors the particle production vertices are forced at (0,0,0,0). 
Particle decays in Pythia8 have therefore to be treated with care and inhibited as much as possible. 
Currently the baseline configuration for decays inhibits all those particles with ctau < 0.001 mm.
Therefore …
> Temporary patch Pythia8 to force particle vertex to (0,0,0,0)

- Framework/Utils/include/DPLUtils/MakeRootTreeWriterSpec.h
- Framework/Utils/include/DPLUtils/RootTreeWriter.h
- Framework/Utils/test/test_RootTreeWriterWorkflow.cxx
- adding multipart support
- adding runtime branch selection
> Update of DPL utility RootTreeWriter

- Detectors/Calibration/include/DetectorsCalibration/TimeSlot.h
- Detectors/Calibration/include/DetectorsCalibration/TimeSlotCalibration.h
@chiarazampolli indeed, there was bug in the logics of adding the slots, thanks for spotting.
> Fix in calibration slots queue creation

- Detectors/ITSMFT/ITS/tracking/cuda/src/Context.cu
Adding  Pascal e Turing generation of GPUs to getCudaCores(...)
> Update GPU architecture types

- Detectors/TPC/simulation/run/convertDigitsToRawZS.cxx
@davidrohr , this adds the option `-p` to create parent directories of the output directory in case it does not exist.
> Add option to create output directory

- Analysis/Tasks/eventSelection.cxx
- Framework/Core/include/Framework/AnalysisDataModel.h
This PR depends on the following PR in AliPhysics:
https://github.com/alisw/AliPhysics/pull/14199
It can be merged as soon as new converted data is available
> ZDC info adopted to Run3. Missing Run2v0 info added

- DataFormats/Detectors/ITSMFT/MFT/include/DataFormatsMFT/TrackMFT.h
- DataFormats/Detectors/ITSMFT/MFT/src/TrackMFT.cxx
- Detectors/ITSMFT/MFT/tracking/CMakeLists.txt
- Detectors/ITSMFT/MFT/tracking/include/MFTTracking/MFTTrackingParam.h
- Detectors/ITSMFT/MFT/tracking/include/MFTTracking/TrackExtrap.h
- Detectors/ITSMFT/MFT/tracking/include/MFTTracking/TrackFitter.h
- Detectors/ITSMFT/MFT/tracking/src/MFTTrackingLinkDef.h
- Detectors/ITSMFT/MFT/tracking/src/MFTTrackingParam.cxx
- Detectors/ITSMFT/MFT/tracking/src/TrackExtrap.cxx
- Detectors/ITSMFT/MFT/tracking/src/TrackFitter.cxx
* Fixed track model for MFT track fitting
* Added helix propagation and fitting
* New configurable parameter for MFT Fitting:
* Track model: Quadratic or Helix
* Configure track seeds. The current seed options are under development. Once refined it will be properly documented.
> Update MFT fitter equations, helix propagation, configurable fitter

- Detectors/TOF/compression/src/tof-compressor.cxx
This PR allows the usage of multiple tof-compressor devices in the same workflow.
The number of devices and their input maching channels are defined via a configuration string.
> Define at runtime the number of compressor devices

- Detectors/Passive/include/DetectorsPassive/Hall.h
- Detectors/Passive/src/Hall.cxx
This this is needed to read the Hall specific transport cuts.
> Hall changed to derive from PassiveBase

- prodtests/sim_challenge.sh
Possible stages: sim, digi, reco.
Allows to run the pipeline on existing set of simulated events.
> Option to start sim challenge script at stages

- Common/SimConfig/CMakeLists.txt
- Common/SimConfig/test/testSimCutParam.cxx
- Common/Utils/include/CommonUtils/ConfigurableParam.h
Fixes: https://alice.its.cern.ch/jira/browse/O2-1397
Also adding a new unit test.
> [O2-1397] Bugfix for ConfigurableParam

- Detectors/FIT/FT0/simulation/src/Detector.cxx
- Detectors/FIT/FT0/simulation/src/Digitizer.cxx
- fix noise formula in Digitizer
- make-up geometry settings
> fix noise formula in Digitizer

- Detectors/TOF/base/include/TOFBase/Digit.h
- Detectors/TOF/base/src/Digit.cxx
Add const qualifier to be able to use const Digits
> Add const to getPhiAndEtaIndex

- Detectors/FIT/FT0/simulation/CMakeLists.txt
- Detectors/FIT/FT0/simulation/include/FT0Simulation/DigitizationConstants.h
- Detectors/FIT/FT0/simulation/include/FT0Simulation/Digitizer.h
- Detectors/FIT/FT0/simulation/src/Digitizer.cxx
This commit improves the FT0 digitization run time by a factor of about 3.7
https://alice.its.cern.ch/jira/browse/O2-1402
Please don't merge yet. I'd like to do some more cosmetic changes.
@AllaMaevskaya: I have checked that it reproduces the INFO log messages for 500 pythia events from before. Please check on your side if it reproduces previous behaviour.
> Optimization of FT0 digitization

- Detectors/TOF/reconstruction/include/TOFReconstruction/Encoder.h
- Detectors/TOF/reconstruction/src/Encoder.cxx
- Detectors/TOF/workflow/include/TOFWorkflow/TOFRawWriterSpec.h
- Detectors/TOF/workflow/src/TOFRawWriterSpec.cxx
Accordingly to PR 3516: output dir added and cfg file for raw automaticaly provided
> tof raw encoding: add output dir and cfg file

- Framework/Core/include/Framework/AnalysisTask.h
* When using a `Join` as a grouping table, the index to the first table in the join now serves as a grouping index
> Fix for grouping with soa::Join

- Utilities/Mergers/include/Mergers/FullHistoryMerger.h
- Utilities/Mergers/src/FullHistoryMerger.cxx
- Utilities/Mergers/test/benchmark_FullVsDiff.cxx
- Utilities/Mergers/test/benchmark_MergingCollections.cxx
- Utilities/Mergers/test/multinodeBenchmarkMergers.cxx
- Utilities/Mergers/test/multinodeBenchmarkProducers.cxx
> Various improvements in Mergers benchmarks

- Detectors/TOF/reconstruction/include/TOFReconstruction/Encoder.h
- Detectors/TOF/reconstruction/src/Encoder.cxx
- Detectors/TOF/workflow/src/TOFRawWriterSpec.cxx
- macro/run_digi2raw_tof.C
Accordingly to PR 3516: output dir added and cfg file for raw automaticaly provided
> TOF encoder using RawFileWriter

- Detectors/MUON/MCH/Simulation/src/Digitizer.cxx
change error to warning to avoid blocking of digitizer MCH within ALICE wide simulation
> changed error to warning

- Framework/Core/src/DataProcessingDevice.cxx
Messages on the same channel were supposed to be collected when forwarding
to next processor. This is to make sure that messages receive together are
also forwarded together. The optimization to use the pointer to channel name
string as key in the map could not work because every forward entry has it's
own string. As a consequence, all messages have been sent separately.
> DPL: fix forwarding to make sure messages arrive together

- Framework/Core/include/Framework/DataRefUtils.h
@matthiasrichter @ktf Was there any reason not to do that?
> DataRefUtils - allow to get inherited types of non-T objects

- GPU/Common/GPUCommonDefAPI.h
- GPU/Common/GPUCommonMath.h
- GPU/GPUTracking/Merger/GPUTPCGMMerger.cxx
- GPU/GPUTracking/Merger/GPUTPCGMTrackParam.cxx
- GPU/GPUTracking/Merger/GPUTPCGMTrackParam.h
This PR is basically ready, but it needs #3488 before merging, thus marked as WIP
> GPU: Use inverse transform in track fit / cluster attachment

- GPU/Common/GPUCommonAlgorithm.h
- GPU/Common/GPUDefGPUParameters.h
- GPU/GPUTracking/DataCompression/GPUTPCCompressionKernels.cxx
- GPU/GPUTracking/DataCompression/GPUTPCCompressionKernels.h
- GPU/GPUTracking/Global/GPUChainTracking.cxx
This PR parallelize the compression gather kernel across a single block.
@davidrohr I tried to parallelize the attached and unattached clusters. But no matter how i chose the warp distribution i would lose >1 GB/s in throughput. So i took it out again. :(
> GPU: Parallelize compression gather kernel.

- Utilities/Mergers/CMakeLists.txt
- Utilities/Mergers/include/Mergers/CustomMergeableTObject.h
- Utilities/Mergers/include/Mergers/FullHistoryMerger.h
- Utilities/Mergers/include/Mergers/MergeInterface.h
- Utilities/Mergers/src/FullHistoryMerger.cxx
- Utilities/Mergers/src/MergerAlgorithm.cxx
- Utilities/Mergers/src/ObjectStore.cxx
- Utilities/Mergers/test/test_ObjectStore.cxx
> Fixing memory leaks in Mergers

- Analysis/DataModel/src/dumpDataModel.cxx
- Framework/Core/include/Framework/AnalysisDataModel.h
- Framework/Core/src/AODReaderHelpers.cxx
Return to labels insteed of lbl. Separate tables for tracks and calo clusters. Index from the labels to the MC particles. Updated dumpDataModel
> Updated MC labels

- Framework/Core/include/Framework/InputRecord.h
For correctness, calling the base class of the deleter in the constructors,
this has no effect for the moment as default_delete does not have any state,
but better to do it for the (small) chance of changing the base.
We also allow assignment if the target object is pristine.
> DPL: small changes to the the InputRecord special deleter

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/ConfigContext.h
- Framework/Core/src/ConfigContext.cxx
- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
To avoid replication convert function SimpleDigitizerWorkflow::helpOnCommandLine of Sandro.
> Make helpOnCommandLine a method of ConfigContext

- GPU/GPUTracking/Base/GPUReconstruction.cxx
- GPU/GPUTracking/Base/GPUReconstruction.h
- GPU/GPUTracking/DataCompression/GPUTPCCompression.cxx
- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/Global/GPUChainTracking.h
- GPU/GPUTracking/Global/GPUChainTrackingIO.cxx
- GPU/GPUTracking/Merger/GPUTPCGMMerger.cxx
- GPU/GPUTracking/Merger/GPUTPCGMMerger.h
- GPU/GPUTracking/SliceTracker/GPUTPCTracker.cxx
- GPU/GPUTracking/Standalone/standalone.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCClusterFinder.cxx
- GPU/GPUTracking/TPCConvert/GPUTPCConvert.cxx
- GPU/Utils/FlatObject.h
Several changes to the internals how memory is given to GPU processors. Doesn't change much by itself, but should allow to reduce the memory consumption further in the future.
> Rework GPU memory allocation

- Detectors/TPC/reconstruction/src/GPUCATracking.cxx
- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/Global/GPUChainTracking.h
- GPU/GPUTracking/Global/GPUChainTrackingIO.cxx
- GPU/GPUTracking/Interface/GPUO2Interface.cxx
- GPU/GPUTracking/Standalone/qa/GPUQA.cxx
@shahor02 : This should fix the issue you have been observing
> Fix incorrect cluster IDs

- Detectors/TRD/base/include/TRDBase/CalOnlineGainTables.h
- Detectors/TRD/base/include/TRDBase/Calibrations.h
- Detectors/TRD/base/include/TRDBase/PadCalibrations.h
- Detectors/TRD/base/include/TRDBase/PadParameters.h
- Detectors/TRD/base/include/TRDBase/Tracklet.h
- Detectors/TRD/base/macros/ConvertRun2DigitsAndTracklets.C
- Detectors/TRD/base/macros/PrintTrapConfig.C
- Detectors/TRD/base/macros/Readocdb.C
- Detectors/TRD/base/src/Calibrations.cxx
- Detectors/TRD/base/src/FeeParam.cxx
- Detectors/TRD/base/src/Tracklet.cxx
- Detectors/TRD/simulation/include/TRDSimulation/TrapConfig.h
- Detectors/TRD/simulation/include/TRDSimulation/TrapSimulator.h
- Detectors/TRD/simulation/src/TRDSimulationLinkDef.h
- Detectors/TRD/simulation/src/TrapConfig.cxx
- Detectors/TRD/simulation/src/TrapSimulator.cxx
- Detectors/TRD/workflow/CMakeLists.txt
- Detectors/TRD/workflow/include/TRDWorkflow/TRDTrapSimulatorSpec.h
- Detectors/TRD/workflow/src/TRDDigitReaderSpec.cxx
- Detectors/TRD/workflow/src/TRDDigitizerSpec.cxx
- Detectors/TRD/workflow/src/TRDTrackletWriterSpec.cxx
- Detectors/TRD/workflow/src/TRDTrapSimulatorSpec.cxx
- cmake/O2RootMacroExclusionList.cmake
- tracklet labels assigned and sent on, they are not usable though.
- time records sent with tracklets (have problems, hacked in sending code in subsequent pr )
- tracklet class modified trying to maintain backwards compatability and forward, not ideal.
- parallelisation removed, sorting after is too expensive, might be different for pbpb
- ignore raw data functions for now, they will come in a different PR
> Trapsim update

- GPU/GPUTracking/DataCompression/GPUTPCCompressionKernels.cxx
@davidrohr This PR should fix the gather kernel. It passes the verification now.
> GPU: Fix vectorised memcpy in gather kernel.

- Framework/Core/include/Framework/DataRefUtils.h
- Framework/Core/include/Framework/RawBufferContext.h
- Framework/Core/src/CompletionPolicyHelpers.cxx
nullptr is actually a valid value for empty messages.
> DPL: more payload nullptr checks which should not be

- Detectors/MUON/MCH/Raw/Common/include/MCHRawCommon/SampaCluster.h
- Detectors/MUON/MCH/Raw/Common/src/SampaCluster.cxx
- Detectors/MUON/MCH/Raw/Common/test/testSampaCluster.cxx
- Detectors/MUON/MCH/Raw/Decoder/src/BareElinkDecoder.h
- Detectors/MUON/MCH/Raw/Decoder/src/UserLogicElinkDecoder.h
- Detectors/MUON/MCH/Raw/Decoder/src/testUserLogicEndpointDecoder.cxx
- Detectors/MUON/MCH/Raw/Encoder/Digit/DigitEncoder.cxx
- Detectors/MUON/MCH/Raw/Encoder/Payload/testBareElinkEncoder.cxx
- Detectors/MUON/MCH/Raw/Encoder/Payload/testElinkEncoder.cxx
- Detectors/MUON/MCH/Raw/Encoder/Payload/testGBTEncoder.cxx
- Detectors/MUON/MCH/Raw/Encoder/Payload/testPayloadEncoder.cxx
- Detectors/MUON/MCH/Raw/test/testClosureCoDec.cxx
This allows to keep track of the cluster size also in charge sum mode.
> MCH: added explicit cluster size data member to SampaCluster structure

- Framework/Core/src/TextControlService.cxx
> DPL: speedup parseControl

- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/ArrowTypes.h
- Framework/Core/include/Framework/ConfigParamRegistry.h
- Framework/Core/include/Framework/DataProcessingDevice.h
- Framework/Core/include/Framework/Expressions.h
- Framework/Core/include/Framework/RootTableBuilderHelpers.h
- Framework/Core/include/Framework/TableBuilder.h
- Framework/Core/include/Framework/TableTreeHelpers.h
- Framework/Core/src/FairOptionsRetriever.cxx
- Framework/Core/src/TableTreeHelpers.cxx
- Framework/Core/test/FrameworkCoreTestLinkDef.h
- Framework/Core/test/test_Root2ArrowTable.cxx
- Framework/Core/test/test_StaggeringWorkflow.cxx
- Framework/Core/test/test_TableBuilder.cxx
- Framework/Core/test/test_Task.cxx
- Framework/Core/test/test_TreeToTable.cxx
. Reading/writing of array columns using FixedSizeList
. Modified TableBuilder and ASoA to use FixedSizeList instead of FixedSizeBinary
> DPL: allow reading/writing of array columns

- DataFormats/simulation/include/SimulationDataFormat/DigitizationContext.h
- DataFormats/simulation/src/DigitizationContext.cxx
- Steer/DigitizerWorkflow/src/ITSMFTDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/SimReaderSpec.cxx
- Steer/include/Steer/HitProcessingManager.h
QED events are now handled by DigitizationContext so that
detectors can use them without having to provide custom treatment.
Application to ITS/MFT.
> QED events integrated in DigitizationContext

- DataFormats/simulation/include/SimulationDataFormat/DigitizationContext.h
- DataFormats/simulation/src/DigitizationContext.cxx
- Steer/DigitizerWorkflow/src/ITSMFTDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/SimReaderSpec.cxx
- Steer/include/Steer/HitProcessingManager.h
Reverts AliceO2Group/AliceO2#3763
> Revert "QED events integrated in DigitizationContext"

- Framework/Core/include/Framework/DataSpecUtils.h
- Framework/Core/src/DataSpecUtils.cxx
- Framework/Core/test/unittest_DataSpecUtils.cxx
> Add DataSpecUtils::asConcreteDataDescription

- GPU/GPUTracking/Merger/GPUTPCGMTrackParam.cxx
- GPU/GPUTracking/Merger/GPUTPCGMTrackParam.h
Follow-up to #3772, fully restores the performance of the track fit on NVIDIA
> GPU: Workaround for NVIDIA performance regression in track fit

- Analysis/Tutorials/src/mcHistograms.cxx
- Framework/Core/include/Framework/AnalysisDataModel.h
adding phi resolution histogram
> fixing phi and eta dynamic column definitions

- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/src/ScopedExit.h
Avoid creating the function at each iteration.
> DPL: improve ScopedExit

- Detectors/Passive/data/simcuts_ABSO.dat
- Detectors/Passive/src/Absorber.cxx
- Detectors/Passive/src/Pipe.cxx
- optimized cuts for PIPE RB26 (inside shield)
- higher cuts for tungsten shield in ABSO
- some unused material and media removed from ABSO
> O2 tranportcut opt

- Framework/Core/src/AODReaderHelpers.cxx
This removes the limitation on what original table can be used for an expression-extended table
> DPL Analysis: base new schema directly on original

- Framework/Core/include/Framework/AnalysisTask.h
This can be used to retrieve a service from the Context or
via the Singleton static method "instance()".
> DPL Analysis: add Service helper class

- Framework/Core/src/ExternalFairMQDeviceProxy.cxx
Amending PR #3801. Checking for the requested change of device state before
dispatching messages might silently drop data.
Have to ensure that message are always dispatched, and if the sending does not
succeed an error message is printed. Only after that the pending device state
change is checked and can break the loop.
> Make sure to print an error if data is lost while terminating DPL raw proxy

- Detectors/Raw/README.md
- Detectors/Raw/include/DetectorsRaw/HBFUtils.h
- Detectors/Raw/include/DetectorsRaw/RDHUtils.h
- Detectors/Raw/include/DetectorsRaw/RawFileReader.h
- Detectors/Raw/include/DetectorsRaw/RawFileWriter.h
- Detectors/Raw/src/RawFileReader.cxx
- Detectors/Raw/src/RawFileReaderWorkflow.cxx
- Detectors/Raw/src/RawFileWriter.cxx
- Detectors/Raw/src/rawfileCheck.cxx
- Detectors/Raw/test/testRawReaderWriter.cxx
@mfasDa now you should be able to write/read EMCal raw data via RawFileWriter/Reader, I put in the updated  ``O2/Detectors/Raw/test/testRawReaderWriter.cxx`` an example of toy RORC detector reader/writer, see ``RawReaderWriter_RORC`` section
> Support of RORC detectors by RawFileWriter/Reader

- Detectors/README.md
- README.md
- Added info about Alice Talk in the top README.md
- Added CPV, CTF detectors in Detectors/README.md
> Updated documentation:

- Detectors/MUON/MCH/Simulation/include/MCHSimulation/Detector.h
- Detectors/MUON/MCH/Simulation/include/MCHSimulation/Geometry.h
- Detectors/MUON/MCH/Simulation/include/MCHSimulation/GeometryTest.h
- Detectors/MUON/MCH/Simulation/src/Detector.cxx
- Detectors/MUON/MCH/Simulation/src/Geometry.cxx
- Detectors/MUON/MCH/Simulation/src/GeometryTest.cxx
- Detectors/MUON/MCH/Simulation/src/MCHSimulationLinkDef.h
- Detectors/MUON/MCH/Simulation/test/testGeometry.cxx
Implementing Detector::addAlignableVolumes 
Actual addition of alignable volumes in Geometry::addAlignableVolumesMCH and Geometry::addAlignableVolumesHalfChamber
> Adding MCH alignable volumes

- DataFormats/Detectors/Common/include/DetectorsCommonDataFormats/NameConf.h
- DataFormats/Detectors/Common/src/NameConf.cxx
- Detectors/Base/include/DetectorsBase/MaterialManager.h
- Detectors/Base/src/MaterialManager.cxx
- Detectors/gconfig/SetCuts.h
- macro/o2sim.C
* print summary of processes/cuts per medium into a dedicated file
* warn if application of special cuts fails due to indexing problem
> o2-sim: Summary of process/cut configuration used

- Framework/Core/src/DDSConfigHelpers.cxx
- Framework/Core/test/test_FrameworkDataFlowToDDS.cxx
ID tag is obsolete and was replaced with NAME tag
> Correct DPL export to DDS XML topology

- Framework/Core/include/Framework/ContextRegistry.h
- Framework/Core/include/Framework/DataProcessingDevice.h
- Framework/Core/include/Framework/ServiceRegistry.h
- Framework/Core/src/DataProcessingDevice.cxx
A few more percents off the inner-loop.
> DPL: performance improvements

- Generators/src/DecayerPythia8.cxx
Do not include the decaying particle
> Fix importing decay products:

- prodtests/check_embedding_pileup.sh
I added a couple of lines to make this test work out of the box on macOS too.
> Set up prodtests/check_embedding_pileup.sh to work on macOS

- Detectors/Passive/src/Shil.cxx
Reduces the number of overlaps with MCH.
> corrected positions of shielding inside recesses

- Analysis/Core/src/CorrelationContainer.cxx
- Analysis/Tasks/vertexerhf.cxx
- Detectors/EMCAL/base/src/Geometry.cxx
- Detectors/EMCAL/simulation/src/Detector.cxx
- Detectors/EMCAL/workflow/src/RawToCellConverterSpec.cxx
- Detectors/FIT/FV0/base/src/Geometry.cxx
- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
- Detectors/ITSMFT/MFT/tracking/src/TrackFitter.cxx
- Detectors/ITSMFT/MFT/tracking/src/TrackParamMFT.cxx
- Detectors/MUON/MCH/Simulation/src/Geometry.cxx
- Detectors/MUON/MCH/Tracking/src/TrackParam.cxx
- Detectors/Raw/src/RawFileReader.cxx
- Detectors/TOF/base/src/Geo.cxx
- Detectors/TOF/reconstruction/src/Clusterer.cxx
- Detectors/TOF/simulation/src/Digitizer.cxx
- Detectors/TPC/reconstruction/src/GBTFrameContainer.cxx
- Detectors/TPC/reconstruction/src/HwClusterer.cxx
- Detectors/TPC/reconstruction/src/RawReader.cxx
- Detectors/TRD/base/src/Calibrations.cxx
- Detectors/TRD/base/src/TRDPadPlane.cxx
- Detectors/TRD/simulation/src/TrapConfig.cxx
- Detectors/TRD/simulation/src/TrapConfigHandler.cxx
- Detectors/TRD/simulation/src/TrapSimulator.cxx
- Generators/src/GeneratorFactory.cxx
- Utilities/DataFlow/src/TimeframeValidatorDevice.cxx
- Utilities/aliceHLTwrapper/src/WrapperDevice.cxx
Add a lot of braces, that were missing and violating O2 coding guidelines.
This prevents bumping to new FairLogger due to warnings thrown by MacOS clang.
> Add missing braces

- Common/MathUtils/include/MathUtils/Utils.h
- DataFormats/Reconstruction/include/ReconstructionDataFormats/Track.h
> Track::getPhi and getPhiPos redefined to 0:2pi range

- GPU/GPUTracking/Base/GPUReconstruction.cxx
Treatment of unaligned buffers on the host was working already before, but it failed when a corresponding buffer was allocated on the GPU with the higher alignment. Since the pointers in the buffer were placed at aligned positions, the buffer sizes where slightly different, which lead to an error when copying the buffer from the device to the host.
> Fix one more alignment issue

- Detectors/ITSMFT/MFT/base/include/MFTBase/HeatExchanger.h
- Detectors/ITSMFT/MFT/base/src/HeatExchanger.cxx
Update of the heat exchangers in term of positioning, dimensions and shapes.
> Update of the Heat Exchangers

- Detectors/ITSMFT/MFT/tracking/include/MFTTracking/FitterTrackMFT.h
- Detectors/ITSMFT/MFT/tracking/include/MFTTracking/MFTTrackingParam.h
- Detectors/ITSMFT/MFT/tracking/include/MFTTracking/TrackExtrap.h
- Detectors/ITSMFT/MFT/tracking/include/MFTTracking/TrackFitter.h
- Detectors/ITSMFT/MFT/tracking/src/FitterTrackMFT.cxx
- Detectors/ITSMFT/MFT/tracking/src/TrackExtrap.cxx
- Detectors/ITSMFT/MFT/tracking/src/TrackFitter.cxx
- MCS on MFT track fitting
- Verbosity output option (configurable parameter)
- Enabling linear track fitting with MFT coordinate system
- Fix bug on track propagation (L3 Magnet polarity)
- MFTFitterTrack: fix copy constructor, cleanup
> [MFT] Tracking update: MCS, fix propagator bug, new option for linear fitting

- DataFormats/Headers/include/Headers/DataHeader.h
- Detectors/CTF/workflow/include/CTFWorkflow/CTFReaderSpec.h
- Detectors/CTF/workflow/src/CTFReaderSpec.cxx
- Detectors/Raw/src/RawFileReaderWorkflow.cxx
Reverts AliceO2Group/AliceO2#3892
Was merged accidentally instead of other PR
> Revert "TF counter in the DataHeader"

- DataFormats/simulation/include/SimulationDataFormat/MCTruthContainer.h
- DataFormats/simulation/test/testMCTruthContainer.cxx
Allows adding to the end of the MCTruthContainer an arbitrary range of other container
> extended version MCTruthContainer::mergeAtBack

- Steer/DigitizerWorkflow/src/GRPUpdaterSpec.cxx
@rpezzi with this you don't need to modify the GRPUpdater
> Use DetID::getDataOrigin() in the GRPUpdater

- Framework/Core/src/DriverInfo.h
- Framework/Core/src/runDataProcessing.cxx
More cleanups from moving to libuv.
> DPL Driver: drop unneeded field

- Framework/Core/src/AODReaderHelpers.cxx
If we spot that at least one of the AOD files starts with alien://,
we force invoke TGrid::Connect().
> DPL: make sure we call TGrid::Connect() when needed (O2-1561)

- Analysis/DataModel/CMakeLists.txt
- Analysis/DataModel/include/PID/PIDResponse.h
- Analysis/DataModel/include/PID/PIDTOF.h
- Analysis/DataModel/src/PIDTOF.cxx
- Analysis/Tasks/CMakeLists.txt
- Analysis/Tasks/spectraTOF.cxx
- Add TOF response
- Base class for response
- Example task to use response
> Add base class for TOF pid in analysis tasks

- Framework/Core/src/DataInputDirector.cxx
Fixes opening alien:/// files.
> DPL: use TFile::Open to open files (O2-1561)

- CMakeLists.txt
- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/src/FrameworkGUIDeviceInspector.cxx
- Framework/Foundation/include/Framework/Tracing.h
Useful to debug multithreaded payloads and in general to have some
insight about DPL. Requires AliceO2Group/DebugGUI > v0.2.0 and
to pass -DDPL_ENABLE_TRACING.
> DPL: add support for Tracy profiler / debugger

- Framework/Core/include/Framework/DeviceInfo.h
- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/src/DriverInfo.h
- Framework/Core/src/FrameworkGUIDeviceInspector.cxx
- Framework/Core/src/runDataProcessing.cxx
* Now GUI connects directly to the correct device.
* Tracing more places in DPL
* Reflow misaligned code in preparation for multithreading refactoring.
> DPL: misc fixes related to tracing app

- Detectors/Raw/README.md
- Detectors/Raw/include/DetectorsRaw/RawFileReader.h
- Detectors/Raw/src/RawFileReader.cxx
- Detectors/Raw/src/RawFileReaderWorkflow.cxx
- Detectors/Raw/src/RawFileReaderWorkflow.h
- Detectors/Raw/src/rawfile-reader-workflow.cxx
To create part per HBF use option --part-per-hbf
> raw-file-reader will create part per readout super-page in FMQ multiparts

- Detectors/ITSMFT/MFT/base/src/HalfCone.cxx
A new version of HalfCone 2020
> add new version

- Detectors/Raw/include/DetectorsRaw/RawFileReader.h
- Detectors/Raw/src/RawFileReader.cxx
- Detectors/Raw/src/RawFileReaderWorkflow.cxx
- Detectors/Raw/src/rawfile-reader-workflow.cxx
* Create messages with FMQ channel transort
* Create buffer for every input file
* In part-per-super-page mode read s-page as single chunk
* Add timers
> Multiple fixes in RawFileReader

- Analysis/Core/src/InsertNewRunToTimestamp.cxx
- Analysis/Core/src/RunToTimestamp.cxx
- Analysis/Scripts/insert_Run2_run_to_timestamps.py
- Analysis/Scripts/inspect_Run2_run_to_timestamps.py
- Analysis/Tasks/timestamp.cxx
- Fix ns -> ms conversion
- Add check on ms 
- Add converter inspector
- Improve messages
> Improve run => timestamp conversion

- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFClusterizer.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFClusterizer.h
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFDeconvolution.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFDeconvolution.h
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFNoiseSuppression.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFNoiseSuppression.h
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFPeakFinder.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFPeakFinder.h
Some small improvements for the tpc cluster finder:
- Apply inlining and loop unrolling in more places.
- Simplify function names.
> TPCClusterFinder: Some small improvements

- Framework/Core/include/Framework/DataProcessingDevice.h
- Framework/Core/src/DataProcessingDevice.cxx
The actual data processing is now somewhat reentrant, as it's performed
by static functions which act on a DataProcessingContext object.
This will allow in the future to have different contexes for different threads
making sure that each context either points to a thread safe component,
or to a per thread copy.
> DPL: progress towards multithreading support

- Analysis/Core/include/Analysis/RunToTimestamp.h
- Analysis/Core/src/InsertNewRunToTimestamp.cxx
- Analysis/Core/src/RunToTimestamp.cxx
- Analysis/Scripts/insert_Run2_run_to_timestamps.py
- Analysis/Tasks/centralityTable.cxx
- Analysis/Tasks/eventSelection.cxx
- Analysis/Tutorials/src/ccdbaccess.cxx
- CCDB/README.md
- CCDB/include/CCDB/BasicCCDBManager.h
- CCDB/test/testBasicCCDBManager.cxx
- Also extended README for CCDB access
> Renamed setters for CCDB manager and remove TNamed inheritance 

- Detectors/gconfig/g4config.in
(Geant4 VMC v5-0-p5 or development version is required.)
> Update g4config.in with added tuning for killing looping particles

- Detectors/FIT/FT0/simulation/include/FT0Simulation/DigitizationParameters.h
- Detectors/FIT/FT0/simulation/src/Digitizer.cxx
- Detectors/FIT/FT0/simulation/src/Digits2Raw.cxx
small bugs fix
- not store empty digit
- write last word
> fix small bugs

- Steer/DigitizerWorkflow/src/SimReaderSpec.cxx
User must provide explicitly the x-sections ratio value
> Dont use default qed/hadronic xsections ratio

- Analysis/Tasks/CMakeLists.txt
- Analysis/Tasks/hfcandidatecreator2prong.cxx
- Analysis/Tasks/hftrackindexskimscreator.cxx
* Get particle masses from the PDG database.
* Fix indentation in CMakeLists.txt.
> Get particle masses from the PDG database.

- Detectors/ITSMFT/MFT/base/include/MFTBase/HalfDetector.h
- Detectors/ITSMFT/MFT/base/src/GeometryBuilder.cxx
- Detectors/ITSMFT/MFT/base/src/HalfDetector.cxx
- Detectors/ITSMFT/MFT/base/src/PowerSupplyUnit.cxx
New version of the power supply unit and creation of the 2 half parts
> New Power Supply Unit

- Analysis/DataModel/CMakeLists.txt
- Analysis/DataModel/include/PID/PIDResponse.h
- Analysis/DataModel/include/PID/PIDTPC.h
- Analysis/DataModel/include/PID/ParamBase.h
- Analysis/DataModel/src/PIDTPC.cxx
- Analysis/Tasks/CMakeLists.txt
- Analysis/Tasks/spectraTPC.cxx
- Detectors/TPC/simulation/include/TPCSimulation/Detector.h
- add base class for parametrization
- add table for TPC PID quantities
- add TPC PID task
> Add a proto PID response for TPC signals

- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- GPU/GPUTracking/Base/GPUSettingsList.h
- GPU/GPUTracking/Base/opencl-common/GPUReconstructionOCLInternals.h
- GPU/GPUTracking/Interface/GPUO2InterfaceConfigurableParam.cxx
- GPU/GPUTracking/Standalone/makefiles/makefile_opencl_compiler.cxx
@shahor02 : Could you check whether the defaults work for you now?
> Fix defaults in TPC workflow and add some more options

- Analysis/DataModel/include/Analysis/RecoDecay.h
- Analysis/Tasks/hfcandidatecreator2prong.cxx
- Analysis/Tasks/hftrackindexskimscreator.cxx
- Replace vector calculations back with explicit helper functions.
- Get particle masses outside process().
- Rename mass variables.
- Simplify bool value conditions.
- Fix filling of 3-prong mass histogram.
@ktf
> Version for analysis challenge

- Analysis/Core/include/Analysis/MC.h
- Analysis/Tutorials/src/mcHistograms.cxx
- Framework/Core/include/Framework/AnalysisDataModel.h
Replace the mother and daughter arrays by separate columns.
Introduce impact parameter in the MC collision.
> Replace the mother and daughter arrays by separate columns.

- Detectors/ITSMFT/MFT/base/include/MFTBase/MFTBaseParam.h
- Detectors/ITSMFT/MFT/base/src/HeatExchanger.cxx
Following JIRA request https://alice.its.cern.ch/jira/browse/O2-1046 , the dummy box is removed.
> Remove dummy box to solve illegal case in geometry

- Framework/Core/src/Dispatcher.cxx
> [QC-378] Data Sampling: Support multiple parts in Dispatcher

- Analysis/Tutorials/src/filters.cxx
- Framework/Core/include/Framework/Expressions.h
- Framework/Core/src/Expressions.cxx
Fixes #4050 that was missing '&' and thus had no effect.
> DPL Analysis: working fix for TrackType filter

- Detectors/GlobalTrackingWorkflow/tofworkflow/CMakeLists.txt
- Detectors/GlobalTrackingWorkflow/tofworkflow/include/TOFWorkflow/CalibInfoReaderSpec.h
- Detectors/GlobalTrackingWorkflow/tofworkflow/src/CalibInfoReaderSpec.cxx
- Detectors/GlobalTrackingWorkflow/tofworkflow/src/tof-calibinfo-reader.cxx
- Detectors/TOF/base/src/WindowFiller.cxx
- Detectors/TOF/reconstruction/include/TOFReconstruction/Clusterer.h
- Detectors/TOF/reconstruction/src/Decoder.cxx
- Detectors/TOF/simulation/src/Digitizer.cxx
Add TOF calib reader to provide multi-streams of calib info for calibrator DPL
> TOF CalibInfo reader in

- Detectors/Base/src/GeometryManager.cxx
@shahor02 @sawenzel : This happens frequently in the reco, so perhaps we should reduce this to a warning. Would allow better filtering for real errors.
> Reduce verbosity

- Analysis/DataModel/include/Analysis/RecoDecay.h
- Analysis/DataModel/include/Analysis/SecondaryVertexHF.h
- Analysis/DataModel/include/Analysis/decayUtilities.h
- Analysis/Tasks/hfcandidatecreator2prong.cxx
- Analysis/Tasks/hftrackindexskimscreator.cxx
- Analysis/Tasks/vertexerhf.cxx
`RecoDecay` class provides a set of static functions to calculate properties of reconstructed decay candidates for an arbitrary number of prongs.
> Add RecoDecay class.

- GPU/GPUTracking/Base/GPUReconstruction.cxx
- GPU/GPUTracking/Base/GPUReconstruction.h
- GPU/GPUTracking/Base/GPUReconstructionCPU.h
- GPU/GPUTracking/Base/GPUSettingsList.h
- GPU/GPUTracking/Global/GPUChain.h
- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/Global/GPUChainTracking.h
- GPU/GPUTracking/Standalone/display/GPUDisplay.cxx
Was investigating the random error in the full system test and was hoping this might be the cause, but it turned out I introduced an unrelated problem in the code for the debug output, which is fixed in this PR. Original problem still under investigation.
> Fix memory corruption in debug code + unrelated stuff

- Framework/Core/include/Framework/RawDeviceService.h
FairMQ is thread safe when sending / receiving messages.
> DPL: make RawDeviceService global

- DataFormats/Detectors/FIT/FV0/CMakeLists.txt
- DataFormats/Detectors/FIT/FV0/include/DataFormatsFV0/BCData.h
- DataFormats/Detectors/FIT/FV0/include/DataFormatsFV0/LookUpTable.h
- DataFormats/Detectors/FIT/FV0/include/DataFormatsFV0/RawEventData.h
- DataFormats/Detectors/FIT/FV0/src/DataFormatsFV0LinkDef.h
- DataFormats/Detectors/FIT/FV0/src/RawEventData.cxx
- Detectors/FIT/FV0/CMakeLists.txt
- Detectors/FIT/FV0/base/include/FV0Base/Constants.h
- Detectors/FIT/FV0/base/include/FV0Base/Geometry.h
- Detectors/FIT/FV0/base/src/Geometry.cxx
- Detectors/FIT/FV0/macro/CMakeLists.txt
- Detectors/FIT/FV0/macro/readFV0Digits.C
- Detectors/FIT/FV0/reconstruction/CMakeLists.txt
- Detectors/FIT/FV0/reconstruction/include/FV0Reconstruction/ReadRaw.h
- Detectors/FIT/FV0/reconstruction/src/FV0ReconstructionLinkDef.h
- Detectors/FIT/FV0/reconstruction/src/ReadRaw.cxx
- Detectors/FIT/FV0/simulation/CMakeLists.txt
- Detectors/FIT/FV0/simulation/include/FV0Simulation/DigitizationConstant.h
- Detectors/FIT/FV0/simulation/include/FV0Simulation/Digitizer.h
- Detectors/FIT/FV0/simulation/include/FV0Simulation/Digits2Raw.h
- Detectors/FIT/FV0/simulation/src/Digitizer.cxx
- Detectors/FIT/FV0/simulation/src/Digits2Raw.cxx
- Detectors/FIT/FV0/simulation/src/digit2raw.cxx
Not within the DPL yet - but it's the base for that.
Additionally, fix of circular dependency issue -> some small changes to geometry and digitizer classes
> [FV0] Digits <-> RAW converter

- Framework/Logger/include/Framework/Logger.h
@ktf : Can we remove these workarounds? I assume they are not longer needed.
> Logger: Remove obsolete workarounds

- Detectors/EMCAL/base/src/RCUTrailer.cxx
- Detectors/EMCAL/reconstruction/macros/RawFitterTESTs.C
- Detectors/EMCAL/reconstruction/src/EMCALReconstructionLinkDef.h
- Trailer marker (2<<30) added to trailer words during encoding
- CaloRawFitterGamma2 added to reconstruction LinkDef
- Fix test macro for raw fitter
> [EMCAL-646] Fix encoding of the RCU trailer

- Generators/include/Generators/DecayerPythia8Param.h
- Generators/src/DecayerPythia8.cxx
- Generators/src/GeneratorFactory.cxx
- Generators/src/GeneratorPythia8.cxx
- doc/DetectorSimulation.md
- run/SimExamples/ForceDecay_Lambda_Neutron_Dalitz/README.md
- run/SimExamples/ForceDecay_Lambda_Neutron_Dalitz/run.sh
- run/SimExamples/HF_Embedding_Pythia8/GeneratorHF.macro
- run/SimExamples/HF_Embedding_Pythia8/decays/force_hadronic_D.cfg
- run/SimExamples/HF_Embedding_Pythia8/decays/force_hadronic_D_forceLcChannel1.cfg
- run/SimExamples/HF_Embedding_Pythia8/decays/force_hadronic_D_forceLcChannel2.cfg
- run/SimExamples/HF_Embedding_Pythia8/decays/force_hadronic_D_use4bodies.cfg
- run/SimExamples/HF_Embedding_Pythia8/decays/force_hadronic_D_useDtoV0.cfg
- run/SimExamples/HF_Embedding_Pythia8/o2sim_configuration_bkg.ini
- run/SimExamples/HF_Embedding_Pythia8/o2sim_configuration_sgn.ini
- run/SimExamples/HF_Embedding_Pythia8/pythia8_ccbar.template
- run/SimExamples/HF_Embedding_Pythia8/pythia8_userhooks_ccbar.macro
- run/SimExamples/HF_Embedding_Pythia8/run.sh
- run/SimExamples/README.md
This PR bring some minor adjustments and additions for the Pythia8 event generator and decayer.
The main part is the example simulation for embedding of HF signals into Pb-Pb background, a pretty complex simulation exercise.
> Rdev generator addons + HF embedding example

- Detectors/TRD/macros/convertRun2ToRun3Digits.C
- cmake/O2RootMacroExclusionList.cmake
This macro will allow the user to convert either raw data or run2 digits into run3 digits
> conversion macro for run2 digits

- Detectors/TOF/reconstruction/include/TOFReconstruction/DecoderBase.h
- Detectors/TOF/reconstruction/src/DecoderBase.cxx
- Detectors/TOF/workflow/include/TOFWorkflow/CompressedDecodingTask.h
- Detectors/TOF/workflow/include/TOFWorkflow/CompressedInspectorTask.h
all handlers are now pure virtual functions, to ensure this class is abstract.
> Make DecoderBase class an abstract one

- Detectors/EMCAL/reconstruction/macros/RawFitterTESTs.C
- Detectors/EMCAL/reconstruction/run/rawReaderFile.cxx
STU DDLs numbered 44 and 45 will be rejected as the
raw format is different.
> [EMCAL-646] Reject STU DDLs for FEE raw parsing

- Detectors/Raw/include/DetectorsRaw/RawFileReader.h
- Detectors/Raw/src/RawFileReader.cxx
- Detectors/Raw/src/RawFileReaderWorkflow.cxx
Allows to read data with missing TF, HBF flags, as seen in test ITS data
> Changes to allow reading of incomplete/corrupted data

- Analysis/DataModel/src/dumpDataModel.cxx
- Analysis/Tutorials/CMakeLists.txt
- Analysis/Tutorials/src/vzeroIteration.cxx
- Framework/Core/include/Framework/AnalysisDataModel.h
> adding transient collision id table for v0 and cascades

- Framework/Core/src/runDataProcessing.cxx
The cpu is guaranteed to have been used by the parent.
> DPL: {cpu} expands to always the same CPU

- DataFormats/Reconstruction/include/ReconstructionDataFormats/TrackFwd.h
- DataFormats/Reconstruction/src/TrackFwd.cxx
- Detectors/ITSMFT/MFT/tracking/include/MFTTracking/TrackFitter.h
- Detectors/ITSMFT/MFT/tracking/src/TrackFitter.cxx
Move Kalman update function to TrackParCovFwd (missed this on PR #4040).
> [MFT] Kalman update step moved to TrackParCovFwd

- Analysis/DataModel/include/Analysis/RecoDecay.h
- Analysis/DataModel/include/Analysis/SecondaryVertexHF.h
- Analysis/DataModel/include/Analysis/trackUtilities.h
- Analysis/Tasks/hfcandidatecreator2prong.cxx
- Analysis/Tasks/hftrackindexskimscreator.cxx
- Analysis/Tasks/taskdzero.cxx
Add more RecoDecay functions.
Add more columns to candidate tables.
Add helper function for getting primary vertex.
Rearrange code.
Reorganise namespaces.
Clean up code (includes, namespaces).
Improve naming of variables.
Improve documentation.
> Extend RecoDecay, candidate tables and tasks.

- GPU/GPUTracking/Base/GPUReconstructionKernels.h
- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFChargeMapFiller.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCCFChargeMapFiller.h
- GPU/GPUTracking/TPCClusterFinder/GPUTPCClusterFinder.cxx
- GPU/GPUTracking/TPCClusterFinder/GPUTPCClusterFinder.h
@davidrohr This should fix the issue discussed in #4141.
Also added some small performance improvement for the mc propagation.
> TPCClusterFinder: Fix mc propagation with ZS enabled.

- Framework/Core/src/ResourcesMonitoringHelper.h
* Notice std::to_string truncates at 6 digits
* Cleanup style
> DPL: used fixed notation for resource monitoring

- Detectors/FIT/FT0/workflow/README.md
- Detectors/FIT/README.md
- Detectors/MUON/MCH/README.md
- doc/README.md
- doc/Upgrades.md
Added doxygen keywords where missing
> Fixes in doxygen:

- DataFormats/Detectors/ITSMFT/common/include/DataFormatsITSMFT/ClusterTopology.h
- DataFormats/Detectors/ITSMFT/common/src/TopologyDictionary.cxx
- Detectors/ITSMFT/common/reconstruction/src/BuildTopologyDictionary.cxx
Fix Err2X and Err2Z for groups of rare topologies (previously it was not set) + fix typos
> Fix Err2 for rare topologies

- Detectors/ITSMFT/ITS/tracking/src/Tracker.cxx
> Fix wrong assert

- Detectors/ITSMFT/ITS/tracking/src/Tracker.cxx
fixes an actual problem (was hidden before), merging
> Fix ITS Compilation without -DNDEBUG

- Detectors/CTF/CMakeLists.txt
- Detectors/CTF/test/test_ctf_io_tof.cxx
> add tof ctf unit test

- Detectors/EMCAL/simulation/src/RawCreator.cxx
@mfasDa I've added some standard features which also other converters support.
When testing on ``emcaldigits.root`` I get 
````
o2-emcal-rawcreator -o raw/EMC
[INFO] Registered Link SubSpec=0x00000026(006:02:0) feeID=0x0026 with output to raw/EMC/emcal.root
[INFO] EP:0 CRU:0x0006 Link:3   FEEID:0x0027 SrcID:EMC[18] Packet:0   MemSize:0     OffsNext:0      prio.:0 HS:64 HV:6
[INFO] Orbit:0         BC:0    Stop:0 Page:0     Trg:00000000000000000000000000000000 Par:0     DetFld:0x0000
[INFO] Registered Link SubSpec=0x00000027(006:03:0) feeID=0x0027 with output to raw/EMC/emcal.root
terminate called after throwing an instance of 'o2::emcal::Mapper::FileFormatException'
what():  Failure reading input file: stoi
...
(gdb) 
#6  0x00007ffff7910a61 in o2::emcal::Mapper::init …
```
> Create output dir. if needed, use default digits name

- Detectors/ITSMFT/ITS/tracking/src/Tracker.cxx
> Fix faulty assert

- Analysis/Tasks/PWGCF/dptdptcorrelations.cxx
Also
- circumvent the number of output objects limitation
- circumvent the use of HistogramsRegistry
- circumvent the number of task scope variables limitation
But all this needs to be tested on the grid environment
> The singles distribution for NUA correction extraction

- Detectors/TOF/base/include/TOFBase/Digit.h
- Detectors/TOF/base/src/Digit.cxx
- Detectors/TOF/base/src/WindowFiller.cxx
- Detectors/TOF/workflow/src/CompressedDecodingTask.cxx
Implemented suggestions from PR 4117
> change TOF digit structure: longBC to InteractionRecord

- Detectors/ITSMFT/MFT/macros/test/CMakeLists.txt
- Detectors/ITSMFT/MFT/macros/test/CheckTopologies.C
CheckTopologies.C from ITS was adapted to generate MFT clusters dictionary.
> [MFT] Macro to generate MFT Cluster dictionary
