- devices/aliceHLTwrapper/CMakeLists.txt
- devices/aliceHLTwrapper/Component.cxx
- devices/aliceHLTwrapper/Component.h
- devices/aliceHLTwrapper/EventSampler.cxx
- devices/aliceHLTwrapper/MessageFormat.cxx
- devices/aliceHLTwrapper/MessageFormat.h
- devices/aliceHLTwrapper/WrapperDevice.cxx
- devices/aliceHLTwrapper/WrapperDevice.h
- devices/aliceHLTwrapper/aliceHLTWrapper.cxx
avoiding copy of the output data when creating messages and some bugfixes
There was a mistake when rebasing commit 0e9bdbbfe41d5caa7474119d43be26e367866888 which dropped the std:: attributes for string and vector in the header file
Corrected as a new commit a1bf73ad7a4c4057063bcac32593708006d050e3 now
> update of the aliceHLTWrapper 2nd try

- its/Detector.cxx
- its/Detector.h
- its/Point.cxx
- its/Point.h
- Add track status to point (inside Detector.cxx use mStatus and
mStatus0)
- Add members for point at entrance and time at entrance to the ITS
point
> Add track status to point

- macro/CMakeLists.txt
- macro/load_all_libs.C
This test is needed that gcov knows about all libraries which
belong to the project. gcov still doesn't know about the binaries.
> Add new test which simply load all libraries.

- its/Segmentation.h
- its/UpgradeSegmentationPixel.cxx
- its/UpgradeSegmentationPixel.h
Instead of warnings and boolean return values use exception in case of
out of range errors. Two types of exceptions are implemented:
- InvalidPixelException dealing with pixels out of range
- OutOfActiveAreaException dealing with local (chip) coordinates
exceeding the active area of the chip
Functions to which these cases might apply are updaged in the way that
they throw exceptions in case of errors and do not return any value.
> Change error handling to exceptions

- CMakeLists.txt
- Generators/CMakeLists.txt
- devices/aliceHLTwrapper/WrapperDevice.cxx
- devices/aliceHLTwrapper/WrapperDevice.h
- devices/aliceHLTwrapper/aliceHLTWrapper.cxx
- topologies/o2prototype_topology.xml
This PR mainly reflects the usage of collections in DDS. Furthermore there were changes to the FairMQ state machine and the wrapper device has been adapted to that.
> Changes from the July DDS workshop

- CMakeLists.txt
- cmake/modules/ROOTMacros.cmake
Copy ROOTMacros.cmake from FairRoot to cmake/modules. Do some small change in the cmake script which is needed to find all include directories. Change the directory
order of the CMAKE_MODULE_PATH such that cmake/modules has highest priority. Search for package IWYU and create build target to use it.
> Implement target checkHEADERS to use the include-what-you-use tool.

- README.md
- doxygen/doxyfile.in
Add more documentation 
clean the oxygen configuration file
> Documentation 

- devices/flp2epn-distributed/CMakeLists.txt
- devices/flp2epn-distributed/EPNReceiver.cxx
- devices/flp2epn-distributed/EPNReceiver.h
- devices/flp2epn-distributed/FLPSender.cxx
- devices/flp2epn-distributed/FLPSender.h
- devices/flp2epn-distributed/FLPSyncSampler.cxx
- devices/flp2epn-distributed/FLPSyncSampler.h
- devices/flp2epn-distributed/run/runEPNReceiver.cxx
- devices/flp2epn-distributed/run/runFLPSender.cxx
- devices/flp2epn-distributed/run/runFLPSyncSampler.cxx
- devices/flp2epn-distributed/runO2Prototype/runFLPSyncSampler.cxx
- devices/flp2epn-distributed/test/testFLP2EPN-distributed.sh.in
- devices/flp2epn/O2EPNex.cxx
- devices/flp2epn/O2EPNex.h
- devices/flp2epn/O2EpnMerger.cxx
- devices/flp2epn/O2EpnMerger.h
- devices/flp2epn/O2FLPex.cxx
- devices/flp2epn/O2FLPex.h
- devices/flp2epn/O2Merger.cxx
- devices/flp2epn/O2Merger.h
- devices/flp2epn/O2Proxy.cxx
- devices/flp2epn/O2Proxy.h
- Add integration test for flp2epn-distributed.
Test starts a chain of flpSyncSampler, 2 flpSenders and 2 epnReceivers.
100 time frames are generated.
Test succeeds if the timeframes are correctly distributed, merged and acknowledged.
- Use smart pointer methods in flp2epn and flp2epn-distributed devices.
> Add integration test for flp2epn-distributed devices

- Generators/Pythia8Generator.h
- devices/flp2epn-distributed/EPNReceiver.cxx
- devices/flp2epn-distributed/FLPSender.cxx
- devices/flp2epn-distributed/FLPSyncSampler.cxx
- devices/flp2epn-distributed/run/runEPNReceiver.cxx
- devices/flp2epn-distributed/run/runFLPSender.cxx
- devices/flp2epn-distributed/run/runFLPSyncSampler.cxx
- devices/flp2epn-distributed/runO2Prototype/runEPNReceiver.cxx
- devices/flp2epn-distributed/runO2Prototype/runFLPSender.cxx
- devices/flp2epn-distributed/runO2Prototype/runFLPSyncSampler.cxx
- devices/flp2epn/O2EPNex.cxx
- devices/flp2epn/O2EpnMerger.cxx
- devices/flp2epn/O2Merger.cxx
- devices/flp2epn/run/runEPN.cxx
- devices/flp2epn/run/runEPN_M.cxx
- devices/flp2epn/run/runFLP.cxx
- devices/flp2epn/run/runMerger.cxx
- devices/flp2epn/run/runProxy.cxx
Eliminate several warnings:
- member initialization order for some device classes `[-Wreorder]`.
- comparison between signed and unsigned integer `[-Wsign-compare]`.
- member initialization lists `[-Weffc++]`.
> Eliminate warnings

- o2cdb/CMakeLists.txt
- o2cdb/ConditionsMQServer.cxx
- o2cdb/ConditionsMQServer.h
- o2cdb/README
- o2cdb/fill_local_ocdb.C
This commit also requires the following change (one added line, string data members made protected) in parmq/ParameterMQServer.h in FairRoot:
diff --git a/parmq/ParameterMQServer.h b/parmq/ParameterMQServer.h
index 2253b37..661d9c7 100644
--- a/parmq/ParameterMQServer.h
+++ b/parmq/ParameterMQServer.h
@@ -53,6 +53,7 @@ class ParameterMQServer : public FairMQDevice
private:
FairRuntimeDb* fRtdb;
+  protected:
std::string fFirstInputName;
std::string fFirstInputType;
std::string fSecondInputName; 
Cheers,
Raffaele
> Let ConditionsMQServer derive from FairRoot/parmq/ParameterMQServer

- DataFormats/Generic/test/testMessageList.cxx
This commit was not part of the pull request but got merged accidentally.
Revert "Bugfix: replace static_cast by local variable for type conversion"
This reverts commit d525a090af6eb016c7d92783b9dc3cc1478d2d72.
The type cast has not been the problem.
> Reverting accidentally merged commit

- CCDB/src/runConditionsClient.cxx
- CCDB/src/runConditionsServer.cxx
Call the ParseAll without if statement as it does not return anything
Remove outdated way of choosing the transport engine
> Adapt conditions to new scheme

- Detectors/TPC/simulation/include/Digitizer.h
- Detectors/TPC/simulation/include/DigitizerTask.h
Add the namespaces to the classdef  otherwise the classes cannot be used in the macro on MAC OS with ROOT6
> add the namespaces to the classdef 

- cmake/O2Dependencies.cmake
Fixes compilation issue (Could not find libsodium)
> Link against the dynamic library of ZeroMq

- Utilities/aliceHLTwrapper/CMakeLists.txt
- cmake/O2Dependencies.cmake
Wether or not to use DDS for a given bucket should be a centrally
enforced decision, not left to single modules.
> Avoid if condition in module CMakeLists.txt

- cmake/O2Utils.cmake
Some debug (STATUS) messages in the O2 cmake utilities have not yet been commented out and flood the output - have now commented out the two lines
> Commenting out debug messages in the cmake utilities

- cmake/O2Dependencies.cmake
- cmake/O2Utils.cmake
I have introduced a new property for the bucket definition to allow for include directories declared as 'SYSTEM'. That suppresses the warnings from boost again as we had it before.
@rbx @ktf @MohammadAlTurany @Barthelemy could you have a look if this makes sense
> Adding property SYSTEMINCLUDE_DIRECTORIES to bucket definition

- Utilities/aliceHLTwrapper/include/TPCRawCluster.h
This is a re-definition of AliHLTTPCRawCluster from AliRoot HLT. The
definition is self-consistent an comes also with a wrapper for a binary
data block to easily open binary files and access of individual raw
clusters.
TODO: a consistency check needs to be added which conditionally (based on
availability of AliRoot during build) checks if the defined structure
matches the one from AliRoot.
new file:   ../aliceHLTwrapper/include/TPCRawCluster.h
> Adding definition of HLT TPC raw cluster format

- Detectors/ITSMFT/MFT/base/CMakeLists.txt
- Detectors/ITSMFT/MFT/base/include/MFTBase/EventHeader.h
- Detectors/ITSMFT/MFT/base/src/EventHeader.cxx
- Detectors/ITSMFT/MFT/base/src/MFTBaseLinkDef.h
- Detectors/ITSMFT/MFT/reconstruction/CMakeLists.txt
- Detectors/ITSMFT/MFT/reconstruction/config/reco_merger.json
- Detectors/ITSMFT/MFT/reconstruction/include/MFTReconstruction/FindHits.h
- Detectors/ITSMFT/MFT/reconstruction/include/MFTReconstruction/FindTracks.h
- Detectors/ITSMFT/MFT/reconstruction/include/MFTReconstruction/devices/Merger.h
- Detectors/ITSMFT/MFT/reconstruction/include/MFTReconstruction/devices/TaskProcessor.h
- Detectors/ITSMFT/MFT/reconstruction/include/MFTReconstruction/devices/TaskProcessor.tpl
- Detectors/ITSMFT/MFT/reconstruction/src/FindHits.cxx
- Detectors/ITSMFT/MFT/reconstruction/src/FindTracks.cxx
- Detectors/ITSMFT/MFT/reconstruction/src/devices/FileSink.cxx
- Detectors/ITSMFT/MFT/reconstruction/src/devices/Merger.cxx
- Detectors/ITSMFT/MFT/reconstruction/src/devices/Sampler.cxx
- Detectors/ITSMFT/MFT/reconstruction/src/runMFTrecoFileSink.cxx
- Detectors/ITSMFT/MFT/reconstruction/src/runMFTrecoMerger.cxx
- Detectors/ITSMFT/MFT/reconstruction/src/runMFTrecoSampler.cxx
- Detectors/ITSMFT/MFT/reconstruction/src/runMFTrecoTaskProcessor.cxx
Implement the reconstruction (MC points to hits and hits to tracks - one after the other) from two simulation files, using two samplers, two processor, one merger and one sink.
> MFT: implement reconstruction with sampler + processor + merger + sink

- Detectors/ITSMFT/ITS/simulation/src/DigitizerTask.cxx
- macro/run_clusterer.C
- macro/run_digi.C
- macro/run_sim.C
Problem: Digitizer was created in the constructor of the task and in the ctor of the digitiser it tries to access the geometry which is still not available at this stage.   
Solution: The Digitizer is created and initialised in the init of the Task.
No need to load the geometry separately (This was the work around!) it is taken now from the parameters 
Remove hardcoded paths.
Switch off  track visualisation
Set the verbosity to low in the macro
> Initialization error

- Utilities/aliceHLTwrapper/src/aliceHLTEventSampler.cxx
- Utilities/aliceHLTwrapper/src/aliceHLTWrapper.cxx
DDS Intercom API has been changed in version v1.4 without maintaining
backward compatibility. As it is not a matter of changing a few lines
of code, DDS support is disabled now in the aliceHLTWrapper. The device
needs a major rewrite to adopt to the latest changes in FairRoot and
the new DDS Intercom API
> Disable DDS support in aliceHLTWrapper, Fixes #183

- macro/run_sim.C
When using "const int" cling claim to use reference and not value which ends with an error as the kNRow and kNCol  are local variables. 
For all other variables in macro there is an implicit cast to float from const double 
Still need to be understood but removing the const it works!!!
> Problem with cling when using const

- Utilities/DataCompression/test/test_dc_primitives.cxx
- Utilities/DataCompression/test/test_huffmancodec.cxx
- Utilities/DataCompression/tpccluster_parameter_model.h
Test program development squashed into single commit per executable, both moved to `Utilities/DataCompression/test`. Integration to cmake will follow soon.
Follow-up-change in tpccluster_parameter_model.h according to moved header files.
> Squashed development of test programs for Utility/DataCompression

- DataFormats/Headers/include/Headers/DataHeader.h
- DataFormats/Headers/src/DataHeader.cxx
* Generic methods to convert a string to a uint of variable size, basically it allows to change
```
String2uint64("DESCRIPTION") -> String2<uint64_t>("DESCRIPTION")
```
It goes through the same template code for all types.
* Generic implementation for N-byte descriptors, using it for the DataOrigin
* Adding also a type conversion operator for `AliceO2::Header::Block` to extract the first `BaseHeader`
> Generic tools for the data header

- Examples/flp2epn-distributed/CMakeLists.txt
As is those get installed in the BUILD directory, but not in the
installation area.
> Install FLP2EPN Example scripts and configs

- DataFormats/Headers/src/DataHeader.cxx
This is a minor issue, printf needs the correct format specifier but 'llu'
for long long unsinged int has a different underlying type for different
architectures. On some 64bit systems it does not match the type for uint64_t,
on 32 bit systems, long long is the 64bit integer.
Solved by casting the variable to long long unsinged.
We can probably avoid this by switching to stream output.
> Handling a compiler warning for printf formatting

- DataFormats/Headers/include/Headers/DataHeader.h
- Making types start with capital letter following coding conventions
- Fixing also a typo in the documentation
> Internal changes in DataHeader fo follow coding guidelines

- DataFormats/Headers/test/dataHeaderTest.cxx
Trying to fill unit tests for DataHeaders.
This test fails when the DataDescription is taking the string from memory which is followed by garbage.
> Proper unit test for DataDescription

- Generators/include/Generators/Pythia8Generator.h
- Generators/src/Pythia8Generator.cxx
Pythia8 include path is defined and used in the O2Dependancies.cmake, no need for dirctory name in include
> Pythia8 includes

- DataFormats/Headers/include/Headers/DataHeader.h
- DataFormats/Headers/src/DataHeader.cxx
Fixes #240 
Adding static_assert checks to the `String2<type>` initializer, mainly to catch the case of too long strings.
Also a bug in the generation of the DataDescriptor from strings up to 8 bytes has been fixed.
> Adding compile time checks for string initializers of `AliceO2::Header::Descriptor` etc

- Generators/include/Generators/Pythia8Generator.h
- Generators/src/Pythia8Generator.cxx
- cmake/O2Dependencies.cmake
This PR should fix issue 246 and lead back to a fully compiling dev branch on jenkins.
It turns out that there is an inconsistent use of upper and lower case spelling for pythia6.
The O2 recipes build a libpythia6 but sometimes (FairRoot + Generators) ask for libPythia6
I changed this code to comply with the O2 build system for the moment.
> Fix issue #246

- CCDB/CMakeLists.txt
- DataFormats/Headers/CMakeLists.txt
- Detectors/ITSMFT/MFT/reconstruction/CMakeLists.txt
- Examples/ExampleModule1/CMakeLists.txt
- Examples/ExampleModule2/CMakeLists.txt
- Examples/flp2epn-distributed/CMakeLists.txt
- Examples/flp2epn/CMakeLists.txt
- Utilities/O2MessageMonitor/CMakeLists.txt
- Utilities/QC/QCMerger/CMakeLists.txt
- Utilities/QC/QCMetricsExtractor/CMakeLists.txt
- Utilities/QC/QCProducer/CMakeLists.txt
- Utilities/QC/QCViewer/CMakeLists.txt
- Utilities/aliceHLTwrapper/CMakeLists.txt
- cmake/O2Utils.cmake
* do no longer reset variables gives to O2_GENERATE_LIBRARY
* resulting simplification of CMakeLists.txt files
see issue #149
> fix cmake issue with O2_GENERATE_LIBRARY

- DataFormats/Headers/include/Headers/DataHeader.h
- DataFormats/Headers/test/dataHeaderTest.cxx
Added default initialization for the default constructor and a constructor
from the integer type. Declaring all constructors constexpr.
Adding type cast operator to simplify the usage of Descriptor struct which
returns its integer member.
Adding a runtime init function in both DataDescription and generic
Descriptor to allow for use cases where the initializer string comes only
at runtime. The naming of the functions indicates that this is not a
compile-time feature and must be used with care.
Defining a type alias DataHeader::SubSpecificationType for the type of
member subSpecification of the DataHeader to allow generic use outside
the struct.
> Further work on Descriptor struct: unit test, runtime init

- DataFormats/Headers/include/Headers/DataHeader.h
This is because `void *` is what is actually returned by ZeroMQ /
FairMQ. This way we avoid one cast in user code.
> Allow void* based API to AliceO2::Headers::get<>

- cmake/O2Utils.cmake
Fix #254: Automatically find internal header files in module's src directory
Fix #256: conditional installation of public headers
> Fix #254 and Fix #256 in O2Utils.cmake

- DataFormats/CMakeLists.txt
- DataFormats/Headers/include/Headers/TimeStamp.h
- DataFormats/TimeFrame/CMakeLists.txt
- DataFormats/TimeFrame/include/TimeFrame/TimeFrame.h
- DataFormats/TimeFrame/src/TimeFrame.cxx
- DataFormats/TimeFrame/src/TimeFrameLinkDef.h
- DataFormats/TimeFrame/test/TimeFrameTest.cxx
- cmake/O2Dependencies.cmake
This is a working piece of deployable unit that brings in a skeleton TimeFrame class (including working ROOT IO + unit test).
This can now be used by the DataFlow effort and expanded thereafter.
> Skeleton for a TimeFrame class

- Common/Field/src/MagFieldContFact.cxx
- Common/Field/src/MagneticWrapperChebyshev.cxx
- Common/MathUtils/src/Chebyshev3D.cxx
- DataFormats/simulation/src/Stack.cxx
- Detectors/ITSMFT/ITS/base/src/GeometryManager.cxx
- Detectors/ITSMFT/ITS/base/src/GeometryTGeo.cxx
- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
- Detectors/ITSMFT/ITS/simulation/src/GeometryHandler.cxx
- Detectors/ITSMFT/ITS/simulation/src/V11Geometry.cxx
- Detectors/ITSMFT/ITS/simulation/src/V1Layer.cxx
- Detectors/ITSMFT/common/base/src/SegmentationPixel.cxx
- Detectors/ITSMFT/common/simulation/src/Chip.cxx
- Detectors/Passive/src/Cave.cxx
- Detectors/Passive/src/GeoCave.cxx
- Detectors/Passive/src/Magnet.cxx
- Detectors/Passive/src/PassiveContFact.cxx
- Detectors/TPC/simulation/src/Detector.cxx
- Examples/ExampleModule1/test/testExampleModule1.cxx
- Examples/flp2epn/src/O2FLPex.cxx
Description of the check can be found at:
https://clang.llvm.org/extra/clang-tidy/checks/modernize-deprecated-headers.html
> Fix all the modernize-deprecated-headers errors reported by clang-tidy

- Utilities/DataFlow/src/SubframeBuilderDevice.cxx
This is a follow up for the previously committed fix for issue #279,
linker problem with private constexpr class member.
Added redeclaration of all private constexpr data members and enhancing
the comment in the code.
From C++11 on, constexpr static data members are implicitly inlined.
Redeclaration is still permitted, but deprecated. Some compilers do
not implement this standard correctly. It also has to be noticed that
this error does not occur for all the other public constexpr members.
Closing #282. Whether the variables have to be constexpr (and fixed) or
configurable will be handled when the work on the devices is resumed.
> Redeclaration of private constexpr class member to avoid linker error

- DataFormats/Headers/include/Headers/DataHeader.h
- DataFormats/Headers/test/dataHeaderTest.cxx
The DataDescription structure has a 16 Byte field, which is
initialized by two calls to String2<uint64_t>.
This warning occurs if the actual string is shorter than 9 characters,
when only the first integer field can be filled. The condition is
correctly handled, but in clang the code branch is still compiled,
though not called. It turns out that the previously chosen offset
parameter was not a good choice. Using 0 as offset masks the warning.
Also extending the unit test in order to check the underlying
integer member.
> Fix #268 DataDescription c'tor: String2<uint64_t> offset adjusted

- Detectors/Base/src/BaseLinkDef.h
- Detectors/Base/test/testBasicHits.cxx
* ROOT only provides dictionaries for <double> specializations
of their Point3D, etc. classes
* we need to create a dictionary for the <float> case
* extend unit test to check correct working for <double> case, too
> Fix remaining ROOT IO problem for basic hit classes

- doc/CMakeLists.txt
If we turn documentation installation on, then we must make sure that the documentation is generated. It is therefore added to the target ALL. 
It is a follow up of https://github.com/AliceO2Group/AliceO2/pull/298
> Make sure documentation is generated in case we must install it

- DataFormats/simulation/CMakeLists.txt
- DataFormats/simulation/include/SimulationDataFormat/BaseHits.h
- DataFormats/simulation/src/SimulationDataLinkDef.h
- DataFormats/simulation/src/Stack.cxx
- DataFormats/simulation/test/testBasicHits.cxx
- Detectors/Base/CMakeLists.txt
- Detectors/Base/src/BaseLinkDef.h
* restructuring O2 hit class; we need to have
a common base class with an interface as needed by the particle stack
* move class to DataFormats/simulation to avoid cyclic dependency
* commit achieves a complete decoupling from FairMC point; now
all of our detectors have to use the AliceO2::BaseHit and derived classes
> Adding hit mother class; move to DataFormats/simulation

- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/Detector.h
- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
- Detectors/ITSMFT/common/simulation/include/ITSMFTSimulation/Point.h
- Detectors/ITSMFT/common/simulation/src/Chip.cxx
- Detectors/ITSMFT/common/simulation/src/ITSMFTSimulationLinkDef.h
- Detectors/ITSMFT/common/simulation/src/Point.cxx
- cmake/O2Dependencies.cmake
1) Adopt new BaseHit::BaseXYZE_f_f as a base class for ITS hit
2) Make sure just 1 hit is generated at each traversal of sensor by track
3) Lot of cleaning in ITS/Detector
4) Squashed separate commit to make ITSMFT Point c-tor inline
The previous PR #312 became polluted due, reopening here after squashing 2 relevant commits
> Fix of ITS hit generation (instead of #312)

- CCDB/include/CCDB/ConditionsMQServer.h
- CCDB/src/ConditionsMQServer.cxx
- CCDB/src/IdPath.cxx
- Detectors/ITSMFT/ITS/base/include/ITSBase/GeometryTGeo.h
last set of fixes to achieve clean state for
* member names
* C++11 features: nullptr
> Fix member name convention + nullptr + default

- cmake/O2Utils.cmake
This is related to #256, the previous fix in #257 introduced
a bug skipping header file installation completely. The
check for existence of public header directory needs the
CMAKE_CURRENT_SOURCE_DIR in the directory path.
> Fix #296: Installation of public header files

- Utilities/aliceHLTwrapper/src/aliceHLTEventSampler.cxx
- Utilities/aliceHLTwrapper/src/aliceHLTWrapper.cxx
This worked so far, because one of FairMQ header files had 'using namespace std', that will be cleaned soon.
> Add missing std members

- DataFormats/TimeFrame/test/TimeFrameTest.cxx
- cmake/O2Dependencies.cmake
Both ZeroMQ and DDS are handled by FairMQ. Some QC devices need to get polished to get rid of all DDS dependencies.
> Getting rid of ZeroMQ and DDS dependencies, fixes #344

- Utilities/aliceHLTwrapper/CMakeLists.txt
- Utilities/aliceHLTwrapper/src/aliceHLTWrapper.cxx
Renaming
`aliceHLTWrapper` -> `AliceHLTWrapperDevice`
`aliceHLTEventSampler` -> `AliceHLTEventSamplerDevice`
This also follows the naming scheme recently been used for
device applications.
I'm going to update also the scripts/macrp now, but this needs a bit more time to test as those have not been running for a while.
> Renaming applications to avoid problems on Mac OS (#362)

- Utilities/aliceHLTwrapper/cluster-relay-to-tracker.sh
- Utilities/aliceHLTwrapper/launch-flp-epn.sh
- Utilities/aliceHLTwrapper/launchSimpleChain.sh
Bringing the 2014 prototype setup back to live. Some adjustments in the start scripts.
* Renaming aliceHLTWrapper to AliceHLTWrapperDevice following https://github.com/AliceO2Group/AliceO2/issues/362/https://github.com/AliceO2Group/AliceO2/pull/363
* Removing node setup tailored to the HLT dev cluster and replacing it with a local setup
* Some enhancements to run multiple FLP groups on one node
> Reviving start scripts for the 2014 prototype setup

- DataFormats/Headers/include/Headers/DataHeader.h
- DataFormats/Headers/test/testDataHeader.cxx
The message parameter of static_assert became optional only in C++17
This was not detected by CI because gcc 6.2 (now the default in
the build recipe) seems to automatically support static_assert
w/o message.
Also adding compile time checks directly in the header file.
> Adding message parameter in static_assert to comply with C++11

- cmake/O2Dependencies.cmake
The `aliHLTwrapper` module depends on `O2DeviceApplication_bucket` since 3dc9c2e3
> Removing deprecated alicehlt_bucket from dependency definitions

- DataFormats/Headers/include/Headers/DataHeader.h
- defining HeaderType and SerializationMethod as implementations of Descriptor
- added optional length parameter for the runtimeInit methods
- fixing a small typo
> Extensions to DataHeader tools and cleanup

- Detectors/TPC/simulation/include/TPCSimulation/DigitMC.h
- Detectors/TPC/simulation/include/TPCSimulation/DigitPad.h
- Detectors/TPC/simulation/src/DigitPad.cxx
- Detectors/TPC/simulation/src/DigitizerTask.cxx
- Detectors/TPC/simulation/src/TPCSimulationLinkDef.h
- Detectors/TPC/simulation/test/testTPCSimulation.cxx
- macro/run_sim_tpc.C
* Needed in order to be able to test/debug/evaluate
approaches based on FairLinks (solution based on compile time switches)
* Small adjustment to TPC runscript: Offer
possibility to use Box generator or GeneratorFromFile
@authors: Andreas Matthis, Sandro Wenzel
> Regain possibility to do MC truth handling for TPC digits manually

- Detectors/ITSMFT/ITS/macros/test/run_test.sh
- Detectors/ITSMFT/ITS/reconstruction/CMakeLists.txt
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/Clusterer.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/ClustererTask.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/PixelReader.h
- Detectors/ITSMFT/ITS/reconstruction/src/Clusterer.cxx
- Detectors/ITSMFT/ITS/reconstruction/src/ClustererTask.cxx
- Detectors/ITSMFT/ITS/reconstruction/src/ITSReconstructionLinkDef.h
- Detectors/ITSMFT/ITS/reconstruction/src/PixelReader.cxx
- Detectors/ITSMFT/common/simulation/CMakeLists.txt
- Detectors/ITSMFT/common/simulation/include/ITSMFTSimulation/Chip.h
- Detectors/ITSMFT/common/simulation/include/ITSMFTSimulation/SimuClusterShaper.h
- Detectors/ITSMFT/common/simulation/include/ITSMFTSimulation/SimulationAlpide.h
- Detectors/ITSMFT/common/simulation/src/Chip.cxx
- Detectors/ITSMFT/common/simulation/src/DigitChip.cxx
- Detectors/ITSMFT/common/simulation/src/ITSMFTSimulationLinkDef.h
- Detectors/ITSMFT/common/simulation/src/SimuClusterShaper.cxx
- Detectors/ITSMFT/common/simulation/src/SimulationAlpide.cxx
- macro/run_clus_its.C
This is a minimalistic port of the ITS cluster finder. From now on, both this cluster finder and the ALPIDE response are activated inside the default ITS test.
> Porting the real cluster finder

- Detectors/TPC/base/include/TPCBase/Sector.h
char might be confusing and int is semantically more correct
This PR is due to suggestions by @ktf and @matthiasrichter.
> Use int for Sector::MAXSECTOR instead of char

- DataFormats/Headers/include/Headers/DataHeader.h
- DataFormats/Headers/test/testDataHeader.cxx
The DataDescription and Descriptor structs are not supposed to be
compared by string. The compiler probably creates an operator for
raw pointers automatically.
> Explicitely forbid comparison of data descriptors with pointers, e.g. const char* strings

- Utilities/aliceHLTwrapper/test/testMessageFormat.cxx
The index has to be divided by 2 to get the correct index in the array
of test data. Comes from the fact that every payload message is preceded
by a header message.
> Fix #402 index out of bound error in the vector of dummy test data

- Detectors/ITSMFT/ITS/simulation/CMakeLists.txt
- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/Detector.h
- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/V3Layer.h
- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
- Detectors/ITSMFT/ITS/simulation/src/ITSSimulationLinkDef.h
- Detectors/ITSMFT/ITS/simulation/src/V3Layer.cxx
- macro/run_sim_its_ALP3.C
New V3Layer geometry file created which contains the latest ITSU Inner Barrel description as ported from current AliRoot v2 version.
> Porting latest ITSU geometry from AliRoot v2 to O2

- cmake/O2Utils.cmake
All man pages had been added to the global man target. This makes
a build in only a submodule fail at installation, and the man pages
were not updated when running make in the subdirectory.
Adding additional custom target per submodule for man pages and
make this target depending on the configured man pages of the
module.
> Fix #392: make sure that man pages are created when building submodule

- DataFormats/Headers/src/DataHeader.cxx
We reached the agreement to define the decriptors without 'blank'-padding
> Fix #372: descriptor definitions without blanks

- DataFormats/Headers/include/Headers/HeartbeatFrame.h
- Utilities/aliceHLTwrapper/include/aliceHLTwrapper/MessageFormat.h
- Utilities/aliceHLTwrapper/src/Component.cxx
- Utilities/aliceHLTwrapper/src/MessageFormat.cxx
- Utilities/aliceHLTwrapper/test/testMessageFormat.cxx
The device forwards now incoming heartbeat information and wraps the HLT data blocks in heartbeat frames if the HBF is available at the input.
> Implementing the handling of heartbeat information in the AliceHLTWrapperDevice

- cmake/O2Utils.cmake
Test executables do not necessarily depend on a library or a certain
bucket, these two parameters to O2_GENERATE_TESTS are now optional.
> Allow test executables without library and bucket dependencies

- Utilities/aliceHLTwrapper/doc/AliceHLTWrapperDevice.1.in
- Utilities/aliceHLTwrapper/include/aliceHLTwrapper/Component.h
- Utilities/aliceHLTwrapper/include/aliceHLTwrapper/EventSampler.h
- Utilities/aliceHLTwrapper/include/aliceHLTwrapper/HOMERFactory.h
- Utilities/aliceHLTwrapper/include/aliceHLTwrapper/MessageFormat.h
- Utilities/aliceHLTwrapper/include/aliceHLTwrapper/SystemInterface.h
- Utilities/aliceHLTwrapper/include/aliceHLTwrapper/WrapperDevice.h
- Utilities/aliceHLTwrapper/src/Component.cxx
- the OCDB URI can now be specified as command line option --ocdb,
the existence of ALIHLT_HCDBDIR is checked otherwise
- logging through the FairMQ logging channel
- minor code cleanup
> Added command line option to specify the OCDB configuration

- Utilities/DataCompression/include/DataCompression/DataDeflater.h
- Utilities/DataCompression/test/test_DataDeflater.cxx
std::array is used in test_DataDeflater.cxx, but the include was
missing, some compilers seem to be more strict on that and fail.
Also suppressing a warning by using the static_assert with two
arguments (condition and error string)
> Fix #428: adding missing include for std::array

- Detectors/Base/CMakeLists.txt
- Detectors/Base/include/DetectorsBase/DetID.h
- Detectors/Base/src/BaseLinkDef.h
- Detectors/Base/src/DetID.cxx
- Detectors/Base/test/testDetID.cxx
The names of detectors are currently defined in the class itself and overlap with DataOrigin
names. Once DataOrigin will be complete, detector names will be taken from there
> Alice detector ID class allowing iteration over detectors

- CCDB/include/CCDB/Backend.h
- CCDB/src/Backend.cxx
- CCDB/src/BackendRiak.cxx
Compilation breaks under Xcode when request.pb.h is included
in the header file with the message that the file is not found.
Working when the header created by protobuf is included in
source files.
> Make O2 compile under Xcode

- Detectors/EMCAL/base/include/EMCALBase/EMCGeometry.h
- Detectors/EMCAL/base/include/EMCALBase/Geometry.h
- Detectors/EMCAL/base/include/EMCALBase/ShishKebabTrd1Module.h
- Detectors/EMCAL/base/src/EMCALBaseLinkDef.h
- Detectors/EMCAL/base/src/EMCGeometry.cxx
- Detectors/EMCAL/base/src/Geometry.cxx
- Detectors/EMCAL/base/src/ShishKebabTrd1Module.cxx
- Detectors/EMCAL/simulation/include/EMCALSimulation/Detector.h
- Detectors/EMCAL/simulation/src/Detector.cxx
As argued in #445 the dependence on ROOT is reduced:
- Classes Geometry, EMCGeometry and ShishKebabTrdModule do not
inherit from TNamed any more
- The containers for the ShishKebabTrd1Modules are moved from
TList to std::vector, and not any more a pointer but class members
directly. Furthermore they do not own pointers but the objects
directly. Boundary errors are not handled any more with returning
a nullptr but by throwing an exception
- The EMCGeometry is now a member of Geometry and not a pointer
member
- ROOT TString is replace wherever possible with std::string, const char*
in function arguements with std::string_view (still taken from ROOT)
> Reduction of the dependence of the Geometry classes on ROOT

- Common/MathUtils/include/MathUtils/Cartesian3D.h
- DataFormats/simulation/include/SimulationDataFormat/BaseHits.h
- DataFormats/simulation/src/SimulationDataLinkDef.h
- Detectors/EMCAL/base/include/EMCALBase/Geometry.h
- Detectors/EMCAL/simulation/include/EMCALSimulation/Detector.h
- cmake/O2Dependencies.cmake
* provide commonly used linear algebra types such as Point3D, Vector3D
in a standalone header in Common/MathUtils
* fixes PR #464
> Common header file for Cartesian3D data types

- Detectors/Passive/src/FrameStructure.cxx
fixes a bug where we where accessing a medium from the TGeoManager
by inconsistent name, hence returning a nullptr (thanks to F. Noferini)
> Fixing inconsistency in Frame medium treatment

- Utilities/DataCompression/include/DataCompression/DataDeflater.h
- Utilities/DataCompression/include/DataCompression/TruncatedPrecisionConverter.h
- Utilities/aliceHLTwrapper/include/aliceHLTwrapper/Component.h
- Utilities/aliceHLTwrapper/include/aliceHLTwrapper/EventSampler.h
- Utilities/aliceHLTwrapper/include/aliceHLTwrapper/HOMERFactory.h
- Utilities/aliceHLTwrapper/include/aliceHLTwrapper/MessageFormat.h
- Utilities/aliceHLTwrapper/include/aliceHLTwrapper/SystemInterface.h
- Utilities/aliceHLTwrapper/include/aliceHLTwrapper/WrapperDevice.h
Remove the unnecessary option "-*- Mode: C++ -*-" from the first line, since it does not match the guidelines for Copyright.
> Fix the Copyright header

- macro/run_sim_tpc.C
* this used to be the default behaviour and got unfortunately overwritten
in some commit
* fixing this here
> Use BOX_GENERATOR by default in TPC sim macro

- DataFormats/TimeFrame/test/TimeFrameTest.cxx
- Detectors/TPC/base/include/TPCBase/CalArray.h
- Utilities/DataCompression/include/DataCompression/HuffmanCodec.h
- Utilities/DataCompression/test/test_HuffmanCodec.cxx
- Utilities/DataFlow/test/test_PayloadMerger01.cxx
These commits fix some compiler warnings and make the build completely warning free (at least using gcc on linux).
> Fix compiler warnings

- Detectors/EMCAL/base/CMakeLists.txt
- Detectors/EMCAL/base/include/EMCALBase/EMCGeometry.h
- Detectors/EMCAL/base/include/EMCALBase/Geometry.h
- Detectors/EMCAL/base/include/EMCALBase/GeometryBase.h
- Detectors/EMCAL/base/src/EMCGeometry.cxx
- Detectors/EMCAL/base/src/Geometry.cxx
- Detectors/EMCAL/simulation/src/Detector.cxx
- Use std::tuple instead of multiple references to handle
multiple return values of a function
- For several cases use custom exception (invalid position / cell abs ID)
for error handling instead of boolean return values
- Move classes for exceptions connected to geometry classes and enum
with constants to a common header file GeometryBase, which can be
included both in Geometry and EMCGeometry, no need for redeclaration
- Adapt doxygen documentation where code was changed
> Fixes in output and error handling

- Detectors/EMCAL/base/include/EMCALBase/EMCGeometry.h
- Detectors/EMCAL/base/src/EMCALBaseLinkDef.h
- Detectors/EMCAL/base/src/EMCGeometry.cxx
- Detectors/Passive/include/DetectorsPassive/FrameStructureRun3.h
- Detectors/Passive/src/FrameStructureRun3.cxx
provide missing dictionary entries
fix a constructor for FrameStructure which was not taken by ROOT properly
> Fixes ROOT IO warnings emitted from FairRunSim

- Common/Field/include/Field/MagneticField.h
- Common/Field/src/MagneticField.cxx
The VMC simulation code calls the field via the "Field" API and not
via "GetFieldValue" from FairRoot; It is better to directly override this
function to avoid a double virtual dispatch.
Allowing the compiler to perform more optimization by declaring
the position and field pointers to be strictly separate
(avoids pointer aliasing problem).
Avoiding some virtual function dispatches by prepending with the class name.
> MagneticField: Proper VMC interface + Aliasing optimization

- .gitignore
These are files generated by rbenv which should not be committed.
> Ignore .ruby-version files

- CCDB/src/ConditionsMQServer.cxx
- Utilities/QC/QCMerger/include/QCMerger/MergerDevice.h
- Utilities/QC/QCMerger/src/MergerDevice.cxx
- Utilities/QC/QCMerger/src/runMerger.cxx
- Utilities/QC/QCMerger/test/MergerDeviceTestSuite.cxx
- Utilities/QC/QCProducer/include/QCProducer/ProducerDevice.h
- Utilities/QC/QCProducer/src/ProducerDevice.cxx
- Utilities/QC/QCProducer/src/runProducer.cxx
- Utilities/QC/QCProducer/test/ProducerDeviceTestSuite.cxx
- Utilities/QC/QCViewer/include/QCViewer/ViewerDevice.h
- Utilities/QC/QCViewer/src/ViewerDevice.cxx
- Utilities/QC/QCViewer/src/runViewerDevice.cxx
- Utilities/QC/QCViewer/test/ViewerTestSuite.cxx
- Utilities/aliceHLTwrapper/src/WrapperDevice.cxx
These changes depend on a recent FairRootGroup/FairRoot@f48bd27 commit in FairRoot.
`SetProperty`/`GetProperty` interface of FairMQDevice will be deprecated/removed in the near future, replaced either by access to config container or directly setters/getters.
> Update deprecated configuration calls

- Utilities/Tools/README.md
Valgrind has various false positives when boost / ROOT are linked. This
pollutes the reports and makes more difficult to spot real errors. The
following suppression file can be used via the `--suppressions` option
to remove all the messages which come from an empty:
int main(int argc, char **) {return 0;}
linked against ROOT and Boost.
> Add Valgrind suppression file for ROOT and Boost

- CMakeLists.txt
- config/CMakeLists.txt
This will be read by FairRootManager and set the name of the sim branch according to the content of the `rootmanager.dat` file.
> Copy rootconfig.dat in share/config/

- DataFormats/Legacy/HLT/include/AliceHLT/TPCRawCluster.h
- Utilities/aliceHLTwrapper/include/aliceHLTwrapper/Component.h
- Utilities/aliceHLTwrapper/include/aliceHLTwrapper/EventSampler.h
- Utilities/aliceHLTwrapper/include/aliceHLTwrapper/HOMERFactory.h
- Utilities/aliceHLTwrapper/include/aliceHLTwrapper/MessageFormat.h
- Utilities/aliceHLTwrapper/include/aliceHLTwrapper/SystemInterface.h
- Utilities/aliceHLTwrapper/include/aliceHLTwrapper/WrapperDevice.h
- Utilities/aliceHLTwrapper/src/Component.cxx
- Utilities/aliceHLTwrapper/src/EventSampler.cxx
- Utilities/aliceHLTwrapper/src/HOMERFactory.cxx
- Utilities/aliceHLTwrapper/src/MessageFormat.cxx
- Utilities/aliceHLTwrapper/src/SystemInterface.cxx
- Utilities/aliceHLTwrapper/src/WrapperDevice.cxx
- Utilities/aliceHLTwrapper/src/aliceHLTEventSampler.cxx
- Utilities/aliceHLTwrapper/src/aliceHLTWrapper.cxx
- Utilities/aliceHLTwrapper/src/runComponent.cxx
- Utilities/aliceHLTwrapper/test/testMessageFormat.cxx
All code of the aliceHLTWrapper module is now in the o2::AliceHLT
namespace. A header file has still been directly under the include
directory without the additional level.
> Correcting namespace names, mv header file to more appropriate place

- Detectors/EMCAL/base/include/EMCALBase/Geometry.h
- Detectors/EMCAL/base/include/EMCALBase/Hit.h
- Detectors/EMCAL/base/include/EMCALBase/ShishKebabTrd1Module.h
- Detectors/EMCAL/base/src/Geometry.cxx
- Detectors/EMCAL/base/src/ShishKebabTrd1Module.cxx
- Detectors/EMCAL/simulation/include/EMCALSimulation/Detector.h
- Detectors/EMCAL/simulation/src/Detector.cxx
- Detectors/EMCAL/testsimulation/drawEMCALgeometry.C
- macro/run_sim_emcal.C
- macro/run_sim_emcal.sh
- Bug fix (temporary) in Shishkebab geometry
- Small fix in EMCAL geometry
- Remove unused variable (shut) in Hit
- Fix z-coordinate of Hit
- Fix add function for hit: All hits from the same track are
added to 1 hit. For this a lookup table is used to map the hits
- Handle calculation of the module ID: Module ID needs to be
obtained from the copy number of the volume and the volume ID
over various levels in the geometry tree
- Process Hits add currently hits once a volume is passed
> Implement first version of EMCAL hit creation

- cmake/O2Utils.cmake
The circular dependencies had been created for man pages in the top directory where the target file and the configured dependency are the same. They are dropped by `make` automatically
```
make[2]: Circular CMakeFiles/o2.1 <- o2.1 dependency dropped.
make[2]: Circular o2.1 <- o2.1 dependency dropped.
make[2]: Circular CMakeFiles/FairMQDevice.1 <- FairMQDevice.1 dependency dropped.
make[2]: Circular FairMQDevice.1 <- FairMQDevice.1 dependency dropped.
```
This PR solves these warnings. 
Also adding a check to make sure that there are no header files directly in the `include` directory.
> CMake setup: Fixing a circular dependency and adding check for header files

- Utilities/MCStepLogger/CMakeLists.txt
- Utilities/MCStepLogger/src/MCStepInterceptor.cxx
- Utilities/MCStepLogger/src/MCStepLoggerImpl.cxx
- Utilities/MCStepLogger/src/MCStepLoggerLinkDef.h
- Utilities/MCStepLogger/src/StepInfo.cxx
- Utilities/MCStepLogger/src/StepInfo.h
- cmake/O2Dependencies.cmake
The logger can now stream to a ROOT TTree when environment
variable MCSTEPLOG_TTREE is activated; In this case, it will
not report a summary on the screen; The output file is controlled
via MCSTEPLOG_OUTFILE; This mode will give the most flexibility to
analyse the data.
Improved logging for magnetic field calls, now recording the position
and magnetic field answer
Possibility to provide an ascii file with a mapping of geometry volume
names to detector names; This is activated via the MCSTEPLOG_VOLMAPFILE
environment variable; This information is useful to get quick statistics of
how many steps where done in each detector etc.;
The format of the file is as follows
VOLNAME1 DETECTOR
VOLNAME2 DETECTOR
> MCStepLogger: TTree output and other improvements

- cmake/O2Utils.cmake
Throw fatal cmake error if module and application name can not be
distinguished on case-insensitive file systems
> Fix #362: consistency check for module and application names

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/DeviceSpec.h
- Framework/Core/src/DeviceSpec.cxx
- Framework/Core/src/GraphvizHelpers.cxx
- Framework/Core/src/GraphvizHelpers.h
- Framework/Core/src/runDataProcessing.cxx
- Framework/Core/test/test_Graphviz.cxx
This refactor code so that an actual test for the Graphviz output is
possible (and provided). This is nice because it basically as well
allows to test the DataProcessorSpec to DeviceSpec conversion in a
sandboxed manner.
> Improve Graphviz support

- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
The definition of some materials used in the Outer Barrel volumes was missing. Among the other issues, this was causing all hits in OB layers to be lost. All missing materials were added.
> Add missing material definition for ITSU OB volumes

- Detectors/TPC/simulation/src/Detector.cxx
This fixes a warning in the inplug geometry in the TPC
> fix definition in TGeoPcon

- CCDB/CMakeLists.txt
- CCDB/README.md
- CCDB/config/conditions-client.json
- CCDB/config/conditions-server.json
- CCDB/include/CCDB/Backend.h
- CCDB/include/CCDB/BackendOCDB.h
- CCDB/include/CCDB/BackendRiak.h
- CCDB/include/CCDB/Condition.h
- CCDB/include/CCDB/Manager.h
- CCDB/include/CCDB/TObjectWrapper.h
- CCDB/src/BackendOCDB.cxx
- CCDB/src/BackendRiak.cxx
- CCDB/src/CCDBLinkDef.h
- CCDB/src/ConditionsMQServer.cxx
- CCDB/src/Manager.cxx
- CCDB/test/TestClass.h
- CCDB/test/testQueryServerStandalone.cxx
- CCDB/test/testWriteReadAny.cxx
* Introduction of TObjectWrapper to be able to put any class with
a dictionary inside a Condition (no more required to be of TObject type initially)
* Unit test to read/write a non TObject class
* Some renaming of functions to better express the return value of "Condition" rather
than "Object"
* The Backend::Unpack function now returns a condition; Otherwise the user can not get
hold of the unpacked blob
* A new example demonstrating that we can quere the conditions-server from any
(even non-device) user code; The example is very prototypic
@authors: J. Wiechula, S. Wenzel
> CCDB: generalization; refactoring; new server query example

- DataFormats/Headers/CMakeLists.txt
- DataFormats/Headers/include/Headers/HeartbeatFrame.h
- DataFormats/Headers/test/test_HeartbeatFrame.cxx
- adding a generic reverse parser for sequences of blocks composed
of header - payload - trailer with variable payload length
- adding container class for multiple sequences of heartbeat frames
with row and column access iterators
Further comments:
passing the access function to the iterator did not work because
the typedef for the access function is without the capture, so there
is no matching conversion.
Solution would be to use std::function but that's probably slow and
the function is called often. Can be checked later.
> Adding a frame collection parser and heartbeat sequence container

- Detectors/ITSMFT/common/simulation/include/ITSMFTSimulation/AlpideSimResponse.h
- Detectors/ITSMFT/common/simulation/src/AlpideSimResponse.cxx
- Detectors/ITSMFT/common/simulation/src/ITSMFTSimulationLinkDef.h
- Detectors/ITSMFT/common/simulation/test/testAlpideSimResponse.cxx
Hi @dr4kan 
Alpide response was not flipped for negative x and y. Also, half-Zbin shift is corrected.
The flipped response matrix should be obtained as:
```` 
AlpideSimResponse resp;
resp.initData();
AlpideRespSimMat rspmat;
constexpr int npix = resp.getNPix();
// get x,y,z in pixel frame...
if ( resp.getResponse(x,y,z, rspmat) ) {  // use repsonse 
for (int i=npix;i--;) {
for (int j=npix;j--;) {
float o2r = rspmat.getValue(i,j); // o2 response
}
}
}
````
Faster way (avoid copy of the flipped response) is to get unflipped repsonse *pointer* together with
flipping flags:
````
AlpideSimResponse resp;
resp.initData();
bool flipX,flipY;
constexpr int npix = resp.getNPix();
// get x,y,z in pixel frame...
auto rspmat = resp.getResponse(x,y,z, flipX, flipY); 
if (rsmpat) {
for (int i=npix;i--;) …
```
> Added row/col flipping for negative x,y

- Algorithm/test/parser.cxx
macos seems to be more picky on that, `-Werror` was just introduced in https://github.com/alisw/alidist/commit/52b04a64c685f33fa5c290805fd79ed6414e8c9b while PR #562 was open and checked
> Fixing -Wbraced-scalar-init in parser unit test

- DataFormats/Headers/include/Headers/HeartbeatFrame.h
- DataFormats/Headers/test/test_HeartbeatFrame.cxx
- defining type names matching naming convention, more cleanup to come
- bugfix: handle iterator initializers for empty container
- formatting
- checking header size by static_assert
> Bugfix and cleanup in HeartbeatFrame.h

- Detectors/Base/include/DetectorsBase/Detector.h
- Detectors/EMCAL/simulation/src/Detector.cxx
- Detectors/TOF/simulation/src/Detector.cxx
- Detectors/TOF/simulation/src/TOFSimulationLinkDef.h
- Detectors/TRD/simulation/src/Detector.cxx
- Detectors/TRD/simulation/src/TRDSimulationLinkDef.h
We had a problem with duplicate dictionary entries coming from initiating
TClonesArrays with alias type names:
using T=X;
TClonesArray("T");
Unfortunately, this does not work unless we created a dictionary for T
next to the one for X; This was a requirement from ROOT.
This commit fixes the issue by providing a standalone function which converts a type T
into its original type name "X"; In addition this function performs other important type
checks on T which is otherwise only done during runtime.
> Fix problem with duplicate dictionary entries due to alias types

- .clang-tidy
This file contains (just like .clang-format) project
specific configuration passed to the O2codechecker (or clang-tidy)
> Adding a .clang-tidy configurations file

- Algorithm/CMakeLists.txt
- Algorithm/include/Algorithm/TableView.h
- Algorithm/test/StaticSequenceAllocator.h
- Algorithm/test/parser.cxx
- Algorithm/test/tableview.cxx
Container class for multiple sequences of data wrapped by markers.
This is a container for data sequences of multiple frames consisting
of a header marker struct, a payload, and an optional trailer marker
struct. Each sequence forms a row in the TableView, the columns
are provided by the markers/frames.
A parser is used to step through the data sequence and extract
headers, trailers and payload positions.
Factoring out the test frame allocator utility to a separate file
to be used in multiple unit tests. Going to be made more general in
the future.
> Adding table view abstraction for data sequences

- Common/Field/src/MagFieldFact.cxx
Removing a coupling of MagFieldFact::SetParm() to
FaiRunAna which is
a) not needed since FairRuntimeDb is itself a singleton
b) meant a strong coupling to a FairRunAna which might not be the
FairRun actually steering the processing
> MagFieldFact: Remove strong coupling to FairRunAna

- Common/MathUtils/CMakeLists.txt
- Common/MathUtils/include/MathUtils/CachingTF1.h
- Common/MathUtils/src/CachingTF1.cxx
- Common/MathUtils/src/MathUtilsLinkDef.h
- Common/MathUtils/test/testCachingTF1.cxx
- Detectors/TPC/simulation/src/GEMAmplification.cxx
- cmake/O2Dependencies.cmake
* The ordinary TF1 does not write state information such as
internally calculated integrals;
This extension provides this feature; This was suggested by
the ROOT team who did not want to change this behaviour in the
base class
* Application of CachingTF1 in the initialization of the GEMAmplification
response which is quite compute intensive due to evaluation of integrals
for the random number generation
(The idea is that we can put this CachingTF1 into the conditions database
in the future)
This caching might be a temporary solution, but until something better is found
removes a 4s initialization overhead (for each TPC sector).
> CachingTF1: A variant of TF1 able to persist integral caches

- Detectors/TPC/simulation/src/DigitizerTask.cxx
fixing a segfault which derived from deleting a container
based on an inconsistent condition
> Fix segfault in destructor of TPC::DigitizerTask

- Common/Field/include/Field/MagFieldFact.h
- Common/Field/src/MagFieldFact.cxx
- macro/run_sim_tpc.C
* do not leak memory from MagFieldFact
* use unique_ptr in run_sim_tpc since field is not cleaned up in FairRunSim
> Better resource management for MagneticField (unique_ptr)

- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/ClustererTask.h
- Detectors/ITSMFT/MFT/reconstruction/include/MFTReconstruction/ClustererTask.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/Clusterer.h
- Detectors/ITSMFT/common/reconstruction/src/Clusterer.cxx
This is a trivial namespace fix, can this be merged quickly?
> common ITS/MFT clusterer must be in ITSMFT namespace

- Examples/flp2epn-distributed/src/EPNReceiver.cxx
- Framework/Core/src/TextControlService.cxx
- Framework/Core/src/runDataProcessing.cxx
- Utilities/DataFlow/src/EPNReceiverDevice.cxx
- Utilities/DataFlow/src/TimeframeValidationTool.cxx
- Utilities/QC/QCMerger/src/Merger.cxx
- Utilities/QC/QCMerger/src/runMerger.cxx
- Utilities/QC/QCProducer/src/runProducer.cxx
- Utilities/QC/QCViewer/src/runViewerDevice.cxx
- Utilities/aliceHLTwrapper/include/aliceHLTwrapper/EventSampler.h
- Utilities/aliceHLTwrapper/include/aliceHLTwrapper/WrapperDevice.h
This patch adapts O2 code to breaking FairMQ changes (coming to FairRoot dev branch when FairRootGroup/FairRoot#607 is merged). Merge after the FairRoot PR is merged (and O2 fork is updated).
Following changes require update of O2 code (done in this PR):
- removal of `FairMQConfigurable`.
- Since long unused by O2, but still some remaining dead code (`FairMQDevice::Last`). (**backwards-compatible**)
- FairMQLogger header no longer includes `<iostream>`.
- Some includes must be added in O2. (**backwards-compatible**)
- introduction of `DeviceRunner`, control/config plugins, removal of `runSimpleMQStateMachine`.
- This simplifies some of the setup code for devices that have custom `main()`. For O2 this is `Framework/Core/src/runDataProcessing` (fixed in this PR) and QC devices (this PR …
> Update code affected by breaking FairMQ changes.

- cmake/O2Dependencies.cmake
- macro/build_geometry.C
MFT detector is now compiled into o2sim executable
By default it is not yet activated as it has problems with the segmentation configuration
which needs to be addressed.
> Integrate basic version of MFT into o2sim

- Detectors/ITSMFT/common/simulation/src/Digitizer.cxx
- Detectors/ITSMFT/common/simulation/src/SimulationAlpide.cxx
This is a bug fix, in some situations UInt_t of negative value was calculated, leading to overflow in the ROFrame
> fix MaxROFrame calculation: avoid UInt of t<0

- Detectors/ITSMFT/ITS/macros/test/CheckClusters.C
- Detectors/ITSMFT/ITS/macros/test/CheckDigits.C
- Detectors/ITSMFT/ITS/macros/test/DisplayTrack.C
- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/Detector.h
- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/DigitizerTask.h
- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
- Detectors/ITSMFT/ITS/simulation/src/DigitizerTask.cxx
- Detectors/ITSMFT/common/simulation/include/ITSMFTSimulation/Digitizer.h
- Detectors/ITSMFT/common/simulation/include/ITSMFTSimulation/Hit.h
- Detectors/ITSMFT/common/simulation/src/Digitizer.cxx
- Detectors/ITSMFT/test/HitAnalysis/include/HitAnalysis/HitAnalysis.h
- Detectors/ITSMFT/test/HitAnalysis/src/HitAnalysis.cxx
- cmake/O2Dependencies.cmake
This PR provides the replacement of TClonsArrays -> std::vector for hits for ITS as important steps for #610.
some other smaller optimization fixes:
a) use const ref for TVector3
b) use cached reference to TVirtualMC::GetMC
> Strongly typed hits in ITS + other minor changes

- cmake/O2Utils.cmake
This modifies O2_GENERATE_TESTS to impose a strict naming convention:
test_${MODULE_NAME}<actual name call>
This is to accomplish the following:
- Ensure that tests are well identifiable by the test_ prefix.
- Ensure that we do not have generic names like `test_Fifo` or
`test_Collections` like we do now.
- Ensure the origin of the source (i.e. which module) is clear
without having to grep for the test name through the codebase.
> Impose naming convention to tests

- DataFormats/Headers/include/Headers/HeartbeatFrame.h
Without this compilation fails on GCC 7.2.1 with
error: ‘function’ in namespace ‘std’ does not name a template type
Probably this was hidden by some implicit inclusion of
<functional> so far.
> Add missing <functional> library include

- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/Cluster.h
- Detectors/ITSMFT/common/reconstruction/src/Cluster.cxx
- Detectors/ITSMFT/common/reconstruction/src/Clusterer.cxx
For clusterization and compression studies we need to optionally
store in the clusters the pixels topology. To disable this feature
the ``#define _ClusterTopology_`` in ``ITSMFTReconstruction/Cluster.h``
should be commented out.
> Store cluster topology if _ClusterTopology_ is defined.

- Algorithm/CMakeLists.txt
- Algorithm/include/Algorithm/PageParser.h
- Algorithm/test/pageparser.cxx
This is the basis for a generic raw reader of data split in consecutive DMA pages.
Memory pages have a fixed size and start with a page header. The parser
provides transparent iteration through data objects and handles page
boundaries.
Added in the update:
- write functionality for parser iterator
- bidirectional copy function
- runtime check for the buffer const'ness
- copy assignment and copy contructor for iterator
- supporting iterator and const_iterator
> Adding parser for a set of data objects in consecutive memory pages (follow up #585)

- DataFormats/simulation/include/SimulationDataFormat/MCTrack.h
- DataFormats/simulation/include/SimulationDataFormat/Stack.h
- DataFormats/simulation/src/MCTrack.cxx
- DataFormats/simulation/src/SimulationDataLinkDef.h
- DataFormats/simulation/src/Stack.cxx
- Detectors/ITSMFT/ITS/macros/test/CheckTracks.C
* MCTrack no longer inherits from TObject
* particle and track vectors use std::vector instead of TClonesArray
(saving 8byte due to not using pointers)
* put MCTrack in o2 namespace
* some cleanup (removal of unused functions, etc)
> Stack/MCTrack: Cleanup + memory improvement

- DataFormats/simulation/include/SimulationDataFormat/BaseHits.h
- Detectors/TPC/simulation/include/TPCSimulation/Detector.h
- Detectors/TPC/simulation/include/TPCSimulation/Digitizer.h
- Detectors/TPC/simulation/include/TPCSimulation/DigitizerTask.h
- Detectors/TPC/simulation/include/TPCSimulation/Point.h
- Detectors/TPC/simulation/src/Detector.cxx
- Detectors/TPC/simulation/src/Digitizer.cxx
- Detectors/TPC/simulation/src/DigitizerTask.cxx
- Detectors/TPC/simulation/src/TPCSimulationLinkDef.h
Partial step towards #610.
Removal of old code (protected by macro) for non-sectorwise processing.
> Use std::vector for Hits in TPC + Cleanup 

- Algorithm/CMakeLists.txt
- Algorithm/include/Algorithm/O2FormatParser.h
- Algorithm/test/o2formatparser.cxx
Generic parser for an input list of messages attempting to interpret the O2
header payload sequence.
The following callbacks are mandadory to be provided, e.g. through lambdas
- insert function with signature (const DataHeader&, ptr, size)
auto insertFct = [&] (const auto & dataheader,
auto ptr,
auto size) {
// do something with dataheader and buffer
};
- getter for the message pointer, e.g. provided std::pair is used
auto getPointerFct = [] (auto & arg) {return arg.first;};
- getter for the message size, e.g. provided std::pair is used
auto getSizeFct = [] (auto & arg) {return arg.second;};
Optionally, also callbacks for individual headers in the header stack can be
provided.
> Adding generic parser for o2 data format

- DataFormats/simulation/src/Stack.cxx
The MCTrack vector was wrongly initialized to be of size 100
in contrast to the desired "capacity of 100".
Thanks to Iouri Belikov for spotting this.
> Fix wrong initialization of MCTrack vector in Stack

- Framework/Core/include/Framework/ConfigParamsHelper.h
- Framework/Core/include/Framework/DataRef.h
- Framework/Core/include/Framework/DataRefUtils.h
- Framework/Core/include/Framework/DataSourceDevice.h
- Framework/Core/include/Framework/InputRecord.h
- Framework/Core/include/Framework/Variant.h
- Framework/Core/src/ConfigParamsHelper.cxx
- Framework/Core/src/DataAllocator.cxx
- Framework/Core/src/DataSourceDevice.cxx
- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/Core/src/FrameworkGUIDevicesGraph.cxx
- Framework/Core/src/runDataProcessing.cxx
- Framework/TestWorkflows/src/o2_sim_tpc.h
This is a proposal for a couple of bugfixes and enhancements for the framework module
- Implementing argument scan via boost program options
cures the 'unrecognized option' warnings at child start and adds help printout, provides the basis to
support options without extra parameter or even multitoken in `ConfigParamSpec`
- adding variant_type trait
- Adding rate control to DataSourceDevice (yet to be configured via command line parameter)
- add iterator for elements of InputRecord
- using o2::Header::get to extract DataHeader
- adding header message size to DataRef and support assignment
- bugfix, set payloadSize in the data header
- fixing a compilation warning (shadowed variable)
- bugfixes for argument forwarding (obsolete with the move to boost program options)
- correcting typos
> Dev framework update

- Utilities/QC/CMakeLists.txt
- Utilities/QC/QCProducer/include/QCProducer/TH1Producer.h
- Utilities/QC/QCProducer/include/QCProducer/TH2Producer.h
- Utilities/QC/QCProducer/include/QCProducer/TH3Producer.h
- Utilities/QC/QCProducer/include/QCProducer/THnProducer.h
- Utilities/QC/QCProducer/include/QCProducer/TreeProducer.h
- Utilities/QC/QCProducer/src/TH1Producer.cxx
- Utilities/QC/QCProducer/src/TH2Producer.cxx
- Utilities/QC/QCProducer/src/TH3Producer.cxx
- Utilities/QC/QCProducer/src/THnProducer.cxx
- Utilities/QC/QCProducer/src/TreeProducer.cxx
- Utilities/QC/Workflow/CMakeLists.txt
- Utilities/QC/Workflow/src/RootObjectMergerSpec.cxx
- Utilities/QC/Workflow/src/RootObjectMergerSpec.h
- Utilities/QC/Workflow/src/RootObjectProducerSpec.cxx
- Utilities/QC/Workflow/src/RootObjectProducerSpec.h
- Utilities/QC/Workflow/src/SimpleMergerWorkflow.cxx
- cmake/O2Dependencies.cmake
Setup consists of:
- QCProducerSpec interfacing the four Producer classes of QCProducer module
available options:
--objectType TH2F
--objectName <name>
--objectTitle <title>
--nBins <n>
--nBranches <n>
--nTreeEntries <n>
- QCMergerSpec interfacing Merger from QCMerger module
no options at the moment
> Adding QC setup using declarative workflow of the framework

- Detectors/Base/include/DetectorsBase/Track.h
- Detectors/Base/src/BaseLinkDef.h
- Detectors/Base/src/Track.cxx
- Detectors/ITSMFT/ITS/macros/test/CheckTracks.C
- Detectors/ITSMFT/ITS/macros/test/run_test.sh
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CAaux.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CookedTrack.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CookedTracker.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CookedTrackerTask.h
- Detectors/ITSMFT/ITS/reconstruction/src/CATracker.cxx
- Detectors/ITSMFT/ITS/reconstruction/src/CAaux.cxx
- Detectors/ITSMFT/ITS/reconstruction/src/CookedTrack.cxx
- Detectors/ITSMFT/ITS/reconstruction/src/CookedTracker.cxx
- Detectors/ITSMFT/ITS/reconstruction/src/CookedTrackerTask.cxx
- Detectors/TPC/reconstruction/include/TPCReconstruction/TrackTPC.h
- Detectors/TPC/reconstruction/macro/testTracks.C
- Detectors/TPC/reconstruction/src/Cluster.cxx
- macro/run_trac_its.C
@iouribelikov when deriving CookedTrack from TrackParCov I saw that
the clusters indices are kept in the std::vector which is expanded to 7 slots in track
constructor. To make the tracks POD-like copyable (and smaller) I changed
this to array<int,7>.
> Make TrackParCov base class of other tracks + extra methods for matching

- Utilities/QC/Workflow/src/RootObjectMergerSpec.cxx
- Utilities/QC/Workflow/src/RootObjectProducerSpec.cxx
By using shared_ptr for the worker instances passed to the processing
lambda, the instances will be cleaned up correctly when the function
gets out of scope
> Correcting cleanup of instances of worker classes

- Detectors/TPC/simulation/include/TPCSimulation/DigitTime.h
- Detectors/TPC/simulation/include/TPCSimulation/Digitizer.h
- Detectors/TPC/simulation/include/TPCSimulation/DigitizerTask.h
- Detectors/TPC/simulation/src/Detector.cxx
- Detectors/TPC/simulation/src/DigitCRU.cxx
- Detectors/TPC/simulation/src/DigitRow.cxx
- Detectors/TPC/simulation/src/DigitTime.cxx
- Detectors/TPC/simulation/src/Digitizer.cxx
- Detectors/TPC/simulation/src/DigitizerTask.cxx
- Detectors/TPC/simulation/src/ElectronTransport.cxx
- Detectors/TPC/simulation/src/PadResponse.cxx
- Detectors/TPC/simulation/test/testTPCElectronTransport.cxx
* Several small fixes in the simulation code
* Temporary possibility for realistic event times
* Small code modernisation
> Fix simulation

- DataFormats/simulation/CMakeLists.txt
- DataFormats/simulation/include/SimulationDataFormat/MCTrack.h
- DataFormats/simulation/include/SimulationDataFormat/Stack.h
- DataFormats/simulation/src/MCTrack.cxx
- DataFormats/simulation/src/SimulationDataLinkDef.h
- DataFormats/simulation/src/Stack.cxx
- DataFormats/simulation/test/MCTrack.cxx
- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/Detector.h
- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
- Detectors/Passive/include/DetectorsPassive/Cave.h
- Detectors/Passive/src/Cave.cxx
- Detectors/gconfig/commonConfig.C
- Detectors/gconfig/g3Config.C
- Detectors/gconfig/g4Config.C
- macro/o2sim.C
The stack is a major consumer of memory for big events;
This commit essentially "completely" reduces the memory used by the stack, by
a) making MCTrack objects configurable on floating point type
b) storing lean MCTrack objects instead of TParticles as transient tracks
c) cleaning up + filtering of tracks after each (N-th) primary instead of after each event (as originally foreseen by FairRoot)
> Next round of improvements to Stack class

- Framework/Core/src/runDataProcessing.cxx
This handles a boost exception for processors with more than one channel.
Introduced when the framework argument scan was changed to boost program
options. The child processes are started with one or more '--channel-config'
option(s)
Initially, also a unit test to handle this case was planned, but it turned out to be more complex as expected. The error condition of the the failing child process is not caught in the main process, and
thus the unit test is not failing.
> Bugfix: allow multiple occurence of '--channel-config' option

- Framework/Core/CMakeLists.txt
- Framework/Core/README.md
- Framework/Core/include/Framework/DataAllocator.h
- Framework/Core/include/Framework/DataRefUtils.h
- Framework/Core/include/Framework/InputRecord.h
- Framework/Core/include/Framework/TMessageSerializer.h
- Framework/Core/src/DataAllocator.cxx
- Framework/Core/src/DataProcessor.cxx
- Framework/Core/src/FrameworkGUIDebugger.cxx
- Framework/Core/src/InputRecord.cxx
- Framework/Core/test/test_DataRefUtils.cxx
- Framework/Core/test/test_FrameworkDataFlowToDDS.cxx
- Framework/Core/test/test_GenericSource.cxx
- Framework/Core/test/test_InputRecord.cxx
- Framework/Core/test/test_ParallelProducer.cxx
- Framework/Core/test/test_SimpleDataProcessingDevice01.cxx
- Framework/Core/test/test_SingleDataSource.cxx
- Framework/TestWorkflows/src/o2DiamondWorkflow.cxx
- Framework/TestWorkflows/src/o2DummyWorkflow.cxx
- Framework/TestWorkflows/src/o2ParallelWorkflow.cxx
- Framework/TestWorkflows/src/test_o2RootMessageWorkflow.cxx
- Utilities/QC/Workflow/src/RootObjectMergerSpec.cxx
- Utilities/QC/Workflow/src/RootObjectProducerSpec.cxx
This improves the API for both InputRecord and DataAllocator to
simplify creation of objects which are to be sent via the framework
or their retrivial on the sink side.
In particular the new API is much more orthogonal WRT the types and
it basically has only three templated methods:
- `DataAllocator::make<T>()` to create objects which are owned by the
framework and that will be sent and the end of the processing.
- `DataAllocator::adopt()` to adopt preexisting objects and send them
once the processing ends.
- `InputRecord::get<T>` to extract a T& from the message.
The methods are smart enough to do the right thing depending wether
the type T in question is a POD, a Collection of POD or a TObjetct
derived one. Moreover as a side effect this greatly simplifies the ROOT
based message passing …
> Improve API for creating and receiving messages 

- DataFormats/simulation/include/SimulationDataFormat/MCTruthContainer.h
- DataFormats/simulation/test/testMCTruthContainer.cxx
- Detectors/TPC/reconstruction/macro/readClusterMCtruth.C
- Detectors/TPC/reconstruction/src/ClustererTask.cxx
- Detectors/TPC/simulation/include/TPCSimulation/DigitizerTask.h
- Detectors/TPC/simulation/src/DigitizerTask.cxx
Several improvements on MCTruthContainer:
* cut inheritance from TNamed as this is no longer
necessary (since we can register arbitrary types with FairRoot now)
This means:
- need to register the object with RegisterAny
- no longer need a trailing dot (.) in the branch name
* offer copy/assignment operator on MCTruthContainer as requested
by @KlewinS
* reduce memory footprint by deleting the size field in
MCTruthHeaderElement; This size can in fact be calculated on the fly
as pointed out by David Rohr (@davidrohr).
> MCTruthContainer: copy constructor, no TNamed, memory reduction

- Framework/Core/include/Framework/ConfigParamsHelper.h
- Framework/Core/include/Framework/DeviceSpec.h
- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/Core/src/DeviceSpecHelpers.h
- Framework/Core/src/runDataProcessing.cxx
The options defined in a `ProcessorSpec` can now be grouped together on the command line,
an option is created from the spec name, e.g. 
`--my_spec_name  "--myoption1 arg myoption2 arg --rate 1"`
will forward the options only to devices of spec `my_spec_name`
Rate control for ConditionalRun is going to be introduced to FairMQDevice in PR
https://github.com/FairRootGroup/FairRoot/pull/675, option `--rate` is now forwarded.
> Introducing option groups for processing specs and forwarding --rate to device

- Algorithm/test/headerstack.cxx
- DataFormats/Headers/CMakeLists.txt
- DataFormats/Headers/include/Headers/DataHeader.h
- DataFormats/Headers/include/Headers/NameHeader.h
- DataFormats/Headers/include/Headers/RAWDataHeader.h
- DataFormats/Headers/src/DataHeader.cxx
- DataFormats/Headers/src/NameHeader.cxx
- DataFormats/Headers/test/testDataHeader.cxx
- DataFormats/Headers/test/test_RAWDataHeader.cxx
- Framework/Core/include/Framework/ChannelMatching.h
- Framework/Core/include/Framework/ChannelSpec.h
- Framework/Core/include/Framework/ConfigParamRegistry.h
- Framework/Core/include/Framework/ConfigParamsHelper.h
- Framework/Core/include/Framework/ForwardRoute.h
- Framework/Core/include/Framework/InputSpec.h
- Framework/Core/include/Framework/MessageContext.h
- Framework/Core/include/Framework/OutputRoute.h
- Framework/Core/include/Framework/RootObjectContext.h
- Utilities/O2MessageMonitor/src/O2MessageMonitor.cxx
- Utilities/aliceHLTwrapper/test/testMessageFormat.cxx
The definition of RDH follows the working document 
https://docs.google.com/document/d/1IxCCa1ZRpI3J9j3KCmw2htcOLIRVVdEcO-DDPcLNFM0
Some cleanup in the DataHeader definition, moving the printout statements to cxx file, and moving example `NameHeader` to separate file.
> Adding definition of ReadoutDataHeader, moving DataHeader printout functionality

- Framework/Core/include/Framework/DataAllocator.h
- Framework/Core/src/DataAllocator.cxx
This handles the case when the processor keeps a TObject over multiple calls of the processing function and wants to send a serialized snapshot while keeping the ownership.
> Extending the DataAllocator by TObject snapshot functionality

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/TypeTraits.h
- Framework/Core/test/test_TypeTraits.cxx
This is useful to specialize behavior of templated functions based on
the kind of collection they belong to.
> Add type trait to check for template specialization

- Framework/Core/src/DataAllocator.cxx
serialization method has to be set to NONE in order to be consistent
with the check in DataRefUtils::as<>
> bugfix: set payload serialization method

- Framework/Core/include/Framework/ConfigParamsHelper.h
- Framework/Core/src/ConfigParamsHelper.cxx
- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/Core/src/runDataProcessing.cxx
The command line options are populated with a couple of hidden options
by the framework to correctly start the device. Using a key of the
hidden options in the processor config spec resulted in a parser error
due to duplicated definitions.
The allows in particular '--channel-config' to be used in the config
specs to specify external channels
Also forwarding default values of all options to devices. Currently the `ConfigParamSpec` does not foresee _no default_.
> Resolve conflict of hidden device options with potential config specs.

- DataFormats/simulation/CMakeLists.txt
- DataFormats/simulation/include/SimulationDataFormat/MCInteractionRecord.h
- DataFormats/simulation/src/SimulationDataLinkDef.h
- Steer/CMakeLists.txt
- Steer/include/Steer/InteractionSampler.h
- Steer/src/InteractionSampler.cxx
- Steer/src/SteerLinkDef.h
- Steer/test/testInteractionSampler.cxx
@sawenzel : please check. In principle, would be good to extract the LHC-related constants to separate header, eventually other classes will need them, but I was not sure that Steer is a correct location for this sample at 1st place, so did not want to complicate dependencies.
> Interaction record sampler class + its test

- CCDB/CMakeLists.txt
- Detectors/TPC/monitor/CMakeLists.txt
- Detectors/TPC/reconstruction/CMakeLists.txt
- Detectors/TPC/simulation/CMakeLists.txt
- run/CMakeLists.txt
Those lines are likely to be remnants of restructering the repository
and utilization of the O2_GENERATE_EXECUTABLE macro
@sawenzel, @wiechula I came across those lines when I tried to understand how the tests are generated and looked a bit in the file history. Please check if we can clean this up, I did a search for similar lines in the repository after finding the obsolete commented code in `run/CMakeLists.txt`
> Removing obsolete commented lines in the cmake setup

- Framework/Core/include/Framework/ConfigParamSpec.h
- Framework/Core/include/Framework/ConfigParamsHelper.h
- Framework/Core/include/Framework/Variant.h
- Framework/Core/src/BoostOptionsRetriever.cxx
- Framework/Core/src/ConfigParamsHelper.cxx
- Framework/Core/src/FrameworkGUIDebugger.cxx
- Framework/Core/src/WorkflowHelpers.cxx
- Framework/Core/test/test_BoostOptionsRetriever.cxx
- Framework/Core/test/test_SingleDataSource.cxx
- Framework/Core/test/test_Variants.cxx
- Framework/TestWorkflows/src/o2DummyWorkflow.cxx
- Framework/TestWorkflows/src/o2_sim_tpc.cxx
- Utilities/QC/Workflow/src/RootObjectProducerSpec.cxx
The variant can now be explicitely empty and a dedicated constructor
can be used to define config specs without default value. The boost option
semantics is only populated with default value when specified.
The help string is now mandatory for config specs and is represented as
a dedicated type. This requires the string to be brace-enclosed.
In order to destinguish between help string and default variant value,
brace-enclosed constructor is now forbidden for Variant.
> Support config spec with empty default value

- .travis.yml
This will create and deploy doxygen generated pages every time
the dev branch is updated. They will be visible under:
https://aliceo2group.github.io/AliceO2/
> Add .travis.yml file which creates doxygen pages

- Detectors/FIT/base/README.md
- Detectors/ITSMFT/ITS/base/README.md
Files with empty or trivial content are polluting the doxygen
documentation. Whenever you add a README you should make
sure you have at least one section, either via:
```
```
or via
```
Meaningful section name
=======================
```
give it a meaningful name. Such a name will appear at toplevel
under the Project navigation in the doxygen documentation at:
http://aliceo2group.github.io/AliceO2/
> Eliminate more spurious README files

- Framework/Core/README.md
- Framework/Core/include/Framework/DataAllocator.h
- Framework/Core/src/DataAllocator.cxx
- Framework/TestWorkflows/test/test_MakeDPLObjects.cxx
__Extending DataAllocator API to support vector of pointers__
Adding snapshot support for vector of pointers to trivially copyable
objects. The data set is linearized and can be retrieved as a gsl::span
on the receiver side.
Combining duplicated code in a dedicated function adding parts to context.
__Adding specialization to catch unsupported types as template arguments__
This allows to produce a more descriptive compiler error if unsupported
types are used in 'make' and 'snapshot' API methods.
__Consistent API, bugfix__
Passing the TObject by reference to snapshot method to be consistent
with other specializations.
Bugfix for the single POD snapshot method, const'ness violating cast
removed
> Updating the DataAllocator API

- Detectors/EMCAL/simulation/src/SpaceFrame.cxx
Fixes a bug (segfault with Geant4) introduced due to the earlier introduction of
DetectorID + conversion from EMCAL -> EMC.
> Correct medium name for EMCAL

- DataFormats/Headers/include/Headers/DataHeader.h
- DataFormats/Headers/src/DataHeader.cxx
- Detectors/ITSMFT/MFT/reconstruction/src/devices/Sampler.cxx
- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/TMessageSerializer.h
- Framework/Core/src/TMessageSerializer.cxx
This provides rudimentary support for handling ROOT schema information when communicating via messages. The framework integration part is missing, should be easy to do if this interface is accepted, of course there are other ways of doing this. This one is based on the code and logic we use in the HLT ZMQ framework.
The functionality included allows for (optionally) caching the streamers for objects that are serialized, constructing a FairMQMessage containing those streamers and a method to decode a message containing streamers and update ROOT internals.
idea is to use it like this (when streamers should be created/updated while serializing):
`mDevice->Serialize<TMessageSerializer>(*payloadMessage, object, TMessageSerializer::CacheStreamers::yes, TMessageSerializer::CompressionLevel{2});`
> Root streamers

- DataFormats/TPC/include/DataFormatsTPC/ClusterHardware.h
- Detectors/FIT/simulation/src/Detector.cxx
- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
- Detectors/ITSMFT/MFT/simulation/src/Detector.cxx
- Detectors/TPC/simulation/src/Detector.cxx
The FairGenericRootManager is not activated anymore, detectors must register their branches
via FaitRootManager::Instance()
> Fix following elimination of FairGenericRootManager

- DataFormats/simulation/src/Stack.cxx
There was one more remnant after #747 
FairGenericRootManager.h has been removed in
https://github.com/FairRootGroup/FairRoot/pull/703
> Removing one more include of FairGenericRootManager.h following #747

- Detectors/Base/include/DetectorsBase/Detector.h
- Detectors/Base/src/Detector.cxx
- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/Detector.h
- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/V3Layer.h
- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
- Detectors/ITSMFT/ITS/simulation/src/V3Layer.cxx
X and Z dimensions of many IB and OB volumes were set in different places using different static constants or passed as parameters. Though all values are not in conflict with each other, this approach could lead to inconsistencies in the long term. With the proposed changes, all dimensions are properly computed internally using the chip dimensions as building block.
> Compute X and Z dimensions internally in the code

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/DeviceControl.h
- Framework/Core/include/Framework/DeviceInfo.h
- Framework/Core/include/Framework/LogParsingHelpers.h
- Framework/Core/include/Framework/PaletteHelpers.h
- Framework/Core/include/Framework/TextControlService.h
- Framework/Core/src/FrameworkGUIDebugger.cxx
- Framework/Core/src/FrameworkGUIDevicesGraph.cxx
- Framework/Core/src/LogParsingHelpers.cxx
- Framework/Core/src/PaletteHelpers.cxx
- Framework/Core/src/TextControlService.cxx
- Framework/Core/src/runDataProcessing.cxx
- Framework/Core/test/test_LogParsingHelpers.cxx
This allows controlling the log level from the GUI and
colorize things differently depending on it. It also extends
the GUI to allow changing the log level dynamically, on a
per Device level.
Moreover, in case an error is encountered in any of the Data Processors, the application
exits with 1 rather than 0. This should allow us to spot
test that while not crashing, do not behave correctly.
> Support for log level understanding and control

- CMakeLists.txt
This introduces a new COVERAGE mode for CMake which will embed code coverage
information. In order to fully exploit this we need to enable it at alidist
level, e.g. by switching defaults-o2-dev-fairroot to use it and push results
to a code coverage service like codecov.io.
> Add support for code coverage

- DataFormats/Parameters/include/DataFormatsParameters/GRPObject.h
- DataFormats/Parameters/src/GRPObject.cxx
- macro/o2sim.C
root does not know how to save chrono::time_point, at the moment change to time_t.
o2sim will set a GRP start/end times the actual processing times
> Revert GRP timing to time_t (chrono is not root-persistent)

- DataFormats/Headers/include/Headers/DataHeader.h
- DataFormats/Headers/include/Headers/TimeStamp.h
- correcting name of the internal namespace
- replacing tabs with spaces
- using std::integral_constant instead of self-defined template
> Code cleanup DataHeader.h and TimeStamp.h

- Detectors/Base/include/DetectorsBase/MaterialManager.h
- Detectors/Base/src/MaterialManager.cxx
- Detectors/Passive/src/Absorber.cxx
- Detectors/Passive/src/Dipole.cxx
- Detectors/Passive/src/FrameStructure.cxx
- Detectors/Passive/src/Hall.cxx
- Detectors/Passive/src/Magnet.cxx
- Detectors/Passive/src/Pipe.cxx
- Detectors/Passive/src/Shil.cxx
This removes an old temporary workaround and treats material/medium construction properly in case of the passive detectors. I checked that stepping/transport is completely unaffected.
> Use MaterialManager in passive detectors

- DataFormats/simulation/include/SimulationDataFormat/MCTruthContainer.h
- DataFormats/simulation/test/testMCTruthContainer.cxx
Providing a function to allow appending
element/labels for abitrary valid dataindices.
Note that the new functions is slow and should only be
used when absolutely required.
Previously it was only possible to append elements
for the last dataindex.
> Allow random appending of labels into MCTruthContainer

- Detectors/TPC/reconstruction/include/TPCReconstruction/HardwareClusterDecoder.h
- Detectors/TPC/reconstruction/include/TPCReconstruction/TrackTPC.h
- Detectors/TPC/reconstruction/src/HardwareClusterDecoder.cxx
- Detectors/TPC/reconstruction/src/TPCCATracking.cxx
- Detectors/TPC/reconstruction/src/TrackTPC.cxx
- fix shift in cluster coordinates
- add chi2 / vertex time / outerparam
- unify TPC side definition between o2 and standalone tracking library
- compatibility fix for root 6 with gcc 7
The "Side" variable (1 for A, 0 for C) from the standalone library has been replaced by a new CSide variable (1 for C, 0 for A), which is the same numbering as in other TPC / O2 code.
In order to not simply negate the Side variable, which could cause some confusion, I introduced the new CSide getter. This patch adapts O2 to the new interface of the standalone library. The old Side getter will be removed thereafter.
> Update to TPCCATracking

- Framework/Core/src/TextControlService.cxx
The current implementation of the driver has a naive way
of sending control requests from the child to the parent
via std::cout. It seems possible that sometimes this
is garbled by the actual Logger output, so I use the
Logger for the commands themselves assuming messages there
are atomic.
> Use LOG(INFO), rather than std::cout for commands

- Detectors/ITSMFT/MFT/base/README.md
- Detectors/ITSMFT/MFT/reconstruction/include/MFTReconstruction/devices/README.md
- Detectors/ITSMFT/MFT/reconstruction/src/devices/README.md
- Steer/README.md
Since README files are now showed in our doxygen documentation at:
https://aliceo2group.github.io/AliceO2/
I am adding context to all the README files so that we get a proper
entry in the sidebar menu, rather than a generic "README" one.
> Add context to documentation

- Detectors/Base/src/TrackReference.cxx
- Detectors/EMCAL/simulation/src/Detector.cxx
- Detectors/PHOS/simulation/src/Detector.cxx
- Detectors/TRD/simulation/src/Detector.cxx
Fixes #563.
Uses newly introduced float API in VMC and avoids
useless type conversions.
> Use VMC::TrackPosition in float mode

- Common/Field/include/Field/MagneticField.h
- Common/Field/include/Field/MagneticWrapperChebyshev.h
- Common/Field/src/MagneticField.cxx
- Common/Field/src/MagneticWrapperChebyshev.cxx
- Common/MathUtils/include/MathUtils/Chebyshev3D.h
- Common/MathUtils/src/Chebyshev3D.cxx
- DataFormats/simulation/include/SimulationDataFormat/Stack.h
- DataFormats/simulation/src/Stack.cxx
The new logging infrastructure in FairRoot makes direct usage of
FairLogger unnecessary and the old version is still able to compile
in a forward compatible mode.
> Finish refactoring to the new Logger infrastructure

- Detectors/gconfig/g3Config.C
This commit fixes a large descripancy observed in
the number of steps done in O2 vs AliRoot (for EMCAL).
AUTO(1) is the default G3 mechanism, which automatically
determines the best tracking parameters (for stepmax). This default
is also used on AliRoot and also corresponds to what G4 is doing.
Thanks to @mFasDa for a shared debugging session.
> Switch to GEANT3 AUTO tracking mode

- Detectors/EMCAL/testsimulation/PutEmcalInTop.C
- Detectors/EMCAL/testsimulation/drawEMCALgeometry.C
Fix some copy/paste errors and add forgotten
header files needed to run macros in compiled
mode. Note this should have no effects in
JIT-compiled mode as the headers are protected
by a guard.
> Fix headers for EMCAL test macros

- .gitignore
Ignores the .vscode folder for changes. Useful for vscode users as this folder otherwise keeps hanging in the unstaged changes.
> Ignore vscode folder

- cmake/O2Dependencies.cmake
Apparently some people started to use Boost::serialization in
simulation / reconstruction breaking the builds. This is hopefully the reason we have tests failures in (some) macros. I am not actually sure how things could work before and how they can work in the dev-fairroot branch.
> Add Boost::serialization

- Detectors/TPC/calibration/src/CalibRawBase.cxx
- Detectors/TPC/reconstruction/include/TPCReconstruction/GBTFrameContainer.h
- Detectors/TPC/reconstruction/include/TPCReconstruction/RawReader.h
- Detectors/TPC/reconstruction/run/readRawData.cxx
- Detectors/TPC/reconstruction/src/GBTFrameContainer.cxx
- Detectors/TPC/reconstruction/src/RawReader.cxx
New SAMPA v3 and v4 do flipping of bit9 now internally, therefore the decoding should not do this as well. To keep backwards compatibility, the SMAPA version can be set for the decoding.
> Support for different SAMPA versions in TPC RawReader

- .clang-format
Adding a new configuration key. This fixes an unwanted behaviour where
empty lines, for example between function declarations, were removed by clang-format.
> clang-format: avoid removal of empty lines

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/DataProcessorLabel.h
- Framework/Core/include/Framework/DataProcessorSpec.h
- Framework/Core/test/test_DataProcessorSpec.cxx
This allows optionally specifying one or more label to be associated
to the DataProcessorSpec, to be later used for things like generating
sub-topologies for a given label or to customize behavior for devices
associated with a DataProcessorSpec with a given label.
> Add Labels to DataProcessorSpec

- Detectors/ITSMFT/ITS/macros/test/CheckClusters.C
- Detectors/ITSMFT/ITS/macros/test/CheckTopologies.C
- Detectors/ITSMFT/ITS/macros/test/run_test.sh
- Detectors/ITSMFT/common/reconstruction/CMakeLists.txt
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/BuildTopologyDictionary.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/Cluster.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/ClusterTopology.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/Clusterer.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/LookUp.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/PixelReader.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/TopologyDictionary.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/TopologyFastSimulation.h
- Detectors/ITSMFT/common/reconstruction/src/BuildTopologyDictionary.cxx
- Detectors/ITSMFT/common/reconstruction/src/Cluster.cxx
- Detectors/ITSMFT/common/reconstruction/src/ClusterTopology.cxx
- Detectors/ITSMFT/common/reconstruction/src/Clusterer.cxx
- Detectors/ITSMFT/common/reconstruction/src/ITSMFTReconstructionLinkDef.h
- Detectors/ITSMFT/common/reconstruction/src/LookUp.cxx
- Detectors/ITSMFT/common/reconstruction/src/PixelReader.cxx
- Detectors/ITSMFT/common/reconstruction/src/TopologyDictionary.cxx
- Detectors/ITSMFT/common/reconstruction/src/TopologyFastSimulation.cxx
Some classes for the study of the topologies of the clusters of the ITS are added:
- ClusterTopology, which is the base class
- TopologyDictionary, i.e. the dictionary with all the cluster topologies
- BuildClusterTopology, necessary for the construction of the dictionary
- LookUp, necessary for the identification of the topology wih the corresponding key in the dictionary
-FastSimulation, to generate a distribution of cluster topologies according to the dictionary
This PR has been discussed with @shahor02 and @iouribelikov.
> Include cluster topology classes

- Detectors/TPC/reconstruction/macro/convertClusterToClusterHardware.C
@davidrohr : it was working before w/o these headers, apparently they were provided via some other headers which now have changed...
> Fix: add missing header for TChain/TTree

- Framework/Core/CMakeLists.txt
- Framework/Core/README.md
- Framework/Core/include/Framework/ChannelConfigurationPolicy.h
- Framework/Core/include/Framework/ChannelConfigurationPolicyHelpers.h
- Framework/Core/include/Framework/ChannelSpec.h
- Framework/Core/include/Framework/runDataProcessing.h
- Framework/Core/src/ChannelConfigurationPolicy.cxx
- Framework/Core/src/ChannelConfigurationPolicyHelpers.cxx
- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/Core/src/DeviceSpecHelpers.h
- Framework/Core/src/runDataProcessing.cxx
- Framework/Core/test/test_DeviceSpec.cxx
- Framework/Core/test/test_FrameworkDataFlowToDDS.cxx
- Framework/Core/test/test_Graphviz.cxx
- Framework/Core/test/test_TimeParallelPipelining.cxx
This allows users to specify a set of policies on
how the FairMQ channels should be configured, e.g.
using PUSH/PULL rather than PUB/SUB.
> Introduce ability to customize channel configuration

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/DeviceInfo.h
- Framework/Core/include/Framework/FrameworkGUIDebugger.h
- Framework/Core/include/Framework/runDataProcessing.h
- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/Core/src/DriverControl.cxx
- Framework/Core/src/DriverControl.h
- Framework/Core/src/DriverInfo.cxx
- Framework/Core/src/DriverInfo.h
- Framework/Core/src/FrameworkDummyDebugger.cxx
- Framework/Core/src/FrameworkGUIDebugger.cxx
- Framework/Core/src/runDataProcessing.cxx
- Framework/Core/test/test_DeviceSpec.cxx
- Framework/Core/test/test_FrameworkDataFlowToDDS.cxx
- Framework/Core/test/test_Graphviz.cxx
- Framework/Core/test/test_TimeParallelPipelining.cxx
- Framework/DebugGUI/src/DebugGUI.cxx
This introduces a state machine for the DPL driver process so that more complex behaviours can be implemented in the future, like, for example spawning processes on a cluster using DDS or a web based console.
This will come also handy to implement proper process cleanup on quit, which at the moment is kind of brutal.
> Introduce a state machine for the DPL driver process

- DataFormats/Detectors/TPC/include/DataFormatsTPC/ClusterHardware.h
- DataFormats/Detectors/TPC/include/DataFormatsTPC/ClusterNative.h
- DataFormats/Detectors/TPC/include/DataFormatsTPC/Helpers.h
- DataFormats/Detectors/TPC/src/DataFormatsTPCLinkDef.h
- DataFormats/Detectors/TPC/src/Helpers.cxx
- DataFormats/Detectors/TPC/test/ClusterNative.cxx
- Detectors/TPC/reconstruction/include/TPCReconstruction/HardwareClusterDecoder.h
- Detectors/TPC/reconstruction/include/TPCReconstruction/TPCCATracking.h
- Detectors/TPC/reconstruction/include/TPCReconstruction/TrackTPC.h
- Detectors/TPC/reconstruction/macro/convertClusterToClusterHardware.C
- Detectors/TPC/reconstruction/macro/runCATrackingClusterNative.C
- Detectors/TPC/reconstruction/macro/runHardwareClusterDecoderRaw.C
- Detectors/TPC/reconstruction/macro/runHardwareClusterDecoderRoot.C
- Detectors/TPC/reconstruction/src/HardwareClusterDecoder.cxx
- Detectors/TPC/reconstruction/src/TPCCATracking.cxx
TPC data format definitions in DataFormats/Detectors/TPC got an extra
level of namespace which is not necessary.
@wiechula, @davidrohr, @sawenzel, @ktf, what do you think? I suggest removing one namespace level from the TPC data format definitions.
> reducing namespace o2::DataFormat::TPC to o2::TPC

- Framework/DebugGUI/src/DebugGUI.cxx
Header files where reordered by clang format, but apparently this triggers errors on mac. Rolling back that `clang-format` issue.
> Fix messup by clang-format

- .clang-format
This should solve the problem with messing up our include order.
> clang-format: disallow sorting of includes

- DataFormats/simulation/include/SimulationDataFormat/Stack.h
- DataFormats/simulation/src/Stack.cxx
- Detectors/EMCAL/simulation/include/EMCALSimulation/Detector.h
- Detectors/EMCAL/simulation/src/Detector.cxx
- Detectors/FIT/simulation/src/Detector.cxx
- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
- Detectors/ITSMFT/MFT/simulation/src/Detector.cxx
- Detectors/Passive/include/DetectorsPassive/FrameStructure.h
- Detectors/Passive/src/FrameStructure.cxx
- Detectors/TOF/simulation/include/TOFSimulation/Detector.h
- Detectors/TOF/simulation/src/Detector.cxx
- Detectors/TPC/simulation/include/TPCSimulation/Detector.h
- Detectors/TPC/simulation/src/Detector.cxx
- Detectors/TRD/simulation/include/TRDSimulation/Detector.h
- Detectors/TRD/simulation/src/Detector.cxx
- Detectors/gconfig/commonConfig.C
- Replaced calls to FairGenericRootManager with FairRootManager
(now thread-safe)
- Migrated code in Detectors and DataFormats to MT
- Implemented CloneModule() method where missing
- Moved definition of sensitive volumes in detectors from
ConstructGeometry() to Initialize(), to get it called on threads
- Changed static local variables defined during event processing
in static thread_local
- Implemented o2::Stack::FinishPrimary(), which has been added in FairGenericStack
base class, and removed the hook for calling this code from commonConfig.C.
The code still requires clean-up by the author of the Stack class to avoid
mIsG4Like test here.
> Update for MT simulation (version 2):

- Framework/Core/include/Framework/DataAllocator.h
- Framework/Core/include/Framework/DataRefUtils.h
- Framework/Core/include/Framework/InputRecord.h
- Framework/Core/include/Framework/TypeTraits.h
- Framework/Core/test/test_TypeTraits.cxx
Extending snapshot method of framework::DataAllocator to support
trivially copyable objects in general in all specializations. On the
receiving side, DataRefUtils::as has been made consistent to that.
> Introducing type trait is_messageable and replacing is_trivially_copyable/is_pod with this

- Detectors/TPC/base/include/TPCBase/CalDet.h
This is related to a reported issue #843. The include is not needed and we might have to revisit when needed.
> Take out unused Vc include

- Framework/Core/include/Framework/runDataProcessing.h
Insert the default `ChannelConfigPolicy` after the user defined
ones so that the user can simply use push_back in his own code.
Fixes #841.
> Rework ChannelConfigPolicy defaults

- Detectors/TPC/reconstruction/src/HwClusterer.cxx
The number of threads is wrongly calculated by 1 in case the number of
CRUs is smaller than the number of threads.
> Fix problem in HwClusterer

- Detectors/EMCAL/base/include/EMCALBase/Digit.h
- Detectors/EMCAL/base/src/Digit.cxx
- Detectors/EMCAL/simulation/CMakeLists.txt
- Detectors/EMCAL/simulation/include/EMCALSimulation/Digitizer.h
- Detectors/EMCAL/simulation/include/EMCALSimulation/DigitizerTask.h
- Detectors/EMCAL/simulation/src/Digitizer.cxx
- Detectors/EMCAL/simulation/src/DigitizerTask.cxx
- Detectors/EMCAL/simulation/src/EMCALSimulationLinkDef.h
Modified Digit class: stores absolute cell ID, introduction of + += < and > operators
Introduced Digitizer class: converts Hits to Digits, addes Digits in the same tower and time window, fills output vector of Digits
Introduced DigitizerTask class: interacts with analysis manager, gets vector of Hits, uses Digitizer to convert to vector of Digits
Modified simulation/CMakeLists.txt and simulation/src/EMCALSimulationLinkDef.h files to account for the new classes
> [AOGM-212] Initial version of the EMCAL digitizer

- Framework/Core/src/DriverControl.h
- Framework/Core/src/DriverInfo.h
- Framework/Core/src/FrameworkGUIDebugger.cxx
- Framework/Core/src/runDataProcessing.cxx
- More resilient quit behavior is now implemented thanks
to the state machine introduced in #832. The signal handlers
are now fully signal safe.
- Add working controller window which allows to pause and single step
through the execution of all the devices. The quantum is given by the
children blocking when writing output.
- Add --single-step option to start in single step mode, if needed.
> Improve the driver control facilities

- Common/Field/include/Field/MagneticField.h
- Common/Field/src/MagneticField.cxx
To make the MC production usable on the system different from where it was generated
we should store unparsed path to the data file
> Do not parse stored field-map path

- Framework/Core/src/DriverControl.h
- Framework/Core/src/DriverInfo.h
- Framework/Core/src/FrameworkGUIDebugger.cxx
- Framework/Core/src/runDataProcessing.cxx
It is now possible to customise the behavior of the state machine via
callbacks. This allows, for example to express the dumping of DDS and
graphviz configuration files as state machine programs, rather than
ad-hoc functions.
This will also allow the GUI to be more flexible, e.g. to dump a text
representation of the current state, without having to introduce new
ad-hoc states.
> Allow driver state machine to perform callbacks

- Framework/Core/src/DriverInfo.h
- Framework/Core/src/runDataProcessing.cxx
It's now possible to quit any workflow after a predetermined amount of
time by using the --timeout <period> option. The option will trigger a
graceful exit after the period has ellapsed.
> Add --timeout option to DPL

- CMakeLists.txt
- Framework/ArrowTests/CMakeLists.txt
- Framework/ArrowTests/src/dummy.cxx
- Framework/ArrowTests/test/test_Arrow01.cxx
- Framework/CMakeLists.txt
- cmake/O2Dependencies.cmake
- cmake/modules/FindArrow.cmake
This adds a package as a playground for Apache Arrow and does
all the ancillary related work.
> Add playground for Apache Arrow examples

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/DataAllocator.h
- Framework/Core/include/Framework/DataRefUtils.h
- Framework/Core/include/Framework/InputRecord.h
- Framework/Core/include/Framework/SerializationMethods.h
- Framework/Core/include/Framework/TMessageSerializer.h
- Framework/Core/include/Framework/TypeTraits.h
- Framework/Core/test/FrameworkCoreTestLinkDef.h
- Framework/Core/test/TestClasses.cxx
- Framework/Core/test/TestClasses.h
- Framework/Core/test/test_TypeTraits.cxx
- added support for ROOT serialization of non-TObject objects
- automatically deduce serialization method for messageable and ROOT-serializable objects and handle ambiguity for those which are both
- adding type wrapper to force ROOT-serialization method
> Update of the DPL I/O API

- Detectors/ITSMFT/ITS/macros/test/run_test.sh
- Detectors/ITSMFT/ITS/reconstruction/CMakeLists.txt
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CookedTracker.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CookedTrackerTask.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/TrivialVertexer.h
- Detectors/ITSMFT/ITS/reconstruction/src/CookedTracker.cxx
- Detectors/ITSMFT/ITS/reconstruction/src/CookedTrackerTask.cxx
- Detectors/ITSMFT/ITS/reconstruction/src/TrivialVertexer.cxx
- macro/run_sim_its_ALP3.C
- macro/run_trac_its.C
This PR opens the possibility to do basic performance studies on events with randomly distributed primary vertices.  The simulation, reconstruction and comparison work in both triggered and continuous readout mode.  The information about the primary vertices is passed to the tracking via a "primary vertexer".   Limitation of the moment :  this vertexer (TrivialVertexer) takes the vertices directly from the MC.
> Possibility to run with randomly distributed primary vertices

- Detectors/EMCAL/simulation/include/EMCALSimulation/Detector.h
Fixes a segfault when loading the FairRuntimeDB when
EMCAL Detector is included.
> Make hit collection non-streamable

- DataFormats/Detectors/CMakeLists.txt
- DataFormats/Detectors/MUON/CMakeLists.txt
- DataFormats/Detectors/MUON/MID/CMakeLists.txt
- DataFormats/Detectors/MUON/MID/include/DataFormatsMID/Cluster2D.h
- DataFormats/Detectors/MUON/MID/include/DataFormatsMID/StripPattern.h
- Detectors/MUON/MID/Base/CMakeLists.txt
- Detectors/MUON/MID/Base/include/MIDBase/LegacyUtility.h
- Detectors/MUON/MID/Base/include/MIDBase/Serializer.h
- Detectors/MUON/MID/Base/src/LegacyUtility.cxx
- Detectors/MUON/MID/Base/test/testDEconversion.cxx
- Detectors/MUON/MID/CMakeLists.txt
- Detectors/MUON/MID/Clustering/CMakeLists.txt
- Detectors/MUON/MID/Clustering/README.md
- Detectors/MUON/MID/Clustering/config/runMIDClusterizer.json
- Detectors/MUON/MID/Clustering/src/Clusterizer.cxx
- Detectors/MUON/MID/Clustering/src/Clusterizer.h
- Detectors/MUON/MID/Clustering/src/ClusterizerDevice.cxx
- Detectors/MUON/MID/Clustering/src/ClusterizerDevice.h
- Detectors/MUON/MID/Clustering/src/runMIDClusterizer.cxx
- Detectors/MUON/MID/Clustering/test/CMakeLists.txt
- Detectors/MUON/MID/Clustering/test/bench_Clusterizer.cxx
- Detectors/MUON/MID/Clustering/test/testClusterizer.cxx
- cmake/O2Dependencies.cmake
This is the initial version of a clustering device for MID.
It consists of 4 closely related commits: the first three introduce some necessary classes for the Clustering.
The first commit, in particular, defines a very preliminary version of the expected input "digits" format,
which are indeed strip patterns. This was added to DataFormats/Detectors.
Since it is the first MUON commit in the DataFormats, it also defines the directory structure,
which is chosen to be equivalent to the one in o2/Detectors.
> First version of clustering for MID

- Framework/Core/test/test_DataAllocator.cxx
Using error messages instead of exiting with assert to indicate the failing checks in the unit test. This fits better into the workflow driver.
> Cleanup: Replacing assert by error messages

- cmake/O2Utils.cmake
This allows now to specify ctest timeout and optional command line arguments
for a test target. Different command line arguments can be specified by
invoking O2_GENERATE_TESTS individually for tests having different command line
arguments.
> Adding options TIMEOUT and COMMAND_LINE_ARGS to O2_GENERATE_TESTS

- Framework/Core/include/Framework/InputRecord.h
This is another solution for the problem addressed in PR #908, we do
not need a definition in the o2::framework namespace, the declaration
was just for convenience. So it is cleaner to remove it.
> Using std::default_delete directly to avoid naming conflict

- Framework/Core/include/Framework/DataAllocator.h
- Framework/Core/include/Framework/DataRefUtils.h
- Framework/Core/include/Framework/TypeTraits.h
The type trait was classifying pointers as messageable because they are
trivially copyable. But this is not what we want. Pointers are easy to
pass to the DataAllocator API by mistake, catching this case with a
proper compile error now.
Adding a helper function to DataRefUtils to estract the payload size from
DataRef.
> Bugfix: make pointer data types non-messageable

- cmake/O2Dependencies.cmake
In PR #886 some compilation errors have been introduced, triggered only
when IWYU is installed.
```
CMake Error: Attempt to add a custom rule to output "/home/richter/src/alisw/sw/BUILD/aa1513468d78797f9c98e17f41686f1676d4ca5c/O2/Detectors/MUON/MCH/Mapping/Impl3/GenDetElemId2SegType.iwyu.rule" which already has a custom rule.
CMake Error: Attempt to add a custom rule to output "/home/richter/src/alisw/sw/BUILD/aa1513468d78797f9c98e17f41686f1676d4ca5c/O2/Detectors/MUON/MCH/Mapping/Impl3/PadGroupType.iwyu.rule" which already has a custom rule.
CMake Error: Attempt to add a custom rule to output "/home/richter/src/alisw/sw/BUILD/aa1513468d78797f9c98e17f41686f1676d4ca5c/O2/Detectors/MUON/MCH/Mapping/Impl3/SegmentationCreator.iwyu.rule" which already has a custom rule.
CMake Error: Attempt to …
```
> Disable IWYU integration because of compilation failure

- DataFormats/Detectors/TPC/src/DataFormatsTPCLinkDef.h
- Detectors/TPC/reconstruction/src/TPCReconstructionLinkDef.h
After moving TPC::Cluster to DataFormats/Detectors/TPC, this is also
the better place to define the dictionary generation of vector<TPC::Cluster>.
> LinkDef cleanup after moving of TPC::Cluster

- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/Detector.h
- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
The alignable volumes were added for the whole ITSU and its daughters. At the same all references to the obsolete MisalignmentParameter were discarded.
> Add alignable volumes to ITSU

- Detectors/MUON/MID/Base/CMakeLists.txt
- Detectors/MUON/MID/Base/include/MIDBase/Constants.h
- Detectors/MUON/MID/Base/include/MIDBase/Mapping.h
- Detectors/MUON/MID/Base/src/Constants.cxx
- Detectors/MUON/MID/Base/src/Mapping.cxx
This allows a re-use of code in existing and future classes.
> Move MID constants to a separate class

- Framework/Core/include/Framework/DataAllocator.h
- Framework/Core/include/Framework/SerializationMethods.h
- Framework/Core/include/Framework/TMessageSerializer.h
- Framework/Core/test/test_DataAllocator.cxx
This allows for ROOT serialization by class name instead of class type,
e.g. to generically process data from branches of a TTree.
EDIT: updated more generic version uses either const char names or the TClass object directly, the latter for better performance.
> Introducing optional hint for the class info to be used in ROOTSerialized type wrapper

- Detectors/MUON/MCH/Mapping/Interface/include/MCHMappingInterface/Segmentation.h
- Detectors/MUON/MCH/Mapping/test/src/Segmentation.cxx
Kind of needed for DPL when Segmentation is used as state in a ProcessCallback created by an InitCallback (and capture is done, as it should, by value). 
Also bring == and != operators for good measure.
> Add proper copy and assignment.

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/DataSampling.h
- Framework/Core/include/Framework/DataSamplingConfig.h
- Framework/Core/include/Framework/Dispatcher.h
- Framework/Core/include/Framework/DispatcherDPL.h
- Framework/Core/include/Framework/DispatcherFairMQ.h
- Framework/Core/include/Framework/DispatcherFlpProto.h
- Framework/Core/src/DataSampling.cxx
- Framework/Core/src/DispatcherDPL.cxx
- Framework/Core/src/DispatcherFairMQ.cxx
- Framework/Core/src/DispatcherFlpProto.cxx
- Framework/Core/test/test_DataSamplingFairMQ.ini
- Framework/Core/test/test_Parallel.cxx
- Framework/Core/test/test_TimePipeline.cxx
- Framework/TestWorkflows/CMakeLists.txt
- Framework/TestWorkflows/dataSamplingFullChainConfig.ini
- Framework/TestWorkflows/src/dataSamplingFullChain.cxx
- Framework/TestWorkflows/src/dataSamplingParallel.cxx
- Framework/TestWorkflows/src/dataSamplingPodAndRoot.cxx
- Framework/TestWorkflows/src/dataSamplingTimePipeline.cxx
Changes:
- Major refactoring, due to growing size of Data Sampling - created Dispatcher base class which is inherited by different kinds of dispatchers. Also moved some configuration structures to separate header.
- added more explicit way of choosing dispatcher type
- introduced DispatcherFlpProto, which behaves properly with Readout and QualityControl using 'FLP proto data model'
- updated DataSamplingFullChain to work properly in between Readout and QC
- changed 'Headers' to 'headers'
> Update Data Sampling

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/RootTreeReader.h
- Framework/Core/test/TestClasses.h
- Framework/Core/test/test_RootTreeReader.cxx
The reader interfaces one TTree specified by its name, and supports this
tree to be distributed over multiple files multiple files.
The class uses a KeyType to define sinks for specific branches, the default
key type is OutputSpec. Branches are defined for processing by pairs of
key type and branch name.
Usage (for the default KeyType):
```
RootTreeReader(treename,
filename1, filename2, ...,
OutputSpec{...}, branchname1,
OutputSpec{...}, branchname2,
) reader;
auto processSomething = [] (auto& key, auto& object) {/*do something*/};
while (reader.next()) {
reader.process(processSomething);
}
// -- or --
while ((++reader)(processSomething));
```
In the DPL AlgorithmSpec the processing lambda can simple look like
```
auto processingFct = [reader](ProcessingContext& pc) {
// increment the …
```
> Adding generic DPL reader utility for ROOT TTree

- Framework/Core/src/GraphvizHelpers.cxx
- Framework/Core/test/test_Graphviz.cxx
@ktf 
Got a few issues with an invalid (because of dashes in names) dot file generated by "my workflow -g"
Seems the replace of dashes by underscores was not done in all required places.
But anyway why not simply quote the strings instead ?
I tested my mods on a few workflows and it seems to work... e.g. : 
```bash
rm -rf toto.html && o2DummyWorkflow -g | grep -v '^\[INFO' | dot -Tsvg > toto.html
```
> Quote some strings to allow e.g. for dashes in processor names

- DataFormats/Detectors/ITSMFT/ITS/include/DataFormatsITS/TrackITS.h
- DataFormats/Detectors/ITSMFT/ITS/src/TrackITS.cxx
- DataFormats/Parameters/include/DataFormatsParameters/GRPObject.h
- DataFormats/Parameters/src/GRPObject.cxx
- DataFormats/Reconstruction/include/ReconstructionDataFormats/Vertex.h
- DataFormats/Reconstruction/src/Track.cxx
- Detectors/Base/src/Propagator.cxx
- Detectors/GlobalTracking/src/MatchTPCITS.cxx
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CA/IOUtils.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CA/Tracker.h
- Detectors/ITSMFT/ITS/reconstruction/src/CA/IOUtils.cxx
- Detectors/ITSMFT/ITS/reconstruction/src/CA/Tracker.cxx
- macro/run_match_TPCITS.C
- macro/run_trac_ca_its.C
@mpuccio I see that the tracklet vertexer is still not use for CA tracker. The way you
were imposing the MCtruth vertex will not work cont. mode since the clusters tree entry does not correspond to MCHeader entries. Fixing this will require lengthy loop over MC vertices, don't think it worths it if the real vertexer will be attached soon. Therefore, the run_trac_ca_its at the moment imposes dummy 0,0,0 vertex and will work properly only with MC generated at this vertex (only in cont. mode, which is detected from the GRP). Could you please check if my changes in your code are ok.
Cheers,
Ruben
> Adapt CA ITS tracker for matching + fix in refit after matching

- Algorithm/include/Algorithm/HeaderStack.h
- Algorithm/include/Algorithm/O2FormatParser.h
- DataFormats/Headers/include/Headers/DataHeader.h
- DataFormats/Headers/test/testDataHeader.cxx
- Framework/Core/include/Framework/DataRefUtils.h
- Framework/Core/include/Framework/InputRecord.h
- Framework/Core/src/DataAllocator.cxx
- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/src/DataProcessor.cxx
- Framework/Core/src/DataRelayer.cxx
- Framework/Core/src/DispatcherDPL.cxx
- Framework/Core/src/DispatcherFairMQ.cxx
- Framework/Core/src/DispatcherFlpProto.cxx
- Framework/Core/src/ExternalFairMQDeviceProxy.cxx
- Framework/Core/test/test_DataAllocator.cxx
- Framework/Core/test/test_Parallel.cxx
- Framework/Core/test/test_RootTreeReader.cxx
- Framework/TestWorkflows/src/dataSamplingParallel.cxx
- Framework/TestWorkflows/src/dataSamplingPodAndRoot.cxx
- Framework/TestWorkflows/src/dataSamplingTimePipeline.cxx
- Framework/TestWorkflows/src/o2DummyWorkflow.cxx
- Utilities/DataFlow/src/EPNReceiverDevice.cxx
- Utilities/DataFlow/src/FLPSenderDevice.cxx
- Utilities/DataFlow/src/SubframeBuilderDevice.cxx
- Utilities/DataFlow/src/TimeframeParser.cxx
- Utilities/DataFlow/src/TimeframeValidatorDevice.cxx
- Utilities/O2MessageMonitor/src/O2MessageMonitor.cxx
- Utilities/Publishers/src/DataPublisherDevice.cxx
- Utilities/QC/Workflow/src/RootObjectMergerSpec.cxx
- Utilities/aliceHLTwrapper/src/MessageFormat.cxx
this changes the signature of the header::get<> : the template parameter must be a pointer type in order to have a pointer returned, e.g.
`DataHeader* h = header::get<DataHeader*>(buffer)`
> Ask for pointer to get a pointer in header::get<T>

- Generators/include/Generators/GeneratorFromFile.h
- Generators/src/GeneratorFromFile.cxx
Generalize GeneratorFromFile to skip non-trackable particles (do
not pass them to the primary generator) when reading from an
external kinematics file.
Later on -- when the MC stack has been improved to deal with non-trackable
primaries -- we can make this a real configuration option.
> Skip non-trackable particles when reading AliRoot kinematics

- DataFormats/Headers/include/Headers/TimeStamp.h
`std::duration` has been used the wrong way as template parameter and
only recent compilers complain about this. The return type is now
defined based on the rep and period member types which allows to
use either clock or duration types following the `std::chrono` concept.
We have discussed a conceptual question: both `get<Clock>` and `get<Duration>`
return a duration, and in the case of a clock type it's the subtype while
in the latter it's the type itself. For the moment it's convenient that
way, however subject to change if it turns out to be confusing.
> Correctly defining duration return type of getter

- DataFormats/Detectors/MUON/MID/CMakeLists.txt
- DataFormats/Detectors/MUON/MID/include/DataFormatsMID/Cluster3D.h
- DataFormats/Detectors/MUON/MID/include/DataFormatsMID/Track.h
- DataFormats/Detectors/MUON/MID/src/Track.cxx
- Detectors/MUON/MID/Base/CMakeLists.txt
- Detectors/MUON/MID/Base/include/MIDBase/HitFinder.h
- Detectors/MUON/MID/Base/src/HitFinder.cxx
- Detectors/MUON/MID/CMakeLists.txt
- Detectors/MUON/MID/TestingSimTools/CMakeLists.txt
- Detectors/MUON/MID/TestingSimTools/include/MIDTestingSimTools/TrackGenerator.h
- Detectors/MUON/MID/TestingSimTools/src/TrackGenerator.cxx
- Detectors/MUON/MID/Tracking/CMakeLists.txt
- Detectors/MUON/MID/Tracking/README.md
- Detectors/MUON/MID/Tracking/config/runMIDtracking.json
- Detectors/MUON/MID/Tracking/src/Tracker.cxx
- Detectors/MUON/MID/Tracking/src/Tracker.h
- Detectors/MUON/MID/Tracking/src/TrackerDevice.cxx
- Detectors/MUON/MID/Tracking/src/TrackerDevice.h
- Detectors/MUON/MID/Tracking/src/runMIDTracking.cxx
- Detectors/MUON/MID/Tracking/test/CMakeLists.txt
- Detectors/MUON/MID/Tracking/test/bench_Tracker.cxx
- Detectors/MUON/MID/Tracking/test/testTracker.cxx
- cmake/O2Dependencies.cmake
This pull-request consists of 4 closely related commits:
- the first commit defines a track for MID
- the second and third define some tools which allow for testing the tracking. In particular they add:
* a class to find the impact point of the (generated) track on a chamber
* a fast track generator
- the last commit is the tracking device itself with the corresponding tests.
Although they are closely related, it would be good if they can be merged without squashing since they are "atomic" commits.
> First version of tracking for MID

- Framework/Core/include/Framework/ProcessingContext.h
- Framework/Core/include/Framework/RootTreeReader.h
- Framework/Core/src/DispatcherDPL.cxx
- Framework/Core/test/test_DataAllocator.cxx
- Framework/Core/test/test_FrameworkDataFlowToDDS.cxx
- Framework/Core/test/test_Parallel.cxx
- Framework/Core/test/test_ParallelProducer.cxx
- Framework/Core/test/test_SimpleDataProcessingDevice01.cxx
- Framework/Core/test/test_SimpleStatefulProcessing01.cxx
- Framework/Core/test/test_SingleDataSource.cxx
- Framework/Core/test/test_TimePipeline.cxx
- Framework/TestWorkflows/src/dataSamplingParallel.cxx
- Framework/TestWorkflows/src/dataSamplingPodAndRoot.cxx
- Framework/TestWorkflows/src/dataSamplingTimePipeline.cxx
- Framework/TestWorkflows/src/o2DiamondWorkflow.cxx
- Framework/TestWorkflows/src/o2DummyWorkflow.cxx
- Framework/TestWorkflows/src/o2ParallelWorkflow.cxx
- Framework/TestWorkflows/src/test_o2RootMessageWorkflow.cxx
- Framework/TestWorkflows/test/test_MakeDPLObjects.cxx
- Utilities/QC/Workflow/src/RootObjectProducerSpec.cxx
As agreed in a past WP4 meeting, we rename allocator to outputs as it
apparently is less confusing.
> Rename `ProcessingContext::allocator()` to `outputs()`

- Detectors/TPC/simulation/include/TPCSimulation/Detector.h
Hi @sawenzel , @matthiasrichter , @ktf , the missing override of TPC::Detector::DefineSensitiveVolumes started to produce an error and blocks other PRs. could you please merge this
> Fix: add missing override for DefineSensitiveVolumes

- run/CMakeLists.txt
This is creating noise in other PRs. We need to disable this as PR tests will become mandatory (i.e. they'll have to be green) soon. Both MT and normal tests have been disabled
> Temporarily disable G4 tests

- macro/o2sim.C
Since the VMC materials and media are created in parallel with those of TGeo, importing the TGeo to VMC leads to duplication of media (and loss of special properties of some media, set directly via VMC).
@sawenzel , @AllaMaevskaya, with this patch (requires updated alidist) the Cerenkov generation in FIT works.
> Forbid importing TGeo to VMC to avoid duplication

- Detectors/MUON/MID/Clustering/test/bench_Clusterizer.cxx
Runs a series of benchmarks for different number of clusters and cluster size
so that one can test the timing evolution in different occupancy conditions.
> Improve MID clustering benchmark

- Detectors/ITSMFT/ITS/reconstruction/CMakeLists.txt
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CA/ArrayUtils.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CA/Cell.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CA/Cluster.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CA/Constants.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CA/Event.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CA/IOUtils.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CA/IndexTableUtils.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CA/Label.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CA/Layer.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CA/MathUtils.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CA/PrimaryVertexContext.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CA/Road.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CA/Tracker.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CA/TrackingUtils.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CA/Tracklet.h
- Detectors/ITSMFT/ITS/reconstruction/src/CA/Cell.cxx
- Detectors/ITSMFT/ITS/reconstruction/src/CA/Cluster.cxx
- Detectors/ITSMFT/ITS/reconstruction/src/CA/Event.cxx
- Detectors/ITSMFT/ITS/reconstruction/src/CA/IOUtils.cxx
- Detectors/ITSMFT/ITS/reconstruction/src/CA/IndexTableUtils.cxx
- Detectors/ITSMFT/ITS/reconstruction/src/CA/Label.cxx
- Detectors/ITSMFT/ITS/reconstruction/src/CA/Layer.cxx
- Detectors/ITSMFT/ITS/reconstruction/src/CA/PrimaryVertexContext.cxx
- Detectors/ITSMFT/ITS/reconstruction/src/CA/Road.cxx
- Detectors/ITSMFT/ITS/reconstruction/src/CA/Track.cxx
- Detectors/ITSMFT/ITS/reconstruction/src/CA/Tracker.cxx
- Detectors/ITSMFT/ITS/reconstruction/src/CA/TrackingUtils.cxx
- Detectors/ITSMFT/ITS/reconstruction/src/CA/Tracklet.cxx
Hi @shahor02 , @iouribelikov ,
this is the fix I was mentioning, sorry it took longer than expected. The allocation for the lookup table has been fixed adding a linear term to our formula. However this might not be the _final_ solution: in the cases I have tested it always give a 30-40% margin where it was failing before, however I will have to test it on larger pp and Pb-Pb samples and with continuous readout.
Only the first commit contains the relevant changes, the second one is only clang-format noise...
Cheers,
Max
> Fix ITS CA tracker crash

- Detectors/MUON/MID/Base/include/MIDBase/GeometryTransformer.h
- Detectors/MUON/MID/Base/src/GeometryTransformer.cxx
- Detectors/MUON/MID/Base/test/testGeometryTransformer.cxx
So that it can be used with either float or double.
This is particularly useful to circumvent floating point precision in boost tests.
> Templetize the geometry transformer

- DataFormats/Detectors/TPC/CMakeLists.txt
- DataFormats/Detectors/TPC/include/DataFormatsTPC/ClusterGroupAttribute.h
- DataFormats/Detectors/TPC/include/DataFormatsTPC/ClusterNative.h
- Detectors/TPC/reconstruction/src/TPCCATracking.cxx
- Adding structure ClusterGroupAttribute as the base for the ClusterNativeContainer
this struct can also be used for a flattened buffer sent over the wire
- Adding structure ClusterGroupHeader extending the attribute by one member for
number of clusters, this is required for sending concatenated flattened containers
- ClusterNativeAccessFullTPC: making the pointer const, this class is intended
to index multiple cluster arrays for read access
- correct implemenatton of the cluster conversion using a separate index
to access non const pointers for writing the converted clusters
> Enhancing access tools for TPC ClusterNative data

- Framework/Core/include/Framework/RootTreeReader.h
This is a follow up to PR #984, which changes DPL `OutputSpec` to `Output`.
> Adjusting class ducomentation and default template type after PR #984

- Steer/include/Steer/HitProcessingManager.h
Without the header, compilation fails with GCC 7.2 for me
> Add missing header

- macro/run_digi_its.C
- macro/run_digi_its.sh
- Current macro for digitization does not set the proper flag for continuous readout mode in ITS in the `o2sim_grp.root` file.
- Adapted the function to be more friendly when working with files generated with `o2sim`.
- The changes are freely picked up from the `run_digi_all.C` macro in the same directory, adapted to work with ITS only.
- Notice that this can be taken as a proposal, but my idea is that eventually we would have something that works properly with continuous readout.
> Fix flagging in GRP file for CRO

- Utilities/MCStepLogger/src/MCStepLoggerImpl.cxx
Some lookup structures need to be cleared for each logged event;
This was previously forgotten.
> MCStepLogger: Clear lookup structure for each entry

- Utilities/O2Device/include/O2Device/O2Device.h
- cmake/O2Dependencies.cmake
- cmake/modules/FindMonitoring.cmake
I'm not sure from where I could pick up channel metrics.
This is the code to do so:
```cpp
for (const auto& mi : fChannels) {
for (const auto& vi : mi.second) {
monitoring->sendGrouped(vi.GetChannelName(), {
{(uint64_t) vi.GetBytesTx(), "BytesTx"},
{(uint64_t) vi.GetBytesRx(), "BytesRx"},
{(uint64_t) vi.GetMessagesTx(), "MessagesTx"}
{(uint64_t) vi.GetMessagesRx(), "MessagesRx"}
}); 
}   
}
```
Remove `#include "options/FairMQProgOptions.h"` as soon as https://github.com/FairRootGroup/FairRoot/pull/745 is merged and new version of FairRoot released in `alisw`.
> Provide monitoring in O2Device

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/InputSpec.h
- Framework/Core/src/StreamOperators.cxx
This is a small addition to allow convenient printout, more operators like this can go into the same file
> Defining stream output operator for Framework/InputSpec.h

- Detectors/FIT/simulation/src/Detector.cxx
* remove unused includes
* remove use of TLorentzVector in favour of faster
TVirtualTrackPosition(float, float, float) interface
> FIT: Use new TVirtual::TrackPosition interface

- Framework/Core/src/runDataProcessing.cxx
This generalizes the exit control logic
to allow exiting from devices marked with "readToQuit(false)".
With this, my workflows are now able to quit themselves when work is done using
the "readyToQuit(false)" API.
> Framework: Generalize quitting control logic

- CMakeLists.txt
When not using alibuild to configure a build (e.g. from CLion or VSCode with Ninja for instance...), I've ran a couple of times into the issue of not getting the simulation stuff (e.g. o2sim) built (because I  forgot to set the LD_LIBRARY_PATH for Geant3/4 before cmake, or forgot to specify Pythia6 path, or ...)
As the simulation env. depends on 5 variables, having a message printing those out helps finding out which one is causing problem more easily...
> Some helpful message of why a simulation environment cannot be found

- Framework/Core/include/Framework/DataAllocator.h
- Framework/Core/include/Framework/OutputRef.h
- Framework/Core/include/Framework/OutputSpec.h
- Framework/Core/src/DataAllocator.cxx
- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/TestWorkflows/src/o2DiamondWorkflow.cxx
- Framework/TestWorkflows/src/o2DummyWorkflow.cxx
This should reduce the verbosity of the output API by allowing assigning
a label to the OutputSpec and use such a label to refer to it.
> Allow referencing outputs by label

- DataFormats/Headers/include/Headers/DataHeader.h
- DataFormats/Headers/src/DataHeader.cxx
@mkrzewic, what was the reason for having the data origin definitions in the compiled library rather than defining them `constexpr`. I simply don't remember, and maybe we can change it.
> DataHeader: Using constexpr for all defined constants and minor cleanup

- Detectors/TPC/simulation/include/TPCSimulation/HitDriftFilter.h
- Detectors/TPC/simulation/include/TPCSimulation/Point.h
- Detectors/TPC/simulation/src/DigitizerTask.cxx
- Steer/CMakeLists.txt
- Steer/DigitizerWorkflow/CMakeLists.txt
- Steer/DigitizerWorkflow/src/CollisionTimePrinter.cxx
- Steer/DigitizerWorkflow/src/CollisionTimePrinter.h
- Steer/DigitizerWorkflow/src/SimReaderSpec.cxx
- Steer/DigitizerWorkflow/src/SimReaderSpec.h
- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
- Steer/DigitizerWorkflow/src/TPCDriftTimeDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/TPCDriftTimeDigitizerSpec.h
- Steer/include/Steer/HitProcessingManager.h
- cmake/O2Dependencies.cmake
This commit provides a step/initial components towards
the processing of simulated hits using the O2 Data Processing Layer.
The main components are
a) SimReader:
A device which is supposed to read and preprocess hit files generated
by detector simulation. Main tasks are
- reading hits from background + signal simulations
- assigning/sampling collision times based on bunch-crossing parameters
- sampling of background/signal scenarios
- propagating generated information to consuming devices (such as digitization)
b) TPCDriftTimeDigitizer:
A device doing (sectorwise) digitization for the TPC.
The digitization is done in units of drift times which makes
the pileup handling convenient.
What this PR achieves:
- Demonstration of a new parallel workflow using a realistic task
from simulation
Note …
> SimReader device + TPC digitization using DPL

- Framework/ArrowTests/test/test_Arrow01.cxx
Probably an interference from a recent alidist update, the effected unit test has
not been changed recently.
The CI build on macos failsin Framework/ArrowTests/test/test_Arrow01.cxx with error
```
error: ignoring return value of function declared with 'warn_unused_result' attribute
[-Werror,-Wunused-result]
```
Assigning the return value to variables to get rid of this.
> Fix Framework/ArrowTests/test/test_Arrow01.cxx on macos CI

- Detectors/TPC/reconstruction/src/TPCCATracking.cxx
@davidrohr @wiechula 
Bug fixed in TPCCATracking.cxx. Qtot and Qmax were switched in lines 113 and 114.
> fixed Qmax and Qtot in TPCCATracking.cxx

- Detectors/CMakeLists.txt
- Detectors/gconfig/CMakeLists.txt
- Detectors/gconfig/include/SimSetup/SimSetup.h
- Detectors/gconfig/src/G3Config.cxx
- Detectors/gconfig/src/G4Config.cxx
- Detectors/gconfig/src/GConfLinkDef.h
- Detectors/gconfig/src/SimSetup.cxx
- Steer/DigitizerWorkflow/CMakeLists.txt
- Steer/DigitizerWorkflow/src/TPCDriftTimeDigitizerSpec.cxx
- cmake/O2Dependencies.cmake
- macro/o2sim.C
Compile the simulation configutation into a library;
Avoids macro interpretation at runtime and leads to
visibly faster simulation setup and reduced memory footprint (~40MB)
This needs a syncronized commit in FairRoot
> Compiled sim setup

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/CallbackRegistry.h
- Framework/Core/include/Framework/CallbackService.h
- Framework/Core/include/Framework/DataProcessingDevice.h
- Framework/Core/include/Framework/DataSourceDevice.h
- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/src/DataSourceDevice.cxx
- Framework/Core/src/runDataProcessing.cxx
- Framework/Core/test/test_CallbackRegistry.cxx
- Framework/Core/test/test_Services.cxx
- Framework/Core/test/test_SimpleStatefulProcessing01.cxx
The `CallbackService` can be used to register hooks to be invoked by the framework at different processing stages, currently `Start`, `Stop`, and `Reset` are supported which correspond to the `PreRun`, `PostRun`, and `Reset` methods of `FairMQDevice`.
There has also been a modification to store service registry by reference in the DPL devices.
The service registry is passed by reference to the constructor but inside a copy was stored, likely by accident, fixed with this commit.
> Introducing a CallbackService to the DPL

- Examples/flp2epn-distributed/src/EPNReceiver.cxx
- Utilities/DataFlow/src/EPNReceiverDevice.cxx
Depending on the distribution / compiler implicit inclusion of
iomanip changes. This includes them directly where needed
for std::setw.
> Fix a few missing include errors

- cmake/O2Dependencies.cmake
On ubuntu 16.04 gcc (Ubuntu 6.4.0-17ubuntu1~16.04) 6.4.0 20180424
there has been a problem after commits 9361b501d3c6e89710bff41d57a5527166eb1a28 and ed822260d877af5b079172420ec840ed92bc3893, symbols from libpythia6.so could not be found in `EGPythia6`.
```
sw/ubuntu1604_x86-64/ROOT/v6-12-04-1/lib/libEGPythia6.so: undefined reference to `pyinit_'
sw/ubuntu1604_x86-64/ROOT/v6-12-04-1/lib/libEGPythia6.so: undefined reference to `py1ent_'
sw/ubuntu1604_x86-64/GEANT3/v2-5-1/lib/libgeant321.so: undefined reference to `pyeevt_'
collect2: error: ld returned 1 exit status
```
It turned out that `libEGPythia6` is in the list of dependencies of `libSimSetup`
but not `libpythia6` despite both are specified as dependencies. Moving the
two lines further down makes also `libpythia6` appear as …
> Fixing build problem with libSimSetup.so

- Detectors/TPC/workflow/src/ClusterConverterSpec.cxx
- Detectors/TPC/workflow/src/ClustererSpec.cxx
- Detectors/TPC/workflow/src/RootFileWriterSpec.cxx
- Framework/Core/README.md
- Framework/Core/include/Framework/InputRecord.h
- Framework/Core/test/test_DataAllocator.cxx
- Framework/Core/test/test_InputRecord.cxx
- Framework/Core/test/test_RootTreeReader.cxx
- Framework/TestWorkflows/test/test_MakeDPLObjects.cxx
This reflects the outcome of the discussion following PR #973. The result for
`get<T>` (`T` not being a pointer) is either
- a smart pointer for type `T`, or
- an object providing iterator and begin/end methods to access elements
Special cases like `get<const char*>` and `get<std::string>` are preserved.
The smart-pointer case is fully covered by `unique_ptr` with the custom deleter
already available. We can later consider to factor out to separate file.
As for containers, currently only serialized std containers of types with
ROOT dictionary are supported. A general `container_ref` type implementation is
in progress.
I also want to keep the other approach in a separate commit for the record.
> Unifying the return type of the DPL input API 

- Algorithm/test/headerstack.cxx
- DataFormats/Headers/include/Headers/DataHeader.h
- DataFormats/Headers/test/testDataHeader.cxx
- Framework/Core/src/DataAllocator.cxx
- Framework/Core/src/ExternalFairMQDeviceProxy.cxx
- Utilities/O2Device/include/O2Device/O2Device.h
I think in the end it was not such a great idea to expose the internals, in the future maybe Stack should become a class instead of struct.
> Hide header::Stack internals in preparation of future updates

- DataFormats/simulation/include/SimulationDataFormat/MCTruthContainer.h
- DataFormats/simulation/test/testMCTruthContainer.cxx
This commit introduces a new function, with which
we can merge/append a truth container at the end of another one.
(This is necessary for instance when the original data containers
(digits) get appended).
Also fixing a few unsigned/signed comparisions.
> Be able to merge MC truth containers

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/DataAllocator.h
- Framework/Core/include/Framework/DataRelayer.h
- Framework/Core/include/Framework/FairMQDeviceProxy.h
- Framework/Core/include/Framework/InputRecord.h
- Framework/Core/include/Framework/RootObjectContext.h
- Framework/Core/src/DataAllocator.cxx
- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/src/DataSourceDevice.cxx
- Framework/Core/src/ExternalFairMQDeviceProxy.cxx
- Framework/Core/src/FairMQDeviceProxy.cxx
Because of its dependency on Boost mpl and Boost fusion,
including FairMQDevice.h is very heavy duty for the compiler.
Given that the FairMQDevice is not really needed, but only the Transport
and the correct serialization policy, we simply move to use those
directly.
> Shield DPL workflows from FairMQDevice

- .clang-format
- .travis.yml
Too many things fall apart when clang-format tries to be smart about
reflowing long lines, resulting in a clearly more confusing resulting
code.
This prevents the reflowing, but results in less far positives. While
I fully agree that long lines are bad, I guess people in general tend
to avoid those and the benefit for the number of false positives is too
low.
> Do not try to be smart about long lines

- Steer/DigitizerWorkflow/src/SimReaderSpec.cxx
- Steer/include/Steer/HitProcessingManager.h
- Steer/src/HitProcessingManager.cxx
This should allow to execute (DPL) workflows for say the digitization of TPC and ITS separately since we can backup the sampled collisions and reuse them.
> Be able to store/load RunContext

- DataFormats/Headers/include/Headers/DataHeader.h
- DataFormats/Headers/test/testDataHeader.cxx
- Detectors/TPC/workflow/src/ClusterReaderSpec.cxx
- Detectors/TPC/workflow/src/DigitReaderSpec.cxx
- Framework/Core/include/Framework/DataAllocator.h
- Framework/Core/include/Framework/DataRefUtils.h
- Framework/Core/include/Framework/Output.h
- Framework/Core/include/Framework/OutputRef.h
- Framework/Core/src/DataAllocator.cxx
- Framework/Core/test/test_DataAllocator.cxx
- Framework/Utils/include/Utils/RootTreeReader.h
- Framework/Utils/test/test_RootTreeReader.cxx
Supporting header stack in the DPL output API
- Introducing optional header stack parameter to Output description
- Adding helper method to access headers from the header stack at DPL input
- removing code duplication
Closes #950
> Supporting header stack in the DPL output API

- Detectors/Base/src/Detector.cxx
- Detectors/Base/src/MaterialManager.cxx
- macro/o2sim.C
Decoupling TGeo material creation from VMC (i.e. can now build TGeo material without having to instantiate first a TGeant3TGeo or TGeant4 object)
This is done by inverting the current responsabilities. TGeo is now the master in charge of
creating the geometry, and VMC is just the client taking the geometry
from TGeo (and possibly tweaking media properties which cannot be
handled by TGeo itself).
The net advantage is to get a lighter dependency tree and is useful e.g. to build a geometry within a unit test.
> Allow the creation of a(n almost) full geometry w/o a prior VMC instance

- Generators/include/Generators/Pythia8Generator.h
- Generators/src/Pythia8Generator.cxx
The Pythia8Generator header had several issues:
- it included lots of header files from Pythia8, which notably
let to a problem when dlfn is included as well
(as Pythia8 redefines a symbol from dlfn for whatever reason)
- This problem is now solved by forward declarations, also
leading to faster compilation
- Also avoiding a global "using namespace" in a header file
> Fix issues in Pythia8Generator header

- Detectors/TPC/base/include/TPCBase/CDBInterface.h
- Detectors/TPC/base/src/CDBInterface.cxx
- Detectors/TPC/base/test/testTPCCDBInterface.cxx
- Detectors/TPC/reconstruction/macro/testTracks.C
- Detectors/TPC/simulation/include/TPCSimulation/ElectronTransport.h
- Detectors/TPC/simulation/include/TPCSimulation/GEMAmplification.h
- Detectors/TPC/simulation/include/TPCSimulation/HitDriftFilter.h
- Detectors/TPC/simulation/include/TPCSimulation/SAMPAProcessing.h
- Detectors/TPC/simulation/src/DigitGlobalPad.cxx
- Detectors/TPC/simulation/src/Digitizer.cxx
- Detectors/TPC/simulation/src/DigitizerTask.cxx
- Detectors/TPC/simulation/src/ElectronTransport.cxx
- Detectors/TPC/simulation/src/GEMAmplification.cxx
- Detectors/TPC/simulation/src/SAMPAProcessing.cxx
- Detectors/TPC/simulation/test/testTPCDigitContainer.cxx
- Detectors/TPC/simulation/test/testTPCElectronTransport.cxx
- Detectors/TPC/simulation/test/testTPCGEMAmplification.cxx
- Detectors/TPC/simulation/test/testTPCSAMPAProcessing.cxx
- Steer/DigitizerWorkflow/src/TPCDriftTimeDigitizerSpec.cxx
o temporarily cached in the corresponding classes to avoid performance bias due to many CDB queries
o cached parameters are updated for every event
o removal of many static functions as a preparation for code re-structurization
o Prepare option to decalibrate with a gain map
> CDB acces for calibration parameter retrieval

- Steer/DigitizerWorkflow/src/TPCDigitRootWriterSpec.cxx
In some circumstances the branchname given to the tree was empty.
Somehow the literal char* did not get converted correctly to the final
branch name. Using strings instead of char* seems to solve the problem.
> TPCDigitWriter: Fix a problem with empty branch names

- Framework/Core/src/DeviceMetricsInfo.cxx
- Framework/Core/src/LogParsingHelpers.cxx
- Framework/Core/src/TextControlService.cxx
- Framework/Core/src/runDataProcessing.cxx
Regular expressions were avoided/optimized as much as possible. This code is
executed very frequently on the control process and profiling shows it had,
before optimization, a heavy impact on the workflow.
After optimization, the vast majority of the CPU time is spent in the regular
expression parsing metrics. There are still margins of optimization there.
Note that we rely on the fact that:
* control messages use log level "INFO"
* metrics use an unknown log level
> Improve log parsing speed for control and metrics

- Framework/Core/src/LogParsingHelpers.cxx
- Framework/Core/src/TextControlService.cxx
- Framework/Core/test/test_LogParsingHelpers.cxx
Optimization done in #1172 broke parsing of control messages.
@matthiasrichter the problem of failing tests was NOT in your code
@ktf another shining example of brown paper bag bug
> DPL: fix logic of optimized ctl messages parsing

- Detectors/Base/include/DetectorsBase/Detector.h
- Detectors/Base/include/DetectorsBase/MaterialManager.h
- Detectors/Base/src/Detector.cxx
- Detectors/Base/src/MaterialManager.cxx
- Detectors/Passive/include/DetectorsPassive/Hall.h
- Detectors/Passive/src/Hall.cxx
- Detectors/TPC/simulation/include/TPCSimulation/Detector.h
- Detectors/TPC/simulation/src/Detector.cxx
- Detectors/gconfig/SetCuts.h
- Detectors/gconfig/src/G3Config.cxx
- Detectors/gconfig/src/G4Config.cxx
Production cuts and settings of processes for GEANT (or other possible engines) are now done via the MaterilaManager. This applies to both global settings and those for single media.
In order to have the cuts correctly available the MaterialManager helds a list of the respective parameters. In that way O2 is capable to abstract from specific engines later on making the processes/cuts O2 dependend and not engine dependent having the MaterialManager as an interface.
Also, some interfaces are added to MaterialManager to get/print processes and cuts.
Proof-of-concept implementations have been done for the TPC and HALL. In the former case the old implementation in O2 was changed now using the MaterialManager interface; for the HALL cuts were ported from in AliRoot.
Medium IDs of TPC and HALL …
> cuts/processes via MaterialManager; TPC, HALL as proof of concept

- Utilities/MCStepLogger/src/StepInfo.cxx
Use `TVirtualMC::TrackStep()` and `TVirtualMC::MaxStep()` to extract length of current step and maximum step size allowed in current medium, respectively.
> Add extraction of step length and maxstep length

- DataFormats/Detectors/ITSMFT/common/include/DataFormatsITSMFT/Cluster.h
- DataFormats/Reconstruction/include/ReconstructionDataFormats/BaseCluster.h
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/ClustererTask.h
- Detectors/ITSMFT/ITS/reconstruction/src/ClustererTask.cxx
- Detectors/ITSMFT/ITS/reconstruction/src/CookedTracker.cxx
- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/DigitizerTask.h
- Detectors/ITSMFT/MFT/reconstruction/include/MFTReconstruction/ClustererTask.h
- Detectors/ITSMFT/MFT/reconstruction/src/ClustererTask.cxx
- Detectors/ITSMFT/MFT/simulation/include/MFTSimulation/DigitizerTask.h
- Detectors/ITSMFT/common/reconstruction/CMakeLists.txt
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/Clusterer.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/PixelData.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/PixelReader.h
- Detectors/ITSMFT/common/reconstruction/src/Clusterer.cxx
- Detectors/ITSMFT/common/reconstruction/src/ITSMFTReconstructionLinkDef.h
- Detectors/ITSMFT/common/reconstruction/src/PixelData.cxx
- Detectors/ITSMFT/common/reconstruction/src/PixelReader.cxx
- Detectors/ITSMFT/common/simulation/include/ITSMFTSimulation/AlpideSignalTrapezoid.h
- Detectors/ITSMFT/common/simulation/include/ITSMFTSimulation/DigiParams.h
- Detectors/ITSMFT/common/simulation/include/ITSMFTSimulation/Digitizer.h
- Detectors/ITSMFT/common/simulation/src/AlpideSignalTrapezoid.cxx
- Detectors/ITSMFT/common/simulation/src/DigiParams.cxx
- Detectors/ITSMFT/common/simulation/src/Digitizer.cxx
- macro/run_clus_its.C
- macro/run_digi_its.C
In the default clusterization mode the o2::ITSMFT::Clusterer will reject in every ROFrame 
those pixels which were fired in the previous ROFrame (due to the long signal over threshold).
Option can be configured via:
clusterer->setMaskOverflowPixels(bool);
e.g.
o2::ITS::ClustererTask task;
task->getClusterer().setMaskOverflowPixels(true);
Same for the o2::MFT::ClustererTask
> Alpide clusterer can mask pixels fired in previous ROFrame

- Detectors/ITSMFT/common/reconstruction/src/PixelData.cxx
static_assert with no message is a C++17 extension
> add message to static_assert to comply with C++ standard

- DataFormats/MemoryResources/include/MemoryResources/MemoryResources.h
This is the only safe thing to do unless pointer-to-message association
is kept within the transport factory. In this case we just have to make
sure to have exactly one allocator per transport factory (so always use
getTransportAllocator(...)).
This was a case of a brown-paper-bag bug. Will add some testing functionality to catch these kinds of bugs at some point.
> Opt for the safer variant of allocator is_equal check

- DataFormats/Headers/include/Headers/DataHeader.h
- Utilities/DataFlow/src/HeartbeatSampler.cxx
- Utilities/DataFlow/src/SubframeBuilderDevice.cxx
- Utilities/O2Device/README.md
- Utilities/O2Device/include/O2Device/O2Device.h
- Utilities/O2Device/include/O2Device/Utilities.h
- Utilities/O2Device/test/test_O2Device.cxx
- Utilities/O2MessageMonitor/include/O2MessageMonitor/O2MessageMonitor.h
- Utilities/O2MessageMonitor/src/O2MessageMonitor.cxx
- Utilities/Publishers/src/DataPublisherDevice.cxx
This cleans up most of current O2Device and moves most functionality out to O2Device/Utilities.h as free standing functions that can be used from any FairMQDevice. It builds on #1140 which enables this split. Also additional tests are added and some documentation. As always, this is work in progress and more is coming in other PRs.
> Cleanup O2Device

- Framework/Core/CMakeLists.txt
- Framework/Core/README.md
- Framework/Core/include/Framework/CompletionPolicy.h
- Framework/Core/include/Framework/CompletionPolicyHelpers.h
- Framework/Core/include/Framework/DataRelayer.h
- Framework/Core/include/Framework/DeviceSpec.h
- Framework/Core/include/Framework/InputRecord.h
- Framework/Core/include/Framework/PartRef.h
- Framework/Core/include/Framework/runDataProcessing.h
- Framework/Core/src/CompletionPolicy.cxx
- Framework/Core/src/CompletionPolicyHelpers.cxx
- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/src/DataRelayer.cxx
- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/Core/src/DeviceSpecHelpers.h
- Framework/Core/src/DriverInfo.h
- Framework/Core/src/FrameworkGUIDebugger.cxx
- Framework/Core/src/InputRecord.cxx
- Framework/Core/src/runDataProcessing.cxx
- Framework/Core/test/test_DataRelayer.cxx
- Framework/Core/test/test_DeviceSpec.cxx
- Framework/Core/test/test_FrameworkDataFlowToDDS.cxx
- Framework/Core/test/test_Graphviz.cxx
- Framework/Core/test/test_InputRecord.cxx
- Framework/Core/test/test_TimeParallelPipelining.cxx
- Framework/TestWorkflows/CMakeLists.txt
- Framework/TestWorkflows/src/o2DiamondWorkflow.cxx
- Framework/TestWorkflows/src/o2ParallelWorkflow.cxx
- Framework/TestWorkflows/src/test_CompletionPolicies.cxx
This introduces the concept of "completion policies" i.e. the ability to
customize when a record (i.e. a set of inputs) being received by a data
processor is ready to be consumed.
Moreover it also fixes a brown paper bag bug which was preventing merging of different timeslices after a timePipeline to work correctly.
> Introduce customizable CompletionPolicy

- DataFormats/Headers/include/Headers/DataHeader.h
- Framework/Core/include/Framework/ChannelMatching.h
- Framework/Core/src/DataAllocator.cxx
- Framework/Core/src/StreamOperators.cxx
- Framework/Core/src/WorkflowHelpers.cxx
- Framework/Core/test/test_DataAllocator.cxx
- Framework/Core/test/test_DeviceSpec.cxx
Channel matching is based on the created channel names rather than data origin and description fields. For this logic to be reliable, the individual strings to build the name from have to be zero terminated.
> Fix #884: fixed creation of channel names to make DPL I/O matching reliable

- DataFormats/Detectors/ITSMFT/common/CMakeLists.txt
- DataFormats/Detectors/ITSMFT/common/include/DataFormatsITSMFT/ClusterPattern.h
- DataFormats/Detectors/ITSMFT/common/include/DataFormatsITSMFT/ClusterTopology.h
- DataFormats/Detectors/ITSMFT/common/include/DataFormatsITSMFT/TopologyDictionary.h
- DataFormats/Detectors/ITSMFT/common/src/ClusterPattern.cxx
- DataFormats/Detectors/ITSMFT/common/src/ClusterTopology.cxx
- DataFormats/Detectors/ITSMFT/common/src/ITSMFTDataFormatsLinkDef.h
- DataFormats/Detectors/ITSMFT/common/src/TopologyDictionary.cxx
- Detectors/ITSMFT/ITS/macros/test/CheckTopologies.C
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/BuildTopologyDictionary.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/LookUp.h
- Detectors/ITSMFT/common/reconstruction/src/BuildTopologyDictionary.cxx
- Detectors/ITSMFT/common/reconstruction/src/LookUp.cxx
A look-up table containing all the IDs of topologies whose bitmap is contained in 1B has been added. Thus it is possible to avoid the computation of the hashcode for the smallest (and very common) topologies when ecountered. Indeed, the LUT element is directly accessed through its 1-Byte bitmap.
Then the dimensions of the groups of rare topologies have changed. Previously, the maximum size of the pattern was 32x32 (defined in `TopologyDictionary`). However, all the topologies with one dimensions exceeding this limit belonged to the group with 32 as number of row or columns. Now, the maximum number of rows/columns has been increased to the highest possible number for a topology with 512 pixels (`Cluster::kMaxPatternBits`).
> Implementation of a look-up table for small topologies and changes in the dimensions of the groups of rare topology.

- Detectors/TOF/simulation/src/Detector.cxx
- run/CMakeLists.txt
This should avoid the problem with the o2sim_G3 test in the CI ... while not fixing it yet.
Also some minor log level change in the TOF detector in order to get less output by default.
> Stability fix for simulation

- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/DigitizerTask.h
- Detectors/ITSMFT/ITS/simulation/src/DigitizerTask.cxx
- Detectors/ITSMFT/MFT/simulation/include/MFTSimulation/DigitizerTask.h
- Detectors/ITSMFT/MFT/simulation/src/DigitizerTask.cxx
- Detectors/ITSMFT/common/simulation/include/ITSMFTSimulation/Digitizer.h
- Detectors/ITSMFT/common/simulation/src/Digitizer.cxx
- macro/run_digi_its.C
ITS/MFT digitizer can process hits from QED backgroung, overlaying it on top of the
hits provided by the central digitization manager
Extra modification:
Store DigiParams in the digitizer only, do not duplicate in the task
Digitizer::process takes as arguments hits vector, source and entry ID to process,
rather than take in from data members, assigned in advance by the DigitizerTask
> Optionally QED hits processing by ITS/MFT digitizer

- Framework/Utils/include/Utils/MakeRootTreeWriterSpec.h
- Framework/Utils/include/Utils/RootTreeWriter.h
- Framework/Utils/test/test_RootTreeWriter.cxx
- Framework/Utils/test/test_RootTreeWriterWorkflow.cxx
Removing the necessity to specify the configuration in two places, first part
as template arguments and second part as arguments to the constructor.
Now the constructor takes a variadic argument list of BranchDef holding type,
input key and branch name. The DPL spec generator is adjusted accordingly.
Here, ```MakeRootTreeWriterSpec::BranchDefinition<T>{ InputSpec{...}, "branchname"}```
is used to specify the input and corresponding branches.
> Get rid of class template arguments

- Steer/include/Steer/O2MCApplication.h
- run/o2sim.cxx
- run/o2sim_parallel.cxx
This is providing one more step to be consistent with the serial and parallel
version of the simulation. Up until now, the parallel version did not call
important hooks on the stack object after each event.
Also adding some total timing information to both o2sim and o2sim_parallel
for better systematic comparison.
> o2sim_parallel: correct stack filtering, add timing information

- Framework/TestWorkflows/src/o2ParallelWorkflow.cxx
The final writer does not need to merge the previous layer
because they are time pipelined.
> DPL: Fix bug in o2ParallelWorkflow

- DataFormats/MemoryResources/include/MemoryResources/MemoryResources.h
- DataFormats/MemoryResources/test/testMemoryResources.cxx
- Framework/Core/src/DataAllocator.cxx
- Framework/Core/src/ExternalFairMQDeviceProxy.cxx
- Utilities/O2Device/README.md
- Utilities/O2Device/include/O2Device/Utilities.h
- Utilities/O2Device/test/test_O2Device.cxx
- Utilities/O2MessageMonitor/src/O2MessageMonitor.cxx
Allow adoption of message data by STL containers.
- adoptVector<Elem>(size_t nelem, ChannelResource* upstream, FairMQMessagePtr message): return a std::vector<const Elem> (const data) while taking ownership of the message to avoid global state - container is (almost) fully self-contained - the global state we have are the transport factories and associated allocators, but that is largely invisible. Ownership of the message can be reclaimed using the standard getMessage() mechanism if data is to be forwarded. 
- some minor modifications to the ChannelResource logic to allow for the above.
- simple tests.
It is work in progress, so interfaces can still be tweaked, names changed, more obscure things moved to ::internal namespace etc.
> Better container adopt using polymorphic allocators

- Framework/Core/include/Framework/InputRecord.h
- Framework/Utils/include/Utils/MakeRootTreeWriterSpec.h
- Framework/Utils/include/Utils/RootTreeWriter.h
- Framework/Utils/test/test_RootTreeWriter.cxx
- Framework/Utils/test/test_RootTreeWriterWorkflow.cxx
Filling of tree fails in some cases with segfault if the address
of the extracted object is used directly. Using a copy until the
problem is solved generically. The problem has been encountered
with std::vector of objects, no investigation so far whether that
is the only case.
Changes in detail:
- Copy extracted object to store variable for filling
- Extending unit test to include all steps of the processing.
- Using InputRecord instead of ProcessingContext as input context
> Bugfix: using object copy instead of address to extracted object

- Framework/Core/src/DeviceSpecHelpers.cxx
Introducing option '--child-driver' to specify an external driver to start
child processes with. It takes one single string with the complete driver
command, put in quotes or use escaped spaces.
Example
```
workflow-exec --child-driver "valgrind --tool=callgrind"
```
The external driver can be applied to individual processes using group options
```
workflow-exec --processname "--child-driver valgrind\ --tool=callgrind"
```
with processname being the name of a process, note the slash-space sequence `\ `
to make the child driver command one single string
> [DPL] add option to start child with external driver, e.g. valgrind

- Framework/TestWorkflows/src/o2SyncReconstructionDummy.cxx
Now command line options are actually taken into account and we
busy loop rather than sleeping to simulate CPU usage.
> DPL: improve sync reco dummy

- Detectors/gconfig/g3Config.C
This commit restores behaviour before 39f4d40077250e62
which took out the SetMaxNStep() setting.
Since the setting is global, it is now applied in
the general configuration for G3.
> Avoid GTRACK: track abandond messages in TPC

- Framework/Core/src/DispatcherDPL.cxx
In the end, it should be done without a copy, this just a quick fix.
> Fix passing POD inputs in DispatcherDPL

- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/Core/src/runDataProcessing.cxx
Use the `--monitoring-backend` option to select to which monitoring backend redirect the metrics pushed by DPL.
> DPL: Allow configuration of monitoring backend

- Framework/Core/include/Framework/ChannelMatching.h
- Framework/Core/src/DeviceSpec.cxx
- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/Core/src/WorkflowHelpers.cxx
This fixes another place where we have a mix between what is the valid
range of outputs and what is the expected input domain.
This cleanup is needed as a first step towards supporting wildcard
expressions.
> Split LogicalChannel and PhysicalChannel classes

- Detectors/TPC/reconstruction/CMakeLists.txt
Rename cmake option as discussed with Max and Dario (use same common name for AliRoot / O2; TPC / ITS)
O2 version of alisw/AliRoot#720
At some point we should perhaps move it further up in the cmake hierarchy, perhaps even to top level.
@dberzano @mpuccio : ping
> Rename GPU CMAKE build options

- DataFormats/Headers/include/Headers/DataHeader.h
- DataFormats/MemoryResources/include/MemoryResources/MemoryResources.h
- Framework/Core/include/Framework/TMessageSerializer.h
- Framework/Core/src/TMessageSerializer.cxx
- Framework/Core/test/test_DataAllocator.cxx
- Framework/Core/test/test_TMessageSerializer.cxx
- Utilities/O2Device/include/O2Device/Utilities.h
- Utilities/Publishers/include/Publishers/DataPublisherDevice.h
- Utilities/Publishers/src/DataPublisherDevice.cxx
- Utilities/aliceHLTwrapper/macros/overlayClusters.C_backup
this is to avoid clashes with std::byte of C++17
> Move temporary "byte" definition to o2:: namespace

- Framework/Core/CMakeLists.txt
- Framework/Core/test/test_ProcessorOptions.cxx
- Framework/Core/test/test_WorkflowOptions.cxx
We have to send at least one message to make sure that the callback of the consumer
is called to request termination via the ControlService. Depending on the scheduler,
the ControlService of the consumer might not be running when the producer sends the
termination command for all devices. And then termiation for the consumer is never
triggered.
This will however not fix the problem that sometimes the device does not terminate
correctly. The typical signature is that the device gets the terminate signal and
leaves the RUNNING state, entering READY state is the last message.
>  Fixing sporadically failing unit test 

- Framework/Core/include/Framework/Task.h
The expansion of parameter packs handles automatically empty parameter packs.
> Fix of parameter pack forwarding and removal of useless override

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/DataSamplingCondition.h
- Framework/Core/src/DataSamplingConditionRandom.cxx
- Framework/Core/test/test_DataSamplingCondition.cxx
- cmake/O2Dependencies.cmake
There were feature requests concerning the way of taking decisions about sampling data - some users would like to receive not only random samples, but f.e. 3 consecutive during some periods. This commit prepares place for such a need.
DataSamplingCondition is not used yet by Dispatchers, but it will be when DataSamplingPolicy is implemented.
@Barthelemy
> Introduce standarised Data Sampling condition

- Detectors/FIT/simulation/src/Detector.cxx
TrackIDs for FIT hits where not correct in the
simulation file. We need to communicate to the stack
that a certain track left a hit, for this to be correct.
This commit fixes this for FIT, but we need to revise
all detectors. I guess this calls for a more framework-like
solution where the registration is done automatically.
> Fix trackID issue in FIT hits

- Common/Utils/CMakeLists.txt
- Common/Utils/include/CommonUtils/BoostSerializer.h
- Common/Utils/test/testBoostSerializer.cxx
- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/DPLBoostSerializer.h
- cmake/O2Dependencies.cmake
Implementation of A DPL-compliant dataset serialiser.
It works flawlessly for STL containers such as vectors, arrays and lists.
It can be used for raw arrays.
This utility makes use of boost serialisation routines.
Various tests are performed on the DPL-independent methods.
A DPL workflow will be added to the tests to perform top-level checks.
> Implementation of DPL serializer using boost serialization routines

- Generators/src/GeneratorFactory.cxx
- Generators/src/Pythia8Generator.cxx
1) decays performed by pythia are limited to 0.1mm (no B-field assumed), TOF of decayed track is
propagated to the FairPrimaryGenerator.
2) Pythia uses mm and mm/c units, when adding its particles to FairPrimaryGenerator, convert
them to cm, s.
> Fix in pythia8: limit decays dist + correct dimensions

- Detectors/Base/include/DetectorsBase/Detector.h
- Detectors/EMCAL/simulation/include/EMCALSimulation/Detector.h
- Detectors/EMCAL/simulation/src/Detector.cxx
- Detectors/FIT/simulation/include/FITSimulation/Detector.h
- Detectors/FIT/simulation/src/Detector.cxx
- Detectors/HMPID/simulation/include/HMPIDSimulation/Detector.h
- Detectors/HMPID/simulation/src/Detector.cxx
- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/Detector.h
- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
- Detectors/ITSMFT/MFT/simulation/include/MFTSimulation/Detector.h
- Detectors/ITSMFT/MFT/simulation/src/Detector.cxx
- Detectors/MUON/MCH/Simulation/include/MCHSimulation/Detector.h
- Detectors/MUON/MCH/Simulation/src/Detector.cxx
- Detectors/PHOS/simulation/include/PHOSSimulation/Detector.h
- Detectors/PHOS/simulation/src/Detector.cxx
- Detectors/TOF/simulation/include/TOFSimulation/Detector.h
- Detectors/TOF/simulation/src/Detector.cxx
- Detectors/TPC/simulation/include/TPCSimulation/Detector.h
- Detectors/TPC/simulation/src/Detector.cxx
- Detectors/TRD/simulation/include/TRDSimulation/Detector.h
- Detectors/TRD/simulation/src/Detector.cxx
This commit provides a more "framework" like approach to implementing
CloneModule for detectors. From now on this function can no longer be forgotten
and the requirements for G4-MT are automatically satisfied. This works
by using the templated DetImpl class.
This commit follows the "dont-repeat-yourself" principle. I plan to extend
it to other common functions in simulation detector code.
> Code reduction: Automatically implement CloneModule for detectors

- run/CMakeLists.txt
The G4 tests are failing on our MacOS CI machine.
I could not reproduce this error anywhere else but
I am switching off these tests temporarily, and on MacOS
only, until a solution is found.
> Switch off failing G4 tests on MacOS

- Detectors/Base/include/DetectorsBase/Detector.h
- Detectors/EMCAL/simulation/include/EMCALSimulation/Detector.h
- Detectors/EMCAL/simulation/src/Detector.cxx
- Detectors/FIT/simulation/include/FITSimulation/Detector.h
- Detectors/FIT/simulation/src/Detector.cxx
- Detectors/HMPID/simulation/include/HMPIDSimulation/Detector.h
- Detectors/HMPID/simulation/src/Detector.cxx
- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/Detector.h
- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
- Detectors/ITSMFT/MFT/simulation/include/MFTSimulation/Detector.h
- Detectors/ITSMFT/MFT/simulation/src/Detector.cxx
- Detectors/MUON/MCH/Simulation/include/MCHSimulation/Detector.h
- Detectors/MUON/MCH/Simulation/src/Detector.cxx
- Detectors/PHOS/simulation/include/PHOSSimulation/Detector.h
- Detectors/PHOS/simulation/src/Detector.cxx
- Detectors/TOF/simulation/include/TOFSimulation/Detector.h
- Detectors/TOF/simulation/src/Detector.cxx
- Detectors/TPC/simulation/include/TPCSimulation/Detector.h
- Detectors/TPC/simulation/src/Detector.cxx
- Detectors/TRD/simulation/include/TRDSimulation/Detector.h
- Detectors/TRD/simulation/src/Detector.cxx
Provide a stricter detector initialization mechanism.
In the past, each detector was expected/obliged to call
the init function of the mother class itself. This is now
expressed in a better mechanism.
Also leads to less code.
> Better (less error prone) detector initialization

- Framework/Core/include/Framework/DataAllocator.h
- Framework/Core/include/Framework/DataProcessingDevice.h
- Framework/Core/include/Framework/DataSourceDevice.h
- Framework/Core/include/Framework/MessageContext.h
- Framework/Core/include/Framework/RootObjectContext.h
- Framework/Core/include/Framework/TimingInfo.h
- Framework/Core/src/DataAllocator.cxx
- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/src/DataSourceDevice.cxx
Initially the timing information was hold into MessageContext as that
one was the only one existing. As we add serialization methods and
therefore possibly add new Contextes it makes sense to separate the
timing information out of the context, so that we avoid duplicating it.
This is propedeutic to support Arrow based serialization and
sub timeframe serialization.
> DPL: Move timing out of message contextes

- Utilities/MCStepLogger/CMakeLists.txt
- Utilities/MCStepLogger/README.md
- Utilities/MCStepLogger/include/MCStepLogger/BasicMCAnalysis.h
- Utilities/MCStepLogger/include/MCStepLogger/MCAnalysis.h
- Utilities/MCStepLogger/include/MCStepLogger/MCAnalysisFileWrapper.h
- Utilities/MCStepLogger/include/MCStepLogger/MCAnalysisManager.h
- Utilities/MCStepLogger/include/MCStepLogger/MCAnalysisUtilities.h
- Utilities/MCStepLogger/include/MCStepLogger/MetaInfo.h
- Utilities/MCStepLogger/include/MCStepLogger/ROOTIOUtilities.h
- Utilities/MCStepLogger/include/MCStepLogger/StepInfo.h
- Utilities/MCStepLogger/src/BasicMCAnalysis.cxx
- Utilities/MCStepLogger/src/MCAnalysis.cxx
- Utilities/MCStepLogger/src/MCAnalysisFileWrapper.cxx
- Utilities/MCStepLogger/src/MCAnalysisManager.cxx
- Utilities/MCStepLogger/src/MCAnalysisUtilities.cxx
- Utilities/MCStepLogger/src/MCStepInterceptor.cxx
- Utilities/MCStepLogger/src/MCStepLoggerImpl.cxx
- Utilities/MCStepLogger/src/MCStepLoggerLinkDef.h
- Utilities/MCStepLogger/src/ROOTIOUtilities.cxx
- Utilities/MCStepLogger/src/StepInfo.cxx
- Utilities/MCStepLogger/src/analyseMCSteps.cxx
- Utilities/MCStepLogger/src/basicMCAnalysisCI.cxx
- cmake/O2Dependencies.cmake
The framework aims at analysing the step information collected with
the MCStepLogger library during a simulation run. One of the main
goals is the implementation of a CI for O2 detector simulation to be
able to investigate sanity of the simulation at PR-time.
Providing one analysis by default, custom analyses can be added on
the fly and are steered by a central executable.
Interfaces for reading and writing analysis files are provided and
these are hecnce standardised. This enables for straight-forward
plotting and further investigation of the analysis.
Proof-of-concept executable for a possible CI is included for the
default analysis called 'runTestAnalysisBasic'.
> Small and flexible MCStepLogger analysis framework

- Detectors/TPC/reconstruction/src/TPCCATracking.cxx
The GetParam().OuterParam() interface will be dropped in favor of OuterParam() directly.
> Preparations for AliTPCCommon v1.4

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/ContextRegistry.h
- Framework/Core/include/Framework/DataAllocator.h
- Framework/Core/include/Framework/DataProcessingDevice.h
- Framework/Core/include/Framework/DataProcessor.h
- Framework/Core/include/Framework/DataSourceDevice.h
- Framework/Core/include/Framework/InputRecord.h
- Framework/Core/include/Framework/MessageContext.h
- Framework/Core/include/Framework/RootObjectContext.h
- Framework/Core/include/Framework/StringContext.h
- Framework/Core/src/DataAllocator.cxx
- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/src/DataProcessor.cxx
- Framework/Core/src/DataSourceDevice.cxx
- Framework/Core/test/test_SimpleStringProcessing.cxx
This introduces preliminary support to create and send around `std::string`s. While this could have been done in other ways (e.g. using root serialization) we use this as a prototype of what is needed to create yet another serialization backend.
> Add native support to send around strings

- Framework/Core/src/DataProcessingDevice.cxx
The bug was introduced in 'DPL: decouple GUI backend from drawing operations' and it affected f.e. o2DiamondWorkflow.
@ktf
> Fix segfaults of devices using non-standard completion policies

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/TableBuilder.h
- Framework/Core/include/Framework/TableConsumer.h
- Framework/Core/src/TableBuilder.cxx
- Framework/Core/src/TableConsumer.cxx
- Framework/Core/test/test_TableBuilder.cxx
- cmake/O2Dependencies.cmake
This introduces a new TableBuilder helper which allows creating
`arrow::Table` objects in a simple manner. For the moment the type of
each column has to be known at compile time, but it should be fairly
straightforward to make it dynamic.
Paired to that comes a TableConsumer which can be used to create
`arrow::Table` from a previously serialized `arrow::RecordBatch`.
> DPL: Add TableBuilder / TableConsumer for arrow

- Detectors/EMCAL/base/include/EMCALBase/Geometry.h
- Detectors/EMCAL/base/src/Geometry.cxx
Swapping of eta and phi coordinate in module indexing leaded to an
incomplete lookup table with cell centers in Eta and Phi. Therefore only
three cells were possible per supermodule (all others had the same
value). Random comparison with different eta-phi positions ended in the
same cell abs ID with AliRoot and O2.
> [EMCAL-401] Fix geometry bug leading to incorrect cell abs IDs

- Framework/Core/include/Framework/DataProcessingDevice.h
- Framework/Core/src/DataProcessingDevice.cxx
This paves the way to fix several limitation of the current
DataProcessingDevice like the ability to limit polling
on channels which are faster than others or the ability to
have time triggered inputs rather then those which are data
triggered, rendering the "DataSourceDevice" effectively useless.
> DPL: Use ConditionalRun() to steer the inner loop

- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/Core/src/runDataProcessing.cxx
- Framework/TestWorkflows/src/o2DiamondWorkflow.cxx
InfoLogger can now be used as a Framework service by providing the `--infologger-backend` commandline option.
Further integration with FairLogger coming in a different PR.
> DPL: add initial InfoLogger integration to DPL

- Steer/DigitizerWorkflow/CMakeLists.txt
- Steer/DigitizerWorkflow/src/TPCDigitRootWriterSpec.cxx
- Steer/DigitizerWorkflow/src/TPCDriftTimeDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/TPCSectorHeader.cxx
- Steer/DigitizerWorkflow/src/TPCSectorHeader.h
This commit simplifies the communication of the sector number
to which the digit data belongs.
So far this needed to be communicated via a separate channel.
Now it is done using the header stack feature, which allows to attach
meta-information to messages.
> Digitizer-workflow: Communicate TPC sector as part of the header stack

- Framework/Core/README.md
- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/Core/src/runDataProcessing.cxx
This enables using the standard LOG macros to sent data to the
InfoLogger. See README.md for more details of how to configure this.
> DPL: add InfoLogger as FairLogger stream

- Framework/Core/src/DataSamplingReadoutAdapter.cxx
- cmake/O2Dependencies.cmake
Common is now a dependency of O2, so the copy of DataBlockHeader declaration can be deleted. It addressed [this comment on PR](https://github.com/AliceO2Group/AliceO2/pull/1276#discussion_r207128672).
> Delete a copy of DataBlockHeader structure and refer to its header

- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
- Steer/DigitizerWorkflow/src/TPCDigitRootWriterSpec.cxx
This commit uses the DPL completion-policy mechanism
to write TPC digits or labels into the ROOT file as soon
as they are available in the writer device.
The writer device now takes a lot less memory and distributes its
CPU activity more evenly.
This concludes Jira ticket [O2-268].
> Use DPL completion policy in TPCDigitWriter

- Framework/Core/include/Framework/DataRelayer.h
- Framework/Core/src/DataRelayer.cxx
While being just a minor performance improvement, this refactoring
will come useful with the coming integration of proper Lifetime for
objects.
> DPL: create index of distinct InputRoutes

- Detectors/TOF/base/src/Geo.cxx
This is a bug fix. I found that the Info() API (from ROOT?) interferes
with the LOG(INFO) system from FairLogger. Since the latter is also used for
control in DPL, some control messages were sometimes not dispatched
correctly leading to non-exiting DPL workflows.
> Use LOG(INFO) instead of Info()

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/TypeTraits.h
- Framework/Core/src/runDataProcessing.cxx
- Framework/Core/test/test_PtrHelpers.cxx
FairMQ changed `FairMQDevice::fDevice` to a shared_ptr from a
unique_ptr. This makes sure we can compile DPL with both version and
introduces an helper to handle this kind of situations in the future
when updating might not be an option.
> DPL: adapt to support new FairMQ versions

- Steer/DigitizerWorkflow/src/SimReaderSpec.cxx
- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
We should only digitize detectors which are present in the simulation
file (or which are set as active in the GRP).
This commit makes a first step into this direction by reading
the GRP at startup to influence the workflow setup.
It is hence now possible to start the workflow for selected
components only.
A second way to influence this, might be added later via command line
arguments.
This is related to https://alice.its.cern.ch/jira/browse/O2-356.
> Use GRP information to influence digitization workflow

- Framework/Core/include/Framework/DataProcessingDevice.h
- Framework/Core/src/DataProcessingDevice.cxx
This will allow to dispatch computation also on non FairMQ data
triggered transitions like a timer or a fetch via curl.
> DPL: rework data dispatching event loop

- DataFormats/Headers/include/Headers/RAWDataHeader.h
- DataFormats/Headers/test/test_RAWDataHeader.cxx
RDH v3 consists of 4 64 bit words, each of the words is extended to 128 bits by the CRU
https://docs.google.com/document/d/1otkSDYasqpVBDnxplBI7dWNxaZohctA-bvhyrzvtLoQ
accessed on Sep 12 2018, a pdf version is available under this link
https://alice-o2-project.web.cern.ch/_webdav/files/pdf/RDH%20V3_2.pdf
> Updating RAWDataHeader to version 3

- Framework/Core/src/DeviceSpecHelpers.cxx
Since real people are starting to use DPL, it turns out it is not
particularly user friendly, especially with many devices and without the
GUI, to have so many messages about the performance rate. As a quick fix
I hardcoded a saner value than the current one. This should probably be
made configurable in an easy way.
> DPL: saner rate for rate channel logger

- Common/Utils/CMakeLists.txt
- Common/Utils/include/CommonUtils/CompStream.h
- Common/Utils/src/CompStream.cxx
- Common/Utils/test/testCompStream.cxx
- Utilities/DataCompression/CMakeLists.txt
- Utilities/DataCompression/include/DataCompression/CodingModelDispatcher.h
- Utilities/DataCompression/include/DataCompression/DataDeflater.h
- Utilities/DataCompression/include/DataCompression/HuffmanCodec.h
- Utilities/DataCompression/include/DataCompression/TruncatedPrecisionConverter.h
- Utilities/DataCompression/include/DataCompression/dc_primitives.h
- Utilities/DataCompression/test/DataGenerator.h
- Utilities/DataCompression/test/Fifo.h
- Utilities/DataCompression/test/test_DataGenerator.cxx
- Utilities/DataCompression/test/test_Fifo.cxx
- Utilities/DataCompression/test/test_HuffmanCodec.cxx
- Utilities/DataCompression/test/test_dc_primitives.cxx
- cmake/O2Dependencies.cmake
Adding a stream interface for iostreams with compression filters based on boost::iostreams.
Small incremental update otherwise:
* cleanup license information
* cleanup namespaces and coding convention adjustments
* writing the Huffman configuration in compressed format
> Cleanup and update of data compression utilities

- Common/Utils/src/CompStream.cxx
- Common/Utils/test/testCompStream.cxx
Dependencies need to be resolved first. Lzma package is included in the
software stack already today, but not as a requirement for boost. Furthermore,
boost seems to use a different find procedure, as it does not find the package
in a non-system place.
> Temporarily removing the lzma support from CompStream

- Framework/Utils/include/Utils/RootTreeReader.h
- Framework/Utils/test/test_RootTreeReader.cxx
The process call is now supporting a variadic list of headers which will
be put on the stack.
> Adding support for header stacks to RootTreeReader

- DataFormats/simulation/include/SimulationDataFormat/Stack.h
- DataFormats/simulation/src/Stack.cxx
- Detectors/EMCAL/simulation/src/Detector.cxx
New stack inferfaces allowing to
* query daughter-parent relationships given daughter and parent track ids
* query the full vector of parent ids for the current track
> New interfaces for simulation stack

- Common/SimConfig/include/SimConfig/SimConfig.h
- Common/SimConfig/src/SimConfig.cxx
- Detectors/EMCAL/base/src/Geometry.cxx
- Detectors/EMCAL/simulation/src/Detector.cxx
- Detectors/FIT/simulation/src/Detector.cxx
- Detectors/HMPID/simulation/src/Detector.cxx
- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
- Detectors/ITSMFT/MFT/base/src/GeometryBuilder.cxx
- Detectors/ITSMFT/MFT/base/src/GeometryTGeo.cxx
- Detectors/ITSMFT/MFT/base/src/HalfDetector.cxx
- Detectors/ITSMFT/MFT/base/src/HeatExchanger.cxx
- Detectors/ITSMFT/MFT/base/src/Segmentation.cxx
- Detectors/ITSMFT/MFT/simulation/src/Detector.cxx
- Detectors/TOF/simulation/src/Detector.cxx
- Generators/src/GeneratorFactory.cxx
- macro/build_geometry.C
- run/o2sim.cxx
This commit is doing some cleanup and uniformization on the logging
printouts.
Do
* less logging to INFO since this leads to very large unreadable printouts
at each simulations start
* remove unnecessary endl and "\n"
* favour LOG(INFO) over Info(...) from ROOT
This also introduces a configurability of the logseverity and logverbosity
from the command line. We can now say
```
o2sim --logverbosity veryhigh --logseverity DEBUG3 ...
```
to see everything up to DEBUG3 level with veryhigh verbosity
(see FairLogger for more info).
> o2sim: Make logging info more uniform; Do less logging to info

- DataFormats/Detectors/TPC/CMakeLists.txt
- DataFormats/Detectors/TPC/include/DataFormatsTPC/TPCSectorHeader.h
- DataFormats/Detectors/TPC/src/TPCSectorHeader.cxx
- Detectors/TPC/workflow/README.md
- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- Detectors/TPC/workflow/src/CATrackerSpec.h
- Detectors/TPC/workflow/src/ClusterConverterSpec.cxx
- Detectors/TPC/workflow/src/ClusterConverterSpec.h
- Detectors/TPC/workflow/src/ClusterDecoderRawSpec.cxx
- Detectors/TPC/workflow/src/ClusterDecoderRawSpec.h
- Detectors/TPC/workflow/src/ClustererSpec.cxx
- Detectors/TPC/workflow/src/ClustererSpec.h
- Detectors/TPC/workflow/src/DigitReaderSpec.cxx
- Detectors/TPC/workflow/src/RangeTokenizer.h
- Detectors/TPC/workflow/src/RootFileWriterSpec.cxx
- Detectors/TPC/workflow/src/tpc-reco-workflow.cxx
- Steer/DigitizerWorkflow/CMakeLists.txt
- Steer/DigitizerWorkflow/src/TPCDigitRootWriterSpec.cxx
- Steer/DigitizerWorkflow/src/TPCDriftTimeDigitizerSpec.cxx
- cmake/O2Dependencies.cmake
This implements the processing of TPC digits in individual sectors, the collection in the tracker process and running tracking when the input is complete.
Command line:
```
tpc-reco-workflow --infile tpcdigits.root --disable-mc 1
```
The input can be created by running the simulation (`o2sim`) and the digitizer workflow.
Blockers:
it turns out that the cluster output from the clusterer is not sorted in CRU, so the converter needs to do some sorting into pages, labels also need to be sorted
the decoder expects an array of single raw pages and a corresponding array of labels which need to be create from the single input block of labels, see https://alice.its.cern.ch/jira/browse/O2-394 for reason of splitting the MC container
To be done in the next iteration
> Update of TPC reco workflow

- Framework/Core/CMakeLists.txt
- Framework/Core/README.md
- Framework/Core/include/Framework/CallbackService.h
- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/test/test_CallbackService.cxx
This introduces two new kinds of callbacks in the `CallbackService`:
* `ClockTick`: invoked on each iteration of the FairMQ event loop.
* `Idle`: invoked whenever there was no data to be processed.
> DPL: add Idle & ClockTick callbacks

- Detectors/TPC/workflow/README.md
- Detectors/TPC/workflow/src/CATrackerSpec.cxx
This has actually been forgotten to be added to the options definition while
it was already queried. Have to check why the error message slipped through.
The TPCCATracking worker class can be initialized with a string of options,
e.g. now one can specify --tracker-options "refX=83"
> Adding missing option '--tracker-options' to tracker spec

- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CA/Definitions.h
When CUDA headers are loaded, and the non-CUDA version of ITS tracking is used, these definitions will clash with CUDA. In particular, this automatically fails if ROOT is build against CUDA. This patch is not really perfect, as it only handles the case when the CUDA header is loaded first, but at least it fixes the problem in ROOT, and I do not see a better solution.
> Protection when CUDA headers are loaded

- DataFormats/Detectors/TPC/include/DataFormatsTPC/Cluster.h
- Detectors/TPC/reconstruction/include/TPCReconstruction/ClustererTask.h
Having #include "boost.." in the headers which may end up in the macros makes their compilation impossible unless the ROOT_INCLUDE_PATH is patched.
> remove #include boost: the class is fwd-declared

- Steer/DigitizerWorkflow/src/TPCDigitRootWriterSpec.cxx
Fixing a problem in which sometimes not all sector branches were written in the output file.
> TPCDigitRootWriter: Fix logic to determine when done

- Detectors/TPC/workflow/CMakeLists.txt
- Detectors/TPC/workflow/README.md
- Detectors/TPC/workflow/include/TPCWorkflow/RecoWorkflow.h
- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- Detectors/TPC/workflow/src/CATrackerSpec.h
- Detectors/TPC/workflow/src/ClusterConverterSpec.cxx
- Detectors/TPC/workflow/src/ClusterConverterSpec.h
- Detectors/TPC/workflow/src/ClusterDecoderRawSpec.cxx
- Detectors/TPC/workflow/src/ClusterDecoderRawSpec.h
- Detectors/TPC/workflow/src/ClustererSpec.cxx
- Detectors/TPC/workflow/src/ClustererSpec.h
- Detectors/TPC/workflow/src/DigitReaderSpec.cxx
- Detectors/TPC/workflow/src/DigitReaderSpec.h
- Detectors/TPC/workflow/src/RecoWorkflow.cxx
- Detectors/TPC/workflow/src/tpc-reco-workflow.cxx
Moving TPC reco workflow definition to separate file and creating library for module
TPCWorkflow with reco workflow and processor specs.
Parallel workflow can be configured using option '--tpc-lanes n'
Added features:
- workflow option --tpc-lanes
- DigitReaderSpec fan out
- CATrackerSpec fan in
- adding input type 'digitizer' to connect directly to the digitizer workflow
- adjusting data descriptions to output of digitizer workflow ('DIGITS', 'DIGITSMCTR').
- forwarding empty data sets at end of processing.
- adjusting processor names: prefix tpc
> Implementing parallel processing in the tpc-reco-workflow

- Steer/DigitizerWorkflow/src/SimReaderSpec.cxx
- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
- Steer/DigitizerWorkflow/src/TPCDriftTimeDigitizerSpec.cxx
- cmake/O2Dependencies.cmake
Optionally attaching TPC reco workflow to digitizer workflow
New workflow option `--tpc-reco-type` determines the output of the workflow 
*Note*: at the moment the reco workflo only supports `tracks` as type. 
Some cleanup has been done in the `SimReader` to skip the channel for sector assign as the `TPCSectorHeader` has to be sent anyhow to ensure propagation of the active sectors to the tracker.
> Connecting the TPC reco workflow to the digitizer workflow

- Utilities/Tools/monitorMEM_DPL.sh
The script records memory for each processor participating in a workflow.
For example to record memory for all procs in DPL workflow "digitizer"
simply say
. monitorMEM_DPL digitizer
> Adding a script to monitor memory vs time for DPL workflow

- Steer/DigitizerWorkflow/src/TPCDriftTimeDigitizerSpec.cxx
Solving a memory problem in the digitizer workflow by moving the initialization
of the TPC digitizer into the actual init lambda.
Before it was done in the "getDataProcessorSpec" function. This is not a good place
since in fact every single DPL processor/process with evaluate this function (if it needs it
or not) upon topology creation.
In this case, every single DPL processor was instantiating pixels of a TPC readout chamber...
even though it was not actually doing TPC stuff.
We need to be careful about that. Some other data structures such as shared_ptrs need to be revised
in different places.
On the other hand, I think there is no need that every single processor evaluates the whole topology
at startup. This should really be done by a single master processor which communicates the …
> DPL: Initialize things in the init function and not elsewhere

- Framework/Core/CMakeLists.txt
- Framework/Core/test/test_CustomGUI.cxx
Sometimes it can be handy to create a custom GUI to inspect contents of
a messages, state of the algorithm or simply some custom controls in a
quick, throw away, manner. The example in
`Framework/Core/test/test_CustomGUI.cxx` shows how to do that using the
same kind of toolkit used by the DPL debug GUI.
Notice that in order to keep things simple, the example will open one
new window per initGUI() and requires redrawing on each iteration.
>  DPL: example of how to create a custom GUI

- Detectors/TPC/simulation/src/GEMAmplification.cxx
- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
This commit addresses more memory reductions on top of c0ef1d905dd59f.
With this commit, we avoid setting up the TPC GEM initialization in every
DPL processor by restricting it to the master process. Finding out
if we are in the master process is done using environment variables.
(Reminder: This is an objects which needs to be initialized before the TPC
digitizers which have common access to it, and so this is for the moment done
during global workflow setup.)
It is understood that the final solution will use a different mechanism
(OCDB) but given that we gain ~100MB per processor, it is worth improving
on the existing solution NOW.
The commit also now avoids an error message "File not found" during the actual
setup.
> digitizer-workflow: memory reductions part 2

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/DataProcessingDevice.h
- Framework/Core/include/Framework/DataRelayer.h
- Framework/Core/include/Framework/TimesliceIndex.h
- Framework/Core/include/Framework/TimesliceIndex.inl
- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/src/DataRelayer.cxx
- Framework/Core/test/test_DataRelayer.cxx
- Framework/Core/test/test_TimesliceIndex.cxx
This is done so that TimesliceIndex can be offered as a service to the
ClockTick callback, allowing for new timeslices to be inserted pushed in
the stream without actual data being associated to them. This is a
requirement to get timers and objects from CCDB or any other external
source in the stream.
It also paves the way to a more sophisticated implementation for the
index rather then the current "modulo" one (e.g. it might allow for
multiple entries for the same timeslice as requested by @sawenzel at
some point).
> DPL: refactor and extract a TimesliceIndex from DataRelayer

- Detectors/TPC/workflow/README.md
- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- Detectors/TPC/workflow/src/RecoWorkflow.cxx
- Detectors/TPC/workflow/src/RootFileWriterSpec.cxx
- Detectors/TPC/workflow/src/RootFileWriterSpec.h
Renamed process to tpc-tracks-writer, options are now:
```
Data processor options: tpc-track-writer:
--outfile arg (=tpctracks.root)       Name of the input file
--treename arg (=o2sim)               Name of output tree
--track-branch-name arg (=TPCTracks)  Branch name for TPC tracks
--trackmc-branch-name arg (=TPCTracksMCTruth)
Branch name for TPC track mc labels
```
Also catching possible error code at TPCCATracking initialization, from AliTPCCommon v.1.4.3 the error is returned on unknown option.
> Writing Track MC labels to output file, adjusting default branch names

- Framework/Core/test/test_ProcessorOptions.cxx
While this should have been gracefully handled by FairMQ, it does not
really make sense to quit when the producer is done, as all the testing
happens in the consumer.
> DPL: workaround hanging test

- Algorithm/test/headerstack.cxx
- DataFormats/Headers/include/Headers/DataHeader.h
- DataFormats/Headers/include/Headers/Stack.h
- DataFormats/Headers/test/testDataHeader.cxx
- DataFormats/MemoryResources/include/MemoryResources/Types.h
- Framework/Core/include/Framework/DataAllocator.h
- Framework/Core/include/Framework/Output.h
- Framework/Core/include/Framework/OutputRef.h
- Framework/Core/src/DataAllocator.cxx
- Framework/Core/src/DataSamplingConditionNConsecutive.cxx
- Framework/Core/src/DataSamplingConditionPayloadSize.cxx
- Framework/Core/src/LifetimeHelpers.cxx
- Framework/Core/test/test_DataRelayer.cxx
- Framework/Core/test/test_DataSamplingCondition.cxx
- Framework/Core/test/test_InputRecord.cxx
- Utilities/O2Device/include/O2Device/Utilities.h
- Utilities/aliceHLTwrapper/src/MessageFormat.cxx
- Utilities/aliceHLTwrapper/test/testMessageFormat.cxx
This separates Stack in its own header so that boost is
not exposed when DataHeader is included. Apart from the discussion
of whether we should include boost in our ROOT_INCLUDE_PATH, this
is in any case a good refactoring which separates the data header
descriptions from their actual manipulation.
Notice we still have Stack being exposed in things which might endup in the workflow, so I am not sure this will completely avoid the boost issue...
> DPL: refactor DataHeader to not include boost

- Common/SimConfig/CMakeLists.txt
- Common/SimConfig/doc/ConfigurableParam.md
- Common/SimConfig/include/SimConfig/ConfigurableParam.h
- Common/SimConfig/include/SimConfig/ConfigurableParamHelper.h
- Common/SimConfig/include/SimConfig/SimConfig.h
- Common/SimConfig/src/ConfigurableParam.cxx
- Common/SimConfig/src/ConfigurableParamHelper.cxx
- Common/SimConfig/src/SimConfig.cxx
- Common/SimConfig/test/TestConfigurableParam.cxx
- Detectors/Passive/CMakeLists.txt
- Detectors/Passive/include/DetectorsPassive/HallSimParam.h
- Detectors/Passive/src/Hall.cxx
- Detectors/Passive/src/HallSimParam.cxx
- Detectors/Passive/src/PassiveLinkDef.h
- cmake/O2Dependencies.cmake
- macro/o2sim.C
This commit introduces a concept for configurable parameters, which
means that they are class members which can be, fully-automatic, influenced
from a config file or by other means (command-line, distributed key-value stores).
The commit focuses on providing an automatic mechanism, so that the developer/user
merely needs to declare a parameter class in a special way:
```
class FooParam : public o2::conf::ConfigurableParamHelper<FooParam> {
double getDensity() const { return mDensity; }
private:
double mDensity = 1.1;
int mNPlanes = 2;
O2ParamDef(FooParam, "Foo")
};
```
After this, parameters Foo.mDensity, Foo.mNPlaces are automatically part of
a global parameter database (using boost property_tree) by means of an introspection
mechanism (using ROOT dictionaries).
Parameters can then be …
> A concept for configurable parameters

- Framework/DebugGUI/CMakeLists.txt
- Framework/DebugGUI/include/DebugGUI/imgui.h
- Framework/DebugGUI/test/imgui.h
- Framework/DebugGUI/test/imgui_demo.cpp
- Framework/DebugGUI/test/test_ImGUIHeadless.cpp
Framework/DebugGUI package is a red-herring in terms of coverage, due to
the imported imgui. While the proper solution would be to manage to
compile imgui outside AliceO2, this should increase a bit the actual
coverage.
> DPL GUI: add headless test for ImGUI

- DataFormats/simulation/src/Stack.cxx
- Detectors/FIT/simulation/include/FITSimulation/Detector.h
- Detectors/FIT/simulation/src/Detector.cxx
- Detectors/PHOS/simulation/include/PHOSSimulation/Detector.h
- Detectors/PHOS/simulation/src/Detector.cxx
- Detectors/ZDC/simulation/src/Detector.cxx
- Detectors/gconfig/g4Config.C
- Detectors/gconfig/g4config.in
- in fit::Detector - moved definition of optical properties in ConstructOpGeometry(); fixed copy ctor
- in zdc::Detector - fixed materials definitions
- in phos::Detector - moved defition of sensitive volumes to InitO2Detector()
- in g4config.in - fixed the media names for setting SpecialUrbanMsc model
- in g4Config.C - added commented lines for entering in Geant4 UI (useful for debugging)
- in Data::Stack - added more info in printing about a nonconform detector
> Fixes for Geant4 simulation plus one update:

- Detectors/TPC/simulation/CMakeLists.txt
- Detectors/TPC/simulation/include/TPCSimulation/Digitizer.h
- Detectors/TPC/simulation/include/TPCSimulation/DigitizerTask.h
- Detectors/TPC/simulation/include/TPCSimulation/SpaceCharge.h
- Detectors/TPC/simulation/src/Digitizer.cxx
- Detectors/TPC/simulation/src/DigitizerTask.cxx
- Detectors/TPC/simulation/src/SpaceCharge.cxx
- Detectors/TPC/simulation/src/TPCSimulationLinkDef.h
- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
- Steer/DigitizerWorkflow/src/TPCDriftTimeDigitizerSpec.cxx
- cmake/O2Dependencies.cmake
Adding first version of constant space-charge distortions to TPC simulation. New options to enable distortions in digitizer-workflow.
Usage in digitizer-workflow:
--distortionType 2 (enable constant distortions)
--gridSize 33,180,33 (comma separated list of z,phi,r bin of lookup tables, default value 33,180,33)
--initialSpaceChargeDensity (path to root file with TH3 used as initial space-charge density and name of TH3 (comma separated))
> Adding constant space-charge distortions to TPC simulation

- Detectors/TPC/simulation/include/TPCSimulation/Detector.h
- Detectors/TPC/simulation/src/Detector.cxx
This aligns/uniformizes the definition of TPC sensitive
volumes with how its done for other detectors.
In fact TPC was the only one overriding a FairRoot interface
for this which is now going to be deprecated.
This commit fixes a compile error for defaults-fairroot-dev.
> Fix sensitiveVolume function in TPC

- Detectors/TOF/reconstruction/src/Clusterer.cxx
This commit is removing lots of anwanted empty
lines in the output of TOF digitizer.
Note that with FairLogger it is no longer
necessary to put "\n" nor FairLogger::endl;
Now the text output of the DPL digitizer workflow is
substantially smaller.
> Do not use FairLogger::endl

- Generators/CMakeLists.txt
- Generators/include/Generators/InteractionDiamondParam.h
- Generators/include/Generators/PrimaryGenerator.h
- Generators/src/GeneratorsLinkDef.h
- Generators/src/InteractionDiamondParam.cxx
- Generators/src/PrimaryGenerator.cxx
- cmake/O2Dependencies.cmake
- macro/o2sim.C
This PR implements a configurable setup for the simulation of the vertex spread in simulation.
A configurable `InteractionDiamondParam` is queried while `Init` the `PrimaryGenerator`, which in turns sets itself up to generate events according to the requested configuration.
The user can configure the xyz values of the position (`position`) and gaussian width (`width`) of the interaction diamond  via `o2sim` command line arguments.
The default xyz values of the position (`position`) and width (`width`) of the interaction diamond are `position[3] = {0., 0., 0.}` and `width[3] = {0., 0., 0.}`. By default, vertices are always generated at `{0., 0., 0.}` with no spread.
For instance, to configure the z-width of the interaction diamond to be 6 cm, add
`--configKeyValue "Diamond.width[2]=6."`
to …
> CMD line configurable interaction diamond for vertex spread in simulation

- Common/SimConfig/src/ConfigurableParam.cxx
this PR provides two commits aimed at improving the safety of the use of the ConfigurableParam concept which started with PR #1285.
1. The first commit modifies the current behaviour from WARN to FATAL in case a configuration key is not found and/or is invalid. This will ensure that any attempt to modify not-existing parameters will lead to the crash of the execution.
2. The second commit allows the user to use a potentially more screen-friendly input string and use spaces as he/she wishes. It simply removes the spaces from the configuration string before parsing. Configuration strings such as
`--configKeyValue "HallSim.mCUTGAM = 2, HallSim.mCUTELE = 3"`
are therefore allowed, and will correspond exactly to
`--configKeyValue "HallSim.mCUTGAM=2,HallSim.mCUTELE=3"` in the previous …
> Safety improvements to the ConfigurableParam concepts

- Common/SimConfig/doc/ConfigurableParam.md
- Common/SimConfig/include/SimConfig/ConfigurableParam.h
- Common/SimConfig/include/SimConfig/ConfigurableParamHelper.h
- Common/SimConfig/src/ConfigurableParam.cxx
- Common/SimConfig/src/ConfigurableParamHelper.cxx
This commit enables support for std::string members in parameter classes:
```
struct Param : ConfigurableParamHelper<Param> {
std::string name = "defaultString";
};
```
will now work and be modifyable through the offered APIs.
std::string is the only way to represent strings. char* will not work.
> ConfigurableParam: Support for std::string parameter values

- DataFormats/Headers/include/Headers/DataHeader.h
- DataFormats/Headers/test/testDataHeader.cxx
- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/InputSpec.h
- Framework/Core/include/Framework/OutputSpec.h
- Framework/Core/src/WorkflowHelpers.cxx
- Framework/Core/src/WorkflowHelpers.h
- Framework/Core/test/test_DanglingOutputs.cxx
- Framework/Core/test/test_WorkflowHelpers.cxx
Sometimes it's handy to leave dangling outputs visible to a data
processor, so that one can reuse a given algorithm in different
scenarious where they might or not be requested.
This changes the previous behavior that was to wipe the output
completely, so that invoking make() on it would have thrown an
exception.
The new behavior will allow the user to invoke make and pass the output
to an internal device that acts as a sink.
Future updates of this feature will allow the user to query if
a given output is dangling or not and provide a callback based API for
make which will invoke the callback only if the output is not dangling.
We could also exploit this feature to have preconfigured actions (e.g. write
to a ROOT file) for dangling outputs, so that the user does not need to
instanciate a …
> DPL: add support for dangling outputs

- Framework/Core/include/Framework/ChannelConfigurationPolicy.h
- Framework/Core/include/Framework/ConfigParamSpec.h
- Framework/Core/include/Framework/DataAllocator.h
- Framework/Core/include/Framework/DataProcessingDevice.h
- Framework/Core/include/Framework/DataRefUtils.h
- Framework/Core/include/Framework/DataSamplingConfig.h
- Framework/Core/include/Framework/InputSpec.h
- Framework/Core/include/Framework/LifetimeHelpers.h
- Framework/Core/include/Framework/MessageContext.h
- Framework/Core/include/Framework/runDataProcessing.h
- Framework/Core/src/runDataProcessing.cxx
This refactors a few include statements orders to improve chances
our headers are fully self contained.
> DPL: refactor include statements to ensure atomicity

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/DataDescriptorMatcher.h
- Framework/Core/test/test_DataDescriptorMatcher.cxx
This introduces a facility to do complex queries with a given
DataHeader, e.g. leave one of the fields undetermined or pick only
certain combinations. At the moment this is just a helper class,
but it is one of the requirements to have more flexibility in the
`InputSpec` definition and possibly in other ancillary tasks.
The query itself is expressed in terms of a query tree, see the
example test_DataDescriptorMatcher.cxx for more details.
> DPL: add initial facility for complex queries on DataHeader

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/DataDescriptorMatcher.h
- Framework/Core/include/Framework/DataDescriptorQueryBuilder.h
- Framework/Core/src/DataDescriptorQueryBuilder.cxx
- Framework/Core/test/test_DataDescriptorMatcher.cxx
This can be used to e.g. allow the user to select which outputs to save
from command line, or to write a InputSpec in a generic manner, without
having to rely on the O2 Data Model descriptors.
For the moment the syntax is very basic:
<origin>/<description>/<subSpec>,<...>
but we can complicate it as needed in later PRs.
> DPL: add query builder for DataDescriptors from a config string

- DataFormats/common/CMakeLists.txt
- DataFormats/common/include/CommonDataFormat/RangeReference.h
- DataFormats/common/src/CommonDataFormatLinkDef.h
- Detectors/TPC/simulation/include/TPCSimulation/DigitizerTask.h
- Detectors/TPC/simulation/include/TPCSimulation/HitDriftFilter.h
- Detectors/TPC/simulation/src/Digitizer.cxx
- Steer/DigitizerWorkflow/src/ITSMFTDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/TPCDigitRootWriterSpec.cxx
- Steer/DigitizerWorkflow/src/TPCDriftTimeDigitizerSpec.cxx
- cmake/O2Dependencies.cmake
When called with ```--TPCtriggered``` option the digitizer-workflow will go to event based processing mode: the interaction time from the sampler will not be added to the time-bin of the digits.
Still, digits from different events are stored in a single entry of the output tree (need to change this).
This is still not a triggered readout since events which are separated by less than 1 drift time will still be processed separately. Eventually, a proper trigger logics should be introduced. @davidrohr , this should be enough to avoid gap between A and C side clusters, I've checked, the reconstruction works even though the digits from different events are piled up in a single entry. Btw, when reconstructing w/o ```cont``` option, I get some clusters on the wrong side:
```
7649]: …
```
> Restore TPC quasi-triggered readout mode for digitization-workflow

- Detectors/TPC/reconstruction/include/TPCReconstruction/ClustererTask.h
- Detectors/TPC/reconstruction/include/TPCReconstruction/HwClusterer.h
- Detectors/TPC/reconstruction/src/ClustererTask.cxx
- Detectors/TPC/reconstruction/src/HwClusterer.cxx
- Detectors/TPC/reconstruction/test/testTPCHwClusterer.cxx
- Detectors/TPC/workflow/src/ClustererSpec.cxx
- added the option to reject clusters:
- single pad clusters
- single time clusters
- peak in the same pad but later timebin
- added first "charge sharing" option, clusters are split at the minimum, the minimum itself contributes half to all clusters.
- added option to **NOT** clear output containers by calling process/finishProcess functions (@matthiasrichter maybe this helps with the reco-workflow, could you please test it)
> add TPC cluster reject options

- Framework/Core/include/Framework/ForwardRoute.h
- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/src/DeviceSpecHelpers.cxx
The inputs forwarding did not work quite well when the next consumer had time-pipelining enabled - the first one of n consumers was receiving all the messages and the forwarding device was showing "Missing header" errors. It seems like forwarding logic lacked the mechanism like in `DataAllocator` [here](https://github.com/AliceO2Group/AliceO2/blob/cf89d9a7a8fbf5dd0ea4be5e7a5bd99786ed5357/Framework/Core/src/DataAllocator.cxx#L46).
I suppose this is unintentional behaviour, so the commit tries to fix that.
> DPL: Fix forwarding inputs to consumers which are time-pipelined

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/CommonDataProcessors.h
- Framework/Core/include/Framework/DataDescriptorMatcher.h
- Framework/Core/src/CommonDataProcessors.cxx
- Framework/Core/src/WorkflowHelpers.cxx
- Framework/Core/src/runDataProcessing.cxx
- Framework/Core/test/test_DataDescriptorMatcher.cxx
This shows how it's possible to have automatic persistency of messages (to file in this particular case) in DPL. While the logic is quite trivial at the moment (drop everything by default, unless specified with the `--keep` option) it can be easily extended. In particular I was thinking about:
* Pushing (selected) dangling `Lifetime::QA` histograms to a ROOT file or CCDB.
* Pushing (selected)  dangling `Lifetime::Condition` objects to CCDB.
* Pushing (selected) dangling Arrow tables to root or Parquet.
* Pushing (selected) dangling `Lifetime::Timeframe` messages to a binary dump (e.g. to debug).
* Allow selecting any intermediate message (dangling or not) and push it to file.
The syntax could be extended to specify the actual output or to support wildcards, e.g.:
```
--keep …
```
> DPL: Add ability to persist selected messages

- Framework/Core/include/Framework/DataDescriptorMatcher.h
- Framework/Core/include/Framework/DataDescriptorQueryBuilder.h
- Framework/Core/src/CommonDataProcessors.cxx
- Framework/Core/src/DataDescriptorQueryBuilder.cxx
- Framework/Core/test/test_DataDescriptorMatcher.cxx
This introduces the ability to build matchers that refer to some
variable in a context. The context itself can either be prefilled,
or filled on the fly on first match.
> DPL: add variables to DataDescriptorMatcher

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/DataDescriptorMatcher.h
- Framework/Core/test/benchmark_DataDescriptorMatcher.cxx
- cmake/O2Dependencies.cmake
Previous results:
```
BM_MatchedSingleQuery              99 ns         99 ns    6865572
BM_MatchedFullQuery               321 ns        320 ns    2206163
BM_UnmatchedSingleQuery           308 ns        308 ns    2270457
BM_UnmatchedFullQuery             313 ns        312 ns    2218307
BM_OneVariableFullMatch           449 ns        448 ns    1552719
BM_OneVariableMatchUnmatch        769 ns        768 ns     889476
```
New results:
```
BM_MatchedSingleQuery              60 ns         60 ns   11614595
BM_MatchedFullQuery               314 ns        314 ns    2242016
BM_UnmatchedSingleQuery            56 ns         56 ns   12320256
BM_UnmatchedFullQuery             272 ns        272 ns    2609243
BM_OneVariableFullMatch           392 ns        392 ns    1783676
BM_OneVariableMatchUnmatch …
```
> DPL: speedup DataDescriptorMatcher

- Framework/Core/include/Framework/InputSpec.h
- Framework/Core/include/Framework/LifetimeHelpers.h
- Framework/Core/src/DataSampling.cxx
- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/Core/src/LifetimeHelpers.cxx
- Framework/Core/test/test_DataRelayer.cxx
- Framework/Core/test/test_InputRecord.cxx
- Framework/Core/test/test_WorkflowHelpers.cxx
As we move closer to have InputSpec as a veritable "matcher" object
rather than a set of variables to be equal compared, I need to tight
the access to the member variables. The first adiabatic step in such a
direction is to make sure an InputSpec is built all at once, and not
incrementally, as that ability will be lost once we move to use
a DataDescriptorMatcher to describe the InputSpec internal State.
> DPL: prevent InputSpec default constructor

- Framework/Core/include/Framework/DataDescriptorMatcher.h
- Framework/Core/include/Framework/DataRelayer.h
- Framework/Core/src/DataRelayer.cxx
- Framework/Core/test/test_DataDescriptorMatcher.cxx
This includes the change mentioned in the title plus related refactoring of the `DataDescriptorMatcher` in order to achieve it. Please do not squash as I would like to keep the refactorings separate.
This is all going towards sub-timeframe inputs and wildcards in InputSpec.
> DPL: move DataRelayer to use a DataDescriptorMatcher for incoming data

- DataFormats/Reconstruction/include/ReconstructionDataFormats/TrackTPCITS.h
- DataFormats/Reconstruction/src/TrackTPCITS.cxx
- Detectors/GlobalTracking/include/GlobalTracking/MatchTPCITS.h
- Detectors/GlobalTracking/src/MatchTPCITS.cxx
In principle, this information is redundant, but fetching it from original ITS and TPC tracks trees might take more resources.
> Store ITS/TPC labels and outerParam for matched tracks

- Detectors/MUON/MID/Base/CMakeLists.txt
The testGeometryTransformer for MID takes very long to complete.
This is probably due to its "sampling" nature.
Disabling it momentarily to speed up CI. Please revise the test before re-enabling.
> Temporarily disable test_MID_GeometryTransformer

- Detectors/MUON/MID/Base/CMakeLists.txt
- Detectors/MUON/MID/Base/test/testGeometryTransformer.cxx
With this PR one cans safely re-enable the tests that where removed with https://github.com/AliceO2Group/AliceO2/pull/1450
> Reduce number of generated tests for MID geometry transformer

- Common/SimConfig/include/SimConfig/SimConfig.h
- Common/SimConfig/src/SimConfig.cxx
- run/O2PrimaryServerDevice.h
Allow to set the seed for simulation. By default
a random seed will be chosen at each start. If reproducible tests
are needed ... set the seed with the --seed option.
For the moment, change restricted to o2sim_parallel.
> Possibility to set seed for simulation

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/DeviceInfo.h
- Framework/Core/include/Framework/Metric2DViewIndex.h
- Framework/Core/src/Metric2DViewIndex.cxx
- Framework/Core/src/runDataProcessing.cxx
- Framework/Core/test/test_GUITests.cxx
This makes the old DataRelayerViewIndex a generic component for metrics
which should really grouped in a 2D display. To be used by the soon to
be introduced DataDescriptorMatcher debug view.
> DPL GUI: refactor 2D Metrics index

- Framework/Core/src/DataSampling.cxx
Just a misplaced 'break' which caused jumping out of the loop too soon.
> Fix InputSpecs generation in Data Sampling

- CMakeLists.txt
This is supposed to be a temporary measure. See #1464 and #1458.
> Do not test macros including problematic headers

- DataFormats/MemoryResources/include/MemoryResources/MemoryResources.h
- DataFormats/TimeFrame/test/TimeFrameTest.cxx
- Framework/Core/include/Framework/Dispatcher.h
- Framework/Core/include/Framework/FairMQDeviceProxy.h
- Framework/Core/src/Dispatcher.cxx
- Framework/Core/src/FairMQDeviceProxy.cxx
- run/O2SimDeviceRunner.cxx
This is the bare minimum to make it chooch. There will be another PR that will integrate the new memory_resource stuff that got merged in FairMQ (thus removing most of the current O2 implementation).
> Compile against FairMQ 1.3.6

- Common/Utils/include/CommonUtils/BoostSerializer.h
- Common/Utils/test/testBoostSerializer.cxx
- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/ContextRegistry.h
- Framework/Core/include/Framework/DataAllocator.h
- Framework/Core/include/Framework/DataProcessingDevice.h
- Framework/Core/include/Framework/DataProcessor.h
- Framework/Core/include/Framework/DataSourceDevice.h
- Framework/Core/include/Framework/InputRecord.h
- Framework/Core/include/Framework/RawBufferContext.h
- Framework/Core/include/Framework/SerializationMethods.h
- Framework/Core/include/Framework/TypeTraits.h
- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/src/DataProcessor.cxx
- Framework/Core/src/DataSourceDevice.cxx
- Framework/Core/test/test_BoostSerializedProcessing.cxx
This PR contains all the needed changes to introduce RawBufferContext to DPL.
Even if for the moment the related get/adopt API calls are directly linked to boost serialisation methods, the context could easily serve generic binary buffers.
An helper, BoostSerialised, helps to force the call to the boost serialisation methods.
This can be used to highlight that a certain serialisation is enforced to be done using boost.
> Introducing RawBufferContext to DPL

- macro/o2sim.C
Little fix for parallel simulation, where each worker
creates a geometry file + a PID identifier in order to avoid that they all
write to the same file.
We now make sure that the standard file (or a link) O2geometry.root
is created or symlinked, since this is expected by the processing chain further up.
With this, we can now run o2sim_parallel + digitizer-workflow.
Thanks to @davidrohr.
> Make sure geometry file is available in standard way

- Utilities/QC/QCMerger/src/MergerDevice.cxx
FairMQ is going to deprecate the asyncronous version of Send and Receive,
following the suggestion in the warning, Send is used now.
"For non-blocking Send, use timeout version with timeout of 0"
> Using FairMQChannel::Send instead of SendAsync which is deprecated

- Framework/Core/src/SimpleResourceManager.h
Signed short causes the number to become negative for specified initial
port values > 32767, while range up to 65535 is allowed
> Bugfix: need to use unsigned short to represent port range up to 65535

- Framework/Core/CMakeLists.txt
- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/Core/test/test_DeviceSpecHelpers.cxx
Workflow options have to be handled independently from option groups to make sure that
all arguments are forwarded. In case of using an option group for a processor, the
filtering function is called with only a subset from the command line arguments, and
aplying this to the workflow options resulted in forwarding of the default arguments
instead of the arguments from the command line.
> Correcting filtering of options and handling of option groups

- Detectors/HMPID/base/CMakeLists.txt
- Detectors/HMPID/base/include/HMPIDBase/Digit.h
- Detectors/HMPID/base/include/HMPIDBase/Hit.h
- Detectors/HMPID/base/include/HMPIDBase/Param.h
- Detectors/HMPID/base/src/Digit.cxx
- Detectors/HMPID/base/src/HMPIDBaseLinkDef.h
- Detectors/HMPID/simulation/CMakeLists.txt
- Detectors/HMPID/simulation/include/HMPIDSimulation/Detector.h
- Detectors/HMPID/simulation/include/HMPIDSimulation/HMPIDDigitizer.h
- Detectors/HMPID/simulation/src/HMPIDDigitizer.cxx
- Steer/DigitizerWorkflow/CMakeLists.txt
- Steer/DigitizerWorkflow/src/HMPIDDigitWriterSpec.cxx
- Steer/DigitizerWorkflow/src/HMPIDDigitWriterSpec.h
- Steer/DigitizerWorkflow/src/HMPIDDigitizerSpec.cxx
- Steer/DigitizerWorkflow/src/HMPIDDigitizerSpec.h
- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
- cmake/O2Dependencies.cmake
This commit provides a basic DPL digitizer workflow
for HMPID.
It achieves:
- rudimentary digits and first conversion from hits
- a Digitizer class
- DPL components for digitization
With this, everything is there to have the workflow running.
The following steps need to be done next:
- correct hit -> digits conversion
- consider cross talk (hit influencing multiple pads)
- implement digit pileup + zero suppression
- finish IO of digits
- add treatment of MC labels
This commit relates to https://alice.its.cern.ch/jira/browse/O2-384
Authors: @gvolpe79, @sawenzel
> Basic HMPID digitizer workflow

- Framework/Core/src/runDataProcessing.cxx
Integrating with Monitoring changed the order of the matches.
> DPL: fix wrong log message when parsing metrics

- Utilities/aliceHLTwrapper/include/aliceHLTwrapper/EventSampler.h
- Utilities/aliceHLTwrapper/src/EventSampler.cxx
The FairMQ PAUSED state offers little/no advantage over going from RUN to READY (and back to RUN to unpause). Thus it will be removed and its handler (`FairMQDevice::Pause`) deprecated.
This commit removes the overridden but unused Pause handler from the EventSampler device.
> Remove Pause state handler

- Framework/Core/include/Framework/DataDescriptorMatcher.h
- Framework/Core/include/Framework/DataRelayer.h
- Framework/Core/src/CommonDataProcessors.cxx
- Framework/Core/src/DataRelayer.cxx
- Framework/Core/test/benchmark_DataDescriptorMatcher.cxx
- Framework/Core/test/test_DataDescriptorMatcher.cxx
This refactors the logic in `DataRelayer` to use a `DataDescriptorMatcher` query to extract the timeslice information, rather than an hardcoded lookup in `DataProcessingHeader->startTime`.
While the actual query mechanism is still hardcoded, this will be soon extended to be able to do the following:
* Allow generic queries to match the inputs, including wildcard matching.
* Allow a definition of time which is different between various inputs, e.g. allowing merging multiple timeslices together.
> DataDescriptorMatcher based time slice extraction

- Detectors/TPC/workflow/src/ClusterConverterSpec.cxx
- Detectors/TPC/workflow/src/ClusterDecoderRawSpec.cxx
- Detectors/TPC/workflow/src/ClustererSpec.cxx
Have to clear the output containers inside the process method as not only the
containers are cleared but also the cluster counter. Clearing the containers
externally leaves the cluster counter unchanged and leads to an inconsistency
between cluster container and MC label container (the latter just grows with
every call). This is probably a bug of the TPC HwClusterer.
Also implementing:
- some minor changes on the logging output.
- boundary check for MC label object processing in the decoder
> Bugfix tpc reco workflow: clear the output containers for the TPC HwClusterer consistently

- Steer/DigitizerWorkflow/src/EMCALDigitizerSpec.cxx
The digitizer workflow was using by mistake the run1
geometry with 10 supermodules (without DCAL) while
the simulation was using the run2/3 geometry. For
the moment it is hard coded - to be changed when
it is clear how to dynamically handle this according
to the run numbers.
> [O2-379] Using run2/3 geometry in digitizer workflow

- Detectors/TPC/reconstruction/src/TPCCATracking.cxx
- Detectors/TPC/reconstruction/test/testTPCCATracking.cxx
- Ad-hoc correction for time-bin offset.
Will be corrected eventually by proper transformation class.
- Due to smearing, clusters may cross the central electrode a bit.
- Fix missing definitions.
> Minor temporary fixes to TPC tracking

- Detectors/EMCAL/base/src/EMCALBaseLinkDef.h
This is needed in order to read the containers from the
simtree (i.e. in macros)
> Adding vectors with EMCAL Hit/Digit to the linkdef

- cmake/O2Dependencies.cmake
https://github.com/AliceO2Group/AliceO2/pull/1485 deletes FindCommon module therefore `AliceO2::Common` target should be used.
> Use Common target

- README.md
Our DOI is: https://doi.org/10.5281/zenodo.1493334 and will always point to the
latest version.
> Add Zenodo badge: make AliceO2 citable

- DataFormats/Detectors/Common/include/DetectorsCommonDataFormats/DetMatrixCache.h
- DataFormats/Detectors/Common/src/DetMatrixCache.cxx
- DataFormats/Detectors/Common/src/DetectorsCommonDataFormatsLinkDef.h
- Detectors/TRD/base/CMakeLists.txt
- Detectors/TRD/base/include/TRDBase/TRDCommonParam.h
- Detectors/TRD/base/include/TRDBase/TRDGeometry.h
- Detectors/TRD/base/include/TRDBase/TRDGeometryBase.h
- Detectors/TRD/base/include/TRDBase/TRDPadPlane.h
- Detectors/TRD/base/src/TRDBaseLinkDef.h
- Detectors/TRD/base/src/TRDCommonParam.cxx
- Detectors/TRD/base/src/TRDGeometry.cxx
- Detectors/TRD/base/src/TRDGeometryBase.cxx
- Detectors/TRD/base/src/TRDPadPlane.cxx
- Detectors/TRD/simulation/include/TRDSimulation/Detector.h
- Detectors/TRD/simulation/src/Detector.cxx
- cmake/O2Dependencies.cmake
This PR collects several changes needed for the TRD Geometry.
The purpose is to get the full Geometry with Transformation Matrices working and create a version of it that is runable on GPUs.
This PR contains:
- Splits TRD geometry in two parts, a base version that shall run on GPU eventually, and a full version for the host with all the CreateGeometry and related functions.
- Merge recent changes by Ruben to fix creation of Geometry Matrices.
- Adopt DetMatrixCache for TRDGeometry
- Make all constants constexpr
- The class was a semi-singleton with many statics, all statics removed.
The next PR, which requires alisw/alidist#1405, will bring on top:
- Create TRDGeometryGPU version of the class, that derrives from TRDGeometry and FlatObject.
- GPU Version of simplified DetMatrixCache
> Update of TRD Geometry

- Framework/Core/include/Framework/WorkflowSpec.h
- Framework/Core/src/WorkflowSpec.cxx
This simplifies the definition of data flow parallelism
- `parallel`-helper: adding variant for a sequence of processors all amended in the
same way
- `mergeInputs`-helper: adding variant working on a list of inputs
> DPL extension: adding helpers to duplicate sequence of processors and list of inputs

- Detectors/ITSMFT/ITS/tracking/include/ITStracking/Configuration.h
This is a minor bugfix that allows (not-so-)old nvcc to compile the ITS CUDA tracker.
Anyway the header was not used and should have been removed in the past...
> Remove unused header that nvcc does not like

- Common/SimConfig/include/SimConfig/SimConfig.h
- Common/SimConfig/src/SimConfig.cxx
- Common/Utils/src/ShmManager.cxx
- run/CMakeLists.txt
- run/O2SimDeviceRunner.cxx
- run/o2sim_parallel.cxx
This commit makes the parallel version of the simulation
the default one. I believe it is stable enough to give this a try.
With this the user will automatically use
all its cores to do simulation without any chance in the
command line interface.
Please report any problem found.
The former default will be available as o2sim_serial.
> Make parallel sim version the default

- Framework/Utils/include/Utils/MakeRootTreeWriterSpec.h
- Framework/Utils/include/Utils/RootTreeWriter.h
- Framework/Utils/test/test_RootTreeWriter.cxx
Adding optional branch clones with respect to two dimensions:
1) the input key is now a list of inputs and one branch spec execution
will loop over the complete list
2) multiple branch clones can be selected based on the header message
To activate branch clones, the branch definition needs to be configured with:
- cloning multiplicity
- a getter callback to return the branch index based on the DataRef
- a getter callback to create a branch name from base name and index
The branch name is used as a base name.
> Supporting multiple branch clones in one branch definition

- run/CMakeLists.txt
- run/o2sim_parallel.cxx
- force serial execution of simtests (since they now use
parallelism internally)
- update environment for the tests (which was incomplete)
- warn if O2_ROOT not defined at runtime
> Fix ctest environment for o2sim tests

- Detectors/EMCAL/simulation/src/Digitizer.cxx
Do not determine tower ID again for digit from
eta/phi cuts since the method is imprecise and
at the sector boundaries digits are assigned
to incorrect towers or not matched to towers
at all (A. Knospe).
> Use tower ID from Hit

- Framework/Core/include/Framework/DataRefUtils.h
- Framework/Core/include/Framework/InputRecord.h
- Framework/Core/include/Framework/TypeTraits.h
- Framework/Core/test/test_DataAllocator.cxx
- Framework/Core/test/test_TypeTraits.cxx
Also fixing two glitches
- explicitely marking gsl::span of some type as non-messageable
need to investigate why is_messageable type trait is true
- removing an assert for a condition which could not be relied on.
Not all ROOT serializable objects have a deleter interface function, e.g.
container of classes not inheriting from TObject. Thi relates to the
case where a deserialized ROOT object does not comply with the requested
object type.
> DPL IO API: adding method to query input as gsl::span

- Detectors/TRD/simulation/src/Digitizer.cxx
- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
- Steer/DigitizerWorkflow/src/TRDDigitWriterSpec.h
Making use of generic MakeRootTreeWriterSpec.
This completes the mockup processing chain
for TRD digits.
> DPL: Adding TRD digit writer

- Framework/Utils/include/Utils/MakeRootTreeWriterSpec.h
- Framework/Utils/include/Utils/RootTreeReader.h
- Framework/Utils/include/Utils/RootTreeWriter.h
- Framework/Utils/test/test_RootTreeWriter.cxx
Correctly using address of struct object for simple objects and address of pointer
to object for ROOT objects as branch address. This avoids also the copying of the
deserialized data for ROOT objects.
Supporting binary branches. By specifying const char* as store type, the data from
the input will be written to a binary branch, vector of char is used as format. An
additional branch with the size is added.
The RootTreeReader is updated accordingly to publish the binary chunk.
> Improving handling of objects and structs and supporting binary branches

- Framework/Core/include/Framework/DataProcessingHeader.h
- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/src/DataProcessingHeader.cxx
This adds an extra field to the DataProcessing header to account for the
message creation time, which is then used on the backend to compute the
minimum and maximum latencies for the parts composing the inputs to
start being processed. Since we also know how much data the input is
this gives us the rate at which data is being created, injested and
started to be consumed.
As a bonus, metrics are now documented in code for what they do.
> DPL: add metrics for inputs latencies

- Detectors/TPC/reconstruction/include/TPCReconstruction/TPCCATracking.h
- Detectors/TPC/reconstruction/src/TPCCATracking.cxx
- Detectors/TRD/base/src/TRDGeometryBase.cxx
- Beforehand, the ClusterNative clusters were converted to AliRoot format. This is no longer necessary. As of AliTPCCommon 2.2, the CA tracking can accept the ClusterNative directly.
- Conversion code is removed, output is exactly the same.
- +2 minor bug fixes for GPU version.
@matthiasrichter : Can you have a look, this does NOT imply changes to the reco workflow.
> Pass TPC native clusters to TPC CA tracking without conversion

- DataFormats/MemoryResources/include/MemoryResources/MemoryResources.h
- DataFormats/MemoryResources/test/testMemoryResources.cxx
makes it more standards compliant - standard does not allow ```vector<const ElemT>``` - gcc8 starts enforcing that. Also - returned vector inow actually
behaves like a vector with full functionality. Constness needs to be enforced by a framework or the user, depending on the use case.
> Fix adoptVector

- Framework/Core/include/Framework/AlgorithmSpec.h
- Framework/Core/test/test_AlgorithmSpec.cxx
- Framework/Core/test/test_CustomGUI.cxx
- Framework/Core/test/test_SimpleRDataFrameProcessing.cxx
- Framework/Core/test/test_SimpleStatefulProcessing01.cxx
- Framework/TestWorkflows/src/o2DiamondWorkflow.cxx
This introduces an helper which greatly reduces the typing
required to implement a stateless algorithm, i.e. one which
purely transforms the input into an output.
As you can read in the documentation with this the user simply needs
to pass a lambda where he specifies as inputs any of InputRecord,
DataAllocator, ConfigParamService, or any of the services hanging
from the ServiceRegistry, e.g. Monitoring. The actual extraction
of those classes happens via the template magic, leaving the user with
just:
```C++
AlgorithmSpec{
adaptStateless([](InputRecord &inputs, DataAllocator& output){
...
})}
```
In the future we might extend this to non stateless callbacks, capturing
lambdas and actually embed it directly into the AlgorithmSpec
constructor, without the need of an helper.
> DPL: reduce verbosity to use stateless Algorithms

- Common/SimConfig/src/SimConfig.cxx
Print better information instead of just "exception occured"
> o2sim: Improved feedback/handling when command line erroneous

- Framework/Core/include/Framework/FrameworkGUIState.h
- Framework/Core/src/DriverInfo.h
- Framework/Core/src/FrameworkGUIDebugger.cxx
- Framework/Core/src/runDataProcessing.cxx
Old code was recalculating the metrics to display for every iteration,
rather than doing it only when a new metric was added like now. While
this worked well for a few metrics, as we increase the number of them,
this becomes an obvious performance bottleneck.
While in production (i.e. when running on O2 Control / DDS) this part of
the code should not be exercised, several people use the DPL driver code
as convenience way to develop / debug issues and this was affecting
performance there in a significant way.
> DPL Driver: speedup metric handling

- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- Detectors/TPC/workflow/src/ClusterConverterSpec.cxx
- Detectors/TPC/workflow/src/ClusterDecoderRawSpec.cxx
- Detectors/TPC/workflow/src/ClustererSpec.cxx
- Detectors/TPC/workflow/src/PublisherSpec.cxx
- Detectors/TPC/workflow/src/RecoWorkflow.cxx
- Framework/Utils/include/Utils/MakeRootTreeWriterSpec.h
- Framework/Utils/test/test_RootTreeWriterWorkflow.cxx
Propagating the end-of-data condition through the workflow. All processes
signal 'ready-to-quit' individually. All writers use the RootTreeWriter
with a custom termination condition.
> Terminate the TPC workflow on end-of-data

- Detectors/MUON/MCH/Mapping/Impl3/src/CathodeSegmentationCImpl3.cxx
- Detectors/MUON/MCH/Mapping/Impl3/src/CathodeSegmentationImpl3.cxx
- Detectors/MUON/MCH/Mapping/Impl3/src/CathodeSegmentationImpl3.h
- Detectors/MUON/MCH/Mapping/Interface/include/MCHMappingInterface/CathodeSegmentation.h
- Detectors/MUON/MCH/Mapping/Interface/include/MCHMappingInterface/CathodeSegmentationCInterface.h
- Detectors/MUON/MCH/Mapping/Interface/include/MCHMappingInterface/Segmentation.h
- Detectors/MUON/MCH/Mapping/README.md
- Detectors/MUON/MCH/Mapping/SegContour/CMakeLists.txt
- Detectors/MUON/MCH/Mapping/SegContour/src/CathodeSegmentationContours.cxx
- Detectors/MUON/MCH/Mapping/SegContour/src/CathodeSegmentationSVGWriter.cxx
- Detectors/MUON/MCH/Mapping/SegContour/src/SVGSegmentation.cxx
- Detectors/MUON/MCH/Mapping/SegContour/src/SegmentationContours.cxx
- Detectors/MUON/MCH/Mapping/SegContour/src/SegmentationSVGWriter.cxx
- Detectors/MUON/MCH/Mapping/test/CMakeLists.txt
- Detectors/MUON/MCH/Mapping/test/src/BenchCathodeSegmentation.cxx
- Detectors/MUON/MCH/Mapping/test/src/BenchSegmentation.cxx
- Detectors/MUON/MCH/Mapping/test/src/CathodeSegmentation.cxx
- Detectors/MUON/MCH/Mapping/test/src/CathodeSegmentationLong.cxx
- Detectors/MUON/MCH/Mapping/test/src/Segmentation.cxx
Some more renaming, but more important is the new « most probable entry point » for the mapping : the Segmentation class which encompasses two cathodes of one detection element, and its numerous associated tests.
One other important change is to acknowledge the fact that padcid / paduid (names from the Go implementation, btw) are in fact not UIDs but really indices : first one local to a cathode, second one local the detection element. As such, we : 
- renamed them to catPadIndex and dePadIndex respectively
- added some tests to check that they are actually indices ranging from 0 to nofPads-1
(The Go impl will have to follow this new naming eventually).
> Introduce Segmentation class spanning the two cathodes.

- DataFormats/Detectors/TPC/include/DataFormatsTPC/ClusterHardware.h
(Distance in HWCF can be more than 0.5 bins used in software tests)
@KlewinS : This should do it, I hope I did not miss something, let's see what the ctest says.
@matthiasrichter : I am currently in vacation and don't have current O2 compiled here, so I cannot test it.
> PadPre / TimePre need 20 bit to encode sign and full distance 

- Detectors/ITSMFT/common/base/include/ITSMFTBase/SegmentationAlpide.h
The row0/col0 are in the top/left corner when sensor is oriented in such a way that the readout (wide dead zone) part is on the bottom. Before the bottom/left corner was assumed.
> fix Alpide local x,z->row/col mapping

- Framework/Core/include/Framework/DataDescriptorMatcher.h
- Framework/Core/include/Framework/DataDescriptorMatcher.inl
- Framework/Core/src/DataDescriptorMatcher.cxx
This reworks the code of DataDescriptorMatcher so that:
* DataDescriptorMatcher.h only contains the class declarations and
documentation.
* DataDescriptorMatcher.inl contains the inline implementation
* All the code which will never be inlined in any case gets moved to
src/DataDescriptorMatcher.cxx.
This should speed up compilation, result in a more understandable .h
file and workaround cling issue https://sft.its.cern.ch/jira/browse/ROOT-9894,
by not including .inl when being parsed by ROOT / cling.
> DPL: refactor DataDescriptorMatcher to reduce exposed code

- DataFormats/Headers/include/Headers/RAWDataHeader.h
- DataFormats/Headers/test/test_RAWDataHeader.cxx
@matthiasrichter could you please review? BTW, what is the reason you define all the fields of the structs as int64_t, even if much shorter types could be used?
> fix RDH3 header-size field + word1 content

- run/O2HitMerger.h
- run/o2sim_parallel.cxx
There was a problem when the user asked for 0 events
to be simulated, since in this case the data merger device never
received any data and would hang.
This problem is now fixed by letting the merger know how many
events to expect (from analysing the configuration). This probably makes sense
but leads to a tighter coupling. To be reviewed.
Note that the 0 event case is useful since we want to expect
the geometry created during initialization etc.
> o2sim: stability fix for 0 events

- DataFormats/simulation/include/SimulationDataFormat/PrimaryChunk.h
- Steer/src/O2MCApplication.cxx
- run/O2HitMerger.h
- run/O2PrimaryServerDevice.h
- run/O2SimDevice.h
The MCEventHeader produced by the event generator is now
propagated to the merger device and put into the output.
Some cleanup operations; code reduction
Relates to https://alice.its.cern.ch/jira/browse/O2-482
> o2sim: propagate MCEventHeader to merger device and output

- Framework/Core/include/Framework/AODReaderHelpers.h
- Framework/Core/include/Framework/ServiceRegistry.h
- Framework/Core/src/AODReaderHelpers.cxx
- Framework/Core/src/WorkflowHelpers.cxx
- Framework/Core/src/runDataProcessing.cxx
- Framework/Core/test/test_Services.cxx
- Framework/TestWorkflows/src/o2AODDummy.cxx
This set of commits is needed so that users who want to write an analysis task do not need to provide a source DataProcessor which reads them from file.
In case the user has dangling inputs of kind "AOD" we create a source for her / him. Notice that it is still possible to write a custom reader for some of the inputs which will have precedence over the default one.
> Improve AOD example

- Detectors/ITSMFT/common/base/include/ITSMFTBase/SegmentationAlpide.h
- Detectors/ITSMFT/common/reconstruction/src/Clusterer.cxx
Once the Alpide segmentation / matrix orientation were fixed, the shortcut for row/col -> local coordinates
conversion became inconsistent. Add proper shortcut to SegmentationAlpide and use it in the clusterization
> Fix: row/col->local custom shortcut was wrong

- Detectors/ITSMFT/ITS/reconstruction/src/CookedTracker.cxx
- Steer/DigitizerWorkflow/src/ITSMFTDigitizerSpec.cxx
Once the Alpide segmentation / matrix orientation were fixed, the shortcut for row/col -> local coordinates
conversion became inconsistent. Add proper shortcut to SegmentationAlpide and use it in the clusterization
> Add ITS/MFT Digitizer option for Alpide noise setting

- Detectors/TRD/simulation/src/Detector.cxx
I am adding the detector number according with the TRD coordinate system to the TRD hit information. This number is required for the TRD digitizer.
> Added TRD detector number to hit information instead of MCid

- run/o2sim_parallel.cxx
When user asks for zero events (-n 0), there are problems
with unsynchronized shut-down of devices and failing communication.
In order not having to complicate the control, I am now simply using
the non-distributed version in this corner case.
> Simulation: yet more robust behaviour for zero events

- Common/Utils/src/RootChain.cxx
- Common/Utils/src/ShmManager.cxx
Use Logger.h from package FairRootGroup/FairLogger rather that
deprecated FairLogger.h from FairRoot.
> Clean-up dependencies

- DataFormats/MemoryResources/CMakeLists.txt
- DataFormats/MemoryResources/include/MemoryResources/observer_ptr.h
- DataFormats/MemoryResources/test/test_observer_ptr.cxx
was discussed few times, so here it is. I have not put it in the Framework directly since it should be available also to lower level stuff that is a DPL dependency. Could not find a clear candidate for a location, so for now I propose to have it in MemoryResources, since this is pulled in by everybody via e.g. Headers. I'm sure at some point a better spot will present itself.
> Add observer_ptr ( a la C++20 TSv2)

- DataFormats/simulation/CMakeLists.txt
- DataFormats/simulation/include/SimulationDataFormat/Stack.h
- DataFormats/simulation/include/SimulationDataFormat/StackParam.h
- DataFormats/simulation/src/SimulationDataLinkDef.h
- DataFormats/simulation/src/Stack.cxx
- DataFormats/simulation/src/StackParam.cxx
- Detectors/gconfig/commonConfig.C
- Detectors/gconfig/src/G3Config.cxx
- Detectors/gconfig/src/G4Config.cxx
- cmake/O2Dependencies.cmake
We can now switch off/on pruning of kinematics via a simple configuration change
o2sim --configKeyValues "Stack.pruneKine=0"
The default is to prune.
This commit serves as another example how to add components to the simulation
configuration.
> Introduce config parameters for sim stack; Option to prune kinematics

- Framework/Core/CMakeLists.txt
- Framework/Core/test/test_CustomGUIGL.cxx
- Framework/Core/test/test_CustomGUISokol.cxx
- Framework/Core/test/test_DebugGUIGL.cxx
- Framework/Core/test/test_DebugGUISokol.cxx
- Framework/DebugGUI/CMakeLists.txt
- Framework/DebugGUI/include/DebugGUI/GL3DUtils.h
- Framework/DebugGUI/include/DebugGUI/Sokol3DUtils.h
- Framework/DebugGUI/src/DebugGUI.cxx
- Framework/DebugGUI/src/Dummy3DUtils.cxx
- Framework/DebugGUI/src/GL3DUtils.cxx
- Framework/DebugGUI/src/HandMade3DImpl.cxx
- Framework/DebugGUI/src/HandMadeMath.h
- Framework/DebugGUI/src/Sokol3DUtils.cxx
- Framework/DebugGUI/src/sokol_gfx.h
In case anyone feels like doing an event display. There are two
solution proposed:
- A bare bone GL implementation which can be used to adapt existing
code.
- A Sokol3d (https://github.com/floooh/sokol) setup which can be used to
have quickly running a performant 3D rendering engine without spending
too much time optimizing the backend. This will also allow us to
abstract part of the engine and support other backends like Metal or
vulkan.
> DPL: show how to add a 3D display to the Custom GUI

- Steer/src/InteractionSampler.cxx
gRandom->Gaus(mTimeBCRMS) invoked in the wrong way (1 argument has to be the mean and not the RMS). RMS moved as second argument
> bug fix in interaction sampler for event time jitter

- Framework/Core/include/Framework/TableBuilder.h
Previously gotten implicitly via arrow, which did a cleanup in 0.12.0.
> DPL: fix missing header

- Framework/ArrowTests/CMakeLists.txt
- Framework/Core/CMakeLists.txt
- Framework/DebugGUI/CMakeLists.txt
- Framework/TestWorkflows/src/o2_sim_its_ALP3.cxx
- Framework/TestWorkflows/src/o2_sim_tpc.cxx
We need to find a way to have debug builds easily, but
we cannot afford to unoptimised builds anymore as we
get closer to production.
> DPL: Drop a bunch of -O0

- run/O2SimDeviceRunner.cxx
- run/o2sim_parallel.cxx
A step into a more dynamic port configuration in order
to make concurrent unit-testing more robust.
> Make o2sim more port-robust

- Framework/Core/include/Framework/FreePortFinder.h
- Framework/Core/src/FreePortFinder.cxx
- run/o2sim_parallel.cxx
Further factorize FreePortFinder
* add function allowing to check a particular port number
* refactor scan() function to use this function
* allow to enable/disable verbose output (sometimes
it is not wished to be informed about invalid port ranges)
* const correctness fixes
> Small usability improvements to FreePortFinder

- Framework/Core/include/Framework/TableBuilder.h
Old iterator based API seems to be missing from 0.12.0. This should
work with both 0.12.0 and 0.11.0.
> DPL: use ptr + size based API

- DataFormats/Headers/include/Headers/DataHeader.h
Missing definition causes link errors. Use the implicitly-defined one.
> Headers: Remove copy constructor declaration of DataIdentifier

- Detectors/TPC/base/include/TPCBase/CalDet.h
- Detectors/TPC/simulation/include/TPCSimulation/DigitGlobalPad.h
- Detectors/TPC/simulation/include/TPCSimulation/DigitTime.h
- Detectors/TPC/simulation/include/TPCSimulation/SAMPAProcessing.h
- Detectors/TPC/simulation/src/DigitContainer.cxx
- Detectors/TPC/simulation/src/DigitGlobalPad.cxx
- Detectors/TPC/simulation/src/DigitTime.cxx
This is a simplification in the calibration object access. It significantly reduces function calls to the mapper, assuming a specific topology of the calibration object.
For the future, the CalDet and CalArray objects should be optimized.
> Optimize CalDet access in digitisation

- Detectors/MUON/MCH/Mapping/Interface/include/MCHMappingInterface/Segmentation.h
- Detectors/MUON/MCH/Mapping/Interface/include/MCHMappingInterface/Segmentation.inl
- Detectors/MUON/MCH/Mapping/README.md
- Detectors/MUON/MCH/Mapping/SegContour/src/SegmentationContours.cxx
- Detectors/MUON/MCH/Mapping/test/src/Segmentation.cxx
- Detectors/MUON/MCH/Simulation/src/Digitizer.cxx
The bug (see corresponding new CheckPadOffsetsAfterCopy test) was causing
an incorrect value returned by Segmentation::isBendingPad(padid) method,
as long as the segmentation object has been _copied_ before (a freshly
constructed object was just fine).
The split should make the interface easier to look at, as the .h now contains
only the declarations. The implementation is fully in the .inl file.
Also fix the case of Segmentation Bending and NonBending methods (which should
start with lower case letters).
> Fix Segmentation copy bug and split file into .h and .inl.

- Detectors/ITSMFT/ITS/macros/test/CheckTracks.C
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CookedTracker.h
- Detectors/ITSMFT/ITS/reconstruction/src/CookedTracker.cxx
- Detectors/ITSMFT/ITS/workflow/src/CookedTrackerSpec.cxx
This PR contains a couple of fixes and optimizations that improve the performance of the Cooked Matrix tracker ( see https://indico.cern.ch/event/792935/ )
> Optimizations in the CM tracker

- DataFormats/simulation/include/SimulationDataFormat/MCCompLabel.h
- DataFormats/simulation/src/MCCompLabel.cxx
- DataFormats/simulation/test/testMCCompLabel.cxx
The internal encoded value can simply be used as a hash, implementing std::hash
specialization for MCCompLabels allows to use containers like unordered_map.
Some minor cleanup in addition, moving the `static_assert` checks directly to the header.
> Implementing std::hash specialization for MCCompLabel

- DataFormats/simulation/include/SimulationDataFormat/MCCompLabel.h
- DataFormats/simulation/src/MCCompLabel.cxx
- DataFormats/simulation/test/testMCCompLabel.cxx
This reverts commit b8470f8bde8d283fa0cec33da9aa24e91ed3e142.
It breaks compilation on MacOS which needs to fixed first.
> Revert "Implementing std::hash specialization for MCCompLabel"

- Detectors/TPC/base/include/TPCBase/ParameterGEM.h
- Detectors/TPC/base/src/ParameterGEM.cxx
- Detectors/TPC/base/test/testTPCParameters.cxx
- Detectors/TPC/simulation/include/TPCSimulation/GEMAmplification.h
- Detectors/TPC/simulation/include/TPCSimulation/SAMPAProcessing.h
- Detectors/TPC/simulation/src/Digitizer.cxx
- Detectors/TPC/simulation/src/GEMAmplification.cxx
- Detectors/TPC/simulation/test/testTPCGEMAmplification.cxx
o Use single polya distribution instead of full blast computation of four successive GEMs (collection efficiency, gain fluctuations (polya) and extraction efficiency)
o Small fix for compiler warning in SAMPAProcessing
> Implementation of an effective (and efficient) electron amplification in the GEM stack

- Detectors/gconfig/g4config.in
This commits updates the special G4 settings and aligns them with the current AliDPG implementation.
In particular, special settings for the precision of tracking in magnetic field are tuned.
> Adding extra lines for fixing tracking bias [ALIROOT-7121]

- Detectors/TRD/simulation/include/TRDSimulation/Digitizer.h
- Detectors/TRD/simulation/src/Digitizer.cxx
This is work in progress. Dummy implementation of TRD conversion of digits to signals and ADC counts (O2-455) and continuation of PR #1611. The purpose of this PR is to show the current status of the implementation while we prepare the classes to get access to the calibration parameters, as well as the container classes ArraySignal and ArrayADC. The digitization algorithm works, it only lacks of putting the output in the right containers.
> Dummy TRD conversion of digits to ADC (O2-455)

- cmake/O2Dependencies.cmake
This solves an issue in linking tpc_monitor
(on Ubuntu18.04). The problem was that the bucket system
accumulates duplicate libraries for the linker invocation coming
from an overlap of bucket and module dependencies.
The problem is fixed by reducing the bucket dependencies
(at the cost of having to declare more include paths for ROOT
dictionary creation)
We should ideally revise the bucket system and modernize it, but until then
this commit reduces the link time by about a minute.
Fixes https://alice.its.cern.ch/jira/browse/O2-491
> Speedup linking of tpc_monitor

- Framework/Core/src/WorkflowHelpers.cxx
This leaves the termination control to the processes of the defined workflow,
else, only forced termination will work.
> Marking the internal dpl processes with fake callback as ready-to-quit

- Framework/Core/CMakeLists.txt
- Framework/Core/test/test_Parallel.cxx
- Framework/Core/test/test_SimpleDataProcessingDevice01.cxx
* test_Parallel.cxx, test_SimpleDataProcessingDevice01.cxx do not use
sleep anymore.
* Also disable test_Task.cxx which seems to be affected as well.
> DPL: workaround FairMQ issue in a few tests

- Common/SimConfig/include/SimConfig/SimConfig.h
- Common/SimConfig/src/SimConfig.cxx
- DataFormats/simulation/CMakeLists.txt
- DataFormats/simulation/include/SimulationDataFormat/MCEventHeader.h
- DataFormats/simulation/include/SimulationDataFormat/PrimaryChunk.h
- DataFormats/simulation/src/MCEventHeader.cxx
- DataFormats/simulation/src/SimulationDataLinkDef.h
- Generators/include/Generators/PrimaryGenerator.h
- Generators/src/PrimaryGenerator.cxx
- Steer/src/O2MCApplication.cxx
- doc/DetectorSimulation.md
- macro/o2sim.C
- run/O2HitMerger.h
- run/O2PrimaryServerDevice.h
This commit implements a basic mechanism to allow embedding
of signal events on pre-generated background events.
The currently-supported background source is file based,
namely the user needs to specify the filename (o2sim.root)
that contains the background events. The primary generator
of the signal events will force the primary interaction
vertex to be the same as the one of the background event.
Background events are sampled one-by-one until all events
have been used. At that point the events start to be reused.
User can select the embedding mode via o2sim command-line:
o2sim --embedIntoFile o2sim.bkg.root
> Generator-level implementation of embedding into background

- Common/SimConfig/src/SimConfig.cxx
- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
- run/O2SimDeviceRunner.cxx
In case there is only one CPU core and no hyperthreading, the current
mechanism to set the number of workers returned zero.
This commit fixes this problem.
> O2Sim: Fix in determining the default number of workers

- Detectors/TPC/base/include/TPCBase/CalDet.h
`FairLogger.h` is actually in an external project, so it should always be included with `<>`, not "".
> Fix #include statement for FairLogger

- Detectors/Passive/src/Hall.cxx
Fixing a wrong logical condition. The HALL with ZDC had wrong dimensions.
> Fix error in dimensions of HALL (related to ZDC)

- DataFormats/simulation/src/Stack.cxx
Make use of (already existing) index lookup
for motherID fixing.
Much faster than linear search ...
> MCStack : speedup track selection

- Framework/Utils/CMakeLists.txt
This reverts commit 854daf2b7d690ceda239ecf3fa3ad6dfc50ae29c.
Should no longer be a problem with the new testing mechanism.
> Revert "Comment out failing test until problem resolved"

- Detectors/ITSMFT/ITS/macros/EVE/DisplayEvents.C
This is a continuation of the PR #1685.
The commits below bring the following additional functionality:
1) A dedicated  single-chip view that is zoom-able down to the pixel level.
2) Possibility to visualise clusters within the single-chip view.
3) Navigation over events and chips via the GUI.
> An update on the ITS event display

- Common/SimConfig/CMakeLists.txt
- Common/SimConfig/include/SimConfig/SimCutParams.h
- Common/SimConfig/src/SimCutParams.cxx
- Steer/include/Steer/O2MCApplicationBase.h
- Steer/src/O2MCApplication.cxx
- macro/compareHits.C
This commit is introducing the possibility to have tracking cuts
based on geometry and other stepping status.
Custom filtering is possible inside our overriden stepping function.
Introducing a macro to compare information on hits, potentially usefull
to judge if a tracking cut is not changing behaviour.
> O2sim: Custom stepping + configurable geometry tracking cuts

- Framework/Core/include/Framework/DataProcessingDevice.h
- Framework/Core/include/Framework/DataRelayer.h
- Framework/Core/include/Framework/TimesliceIndex.h
- Framework/Core/include/Framework/TimesliceIndex.inc
- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/src/DataRelayer.cxx
- Framework/Core/src/LifetimeHelpers.cxx
- Framework/Core/test/test_TimesliceIndex.cxx
This reports the following metrics via the monitoring interface:
* dpl/relayed_messages: messages which might end up for processing
* dpl/dropped_computations: timeslices dropped because one of the inputs
did not arrive in time.
* dpl/dropped_incoming_inputs: inputs dropped because they arrived
too late and their computation was dropped.
* dpl/malformed_messages: messages which were not suitable for DPL
processing.
> DPL: report data relaying process metrics (QC-139)

- Common/SimConfig/src/SimCutParams.cxx
- DataFormats/MemoryResources/src/MemoryResources.cxx
- Detectors/ITSMFT/ITS/tracking/cuda/src/dummy.cxx
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/json.h
- Detectors/TRD/base/include/TRDBase/TRDCalDet.h
- Detectors/TRD/base/include/TRDBase/TRDCalROC.h
- Detectors/gconfig/SetCuts.h
- Framework/Core/include/Framework/RCombinedDS.h
- Framework/Core/include/Framework/StringContext.h
- Framework/Core/src/DataSpecUtils.cxx
- Framework/Core/src/RCombinedDS.cxx
- Framework/Core/test/benchmark_DataDescriptorMatcher.cxx
- Framework/Core/test/benchmark_TableBuilder.cxx
- Framework/Core/test/test_DebugGUIGL.cxx
- Framework/Core/test/test_DebugGUISokol.cxx
- Generators/include/Generators/Generator.h
- Generators/include/Generators/GeneratorTGenerator.h
- Generators/include/Generators/PrimaryGenerator.h
- Generators/src/Generator.cxx
- Generators/src/GeneratorTGenerator.cxx
Also, `Detectors/gconfig/SetCuts.h` had DOS-style line endings. Had to convert the whole file to not no mix line ending styles.
> Fix missing or malformed copyright notices

- Framework/Core/src/WorkflowHelpers.cxx
Previously messages with AOD origin were only meant to be provided by
the internal AOD reader. With this, in case one of the data processor
claims it is able to produce some AOD (e.g.  quantities which are not
persisted), it can do so without the system being confused about it.
> DPL: allow on-the-fly creation of AOD by a DPL dataprocessor

- Framework/Core/src/ExternalFairMQDeviceProxy.cxx
This avoids that DPL tries to forward messages from the proxied
component to one of the fake inputs, e.g. the one used for
enumeration. A proper fix should come when the proxied components
will be implemented as fake inputs themselves.
> DPL: workaround issue introduced by the new fake channels [O2-511]

- DataFormats/Detectors/TPC/include/DataFormatsTPC/Cluster.h
- Detectors/TPC/base/include/TPCBase/CRU.h
- Detectors/TPC/base/include/TPCBase/Digit.h
- Detectors/TPC/base/include/TPCBase/DigitPos.h
- Detectors/TPC/base/include/TPCBase/FECInfo.h
- Detectors/TPC/base/include/TPCBase/PadPos.h
- Detectors/TPC/base/include/TPCBase/PadRegionInfo.h
- Detectors/TPC/base/include/TPCBase/PadSecPos.h
- Detectors/TPC/base/include/TPCBase/PartitionInfo.h
- Detectors/TPC/base/include/TPCBase/RandomRing.h
- Detectors/TPC/base/include/TPCBase/Sector.h
- Detectors/TPC/reconstruction/include/TPCReconstruction/ClustererTask.h
- Detectors/TPC/reconstruction/include/TPCReconstruction/TPCCATracking.h
- Detectors/TPC/reconstruction/src/ClustererTask.cxx
- Detectors/TPC/simulation/include/TPCSimulation/DigitContainer.h
- Detectors/TPC/simulation/include/TPCSimulation/DigitGlobalPad.h
- Detectors/TPC/simulation/include/TPCSimulation/DigitMCMetaData.h
- Detectors/TPC/simulation/include/TPCSimulation/Digitizer.h
- Detectors/TPC/simulation/src/Digitizer.cxx
A first step to get the O2 code checker CI functional again. No functional
changesto the TPC code.
Whitespace changes can be suppressed in the diff by using either option '-b' or '-w'.
> Applying clang modernize and formatting rules to TPC code

- Detectors/TPC/workflow/README.md
- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- Detectors/TPC/workflow/src/PublisherSpec.cxx
- Detectors/TPC/workflow/src/tpc-reco-workflow.cxx
- buffering of input data in the TPC CA tracker spec only done if the input data set is not complete within one processor call
- using DPL time slice concept correctly through an alternative lane configuration
- publisher spec can now be run in loop mode
> Update to TPC reco workflow, optimizing buffering of data and lane configuration

- Detectors/TPC/workflow/src/ClustererSpec.cxx
- Detectors/TPC/workflow/src/ClustererSpec.h
- Detectors/TPC/workflow/src/RecoWorkflow.cxx
- Detectors/TPC/workflow/src/tpc-reco-workflow.cxx
The TPC digitizer defines a third output channel, which was left dangling when connecting to the reco workflow. The automatically added file dump however does not signal ready-to-quit, leaving the workflow unterminated.
Need to clarify if the data sent over this channel is needed by the clusterer.
> Subscribing to the DIGTRIGGERS data channel published by TPC digitizer

- run/CMakeLists.txt
G4 tests had timeout problems. Try to increase it.
> Increase timeout for G4 tests

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/ReadoutAdapter.h
- Framework/Core/src/ReadoutAdapter.cxx
- Framework/TestWorkflows/README
- Framework/TestWorkflows/src/flpQualification.cxx
This introduces preliminary ability to connect to a Readout device. For
the moment no interpretation of the input is done and the timestamp for
the DataProcessingHeader is a simple enumeration of the messages.
> flpQualification: connect to readout

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/WorkflowSpec.h
- Framework/Core/src/WorkflowSpec.cxx
- Framework/Core/test/test_ParallelPipeline.cxx
This helper function creates a workflow with parallel pipelines, each serving multiples
of data channels of the same origin and description but different sub specification.
If total number of parallel channels is larger than the number of pipelines, the
channels are distributed among the pipelines.
> Adding helper function to create parallel pipelines from a pre-defined workflow

- Steer/DigitizerWorkflow/src/SimReaderSpec.cxx
- Steer/DigitizerWorkflow/src/SimReaderSpec.h
- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
- using [RangeTokenizer](https://github.com/AliceO2Group/AliceO2/blob/dev/Algorithm/include/Algorithm/RangeTokenizer.h) to extract list of TPC sectors, sequences of ranges
can now be specified, e.g. 0-3,5,16-20
- propagating the tpc sector configuration to the reco workflow, this allows
to run all the different output modes of the TPC reconstruction workflow:
raw, decoded-clusters, tracks
- minor cleanup of internal variable, no need to make it shared_ptr
> Updating the coupling of TPC reconstruction workflow to digitizer workflow

- Detectors/EMCAL/base/CMakeLists.txt
- Detectors/EMCAL/base/include/EMCALBase/Cell.h
- Detectors/EMCAL/base/include/EMCALBase/Constants.h
- Detectors/EMCAL/base/src/Cell.cxx
- Detectors/EMCAL/base/src/EMCALBaseLinkDef.h
Introduce EMCal Cell: a compact (40-bit) container for the amplitude, time, and tower ID
> Introduce EMCal Cell Class

- Framework/TestWorkflows/src/flpQualification.cxx
Unlike real life, where we struggle to keep up with the lack of
sleep and a good night is fundamental for our proper functioning,
invoking sleep on a computer process drastically reduces its
performance making it unresponsive to external inputs.
> flpQualification: do not sleep between one message and the other

- Common/SimConfig/src/ConfigurableParam.cxx
Users can now specify an array value for a  ConfigurableParam
via the configKeyValues option of the o2sim_serial executable.
i.e. o2sim_serial ...--configKeyValues="key1=[elem1, ..];key2=..."
Note that the previous key/value pair delimiter was the comma,
but as that is used in arrays, we now split on semi-colon.
> ConfigurableParam: add support for command-line arrays

- Generators/include/Generators/PrimaryGenerator.h
- Generators/src/GeneratorFactory.cxx
- Generators/src/PrimaryGenerator.cxx
This PR fixes the issue reported in JIRA [02-496].
A first commit adds a protection at the PrimaryGenerator level to avoid injecting in the stack particles which are unknown to the PDG table. They are discarded and a warning is issued.
A second commit fixes an unexpected behaviour in the particle decays with Pythia8 which caused excited hadronic states (like D* and B*) to be injected in the stack (unknown particles to G3/G4) instead of being decayed. For some reason, this behaviour appears to only happen when running the heavy-ion machinery. The commit changes the strategy and now the decays are configured based on the intrinsic lifetime of the particle (decay if cTau < 1 um).
A third commit adds another Pythia8 generator configuration to force the production of heavy flavours via the …
> FindParticle problem in Geant4/HMPID/Pythia8HI

- Framework/TestWorkflows/README
- Framework/TestWorkflows/src/flpQualification.cxx
This can be changed on the command line as documented.
> flpQualification: use shmem for readout transport

- Detectors/MUON/MID/Base/CMakeLists.txt
- Detectors/MUON/MID/Base/include/MIDBase/ChamberEfficiency.h
- Detectors/MUON/MID/Base/src/ChamberEfficiency.cxx
- Detectors/MUON/MID/CMakeLists.txt
- Detectors/MUON/MID/Simulation/CMakeLists.txt
- Detectors/MUON/MID/Simulation/include/MIDSimulation/ChamberEfficiencyResponse.h
- Detectors/MUON/MID/Simulation/include/MIDSimulation/ChamberHV.h
- Detectors/MUON/MID/Simulation/include/MIDSimulation/ChamberResponse.h
- Detectors/MUON/MID/Simulation/include/MIDSimulation/ChamberResponseParams.h
- Detectors/MUON/MID/Simulation/src/ChamberEfficiencyResponse.cxx
- Detectors/MUON/MID/Simulation/src/ChamberHV.cxx
- Detectors/MUON/MID/Simulation/src/ChamberResponse.cxx
- Detectors/MUON/MID/Simulation/src/ChamberResponseParams.cxx
This is the first of a series of commits to provide the digitization for MID
The commit consists of three parts:
- A class that stores the HV values (needed to determine the probability to fired a strip at a distance d from the impact point)
- The class that uses the HV values and other parameters to determine the probability to fire a strip at a distance d from the impact point)
- The chamber efficiency
The commits are related, but they are indeed atomic and valid on their own: please do not squash this PR
> Adding responses for MID simulations

- DataFormats/Detectors/MUON/MID/CMakeLists.txt
- DataFormats/Detectors/MUON/MID/include/DataFormatsMID/ColumnData.h
- DataFormats/Detectors/MUON/MID/src/ColumnData.cxx
- DataFormats/Detectors/MUON/MID/src/DataFormatsMIDLinkDef.h
- Detectors/MUON/MID/Clustering/test/testClusterizer.cxx
- Detectors/MUON/MID/Simulation/CMakeLists.txt
- Detectors/MUON/MID/Simulation/include/MIDSimulation/ColumnDataMC.h
- Detectors/MUON/MID/Simulation/src/MIDSimulationLinkDef.h
This is the second of a series of commit to introduces the MID digitization. In this commit I introduce the data format.
For MID, the MC digits and real digits coincide. They need to be streamed to a root file in the simulation, while we do not necessarily need to be dependent on ROOT during reconstruction.
Actually, we want the real digits format to be as simple as possible, independent of the serialization method.
In order to do so, the real digits (ColumnData) were simplified: they are now just a plain struct with some setters/getters. Any serialization-specific method was stripped off.
On the other hand, we introduced the MC digits (ColumnDataMC), which derive from both ColumnData and dataformats::TimeStamp. They implement a dictionary and a ClassDef, so that they can be streamed to …
> MC digits for MID

- Generators/share/external/extgen.C
- Generators/share/external/hijing.C
- Generators/share/external/pythia6.C
- Generators/share/external/tgenerator.C
- Generators/src/GeneratorFactory.cxx
Modifies the behaviour of o2sim with the external generator option -g extgen.
It now expects that the external configuration macro defined via --extGenFile returns a FairGenerator* instead of a TGenerator* as it was before.
This allows for a more generic handling of customised external generators.
The TGenerator interface functionality is preserved, as everything can be defined in the configuration macro. Please see for example
share/external/tgenerator.C
share/external/pythia6.C
This change simplifies significantly the code and provides the user with more flexibility.
The user can define its own generator class within the configuration macro. Please see for example
share/external/exgen.C
> Extend the external generator (extgen) concept to any FairGenerator

- CMakeLists.txt
Explicitely set the DEBUG build type to use -O0, in order to override
optimization flags that may come from the outside.
> CMake: Enable unoptimized debug build

- Steer/include/Steer/InteractionSampler.h
- Steer/src/InteractionSampler.cxx
- Steer/test/testInteractionSampler.cxx
Due to the bug, only half of the non-interacting bunches was skipped, leading to ~2 times higher int.rate than expected.
A test added to intercept such behaviour.
@sawenzel: can this be merged quickly, I need it for tests with another branch.
> Fix: real IR of the InteractionSampler was twice of the declared one

- Detectors/TRD/simulation/include/TRDSimulation/Detector.h
- Detectors/TRD/simulation/include/TRDSimulation/Digitizer.h
- Detectors/TRD/simulation/src/Detector.cxx
- Detectors/TRD/simulation/src/Digitizer.cxx
- Detectors/TRD/simulation/src/TRDSimulationLinkDef.h
Several short improvements at the level of hit creation (O2-453):
- Update TRD ProcessHits to the same level of AliRoot by keeping track references for the future.
- Hit vector is now ordered by detector number before going into the digitizer.
- Store charge instead of energy deposits (need some work on the future to keep the HitType with the right names).
- Removed Energy to Charge conversion at the Digitizer.
- Included TRsim at Link definitions.
> Update on TRD Hits (O2-453)

- Detectors/Passive/src/PassiveLinkDef.h
- Detectors/gconfig/CMakeLists.txt
- Detectors/gconfig/SetCuts.h
- Detectors/gconfig/include/SimSetup/GlobalProcessCutSimParam.h
- Detectors/gconfig/src/G3Config.cxx
- Detectors/gconfig/src/G4Config.cxx
- Detectors/gconfig/src/GlobalProcessCutSimParam.cxx
- cmake/O2Dependencies.cmake
The global process and cut settings for particle transport have been
made configurable making use of the O2 ConfigurableParam concept.
Modifying parameters can be done via the key 'GlobalSim'. Hence, they
can be set also in the command line
$> o2sim --configKeyValues 'GlobalSim.mPAIR=0'
which in this case turns off pair production.
> Make global cut and process settings configurable

- Framework/DebugGUI/src/imgui_extras.cpp
Speeds up a bit the rendering when many metrics are involved.
> DPL GUI: do not calculate scale at every iteration

- Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
With this, configurable parameters can be changed from the command line
and used in all processors participating in the digitizer workflow.
This is a first step. We are discussing a yet deeper automation
of the mechanism.
> DigitizerWorkflow: Enable Configurable parameters to be influenced

- Framework/Core/COOKBOOK.md
- Framework/Core/src/FrameworkGUIDeviceInspector.cxx
Uses lldb in Terminal.app on macOS, gdb in an xterm on Linux.
> DPL GUI: add ability to attach a debugger from the GUI

- Framework/Core/CMakeLists.txt
- Framework/Core/test/test_DataAllocator.cxx
Revert "DPL: disable tests which timeout due to a FairMQ regression"
This reverts commit defa237caa5e47e567bfb8145e431a098d9287ae.
Tests are run with `--dont-fail-on-timeout` since 310e8f2129, real
issues will lead to other error codes and are not masked.
> Re-enable the DPL workflow unit tests

- Detectors/MUON/MID/Simulation/src/Digitizer.cxx
- Detectors/MUON/MID/Simulation/test/testSimulation.cxx
There was an issue that appeared only for a very particular configuration of fired digits.
Since the tests are done by generating random hit positions, the issue did not appeared in my local tests.
> Fixes for MID digitizer

- Detectors/MUON/MID/Base/src/ChamberEfficiency.cxx
This is a private method used to convert the enum class to int.
All cases are treated, so the correct value is always returned.
However, the absence of a default causes a compiler warning: I am adding a dummy return value whose only aim is to suppress the warning
> Add default return value to suppress compiler warning

- Framework/Core/include/Framework/ArrowContext.h
- Framework/Core/include/Framework/ContextRegistry.h
- Framework/Core/include/Framework/MessageContext.h
- Framework/Core/include/Framework/RawBufferContext.h
- Framework/Core/include/Framework/RootObjectContext.h
- Framework/Core/include/Framework/StringContext.h
- Framework/Core/src/DataProcessingDevice.cxx
This is only a first step avoiding the array with fixed positions with minimal
changes to the other code. Further cleanup ahead.
> Making the ContextRegistry a dynamic, type-safe registry

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/DataAllocator.h
- Framework/Core/include/Framework/MessageContext.h
- Framework/Core/src/DataAllocator.cxx
- Framework/Core/src/DataProcessor.cxx
- Framework/Core/src/MessageContext.cxx
- Framework/Core/test/test_DataAllocator.cxx
@ktf, happy to receive your comments.
When I was about to add yet another context I figured out that the registry was not intended for that, so I made it more generic and type safe. In the next step I had to make a context which allows to control different types of `span<T>`, so I ended up making also `MessageContext`  more generic. Apart from cleanup, this should do the job now.
We can consider to move the functionality from the different contexts to specialized context objects in the future if you find the concept appropriate. But that's not urgent, the generic MessageContext would allow this with not to much extension.
> Fix O2-521

- DataFormats/Detectors/ITSMFT/common/include/DataFormatsITSMFT/ClusterTopology.h
- DataFormats/Detectors/ITSMFT/common/include/DataFormatsITSMFT/TopologyDictionary.h
- DataFormats/Detectors/ITSMFT/common/src/ITSMFTDataFormatsLinkDef.h
- Detectors/ITSMFT/ITS/macros/test/run_buildTopoDict_its.C
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/BuildTopologyDictionary.h
- Detectors/ITSMFT/common/reconstruction/src/BuildTopologyDictionary.cxx
Hi @lbariogl ,
In order to generate a realistic dictionary I've modified the way pattern info is accounted: now one can account only its frequency w/o affecting the COG bias evaluation. See comment of 1st commit for details.
Also I am adding a macro to generate a dictionary (accounting noise and QED clusters for the entropy only but not for the bias) from the data produced by the DPL flow. I think old CheckTopologies should be eliminated since it will not work with MC containing the QED contribution and the way it accesses the MC hits is super-slow for data with continuous readout.
> Extra features in Alpide cluster patterns dictionary generation

- Detectors/TPC/base/src/ParameterElectronics.cxx
o Otherwise the clusterizer finds also clusters in the tails of the digits
o Hence, more than one track per particle is found
> Bump DigitizationMode to subtract the pedestals by default

- CMakeLists.txt
- Framework/Core/src/FrameworkGUIDeviceInspector.cxx
- Framework/Core/src/RCombinedDS.cxx
As discussed last week, sets the O2 compile flags in our cmake instead of pulling in fairroot @pzhristov  @sawenzel @dberzano  @matthiasrichter 
@ktf : You seem to use assert(false) to silence "no return value" compiler warnings in several places, which does not work if we set the -DNDEBUG compile flag. However, I think it is correct to set this in debug mode, so I added some dummy returns.
> Set O2 compile flags in CMakeList and remove check_compiler macro

- Framework/Core/include/Framework/DataProcessingStats.h
- Framework/Core/src/DataProcessingDevice.cxx
Given we need to scale to up to 8kHz, there is no way we can use
monitoring to send the data relayer information at that rate. We
therefore send those metrics on a much lower frequency (1Hz) which
should still allow using the GUI for less demanding workflows, but
avoids the bottleneck for high rate ones.
> DPL: make relayer stats delayed by 1 second

- Framework/Core/include/Framework/DeviceMetricsInfo.h
- Framework/Core/include/Framework/LogParsingHelpers.h
- Framework/Core/include/Framework/TextControlService.h
- Framework/Core/src/DataProcessingStatus.h
- Framework/Core/src/DeviceMetricsInfo.cxx
- Framework/Core/src/LogParsingHelpers.cxx
- Framework/Core/src/TextControlService.cxx
- Framework/Core/src/runDataProcessing.cxx
- Framework/Core/test/test_DeviceMetricsInfo.cxx
Remove a bit of technical debt when processing the inputs from the
children dataprocessors. In particular:
* Most of parsing / processing now uses a string_view so that the
unparsed buffers are not copied around multiple times.
* Read buffer is now 16kB (was 1kB) which seems to avoid having
to split the processing in multiple iterations.
* Add tracing information for data being read from children and
for data processed by the driver.
> DPL driver: increase input parsing performance

- Detectors/TPC/workflow/README.md
- Detectors/TPC/workflow/include/TPCWorkflow/RecoWorkflow.h
- Detectors/TPC/workflow/src/RecoWorkflow.cxx
- Detectors/TPC/workflow/src/tpc-reco-workflow.cxx
This cleans up some incorrect help message and defines the output of the `HardwareClusterDecoder` (TPC NativeClusters) as input/output type `clusters`.
> Cleaning up TPC reco workflow

- DataFormats/simulation/include/SimulationDataFormat/MCTruthContainer.h
- DataFormats/simulation/test/testMCTruthContainer.cxx
Have been running into problems with some existing code because the content of
the container was not really moved to the target instance. By explicitly defining
the move constructor and assignment operator as default, the compiler does the
correct thing with the member vectors.
There was probably a bug in the TPC HardwareClusterDecoder where std::move(container)
has been used with the intention to make the original container empty.
> Defining default move constructor and assignment operator for MCTruthContainer

- DataFormats/Detectors/TPC/include/DataFormatsTPC/ClusterHardware.h
- DataFormats/Detectors/TPC/include/DataFormatsTPC/ClusterNative.h
- DataFormats/Detectors/TPC/include/DataFormatsTPC/ClusterNativeHelper.h
- Detectors/TPC/reconstruction/include/TPCReconstruction/HardwareClusterDecoder.h
- Detectors/TPC/reconstruction/src/HardwareClusterDecoder.cxx
- Detectors/TPC/workflow/src/ClusterDecoderRawSpec.cxx
Defining also a helper struct to represent ClusterNative objects preceded by
a descriptive header struct in a flat buffer.
This changes the output of the cluster decoder to a flat buffer structure, the memory is allocated directly in the output message, or can be allocated by the custom allocator.
> Write output of TPC cluster decoder directly to message memory

- Framework/Core/include/Framework/ConfigParamRegistry.h
- Framework/Core/src/PropertyTreeHelpers.cxx
The optional short version of the command line option needs to be stripped to
get the correct key for retrieving value from parsed variable map.
Adding also more descriptive exception messages.
> Fix O2-593: using the correct key to populate property tree from program options

- Framework/Core/include/Framework/ConfigParamRegistry.h
- Framework/Core/test/test_ConfigParamRegistry.cxx
Use `if constexpr` to improve maintainability and add test for short options.
> DPL: streamline ConfigParamRegistry

- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
- Detectors/ITSMFT/ITS/simulation/src/V3Layer.cxx
Thanks to Yasser minor bugs in the Inner Barrel geometry were found and fixed:
- the FPC and the capacitors were wrongly oriented (the shortest side of the FPC was toward the cooling pipes instead of the far end of the module; capacitors and resistors were specular to their actual position)
- the tilting angle was in the worng direction with respect to Corrado's plots and photos of the real detector
> FIX IB geometry (FPC/capacitor orientation, tilt sign)

- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/AlpideCoder.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/PayLoadCont.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/PayLoadSG.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/PixelReader.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/RawPixelReader.h
- Detectors/ITSMFT/common/reconstruction/src/PayLoadCont.cxx
- macro/run_CRUDataSkimming_its.C
- macro/run_rawdecoding_its.C
Every GBT link is writing its data to a separate CRU superpage -> multiple triggers of the same link per superpage. When multiple links are dumped into the same file, the trigger data is not contiguous. 
Here we are caching data of each link in a separate buffer, so that decoding can run over the same trigger of different links.
The signature of getRUDecodingStatSW, getRUDecodingStatHW methods has changed, not instead of the reference, they return pointers on relevant RUDecodingStat (will be 0 if RU was not seen in the data).
> Unmangling/caching of multiple links per RU

- DataFormats/simulation/include/SimulationDataFormat/PrimaryChunk.h
- DataFormats/simulation/include/SimulationDataFormat/Stack.h
- DataFormats/simulation/src/SimulationDataLinkDef.h
- DataFormats/simulation/src/Stack.cxx
- DataFormats/simulation/test/MCTrack.cxx
- Detectors/EMCAL/simulation/src/Detector.cxx
- Detectors/FIT/T0/simulation/src/Detector.cxx
- Detectors/FIT/V0/simulation/src/Detector.cxx
- Detectors/HMPID/simulation/src/Detector.cxx
- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
- Detectors/ITSMFT/MFT/simulation/src/Detector.cxx
- Detectors/MUON/MCH/Simulation/src/Stepper.cxx
- Detectors/MUON/MID/Simulation/src/Stepper.cxx
- Detectors/TOF/simulation/src/Detector.cxx
- Detectors/TPC/simulation/src/Detector.cxx
- Detectors/TRD/simulation/src/Detector.cxx
- Detectors/ZDC/simulation/src/Detector.cxx
- Detectors/gconfig/commonConfig.C
- Steer/include/Steer/O2MCApplication.h
- Steer/src/O2MCApplication.cxx
- macro/runCATrackingClusterNative.C
- run/O2HitMerger.h
- run/O2PrimaryServerDevice.h
- run/O2SimDevice.h
I've deleted `using namespace o2;` from `macro/runCATrackingClusterNative.C`, because `o2::base` was clashing with `std::base`.
> Fix namespace naming: o2::Data

- Detectors/ITSMFT/ITS/reconstruction/src/CookedTracker.cxx
@iouribelikov @mpuccio : this fixes the crash in reconstruction (cluster phi happened to be exactly 2pi).
Yura, note that the CookedTracks is prone to crash in multi-thread mode, since the TGeometry used for material budget query is not thread-safe (navigator changes its state). With 8 threads I get: 
````
#6  TObject::TestBit (f=32768, this=<optimized out>) at /home/shahoian/alice/sw/BUILD/f58b77b61af7bc34412ed1a39b4a5bd4a0b1a428/ROOT/include/TObject.h:172
#7  TGeoNode::IsOffset (this=<optimized out>) at /home/shahoian/alice/sw/BUILD/f58b77b61af7bc34412ed1a39b4a5bd4a0b1a428/ROOT/include/TGeoNode.h:100
...
#17 0x00007f383709b885 in o2::ITS::CookedTracker::makeBackPropParam (this=this
entry=0x7fffba178820, track=...) at /home/shahoian/alice/sw/SOURCES/O2/1.0.0/0/Detectors/ITSMFT/ITS/reconst …
```
> Fix: protection for sectorID overflow in CookerTracker

- Common/Utils/include/CommonUtils/ShmManager.h
- run/O2SimDevice.h
We need larger memory buffers to the hits when transporting
10K primaries per sub-event. (The alternative would be to decrease
the max sub-event size ... at some moment we need to correlate these numbers).
This should fix O2-592.
> O2-592: Increase shared memory buffer for hits

- run/O2PrimaryServerDevice.h
* generate events concurrently in a thread
* use asynchronous mode for sending back
This should lead to a more responsive event server.
Other steps (such as asynchronous creation of the ROOT message) might follow.
> o2sim: Make event server less blocking

- DataFormats/simulation/include/SimulationDataFormat/BaseHits.h
- DataFormats/simulation/src/SimulationDataLinkDef.h
- Detectors/TRD/simulation/include/TRDSimulation/Detector.h
- Detectors/TRD/simulation/src/Digitizer.cxx
- macro/analyzeHits.C
This PR adds a more flexible hit type class (`BasicXYZVHit`) and two specialized classes (`BasicXYZEHit` and `BasicXYZQHit`). These classes have different types for the hit value (`double` or `float`, and `int`). Therefore, they can store energy loss or deposited charge as the hit value using the right type.
The motivation is the TRD hit value, which keeps deposited charge (`int`) instead of energy loss (`float` or `double`). In the hit file `o2sim.root` the hits were visualized as energy loss (`mELoss`), while they actually store deposited charge. The wrong variable name could cause mistakes in the future (short discussion in O2-453).
As a solution, `mELoss`  is now `mHitValue`. Two new specialized classes contain the hit value getter methods `GetEnergyLoss()` and `GetCharge()`, both …
> Improved basic hit class

- CMakeLists.txt
`checkStack.C` is part of the o2sim tests already. Random parallel runs will
cause ctest to fail
> Disable clashing double run of checkStack in ctest

- DataFormats/Detectors/TPC/include/DataFormatsTPC/ClusterNativeHelper.h
- DataFormats/Detectors/TPC/src/ClusterNativeHelper.cxx
- DataFormats/Detectors/TPC/src/DataFormatsTPCLinkDef.h
The access to clusters MC truth (or simply destructing the ClusterNativeHelper::Reader) was leading to segm.viol. since the addresses of MC branches were not correctly set. 
With this fix attached macro dumps correctly the cluster info (runs over the output of  
````tpc-reco-workflow  --tpc-digit-reader "--infile tpcdigits.root" --input-type digits --output-type clusters,tracks --tracker-options "cont refX=83 bz=-5.0068597793" --tpc-track-writer "--treename events --track-branch-name Tracks --trackmc-branch-name TracksMCTruth"````). @martenole, you can extract the lines for access to tracks/clusters from it.
[tpcclAcc.C.gz](https://github.com/AliceO2Group/AliceO2/files/3061201/tpcclAcc.C.gz)
> Fix in access to TPC clusters MC info + cleanup of LinkDef 

- run/O2PrimaryServerDevice.h
- run/o2simtopology.json
Use ConditionalRun instead of OnData, in order to be
able to continue upon socket errors. With OnData, the system
automatically exited the device.
Use some higher buffer sizes for message queues
> o2sim: "ConditionalRun" instead of "OnData"

- run/O2HitMerger.h
- run/O2SimDevice.h
- run/o2sim_parallel.cxx
Use ConditionalRun in hit merger; Gives more flexibility/controll
for error handling (over OnData).
Smaller changes to terminal output of worker
Overall, this commit makes the system more
reliable and solves a remaining issue in relation
to "Interrupted system call and could not receive on socket".
> o2sim: ConditionalRun in hit merger

- Common/SimConfig/include/SimConfig/ConfigurableParamHelper.h
- Common/SimConfig/src/ConfigurableParamHelper.cxx
* fix issue with operator<< which was not printing correct values
(probably due to problem with copying pointer values)
* rename paramDataMember to ParamDataMember (since a type)
* some const-correctness fixes
> ConfigurableParam: Fix issue with operator<<; Some code style changes

- DataFormats/TimeFrame/include/TimeFrame/TimeFrame.h
- DataFormats/TimeFrame/src/TimeFrameLinkDef.h
- DataFormats/TimeFrame/test/TimeFrameTest.cxx
- Utilities/DataFlow/src/EPNReceiverDevice.cxx
- Utilities/DataFlow/src/FakeTimeframeBuilder.cxx
- Utilities/DataFlow/src/TimeframeParser.cxx
- Utilities/DataFlow/src/TimeframeValidatorDevice.cxx
- Utilities/DataFlow/src/TimeframeWriterDevice.cxx
Note that I've renamed it to `dataformats`, not `data_format` as the codechecker would rename, because I suspect http://aliceo2group.github.io/AliceO2/d4/de9/namespaceo2_1_1DataFormat.html and http://aliceo2group.github.io/AliceO2/d1/dea/namespaceo2_1_1dataformats.html are related namespaces.
> Fix namespace naming: o2::DataFormat

- Detectors/GlobalTracking/include/GlobalTracking/MatchTPCITS.h
- Detectors/GlobalTracking/src/MatchTOF.cxx
- Detectors/GlobalTracking/src/MatchTPCITS.cxx
- cmake/O2Dependencies.cmake
- macro/run_match_TPCITS.C
@noferini: I've also touched the TOF matching code: since the propagation to TPC outer R is now done after the outward refit in the TPC, the TOF matching should not consider those tracks which did not reach this radius.
> ITC-TPC outward refit after the matching

- Common/SimConfig/include/SimConfig/SimConfig.h
- Common/SimConfig/src/SimConfig.cxx
- DataFormats/simulation/CMakeLists.txt
- DataFormats/simulation/include/SimulationDataFormat/MCEventHeader.h
- DataFormats/simulation/include/SimulationDataFormat/MCEventStats.h
- DataFormats/simulation/include/SimulationDataFormat/Stack.h
- DataFormats/simulation/src/SimulationDataLinkDef.h
- DataFormats/simulation/src/Stack.cxx
- Detectors/Base/include/DetectorsBase/Detector.h
- Steer/include/Steer/O2MCApplication.h
- Steer/include/Steer/O2MCApplicationBase.h
- Steer/src/O2MCApplication.cxx
- run/O2HitMerger.h
- run/O2SimDevice.h
- run/o2sim_parallel.cxx
* Introduction of MCEventStats class to collect
some global properties (number of hits, tracks, etc) done
for one event. Such objects are attached to the MCEventHeader and can
quickly be accessed for filtering MC events.
* First prototype of filtering out events which did not leave any
detector response (hit)
* some reduction of verbosity (INFO -> DEBUG)
Implements most of https://alice.its.cern.ch/jira/browse/O2-604
> Ability to filter out empty events

- Generators/include/Generators/GeneratorTGenerator.h
@preghenella: this is needed to be access calculated X-section of the QED generator wrapped to ``o2::evgen::GeneratorTGenerator``
> Add TGenerator getter for O2 GeneratorTGenerator

- Detectors/TPC/workflow/src/tpc-reco-workflow.cxx
The digitizer workflow is still using the original lane configuration which
distributes data of multiple TPC sectors among subsequent time slices. This
will be changed in the future when the work on staggereing is completed, but
for the moment this needs to be forced in `tpc-reco-workflow`.
> Forcing the original TPC lane configuration for input type `digitizer`

- DataFormats/simulation/include/SimulationDataFormat/MCTrack.h
- DataFormats/simulation/include/SimulationDataFormat/Stack.h
* A new interface to MC stack to query the production
process of the current track
* Actually store the process ID in our MCTrack class
This fixes https://alice.its.cern.ch/jira/browse/O2-617.
Actually, we already kept track of the process because it was
encoded in the TParticle uniqueID. This commit is just propagating this
information further and offering an actual API to read it out.
> o2sim: Keep track of secondary production process

- Steer/include/Steer/O2MCApplicationBase.h
- Steer/src/O2MCApplication.cxx
Keep track of which volumes are sensitive.
The main motivation here is that external tools (MCStepLogger)
can use this to categorize steps according to if in sensitive region
or not.
> o2sim: write out sensitive volumes

- CCDB/CMakeLists.txt
- cmake/O2Dependencies.cmake
The Protobuf and gRPC aliDist recipes are being ported to use CMake instead of upstream's old build system. This change should fix CCDB's CMake to work with what Protobuf's CMake spits out.
See https://github.com/alisw/alidist/pull/1581
> Adapt to Protobuf built with CMake

- Framework/Core/src/DataSpecUtils.cxx
This avoids having a bogus metric name in case the origin or
the description are not null teminated, since that's actually
allowed in the datamodel.
> DPL: handle cornercase for metrics

- Utilities/Mergers/src/mergersTopologyExample.cxx
This duplicated name prevented from running the topology.
> Fix duplicated name in merger example topology

- Detectors/CPV/simulation/src/Detector.cxx
- Detectors/MUON/MCH/Simulation/src/Detector.cxx
- Detectors/MUON/MID/Simulation/src/Detector.cxx
- cmake/O2Dependencies.cmake
add calls to stack->addHit since we need to register tracks that
create a hit (important for Kinematics pruning)
* done for CVP, MCH, MID
remove a duplicate bucket for mid_simulation
> o2sim: correctly register hit creation; remove duplicate bucket

- Detectors/TRD/base/include/TRDBase/TRDSimParam.h
- Detectors/TRD/simulation/src/Digitizer.cxx
This PR only adds a patch at the digitizer level (O2-455) to take care of TR photons that are absorbed outside the chamber volume (according to work done in AliRoot). It also considers some rearrangement of code and reminders as well a few improvements.
In general this PR includes just a few fixes without any new implementations or major changes, besides the included patch (which is something important not to forget).
> TRD digitizer TR photons patch and defaulted values (O2-455)

- Framework/Core/src/FrameworkGUIDeviceInspector.cxx
This was already the case on macOS, but not on Linux, resulting in the GUI freezing when attaching a debugger.
> DPL: run debugger asynchronously from the GUI

- DataFormats/Headers/include/Headers/RAWDataHeader.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/ChipMappingMFT.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/RawPixelReader.h
- Detectors/ITSMFT/common/reconstruction/src/ITSMFTReconstructionLinkDef.h
- macro/run_CRUDataSkimming_its.C
- macro/run_digi2raw_its.C
- macro/run_rawdecoding_its.C
The bits 124-127 of RDH are for the ``DATAPATH WRAPPER ID: number used to identify one of the 2 End Points [0/1]`` and should not be 0 (as it was assumed in the heuristic detection of the RDH in ITS data decoder).
> Fix: b124-127 of RDH are EndPoint ID, 0 is not guaranteed

- GPU/TPCSpaceChargeBase/AliTPCPoissonSolver.cxx
@dberzano @ktf @sawenzel : This fixes the doxygen problem for me. (Was merged as part of AliTPCCommon but its TPC code not GPU :))
> Fix latex code embedded in doxygen of TPC SCD Poisson Solver

- Detectors/TRD/base/src/TRDCommonParam.cxx
Uncommented the GetDiffCoeff method in TRDCommonParam. I suspect this was left aside because of the magnetic field?.
If there are other reasons maybe @davidrohr or @sawenzel can comment. I need this piece of code to apply the diffusion smearing to the position of a single electron at the Digitizer level.
Maybe @shahor02 can confirm that the units returned by o2::field::MagneticField::solenoidField() are still Gauss?
> GetDiffCoeff in TRDCommonParam

- Detectors/Base/include/DetectorsBase/MaterialManager.h
- Detectors/Base/src/MaterialManager.cxx
- Detectors/Passive/include/DetectorsPassive/Compensator.h
- Detectors/Passive/include/DetectorsPassive/HallSimParam.h
- Detectors/Passive/src/Compensator.cxx
- macro/analyzeHits.C
Preparing split of YOKE into fast and slow (skin) component.
Can be used for a systematic study of necessary skin depth.
Add missing physics processes to MaterialManager enums.
Update a macro analysing hits.
> Possibility to have fast YOKE (compensator) treatment

- Common/SimConfig/include/SimConfig/ConfigurableParam.h
- Common/SimConfig/include/SimConfig/ConfigurableParamHelper.h
- Common/SimConfig/src/ConfigurableParam.cxx
- Common/SimConfig/src/ConfigurableParamHelper.cxx
A ConfigurableParam can now have an enum data member, and
be updated with either legal string or int values from the command line.
> ConfigurableParam: add support for enums

- Detectors/ITSMFT/ITS/macros/EVE/DisplayEvents.C
- Detectors/ITSMFT/ITS/macros/test/CheckTracks.C
- Detectors/ITSMFT/ITS/macros/test/run_workflows.sh
- Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CookedTracker.h
- Detectors/ITSMFT/ITS/reconstruction/src/CookedTracker.cxx
- Detectors/ITSMFT/ITS/workflow/include/ITSWorkflow/ClusterWriterSpec.h
- Detectors/ITSMFT/ITS/workflow/include/ITSWorkflow/ClustererSpec.h
- Detectors/ITSMFT/ITS/workflow/include/ITSWorkflow/CookedTrackerSpec.h
- Detectors/ITSMFT/ITS/workflow/include/ITSWorkflow/DigitReaderSpec.h
- Detectors/ITSMFT/ITS/workflow/include/ITSWorkflow/RecoWorkflow.h
- Detectors/ITSMFT/ITS/workflow/include/ITSWorkflow/TrackWriterSpec.h
- Detectors/ITSMFT/ITS/workflow/src/ClusterWriterSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/ClustererSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/CookedTrackerSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/DigitReaderSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/RecoWorkflow.cxx
- Detectors/ITSMFT/ITS/workflow/src/TrackWriterSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/its-reco-workflow.cxx
- macro/run_trac_its.C
With this PR we will be able to
1) run the ITS reconstruction workflow in "triggered" RO mode,
2) run both ITS tests (the macro-driven and the DPL based) in continuous and "triggered" RO modes,
3) process digits and clusters stored in both single or multiple tree entries,
4) suppress the propagation of MC labels through the RAM by means of the "--disable-mc" command-line argument passed to the reconstruction workflow.
> Technical improvements in the ITS reconstruction workflow

- DataFormats/Detectors/TPC/CMakeLists.txt
- DataFormats/Detectors/TPC/include/DataFormatsTPC/TrackTPC.h
- DataFormats/Detectors/TPC/include/DataFormatsTPC/dEdxInfo.h
- DataFormats/Detectors/TPC/src/DataFormatsTPCLinkDef.h
- Detectors/TPC/reconstruction/src/TPCCATracking.cxx
- GPU/Common/GPUDefGPUParameters.h
- GPU/GPUTracking/Base/cuda/GPUReconstructionCUDA.cu
- GPU/GPUTracking/Base/hip/GPUReconstructionHIP.hip.cpp
- GPU/GPUTracking/Base/opencl/GPUReconstructionOCL.cxx
- GPU/GPUTracking/Merger/GPUTPCGMMergedTrack.h
- GPU/GPUTracking/Merger/GPUTPCGMTrackParam.cxx
- GPU/GPUTracking/Merger/GPUTPCGMTrackParam.h
- GPU/GPUTracking/Standalone/tools/switchToAliRootLicense.sh
- GPU/GPUTracking/dEdx/GPUdEdx.h
- GPU/GPUTracking/dEdx/GPUdEdxInfo.h
@wiechula : As we discussed today, this PR moves the dEdx information to TPCDataFormats and stores it in the trackTPC after tracking.
> Store TPC dEdx Information in trackTPC + some fixes

- Common/MathUtils/include/MathUtils/Utils.h
- Detectors/Base/include/DetectorsBase/MatCell.h
- Detectors/Base/include/DetectorsBase/MatLayerCyl.h
- Detectors/Base/include/DetectorsBase/MatLayerCylSet.h
- Detectors/Base/include/DetectorsBase/Ray.h
- Detectors/Base/src/MatLayerCyl.cxx
- Detectors/Base/src/MatLayerCylSet.cxx
- Detectors/Base/src/Ray.cxx
- Detectors/Base/test/buildMatBudLUT.C
- Detectors/Base/test/testMatBudLUT.cxx
- GPU/GPUTracking/Base/GPUReconstructionIncludesDevice.h
- GPU/GPUTracking/Base/cuda/CMakeLists.txt
- GPU/GPUTracking/Base/hip/CMakeLists.txt
- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/Merger/GPUTPCGMPropagator.cxx
- GPU/GPUTracking/Merger/GPUTPCGMPropagator.h
- GPU/GPUTracking/Merger/GPUTPCGMTrackParam.cxx
- GPU/GPUTracking/Standalone/config_common.mak
- GPU/GPUTracking/Standalone/config_libGPUTracking.mak
- cmake/O2Dependencies.cmake
@shahor02 : This adapts the LUT class for GPU. There is one issue left with CUDA. Ray.h uses std::array<CrossPar, 2> mCrossParams;, but CUDA right now does not work with std::array and std::pair.
If that is fine with you, I'd just replace this by two C arrays.
The rest is just adding GPU...() macros and minor modifications.
FYI:
GPUd() is the default macro, GPUdi() will add an inline keyword for host code. You must not write "GPUd() inline" but use GPUdi() instead.
For masking there is different levels:
GPUCA_ALIGPUCODE (everything from AliGPU)
GPUCA_GPUCODE (passed to CUDA / OpenCL / HIP compiler, device or host runtime)
GPUCA_GPUCODE_DEVICE (only compiled for device)
I modified some of the masking levels you already inserted, and added some more for incompatible functions.
We might also …
> Adapt LUT class for GPU

- Detectors/ITSMFT/ITS/tracking/include/ITStracking/Tracker.h
@mpuccio : The run_track_ca_its.C macro does no longer work (I wantet to check the ITS GPU track fit, now that AliTPCCommon is merged.)
There are two problems in the macro.
- Wrong GPU namespace, which is fixed by this PR.
- The other was introduced by @iouribelikov when he changed loadROFrameData(...). It is not fully clear to me how to fix this, could you have a look?
> Fix gpu namespace for ITS tracker (broke the ITS tracking macro)

- CMakeLists.txt
- Detectors/FIT/workflow/CMakeLists.txt
- Detectors/GlobalTrackingWorkflow/CMakeLists.txt
- cmake/ensure-executable-naming-convention.sh.in
Plus two fixes already for executables not following it.
Opened for discussion probably is how to properly deal with the "subsystem" part of the name (o2-subsystem{-whatever-else}) in the script `cmake/ensure-executable-naming-convention.sh.in`
In order not to change any more for the moment, I just listed the existing "subsystems" we currently have in our executable names. Might have to revisit this if we want to categorize a bit our executables. Or do nothing if we don't. In any case the script issue a warning, not an error, for unknown "subsystem" names.
> Test to ensure we stick to the executable naming convention

- Detectors/ZDC/simulation/include/ZDCSimulation/Detector.h
- Detectors/ZDC/simulation/include/ZDCSimulation/Hit.h
- Detectors/ZDC/simulation/src/Detector.cxx
Make hit processing more modular. Here taking out a routine
determining the detector/sector information, making the actual hit creation
logic smaller. Reduce code somewhat and use Vector3D<float> types instead of float* where
possible.
Fix a bug for detection of electromagnetic detector/sector.
Reduce the number of sensitive volumes to absolut necessary (fibres) for digit creation.
This should already be a good optimization as it prevents calling the hit routine
for the passive dominating material ZNST.
(Should one want to track information in passive materials, one may use the MCStepLogger).
Activate previously omitted ZEM as sensitive detector.
> ZDC: Refactor hit processing + optimization

- Detectors/GlobalTracking/include/GlobalTracking/MatchTPCITS.h
- Detectors/GlobalTracking/src/MatchTPCITS.cxx
- Detectors/GlobalTrackingWorkflow/src/TPCITSMatchingSpec.cxx
- macro/run_match_TPCITS.C
Now ITS tracks strore cluster indices wrt the 1st cluster of the relevant ROF, hence refitting
routine of the ITSTPC matching needs to offset them in order to fetch from the clusters buffer of the whole TF
> Account for change of cluster refs in ITS tracks

- Generators/CMakeLists.txt
- Generators/include/Generators/BoxGunParam.h
- Generators/src/BoxGunParam.cxx
- Generators/src/GeneratorFactory.cxx
- Generators/src/GeneratorsLinkDef.h
The box event generator is now configurable which is convenient
for testing/scanning simulation with various particle types and energies.
> Make box particle gun configurable

- Detectors/FIT/T0/simulation/src/Detector.cxx
- Removed DefineOpticalProperties() call from ConstructGeometry() as it should be and is done from ConstructOpGeometry()
- Improved the error message when optical properties are not read
> Fixed setting optical properties in T0:

- Detectors/Base/include/DetectorsBase/Detector.h
- Detectors/Base/src/Detector.cxx
The shared memory readout for hits uses a "busy"
flag to indicate that a buffer is still being processed.
This flag was unset to early, in particular for the TPC where we
have multiple hit branches.
Fixes https://alice.its.cern.ch/jira/browse/O2-689
> o2sim: Fix bug for shared memory readout [O2-689]

- Detectors/ITSMFT/ITS/tracking/include/ITStracking/Configuration.h
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/Constants.h
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/IndexTableUtils.h
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/MathUtils.h
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/PrimaryVertexContext.h
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/ROframe.h
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/Road.h
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/Tracker.h
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/TrackerTraits.h
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/Vertexer.h
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/VertexerTraits.h
- Detectors/ITSMFT/ITS/tracking/src/IOUtils.cxx
- Detectors/ITSMFT/ITS/tracking/src/PrimaryVertexContext.cxx
- Detectors/ITSMFT/ITS/tracking/src/Road.cxx
- Detectors/ITSMFT/ITS/tracking/src/Tracker.cxx
- Detectors/ITSMFT/ITS/tracking/src/TrackerTraitsCPU.cxx
- Detectors/ITSMFT/ITS/tracking/src/VertexerTraits.cxx
- GPU/GPUTracking/ITS/GPUITSFitterKernels.cxx
`GPU/GPUTracking/ITS/GPUITSFitterKernels.cxx` file required manual intervention, because it was using  `constants::its::UnusedIndex` etc. and the name `constants`, after the fix, became resolving as `o2::constants`, not `o2::its::constants`, which caused compilation errors, because there is no `o2::constants::its`. Make sure you agree with the way this was fixed.
> Fix namespace naming: o2::its::Constants

- DataFormats/Headers/include/Headers/TimeStamp.h
- DataFormats/Headers/test/testTimeStamp.cxx
Was renamed to `lhc_clock_parameter`, whilst the tool suggests `lhcclock_parameter`.
> Fix namespace naming: o2::header::LHCClockParameter

- Framework/Core/include/Framework/ExpirationHandler.h
- Framework/Core/src/DataRelayer.cxx
- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/Core/src/LifetimeHelpers.cxx
This PR contains two fixes which make my timer use-case work. The problems and solutions are described in the commit messages.
I think that `test_DanglingInputs` will fail now, because timer messages will be created in slots which were booked by the timer mechanism, so we won't get any cache line completed, which is necessary to invoke the `ProcessCallback` there. Apparently, the test used to pass thanks to a bug ;)
@ktf What do you think? I am not advocating too much for this specific fixes if you have a better idea how to solve that.
> DPL: Fix timers

- Detectors/FIT/workflow/src/T0RecPointWriterSpec.cxx
- Detectors/GlobalTrackingWorkflow/src/TrackWriterTPCITSSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/ClusterWriterSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/ClustererSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/CookedTrackerSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/DigitReaderSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/TrackWriterSpec.cxx
- Detectors/ITSMFT/ITS/workflow/src/TrackerSpec.cxx
In absence of the flow forced termination by its last device setting  ``readyToQuit(true)`` (which creates problems with flows merging, see https://github.com/AliceO2Group/AliceO2/pull/1888#issuecomment-494816380) all devices should terminate themselves by   ``pc.services().get<ControlService>().readyToQuit(false)`` in order to complete the flow.
> Devices set readyToQuit(false) after 1st TF to unblock flow completion

- Detectors/Base/include/DetectorsBase/Detector.h
- Detectors/Base/src/Detector.cxx
- Detectors/Base/src/MaterialManager.cxx
- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/Detector.h
- Detectors/ITSMFT/MFT/simulation/include/MFTSimulation/Detector.h
- Detectors/TRD/simulation/CMakeLists.txt
- Detectors/TRD/simulation/data/simcuts.dat
- Detectors/ZDC/simulation/include/ZDCSimulation/Detector.h
- Detectors/ZDC/simulation/src/Detector.cxx
(Sensitive) detectors can now simply provide a simcuts.dat
file in order to have cuts applied automatically.
This should make it easy to copy cuts from AliRoot (but a review
of the values is in any case suggested).
Since this is virtual mechanism the default behaviour can still be
overridden (as done by TPC).
Applying generic implementation to ZDC and TRD.
> Provide generic SetSpecialPhysicsCut implementation

- Framework/Core/src/runDataProcessing.cxx
Because of the ways workflow merging works, if a dpl executable
is piped to a an external process, e.g. tee or less, it will
dump the configuration, rather than run. By passing the `--run`
option you change this behavior and force it to run regardless
of a pipe being present.
> DPL: force run if --run option is provided

- Common/SimConfig/src/ConfigurableParam.cxx
setValue called with template parameter was having no effect.
The cause was an inversion of returned bool in the function
comparing two byte arrays.
> ConfigurableParam: fix setValue bug

- Detectors/TRD/simulation/include/TRDSimulation/Digitizer.h
- Detectors/TRD/simulation/src/Digitizer.cxx
One more step toward the full digitization chain. Signal conversion to ADC values completed with the number of time bins defaulted to 30 as discussed previously in meetings.
Last thing to do (and next): Filling vectors and passing info to the DPL.
https://alice.its.cern.ch/jira/browse/O2-455
> TRD digitizer signals to ADC O2-455

- Detectors/ZDC/simulation/include/ZDCSimulation/Detector.h
- Detectors/ZDC/simulation/src/Detector.cxx
Review of logic to create hits and how to associate them
to the impacting/principal track entering into the ZDC detectors.
* Introduction of (virtual) envolope volumes for ZN + ZP so that
entering track can be recorded
* Introduction of an index keeping track of the current hit for a particular
detector,sector combination; This index is reinitialized whenever a
new principal track is recorded
* Simplication of code; Get rid of data members when not necessary.
> Iteration on ZDC hit creation

- Detectors/TPC/base/test/testTPCParameters.cxx
Add an explicit test for the two ways of calling setValue
for a parameter.
> ConfigurableParam: add a unit test for setValue

- Detectors/TRD/simulation/src/Digitizer.cxx
Bug fix https://alice.its.cern.ch/jira/browse/O2-711.
@davidrohr, this was the problem with the messages about indices out of range that were filling the log. It is now really fixed.
> TRD Bug fix O2-711

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/AnalysisTask.h
- Framework/Core/include/Framework/Kernels.h
- Framework/Core/src/Kernels.cxx
- Framework/Core/test/test_ASoA.cxx
- Framework/Core/test/test_Kernels.cxx
- Framework/Foundation/CMakeLists.txt
- Framework/Foundation/include/Framework/Traits.h
- Framework/Foundation/test/test_Traits.cxx
- Framework/TestWorkflows/src/o2AnalysisTaskExample.cxx
This PR serves four purposes:
* It introduces an helper which allows static dispatching of virtual methods of a given base class (AnalysisTask, in this case) so that DPL will request the data needed and perform a given operation only when the hooks are effectively overriden by the AnalysisTask implementor.
* It introduces a few kernels for splitting a large table of tracks in it's "per-event" sub-tables. Actual data is zero-copied thanks to Arrow Table slicing facilities. It also serves as an example of how to create Arrow compute Kernels.
* It introduces a few new analysis hooks, as discussed, to process various combinations of Collisions, Timeframe and Tracks.
* It introduces a new SoA layer which sits on top of Arrow Tables and allows to iterate over via a user friendly, physics …
> AnalysisTask improvements

- Framework/Core/include/Framework/DataProcessorSpec.h
This should suppress the 'missing initializer for member' warnings generated when Options, Services and labels are not explicitly specified. We have this warning enabled in QC.
> Provide default values for rarely used DataProcessorSpec members

- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/TableBuilder.h
- Framework/Core/test/test_TableBuilder.cxx
Previous way of building tables:
auto rowWriter = builder.persist<int, int, int>("x", "y", "z");
can now be replaced by:
auto rowWriter = builder.cursor<SimpleVector>();
assuming `SimpleVector` is a `soa::Table` derived class.
> DPL: add SoA support to TableBuilder.

- Framework/Utils/CMakeLists.txt
It started to fail in the CI for no apparent reason. Disabling this
since understanding what is going on it taking long.
> Disable RootTreeWriterWorkflow test.

- Framework/Core/include/Framework/DataAllocator.h
- Framework/Core/src/DataAllocator.cxx
In the Data Sampling's Dispatcher, I would like to be agnostic to what I copy from input to output. This would facilitate supporting all serialization methods and improve its performance (no serialization and de-serialization required anymore).
@ktf @matthiasrichter Are you fine with this modification? I am not forcing it, if there is a way to achieve that with the existing code.
> DPL: Possibility to snapshot an already serialized object

- Detectors/ITSMFT/ITS/tracking/cuda/include/ITStrackingCUDA/Vector.h
@mpuccio @mconcas : I have been observing some undefined behavior and crashes in the ITS tracker traits destructors when I enabled the GPU. It seems to be (at least partially) related to uninitialized ptrs in the ITS GPU vector.
This PR fixes the issue for me for now, but it was not really reproducible, so I am not sure if it is fixed to 100%.
Also, you actually have constructors that should initialize it to nullptr already, but apparently, this is not working in all cases. I didn't manage to fully understand it and then gave up... Anyhow, the initialization in this way should not hurt in any case.
Do you want to check what goes wrong with the initialization, or shell we just merge commit?
Below is a valgrind stacktrace before one of the crashes I had, in case you want to investigate …
> Fix missing GPU vector ptr initialization in ITS tracker

- DataFormats/Detectors/TPC/include/DataFormatsTPC/Constants.h
- GPU/Common/GPUDefConstantsAndSettings.h
@wiechula @sawenzel : Are you OK with this change. The reasoning is:
- I want to use Run 2 data for verification in the standalone mode. For this, I need to change the MAXGLOBALPADROW to 159 for Run 2. In this way, I can use the compression without additional changes, since it bases on the other DataFormatsTPC headers, which use the MAXGLOBALPADROW constant.
- In some places of the GPU code, I have fixed size arrays with the number of TPC sectors / pad rows. OpenCL (and ROOT 5) do not work with constexpr fixed size C-arrays. Hence, I am using defines GPUCA_NSLICES and GPUCA_ROW_COUNT. These will just resolve to o2::tpc::Constants::... normally, but for OpenCL I am just putting the hardcoded value in.
This hopefully gives the cleanes compilation for O2, but still works for all my use …
> Unify TPC constants as far as possible

- Detectors/Base/CMakeLists.txt
- Detectors/Base/include/DetectorsBase/DCAFitter.h
- Detectors/Base/src/DCAFitter.cxx
- Detectors/Base/src/DetectorsBaseLinkDef.h
- Detectors/Base/test/testDCAFitter.cxx
DCA of 2 AliExternalTrackParam tracks, some documentation files on https://alice.its.cern.ch/jira/browse/O2-712
Supports both DCA (unweighted) and Chi2 (weighted DCA) minimization. See testDCAFitter for example of usage
Starts by finding analytical XY crossings (at most 2) and using them as seeds for non-linear minimization
(the track errors used for Chi2 are evaluated only once at these seeding points).
In case the PCA being fitted with one seed appears to be closer to alternative seed, the minimizaiton with
this seed is abandoned. In some cases 2 seeds may produce 2 distinct PCA candidates,
therefore one should check the DCAFitter::getNCandidates() result.
See testDCAFitter.cxx for example of calls
Files dcaMathFin.nb (dcaMathFinNoErr.nb) are Mathematica derivations of the chi2 (or DCA) …
> DCA minimizer for V0 finder [O2-712]

- Framework/Core/include/Framework/DataAllocator.h
> Default serialization method as 'none' for the raw buffer snapshot

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/ChannelMatching.h
- Framework/Core/include/Framework/OutputSpec.h
- Framework/Core/src/ChannelMatching.cxx
- Framework/Core/src/OutputSpec.cxx
Moving the implementation to the .cxx file as preliminary work
to make the OutputSpec support wildcards.
> DPL: refactor OutputSpec and ChannelMatching

- CCDB/CMakeLists.txt
> Disabling failing ccdb_api_test on MacOS

- Detectors/ITSMFT/ITS/simulation/CMakeLists.txt
- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/Detector.h
- Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/V3Services.h
- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
- Detectors/ITSMFT/ITS/simulation/src/ITSSimulationLinkDef.h
- Detectors/ITSMFT/ITS/simulation/src/V3Layer.cxx
- Detectors/ITSMFT/ITS/simulation/src/V3Services.cxx
Implementation of ITS Inner Barrel Support Wheels on Side C: this includes the wheels themselves (with all holes but without the plugs and nuts) and the steps on which the staves are placed (but still without the ruby spheres).
A new class named V3Services is introduced to hold the code of present and future services; its methods are called in Detector.cxx during the creation of geometry just after the Stave creation.
The V3Layer class was modified to avoid fake overlaps with the air containers of End Layer Connectors: these volume containers now are exactly tailored upon the real pieces.
> Implementation of ITS Inner Barrel Support Wheels on Side C

- Framework/Core/include/Framework/ConfigParamRegistry.h
- Framework/Core/include/Framework/runDataProcessing.h
This prints a better error message. Workflows simply have terminated
with "Unknown error while setting up workflow" when an option was requested
but not declared.
> Catch all std exceptions at the top level of DPL standalone driver

- Framework/Core/include/Framework/FairOptionsRetriever.h
With the next FairMQ stable release (1.4.x) we will rename the `FairMQProgOptions` class to `fair::mq::ProgOptions`.
The old name will still be available as `using FairMQProgOptions = fair::mq::ProgOptions`. However this breaks O2 compilation at the line changed in this PR, because of double definition:
```
DEBUG:O2:O2:0: In file included from ~/dev/alice/sw/SOURCES/O2/1.0.0/0/Framework/Core/src/DataProcessingDevice.cxx:16:
DEBUG:O2:O2:0: ~/dev/alice/sw/SOURCES/O2/1.0.0/0/Framework/Core/include/Framework/FairOptionsRetriever.h:21:7: error: using typedef-name 'using FairMQProgOptions = class fair::mq::ProgOptions' after 'class'
DEBUG:O2:O2:0:  class FairMQProgOptions;
DEBUG:O2:O2:0:        ^~~~~~~~~~~~~~~~~
DEBUG:O2:O2:0: In file included from …
```
> Use FairMQ-shipped forward-declaration for FairMQProgOptions when available

- Framework/Core/src/DataProcessingStatus.h
- Framework/Core/src/DataRelayer.cxx
- Framework/Core/test/test_ParallelPipeline.cxx
Substitute them with LOG(DEBUG) or O2_SIGNPOST where it makes sense.
> DPL: remove debug printouts

- CMakeLists.txt
This gets rids of false failure messages (even though non-fatal).
I also removed the CMake warnings for every excluded macro, since it was also spoiling the logs.
> Do not run excluded macro tests, instad of running them in non-fatal way

- Framework/Core/include/Framework/DataSpecUtils.h
- Framework/Core/src/DataSpecUtils.cxx
This will become more meaningful once we migrate to the new OutputSpec, but for
now it should allow QC to migrate away from accessing OutputSpec details.
> DPL: add DataSpecUtils::getOptionalSubSpec API

- Detectors/MUON/MID/Simulation/CMakeLists.txt
- Detectors/MUON/MID/Simulation/include/MIDSimulation/DigitsMerger.h
- Detectors/MUON/MID/Simulation/include/MIDSimulation/DigitsPacker.h
- Detectors/MUON/MID/Simulation/src/DigitsMerger.cxx
- Detectors/MUON/MID/Simulation/src/DigitsPacker.cxx
In the simulation we produce one ColumnData per hit, so that it is easier to associate the corresponding MC label.
However, the ColumnData must then be merged to mimic what happen in real life (sort of digits_to_raw).
The digit merger takes care of it as well as keeping the MC label in synch.
The merged (raw) output can then be packed and sorted according to the timestamp in order to mimic a timeframe. This is done by the sorter.
The two steps where mixed: they are now properly split.
> Split MID digits merger and packer

- Detectors/TRD/base/include/TRDBase/Digit.h
I don't know how this worked without that semicolon. It is maybe ok, but I prefer to keep consistency with the code.
> TRD Missing semicolon

- DataFormats/simulation/include/SimulationDataFormat/MCCompLabel.h
An assignment was used instead of a comparison in a nested condition
> Bug fix in MCCompLabel

- Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
Some elements of the MFT geometry have overlaps with the ITS Wrapper Volumes of Middle and Outer Layers. These cylinders are not real volumes, but simply containers made of air. Their dimensions were reduced to accommodate the MFT elements.
> Reduce ITS Wraper Volume dimensions to avoid fake overlaps with MFT

- GPU/Common/GPUDefGPUParameters.h
- GPU/GPUTracking/Base/GPUReconstructionCPU.cxx
- GPU/GPUTracking/Base/GPUReconstructionTimeframe.cxx
- GPU/GPUTracking/Base/GPUReconstructionTimeframe.h
- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/Merger/GPUTPCGMMerger.cxx
- GPU/GPUTracking/Merger/GPUTPCGMTrackParam.cxx
- GPU/GPUTracking/SliceTracker/GPUTPCStartHitsFinder.cxx
- GPU/GPUTracking/SliceTracker/GPUTPCTracker.cxx
- GPU/GPUTracking/SliceTracker/GPUTPCTracker.h
- GPU/GPUTracking/SliceTracker/GPUTPCTrackerDump.cxx
- GPU/GPUTracking/SliceTracker/GPUTPCTracklet.h
- GPU/GPUTracking/SliceTracker/GPUTPCTrackletSelector.cxx
- GPU/GPUTracking/Standalone/qconfigoptions.h
- GPU/GPUTracking/Standalone/standalone.cxx
- GPU/GPUTracking/Standalone/tools/testCL.sh
- GPU/GPUTracking/Standalone/utils/qconfig.h
- GPU/TPCFastTransformation/TPCFastTransform.h
- Should never segfault when a buffer is exceeded, but always return with an error.
- Memory allocation on the CPU is no longer limited by the constants (will just allocate more if insufficient). (@shahor02 : Should be able to process arbitrary length time frames now, as long as nCl < 2 billion, and if there is enough memory. No need to change the constants any more).
- Overlaying TPC events into time frames now also works with cluster in native TPC coordinates (needed for running tpc conversion and compression).
- Fix a possible FPE (this wasn't seen within O2, so I guess we don't have a check for FPE there yet?)
> Fix TPC Tracking Buffer Allocation and Overflow Check + some other fixes

- DataFormats/Detectors/MUON/MID/include/DataFormatsMID/Cluster3D.h
- DataFormats/Detectors/MUON/MID/include/DataFormatsMID/Track.h
- DataFormats/Detectors/MUON/MID/src/Track.cxx
- Detectors/MUON/MID/Base/src/HitFinder.cxx
- Detectors/MUON/MID/Tracking/include/MIDTracking/Tracker.h
- Detectors/MUON/MID/Tracking/src/Tracker.cxx
- Detectors/MUON/MID/Tracking/test/testTracker.cxx
MID track stricture is simplified so that it can be used in DPL without a (time-consuming) serialisation
So that the output can be passed to DPL without time consuming serialization.
> Use only trivial types in tracker

- Detectors/ITSMFT/MFT/base/include/MFTBase/GeometryTGeo.h
- Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/ChipMappingMFT.h
- Detectors/ITSMFT/common/reconstruction/src/ChipMappingMFT.cxx
This is the MFT mapping connecting the sensor geometry used in the simulations with the read-out cabling and GBT formatting of the raw data. It is working with the template RawPixelReader in the same way as the ITS equivalent mapping. Because the sensor numbers of the MFT do not follow a regular pattern as in the case of ITS, a lot of them are pre-calculated and filled in arrays. The macro used to do this will come in a future commit. This mapping was checked with a simulation, coding digits to raw and decoding raw to digits, which are compared to the original ones.
> MFT: new read-out mapping to work with the latest raw data encoding

- Framework/Core/src/DataSamplingReadoutAdapter.cxx
When we have wildcards, it should be able to publish messages with any subSpec.
@Barthelemy
> Temporary fix for DataSamplingReadoutAdapter

- DataFormats/MemoryResources/test/test_observer_ptr.cxx
- Framework/Core/test/test_PtrHelpers.cxx
Because of doxygen's autolinking of references, all 'A' are displayed as
reference to a struct named 'A'.
TODO: we might want to do this on a higher level at some point
> Exclude test structures named 'A' from doxygen

- Framework/Core/CMakeLists.txt
Workflows have to be executed with command line option --run
The merging functionality would simply dump the configuration on std output
because of the connected log pipe.
> Make framework workflow unit tests running again

- Detectors/MUON/MID/Tracking/include/MIDTracking/Tracker.h
- Detectors/MUON/MID/Tracking/src/Tracker.cxx
- Detectors/MUON/MID/Tracking/test/bench_Tracker.cxx
- Detectors/MUON/MID/Tracking/test/testTracker.cxx
This method keeps all tracks instead of just the best one.
The method has a higher efficiency in events with large track multiplicity
(but it is slower and provides a larger number of fakes)
> Implement a second method to reconstruct tracks

- Detectors/MUON/MID/Base/CMakeLists.txt
- Detectors/MUON/MID/Simulation/CMakeLists.txt
- Detectors/MUON/MID/Simulation/include/MIDSimulation/MCLabel.h
- Detectors/MUON/MID/Simulation/include/MIDSimulation/TrackLabeler.h
- Detectors/MUON/MID/Simulation/src/MCLabel.cxx
- Detectors/MUON/MID/Simulation/src/TrackLabeler.cxx
- Detectors/MUON/MID/Simulation/test/testSimulation.cxx
- Detectors/MUON/MID/TestingSimTools/CMakeLists.txt
- Detectors/MUON/MID/TestingSimTools/include/MIDTestingSimTools/HitFinder.h
- Detectors/MUON/MID/TestingSimTools/include/MIDTestingSimTools/TrackGenerator.h
- Detectors/MUON/MID/TestingSimTools/src/HitFinder.cxx
- Detectors/MUON/MID/TestingSimTools/src/TrackGenerator.cxx
- Detectors/MUON/MID/Tracking/test/bench_Tracker.cxx
- Detectors/MUON/MID/Tracking/test/testTracker.cxx
- cmake/O2Dependencies.cmake
This PR consists of 5 separate but closely related commits:
- the first one adds the track labeler
- the second to fourth are needed for the tests
- the last commit adds the tests for both the track labeler and the cluster labeler
The tests are meant to check the correct label propagation throughout the full simulation/reconstruction chain.
They are in between unit_tests and integration tests.
Please do not squash the 5 commits.
> Track labeler for MID and corresponding tests

- Detectors/ITSMFT/MFT/base/include/MFTBase/PowerSupplyUnit.h
- Detectors/ITSMFT/MFT/base/src/PowerSupplyUnit.cxx
The TNamed is removed (override as well) in PowerSupplyUnit class
> removing TNamed in PSU

- Framework/Core/include/Framework/ASoA.h
- Framework/Core/include/Framework/AnalysisDataModel.h
- Framework/Core/include/Framework/AnalysisTask.h
- Framework/Core/test/test_AnalysisTask.cxx
This will allow us to derive the requested quantities from the
signature of the AnalysisTask::process method in the long run.
For now, it makes the code generating the DataProcessor a bit less
hardcoded.
> DPL analysis: allow adding metadata for SoA tables

- Framework/Core/README.md
- Framework/Logger/include/Framework/Logger.h
- Framework/Logger/test/unittest_Logger.cxx
The former now has printf-like syntax, the latter uses the native
python / fmt syntax.
> Logger: distinguish between LOGF and LOGP

- Framework/Utils/include/DPLUtils/RootTreeReader.h
- Framework/Utils/test/test_RootTreeReader.cxx
After commit 70c6e7b8c78b605665b90794a05caeb60ae8cfd0 it was not possible
to have a single argument like the publishing mode at the end of the argument pack.
> Bugfix RootTreeReader argument parsing

- GPU/Common/FlatObject.h
Correct destructor was somehow lost when we merged the changes for the flat object used for material lut.
> Fix memory leak

- Framework/Core/include/Framework/AnalysisDataModel.h
- Framework/Core/test/test_Kernels.cxx
This allows easily binding secondary objects to their primary
counterparts.
> DPL Analysis: rename ID columns to their target tables

- dependencies/O2Dependencies.cmake
- macro/CMakeLists.txt
* Clang requires LLVM on some platforms, so if LLVM is not there,
this will fail.
* We need to protect against usage of simulation packages when
Geant4 is not there.
* ROOT needs to be at least v6.16.00
> CMake migration: fix a few glitches

- Framework/Logger/CMakeLists.txt
@ktf @aphecetche : fmt is now an alidist dependency, and CMake finds fmt, but fmt::fmt was not added to the Logger. Consequently, it was not used, and even breaking systems which have fmt system-wide, because the header is available, but it is not linked.
> Fix missing fmt dependency

- GPU/Common/CMakeLists.txt
For GPUCommon, include directories are different for the build tree and the install tree
> Fix GPUCommon target include directories

- macro/CMakeLists.txt
- macro/run_digi2raw_mft.C
- macro/run_rawdecoding_mft.C
This is a clone of the corresponding macro for the ITS, adapted to the MFT read-out.
> MFT: add macro for conversion digits to raw

- Framework/Core/include/Framework/CustomWorkflowTerminationHook.h
- Framework/Core/include/Framework/runDataProcessing.h
This defines a function callback `OnWorkflowTerminationHook` with signature
`void (const char*)` and allows to set the hook using the `customize` mechanism
of DPL workflows. The callback hook is invoked just before processes terminate.
The hook is invoked for all childs and the main driver, the id string is passed
as parameter to customize the callback action. For the main driver, the nullptr
is passed.
This is a simple mechanism to allow for deterministic actions at the end of the workflow or parts of it.
An example use case is [O2-778] https://alice.its.cern.ch/jira/browse/O2-778
> Adding customizable hook to be executed on workflow termination

- Framework/Utils/CMakeLists.txt
- Framework/Utils/test/test_RootTreeWriterWorkflow.cxx
Checking the file content in the destructor of a static object turned out to
be executed multiple times because every process has the static object. Using
now a custom hook executed at workflow termination to ensure deterministic
execution.
Re-enable RootTreeWriterWorkflow unit test
> [O2-778] Rework test_RootTreeWriterWorkflow

- Detectors/TPC/workflow/CMakeLists.txt
- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- GPU/GPUTracking/Base/GPUTPCGPURootDump.h
- GPU/GPUTracking/CMakeLists.txt
- GPU/GPUTracking/SliceTracker/GPUTPCClusterErrorStat.h
- GPU/GPUTracking/Standalone/config_common.mak
- GPU/GPUTracking/Standalone/display/GPUDisplay.cpp
- GPU/GPUTracking/Standalone/display/GPUDisplay.h
- GPU/GPUTracking/Standalone/display/GPUDisplayInterpolation.cpp
- GPU/GPUTracking/Standalone/display/GPUDisplayKeys.cpp
- GPU/GPUTracking/Standalone/display/GPUDisplayQuaternion.cpp
- GPU/GPUTracking/Standalone/qa/GPUQA.h
- GPU/GPUTracking/Standalone/qa/genEvents.h
- GPU/GPUTracking/Standalone/standalone.cxx
- Don't fail if GLEW is available but OpenGL version to old.
- Propagate availability to TPC workflow.
- Rename defines to make clear this is about GPU Standalone stuff.
> Some fixes for GPU TPC Tracking visualization

- Detectors/TPC/workflow/src/CATrackerSpec.cxx
- GPU/GPUTracking/Base/GPUDataTypes.h
- GPU/GPUTracking/DataCompression/GPUTPCCompressionKernels.h
- GPU/GPUTracking/Global/GPUChainTracking.cxx
- GPU/GPUTracking/Merger/GPUTPCGMMerger.h
- GPU/GPUTracking/Standalone/display/GPUDisplay.cpp
- GPU/GPUTracking/Standalone/display/GPUDisplay.h
- GPU/GPUTracking/Standalone/display/GPUDisplayKeys.cpp
- GPU/GPUTracking/Standalone/qa/GPUQA.cpp
- GPU/GPUTracking/Standalone/qa/GPUQA.h
- GPU/GPUTracking/Standalone/standalone.cxx
First version of TPC resolution and efficiency QA.
- Supports imported Run 2 Raw / MC data and Run 3 MCTruthContainer and o2sim.log MC trees.
- So far runs only with the tracking, next PR should add standalone capabilities to run on std::vector<trackTPC>
- Some features still disabled for O2, but needs more other work first.
> Adapt TPC Standalone QA to process O2 MC labels + general QA/Display improvements

- Detectors/ITSMFT/ITS/tracking/cuda/CMakeLists.txt
- Framework/DebugGUI/CMakeLists.txt
- GPU/GPUTracking/Base/cuda/CMakeLists.txt
- dependencies/CMakeLists.txt
- dependencies/FindO2GPU.cmake
- dependencies/O2CompileFlags.cmake
This brings back Compile and link flags lost during the CMake migration, in particular the -Wl,--no-undefined, which was missing.
Along that, it also fixes some library dependencies that turned out missing indeed.
Not 100% sure this is all modern CMake,
> Bring back compile and link flags lost in CMake migration

- Detectors/Base/src/DCAFitter.cxx
In case due to the round-of error the determinant of quadr.equation is <0 while 2 roots are expected
we assume that the circles are barely touching (i.e. 2 crossings very close to each other).
In this case we fall-back to solution with the single point in between the circles
> Fix: treat the case of barely touching circles

- Framework/Core/CMakeLists.txt
The workflow test programs are no boost unit tests, flag NO_BOOST_TEST was not
set in #2172. The inserted `--` was causing the test programs to ignore all
command line args, and without option `--run` they all dumped the configuration
instead of running the test.
https://github.com/AliceO2Group/AliceO2/blob/a341176bb96549e2d37ce696cdb7c68d14cd304b/cmake/O2AddTest.cmake#L81
> [WIP] Bugfix after CMake modernization #2172, run workflow tests again

- Framework/Core/include/Framework/DataAllocator.h
- Framework/Core/include/Framework/MessageContext.h
- Framework/Core/include/Framework/TypeTraits.h
- Framework/Core/test/test_DataAllocator.cxx
- Framework/Core/test/test_TypeTraits.cxx
@ktf, this implements the basic support for sending vectors of messageable type through the `DataAllocator::make` API
Only to be merged after #1970
TODO:
In a separate PR the InputRecord API can be adapted, for the moment `span` needs to be used to extract the array of elements.
> DPL support for resizable vector  through make<std::vector<messageable_type>> 

- CCDB/CMakeLists.txt
- CCDB/include/CCDB/Backend.h
- CCDB/include/CCDB/BackendOCDB.h
- CCDB/include/CCDB/BackendRiak.h
- CCDB/include/CCDB/CcdbApi.h
- CCDB/src/CCDBLinkDef.h
As discussed in AliceO2Group/AliceO2#2209
loading of the library libO2CCDB fails
with a segfault due to implicit include
of boost/container/detail/pair.hpp via
FairMQ. All instances of FairMQ includes
are hidden from rootcling via include
protections as well as the function
declarations which utilize FairMQ
objects.
> Fix autoloding segfault

- Framework/Core/include/Framework/DataMatcherWalker.h
- Framework/Core/src/DataDescriptorMatcher.cxx
This introduces an helper which is able to do a deep
first walk of a DataDescriptorMatcher tree.
This also reimplements the operator<< for a DataDescriptorMatcher tree
using such a walker. This will also allow us to customise
the display of the matcher, or to properly serialise it using
RapidJSON.
> DPL: add generic walker for DataDescriptorMatcher

- Detectors/ITSMFT/ITS/tracking/include/ITStracking/Configuration.h
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/IOUtils.h
- Detectors/ITSMFT/ITS/tracking/src/IOUtils.cxx
- Detectors/ITSMFT/ITS/tracking/src/VertexerTraits.cxx
A function to generate simple clusters corresponding to straight lines starting from the point (0,0,0). Improvements will be added later.
> Add a function to generate simple clusters and fix fake pileup

- Detectors/TRD/base/include/TRDBase/Digit.h
https://alice.its.cern.ch/jira/browse/O2-734
@sawenzel, we should try this simple change and see if it outperforms the current version of the digitizer. On the mean time, I am also finalizing the version with flat structures only, but it shouldn't be better than this.
> [WIP] TRD digitizer unordered_map instead of map (O2-734)

- Framework/Core/include/Framework/DataDescriptorMatcher.h
- Framework/Core/include/Framework/DataSpecUtils.h
- Framework/Core/include/Framework/InputSpec.h
- Framework/Core/include/Framework/OutputSpec.h
- Framework/Core/src/DataSpecUtils.cxx
- Framework/Core/src/InputSpec.cxx
- Framework/Core/src/OutputSpec.cxx
- Framework/Core/src/WorkflowHelpers.cxx
- Framework/Core/src/WorkflowSerializationHelpers.cxx
- Framework/Core/test/test_WorkflowSerialization.cxx
- Framework/Core/test/unittest_DataSpecUtils.cxx
- Framework/TestWorkflows/CMakeLists.txt
- Framework/TestWorkflows/src/o2OutputWildcardWorkflow.cxx
e2e7820 is in principle all is needed to have OutputSpec have a wildcard on the subSpecification. Not tested yet.
Notice this depends on #2057...
> DPL OutputSpec wildcards

- Framework/Core/CMakeLists.txt
- Framework/Core/include/Framework/DataProcessor.h
- Framework/Core/include/Framework/DeviceSpec.h
- Framework/Core/include/Framework/DispatchPolicy.h
- Framework/Core/include/Framework/MessageContext.h
- Framework/Core/include/Framework/runDataProcessing.h
- Framework/Core/src/DataAllocator.cxx
- Framework/Core/src/DataProcessingDevice.cxx
- Framework/Core/src/DataProcessor.cxx
- Framework/Core/src/DeviceSpecHelpers.cxx
- Framework/Core/src/DeviceSpecHelpers.h
- Framework/Core/src/DispatchPolicy.cxx
- Framework/Core/src/DriverInfo.h
- Framework/Core/src/runDataProcessing.cxx
- Framework/Core/test/test_StaggeringWorkflow.cxx
`SenderPolicy` describes on per-device basis when completed objects are sent, either at the end of computation - the default and current behavior - or immediately when ready. Depending on the `SenderPolicy` operation, the `DataProcessingDevice` configures the `MessageContext` with a sender callback. The sender policy can be customized in the usual DPL manner.
`MessageContext` has been extended to create context objects embedded into a scope handler. The context object is scheduled, when the handler goes out of scope in the user code. Currently, the `DataAllocator::snapshot` API method uses this feature.
This PR will be the foundation for refactoring the digitizer workflow and to solve the memory problems with large data sets. Enabling the prompt sending also for `DataAllocator::make` …
> Introducing SenderPolicy to DPL processors

- Detectors/GlobalTrackingWorkflow/tofworkflow/src/RecoWorkflowSpec.cxx
Some code checker warnings have been introduced in 6065822182f888769126ccd11e7f5dc1433900ce
```
========== List of errors found ==========
/mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_o2checkcode_o2/0/Detectors/GlobalTrackingWorkflow/tofworkflow/src/RecoWorkflowSpec.cxx:109:63: error: use nullptr [modernize-use-nullptr]
/mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_o2checkcode_o2/0/Detectors/GlobalTrackingWorkflow/tofworkflow/src/RecoWorkflowSpec.cxx:109:69: error: use nullptr [modernize-use-nullptr]
/mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_o2checkcode_o2/0/Detectors/GlobalTrackingWorkflow/tofworkflow/src/RecoWorkflowSpec.cxx:109:75: error: use nullptr [modernize-use-nullptr]
```
> Fixing code checker errors

- Detectors/TPC/simulation/include/TPCSimulation/DigitContainer.h
- Detectors/TPC/simulation/src/Digitizer.cxx
@wiechula @a-mathis Digitizing 200 PbPb events I consistently get crash in TPC Digitizer. What happens is that for primary electron with max.drift time coming from hit with very large hit time (28us) the ``DigitContainer::mEffectiveTimeBin`` exceeds the size of mTimeBins container, leading to seg.viol. in addDigit. 
This PR increases the initial size of mTimeBins from 600 to 700 bins, and skips digitization of electrons with ``(drift_time + hit_time)*ZbinWidth + nShapedPoints > DigitContainer::mTimeBins.size()``.
With 700 bins this is equivalent to rejection of hits with time>138 us (e.g. with nominal drift time ~92us 
hitTimes > 44us will be rejected).
This plot shows partile creation times for 200 PbPb event: probability of hitTimes > 30 should be below 10^-7 so we don't lose mush with …
> Skip digitizing electrons with very large times

- Framework/Core/include/Framework/DataAllocator.h
Obviously there was a glitch which I did not expect when refactoring `DataAllocator::snapshot`. And it seems,
objects have been unnecessarily ROOT serialized all the time, so at least we found this. 
PR #2216 with Commit 68f6b4df267201cbf5e2d6b2732ed822ce1599d6 changed the precedence
order of serialization methods for types which are both messageable and ROOT serializable,
now the unserialized transmission is preferred.
This is a temporary messure until InputRecord has been adapted.
> Reverting PR #2216 because the InputRecord API is not consistent for all cases

- Framework/Core/src/AODReaderHelpers.cxx
COLLISION, not COLLISIONS. A better solution would be to use `AnalysisDataModel.h` to get the names.
> DPL Analysis: fix typo in collection name

- DataFormats/Detectors/EMCAL/src/DataFormatsEMCALLinkDef.h
Missing colon in pragma declaration for digit
and cell class creating problems with dictionary
generation.
> [EMCAL-551] Fix typo in DataFormatsEMCAL LinkDef

- Detectors/ITSMFT/MFT/base/include/MFTBase/Constants.h
The constants giving the positions of the two faces of the fourth disk were wrong by 3mm
(thanks to Andreas and Alicia for spotting this).
> MFT: fix a bug in position of disk 4

- Framework/Logger/CMakeLists.txt
- Framework/Logger/src/Logger.cxx
- GPU/Common/GPUCommon.cxx
I guess this is the propper fix for the issue reported by @mconcas in #2244. (See #2236 and #2245 for reference)
> Fix installation of header files of Framework/Logger after CMake migration

- Framework/Core/src/DataSamplingReadoutAdapter.cxx
The change introduced in 53e08fef5af6c094cb88c9ea49cefd22491320aa was a bit too soon, since QC is not using wildcards for subSpecs yet. This brings back the previous behaviour (assigning the specified subSpec), while giving the possibility to assign the linkID if wildcards are used.
@vascobarroso
> Fix DataSamplingReadoutAdapter's subSpec assignement

- Framework/DebugGUI/src/HandMadeMath.h
- Framework/DebugGUI/src/sokol_gfx.h
@ktf : Your reverted the clang-tidy fixes in #2046, which means that now again everything that includes your DebugGUI headers will fail the CI due to the clang-tidy violations. Right now this affects #2243 .
This PR (hopefully) fixes it properly, keeping the C-stye include for C and moving the C++ include out of the namespace (+ it fixes the sokol header for the case with assertions enabled).
Could you please have a look.
> Fix clang-tidy again in DebugGUI (and with assertions enabled)

- dependencies/Findcub.cmake
@ktf : I think it is just this bogus fatal message. When CUB_FOUND is set to false, we should not bail out with a FATAL. Don't know where it came from, I guess it was added for debugging during the CMake migration.
> Remove fatal debug message left from CMake migration

- dependencies/FindROOT.cmake
Missing target does not only happen on
mac but also on other platforms (i.e
Ubunutu 18.04) and is breaking the compilation
due to undefined link lvdt.
> [CMake] Add vdt target whenever it is missing

- Common/SimConfig/src/ConfigurableParam.cxx
- Common/SimConfig/src/ConfigurableParamHelper.cxx
- Common/SimConfig/src/SimConfigLinkDef.h
- Detectors/TPC/base/src/TPCBaseLinkDef.h
We use introspection features of ROOT to find out
possible constants of enums in the parameter system.
Since ROOT6-18, ROOT has problems providing these constants.
It appears that ROOT, in our situation, is no longer autogenerating/autoloading
the dictionaries for the enum types as it used to do in ROOT6-16.
Also, the TDataMethod::GetOptions is no longer reliably returning the list
of EnumConstants.
This commit addresses these problems, by
a) generating dictionaries for all enum types used in parameters
b) using TEnum::GetEnum() functionality instead of TDataMethod::GetOptions()
for the introspection part
Fixes https://alice.its.cern.ch/jira/browse/O2-801
> Fix enum introspection problems with ROOT6.18

- Detectors/TPC/calibration/SpacePoints/CMakeLists.txt
- Detectors/TPC/calibration/SpacePoints/include/SpacePoints/SpacePointsCalibParam.h
- Detectors/TPC/calibration/SpacePoints/include/SpacePoints/TrackInterpolation.h
- Detectors/TPC/calibration/SpacePoints/include/SpacePoints/TrackResiduals.h
- Detectors/TPC/calibration/SpacePoints/src/SpacePointCalibLinkDef.h
- Detectors/TPC/calibration/SpacePoints/src/SpacePointsCalibParam.cxx
- Detectors/TPC/calibration/SpacePoints/src/TrackInterpolation.cxx
- Detectors/TPC/calibration/SpacePoints/src/TrackResiduals.cxx
- ITS-TPC-TOF tracks are refitted w/o TPC information and the TPC cluster residuals w.r.t. the refitted tracks are stored in a specified data structure
- ITS-TPC tracks can also be used, in this case an extrapolation of the ITS only tracks is performed
- Some track quality cuts have been added, but these are still to be tuned
- The output of the TrackInterpolation class needs to be converted before it can be used as input for TrackResiduals
- This is work in progress!
> Prototype for ITS-TOF trk interpol. for TPC calib

- Detectors/TRD/simulation/include/TRDSimulation/Digitizer.h
- Detectors/TRD/simulation/src/Digitizer.cxx
I noticed that we were systematically loosing electrons
in the signal generation. The reason is that the locC position
is smeared by diffusion and that each electrons applied also
a linear shift.
Further, the diffusion was not independent for each electron as the locC
was merely reused in its last state.
This commit fixes this problem by making the diffusion process start always from
the original hit coordinates. The final coordinates are now
specific/local to each electrion.
> Fix systematic drift bug in TRD digitization

- Detectors/ITSMFT/ITS/tracking/cuda/include/ITStrackingCUDA/VertexerTraitsGPU.h
- Detectors/ITSMFT/ITS/tracking/cuda/src/VertexerTraitsGPU.cu
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/Configuration.h
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/Tracklet.h
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/Vertexer.h
- Detectors/ITSMFT/ITS/tracking/include/ITStracking/VertexerTraits.h
- Detectors/ITSMFT/ITS/tracking/src/Vertexer.cxx
- Detectors/ITSMFT/ITS/tracking/src/VertexerTraits.cxx
- macro/run_primary_vertexer_ITS.C
- macro/run_trac_ca_its.C
These changes are mainly focused on the CPU version, but in general will made debug/mc validation easier and seamlessly portable to GPU version, which as told before will have a refresh too.
More specifically:
- Tracklets are now MC-validated in dedicated function -> no more mention of MC truth in combinatorial code. My plan is to keep the mc-validation on CPU also for GPU vertexer
- Debug boilerplate has been completely dismissed in favour of few utilities heavily relying on the `TreeStreamRedirector` class, as @shahor02 once suggested me to do (thanks!).
Not sure about the formatting, will update and remove the WIP tag upon green light from travis
> [ITS][Vertexer-CPU] Separate montecarlo validation and improve debug

- Detectors/EMCAL/base/include/EMCALBase/Geometry.h
- Detectors/EMCAL/simulation/src/Detector.cxx
Sampling fraction has been applied previously in the digitization
code. As the sampling fraction depends on the MC engine and the
digitizer has no knowledge about the MC engine it has to be applied
during the hit generation.
> [EMCAL-599] Initialize and apply sampling fraction to light yield

- Detectors/ITSMFT/ITS/workflow/include/ITSWorkflow/ClustererSpec.h
- Detectors/ITSMFT/ITS/workflow/src/ClustererSpec.cxx
- Detectors/ITSMFT/MFT/workflow/include/MFTWorkflow/ClustererSpec.h
- Detectors/ITSMFT/MFT/workflow/include/MFTWorkflow/RecoWorkflow.h
- Detectors/ITSMFT/MFT/workflow/src/ClustererSpec.cxx
- Detectors/ITSMFT/MFT/workflow/src/RecoWorkflow.cxx
- Detectors/ITSMFT/MFT/workflow/src/mft-reco-workflow.cxx
@davidrohr this fixes the "Index out of bounds" messages.
@bovulpes Fixing the same problem in the MFT, I noticed that your recoflow has no option to skip the MC labels propagation. I've fixed this in the flow options and propagated to MFT ClustererSpec, but please propagate it also to other MFT recoflow devices.
> Skip compact clusters creation in absence of TopoDictionary 

- GPU/TPCFastTransformation/CMakeLists.txt
Some defines were copied to TPCFastTransform to steer the namespace name, which was added to avoid symbol collisions between O2 and AliRoot when O2 is built v.s. AliRoot. Unfortunately, this breaks the ROOT dictionary for the TPC Fast Transform object.
This is a first simple attempt to fix it, not to be merged yet, must be double-checked.
@sgorbuno : Could you have a look if this works for you?
> Don't set GPUCA_O2_LIB etc for TPCFastTransform, it's only for GPUTracking

- Detectors/TRD/base/include/TRDBase/TRDCalPadStatus.h
- Detectors/TRD/base/include/TRDBase/TRDCalSingleChamberStatus.h
Hi @jolopezl 
This PR fixes the compilation warnings
````
Warning: Unused class rule: o2::dataformats::MCTruthContainer < o2::trd::MCLabel>
Warning: Unused class rule: o2::trd::TRDCalPadStatus
Warning: Unused class rule: o2::trd::TRDCalSingleChamberStatus
````
leading to error in the digitization:
````
[31009:TRDDigitizer]: IncrementalExecutor::executeFunction: symbol '_ZN2o211dataformats16MCTruthContainerINS_3trd7MCLabelEE5ClassEv' unresolved while linking [cling interfac
e function]!
[31009:TRDDigitizer]: You are probably missing the definition of o2::dataformats::MCTruthContainer<o2::trd::MCLabel>::Class()
[31009:TRDDigitizer]: Maybe you need to load the corresponding shared library?
````
1) dictionary generation for o2::dataformats::MCTruthContainer<o2::trd::MCLabel> was ignored since …
> Fixes for TRDBase dictionary generation:

- Framework/Core/src/DataSamplingReadoutAdapter.cxx
The field `id` has become deprecated and it was replaced with two less ambigious fields - `timeframeId` and `blockId`. The latter preserves the original behaviour, producing stricly monotonic sequence.
> Follow the DataBlockHeader changes in DS Readout Proxy

- Detectors/Base/include/DetectorsBase/Detector.h
- Detectors/Base/src/Detector.cxx
- Detectors/FIT/FV0/simulation/src/Detector.cxx
- Detectors/ITSMFT/MFT/simulation/src/Detector.cxx
We cannot rely on the TGeoVolume::GetNumber() function to get the volume
id. This seems to work with Geant3 but not for Geant4.
This commit is offering a new API that the developer/user can use to
register a sensitive volume and to query the volume ID from VMC behind
the scenes.
Application to MFT and V0 which where using GetNumber.
Fixes https://alice.its.cern.ch/jira/browse/O2-814
> Interface to register sensitive volumes and to cache its VMC VolID

- Detectors/EMCAL/base/src/Geometry.cxx
Default and named geometry were mixed up.
> Bugfix: Default geometry not handled for empty name

- Common/MathUtils/include/MathUtils/Utils.h
@MichaelLettrich : This should fix the warnings
@sgorbuno : apparently some gcc versions cause false alarms for lambdas function parameters shadowing variables.
> Fix compile-warnings (even though false alarms) with some GCC versions

- dependencies/FindFairRoot.cmake
- dependencies/Findms_gsl.cmake
- dependencies/Findpythia.cmake
- dependencies/Findpythia6.cmake
- dependencies/O2Dependencies.cmake
- dependencies/O2RecipeAdapter.cmake
- dependencies/O2TestsAdapter.cmake
Extract the test adapter (that will stay) from the recipe adapter
(that will go away at some point).
Make a couple of find modules work with the environment version of the
<PACKAGE>_ROOT cmake variables, so they will work when the
corresponding variable will be removed from command line used in the
o2.sh alidist recipe (the numerous -Dxxx_ROOT= lines)
> [AliRoot-8326] Preparation work for the removal of the O2RecipeAdapter.

- Framework/Core/include/Framework/Dispatcher.h
- Framework/Core/src/Dispatcher.cxx
DataHeader and DataProcessingHeader cannot be forwarded, as they are generated by the framework anyway and we want to avoid having two headers of the same type in the Stack.
@mkrzewic Is there a more efficient and elegant way to do this? I am also not sure if each `std::move` actually helps to elide copying.
> [QC-84] Forward all non-framework headers in Dispatcher

- Detectors/EMCAL/calib/macros/GainCalibrationFactors_CCDBApiTest.C
- Detectors/EMCAL/calib/macros/GainCalibrationFactors_CalibDBTest.C
- Detectors/EMCAL/calib/macros/TempCalibrationParams_CCDBApiTest.C
- Detectors/EMCAL/calib/macros/TempCalibrationParams_CalibDBTest.C
- Detectors/EMCAL/calib/macros/TimeCalibrationParams_CCDBApiTest.C
- Detectors/EMCAL/calib/macros/TimeCalibrationParams_CalibDBTest.C
Using a timestamp in the range of validity of the Read/Write operations in the CCDB
> [EMCAL-575, EMCAL-578, EMCAL-581] Using a timestamp in the range of validity

- Detectors/EMCAL/calib/macros/BadChannelMap_CCDBApitest.C
- Detectors/EMCAL/calib/macros/BadChannelMap_CalibDBtest.C
As the CCDB server now support queries within the
time range the test has been adapted to use a time
stamp within the time range.
> [EMCAL-571] Use time stamp within time range for read test

- dependencies/Findms_gsl.cmake
No need to have a fatal if it is not found and it is not required. If it is required, the call to find_package should indicate it.
> Fix Findms_gsl.cmake

- Detectors/EMCAL/base/include/EMCALBase/Geometry.h
- Detectors/EMCAL/base/include/EMCALBase/GeometryBase.h
- Detectors/EMCAL/base/src/Geometry.cxx
Add handling for invalid supermodule ID. Used in
Geometry::GetSMType(int supermodule), but could
also be used elsewhere.
In addition:
- Documentation of existing exception in GeometryBase
- Minor cleanup in Geometry
> [EMCAL-603] Add exception for invalid supermodule ID

- Utilities/Mergers/CMakeLists.txt
There has been an occasional problem with the generation of libO2Mergers.rootmap
rootcling_wrapper.sh returned with non-zero value without any further error message.
It turned out that more header files in cmake configuration and LLinkDef  have been
inconsistent already in the original commit 7e233ec388d2b29cb05bdb3f53fd1d21b9e9c801
> Fixing the list of headers for libO2Mergers.rootmap

- CCDB/CMakeLists.txt
- CCDB/README.md
- CCDB/include/CCDB/CCDBTimeStampUtils.h
- CCDB/include/CCDB/CcdbApi.h
- CCDB/src/CCDBTimeStampUtils.cxx
- CCDB/src/CcdbApi.cxx
- CCDB/test/testCcdbApi.cxx
CcdbApi: new features and sanitizing
This commit adds the following (sometime prototypic) new functionality to CcdbApi:
* ability to write/retrieve any arbitrary class T (having a ROOT
dictionary) to the CCDB (via the TMemFile) mechanism
- the function is offered next to existing API for the moment
- a unit test checking this functionality was added
* ability parse and return the recursive subfolder structure inside the CCDB
* ability to generate a local snapshot of the CCDB (given some top level path and timestamp)
- checked in unit test
* ability to init the CCDB from the snapshot in order to serve cases when there
is no network connection
- works only with the new template<T> API for the moment
In addition, this commit sanitizes existing code a bit:
* apply const correctness
* pass …
> CcdbApi: new features and sanitizing

- Detectors/TPC/qc/CMakeLists.txt
- Detectors/TPC/qc/include/TPCQC/PID.h
- Detectors/TPC/qc/src/PID.cxx
- Detectors/TPC/qc/src/TPCQCLinkDef.h
- Detectors/TPC/qc/test/test_PID.cxx
The idea is to seprate the logic of the QC analysis from the processing.
The logical part of the analysis, histogram filling, cuts etc. should
stay in O2. Those classes will then be used in the QC tasks.
> Add first example for TPC QC analysis

- Framework/Core/include/Framework/InputRecord.h
- Framework/Core/include/Framework/TypeTraits.h
- Framework/Core/test/test_InputRecord.cxx
- Framework/Core/test/test_TypeTraits.cxx
Using `constexpr if` for type dependent code branches
TODO:
> [WIP] DPL: simplify input record API

- Framework/Core/include/Framework/InputRecord.h
- Framework/Core/test/test_InputRecord.cxx
Compilation problem on macos is fixed. Aparently clang could not handle the
recursive call, split into two functions, selected via SFINAE idiom.
> Re-enable PR #2345 "Simplifying InputRecord API"

- Framework/Core/include/Framework/DataAllocator.h
Finally activating #2216 again. InputRecord API can now handle unserialized vectors of messageable types.
This reverts commit 13a5d105dc0ed7c37be695021d5de97cb00a4e6b.
> Re-enable "Streamline DPL Allocator::snapshot" after update of InputRecord
